### ISSUE TITLE
L2TP

### ISSUE THREAD

**Issue by gameb0y** [henrypp/simplewall#10]
i cant connect l2tp server behind wfptool

i Added port 500, 4500 and 5000

**Comment by hesss5** [comment]
add 1701

**Comment by gameb0y** [comment]
added 1701 but not working :/

**Comment by hesss5** [comment]
i use vpntest.pbk
log show me
System (NT AUTHORITY\SYSTEM) [UDP:router ip:1701] (wfptool - Block) Local
System (NT AUTHORITY\SYSTEM) [UDP:vpnip:1701] (wfptool - Block) Remote
i only add  port 1701 in **Special rules**  and it will connect (outbound)
after that log show me this
C:\windows\system32\svchost.exe (NT AUTHORITY\NETWORK SERVICE) [TCP:10.*.*.*:80] (wfptool - Block) Remote
C:\windows\system32\svchost.exe (NT AUTHORITY\NETWORK SERVICE) [TCP:10.*.*.*:50308] (wfptool - Block) Local
C:\windows\system32\svchost.exe (NT AUTHORITY\NETWORK SERVICE) [TCP:0.0.0.0] (wfptool - Block) Remote
C:\windows\system32\svchost.exe (NT AUTHORITY\NETWORK SERVICE) [TCP:0.0.0.0] (wfptool - Block) Local
but still connected and working very well

**Comment by henrypp** [comment]
1.4.4 added L2TP/IPsec to the system rules
