### ISSUE TITLE
Winget not working while simplewall filters enabled

### ISSUE THREAD

**Issue by samokosik** [henrypp/simplewall#1001]
Hello.
when I enable filters on simplewall, winget package manager stops working - it cannot download apps.
I made sure that these are enabled:
Apps: appinstallercli.exe
Services: BITS, DoSvc, UsoSvc
UWP Apps: App Installer

svchost.exe is disabled

Screenshots:
https://i.imgur.com/ums5fOR.png
https://i.imgur.com/B5SS3JV.png
https://i.imgur.com/B5SS3JV.png

I followed starting services mentioned here and not blocklisting windows update: https://github.com/henrypp/simplewall/issues/988
None helped

Thank you

**Comment by samokosik** [comment]
![image](https://user-images.githubusercontent.com/73645764/131215955-e3bec7f0-2d02-4580-bea5-2d801bf1d5ce.png)
here is the error winget shows

**Comment by henrypp** [comment]
All info in packets log.

Dupl. #988
