### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by sieveLau** [henrypp/simplewall#1004]
Version 3.4 and newer ones crash at startup with error message: _The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s. (0xC0000005)_.

Rolling back to 3.3.5 temporarily works.

System: Windows 10 Pro 21H1 (19043.1052) 64bits

**Comment by sieveLau** [comment]
crashdump file:
[simplewall-1630171036.zip](https://github.com/henrypp/simplewall/files/7071143/simplewall-1630171036.zip)

**Comment by henrypp** [comment]
duplicate of #995
