### ISSUE TITLE
The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s. (0xC0000005)

### ISSUE THREAD

**Issue by helpfulBrother** [henrypp/simplewall#1005]
After updating to latest version of simple wall the app no longer loads and I receive this error.

Windows 10 Enterprise
Version : 20H2
OS Build : 19042.1165

The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s. (0xC0000005)

![image](https://user-images.githubusercontent.com/44999712/131271245-75e78ee4-f676-472b-bffc-bfb16eb8c4f1.png)

**Comment by helpfulBrother** [comment]
Reverted back to v3.4.1 and life is good again.

**Comment by henrypp** [comment]
This is dupl. #995 and now fixed
