### ISSUE TITLE
Incorrectly created rule - IP range:port

### ISSUE THREAD

**Issue by miro71** [henrypp/simplewall#1010]
simplewall v3.4.3
Windows 10 LTSC (x64)

User rule: 
Test IP range-port
TCP, Outbound
(remote) 192.168.1.100-192.168.1.200:445

Result:

		<item>
			<filterKey>{aaa29944-f8bc-482f-8a59-e4ae4c9936ea}</filterKey>
			<displayData>
				<name>simplewall</name>
				<description>User rule\Test IP range-port</description>
			</displayData>
			<flags numItems="1">
				<item>FWPM_FILTER_FLAG_PERSISTENT</item>
			</flags>
			<providerKey>{b0d553e2-c6a0-4a9a-aeb8-c752483ed62f}</providerKey>
			<providerData/>
			<layerKey>FWPM_LAYER_ALE_AUTH_CONNECT_V4</layerKey>
			<subLayerKey>{9fee6f59-b951-4f9a-b52f-133dcf7a4279}</subLayerKey>
			<weight>
				<type>FWP_UINT8</type>
				<uint8>11</uint8>
			</weight>
			<filterCondition numItems="2">
				<item>
					<fieldKey>FWPM_CONDITION_IP_REMOTE_ADDRESS</fieldKey>
					<matchType>FWP_MATCH_RANGE</matchType>
					<conditionValue>
						<type>FWP_RANGE_TYPE</type>
						<rangeValue>
							<valueLow>
								<type>FWP_UINT32</type>
								<uint32>192.168.1.100</uint32>
							</valueLow>
							<valueHigh>
								<type>FWP_UINT32</type>
								<uint32>192.168.1.200</uint32>
							</valueHigh>
						</rangeValue>
					</conditionValue>
				</item>
				<item>
					<fieldKey>FWPM_CONDITION_IP_PROTOCOL</fieldKey>
					<matchType>FWP_MATCH_EQUAL</matchType>
					<conditionValue>
						<type>FWP_UINT8</type>
						<uint8>6</uint8>
					</conditionValue>
				</item>
			</filterCondition>
			<action>
				<type>FWP_ACTION_PERMIT</type>
				<filterType/>
			</action>
			<rawContext>0</rawContext>
			<reserved/>
			<filterId>124078</filterId>
			<effectiveWeight>
				<type>FWP_UINT64</type>
				<uint64>12908160956973973504</uint64>
			</effectiveWeight>
		</item>

Expected result:

		<item>
			<filterKey>{aaa29944-f8bc-482f-8a59-e4ae4c9936ea}</filterKey>
			<displayData>
				<name>simplewall</name>
				<description>User rule\Test IP range-port</description>
			</displayData>
			<flags numItems="1">
				<item>FWPM_FILTER_FLAG_PERSISTENT</item>
			</flags>
			<providerKey>{b0d553e2-c6a0-4a9a-aeb8-c752483ed62f}</providerKey>
			<providerData/>
			<layerKey>FWPM_LAYER_ALE_AUTH_CONNECT_V4</layerKey>
			<subLayerKey>{9fee6f59-b951-4f9a-b52f-133dcf7a4279}</subLayerKey>
			<weight>
				<type>FWP_UINT8</type>
				<uint8>11</uint8>
			</weight>
			<filterCondition numItems="2">
				<item>
					<fieldKey>FWPM_CONDITION_IP_REMOTE_ADDRESS</fieldKey>
					<matchType>FWP_MATCH_RANGE</matchType>
					<conditionValue>
						<type>FWP_RANGE_TYPE</type>
						<rangeValue>
							<valueLow>
								<type>FWP_UINT32</type>
								<uint32>192.168.1.100</uint32>
							</valueLow>
							<valueHigh>
								<type>FWP_UINT32</type>
								<uint32>192.168.1.200</uint32>
							</valueHigh>
						</rangeValue>
					</conditionValue>
				</item>
				<item>
					<fieldKey>FWPM_CONDITION_IP_REMOTE_PORT</fieldKey>
					<matchType>FWP_MATCH_EQUAL</matchType>
					<conditionValue>
						<type>FWP_UINT16</type>
						<uint16>445</uint16>
					</conditionValue>
				</item>
				<item>
					<fieldKey>FWPM_CONDITION_IP_PROTOCOL</fieldKey>
					<matchType>FWP_MATCH_EQUAL</matchType>
					<conditionValue>
						<type>FWP_UINT8</type>
						<uint8>6</uint8>
					</conditionValue>
				</item>
			</filterCondition>
			<action>
				<type>FWP_ACTION_PERMIT</type>
				<filterType/>
			</action>
			<rawContext>0</rawContext>
			<reserved/>
			<filterId>124078</filterId>
			<effectiveWeight>
				<type>FWP_UINT64</type>
				<uint64>12908160956973973504</uint64>
			</effectiveWeight>
		</item>

Henry thanks for the excellent program!

**Comment by miro71** [comment]
Rule creation fix: (IP Range: Port)
simplewall v3.4.3

helper.c

	types = NET_STRING_ANY_ADDRESS | NET_STRING_ANY_SERVICE | NET_STRING_IP_NETWORK | NET_STRING_ANY_ADDRESS_NO_SCOPE | NET_STRING_ANY_SERVICE_NO_SCOPE;

	if (address->is_range)
	{
		code = ParseNetworkString (address->range_start, types, &ni, NULL,/*&port,*/ NULL);  //Fix IP Range:port

		if (code != ERROR_SUCCESS)
			goto CleanupExit;

		code = ParseNetworkString (address->range_end, types, &ni_end, &port,/*NULL,*/ NULL);  //Fix IP Range:port
	}
	else
	{
		code = ParseNetworkString (network_string, types, &ni, &port, &prefix_length);
	}

	if (code != ERROR_SUCCESS)
		goto CleanupExit;

**Comment by henrypp** [comment]
fixed
