### ISSUE TITLE
Enable "Resolve network addresses" cause app crash and also unable to startup.

### ISSUE THREAD

**Issue by kowith337** [henrypp/simplewall#1015]
I think this may possibly dupe #995, maybe...
Problem also occur in 3.4.2 but not yet reproduce at older version in range 3.4.x

Step to reproduce:
1. Start SimpleWall
2. Go to Settings > Rules
3. Enable checkmark `Resolve network addresses`
4. Try invoke some apps/connections and later you will see the `Exception raised` popup appear, that's an error!
> `The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s. (0xC0000005)`
5. Try start SimpleWall again and you will see same dialog above.

My environment:
- Windows 10 19044.1165 (en-GB, Japanese unicode)
- Run [DNSCrypt-proxy](https://github.com/DNSCrypt/dnscrypt-proxy) and [personalDNSFilter](https://github.com/IngoZenz/personaldnsfilter) along with and set network adapter DNS IP address to `127.0.0.1` to resolve domains locally, I use it as alternative of Windows hosts file.

Config:
```[simplewall]
BackupTimestamp=[redacted]
CheckUpdatesLast=[redacted]
SettingsLastPage=104
IsCertificatesEnabled=true
IsLogEnabled=true
IsLogUiEnabled=true
CurrentTab=105
IsTrayIconSingleClick=false
IsNotificationsOnTray=true
IsNetworkResolutionsEnabled=true
[simplewall\window]
IsMaximized=true
```

Dumps:
[simplewall-1630911469.zip](https://github.com/henrypp/simplewall/files/7113935/simplewall-1630911469.zip)

**Comment by kowith337** [comment]
Sorry because this seems it's probably my (fully) fault that blocked the whole `in-addr.arpa` entirely in `dnscrypt-proxy` by myself, the result is SimpleWall fail to resolve DNS name and show in dialog.
but it seems like you still fix to not causing the crash even SimpleWall itself cannot resolving DNS name from `in-addr.arpa`, right?

**Comment by henrypp** [comment]
fixed, you can check it.

[simplewall-3.4.3-bin.zip](https://github.com/henrypp/simplewall/files/7116026/simplewall-3.4.3-bin.zip)

**Comment by kowith337** [comment]
Worked now, even `in-addr.arpa` were blocked, thanks!
