### ISSUE TITLE
Cannot update simplewall directly. Instead forced to fresh install on every update

### ISSUE THREAD

**Issue by pixincreate** [henrypp/simplewall#1016]
Is this a normal thing? Every new version of simplewall prompts me to install, say v3.4.3. Upon clicking on it, asks me whether to install or not. Upon clicking on **OK** button, nothing happens. However, the cancel button works fine, cancels the update.  
I waited for more than an hour after pressiong the ok button which did nothing.   
On the other hand, I tried manually dowloading the application from the repo, and tried installing the same, onto the same dir, which results in installation process to abort.

**Comment by mtaki14** [comment]
Have had the issue since I can remember and still do. But updating manually works for me, which is what I always do

**Comment by zMohawk** [comment]
I have this problem now  too. I wish I could install it manually. I don't know how to. Does it mean (verify with sha to be "more sure") and then just drop the exe in the place of the old exe? Thanks.
