### ISSUE TITLE
App gets internet only till it is open.

### ISSUE THREAD

**Issue by clicky6** [henrypp/simplewall#1017]
Add a feature in simple wall so that when we open an app it gets internet access it has internet access till it's open and when we close the app, internet access is restricted for that app.

NOTE:- This feature should only be available for all apps not services and processes etc...

**Comment by clicky6** [comment]
@henrypp Any plans on adding some feature like this?

**Comment by henrypp** [comment]
> open an app it gets internet access it has internet access till it's open and when we close the app

all apps is already have internet access _only_ if it opened. that how it works, already.

**Comment by clicky6** [comment]
@henrypp I didn't got what you mean to say? And If there is a feature present, How to access it, Where am I gonna find it.

**Comment by clicky6** [comment]
@henrypp 


> Apps cannot access internet only when it is **NOT** opened, it's obvious.

When I minimize an app internet access should be restricted When the app is on focus again it should get internet access so Add a feature for that...

**Comment by henrypp** [comment]
> When I minimize an app internet access should be restricted When the app is on focus again it should get internet access so Add a feature for that...

At this time this is impossible.

**Comment by clicky6** [comment]
> At this time this is impossible.
@henrypp Why?

**Comment by clicky6** [comment]
> windows does not provide API for this, and installing hooks for 3rd party apps is not safe.

@henrypp Can you try to introduce something like this in SimpleWall.

**Comment by henrypp** [comment]
> Can you try to introduce something like this in SimpleWall.

May be. Not now, for sure.

**Comment by clicky6** [comment]
@henrypp Thanks...
