### ISSUE TITLE
[Feature Request] Notify on Internet Access to an "Allowed" App

### ISSUE THREAD

**Issue by ck9ine** [henrypp/simplewall#1018]
It would be nice to have an option to get a notification whenever an "Apps with internet access".  If the feature is added, perhaps it could be listed in the right-click context menu below "Rules > Disable notifications".

Useful to monitor how often a software "calls home", etc.  (i.e. One that you might be concerned about potential privacy issues) without having to click two times, then wade through the packets log to find whether or not it did.

P.S. Btw, thanks for the great software!

**Comment by Chaython** [comment]
Most apps have a constant connection, when they're running. You will just have endless pings.
