### ISSUE TITLE
SimpleWall popup notification blank

### ISSUE THREAD

**Issue by faelism** [henrypp/simplewall#1020]
![simplewall](https://user-images.githubusercontent.com/5818429/133661808-85d4e6c1-52ff-4161-bfb5-6c22431150e4.png)

This just started happening the other day after I updated. I tried to revert back to another version and it did not fix it.
Any ideas?

Thanks!

**Comment by faelism** [comment]
Uninstalled and re-installed and now its working. Thanks!

**Comment by henrypp** [comment]
dup #1009
