### ISSUE TITLE
Why change it

### ISSUE THREAD

**Issue by yontekh** [henrypp/simplewall#1022]
I would just like to let you know that I just spend hours trying to figure out why I couldnt connect to my webserver. And it was because Windows Firewall was still active.

Before SimpleWall would always prompt to disable windows firewall, and i would always let the default yes stay.
now i was assuming it had disabled windows firewall like it always did, but it did not, took me hours to figure it out.

Thanks

**Comment by Chaython** [comment]
I didn't realize he had made the change. He must've changed it when he added the new system rules.
Firewall is necessary to use Xbox and MSFT store. Otherwise svchost would have to be allowed globally, opening basically the whole network. 
Firewall was originally disabled because it was assumed, FW could override WFP.

**Comment by SeriousHoax** [comment]
> I didn't realize he had made the change. He must've changed it when he added the new system rules.
> Firewall is necessary to use Xbox and MSFT store, other modern MSFT app stuff. Otherwise svchost would have to be allowed globally, opening basically the whole network.
> Firewall was originally disabled because it was assumed, FW could override WFP also because one of the main features of Simplewall was "Windows Spy Blocker", and it was worried that MSFT could still make these connections with firewall on.

Hi! Can you please tell me if allowed apps on SimpleWall is allowed outbound connections only or outbound and inbound both are allowed for those? I mean apps allowing from the notification directly or manually adding and checking the tick mark.

**Comment by Chaython** [comment]
> 
> 
> > I didn't realize he had made the change. He must've changed it when he added the new system rules.
> > Firewall is necessary to use Xbox and MSFT store, other modern MSFT app stuff. Otherwise svchost would have to be allowed globally, opening basically the whole network.
> > Firewall was originally disabled because it was assumed, FW could override WFP also because one of the main features of Simplewall was "Windows Spy Blocker", and it was worried that MSFT could still make these connections with firewall on.
> 
> Hi! Can you please tell me if allowed apps on SimpleWall is allowed outbound connections only or outbound and inbound both are allowed for those? I mean apps allowing from the notification directly or manually adding and checking the tick mark.

Apps from the app list, are allowed in and out, custom rules are required for out or in only. 
Port rules are specified in the list. Some ports are not globally open now[I think they only opened the port as a glitch, not intended], rather you right-click rules and apply the rule. 
When you receive a popup to allow an app you can select a rule on the right, for quick access to only allow one way/certain ports.
I may be wrong, but best of my understanding sorry.

**Comment by yontekh** [comment]
Problem is solved for me by either disabling Windows Firewall.

If I ever require Windows Firewall for something, lets say Xbox, then I just enable Windows Firewall and add my incoming rules in both SimpleWall and WinFW.
