### ISSUE TITLE
Empty notification

### ISSUE THREAD

**Issue by andpuxa** [henrypp/simplewall#1030]
All connection notifications are empty.
![2021-09-28_12-07-52](https://user-images.githubusercontent.com/6974583/135058267-ebcd85c2-4013-42ff-aca6-029fcf555793.png)

**Comment by Theo-user** [comment]
It should be resolved in the next version.

**Comment by Thomas-p2-Elliott** [comment]
This makes the software practically unusable for a new user. Is there a version I can get that doesn't have the main interaction method broken?

**Comment by Theo-user** [comment]
> This makes the software practically unusable for a new user. Is there a version I can get that doesn't have the main interaction method broken? Honestly not sure why you'd push a release like this. It makes me lose faith in the developers, a lot.

It's not always an issue. It depends on a few things like multiple monitors, scaling,  etc. 

If bugs cause you to lose faith in developers maybe software isn't for you.

**Comment by henrypp** [comment]
dup #1009
