### ISSUE TITLE
Simplewall requires Windows 7 SP1 or later on Windows 10

### ISSUE THREAD

**Issue by Vildis** [henrypp/simplewall#1031]
![Simplewall update notification](https://user-images.githubusercontent.com/22894537/135067675-1e3b97e8-9688-4239-bd42-a34183990712.png)
When clicking yes on the update notification, this popped up.

![Error message](https://i.imgur.com/L7AstxW.png)

Running winver on my computer shows this:
![Winver image](https://i.imgur.com/sEmOJho.png)

So no clue why it popped up, how is Windows version information checked?

**Comment by Vildis** [comment]
Now I tried to update it again by clicking About -> Check for updates
![Exception raised](https://user-images.githubusercontent.com/22894537/135067889-8afcdcd6-ba02-4900-84a7-fca468e8b1a0.png)

**Comment by henrypp** [comment]
There is nsis installer problem. Upload dump, plz.
