### ISSUE TITLE
Add SimpleWalll to the repository of ruckzuck.tools

### ISSUE THREAD

**Issue by Mannshoch** [henrypp/simplewall#1034]
With ruckzuck you could autoupdate applications on your computer.

Homepage: https://ruckzuck.tools
Github: https://github.com/rzander/ruckzuck
HowTo: https://github.com/rzander/ruckzuck/wiki/How-to-create-a-Package-for-the-Repository

**Comment by icm-git** [comment]
Simplewall is already active in the winget community repo. I was surprised the other day when I did a `winget list` and saw Simplewall displayed with an available update to 2.5.1. Had no trouble using the upgrade command to silently update it; though, I'm sure just running an install would have produced the same result, given the ways SW can be updated.

First time I've heard of it, but based on a quick overview Ruckzuck sorta seems like a royal PITA for many project workflows, with a crazy small repo to boot (like ~600 packages). I looked at it and its new-ish API but it lacks too much for me to trust it in a non-personal use context. And even then, its reliance on Powershell 5.1+ at its core isn't my cup of tea. User base is very niche, I imagine.

Besides, I know Henry++ isn't gonna waste his time to maintain/update every SW version's Ruckzuck repo entry. But I think SW's license would permit you to go ahead and deal with all of that work yourself if you want it in their repo. Pretty sure you can just go ahead an DIY, no permission needed, correct me if I'm wrong.

Not sure who authored the manifest and commit for simplewall into winget, but I appreciate it a bunch! 🥳

Unrelated-_ish_: I have a ton of clients who hate the MS Store as much as I do (that is, having to attempt using its GUI/App which is full of jank), but now that winget uses it as a legit second source repo, I can retrieve those few damn UWP apps that are needed, or find instantly the exact UWP App requested (via its unique ID), all without any MS Account BS or trying to make the Store App itself work (not easy running simplewall with svchost blocked by default, near impossible using a local Win account).

Just one unelevated `winget install <[app.name] | [app.id]> -s msstore` command and it's done, no fuss no muss. You can even disable winget telemetry to MS, and it's respected. As well as outputting the install process to a log file. Open source MS software sucks _**so**_ much less than their proprietary codebases IMO.

**Comment by ltGuillaume** [comment]
Or just use https://scoop.sh (simplewall is in the `extras` bucket).
