### ISSUE TITLE
Version 3.5 : Check apps for digital signatures option not work.

### ISSUE THREAD

**Issue by Alcazer** [henrypp/simplewall#1037]
This feature doesn't work in the latest version (3.5). All signed apps highlighting. Enabled or disabled doesn't change anything.

**Comment by henrypp** [comment]
It works as well. If you disable option new apps will not checked for signatures. And if you restart SW, then apps do not checked for signatures.

**Comment by Alcazer** [comment]
I checked many times before open issue. It keeps checking every time even if it is turned off

**Comment by henrypp** [comment]
Oh shi
