### ISSUE TITLE
Feature request: Prune rules where file no longer exists

### ISSUE THREAD

**Issue by fn5** [henrypp/simplewall#1038]
It would be great to easily remove rules that are linked to files that no longer exist, for example:

![image](https://user-images.githubusercontent.com/7483527/135938582-de03a697-313b-4e9d-bb10-8728d9d36861.png)

One way could be to sort by these "red" rules so they can be deleted easier?

Thankyou

**Comment by skycommand** [comment]
This request has already been implemented. From the menu bar, select "Edit" -> "Purge unused apps".

**Comment by reddyshyam** [comment]
> This feature is already available in SimpleWall. From the menu bar, select "Edit" and "Purge unused apps."

Or double click on status bar where it listes unused apps, to clear the list.

![image](https://user-images.githubusercontent.com/12392746/136065686-7faa1ae9-85f9-40b3-b6e3-fbce2c9af602.png)
