### ISSUE TITLE
Feature Request: Allow everything but....

### ISSUE THREAD

**Issue by terry98** [henrypp/simplewall#1039]
I have been using simplewall for a while already and love the app, is everything just like the name implies... but the rules have always been, allow/deny everything or something specific.. for example I want to add a rule which would block all chrome traffic outgoing from my work local IP (wifi) therefore allowing all traffic from the rest of the network IP (vpn and ethernet); for this I need to create 2 rules, one blocking my work IP and other allowing the other IPs... It would be great to have just one rule specifying allow every IP but not the one from work...

If I grant chrome network access and just create the rule to block the IP from work I can see connections from that IP in the connections log.

**Comment by henrypp** [comment]
rtfm https://github.com/henrypp/simplewall#q-where-is-blacklist-mode
