### ISSUE TITLE
Bug: Crash on windows start

### ISSUE THREAD

**Issue by Fehertukor** [henrypp/simplewall#1043]
Hi!

Thank you for your work! I love simplewall!
But with the latest release 3.5.1.
It crashes with windows start bug code: 
n/a (0x000006D9)
Manual start helps.

That is all.

Thanks!

**Comment by M-O-Z-G** [comment]
v3.5.3
Windows 10 Pro x64 20H2

Same here, but only with huge profile which contains 13k of user rules. Manual restart helps, but after some time after log on.

Switching to "light" profile resolves the problem, but isn't solution by itself of course.

**Comment by henrypp** [comment]
@M-O-Z-G

Let me see dump here.

**Comment by henrypp** [comment]
@Fehertukor 
@MetaIdea 
@M-O-Z-G

you can test new version [here](https://github.com/henrypp/simplewall/issues/1009#issuecomment-955778526).

**Comment by Powsey** [comment]
Hello, just had a crash today on the latest version of simplewall.
Here is my crashdump
[simplewall-1639422783.zip](https://github.com/henrypp/simplewall/files/7706351/simplewall-1639422783.zip)
