### ISSUE TITLE
disable "disable notification" tick as default

### ISSUE THREAD

**Issue by ghost** [henrypp/simplewall#1045]
Allow all blocked connection to notify as default instead of suppressing all of them. Is there already a settings for it? 
![image](https://user-images.githubusercontent.com/87915498/136904262-cb950c86-2ff0-4d9f-8778-46abc19ed6e3.png)

**Comment by henrypp** [comment]
disable notification is off by default, notifications is disabled for app is only when you click "block" button in notification
