### ISSUE TITLE
Network alert - Add PID of process  [suggestion] [feature]

### ISSUE THREAD

**Issue by WildTbag** [henrypp/simplewall#1047]
I would like to suggest to add the PID of the blocked app in the notification alert window. This would especially help to identify the svchost.exe services behind the alerts. I would then use Process Hacker to check out the service(s) behind the blocked svchost instance. 
Thank you very much for this nice program!

**Comment by henrypp** [comment]
It cannot be done because of @microsoft (as always), not any of FWPM_NET_EVENT have PID information.

**Comment by pbarney** [comment]
Well that sucks. Thanks for looking into it.
