### ISSUE TITLE
Notification Failing (FwpmEngineSetOption Error 0x00000003)

### ISSUE THREAD

**Issue by rkmfl** [henrypp/simplewall#1049]
I've used Simplewall since the beginning around 2016.  I am very familiar with the configuration and operation; I'm not making a newbie mistake (eg notifications disabled or skipped for user rules, etc).  

I've never had any major bug, until recently:

**Versions:**
- Henry++ Simplewall v3.5.1 (x64)
- Windows Server 10 21H2 (20348.288)

**Explanation / Recreate Issue:**
- On Windows Server:  Network notifications are not working (Simplewall set to notify, no exceptions)
- On Windows Workstation:  Working fine.
- Set to log packets to file; no traffic shows in the file.
- Simplewall does block the traffic; only the notification is not working.

**Debug log shows only one entry:**
`"Warning","‎10/‎14/‎2021 ‏‎11:39:38 PM","FwpmEngineSetOption","0x00000003","FWPM_ENGINE_COLLECT_NET_EVENTS","3.5.1","10.0 build 20348"`

This log entry is **repeated** every time Simplewall attempts to **Enable Filters**.

**Attempted Fixes**
- I have un-installed, re-installed, removed all settings/vanilla install.  Nothing fixes the issue.
- I have confirmed Windows Firewall (without Simplewall) does show notifications, no problems.
- I have installed a vanilla Windows Server VM to test, same error.
- I have installed a vanilla Windows 10 Pro VM to test, no problems.

Thank you for any insight/ideas.

**Comment by henrypp** [comment]
Dupl #841
