### ISSUE TITLE
[UI] Layered notifications and "Allow" button (2.1.4)

### ISSUE THREAD

**Issue by xEBFE** [henrypp/simplewall#105]
Mode: White list

Because of how notifcations "stack up" over time if not attended to, could you make it so that the "Allow" button is disabled for 0.75s - 1s when the notification UI window gets focus, then after that period the "Allow" buitton would become enabled. The reason for this change is lets say I have 4 notifications yet to be decided on. I'm viewing notification "4/4" and lets say I want to allow it, so I go to single-click "Allow" but I accidently double-click (slowly). Because the two separate clicks were done over the "Allow" button, while I did properly allow program 4/4, I just mistakenly allowed the next program (3/3) in the notificaions. Having a tiny delay of the enabled state of the Allow button would prevent this.

**Comment by ltGuillaume** [comment]
That's a good request.

This also made me think of a question: how does simplewall handle new block notifications while the mouse is hovering a notification? Is there a possibility that you want to click Allow, but just before that, a new message gets added to the notification stack, so you accidentally allow that application instead?

**Comment by xEBFE** [comment]
I just tested that scenario and if you're hovering over a current notifcation and a new program tries to make an outbound connection that isn't whitelisted, that new program will place itself right ontop of the current notification you're viewing and you could accidently trigger an allow click on it if you just happened to click right as it popped up.

@henrypp Could you change the way notifications are displayed. So that if you are presently viewing a notifcation and another blocked app is invoking a notification window that it doesn't place itself ontop of the one you're presently viewing.

**Comment by ltGuillaume** [comment]
@xEBFE Thank you for testing it! :-) That was indeed what I suspected, so it would if new popups were postponed until the mouse is not on top of a current notification.
