### ISSUE TITLE
Add an option to allow an app to access only some connection and not the internet.

### ISSUE THREAD

**Issue by clicky6** [henrypp/simplewall#1050]
Problem - I use FTP to transfer mobile files from mobile to PC. We can only open ftp connections in file explorer and I have restricted internet access of File Explorer because it doesn't need it, So How can I access files from ftp? If I give internet access the File Explorer can connect to Microsoft Servers and I don't want that.

Suggested Solution - Add an option so that we can allow apps to access FTP,SFTP etc... without giving the app internet access so that It cannot connect to the internet.

**Comment by clicky6** [comment]
@henrypp 
How in this screenshot simple wall's screen color is dark?🤔
Is there an option to change theming for simplewall interface?🤔

**Comment by henrypp** [comment]
> Is there an option to change theming for simplewall interface?🤔

No. This is dark windows theme.

https://github.com/henrypp/simplewall/issues/248#issuecomment-766141048
