### ISSUE TITLE
Log not sorting properly

### ISSUE THREAD

**Issue by jorik392** [henrypp/simplewall#1052]
I don't know which version this started happening but I think since 3.5 or later. When trying to sort the log by date for example it is not properly sorted and many of the entries that should be appear on top appear near the bottom. Also for some reason now there are many blank lines with no text showing up in the logs as well.

**Comment by henrypp** [comment]
> Also for some reason now there are many blank lines with no text showing up in the logs as well.

which ones, for example?

**Comment by jorik392** [comment]
They are completely empty lines which show in the logs there is no associated program or rule. When right clicking the empty line and copy it is just blank.

**Comment by henrypp** [comment]
Check for 3.5.2

**Comment by henrypp** [comment]
> Sorting by column such as date still not working properly. Also if I expand the width of date column the UI reverts to original width when it refreshes connections which I think shouldn't happen.

Disable auto-size columns feature
