### ISSUE TITLE
How to refresh automatically?

### ISSUE THREAD

**Issue by sourcepowered** [henrypp/simplewall#1054]
Because I have some special business requirements, I will write rules in profile.xml, and then how do I refresh the simplewall automatically? Thanks!

**Comment by sourcepowered** [comment]
Is to refresh the entire firewall.

**Comment by henrypp** [comment]
> Is to refresh the entire firewall, the function of F5.

It does not required, all filters are updated automatically.

**Comment by sourcepowered** [comment]
What I mean is that if I manually modify the profile.xml, I have to refresh it before these new custom items can take effect. So how can I make it refresh automatically? Without closing and restarting the firewall?

**Comment by sourcepowered** [comment]
I want to write a program to automatically click the "Refresh" button, but I cannot get the handle of the button.
