### ISSUE TITLE
Allowing local ports and remote IPs not working correctly (corrected description)

### ISSUE THREAD

**Issue by FreePlague** [henrypp/simplewall#1057]
I have messed up with #864 issue description. My bad, sorry. Problem still exists.
simplewall v3.5.3 x64, default behavior (whitelist)
Windows 7 x64, Windows firewall disabled

When allowing two local ports for two remote IPs for incoming connections first local port allowed for first remote IP and second local port for second remote IP in lists. But I think should be all ports for all IPs.

Example rule which allows incoming connections:
```
Remote:
-1.1.1.1
-2.2.2.2
Local:
-1111
-2222
```
This rule should allow 4 connections:
```
-1.1.1.1:*any remote port* to *any local IP*:1111
-1.1.1.1:*any remote port* to *any local IP*:2222
-2.2.2.2:*any remote port* to *any local IP*:1111
-2.2.2.2:*any remote port* to *any local IP*:2222
```
But instead allowing only 2 connections (Like first with first, second with second):
```
-1.1.1.1:*any remote port* to *any local IP*:1111
-2.2.2.2:*any remote port* to *any local IP*:2222
```
Seems bug to me because this rule working fine:
```
Remote:
-1.1.1.1
Local:
-1111
-2222
```
Allowing 2 connections:
```
-1.1.1.1:*any remote port* to *any local IP*:1111
-1.1.1.1:*any remote port* to *any local IP*:2222
```

**Comment by henrypp** [comment]
@FreePlague i think not wiki, but in editor description.
