### ISSUE TITLE
Update issues

### ISSUE THREAD

**Issue by samokosik** [henrypp/simplewall#1061]
Hello,
when I try to update simplewall, an error pops up when I try to install the update.
![image](https://user-images.githubusercontent.com/73645764/138268029-664c8ac0-880f-4cf1-88b1-da6d33f3ce95.png)
This works properly and downloads update

![image](https://user-images.githubusercontent.com/73645764/138268128-89897b58-88f2-439c-8161-baca321c02e8.png)
However when I try to click "OK", nothing happens and the small popup window does not even close, so I am forced to close the updater.

Thank you

**Comment by porkmanager** [comment]
i had same issue/
win7 x64 
ver:
![image](https://user-images.githubusercontent.com/44921055/138274006-9168da36-e6a2-4ba5-8d01-ec8c1e4ca11e.png)

**Comment by ags1234** [comment]
This happens to me, too. When click "OK", nothing happens. Definitely a bug.

**Comment by gitguest54** [comment]
> 
> 
> @gitguest54 I think It will be fixed soon till then wait and watch And no need of downloading the setup again and install it just Wait for devs to fix this bug and release that update...

Okay...

**Comment by clicky6** [comment]
@henrypp Is this fixed?

**Comment by henrypp** [comment]
[Yes](https://github.com/henrypp/simplewall/issues/1066#issuecomment-959702493)

**Comment by clicky6** [comment]
@henrypp 
Still showing the same problem when updating from help check for updates.

**Comment by morralletti** [comment]
> Hello, when I try to update simplewall, an error pops up when I try to install the update. ![image](https://user-images.githubusercontent.com/73645764/138268029-664c8ac0-880f-4cf1-88b1-da6d33f3ce95.png) This works properly and downloads update
> 
> ![image](https://user-images.githubusercontent.com/73645764/138268128-89897b58-88f2-439c-8161-baca321c02e8.png) However when I try to click "OK", nothing happens and the small popup window does not even close, so I am forced to close the updater.
> 
> Thank you

Same problem here

**Comment by ags1234** [comment]
> This happens to me, too. When click "OK", nothing happens. Definitely a bug.

Just updated to 3.6.1. Update problem is fixed.

**Comment by clicky6** [comment]
@ags1234 How did you update,
because It's showing the same problem when I try to update with `check for updates` to version `3.6.1` This pops out and Simplewall closes and it doesn't update.
`The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s. (0xC0000005)`

**Comment by ags1234** [comment]
@clicky6 I don't remember if simplewall automatically notified me of the new version or if I clicked Help - Check for updates. But it definitely install the new version correctly for me. Because I use it and definitely did not install it by hand.

**Comment by clicky6** [comment]
I am having some issues with updating of SimpleWall neither it's updating automatically nor updating through Help - Check for updates.
