### ISSUE TITLE
Another big memory leak

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [henrypp/simplewall#1066]
2 days and 2 hours ago (17:39:22 26.10.2021)
Private bytes, 4,65 GB

v.3.5.3 x64 
Empty packet log. Permanent rules.
Windows 10 21H1 (19043. 1288)

Handles
```
Handles, 458
Peak handles, 458
GDI handles, 338
USER handles, 131
Running time, 08:25:23.773
Suspended time, 00:00:00.000
Hang count, 0
Ghost count, 0
```

IO
```
Reads, 1 398
Reads delta, 0
Read bytes, 535,27 MB
Read bytes delta, 0
Writes, 69
Writes delta, 0
Write bytes, 297,7 kB
Write bytes delta, 0
Other, 1 957 454
Other delta, 16
Other bytes, 64,15 MB
Other bytes delta, 1,72 kB/s
I/O priority, Normal
```

Disk IO
```
Reads, 8 325
Read bytes, 458,26 MB
Read bytes delta, 0
Writes, 34
Write bytes, 236 kB
Write bytes delta, 0
```

Other
```
552, simplewall.exe+0x53a90, Normal
4692, winmm.dll!timeGetTime+0x20, Highest
10432, ntdll.dll!TpReleaseCleanupGroupMembers+0x450, Normal
10648, ntdll.dll!TpReleaseCleanupGroupMembers+0x450, Normal
11128, simplewall.exe+0x10fe0, Normal
15468, ntdll.dll!TpReleaseCleanupGroupMembers+0x450, Normal
17396, ntdll.dll!TpReleaseCleanupGroupMembers+0x450, Normal

552
0, ntoskrnl.exe!KeWaitForSingleObject+0x38f0
1, ntoskrnl.exe!KeWaitForSingleObject+0x1787
2, ntoskrnl.exe!KeWaitForSingleObject+0x98f
3, ntoskrnl.exe!KeWaitForSingleObject+0x233
4, ntoskrnl.exe!KeWaitForMultipleObjects+0x45b
5, win32kfull.sys!xxxUpdateInputHangInfo+0x10d7
6, win32kfull.sys!xxxUpdateInputHangInfo+0xca5
7, win32kfull.sys!NtUserPeekMessage+0xebd
8, win32kfull.sys!NtUserGetMessage+0x92
9, win32k.sys!EngSaveFloatingPointState+0x1b85
10, ntoskrnl.exe!setjmpex+0x7cb8
11, win32u.dll!NtUserGetMessage+0x14
12, user32.dll!GetMessageW+0x2e
13, simplewall.exe+0x356c6
14, simplewall.exe+0x53a22
15, kernel32.dll!BaseThreadInitThunk+0x14
16, ntdll.dll!RtlUserThreadStart+0x21

11128
0, ntoskrnl.exe!KeWaitForSingleObject+0x38f0
1, ntoskrnl.exe!KeWaitForSingleObject+0x1787
2, ntoskrnl.exe!KeWaitForSingleObject+0x98f
3, ntoskrnl.exe!KeWaitForSingleObject+0x233
4, ntoskrnl.exe!ObWaitForSingleObject+0x91
5, ntoskrnl.exe!NtWaitForSingleObject+0x6a
6, ntoskrnl.exe!setjmpex+0x7cb8
7, ntdll.dll!NtWaitForSingleObject+0x14
8, KernelBase.dll!WaitForSingleObjectEx+0x8e
9, simplewall.exe+0x2c1c6
10, simplewall.exe+0x11058
11, kernel32.dll!BaseThreadInitThunk+0x14
12, ntdll.dll!RtlUserThreadStart+0x21


1, 0x193e7bd0000, 0, 4,11 MB, 10, , Process Heap, Segment Heap
2, 0x193e7b60000, 1,88 kB, 4 kB, 1, , CSRSS Port Heap, NT Heap
3, 0x193e99e0000, 0, 372 kB, 2, , Private Heap, Segment Heap
4, 0x193e9a30000, 0, 64 kB, 2, , Private Heap, Segment Heap
5, 0x193e9a60000, 0, 4,63 GB, 5 846, , Private Heap, Segment Heap
```
[Process Hacker (simplewall.exe) Memory.txt](https://github.com/henrypp/simplewall/files/7436299/Process.Hacker.simplewall.exe.Memory.txt)

**Comment by henrypp** [comment]
Hello, you can test pre-release build.

https://www.henrypp.org/files/simplewall/latest/

**Comment by henrypp** [comment]
Can you confirm memory leak is fixed (or not)?

**Comment by 0x4E69676874466F78** [comment]
> Can you confirm memory leak is fixed (or not)?

I could not repeat this leak on v.3.5.3
Perhaps it depends on the number of pop-ups.

On 3.5.3.5-beta leak is not repeat itself either.
> 2 days and 6 hours ago (13:42:35 04.11.2021)
Private bytes, 13,96 MB

**Comment by henrypp** [comment]
>  Perhaps it depends on the number of pop-ups.

Yes, notification icons was not utilized after close notification window and some reolve network addresses may leak memory due to race-conditions . It was fixed in next release.

**Comment by deroverda** [comment]
Same memory leak bug here. Can't update to latest version. Should we wait for a new release or should we try a clean install?

**Comment by henrypp** [comment]
@deroverda 
3.5.3 or preview build?

**Comment by deroverda** [comment]
> 
> 
> @deroverda 3.5.3 or preview build?

3.5.1 

Haven't been able to update since this version.

**Comment by deroverda** [comment]
[Here's a screenshot of the error](https://imgur.com/a/Em4gJWV)

**Comment by henrypp** [comment]
You can update to a [working preview here](https://github.com/henrypp/simplewall/issues/1066#issuecomment-959702493).

**Comment by deroverda** [comment]
> 
> 
> You can update to a [working preview here](https://github.com/henrypp/simplewall/issues/1066#issuecomment-959702493).

Are my settings still saved?

**Comment by henrypp** [comment]
@deroverda 
yes

**Comment by deroverda** [comment]
@henrypp excellent, thanks. successfully updated to preview build without any problems.
