### ISSUE TITLE
Windows 10 Pro Firewall

### ISSUE THREAD

**Issue by Mr-Administrator** [henrypp/simplewall#1068]
I am not sure if this is an issue, or that I am not using the correct settings. The problem that I have is that windows firewall turns off when I enable filters after disabling the filters of your awesome little app, Simplewall. I would like to run WIndows firewall in conjunction with your app. I am not sure if this is the best practice, or not. If it is more secure to disable Windows firewall, please do let me know. Thanks for your work in helping Windows users lock down Microsoft's Phone Home OS. 

CYBERCORE -- TeamSys

**Comment by Theo-user** [comment]
Use one or the other, not both. No point.

**Comment by Mr-Administrator** [comment]
Ok, thanks for the clarification, Mr Henry.
