### ISSUE TITLE
Compile SimpleWall to start using it!

### ISSUE THREAD

**Issue by simaotrigo** [henrypp/simplewall#1069]
How can I compile simplewall?

I could get the .exe but rather compile it myself...
Can anyone help me out?

**Comment by simaotrigo** [comment]
I'm still looking how to compile it! It would be great if anyone could tell me so i could learn more!

**Comment by henrypp** [comment]
open in vs19 and compile, where is the problem

**Comment by henrypp** [comment]
also sync `.gitmodules`
