### ISSUE TITLE
Notifications: less sensitive before hiding or snap to taskbar location

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#107]
I have my taskbar at the top of the screen, and before (when I had an ultra-wide monitor) I had it at the right side of the screen. I see a lot of people choosing for an alternative location of their taskbar.

When I'm using the touchpad and I want to have a look at notifications, I can't reach the notification before it disappears. That's because while the taskbar is at the top, the notification stays at the bottom.

To prevent this behavior, could you either:
- make the notification disappear less easily, for instance only after an actual click on another window is made, or
- snap the notification to the taskbar (so it's also at the top)

**Comment by xEBFE** [comment]
@ltGuillaume have you tried changing the option "Display timeout (sec.)" up from 10 (default)? (Settings > Dropped packets log)

**Comment by ltGuillaume** [comment]
@xEBFE No, but it shouldn't matter. I should still be able to see the notification if I hover over the tray icon.
