### ISSUE TITLE
simultaneous editing

### ISSUE THREAD

**Issue by crazyyzarc** [henrypp/simplewall#1071]
![2021-11-02_14-08-28-240_ZhTKE](https://user-images.githubusercontent.com/4954535/139853061-d0d995d7-7cfc-4158-b311-a454df7590d6.png)
`Die Anweisung in 0x%p verwies auf Arbeitsspeicher bei 0x%p. Der Vorgang %s konnte im Arbeitsspeicher nicht durchgeführt werden. (0xC0000005)`

When I open any random user rule (1: e.g., for powershell_ise) **and** I force the simplewall blocking mechanism (2: e.g., open first putty), then I get pop-up information for the blocked application
And then when I save the new putty rule and pass it to the last opened powershell rule the error comes up 

![2021-11-02_14-26-23-025_XWxgS](https://user-images.githubusercontent.com/4954535/139855754-1c3fa596-c1ca-4a8a-8b7a-3aecce2575f6.png)

**Comment by henrypp** [comment]
Upload crash dump.

**Comment by henrypp** [comment]
Fixed

**Comment by henrypp** [comment]
You can download test build from here:
https://www.henrypp.org/files/simplewall/latest/
