### ISSUE TITLE
wfpdiag.etl

### ISSUE THREAD

**Issue by protode** [henrypp/simplewall#1075]
If i disable wfpdiag.etl logging via
**netsh wfp set options netevents=off**
in windows console

It comes back online on next reboot when simplewall starts.
So is this really neccessary? Filtering seems to work ok with that disabled.

**Comment by henrypp** [comment]
> Filtering seems to work ok with that disabled.

Filtering works? How about logging, hmm?

**Comment by protode** [comment]
It does not. But i think it should be related to interface settings, not always enabled.

**Comment by ValZapod** [comment]
>comes back online on next reboot when

But it does not come back just after reboot.
