### ISSUE TITLE
Cannot install using the check for updates menu

### ISSUE THREAD

**Issue by corwinou** [henrypp/simplewall#1080]
Hi,

I tried several times to update simplewall through the help menu / check for updates, but I always got a failure... I just followed these steps:
Help / check for updates
Update available. Download and install now ? Yes
I see the progress bar til the end, OK, but then on the next dialog (something like ready to install) I cannot click on the Yes button

It was the case on multiple previous versions, eg 3.5.x . (Windows 11, app with language selected)

Any hint ?

**Comment by henrypp** [comment]
dup #1061

**Comment by corwinou** [comment]
sorry for inconvenience, I only checked the open issues :o(
