### ISSUE TITLE
Impossible to import a profile.xml

### ISSUE THREAD

**Issue by Janaue** [henrypp/simplewall#1086]
I have updated simplewall today , in  a portable mode. I reset everything by deleting the current profile.xml and .bak, then i use stock settings and then I export the empty profile.xml.
however when i import it

simplewall says
<img width="240" alt="2021-11-11 07_17_10-simplewall" src="https://user-images.githubusercontent.com/10972636/141248159-0de0ab4a-2ee4-4a15-93c6-5abbfa32e669.png">

this is the .xml that is imported :

```
<?xml version="1.0" encoding="UTF-8"?>
<root timestamp="1636611323" type="3" version="4">
	<apps>
		<item path="D:\installation\Simplewall\64\simplewall.exe" timestamp="1636611273" is_enabled="true"/>
		<item path="System" timestamp="1636611273"/>
		<item path="C:\Windows\system32\svchost.exe" timestamp="1636611273"/>
		<item path="C:\Windows\system32\SppExtComObj.exe" timestamp="1636611273"/>
		<item path="C:\Windows\system32\lsass.exe" timestamp="1636611273"/>
		<item path="UsoSvc" timestamp="1636611273"/>
	</apps>
	<rules_custom>
	</rules_custom>
	<rules_config>
	</rules_config>
</root>
```

I tried with a real profile with my custom rules and the warning shows up too.

**Comment by henrypp** [comment]
This is only UI message, profile was imported correctly.

**Comment by LIMUNADE** [comment]
Encounter same thing. Tried to test fast boot setting and as of result when you are trying to turn off the PC it didn't. So I manually turned it off. 

When I launched PC next day, I encounter this error and lost my profile settings. Thought that I could import it back in prog folder, and it was a wrong move. Lost .bak file in a process (why only 1 backup?!).

**Comment by henrypp** [comment]
@LIMUNADE 

simplewall create backup copy of your profile automaticaly.
