### ISSUE TITLE
Blocking application does not work on blizzard games

### ISSUE THREAD

**Issue by wilhelmw201** [henrypp/simplewall#1089]
So I have a "Heroes of the storm" (free to play btw, in case someone wants to reproduce this problem) game by blizzard on my computer, I put HeroesOfTheStorm_x64.exe on the "apps without internet access" list, attempting to block its internet access. However, Heroes of the Storm\Support64\HeroesOfTheStorm_x64.exe accesses internet like nothing has happened. I see a bunch of "ESTABLISHED" connections originating from this HeroesOfTheStorm_x64.exe to other IPs, wireshark shows that real data are recieved from remote. 
Additionally, if I enable internet access for it, then disable its internet access, then the game has no internet for a few seconds, then comes back online.
Any ideas what may have happened?

**Comment by wilhelmw201** [comment]
Never mind, restarting solved the issue.

**Comment by fusionneur** [comment]
restarting pc or simplewall fixed it??
