### ISSUE TITLE
Doesn't run on regular user startup

### ISSUE THREAD

**Issue by ddd111ddd** [henrypp/simplewall#109]
Portable Version 2.1.4, 64-bit (Unicode) - Windows 10 FCU

☑ Load on system startup
☑ simplewall always running as **admin**

I run a **regular** Windows account and when I reboot the system simplewall doesn't start automatically.

Autoruns lists simplewall in the **admin** account (because I need/want it run as admin) `HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run` but nothing happens on startup.

If I remember correctly I had a similar issue with another program and had to use the task scheduler but it doesn't work with GUI programs.

Any possible fix? Thanks!

**Comment by xEBFE** [comment]
While logged into the **admin** account, try removing the simplewall autorun key referencing HKCU (HKEY_CURRENT_USER) and instead create a new autorun key referencing HKLM (HKEY_LOCAL_MACHINE): 

TryMe.reg (This assumes simplewall is installed at C:\Program Files\simplewall\)
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run]
"simplewall"="\"C:\\Program Files\\simplewall\\simplewall.exe\" /minimized"
```

Restart the computer and log into the **regular** Windows account.

**Comment by ddd111ddd** [comment]
Couldn't make it work.

I also tried all the solutions I could find on SO like https://stackoverflow.com/questions/36846688/powershell-run-job-at-startup-with-admin-rights-using-scheduledjob and it's always the same problem. I can get the program to launch but no GUI or tray icon appears. There's several unanswered questions on Microsoft's forums about how to start an elevated interactive GUI on startup as regular user.

**Comment by GHosTiKuS** [comment]
its because simplewall needs admin rights and will not launch without them.
the only solution is to run it with scheduler from user with admin rights.

**Comment by cinke** [comment]
I have the same issue on one of my computers, managed to circumvent it by adding the startups string to:
HKLM\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Run
