### ISSUE TITLE
LocalServiceNoNetworkFirewall CPU Usage when Simplewall Running in Background

### ISSUE THREAD

**Issue by Ithiloneth** [henrypp/simplewall#1090]
When I run Simplewall, even in the background, LocalSeviceNoNetworkFirewall service consumes significantly more CPU - not to the point where I can say for certain it is an issue, but it does _seem_ a little excessive; is there an issue here?
I noticed it when my internal fans spun up even though all I had going on was a download, and when I think back, it seems that has been the case for some time now; not sure how reliable my memory is though.

Running SimpleWall in the background (11 - 14% plus another 4 - 8% from Simplewall itself):
![image](https://user-images.githubusercontent.com/20944949/141465997-e86b1a25-4d38-4631-a6ee-ed4825408cc4.png)

Not running Simplewall; still using it's rules though (1 - 3%):
![image](https://user-images.githubusercontent.com/20944949/141465943-7cb7f143-30f8-43e8-af0b-76d6a456d20a.png)
![image](https://user-images.githubusercontent.com/20944949/141468258-ddbd9078-b780-4d1c-87c4-36ebe1770b4d.png)

**My settings**
Windows Firewall is turned off:
![image](https://user-images.githubusercontent.com/20944949/141466356-6e937299-c0ef-4a4d-ad04-6e58a64d32bb.png)

Simplewall settings:
![image](https://user-images.githubusercontent.com/20944949/141466435-307a195d-d412-4f22-9d1a-ae80ae3687a3.png)

I'm using a VPN, Mullvad, over Wireguard.
I am not running packet logging.
I am running Whitelist with new connection attempt detection active.
I am using Simplewall in the portable mode - unzipped directly onto the system drive in a subfolder.
My last simplewall_debug.log is from 10/8 so it's not attached here as it seems irrelevant. Happy to share a log file but unsure how to get a recent one.

Simplewall number of rules:
![image](https://user-images.githubusercontent.com/20944949/141466500-277f2a69-f8a0-4de6-b908-98d900d9186f.png)

About (Simplewall):
![image](https://user-images.githubusercontent.com/20944949/141466225-6e869f8b-6a89-451a-a046-2647a8ecce37.png)

As always - thanks for a great program; my world would not be the same without you and Simplewall!

**Comment by cocoon** [comment]
I can atleast say I have seen something similar some days ago, too.

For me I had the problem directly after a reboot, after logging in, it seemed to block each other somehow, also my manually started batch to refresh icons (ie4uinit.exe -show) then stopped and waited for these prosesses (waiting cueue) afair.

When I then killed simplewall processes and started it again all was going on normal. I updated to nearly all 3.6-test versions in between and now since 3.6 final + 3.6.1 I have to check again. But I have to say I additionally have the Evorim Free Firewall running.

**Comment by Ithiloneth** [comment]
I have exited and started Simplewall a couple of times - no improvement. Currently I am downloading some large files from my cloud storage, and can't attempt a restart or roll back but will do so ASAP and report back later today.

**Comment by cocoon** [comment]
I had checked with Task Manager (waiting chain) and Sysinternals Process Explorer ... just checked and there seems to be an interesting additional way to check for problems like this:

https://techcommunity.microsoft.com/t5/ask-the-performance-team/alternative-tools-for-application-hangs/ba-p/1685245

**Comment by Ithiloneth** [comment]
A reboot of the system did not help. I will endeavor to rollback to the last version of 3.5 and see if that helps.

**Comment by Ithiloneth** [comment]
Sadly I get similar results with 3.5.3; Significant CPU usage for the LOcalServiceNoNetworkFirewall.
Not sure it is wise to rollback further?

3.5.3 Running in the background:
![image](https://user-images.githubusercontent.com/20944949/141479494-ffb20684-38fb-45a9-a2ea-ef798a097e77.png)

Not running Simplewall:
![image](https://user-images.githubusercontent.com/20944949/141479569-04008cbd-5b63-4a3a-98c7-b83815b04d92.png)

**Comment by cocoon** [comment]
I didn't mean a Reboot fixed it for me!
I had to kill simplewall after boot and start Simplewall manually again.

**Comment by Ithiloneth** [comment]
I did do that; added clarification to earlier post :)

**Comment by cocoon** [comment]
When you have this problem, can you open the "Windows Defender Firewall with Advanced Security" panel? For me it was trying to load but was also blocked. Currently I don't have this problem anymore, so I cannot check more.

**Comment by Ithiloneth** [comment]
Aye; it loads:
![image](https://user-images.githubusercontent.com/20944949/141676727-55e5eec4-41b7-4082-a2f1-751cd9a3444e.png)

**Comment by Altefier** [comment]
I've been dealing with that issue for probably over a year, but until now I've never considered that it may be directly related to simplewall. What fixes this issue for me whenever it occurs is to reset the Windows Firewall to its default settings.

**Comment by Ithiloneth** [comment]
Thank you for the suggestion Altefier.
I've been a combination of sick and busy so hadn't the chance to test your solution; now the issue appears to be resolved.

Only known change is Windows updating - maybe that was it?

Closing this issue, with the hope that it was just a temporary problem. If not it could always be revisited.
Thanks everyone!
