### ISSUE TITLE
Unable to update through updater

### ISSUE THREAD

**Issue by pilsnerbeer** [henrypp/simplewall#1092]
Got a update notification today. Want to install but pressing the OK button doesn't do anything - simply doesnt work.
![Screenshot_1](https://user-images.githubusercontent.com/36133540/141616984-22ee616a-cc06-4173-a9a7-c5905411d85d.png)

on Windows 10

**Comment by ridetonirvana** [comment]
Yes exactly, so freaking annoying...

**Comment by Powsey** [comment]
The update has been fixed in version 3.6.1. 
So you need to download the new version and future updates will be handled fine from now on. 

But you need to do a manual update this time otherwise you will be stuck with the bug ;)

**Comment by ridetonirvana** [comment]
So this bug was fixed on this latest update? yes, I did update it manually like always, so Hackerman fixed it! nice l🤣

**Comment by Powsey** [comment]
Yeah it's been fixed, probably in the version just before 3.6.1 (maybe 3.6.0 ?)
I updated through the updater to 3.6.1 from previous version successfully.

**Comment by henrypp** [comment]
3.6 was fixed, older version still need update manually. dup #1061
