### ISSUE TITLE
Lost all my filters after Windows crash

### ISSUE THREAD

**Issue by whytho2000** [henrypp/simplewall#110]
A driver problem caused my Windows 10 to crash. After reboot all rules were gone.

```
[‎15/‎12/‎2017 ‏‎00:00:00] pugi::load_file() failed with error code 0x00000000 (status: 16, offset: 12624, text: No document element found, file: C:\somefolder\simplewall\apps.xml) [2.1.4]
[‎15/‎12/‎2017 ‏‎00:00:00] pugi::load_file() failed with error code 0x00000000 (status: 16, offset: 1866, text: No document element found, file: C:\somefolder\simplewall\rules_custom.xml) [2.1.4]
```

I had an older backup but maybe it's a good idea to keep automated backups inside a folder so you can restore if this happens. Not even sure why the file got deleted, there's nothing wrong with my disk (I checked).

**Comment by GHosTiKuS** [comment]
same here
`[‎31.‎12.‎2017 ‏‎11:49:11] pugi::load_file() failed with error code 0x00000000 (status: 16, offset: 10292, text: No document element found, file: ***\simplewall\apps.xml) [2.1.4]
[‎31.‎12.‎2017 ‏‎11:49:11] pugi::load_file() failed with error code 0x00000000 (status: 16, offset: 850, text: No document element found, file: ***\simplewall\rules_custom.xml) [2.1.4]`

**Comment by henrypp** [comment]
check 2.2

**Comment by itsvolodya** [comment]
@henrypp 
The problem is still there on 2.3.13. Just had Windows crashed and filters vanished. Also, after those crashes simplewall doesn't react the first time when a process trys to connect: have to restart Firefox a few times to be detected by simplewall.

**Comment by DebugDevil** [comment]
The problem is still there on 3.1.2. Windows 10 1903. Lost all filters. The 3rd time.

**Comment by meadows19** [comment]
Same happened here.
