### ISSUE TITLE
simplewall filter apparently messed up something in Windows

### ISSUE THREAD

**Issue by AlNexus** [henrypp/simplewall#1102]
So yesterday I used simplewall to block Steam from using Internet access. I have no idea how to use it so I assumed that I had to "Enable filters" to prevent the programs selected from accessing the internet, so I did exactly that.
  I think I blocked something important in Windows or I don't know, because after doing that and (some hours later) disabling the filters, Windows had gone to light mode (Default app mode: light mode) and now it seems to switch to that every reboot. I doubt it's something I installed. I really want help with this because it is kind of annoying and some dark mode app settings only apply after a reboot but after a reboot Windows goes back to light mode.
  I'm asking this in the simplewall repo issues because this only happened after using simplewall and blocking something from the system. Please help!

**Comment by Pandaa-P** [comment]
Doubt it's from simplewall, you need to repair missing or corrupted system files of your Windows
- https://support.microsoft.com/en-us/topic/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system-files-79aa86cb-ca52-166a-92a3-966e85d4094e
