### ISSUE TITLE
"Select all" button on apps menu

### ISSUE THREAD

**Issue by CaptainFrosty** [henrypp/simplewall#1105]
Since it doesn't look like there is any way to prioritize rules, it would be helpful to be able to select all apps in the blocklist rules, in order to deselect specific ones to let through. As it stands, I'd have to select every app manually. I'm not going to do that.

**Comment by henrypp** [comment]
Blocklist was apply for all apps by default.

**Comment by CaptainFrosty** [comment]
If I remember correctly, if I were able to select all the apps at once I'd be able to uncheck some and let them through the blocklist that way.
