### ISSUE TITLE
Insufficient accuracy when sorting by "Date" on the "Packages Log" tab

### ISSUE THREAD

**Issue by truekenny** [henrypp/simplewall#1107]
If several events occur in one minute, then sorting by date will not affect the order of the lines in the log for these events.

The current precision is limited to minutes, for example "**11.30.2021 12:32**".

A simple solution: you need to add seconds and fractions of a second to the date format, for example "**11.30.2021 12:32:33.12345**".
A little more complicated: when choosing to sort by date, you must actually sort not by the data of the column with dates, but by the auto-incrementing event identifier.

The picture shows an example: there are three events that happened in one minute, when sorting in ascending and descending order, the order in the table does not change. Expectation: the order must change.

![3](https://user-images.githubusercontent.com/3448197/144021449-f08faf91-eaac-42a0-84c9-6a1e06c9468c.gif)

**Comment by ericgl** [comment]
I agree.
simpleWall time format should also display seconds (HH:mm:ss) in the Packets log "Date" column.
Please see screenshot: https://i.imgur.com/VAJ5vqO.png

**Comment by henrypp** [comment]
It already sorted by timestamps with seconds.
