### ISSUE TITLE
[Feature Suggestion] Icon Caching 

### ISSUE THREAD

**Issue by Chaython** [henrypp/simplewall#1113]
With several hundred apps, the icon loading makes simplewall very slow, taking nearly >30seconds to be in a usable state as it tries to pull the various icons from each of the drives... [waiting for spin up] etc...

**Comment by Chaython** [comment]
Where is it loading from then? It's very slow. Simplewall is in portable mode on a NVME SSD.

**Comment by henrypp** [comment]
It very slow because loading not only icons, but signature and version informations, and some more.

Anyway it's all loading in worker threads so it does not affect ui.
