### ISSUE TITLE
simplewall can't delete apps originated from C:\Windows\System32 from its UI

### ISSUE THREAD

**Issue by Pandaa-P** [henrypp/simplewall#1120]
simplewall can't delete apps originated from `C:\Windows\System32` from its UI. Once an app trigger simplewall after wanting internet access it can't be removed from the UI, you can enable or disable them but can't remove them even though using the context menu or  pressing `Del` will show a conformation window for deleting the selected item. for example `svchost.exe` and bunch of other processes can't be deleted no matter what the user tried.  
- Before attempting deleting 
![p1](https://user-images.githubusercontent.com/85793213/145729388-9067461b-ae0f-4db5-a63a-cde60fd05f71.PNG)
- After attempting deleting (it still exist and can't go away, also tested it with bunch of other system processes)
![p2](https://user-images.githubusercontent.com/85793213/145729389-653e8ff3-53c7-4764-805a-ad0ea0d376d0.PNG)

**Comment by henrypp** [comment]
I know. You cant delete them because it is used.
