### ISSUE TITLE
Feature request: Automatically install Language Packs silently

### ISSUE THREAD

**Issue by cloudgreen** [henrypp/simplewall#1122]
Hi guys!

Is there a way to disable the constant language pack download notifications?

I suspect there is a big percentage of users running the product in English, and for whom the language packs are unnecessary. 

Here is how the feature could be implemented:

![image](https://user-images.githubusercontent.com/42112877/145971930-7b160c57-da69-4a97-b7cb-be584cbe561f.png)

Thanks for a fantastic product! 👍

**Comment by cloudgreen** [comment]
Anyone?

Bueller... Bueller? :)

**Comment by henrypp** [comment]
> Is there a way to disable the constant language pack download notifications?

This is not constant. 

Language updates maximum [once in a month](https://github.com/henrypp/simplewall/commits/master/bin/simplewall.lng), with some fixes.

> I suspect there is a big percentage of users running the product in English.

I think not only english people using this tool.

I think i cannot opt-out this feature.

**Comment by cloudgreen** [comment]
Thanks for your reply, @henrypp! I totally understand that language packs are important.

Would it be possible to make language pack updates automatic in the background instead?

(I have other non-technical people using my computer, and these kind of prompts make them nervous. :) I suspect others have the same scenario.)

**Comment by cloudgreen** [comment]
So instead maybe an opt-in feature like this?

![image](https://user-images.githubusercontent.com/42112877/147574694-ff6d7382-4e90-44aa-9302-69133bc1f80c.png)

**Comment by cloudgreen** [comment]
So, I keep saying "No" to this language pack update, but it keeps popping up several times... Is this by design, @henrypp?

![image](https://user-images.githubusercontent.com/42112877/147880750-064a3a2f-2da2-4907-90ec-206666a6fe67.png)

Could we have either the option "Never install LP updates" or the option "Always automatically install LP updates"? :)

Thanks for the fantastic software! ❤

**Comment by cloudgreen** [comment]
I'm going crazy... the same update window appeared today again:

![image](https://user-images.githubusercontent.com/42112877/148038174-f5811bb6-5844-4eb6-98af-7d2888067a0d.png)

**Comment by cloudgreen** [comment]
...it appeared again. :( What's happening, @henrypp?
![image](https://user-images.githubusercontent.com/42112877/149229076-84f19b8d-66e0-433e-ab9e-109aa3e873a9.png)

**Comment by henrypp** [comment]
Why you just does not update language pack?

**Comment by cloudgreen** [comment]
> Why you just does not update language pack?

So, please follow me in this logic:

1. You **can't say No** to LP updates (it will never stop asking)
\+
2. You should (**have to!) say Yes**

=
3. Always install LP's automatically in the background, without prompting. This would be best user experience, **since there is no point in asking.**

What do you say? 😀

Keep up the good work!

**Comment by cloudgreen** [comment]
Could we please make the installation of these automatic? Since everyone should always want them, there is need to ask?

![image](https://user-images.githubusercontent.com/42112877/155846062-f7bdf26d-ae22-469c-932c-d35aaf328126.png)

Thanks for a fantastic product! 😊

**Comment by cloudgreen** [comment]
Could you please consider automatic installation of language packs? :) Pretty please. ❤

![image](https://user-images.githubusercontent.com/42112877/163544096-9308b2ec-9be4-4215-9408-b273894a12f8.png)

**Comment by gettysburg** [comment]
dumb nigger

**Comment by cloudgreen** [comment]
![image](https://user-images.githubusercontent.com/42112877/165369284-2fc1dfc8-3ae3-42b4-bf10-9b3c6fafea09.png)

Thank you very much for this, @henrypp! Very convenient. 🙏😀 Keep up the great work!
