### ISSUE TITLE
Apps establish connection without asking

### ISSUE THREAD

**Issue by whotheff** [henrypp/simplewall#1124]
I started the app HWinfo and it immediately displayed notification that there is a newer version. That never happened to me with my old firewall app so I was amazed that it managed to get through Simplewall. Then i went to connections and found established connections via port 80 and 443. Then I checked the app list for ANY HWinfo entries and found nothing. 

Then on another PC I noticed that the Windows service: WpnService has connected to the internet, while it is in the "apps **without** internet access" graph.

how is this possible?

**Comment by cloudgreen** [comment]
Sounds weird! It hasn't happened to me during my years with Simplewall....

Do you have these default settings in place?
![image](https://user-images.githubusercontent.com/42112877/146249514-aa16198e-a8af-479c-be84-85db6d5e4753.png)

**Comment by whotheff** [comment]
Yes, I have them. However connection was not to 0.0.0.0 or 127.0.01, but to some external IP, where app successfully identified that there is a newer version. I repeated the test last night and it again managed to check for updates.

**Comment by gettysburg** [comment]
Hello, these hardware information tools like HWinfo are notorious for loading kernel drivers to be able to gather more information about your hardware, the reasoning behind that being that some of it can only be read from the kernel's virtual address space directly.

Now, a programmer could always choose to add networking capabilities to their driver, which their user-mode program then utilizes. However, Windows Filtering Platform (or WFP for short), has both user and kernel-mode components.

From MSDN, now apparently called Microsoft Docs:

```The only way for a filter to be bypassed is if a higher weight filter has permitted or blocked the traffic within the same sub-layer.```

So from my understanding, the driver would have to actively try to defuse the filters installed by simplewall.

I am not very familiar with WFP (the programming interface used by simplewall), so please wait for a reply from @henrypp.

Another thing you could try in the meantime is checking if the "Enable protection of installed filters" checkbox is checked, you can find it by pressing F2 inside simplewall to open the settings, and by navigating to the "Rules" section. This setting should be enabled by default, but who knows.

Even if it is checked, uncheck it and then re-enable it, and do the same thing you did with HWInfo - also try reloading all drivers (F5), play around with the whole thing a bit - if you manage to somehow get simplewall to block these unwanted connections, then I'm positive we can find a fix for it.

Alternatively, I could reverse-engineer their driver (usually a .sys file inside the application installation directory), if you send it to me - you can find my e-mail address on my profile.

Good luck :-)

**Comment by henrypp** [comment]
Open settings ->

1) Packets log -> Enable packets logging interface
2) Exclude -> Uncheck "Exclude allowed connections"

And watch what filters allowed hwinfo.

**Comment by gettysburg** [comment]
@henrypp I totally forgot to mention that, thanks :-)

**Comment by whotheff** [comment]
Thanks, will test it.

**Comment by whotheff** [comment]
Tested it, but for some reason the packets log remains empty. However there is data recorded in the log file:

"‎20.‎12.‎2021 ‎г. ‏‎21:32:51 ч.","**:\install\hw64_570\hwinfo64.exe","192.168.0.10","49205","172.67.205.235","443 (https)","tcp","FWPM_LAYER_ALE_AUTH_CONNECT_V4","TCPv4 connect filter","#65544","Outbound","Blocked"
"‎20.‎12.‎2021 ‎г. ‏‎21:32:51 ч.","**:\install\hw64_570\hwinfo64.exe","192.168.0.10","49204","104.21.22.164","443 (https)","tcp","FWPM_LAYER_ALE_AUTH_CONNECT_V4","TCPv4 connect filter","#65544","Outbound","Blocked"

After selecting the HWinfo app in the list with apps without internet access, none of the rules is applied to it.

**Comment by gettysburg** [comment]
According to that log, the connections were indeed supposed to blocked, however it seems like you are not running simplewall in "Block-all" mode, this is indicated to me by the filter name - "TCPv4 connect filter", this is a _custom, user-made filter_, internal filters are always prefixed with **"Internal\"**.

Can you show us your exported simplewall XML file (File -> Export) - redact sensitive information as needed.

Please also make sure that you are running the latest simplewall version, which at the time of this post is v3.6.1.

**Comment by cloudgreen** [comment]
> According to that log, the connections were indeed supposed to be blocked, however it seems like you are not running simplewall in "Block-all" mode, 

Just double-checking: isn't that also [what I asked in my first post ](https://github.com/henrypp/simplewall/issues/1124#issuecomment-995105490)(with the screenshot)? I don't mean to sound impertinent, I'm honestly just double-checking that "Block-all" it's the same thing. :)

**Comment by gettysburg** [comment]
@cloudgreen 

Yes indeed :-)

**Comment by henrypp** [comment]
> Tested it, but for some reason the packets log remains empty. However there is data recorded in the log file:

Packets log ui does not displays 3rd-party wfp providers, thats why packets log ui remains empty. 

```csv
"‎20.‎12.‎2021 ‎г. ‏‎21:32:51 ч.",":\install\hw64_570\hwinfo64.exe","192.168.0.10","49205","172.67.205.235","443 (https)","tcp","FWPM_LAYER_ALE_AUTH_CONNECT_V4","TCPv4 connect filter","#65544","Outbound","Blocked"
"‎20.‎12.‎2021 ‎г. ‏‎21:32:51 ч.",":\install\hw64_570\hwinfo64.exe","192.168.0.10","49204","104.21.22.164","443 (https)","tcp","FWPM_LAYER_ALE_AUTH_CONNECT_V4","TCPv4 connect filter","#65544","Outbound","Blocked"
```

This is not SW filters.

**Comment by whotheff** [comment]
Simplewall 3.6.1 64bit

Windows Version 6.1 7601 SP1

Setings->Rules - all have a checkbox except "Resolve network addresses"
Blocklists - all are = to Block

<?xml version="1.0" encoding="UTF-8"?>
<root timestamp="1640264385" type="3" version="4">
	<apps>
		<item path="AnyDesk" timestamp="1633873756" is_enabled="true" />
		<item path="W32Time" timestamp="1247546988" />
		<item path="C:\Program Files\simplewall\simplewall.exe" timestamp="1637785065" is_enabled="true" />
		<item path="System" timestamp="1637785065" is_enabled="true" />
		<item path="C:\Windows\system32\svchost.exe" timestamp="1637785065" is_silent="true" />
		<item path="C:\Windows\system32\lsass.exe" timestamp="1637785065" />
		<item path="C:\Program Files\Mozilla Firefox\firefox.exe" timestamp="1637786220" is_enabled="true" />
		<item path="C:\program files (x86)\anydesk\anydesk.exe" timestamp="1637954784" is_enabled="true" />
		<item path="C:\windows\explorer.exe" timestamp="1637960568" is_silent="true" />
		<item path="E:\install\rufus-3.17p.exe" timestamp="1637960638" is_silent="true" />
		<item path="C:\program files (x86)\qbittorrent\qbittorrent.exe" timestamp="1637962392" is_silent="true" />
		<item path="C:\windows\system32\mstsc.exe" timestamp="1637965766" is_enabled="true" />
		<item path="C:\program files (x86)\pc tools firewall plus\fwservice.exe" timestamp="1638286425" is_silent="true" />
		<item path="C:\users\*\appdata\local\fluxsoftware\flux\flux.exe" timestamp="1638286479" is_silent="true" />
		<item path="C:\program files\dc++\dcplusplus.exe" timestamp="1638289000" />
		<item path="E:\install\hw64_570\hwinfo64.exe" timestamp="1640028772" />
	</apps>
	<rules_custom>
		<item name="In qtorrent" rule_local="*****" dir="1" protocol="6" apps="C:\program files (x86)\qbittorrent\qbittorrent.exe" is_enabled="true" />
		<item name="In UDP qbittorrent" rule_local="*****" dir="1" protocol="17" apps="C:\program files (x86)\qbittorrent\qbittorrent.exe" is_enabled="true" />
		<item name="Out Torrent" apps="C:\program files (x86)\qbittorrent\qbittorrent.exe" is_enabled="true" />
		<item name="dcplusplus.exe" rule_local="*****" dir="1" version="2" apps="C:\program files\dc++\dcplusplus.exe" is_enabled="true" />
		<item name="DC++Out" is_enabled="true" />
		<item name="NTP" rule="192.168.0.1" version="2" apps="W32Time" is_enabled="true" />
	</rules_custom>
	<rules_config>
		<item name="UPnP" is_enabled="false" />
		<item name="RDP [outbound]" is_enabled="true" />
		<item name="SMB [outbound]" is_enabled="true" />
		<item name="NTP" is_enabled="true" />
	</rules_config>
</root>

screenshot of apps:
[https://i.ibb.co/MP0dYbB/1Capture.jpg](url)

**Comment by henrypp** [comment]
Are you understand? This is **not** SW filters.

**Comment by henrypp** [comment]
Try reinstall filters (disable,enable).
