### ISSUE TITLE
Request: track app signature changes

### ISSUE THREAD

**Issue by whotheff** [henrypp/simplewall#1125]
When an app changes it may be due to update, but also due to something else changing the .exe or trying to connect via already allowed app. Can Simplewell implement such option: to inform that an app was changed since it's last start and ask if we still allow it to connect and if any other app is trying to connect through an already allowed app?

**Comment by henrypp** [comment]
#394

**Comment by tamr** [comment]
I second this, hash checking is pretty useful. Jetico and Look'n'stop had this great feature.
