### ISSUE TITLE
Blank prompt window?

### ISSUE THREAD

**Issue by realrobd** [henrypp/simplewall#1134]
![Screenshot 2021-12-30 181429](https://user-images.githubusercontent.com/5965468/147793822-8baf42f8-3fd7-472b-a6cf-42ab595e80a5.png)

**Comment by ags1234** [comment]
For me, the network alert window contents look offset in Windows 11. It looked all right until a couple of days ago, and then it modified by itself. Now, it looks like this:

![simplewall_2ic7gB8SGb](https://user-images.githubusercontent.com/21011513/147816192-872df7aa-4b92-4fbf-84f5-4127abd17071.png)

**Comment by henrypp** [comment]
dup #1009
