### ISSUE TITLE
"empty" Not Blocking

### ISSUE THREAD

**Issue by schoolprivacy** [henrypp/simplewall#1135]
Hello

Every time I install a new program on Windows 10, i do not get a notification, and the firewall does not block that program.

When i look at the packet logs, it shows as "empty" and is allowed.

I have to create a rule manually to block the software from accessing the internet.

When i have created the rule, the program name shows up instead of empty.

**Comment by Powsey** [comment]
Hello, before doing anything with rules. 
Have you clicked on "activate filters" so the filtering of all programs is on?

**Comment by schoolprivacy** [comment]
Hello 

Yes the firewall is activated.  I do get some notifications on few programs, but the majority do not and show as *empty and automatically connect to the internet until I add a rule manually.
