### ISSUE TITLE
Avira update

### ISSUE THREAD

**Issue by cinke** [henrypp/simplewall#114]
I use Avira on my PC.
Avira updates by creating a random folder in ProgramData folder (like ughnbh567), extracting update.exe to that folder, and trying to run it from there.
How can I let update.exe through? By the time I click Allow, it is too late.
Can a general rule (like connect to a certain IP is allowed) be applied to all programs on a PC?
Or how to let Avira update, with random exe path?
Thanks

**Comment by cinke** [comment]
I edited rules_system.xml and added a rule there. Seems to work.

**Comment by ddd111ddd** [comment]
File > Add file

**Comment by cinke** [comment]
Not working.
Update.exe is always in a random, new folder.

Update starts:
ProgramData\Avira\RAndom1\update.exe created.
It fails to connect, as firewall blocks it.
Avira deletes the file mentioned above.

Few minutes later tries again, but this time with
ProgramData\Avira\Random2\update.exe

Etc.

2018-01-17 18:12 GMT+01:00 ddd111ddd <notifications@github.com>:

**Comment by henrypp** [comment]
https://www.avira.com/en/support-for-home-knowledgebase-detail/kbid/650

**Comment by cinke** [comment]
Sorry, not clear for me.
Can user rules be applied to all, not just selected programs? To those that not yet even present?
I thought applying a user rule is possible when you right click a known program and choose Settings - Allow.

**Comment by tokariu** [comment]
I had the similar problem.
I set up a global rule for the AV update server IPs. 
However, the next time Avira wants to autoupdate signatures, it creates again a random update.exe. Simplewall doesn't know this new random update.exe and asks again via pop-up if it should allow to connect. The update is working, though, because the global rule for the update-server IPs seems to be active. But you'll get an annoying firewall popup everytime AV creates an update.exe and tries to connect to their servers. 

How to solve this?

**Comment by cinke** [comment]
Like henrypp wrote.
Next time the popup comes up, tick the ip address to create a rule for that
ip.
Then go to Settings, user rules, right click on the recently created rule
to edit. In the right side of the window you see the list of programs you
can assign this new rule to.
Untick update.exe so that no programs are selected.
Now it is a global rule that applies to all programs.
Avira uses several ip s, so you will have to repeat this for a couple of
times.
Hope this helps.

2018. febr. 12. 17:36 ezt írta ("tokariu" <notifications@github.com>):

**Comment by tokariu** [comment]
Ok, then the problem is or was, that the randomly generated update.exe not only connects to aviras update server IPs, but also to a few other IPs... i guess as soon as I add these to global allows it won't popup anymore. (and obviously i had some IPs missing update.exe wants to connect to)
