### ISSUE TITLE
Add two options to the program - simplewall

### ISSUE THREAD

**Issue by radio222** [henrypp/simplewall#1140]
I suggest:
1) In the settings, be able to configure the scale (decrease in 1.5 - 2 - 3 times) the "Network alert" pop-up window,

2) Add a Dark theme both into the shell and in the Network Notifications pop-up window "Network alert".
Example, as is implemented in the program: Netlimiter 4.1.12.0
Registration settings:
- White,
- Dark grey,
- Black.

The rest of the program is excellent.

**Comment by henrypp** [comment]
1) SW used is permonitor dpi aware, this option is unused.
2) https://github.com/henrypp/simplewall/issues/248#issuecomment-766141048
