### ISSUE TITLE
Simplewall doesn't launch on system startup 

### ISSUE THREAD

**Issue by helpthemfix** [henrypp/simplewall#1141]
Hey guys.

I use windows 10 with a standard user account. despite setting the option "Load on system startup", Simplewall doesn't load and I have to launch it myself. Is this a bug or there's a way around this in a standard windows user account?

**Comment by Theo-user** [comment]
Is it disabled under startup in Task Manager?

**Comment by helpthemfix** [comment]
> Is it disabled under startup in Task Manager?

It's not listed there since I moved to a standard account but it was there on the administrative account. Tried reinstalling to no avail.

**Comment by hppyworld** [comment]
I have the same issue. I think problem is for Standard account type do not start simple wall as it requires admin rights. 
Is there any way to fix it so that simplewall can still launch and run for standard user without needing to enter administrator account password ?  
Thanks

**Comment by helpthemfix** [comment]
> I have the same issue. I think problem is for Standard account type do not start simple wall as it requires admin rights. Is there any way to fix it so that simplewall can still launch and run for standard user without needing to enter administrator account password ? Thanks

Wondering about the dame thing. I hope there's a way.

**Comment by sh3kh4r** [comment]
Try this :)
[simplewall how to silent start.pdf](https://github.com/henrypp/simplewall/files/8086262/simplewall.how.to.silent.start.pdf)

!! Don't forget to remove any registry entries that you may have manually made !!
Let me know if it works for you guys +1 .. @Theo-user @hppyworld @helpthemfix @hho2002 @adeii

**Comment by helpthemfix** [comment]
> Try this :) [simplewall how to silent start.pdf](https://github.com/henrypp/simplewall/files/8086262/simplewall.how.to.silent.start.pdf)
> 
> !! Don't forget to remove any registry entries that you may have manually made !! Let me know if it works for you guys +1 .. @Theo-user @hppyworld @helpthemfix @hho2002 @adeii

I'm in Stadnard user account in Windows 10 and the task was not there.

**Comment by sh3kh4r** [comment]
> > Try this :) [simplewall how to silent start.pdf](https://github.com/henrypp/simplewall/files/8086262/simplewall.how.to.silent.start.pdf)
> > !! Don't forget to remove any registry entries that you may have manually made !! Let me know if it works for you guys +1 .. @Theo-user @hppyworld @helpthemfix @hho2002 @adeii
> 
> I'm in Stadnard user account in Windows 10 and the task was not there.

I came across this, I haven't tried it with simplewall, but it looks like something you would need to get elevated privileges:
https://www.sordum.org/9416/powerrun-v1-6-run-with-highest-privileges/

**Comment by henrypp** [comment]
simplewall create autorun entry in HKCU registry key.

You can create entry in HKLM by yourself.

**Comment by adeii** [comment]
> Try this :) [simplewall how to silent start.pdf](https://github.com/henrypp/simplewall/files/8086262/simplewall.how.to.silent.start.pdf)
> 
> !! Don't forget to remove any registry entries that you may have manually made !! Let me know if it works for you guys +1 .. @Theo-user @hppyworld @helpthemfix @hho2002 @adeii

Silent start works on Win8. Listed programs are blocked by default, until SimpleWall is started then I got confirmation dialog to allow program to connect,
