### ISSUE TITLE
Hide Apps cluttering

### ISSUE THREAD

**Issue by Klemci** [henrypp/simplewall#1142]
The Applications  (1st Tab) list has too much .exe listed (blocked), i can't hide those i know i'll never accord internet access. Cluttering.

Is it possible to hide this ones ?

**Comment by henrypp** [comment]
1) Remove unused apps.
2) Groups can be collapsed.

**Comment by Klemci** [comment]
Thanks,

but that's not the point, i want to hide apps that are available (not ones with mising exe/app).
This apps that i will never need to change setting, because will be kept blocked but clutter mylist, the list containing alsdo apps that i grant access when i need.

I search a solution to specify specific apps to not show-up in the UI...

Image with text :
https://drive.google.com/file/d/1SJlzRO30bvWA-mz84w4TO_k0Zw8Z2tj3/view?usp=sharing
Sorry text's bad quality, it says  :
 I want to hide those from the list
never need to edit internet access

AND

I DO NOT need to hide it
in case at any moment
it needs access internet

Thanks again
