### ISSUE TITLE
Auto Allow any app except blocked apps

### ISSUE THREAD

**Issue by anwar-alsilwy** [henrypp/simplewall#1144]
Hi,
I just want to add all blocked apps to simplewall, then I want to Allow all new applications to access Internet automatically without notification or prompt message,
How can I do that ?

**Comment by Theo-user** [comment]
Why have a firewall in the first place?

**Comment by henrypp** [comment]
https://github.com/henrypp/simplewall#q-where-is-blacklist-mode

**Comment by anwar-alsilwy** [comment]
What about (svchost.exe) when I add it to blocked rule, the network not connecting at all, could you explain why please ??
