### ISSUE TITLE
Feature request: Automatically allow new apps while creating rules for them

### ISSUE THREAD

**Issue by vinha** [henrypp/simplewall#1146]
Currently Simplewall can be configured these ways:
- Show notifications for new apps (default, creates a rule, blocks if user doesn't allow)
- Hide notifications for new apps (blocks connection and adds app to blocked list)
- Allow all new apps (blacklist mode, doesn't add any rules, only blocks already blocked)

How about an extra one:
- Allow all new apps, but create a rule for each new app

In other words, it's same to "Hide notifications", but instead of creating a block rule, it would create an allow rule.

This way the user doesn't need to be bombarded with notifications, but could later go through the rules and move the unwanted apps to blocked. I'd call it learning mode, but it is opposite to one described in https://github.com/henrypp/simplewall/issues/696.

**Comment by cinderblock** [comment]
I think this feature is sorely missing. When I'm setting up a new computer, I want all connections to be silently allowed **and** added to the "allowed" list. Personally, I trust all of the connections that come with the OS. When setting up a new system, many apps need an initial internet connection for installation. As it stands, I need to try installing most things twice. The first time has a firewall issue, I allow the app, and then it installs normally (unless it needs subsequent web connections from other binaries).

It's only once I hand it off to users that I want *every* new connection to be blocked by default. I can be trusted, they cannot.

**Comment by GabPierre08** [comment]
yea i need this feature too

**Comment by Ferosauce** [comment]
bump

**Comment by cinderblock** [comment]
@henrypp What is "invalid" about this?

**Comment by henrypp** [comment]
@cinderblock no "automatically" will be

**Comment by cinderblock** [comment]
As in you're against a feature that "automatically" does something?

Would you accept a PR that added this feature as a temporary opt in? Like "Automatically accept all applications for the next 5 minutes"?
