### ISSUE TITLE
Feature request: Timed block option?

### ISSUE THREAD

**Issue by aedelred** [henrypp/simplewall#1147]
I would like to suggest having a timed block option just like the timed approve option. I find this useful for testing functionality without network. I know I could delete the rule later, but sometimes I forget and it would be nice to have a prompt again after a set amount of time, just like the temporary approval option.

Thanks for your consideration.

**Comment by 4evermaat** [comment]
I agree 1000% with this suggestion.  The block feature should not only be permanent.  There should be timers.   Like 30 min, 1 hr, 3 hrs, until computer restart, etc

Often times, you want to see how rules affect your system on a temporary basis.

**Comment by iamPanka** [comment]
Yeah, I like it too

**Comment by henrypp** [comment]
@4evermaat

>until computer restart

already exists.

**Comment by iamPanka** [comment]
Hello, I saw this issue as closed, but I don't find a timer on block button. Am I missing something in settings or something else? Thanks
![immagine](https://github.com/henrypp/simplewall/assets/16743807/e3b964e2-bfe6-4001-81ad-713dc2577ba1)

**Comment by madmarxofficial** [comment]
Hi, I'm waiting for this feature too. As @iamPanka said, it would be so great to have the same dropdown options for Block as for Allow.
Can you reopen please?

**Comment by madmarxofficial** [comment]
up

**Comment by madmarxofficial** [comment]
You should stop being rude and try to understand the subject we're talking about.
We're talking about adding a dropdown menu in the Block button (same as Allow button) in the **Alert popup**.

![image](https://github.com/henrypp/simplewall/assets/26455178/6cb79a04-1f1e-49cc-9f48-5a1a353ce2d3)

**Comment by henrypp** [comment]
@madmarxofficial for fucking sake block need dropdown, id dit not understand

**Comment by madmarxofficial** [comment]
Up. Can you reopen please?

**Comment by henrypp** [comment]
no, it is unusefull

**Comment by 4evermaat** [comment]
> @madmarxofficial no, it is unusefull

While you might think so, can you consider that several other users might see the ability to adjust the `block` connection length directly from the notification prompt as very helpful for their workflow??   It's convenient and less steps.

You don't have to remove other methods.   This is just an additional method.    Please consider it.
