### ISSUE TITLE
New block rules from WindowsSpyBlocker

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#115]
I was wondering if any new entries from the WindowsSpyBlocker project could be automatically added, since the block rules don't make much sense as long as they aren't kept up-to-date. There have been some updates to it since the last release of simplewall.

**Comment by ltGuillaume** [comment]
Just to let you know, WindowsSpyBlocker updated 12 hours ago. https://github.com/crazy-max/WindowsSpyBlocker/releases/tag/4.11.0

**Comment by henrypp** [comment]
Just to let you know, simplewall blocklist updated 7 hours ago (also contained in v2.2 release).

**Comment by henrypp** [comment]
Just to let you know, simplewall blocklist updated 7 hours ago (also contained in v2.2 release).

**Comment by ltGuillaume** [comment]
Great, thank you!
