### ISSUE TITLE
Not Displaying Packet Notifications, nor logging packets. Very strange behavior

### ISSUE THREAD

**Issue by ElectricityMachine** [henrypp/simplewall#1153]
**OS**: Windows 10 x64 21H2
**Versions**: 6.5.3, 6.6, 6.6.1

**Description**: After making a new user profile, and reinstalling Simplewall, the program no longer detects packets and whenever I enable filters, _nothing_ has access to the Internet unless I add it manually. The "Enable Packets Notifications" option is selected.

As well as the aforementioned bug, whenever I re install Simplewall, the program starts automatically before I even finish the install. Extremely strange behavior. The regular simplewall.log file contains nothing when I enable logging too, however, the debug log contains some weird things.

`Level,Date,Function,Code,Description,Version,OS Version
"Warning","‎2/‎7/‎2022 ‏‎1:16:23 AM","FwpmNetEventSubscribe","0x00000005","(null)","3.6.1","10.0 build 19044"
"Warning","‎2/‎7/‎2022 ‏‎1:16:23 AM","FwpmNetEventSubscribe","0x00000005","(null)","3.6.1","10.0 build 19044"
"Warning","‎2/‎7/‎2022 ‏‎1:19:34 AM","FwpmNetEventSubscribe","0x00000005","(null)","3.6.1","10.0 build 19044"
"Warning","‎2/‎7/‎2022 ‏‎1:19:34 AM","FwpmNetEventSubscribe","0x00000005","(null)","3.6.1","10.0 build 19044"
"Warning","‎2/‎7/‎2022 ‏‎1:19:43 AM","FwpmNetEventSubscribe","0x00000005","(null)","3.6.1","10.0 build 19044"

`
The same output for the debug log is observed each time I start the program, and each time I enable or disable filters.

**Comment by ElectricityMachine** [comment]
Fixed by running setup.exe from a Windows boot media USB stick.

**Comment by ElectricityMachine** [comment]
This is now happening after an unknown Windows update installed itself. I am unable to isolate the issue without doing a clean reinstall, but it _definitely_ has something to do with a recent update, as it was working completely fine earlier. I have to switch back to Windows Firewall (ew) for the time being, and if there's anything else I can do, please let me know. The symptoms and errors are the same as when I initially opened the bug.

**Comment by henrypp** [comment]
May help #1133

**Comment by rudolphos** [comment]
Same problem. 1 minute browsing web and no packets. ![image](https://user-images.githubusercontent.com/4366810/209495804-496058fd-ae4e-4459-881e-d8bfa1141963.png)
Connections are showing though.
