### ISSUE TITLE
Auto purge invalid entries

### ISSUE THREAD

**Issue by g-k-m** [henrypp/simplewall#1155]
Hello, currently there is an option from Edit -> Purge unused apps that deletes useless entries of files that no longer exist in that path

It would be nice though not that important if you could have an option, toggle on or off, to auto-purge invalid entries. Meaning as soon as simplewall detects that an entry is invalid and thus would color it in red, just remove it if the option is toggled on

**Comment by GitCurious** [comment]
+ Delete invalid on reboot ?

(rather than constant polling)

**Comment by phonosys** [comment]
this will be hella helpfull.. purge invalid entries on startup will do the trick :)

**Comment by ericgl** [comment]
Yep, this should be implemented: Auto-remove files that no longer exist. 
Win10-Win11 do this all the time when UWP apps get updated, and the previous version no longer exists in the system.

**Comment by jcrevani** [comment]
Agree.

**Comment by henrypp** [comment]
in latest ver it realized already, i think, and yes, there is no logic to save unused apps into profile
