### ISSUE TITLE
[Feature Request] User Rules: Add option put rules in a custom order

### ISSUE THREAD

**Issue by Rexadev** [henrypp/simplewall#1156]
Example - 

- I want to block all traffic except DNS,DHCP, HTTP/S. 
- So I create a rule - Any Protocol, Any Family, Any Direction, Block, on Remote Rule `1-65534` to block all network.
- To only allow (DNS,DHCP, HTTP/S. ) I create a rule - Any Protocol, Family IPv4, Direction - Outbound, **Allow** , on Remote Rule  `53,80,443,67-68`

- There is also Use for Block Rule after Allow
- To Block All IPv6, Block All Network,....

**Comment by nior-t** [comment]
What about creating the second rule and checking `Rules - Disable notifications`? (If you have selected `Settings - Rules - Block outbound connections for all`)

**Comment by Rexadev** [comment]
> What about creating the second rule and checking `Rules - Disable notifications`? (If you have selected `Settings - Rules - Block outbound connections for all`)

I don't understand

**Comment by nior-t** [comment]
By default all connections are blocked by checking `Settings - Rules - Block outbound connections for all`. So as i understand you dont need a block all rule for a program, everything what is not allowed by a rule will be blocked. And by enabling `Rules - Disable notifications` in the Apps tab for a program SW will not ask for a rule for a new connection and will silently block it.

**Comment by Rexadev** [comment]
> By default all connections are blocked by checking `Settings - Rules - Block outbound connections for all`. So as i understand you dont need a block all rule for a program, everything what is not allowed by a rule will be blocked. And by enabling `Rules - Disable notifications` in the Apps tab for a program SW will not ask for a rule for a new connection and will silently block it.

What I understand is, That is for making news apps by default not having internet access. If outbound connections is blocked internet will not work.
