### ISSUE TITLE
Make Rules windows tabs resizable

### ISSUE THREAD

**Issue by Rexadev** [henrypp/simplewall#1163]
![image](https://user-images.githubusercontent.com/62152714/154787804-3ce5e18a-ceca-436e-b5ef-7a65bfc9f0d4.png)

**Comment by Pandaa-P** [comment]
Do you mean the main window of Rules? it's resizable and you can do that by putting the mouse on the border and then can shrink or stretch the window
![Untitled](https://user-images.githubusercontent.com/85793213/155801348-5b8d360e-a2eb-41c3-83b0-b43cf5e5b42d.png)

**Comment by Rexadev** [comment]
> Do you mean the main window of Rules? it's resizable and you can do that by putting the mouse on the border and then can shrink or stretch the window )

No, the space between local and remote rule.
