### ISSUE TITLE
Application location and alerts

### ISSUE THREAD

**Issue by FritesMoules** [henrypp/simplewall#1164]
Hi,

First I'd like to thank the developper for this awesome piece of software, I love it  :))

My issue is: on my computer when Windows starts, Simplewall always triggers an alert saying that an Adobe app wants to access internet.
This is a legit app, no problem at all, so everytime the alert is triggered I create a rule to allow internet access, but the alert keeps coming back at every boot, this is pretty annoying.

I finally understood the reason why: although the name of the app is always the same, it appears to  be located in a different folder everytime: it's always located in a different subfolder of my user Temp folder.
This is why all the rules I create everytime don't work because next time the app tries to access internet, it's interpreted by Simplewall as a new app so Simplewall triggers an alert again.

So my question is: is there a way to tell Simplewall "Allow internet acces to the app named "adobe_xxxx", no matter where this app is located".

Thank you in advance for the help,

**Comment by Pandaa-P** [comment]
But why you run the app from the temp folder? do you run it from within an archive file or are you using some sort of portable app that dump the contents in temp folder? there is no feature in Simplewall  or any firewall I know of that allow apps to run by names, that very risky. The solution is to make a folder and copy your Adobe app in and whitelist it in Simplewall.

**Comment by FritesMoules** [comment]
> But why you run the app from the temp folder? 

I really don't know! I just installed my Adobe apps with all default settings and it ended up like this.
I don't even run this app myself actually: the app is "creativecloud.exe", I think it's the updater of Creative Cloud app, hence it needs access to internet (or maybe it's something else I really don't know).
Anyway I don't see how I could change the location of this app.
But, strangely, the issue didn't happen at all recently, maybe Adobe changed something? I don't know.

Thank you so much for your answer anyway.

**Comment by henrypp** [comment]
User rules with specified ips?
