### ISSUE TITLE
Empty window Simplewall Alert

### ISSUE THREAD

**Issue by o20x** [henrypp/simplewall#1167]
After updating Simplewall new Alerts showing white windows without anything.

![Screenshot_43](https://user-images.githubusercontent.com/81172279/156092165-02cd11ef-9296-4f14-8671-850e6f2a166f.png)

**Comment by henrypp** [comment]
#1009

**Comment by o20x** [comment]
Thanks, changing resolution and scaling then return it back fixed it. 👍
