### ISSUE TITLE
[Help] How to only allow ports 49152-65535 for 127.0.0.1 

### ISSUE THREAD

**Issue by Rexadev** [henrypp/simplewall#1168]
I have blocked ports 49152-65535 for all.

**Comment by MASTREX** [comment]
Loopback is already allowed by default

**Comment by Rexadev** [comment]
> Loopback is already allowed by default

I know I wan to block ports 49152-65535 for every IP except 127.0.0.1

**Comment by MASTREX** [comment]
For other IPs all ports are blocked

**Comment by Rexadev** [comment]
127.0.0.1:1-65535
