### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by Rexadev** [henrypp/simplewall#1170]

**Comment by DomOBU** [comment]
You should find the answer in:
https://github.com/henrypp/simplewall

in paragraph Rules editor-Rule syntax format by expanding it

**Comment by Rexadev** [comment]
@DomOBU  got it I am saying simplewall doesn't have IP:Portx-Port

**Comment by DomOBU** [comment]
@Rexadev 
I am testing simplewall on another laptop than the one I use daily.

On my daily laptop I use another FW. During the installation a rule for the local loopback was created with the correct @ range but without the port range 49152-65535.

On the laptop where I test simplewall I created a rule for the local loop in 2 steps: the 1st one by entering the @ range and in the 2nd one the port range 49152-65535 (see screenshot).

![Règle simplewall](https://user-images.githubusercontent.com/95876663/162588089-9fc9ccea-e1c6-47c6-89f9-803790d13ddf.png)

**Comment by Rexadev** [comment]
Would not that rule mean allow 127.0.0.0/8 or ANY using port 49152-65535.

**Comment by DomOBU** [comment]
@Rexadev
I have unchecked in the settings panel "Allow loopback connections for all".
Once the rule was created, I assigned it to a few programs so it only applies to those programs.

**Comment by Rexadev** [comment]
Ok but that doesn't answer how to allow 255.255.255.255:1024-65535
