### ISSUE TITLE
svchost has many different parameters?  can you block each instance separately?

### ISSUE THREAD

**Issue by 4evermaat** [henrypp/simplewall#1171]
Coming from WFC,  each different instance of `svchost.exe` is blockable and there is a separate prompt for each one.  So for example, I might allow DNS server, but disallow SSNP discovery.  (There are only a handful of `svchost.exe`  instances that are REQUIRED to connect to the internet.

**Comment by gettysburg** [comment]
Yes, just block ``svchost.exe``, that works fine for me.

If it doesn't, post config.
