### ISSUE TITLE
[Question] How to Allow File Sharing

### ISSUE THREAD

**Issue by J0n1k4** [henrypp/simplewall#1176]
Hi all,
I want to configure file synchronization between my Android phone and Windows11 PC.
I have installed SyncMe app on my phone, and I try to scan the network for my PC's IP address, but It can't be found. 
The local network is set as "Private", and I have some folders set as shared, but I can not discover my PC...
Thanks in advance

**Comment by J0n1k4** [comment]
Ok, after some tryal and errors, I have enabled SMB (inboound and outbound) system rules, udp protocol.
Now my phone detects my PC, but I get the notification:
"Netbios name not available (port 137 is blocked?). 
Sync may not function properly."

Continuing the experiment... I will post here if I manage to find a solution by myself.  Hopefuly nothing will burn...

**Comment by ThyHodler** [comment]
Hi, got any luck with it?

**Comment by henrypp** [comment]
You forgot about that netbios is working over network and also available in system rules?

**Comment by J0n1k4** [comment]
> You forgot about that netbios is working over network and also available in system rules?

I forgot nothing - because I didn0't know anything at the begining.  
I have very limited knowkedge about networking. I use PC for 40+ years, it is my work tool, I service my operating system / software by myself -  but I just don't know the networking...
I ended up uninstalling "SyncMe" and installing "SYNCTHING". Simplewall likes Syncthing, and I am able to sync folders on my PC / Android.
As you can see - I am choosing my software based on the fact - does SIMPLEWALL (dis)like it or not... 
:)

Cheers,
Nika

p.S. - I try to search help and/or internet for some guides to try to fix problems by myself before I ask for help. It looks like I either didn't have enough knowledge to reckognise the fix, of I didn't find it at all...
