### ISSUE TITLE
Cloned latest code 3.6.1 & routine 2.4 and its throwing errors.

### ISSUE THREAD

**Issue by kasirajan22** [henrypp/simplewall#1177]
![image](https://user-images.githubusercontent.com/64265182/159676747-f0d49aca-2d50-4ee3-9319-3ca7d6ee46b3.png)

**Comment by kasirajan22** [comment]
any one facing this issue?

**Comment by henrypp** [comment]
you can use tags

https://github.com/henrypp/simplewall/releases/tag/v.3.6.1
https://github.com/henrypp/routine/releases/tag/v.2.3.1
