### ISSUE TITLE
A suggestion needed -

### ISSUE THREAD

**Issue by clicky6** [henrypp/simplewall#1178]
I just needed a suggestion :-
Is there any option to update Windows 11 if I have paused (blocked) all updates using Simplewall.
Any app or something like that.

**Comment by nior-t** [comment]
You can check update history for cumulative updates https://support.microsoft.com/en-us/help/5006099
There are links to microsoft update catalogue, you can install downloaded packages using `dism`

**Comment by gettysburg** [comment]
@nior-t While ``dism`` would work, you can also simply click on the downloaded .msu file, and the standalone update installer will take care of it, at least on my system (Windows Server 2019, which is essentially a stripped-down Windows 10), that tool was assigned to that file extension.

![image](https://user-images.githubusercontent.com/2256003/161435124-e5d2faa5-a9ae-4adb-8eed-b623875510e8.png)

@clicky6 

The Windows Update Catalog can be found [here](https://www.catalog.update.microsoft.com/Home.aspx), and it is reachable even if you enabled all three block-lists, like I did.

**Comment by gettysburg** [comment]
@nior-t While ``dism`` would work, you can also simply click on the downloaded .msu file, and the standalone update installer will take care of it, at least on my system (Windows Server 2019, which is essentially a stripped-down Windows 10), that tool was assigned to that file extension.

![image](https://user-images.githubusercontent.com/2256003/161435291-3bb5a935-927c-473f-9242-87f838da0e5f.png)

@clicky6 

The Windows Update Catalog can be found [here](https://www.catalog.update.microsoft.com/Home.aspx), and it is reachable even if you enabled all three block-lists, like I did.
