### ISSUE TITLE
Special rules

### ISSUE THREAD

**Issue by DomOBU** [henrypp/simplewall#1181]
I just installed Simplewal and haven't activated it yet.

Is it possible to apply 2 special rules to an application, for example one for UDP with some ports and one for TCP with other ports ?

**Comment by gettysburg** [comment]
Sure :-)

**Comment by gettysburg** [comment]
Yes, you can create as many rules as you want for a single application.

Please do not abuse the issue tracker for questions like this, and close this "issue".

Thank you.
