### ISSUE TITLE
Ports 21 and 22 blocked after removing Simplewall

### ISSUE THREAD

**Issue by xberg** [henrypp/simplewall#1184]
Hi,
I removed / deleted simplewall yesterday after testing it for a few hours. 
Today I am no longer able to access any FTP sites through filezilla (port 21 and 22) and I can not longer SSH through Putty (port 22). 
I am not sure this is simplewall's fault but I have very strong suspicions. 
Simplewall was removed via Windows' Add / remove programs. 
Disabling Windows Defender's firewall does not fix my issue. 
Trying to connect to these FTP sites though other computers on my network works. 

Any help would be much appreciated : I have already spent a long time on this issue.

EDIT: if I reinstall simplewall and enable filezilla in simplewall I can access FTP. So my question becomes: how can I remove simplewall and still connect to FTP / Putty?

**Comment by xberg** [comment]
Well I found my answer in Simplewall's documentation:

"When you uninstall simplewall, all previously configured filters stay alive in system. To remove all filters created by simplewall, start simplewall and press "Disable filters" button."

And it works.

May I suggest that a standard uninstall does this automatically? ie - this in my opinion should be the default behavior. Because I spent hours trying to find how I could unblock these ports...

**Comment by ericgl** [comment]
I agree. The uninstall procedure should notify the user that all filters will be removed and do so automatically.

**Comment by gettysburg** [comment]
The installer and uninstaller are generated by NSIS, so Henry has no influence on it's source code, and even if it was written by him he would have to port a lot of code from simplewall.

However, NSIS is quite customizable, and he could invoke simplewall with the ``-uninstall`` parameter which removes all filters, before deleting all files, folders and registry entries.

@henrypp

**Comment by gettysburg** [comment]
The installer and uninstaller are generated by NSIS, so Henry has no influence on it's source code, and even if it was written by him he would have to port a lot of code from simplewall to make deleting the filters by the uninstaller possible.

However, NSIS is quite customizable, and he could invoke simplewall with the ``-uninstall`` argument which removes all filters, before deleting all files, folders and registry entries.

@henrypp
