### ISSUE TITLE
can't sync time to time.windows.com

### ISSUE THREAD

**Issue by laurentvv** [henrypp/simplewall#1187]
I did not find the option that activates the time sync I thought it was NTP, but no it does not work the sync to time.windows.com does not work

**Comment by Theo-user** [comment]
Did you enable NTP under Services?

**Comment by laurentvv** [comment]
can't see NTP under services, another name ?

**Comment by Theo-user** [comment]
> can't see NTP under services, another name ?

Sorry, I meant System Rules.

**Comment by savchenko** [comment]
I see no issues with a single custom rule for `svchost.exe`. Simply allow outgoing UDP/123 to the IP of your NTP server.
