### ISSUE TITLE
how? run simplewall with highest boot priority before PC connects to internet?

### ISSUE THREAD

**Issue by grand-lotus-iroh** [henrypp/simplewall#119]
How do I make it so simplewall has the ultimate, highest boot priority? i have a few other programs, like ShareX and even Mailbird that launch and run before simplewall is even loaded. 

How do I make it so simplewall launches when Windows Defender launches (or even before)?

**Comment by ddd111ddd** [comment]
Settings > Rules > Enable boot-time filters

**Comment by ddd111ddd** [comment]
@henrypp shouldn't _boot-time filters_ be enabled by default?

**Comment by grand-lotus-iroh** [comment]
+1 for Enable boot-time filters*

On 2/1/2018 6:34:56 PM, ddd111ddd <notifications@github.com> wrote:
@henrypp [https://github.com/henrypp] shouldn't boot-time filters be enabled by default?

**Comment by henrypp** [comment]
> Settings > Rules > Enable boot-time filters

No. All installed filters are working _even if simplewall terminated_.
Enable boot-time filters is added for another purposes.

**Comment by grand-lotus-iroh** [comment]
Does that mean all software and applications that are launched and run before SimpleWall is loaded are able to connect to the internet?

What is the purpose of boot-time filters?

**Comment by henrypp** [comment]
@grand-lotus-iroh, No, connections processed by Base Filtering Engine (BFE) and it's started before logon UI shows. If you can block all connections before BFE starts, use "Enable boot-time filters" (experts feature).

**Comment by MycroftHolmes1989** [comment]
Do the rules and filters persist even when SimpleWall is uninstalled?

**Comment by henrypp** [comment]
Answers in topic, Sherlock!
