### ISSUE TITLE
[Feature Request] Custom user blocklist of IP's and ports

### ISSUE THREAD

**Issue by AfanasievAA** [henrypp/simplewall#1205]
Add ability to create a custom blocklist of IP's and ports. So added to this custom blocklist IP's are blocked for all processes and no logging in packet filter occurs.
Possible format of blocklist.ini file might be
`104.46.162.224:443
104.73.92.134:443
104.73.92.134:80
104.73.92.56:443
13.69.239.73:443
13.69.239.74:443
178.79.212.129:80
184.51.233.240:80
184.85.154.29:80
185.213.20.18:443
188.114.98.128:80`

**Comment by gettysburg** [comment]
Until a feature like this gets added, you could save your configuration file and open it with an advanced editor such as Notepad++,
then use it's features (Regular Expressions, Find and Replace, et cetera) to convert your list of IP's and hostnames to a "simplewall"-friendly format, and load that file afterwards.

Hacky, I know, but this is what I would do.

**Comment by AfanasievAA** [comment]
Thanx for an advice ). I've tried before already editing XML file and importing it into Simplewall. Unfortunatelly my blocklist is too big to fit intio a simplewall rule. It is now consists of 180 IP's and it will grow in time.
