### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by DomOBU** [henrypp/simplewall#1207]
Windows 11 Famille – 21H2 22000.613 – simplewall 3.61

Even if "Show confirmation dialog on exit" is selected, when you click on exit no dialog appears.

**Comment by henrypp** [comment]
what do u do?

**Comment by DomOBU** [comment]
Additional information.

With active filters:
- if I click on "Exit" (right corner of the simplewall screen) there is no message.
- if I do "File" then "Exit" I get a screen saying "Installed filters will continue .... Continue? Oui - Non". By this way the dialog box appears.
The operation is the same while passing by the "Exit" of the systray icon.

PS: in the dialog box there is a mixture of English and French (the laptop runs W11 in French). This is not fundamental.

**Comment by henrypp** [comment]
it's normal
