### ISSUE TITLE
PayPal in €

### ISSUE THREAD

**Issue by DomOBU** [henrypp/simplewall#1208]
Hello,

You do not offer the possibility of making a donation in euro.
The cost of a transfer to Kazakhstan, outside the SEPA zone, is extremely high.
The possibility to make a donation in € using PayPal without having to open an account would be convenient (some free softaware editors propose it).

**Comment by henrypp** [comment]
How can i do that?

**Comment by DomOBU** [comment]
It is possible for Keepass.
Maybe you can contact PayPal or Dominik Reichl the editor of Keepass (https://keepass.info/index.html, https://sourceforge.net/u/dreichl/profile/)
