### ISSUE TITLE
New programs blocked without prompt

### ISSUE THREAD

**Issue by synchr** [henrypp/simplewall#121]
Version: 2.1.4, 64-bit (Unicode) on Windows 10

It worked fine for a long time after installing 2.1.4, but now i never see the prompt when a program tries to reach the internet (both new programs and programs that already have rules). Instead they are instantly blocked and added to "blocked apps" without any user interaction.

**Comment by synchr** [comment]
I also have simplewall installed on another computer where this bug is not present.

**Comment by henrypp** [comment]
Windows 10 Redstone 4?

**Comment by synchr** [comment]
No i'm on redstone 3: Version 1709 (OS Build 16299.125)

**Comment by henrypp** [comment]
Dropped packets logging working? Do you see any information about blocked connections in logs?

**Comment by synchr** [comment]
I tried restarting multiple times, still does it after computer restart. Haven't tried reinstalling though.

I'm not able to access my computer right now, but I will check the dropped packet log in about a week.

**Comment by synchr** [comment]
Yes the dropped logging works. This is what the log entries look like:
`[‎18-‎02-‎2018 ‏‎xx:xx:xx] C:\windows\system32\nslookup.exe (xxx\xxx) [Remote: x.x.x.x:x] [Local: x.x.x.x:x] (UDP) simplewall\Block all outbound connections [Out]`

This entry was generated after running nslookup.exe with no rules for nslookup.exe. After running it then it's automatically blocked and added to the blocked apps in the simplewall GUI without any prompt.

**Comment by henrypp** [comment]
"Settings" > "Dropped packets logging" > "Enable dropped packets notifications" checked?

**Comment by synchr** [comment]
Yes that was the problem, thanks!
Sorry for trouble, I must have disabled it by mistake since i didn't even know that this option existed.
