### ISSUE TITLE
Interface issue

### ISSUE THREAD

**Issue by p6002** [henrypp/simplewall#1210]
- Win 11 latest update, interface is too big or something:
https://i.ibb.co/YTM8WjK/Zrzut-ekranu-2022-04-20-212107.png

**Comment by gettysburg** [comment]
Try to disable scaling by setting it to 100%:

![image](https://user-images.githubusercontent.com/2256003/164701981-1809433d-9213-496e-aa1e-fe14f855754c.png)

**Comment by henrypp** [comment]
dup #1009
