### ISSUE TITLE
windows 10 file share folder

### ISSUE THREAD

**Issue by unusualgarment** [henrypp/simplewall#1215]
I am trying to access my Windows 10 file share folder from my Mac.
I tried enabling the msdn responder/bonjour to let through but it didn't work.

So I used Autolearn and it works well but when I turn it off back to Normal Protection. I can't connect to the Win10 computer.

what do I need to let through to get it to work.

**Comment by Sedrini** [comment]
You can try Disable Filters, then  access to win 10 file share folder and see in Connections what programs o services are using internet.
Preferably by closing all programs so that they take up less space
Also "SYSTEM" and "svchost.exe" are usually related to all things windows.

**Comment by henrypp** [comment]
File share working over smb/netbios
