### ISSUE TITLE
Autostart yes or no?

### ISSUE THREAD

**Issue by FrostBlade5** [henrypp/simplewall#1217]
Is simplewall autostart required to block connections during boot, etc?
Is it required or recommended in general?

**Comment by henrypp** [comment]
What does it says when exit?

> Installed filters will continue to work even if you exit. Continue?

**Comment by FrostBlade5** [comment]
When i exit simplewall it says nothing.
I found it has an option for autostart in settings but it doesn't tell to use it or not.

**Comment by FrostBlade5** [comment]
So i guess... autostart is not required
