### ISSUE TITLE
[Typo] Rename [for all] to Global

### ISSUE THREAD

**Issue by Rexadev** [henrypp/simplewall#1219]
![image](https://user-images.githubusercontent.com/62152714/165232299-508e3ca7-ac17-40bc-8347-f2c336a02b3a.png)

**Comment by gettysburg** [comment]
This is not a typo, and whether he writes ``[for all]`` or Global, is up to the developer.

Please stop abusing the bug tracker for crap like this, I haven't exactly counted but just on the first page, 3/4 issues were by you.

@henrypp Please add stricter rules for the bug tracker, and ban users who do not follow those rules.
