### ISSUE TITLE
Rebranding in Windows 10 1709

### ISSUE THREAD

**Issue by pwn0r** [henrypp/simplewall#122]
Windows 10 x64 build 1709. Simplewall as the last official version x64. 

Recently I have found an interesting glitch: the M$ have rebranded _Windows Firewall_ into _Windows **Defender** Firewall_. That was done in Win10 build 1709.

Either due to that or some other reason (but most likely due to this rebranding??) the simplewall no longer disables Windows Firewall service when installing filters. Install/Reinstall filters was tried but did not solve the problem.

**Comment by henrypp** [comment]
Disable service is not necessary, simplewall disable WF profiles through winapi/netsh.

> simplewall no longer disables Windows **Firewall**

Nothing to do with rebranding. It's m$ policy, it disallow configuring windows for themselves with every new window 10 update, sad but true.

**Comment by pwn0r** [comment]
aha. now I know why some random bugs may appear in LAN environment. When you disable these profiles, are you disabling domain profile as well?

Also just tried now -- for whatever reason it actually disabled here Windows Firewall (this desktop is on 1607 build). However the service was not _stopped_. I.e. when installing filters, the service startup type was changed into disabled but the WF service was still running (stopped it manually).

on 1709 build iirc simple wall does not even change it to disabled.

**Comment by ltGuillaume** [comment]
So, what does this entail? For example, I now get Windows Defender Firewall dialogs for incoming connections from programs. It looks like the simplewall rules AND the Defender Firewall rules are now enabled simultaneously. What if something is blocked by one and allowed by the other?

**Comment by beerisgood** [comment]
Disable your Internet, uninstall Simplewall Filter and Reinstall Filter.
Then connect to Internet.
Should be fixed then

**Comment by ltGuillaume** [comment]
Defender Firewall was only enabled for public networks, after uninstalling and reinstalling the filters the Defender Firewall is now completely disabled.

But before build 1709 I couldn't even see the Inboud/Outbound rules of "Windows Defender Firewall with Advanced Security". I'm still wondering what programs that dynamically set Windows Firewall rules, like Windscribe VPN, and invoking `netsh advfirewall firewall add rule (...)` does when simplewall is running.

**Comment by duttyend** [comment]
The way https://github.com/henrypp does it now is the best way because disabling the service leads to problems with Microsoft Store app (impossible to update apps).

**Comment by henrypp** [comment]
@ltGuillaume,
> I'm still wondering what programs that dynamically set Windows Firewall rules

It's not Windows Firewall, all 3-rd party apps used Windows FIltering platform to control network requests, even if WF disabled.

**Comment by pwn0r** [comment]
while for some disabling service may be a problem, for some NOT disabling the WF service could be a problem. I had problems on two occasions when a remote machine running on win10 restarted after updates and the firewall was blocking everythng (no connections from outside). I certainly have doubts about both simplewall and WF (or WDF) running simultanously. For now I'll try to manually disable the service, as loss of inbound connectivity on restart is a problem for remote machines.

**Comment by pwn0r** [comment]
it seems that at least with 1607 the new version (i.e. 2.2) works mostly fine. The current behaviour is as follows:

Disable filtering with Enable Windows Firewall: service startup becomes automatic and firewall service up and running.

Enable filtering with Disable Windows Firewall: service startup becomes disabled, according to event viewer firewall becomes disabled for all three profiles, but the service itself keeps running.
