### ISSUE TITLE
Packet Log and Connections tab show blocked connection in Green. It should be Red

### ISSUE THREAD

**Issue by Rexadev** [henrypp/simplewall#1222]
![image](https://user-images.githubusercontent.com/62152714/165975850-97a77218-caf8-4842-bd5c-ce85099c36c6.png)

**Comment by henrypp** [comment]
It should not.

![sshot-001](https://user-images.githubusercontent.com/3902025/166142593-86dd8acb-cf73-42e5-b9d4-5260a64428fb.png)

**Comment by Rexadev** [comment]
@henrypp That scheme works for "Apps" for Packet Log and Connection different color scheme can be used
