### ISSUE TITLE
simplewall won't allow me to install update 3.6.2

### ISSUE THREAD

**Issue by msgtb** [henrypp/simplewall#1223]
I tried to update from inside the application but the install doesn't complete. So I went to your website and downloaded Simplewall v 3.6.2 and tried to install it also won't allow me to complete the installation. I am running win 7 ultimateD:\photos\2022\Screen Capture\simplewall.png.

Thanks
![simplewall](https://user-images.githubusercontent.com/82438701/166102703-3edccdec-4c69-4287-96b0-ad8f6b4f865e.png)

Dave

**Comment by henrypp** [comment]
Maybe close app before update installation?

**Comment by msgtb** [comment]
Thanks that worked.

Dave
