### ISSUE TITLE
Firewall Blocking Apps without Notification

### ISSUE THREAD

**Issue by mpql** [henrypp/simplewall#1226]
I've been using simplewall since around December of 2019, and it's worked great for me this whole time. Recently, without any relevant changes on my end (to my knowledge), I have stopped getting pop-up notification windows when programs are blocked. Additionally, my `simplewall.log` has not had a new entry since 2022-04-24. Enabling the packet-logging interface for the session also doesn't bring up any logged entries.

I have tried exporting my settings and resetting, but the issue remains. If I add a program that cannot access internet to simplewall and check the box to allow that program's traffic, it gains internet access. Again, I do not think I've changed anything, and I've tried both reinstalling and resetting the application, updating, and restarting my machine.

I am on Windows 10 Pro Version 21H2 (OS Build 19044.1645), if it helps. My Windows firewall has been disabled via the Group Policy Editor (Computer Configuration > Administrative Templates > Network > Network Connections > Windows Defender Firewall > Standard Profile), but this is not new. I've also searched around and found issues #1009, which I believe to be unrelated, and #1153, which seems to have been closed without resolution. I've also found issue #1133, and as mentioned in that issue, I've created a new issue here to keep things from getting too muddied in irrelevant conversation, and to outline the issue more clearly as separate from #1009.

I am willing to try test builds, and take reasonable steps to try further debugging in whatever ways I can do so that preserves my privacy. Thanks for all the work you do on simplewall, this thing is awesome!

**Comment by henrypp** [comment]
#1133

>which seems to have been closed without resolution

man in #1153 have access denied to event logging engine.
