### ISSUE TITLE
Crash on Windows 11 ARM after 3.6.2 update

### ISSUE THREAD

**Issue by ViRb3** [henrypp/simplewall#1228]
### System
- MacBook Pro M1 Max, macOS 12.3
- Windows 11 Pro ARM via Parallels 17, 22H2, 22621.1, 5/‎13/‎2022

### Issue

simplewall 3.6.1 worked great. After I updated to simplewall 3.6.2, I get a crash on start, and nothing fixes it. The issue also exists on 3.6.3. Reverting back to 3.6.1 solves the problem.

![Screen Shot 2022-05-13 at 15 39 38](https://user-images.githubusercontent.com/2650170/168307537-fea9403e-23a3-46aa-ad3f-31c0d862364c.png)

Crash dump:

[simplewall-1652452613.dmp.zip](https://github.com/henrypp/simplewall/files/8688693/simplewall-1652452613.dmp.zip)

**Comment by henrypp** [comment]
Can you start simplewall arm64 (not amd64) and let me know - it is crashed too? if yes, upload new crash dump.

**Comment by ViRb3** [comment]
Yes, also crashes with arm64 build. Crash dumps below.

[simplewall-1652573914.dmp.zip](https://github.com/henrypp/simplewall/files/8694078/simplewall-1652573914.dmp.zip)

**Comment by ViRb3** [comment]
![Screen Shot 2022-05-15 at 13 48 33](https://user-images.githubusercontent.com/2650170/168473714-ab9f4fc4-8fc0-44a8-80d6-391e8b5fe6dc.png)
![Screen Shot 2022-05-15 at 13 48 42](https://user-images.githubusercontent.com/2650170/168473716-9c267f34-b1fa-489f-aa91-8364431be572.png)
1
[simplewall-1652618914.dmp.zip](https://github.com/henrypp/simplewall/files/8694958/simplewall-1652618914.dmp.zip)

**Comment by henrypp** [comment]
try this arm64 build! i hope fixed

[simplewall.zip](https://github.com/henrypp/simplewall/files/8707415/simplewall.zip)

**Comment by ViRb3** [comment]
<img width="457" alt="Screen Shot 2022-05-17 at 11 29 39" src="https://user-images.githubusercontent.com/2650170/168791296-0efbdaaf-dde9-4a8f-bd7f-a9dfdcf27041.png">
<img width="679" alt="Screen Shot 2022-05-17 at 11 30 15" src="https://user-images.githubusercontent.com/2650170/168791392-3cf49076-5902-4048-a8ef-7bd68f1dee16.png">
<img width="668" alt="Screen Shot 2022-05-17 at 11 30 36" src="https://user-images.githubusercontent.com/2650170/168791451-9c65aaaf-ac9c-4d9d-9df9-e908e43f579d.png">


If the first two errors are not a problem, then it works! Thanks a lot, looking forward to seeing the fix commit.

**Comment by henrypp** [comment]
Do you have profile_internal.sp in sw directory? Can you delete it?

**Comment by ViRb3** [comment]
I don't, this is a completely fresh VM with no old installation of simplewall. Even after restarting the computer, the second error always shows on start.

**Comment by gettysburg** [comment]
> For virtual os, there are many problems with the memory area.

What? Just no. 

Please stop posting or get banned.

**Comment by henrypp** [comment]
I am did not understand why win11 arm64 could not verify hash/initialize BCrypt library.

Try this build and let me see error code.

[simplewall.zip](https://github.com/henrypp/simplewall/files/8759814/simplewall.zip)

**Comment by ViRb3** [comment]
With the new build, the first error is gone. The second one remains identical, though:

> The hash requests is not present or not up to date with the current file contents. (0xC000A101)

![Screen Shot 2022-06-01 at 16 58 54](https://user-images.githubusercontent.com/2650170/171448332-7da68f6f-6dd3-453e-a0d1-37cfe518aac8.png)

There were no more errors or logs that I can provide.

**Comment by ViRb3** [comment]
@henrypp I hate to bring bad news, but the internal profile error is still present on simplewall 3.6.4 arm64

![Screen Shot 2022-06-19 at 14 27 05](https://user-images.githubusercontent.com/2650170/174483393-69a5e7bf-4db6-4651-a99f-597a98b5c481.png)
.

**Comment by henrypp** [comment]
@ViRb3 so, crash was fixed, but i still don't know why win11 arm64 does not correctly handle sha256 hash checking. It is only problem. If you have enough time - then i need some real-time tests on your OS, i send builds and you was checking.

At this time you can unzip this file and put into simplewall profile directory and start simplewall.

[profile_internal.zip](https://github.com/henrypp/simplewall/files/8974271/profile_internal.zip)

**Comment by ViRb3** [comment]
@henrypp I'm more than happy to test builds for you, it takes me less than a second...

Can also confirm that the profile you attached fixes the error.

**Comment by ViRb3** [comment]
@henrypp this error still occurs on 3.6.6 every time that I start simplewall.

**Comment by ViRb3** [comment]
@henrypp error still exists on 3.6.7. Anything I can do to help you resolve it?

**Comment by dutden** [comment]
@henrypp I also get the above-mentioned error. I use the Windows Dev Kit 2023 with Windows Pro. 

The hash requests are not present or not up to date with the current file contents. (0xC000A101)

![image](https://user-images.githubusercontent.com/118806120/205838487-ad64bd5e-6341-49c3-bbd2-dadd78636afc.png)

After closing the error message, the application seems to run fine, though. Anything else I can send you to help figure out the Problem?

**Comment by gettysburg** [comment]
I would be available to do some reverse engineering if you can provide the bcrypt binary that simplewall is loading, symbols are already provided by Microsoft since I have an up to date IDA and HexRays license with ARM64 support.

Maybe this needs to be escalated to MS themselves, I have a friend with a similar problem.

**Comment by henrypp** [comment]
You can check it here https://www.henrypp.org/simplewall/latest.

**Comment by gettysburg** [comment]
@henrypp 

I was writing to affected users such as @dutden , since I don't have an ARM64 machine I am unable to reverse-engineer an ARM64 version of bcrypt.dll and figure out why your usage of bcrypt in `db.c` fails.

So my first idea was to get bcrypt.dll and bcryptprimitives.dll from an affected ARM simplewall user and compare to Win x64 using symbols, because I have the suspicion that Microsoft actually introduced a bug in the ARM64 version of bcrypt.

**Comment by ViRb3** [comment]
@gettysburg here are the dlls from latest stable version of Windows 11 22H2 arm64:
[bcrypt.zip](https://github.com/henrypp/simplewall/files/10202174/bcrypt.zip)

**Comment by henrypp** [comment]
Test this build and tell me.

https://www.henrypp.org/files/simplewall/latest/

**Comment by ViRb3** [comment]
@henrypp can confirm this build works on Windows 11 arm64 without any errors.

**Comment by imcool** [comment]
I have the exact same problem on my  Microsoft Surface X ARM CPU tablet. I tried **simplewall-3.6.7-setup.exe** but I still see the  error 'COULD NOT LOAD INTERNAL PROFILE 0XC00A101'

**Comment by ViRb3** [comment]
The fix hasn't been released yet in that release.
