### ISSUE TITLE
Let's make custom rule blocks from popups!

### ISSUE THREAD

**Issue by tokariu** [henrypp/simplewall#123]
If a program wants to connect to a specific ip, a pop up comes up with 3 options like:

[x] Create Custom Rule for IP
[ ] Create Custom Rule for Port
[ ] Disable Notifications for App

[Allow] [Ignore]

--
If i check the first option and click on [Ignore], simplewall does not create a custom BLOCK-rule.
the first two options (Create Custom Rule for IP / Create Custom Rule for Port) only creates a custom rule if i choose ALLOW.

But I want to create custom BLOCK rules from the pop-up for the current pending IP and/or Port!

Any reason why it's only working for ALLOW and not for IGNORE/BLOCK? (and why is it called IGNORE and not BLOCK?

for now I have to manually copy the current pending ip address, go into options and add a manual custom rule for that app and paste the IP.. thats really clumsy.

**Comment by henrypp** [comment]
Notification popup for _already_ blocked rules and did not understand why you need another useless block rule?

**Comment by tokariu** [comment]
I think there is a misunderstanding. I do not want a popup for already blocked programs. 

lets make an example: 
there is a new program on the system and it wants to connect to, lets say 10 different IP addresses. 
but 4 of those 10 IP addresses I want to block, the others should be allowed.

Now the first time the program starts, simplewall makes a popup asking me what I want to do with the first IP address it wants to connect to:

[ ] Create Custom Rule for IP
[ ] Create Custom Rule for Port
[ ] Disable Notifications for App

[Allow] [Ignore]

The first IP I want to block, so I want to create a custom rule directly from the popup by ticking "[x] create custom rule for IP" and click on "IGNORE/(=block)". simplewall will create a block/drop rule for exactly this IP/port and Program. The next time the program tries to connect to this very IP address, packets will get dropped.

Right after that the program trys to connect to a 2nd different IP address. I still don't want this IP to be reached so I create again a block rule for this IP only like before.

the 3rd time the program wants to connect to yet another IP address, but this time I want to allow it. so on the popup i tick "[x] create custom rule for IP" and click on "ALLOW". simple wall creates an allow-rule for this IP/port and Program.

for the rest of the remaining IPs the program wants to connect to I continue to select which IPs are allowed and which are not allowed directly by creating both allow- and block-rules from the popup-notifications.

if anytime later more IP addresses come up the program wants to connect to, I might want to tick "disable notifications for this app" and click on: 
- ALLOW <- then it will allow all yet unknown *future* IP-Addresses it wants to connect to but still blocks the IP-Addresses in the previously created block rules for this app.

- IGNORE (=block) <- then it will block all future connection attempts to any new IP-Addresses which don't have a previously created allow-rule.

The advantage of all this is you can create very app-specific block/allow rules on the fly. there is no need to manually add custom rules in the simplewall main-program, because simplewall learns it all on the fly by just using the apps.

**Comment by tokariu** [comment]
Thank you for implementing, great feature now!

BTW: is there a reason for removing the "ignore future notifications from this app" checkbox? I actually liked it to set it directly from the notification.

**Comment by henrypp** [comment]
@tokariu you can use button in top of the notification window to disable notification for any app.

**Comment by tokariu** [comment]
@henrypp ah, i was misleaded by the loudspeaker symbol of it! I thought it was a way to disable notification sounds when you click on it. I just realized you disable notifications for the current app that way!

i must admit I would prefer something like:

> [Allow] [Block] [ ] disable notifications for this app

and when you click on block with ticked checkbox like that:

> [Allow] [**Block**] [**x**] disable notifications for this app

current ip and all future IPs get blocked.

if i click on the loudspeaker icon on the top, the notification just disappears and left me with the question, what happened? did i allow it? did I block it? will it be blocked or allowed in future connection attempts?

it's more obvious when the user still clicks on either ALLOW or BLOCK and just selects one more option (disable notifications) (imho).

in any case, that might be just my opinion and habit. :)
