### ISSUE TITLE
Simplewall blocks Microsft Edge Sync

### ISSUE THREAD

**Issue by ninuola** [henrypp/simplewall#1247]
**Expected**
I expect Microsoft Edge to be able to sync across all devices without issues when Simplewall is enabled.

**Observed**
Microsoft Edge gets stuck "Setting up sync" when Simplewall is enabled. If "Sync is on" before you enable Simplewall, you might need to restart the browser to see the "Setting up sync" error. However, syncing stops even if you don't restart your browser to see the error.

**Reproduced**
I'm able to reproduce the error all the time. Please see the screenshots below.

**System Spec**
System Model: Ryzen 7 3700X CPU, TUF Gaming B450M-Pro II motherboard, Asus Nvidia 3060Ti graphics card
OS: Windows 11 Pro version 21H2 (Build 22000.708)
Browser: Microsoft Edge
Simplenote app version: 3.6.3 Release 64-bit

**Default Microsoft Spying and Telemetry enabled**
![2022-06-12 15_57_25-Settings](https://user-images.githubusercontent.com/1965655/173240269-5dc8566a-9366-44dd-9bdd-ee1326f34a3f.png)

**`edge://sync-internals` page when Simplewall is disabled**
![2022-06-12 16_08_15-Sync Internals and 11 more pages - Personal - Microsoft​ Edge](https://user-images.githubusercontent.com/1965655/173240373-a0f40603-e050-45fc-aeb9-e08043d8d36f.png)

**`edge://sync-internals` page when Simplewall is enabled**
![2022-06-12 16_11_39-Sync Internals and 12 more pages - Personal - Microsoft​ Edge](https://user-images.githubusercontent.com/1965655/173240443-6c1c7bfb-1b7f-47be-a065-f9b947f0d2a4.png)

Please is there a way to allow or whitelist Microsoft Edge browser sync?
Many thanks.

**Comment by ninuola** [comment]
Disabling or allowing Microsoft spying and telemetry allows syncing.

![2022-06-12 17_09_20-Settings](https://user-images.githubusercontent.com/1965655/173242491-a5dabc69-3dfd-4a88-8090-f3e412f184ce.png)

**Comment by gettysburg** [comment]
Report it to the lists repository and not here.

**Comment by gettysburg** [comment]
Wrong repository.

I suppose next time you could use your brain and click on the Author link, and report it there - this has NOTHING to do with simplewall.

**Comment by gettysburg** [comment]
It does what it is supposed to do, there is no default configuration that would suit all users.

If you have a better approach, please feel free to submit a pull request.

**Comment by ninuola** [comment]
Okay, I understand. You could have said instead of insulting me earlier.

**Comment by gettysburg** [comment]
I suppose I could, but we get flooded with questions (that don't even belong here) and other crap daily.

💐 take these flowers and accept my honest apology.
