### ISSUE TITLE
System rules not working

### ISSUE THREAD

**Issue by AtieshStaff** [henrypp/simplewall#1248]
simplewall 3.6.3
windows 11 (clean install)
all System rules are enabled

if disable svchost.exe from access to network by unchecking 
im unable to use file share and windows update

Packet log show Block connection svchost.exe

**Comment by gettysburg** [comment]
Because programs blocked by user rules take priority over built-in rule-sets.

There is currently no way around this, so write better filters.

**Comment by gettysburg** [comment]
Because programs blocked by user rules take priority over built-in rulesets.

There is currently no way around this, so write better filters.

**Comment by gettysburg** [comment]
Because programs blocked by user rules take priority over built-in rule sets.

There is currently no way around this, so write different filters.

**Comment by AtieshStaff** [comment]
so.. no way to block svchost.exe at all

i try write my own rules for work lan but windows update use svchost for download... its not detect as wuauserv

**Comment by gettysburg** [comment]
Yes you can block svchost.exe, just add a rule for it.

However you don't want to block svchost.exe as some instances of it take care of keeping time in sync and resolving domain names.

**Comment by tnodir** [comment]
@gettysburg There is a "Windows services support" in the [Features](https://github.com/henrypp/simplewall#features).

What does it mean, if you can't control svchost.exe's separate instances by service names?

**Comment by gettysburg** [comment]
@tnodir ?

Sorry but the way you write is borderline incomprehensible.

Yes, you can control single services through that panel - I might have forgotten to mention that.

In that case OP, @AtieshStaff, please go to the services tab and enable `wuauserv`.

This should be the only service required to download updates.

Please let me know if that fixes it.

**Comment by gettysburg** [comment]
@tnodir ?

Sorry but I totally forgot about that, and my tunnel vision from the stimulants I'm taking probably doesn't help.

In that case OP, @AtieshStaff, please go to the services tab and enable `wuauserv` & whatever else you need.

`wuauserv` should be the only service required to download updates.

Please let me know if that results in the behavior you want.

**Comment by gettysburg** [comment]
@tnodir

Sorry but I totally forgot about that, and my tunnel vision from the stimulants I'm taking probably doesn't help.

In that case OP, @AtieshStaff, please go to the services tab and enable `wuauserv` & whatever else you need.

`wuauserv` should be the only service required to download updates.

Please let me know if that results in the behavior you want.
