### ISSUE TITLE
Exception and crash

### ISSUE THREAD

**Issue by g-k-m** [henrypp/simplewall#1251]
Hello i got some exception i pressed ok so i could not write it down however i got a crash dump (the entire program exitted)

[simplewall-1656082470.zip](https://github.com/henrypp/simplewall/files/8977077/simplewall-1656082470.zip)

Version of program is 3.6.4 64 bit

**Comment by ChrisS85** [comment]
I can join this report, also with 3.6.5. Happens on start after the latest update.
[simplewall-1660224278.zip](https://github.com/henrypp/simplewall/files/9309020/simplewall-1660224278.zip)

**Comment by henrypp** [comment]
#1272
