### ISSUE TITLE
Path independent App names

### ISSUE THREAD

**Issue by Extremenis** [henrypp/simplewall#1256]
A lot of apps change paths during download but maintain the same .exe name (for example Visual Studio updates, Dropbox, etc). Simplewall only filters by exact path and this can be a huge problem on this kind of programs. 

Some kind of path independent app names would solve this issue.

Regards.

**Comment by anonwins** [comment]
I came here to say this is needed. There are some programs that we copy paste into different directories and we could use a pattern matching in the program section of create rule window. also the updates don't work right for me and i have to download every version from github but that's off topic. cheers great program dude
