### ISSUE TITLE
Doesn't notify about blocked apps in spite of the settings

### ISSUE THREAD

**Issue by debobrov** [henrypp/simplewall#1267]
Doesn't notify about blocked apps in spite of the settings.
I found out about the problem since the last version, the situation has not changed in the latest version.
If you turn off the lock - applications have access to the network, if you turn it on - it silently locks.

**Comment by henrypp** [comment]
Any error log?

**Comment by debobrov** [comment]
The program does not display any errors. I found only the file simplewall_debug.log do you need to look at it?

**Comment by henrypp** [comment]
yes

**Comment by debobrov** [comment]
I can send you the log, but I can't tell you exactly when these events took place. If so, does it make sense to upload the log?
