### ISSUE TITLE
how does simplewall compare to binisoft wfc?

### ISSUE THREAD

**Issue by SiddharthSharma16923** [henrypp/simplewall#1268]

**Comment by 0x4E69676874466F78** [comment]
Windows Firewall Control is closed source`</thread>`

**Comment by Pandaa-P** [comment]
- The main difference is that simplewall is not a control UI over the native Windows Firewall, and does not interact in any level with Windows Firewall, it's more like Comodo Firewall or zonealarm firewall. 
- it has better interface
- Free and open source
- you are not under the mercy of windows Firewall and can even block windows system files from connecting

**Comment by WDD3MS** [comment]
I use both, WFC on families W10, and SW on my machines. And I wish to have the ability to create a rule:  automatically allows digitally signed programs, with low priority. To make SW like learning mode in WFC.

**Comment by SiddharthSharma16923** [comment]
me after some time :
simplewall is wayy better , when it comes to bocking and allowing rules , wfc is just slow at opening logs and rules and confusing as well
also wfc is less trustable , bcz malicious programs target the firewall , but not simplewall (bcz its uncommon )
thank you devs for keeping such app free
