### ISSUE TITLE
Crash with last update - Esception Raised

### ISSUE THREAD

**Issue by laurentvv** [henrypp/simplewall#1272]
n/a (0xE06D7363)

Dump :

[](https://nextcloud.laurentv.camdvr.org/index.php/s/8TdgPZ76a3ZZ72j)
https://nextcloud.laurentv.camdvr.org/index.php/s/8TdgPZ76a3ZZ72j

**Comment by brian6932** [comment]
Same issue:
https://i.alienpls.org/Tns.dmp

**Comment by spacewaffles309** [comment]
Same.  3.6.4 is still good.  Running in portable mode.

[simplewall-1660241437.dmp.txt](https://github.com/henrypp/simplewall/files/9311126/simplewall-1660241437.dmp.txt)

**Comment by danxxcruz** [comment]
Same issue here

**Comment by RandomCoderFoxy** [comment]
Same issue for me.
crash dump: https://drive.google.com/file/d/1iVrjI8RhmMd1QeSic7C1G3g6_oMIVAst/view?usp=sharing

**Comment by neoOpus** [comment]
Saame here
