### ISSUE TITLE
Uninstall doesn't clear filters

### ISSUE THREAD

**Issue by outdoorsdev** [henrypp/simplewall#1273]
Hey, really appreciate the program but I've had various issues over the years that mean I'd like to stop using it.

Mainly, it's certain programs like discord, zoom, and other programs where the installer calls out to download the rest of the package and fails. Most importantly, windows update breaks.

I've tried unistalling but that seems to leave filters - even if it says it doesn't. Installing and then disabling as much as a I can seems to help. However, still windows update never seems to work again.

I've allowed all apps and services, and then under blocklist, system rules, and user rules I've disabled everything. In blocklist everything is allowed, and under the rules tab in settings everything is unticked. On top of that, the enable filters option is off so nothing should have been applied anyway.

Can anyone help me clear the rules from WFP and uninstall cleanly?

**Comment by henrypp** [comment]
> Uninstall doesn't clear filters

it is a lie:
https://github.com/henrypp/builder/blob/master/src/setup_script.nsi#L317

> Can anyone help me clear the rules from WFP and uninstall cleanly?
Press disable filters, allo?
