### ISSUE TITLE
Update 3.6.5 for 64 bit occasionally blocking internet

### ISSUE THREAD

**Issue by RH-BD** [henrypp/simplewall#1276]
Title says it all. Before this update everything was fine. But after installing this 3.6.5 my internet getting blocked often and then it goes to normal after few seconds which is very annoying. Please look into the matter.

**Comment by DomOBU** [comment]
The release 3.6.6 is available.

**Comment by RH-BD** [comment]
Hi, problem seems not so big but annoying. and, 3.6.6 slightly improved but not fully. For example: it took 2/3 attempts to load the github page.
