### ISSUE TITLE
Xbox Game Bar Keeps Popping Up

### ISSUE THREAD

**Issue by seniorm0ment** [henrypp/simplewall#1282]
Xbox game bar keeps popping up as a network alert constantly while playing a game. I hit allow everytime but it keeps popping. Very annoying, is there a fix?

**Comment by turbodude** [comment]
I have the same issue but it's from onenote instead. Not only the window keeps popping up, but synchronization in Onenote is not working (even though I allow the connections), until I disable Simplewall's filters.

**Comment by seniorm0ment** [comment]
Same, and I don't want to have to disable Simplewall's filters.
It's very aggravating

**Comment by henrypp** [comment]
dup #1294
