### ISSUE TITLE
Comment for each Rule / App

### ISSUE THREAD

**Issue by mozilla-firefox** [henrypp/simplewall#1288]
Add ability to add comment for each Rule / App
and a Column to show it is needed too

**Comment by jcrevani** [comment]
I simply search "what is name.xxx", but a right click to search could help. Not big deal though.

**Comment by thisisthelongestusernameyouhaveeverseen** [comment]
![image](https://user-images.githubusercontent.com/41063376/188505078-21d45ae7-2a9b-41d5-b707-da6de27e84b8.png)
Actually I mean exactly this 'Description' section that is there in Windows Firewall
Also the dear henrypp can add comments for 'Rules' by default
