### ISSUE TITLE
Manually checking for update in Simplewall causes some odd bug

### ISSUE THREAD

**Issue by privacyguy123** [henrypp/simplewall#1291]
All UWP apps break and show strange names with long codes and will not connect to internet even if allowed.

**Comment by showmak** [comment]
I have the same issue since this morning, checkout the screenshots below.
https://imgur.com/a/vvCGD58

**Comment by privacyguy123** [comment]
Reinstalling manually fixes without restart also

**Comment by henrypp** [comment]
dup #1294
