### ISSUE TITLE
No tray icon when minimized

### ISSUE THREAD

**Issue by t3dium** [henrypp/simplewall#1295]
Updated simplewall to 3.6.6 via scoop, and when minimizing the app theres now no tray icon despite still running in the background

OS: w10 20h2
Installed as a portable app via scoop

**Comment by Pandaa-P** [comment]
Go to  `Settings` the click `Rest` then click `Yes` and see if the issue still there

**Comment by t3dium** [comment]
the issue still exists

**Comment by Pandaa-P** [comment]
It could be from the executable that scoop delivered to you. instead install it from the original source. https://github.com/henrypp/simplewall/releases

**Comment by gkiryaziev** [comment]
I also have a problem with the tray icon when the application is load when system startup, the icon is not displayed but the program works.

Portable version from here:
https://github.com/henrypp/simplewall/releases/download/v.3.6.7/simplewall-3.6.7-bin.zip

Windows 8.1 x64

**Comment by Pandaa-P** [comment]
Don't use the portable version, use the full installer instead, windows is not always happy with portable software.
