### ISSUE TITLE
[Feature Request] Allow wildcards/regexp to be used in <item path="">

### ISSUE THREAD

**Issue by jmonachesi** [henrypp/simplewall#1301]
Google Drive is driving me mad every time it updates itself because it creates a new executable in a subfolder like this:

`<item path="C:\program files\google\drive file stream\61.0.3.0\googledrivefs.exe" timestamp="1659030296" is_enabled="true"/>
`
I would find useful if I could use regular expressions or a simple wildcard in the path instead of a fixed location.

Thanks.

**Comment by henrypp** [comment]
not available.
