### ISSUE TITLE
Every 24h I need to restart the machine 

### ISSUE THREAD

**Issue by rock5917** [henrypp/simplewall#1305]
https://github.com/henrypp/simplewall/issues/1274

Last time I forgot to add the debug log:

Level,Date,Function,Code,Description,App version,OS version
"Error","‎11/‎09/‎2022 ‏‎01:37:13","FwpmGetAppIdFromFileName","0xC000003A","C:\users\...\appdata\local\discord\app-1.0.9003\discord.exe","3.6.6","10.0 build 17763"

**Comment by gettysburg** [comment]
Useless ticket, likely an isolated issue on your machine.

RTFM.
