### ISSUE TITLE
Blacklist mode often breaks, and long delay between applying filter and taking effect

### ISSUE THREAD

**Issue by nevubm** [henrypp/simplewall#1306]
I followed the instructions [here](https://www.henrypp.org/product/simplewall) to use blacklist mode, by unchecking "Block inbound/outbound for all" and creating a rule to block all connections, but this doesn't actually work very well.

The first problem is that there is often a long delay (anywhere from roughly 10 to 120 seconds) between toggling the rule to enable/disable the blocking filter, and the filter actually taking effect. Sometimes disabling and re-enabling all filters in simplewall fixes this as a workaround, but other times I encounter a second problem.

The second problem is that I often get the error "Something went wrong. Open debug log file in profile directory." and the rules still don't take effect. Here is the log file [simplewall_debug.log](https://github.com/henrypp/simplewall/files/9544086/simplewall_debug.log) And this is on a fresh install of Windows 11 with all default settings, simplewall 3.6.6

**Comment by gettysburg** [comment]
Isolated issue with your machine.

RTFM.

**Comment by nevubm** [comment]
Yep. Don't know what fixed it but it's fine now. Maybe was fixed by some Windows updates, which I had blocked earlier.
