### ISSUE TITLE
Simplewall blocks "Setup PIN" from login screen

### ISSUE THREAD

**Issue by orangpelupa** [henrypp/simplewall#1307]
steps to reproduce after simplewall has been installed and active

1. setup computer to use microsoft account and PIN
2. reset security thingy on windows security "Settings" that warns you it requires you to restart and set PIN again.
3. restart
4. the login screen will say you need to set up pin again
5. setup pin again, and it will try to open a microsoft account login page but it cant connect to the internet

maybe an option to add that into whitelist? or add it to whitelist by default?

**Comment by henrypp** [comment]
Allow UWP apps "Windows Default Lock Screen" and "Your account" and service "wlidsvc", thats may be help you!

**Comment by orangpelupa** [comment]
can those be added as option somwehere (maybe in the rules? "Allow windows lock sceen to recover password/pin")
or documented in the "FAQ" part of the readme?

**Comment by henrypp** [comment]
"Microsoft account" is already in system rules.
