### ISSUE TITLE
Can't install version 367

### ISSUE THREAD

**Issue by Karmic-UA** [henrypp/simplewall#1310]
Can't install version 367.
Windows blocks access to files.
In portable mode, Windows blocks simplewall.exe, explaining that the developer is not known.

366 version works and installs without any problems.

Windows 10 64bit...

**Comment by henrypp** [comment]
Disable reputation based protection in windows security.

**Comment by henrypp** [comment]
![sshot-004](https://user-images.githubusercontent.com/3902025/191575295-1efb097e-f3e2-427f-a80d-707e27f5cd64.png)

**Comment by henrypp** [comment]
![sshot-004](https://user-images.githubusercontent.com/3902025/191575452-d27c3c0a-7249-4b1d-ae37-6ea6709a72e2.png)
