### ISSUE TITLE
new version seems to crash often 3.6.7 

### ISSUE THREAD

**Issue by kdovale** [henrypp/simplewall#1314]
im receiving lots of these debug errors now since upgrading

Level,Date,Function,Code,Description,App version,OS version
"Error","‎25/‎08/‎2022 ‏‎1:58:39 PM","FwpmGetAppIdFromFileName","0xC000003A","C:\simplewall\simplewall.exe","3.6.6","10.0 build 14393"
"Error","‎25/‎08/‎2022 ‏‎1:58:39 PM","FwpmGetAppIdFromFileName","0xC000003A","C:\program files\probus-it\hyper-v tools\hvm.exe","3.6.6","10.0 build 14393"
"Error","‎25/‎08/‎2022 ‏‎2:05:37 PM","FwpmGetAppIdFromFileName","0xC000003A","C:\simplewall\simplewall.exe","3.6.6","10.0 build 14393"
"Error","‎25/‎08/‎2022 ‏‎2:05:37 PM","FwpmGetAppIdFromFileName","0xC000003A","C:\program files\probus-it\hyper-v tools\hvm.exe","3.6.6","10.0 build 14393"
"Error","‎26/‎08/‎2022 ‏‎11:14:37 AM","FwpmGetAppIdFromFileName","0xC000003A","C:\simplewall\simplewall.exe","3.6.6","10.0 build 14393"
"Error","‎26/‎08/‎2022 ‏‎11:14:37 AM","FwpmGetAppIdFromFileName","0xC000003A","C:\program files\probus-it\hyper-v tools\hvm.exe","3.6.6","10.0 build 14393"
"Error","‎26/‎08/‎2022 ‏‎1:09:47 PM","FwpmGetAppIdFromFileName","0xC000003A","C:\simplewall\simplewall.exe","3.6.6","10.0 build 14393"
"Error","‎26/‎08/‎2022 ‏‎1:09:47 PM","FwpmGetAppIdFromFileName","0xC000003A","C:\program files\probus-it\hyper-v tools\hvm.exe","3.6.6","10.0 build 14393"
"Error","‎26/‎08/‎2022 ‏‎2:02:50 PM","FwpmGetAppIdFromFileName","0xC000003A","C:\simplewall\simplewall.exe","3.6.6","10.0 build 14393"
"Error","‎26/‎08/‎2022 ‏‎2:02:50 PM","FwpmGetAppIdFromFileName","0xC000003A","C:\program files\probus-it\hyper-v tools\hvm.exe","3.6.6","10.0 build 14393"
"Error","‎30/‎08/‎2022 ‏‎2:05:01 PM","FwpmFilterAdd","0x80320020","FWPM_LAYER_ALE_AUTH_CONNECT_V4\User rule\spam_185.30.176.0","3.6.6","10.0 build 14393"
"Error","‎30/‎08/‎2022 ‏‎2:12:05 PM","FwpmGetAppIdFromFileName","0xC000003A","C:\simplewall\simplewall.exe","3.6.6","10.0 build 14393"
"Error","‎30/‎08/‎2022 ‏‎2:12:05 PM","FwpmGetAppIdFromFileName","0xC000003A","C:\program files\probus-it\hyper-v tools\hvm.exe","3.6.6","10.0 build 14393"
"Error","‎30/‎08/‎2022 ‏‎2:12:05 PM","FwpmFilterAdd","0x80320020","FWPM_LAYER_ALE_AUTH_CONNECT_V4\User rule\spam_185.30.176.0","3.6.6","10.0 build 14393"
"Error","‎30/‎08/‎2022 ‏‎2:14:24 PM","FwpmGetAppIdFromFileName","0xC000003A","C:\simplewall\simplewall.exe","3.6.6","10.0 build 14393"
"Error","‎30/‎08/‎2022 ‏‎2:14:24 PM","FwpmGetAppIdFromFileName","0xC000003A","C:\program files\probus-it\hyper-v tools\hvm.exe","3.6.6","10.0 build 14393"
"Error","‎30/‎08/‎2022 ‏‎2:14:24 PM","FwpmFilterAdd","0x80320020","FWPM_LAYER_ALE_AUTH_CONNECT_V4\User rule\spam_185.30.176.0","3.6.6","10.0 build 14393"
"Error","‎26/‎09/‎2022 ‏‎9:20:27 AM","FwpmGetAppIdFromFileName","0xC000003A","C:\simplewall\simplewall.exe","3.6.6","10.0 build 14393"
"Error","‎26/‎09/‎2022 ‏‎9:20:27 AM","FwpmFilterAdd","0x80320020","FWPM_LAYER_ALE_AUTH_CONNECT_V4\User rule\spam_185.30.176.0","3.6.6","10.0 build 14393"
"Error","‎28/‎09/‎2022 ‏‎1:04:21 PM","FwpmGetAppIdFromFileName","0xC000003A","C:\simplewall\simplewall.exe","3.6.6","10.0 build 14393"
"Error","‎28/‎09/‎2022 ‏‎1:04:22 PM","FwpmFilterAdd","0x80320020","FWPM_LAYER_ALE_AUTH_CONNECT_V4\User rule\spam_185.30.176.0","3.6.6","10.0 build 14393"
"Error","‎28/‎09/‎2022 ‏‎1:05:21 PM","FwpmGetAppIdFromFileName","0xC000003A","C:\simplewall\simplewall.exe","3.6.7","10.0 build 14393"
"Error","‎28/‎09/‎2022 ‏‎1:05:21 PM","FwpmFilterAdd","0x80320020","FWPM_LAYER_ALE_AUTH_CONNECT_V4\User rule\spam_185.30.176.0","3.6.7","10.0 build 14393"
"Error","‎28/‎09/‎2022 ‏‎1:34:41 PM","FwpmGetAppIdFromFileName","0xC000003A","C:\simplewall\simplewall.exe","3.6.7","10.0 build 14393"
"Error","‎28/‎09/‎2022 ‏‎1:34:42 PM","FwpmFilterAdd","0x80320020","FWPM_LAYER_ALE_AUTH_CONNECT_V4\User rule\spam_185.30.176.0","3.6.7","10.0 build 14393"
"Error","‎28/‎09/‎2022 ‏‎1:39:04 PM","FwpmGetAppIdFromFileName","0xC000003A","C:\simplewall\simplewall.exe","3.6.7","10.0 build 14393"
"Error","‎28/‎09/‎2022 ‏‎1:39:04 PM","FwpmFilterAdd","0x80320020","FWPM_LAYER_ALE_AUTH_CONNECT_V4\User rule\spam_185.30.176.0","3.6.7","10.0 build 14393"

**Comment by henrypp** [comment]
And where is here crash exactly?

**Comment by kdovale** [comment]
Hi Henry,

 

If you open the simplewall interface, it comes up that the simple wall has crashed, and gives the message look at the debug log.. it seems random but I have had this happen now on about 4 or 5 different servers randomly..

 

 

 

Kind Regards

 

Keith Dovale

 <http://www.hostworx.co.za/> www.HostworX.co.za

+27 87 802 5634 / +27 87 820 4959

**Comment by henrypp** [comment]
This is not a crash, this error code says that the file `C:\simplewall\simplewall.exe` did not exists.

**Comment by kdovale** [comment]
That was the old location of simple wall, I uninstalled it and re-installed it into the default folder in program files, and I did cleanup the apps list, etc. I will take another look, to see where its getting the old path from.

 

 

Kind Regards

 

Keith Dovale

 <http://www.hostworx.co.za/> www.HostworX.co.za

+27 87 802 5634 / +27 87 820 4959



 

From: henrypp ***@***.***> 
Sent: Wednesday, 28 September 2022 17:54
To: henrypp/simplewall ***@***.***>
Cc: kdovale ***@***.***>; Author ***@***.***>
Subject: 17 :- .Re: [henrypp/simplewall] new version seems to crash often 3.6.7 (Issue #1314)

 

This is not a crash, this error code says that the file C:\simplewall\simplewall.exe did not exists.
