### ISSUE TITLE
[Bug] Windows update - inconsistency in between settings

### ISSUE THREAD

**Issue by Tom4tot** [henrypp/simplewall#1315]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.6.7

### Windows version

W11 22H2

### Steps to reproduce

Just check the settings related to Windows Update in: `Blocklist => Microsoft Update` and `Settings => Blocklist => Microsoft Update`

### Expected behavior

I assume these settings should match (if one is ticked, the other should be "allowed").

I don't know if they are doing the same thing:

- If yes, one of the entries should be removed?
- If not, it would be useful to explain what the difference is and why they can have different options, or if they should always be in the same state (allowed/ticked or blocked/unticked)

### Actual behavior

Settings don't necessarily match in between this: https://i.imgur.com/ePo2MtG.png

And this: https://i.imgur.com/wfYNjkr.png

**Comment by henrypp** [comment]
This is not correct.

Actualy `Settings` -> `Blocklist` does not refers to option in main menu `Rules` -> `Allow Windows Update`, it is a different option. 
Actual option in main menu contatined in `Blocklist` submenu.

And i think as Windows Update now works correct, i think to remove update blocklist entries.

**Comment by TontyTon** [comment]
> And i think as Windows Update now works correct, i think to remove update blocklist entries.

@henrypp Please don't remove windows update blocklist, for example I want to use some windows feature which required internet (svchost.exe) other than Windows Update, and I don't want to install updates, then the windows Update blocklist would be helpful.

Also, why remove a feature if it's not doing any harm. To avoid confusion like above (actually it shouldn't have happened, settings are pretty clear) please just add some description.
