### ISSUE TITLE
Writing to Db any app/packet dropped

### ISSUE THREAD

**Issue by kimrot** [henrypp/simplewall#1317]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.6.7

### Problem you are trying to solve

I am checking if it is possible to dump dropped or blocked events for example Source Address, Source Port, Remote Address, Remote port, process/application into a database such as Postgres. Your guidelines is much appreciated. 
Thank you.

### Suggested solution

I do have a small group of IT students and would like to monitor their activities.

**Comment by henrypp** [comment]
Now writing into csv log file available only, i do not think to made another log file format.

**Comment by kimrot** [comment]
Thank you for the Response @henrypp.
