### ISSUE TITLE
[Bug] simplewall doesn't work when VPN is on

### ISSUE THREAD

**Issue by rayman3003** [henrypp/simplewall#1321]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.6.7

### Windows version

10 Pro 19043

### Steps to reproduce

When the VPN is off, everything work as it should be. simplewall works without problem. I mean it blocks all previously-blocked apps & It asks for new apps to allow or block.

But when I turn on the VPN, simplewall becomes non-responsible. I mean that simplewall won't block previously-blocked apps in it's list, & also simplewall won't ask for new apps (to block or allow).

VPN off = simplewall works

VPN on = simplewall acts like a dead app!

So how could I make the simplewall to work when the VPN is on?

### Actual behavior

VPN off = simplewall works

VPN on = simplewall acts like a dead app!

**Comment by thisisthelongestusernameyouhaveeverseen** [comment]
What is your VPN App / Protocol
I used many diff Apps / Protocols and never had not this problem

**Comment by rayman3003** [comment]
> What is your VPN App / Protocol

It is Adguard. (I don't know exactly which protocol they r using).

It has a free version too. Try it yourself:

https://adguard-vpn.com/en/welcome.html
