### ISSUE TITLE
[Feature] Why disable windows firewall automatically?

### ISSUE THREAD

**Issue by Shituation** [henrypp/simplewall#1327]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.6.7

### Problem you are trying to solve

The app states that windows firewall doesn't need to be disabled.
Why does the app always by default disable it? I mean, if the app states that windows firewall can coexist with no issues, why turning it off? 
To be honest, the thing that bothers me is not that it disables it, the issue comes from constant reminders from windows to turn it on again.

### Suggested solution

Make the "disable windows firewall" check mark **remembered** for both options, enable and disable.
![image](https://user-images.githubusercontent.com/43975882/197414290-6d90fc2e-c905-4250-96e2-3a9186ec1607.png)

**Comment by Shituation** [comment]
Is this going to be added? any comments?

**Comment by henrypp** [comment]
It is stupit

**Comment by Shituation** [comment]
Well at least try learn how to spell that.

Here you have it guys, don't expect anything else from this moron's app.

**Comment by henrypp** [comment]
gtfo idiot
