### ISSUE TITLE
[Bug] Firewall bypassed because of the Fiddler running in the background

### ISSUE THREAD

**Issue by dashke** [henrypp/simplewall#1328]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.6.7

### Windows version

10

### Steps to reproduce

1. Download and install Fiddler https://www.telerik.com/fiddler
2. Download run the setup from https://www.opera.com/computer/portable

### Expected behavior

There is no alert window shown, but the Opera setup downloads all the binaries. Practically it bypasses the firewall because of the Fiddler running in the background.

### Actual behavior

There should be a allow/block window shown after running the setup.

### Logs

![fiddler_bug](https://user-images.githubusercontent.com/77551811/197610159-d2cbc49b-dbfe-4d2a-a0b0-38c5ce3b2304.gif)

**Comment by ViRb3** [comment]
This is not a bug. You've allowed Fiddler in Simplewall, and Fiddler acts as a proxy for Opera, so all Opera requests physically go out of Fiddler. This is expected behavior.
