### ISSUE TITLE
[Bug] "Disable filters" button not working

### ISSUE THREAD

**Issue by chanterelles** [henrypp/simplewall#1329]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

simplewall 3.6.7 x64 Portable

### Windows version

Windows 10 Pro 19044.1288

### Steps to reproduce

1. Opened the program window
2. Clicked `Disable filters` > `Disable filters` (Checkbox **Enable Windows Firewall** doesn't matter)

### Expected behavior

The program should disable filters and show [this](https://i.imgur.com/GVMrgxH.png)

### Actual behavior

The program updates the list and continues to write in the status bar [this](https://i.imgur.com/RnQDDm2.png). Filters are not disabled.

### Logs

[simplewall_debug.log](https://www.upload.ee/download/14615237/4775fd0df28f1bdf77f0/simplewall_debug.log)

**Comment by edgetecht** [comment]
i have this same problem when i try to disable filters i use windows 11 22h2

![image](https://user-images.githubusercontent.com/34459507/205998533-f2161100-a10b-48f0-86d6-71f06348e040.png)

**Comment by henrypp** [comment]
You have access denied error.
