### ISSUE TITLE
[Bug] App without internet access has internet access

### ISSUE THREAD

**Issue by apolikan** [henrypp/simplewall#1330]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.6.7

### Windows version

Windows 10 Pro 21H2 19044.1889

### Steps to reproduce

1. Get CPU-Z 2.01.0 and copy it into c:\CPU-Z\
2. Run c:\CPU-Z\cpuz_x64.exe by double clicking in Windows Explorer.
3. Wait 15 seconds... CPU-Z is checking for updates

### Expected behavior

Simplewall blocks internet access for CPU-Z.
CPU-Z can't connect to the update server.

### Actual behavior

Simplewall doesn't block CPU-Z.
CPU-Z successfully checked for update, shows the result.

### Logs

How it looks
[https://imgur.com/a/hh8ZkUE](https://imgur.com/a/hh8ZkUE)

**Comment by axel-1267** [comment]
Can't reproduce it. Probably your misconfiguration?
