### ISSUE TITLE
[Question] App doesn't auto-start on non-admin user

### ISSUE THREAD

**Issue by Veal-Uneasily4** [henrypp/simplewall#1333]
It's really frustrating. 
Windows 10

**Comment by oklokl** [comment]
`schtasks /create /tn simplewall /tr "'%PROGRAMFILES%\simplewall\simplewall.exe' /minimized" /sc ONLOGON /rl HIGHEST`
add

`schtasks /delete /tn simplewall`
remove

So am I.
But there are some things developers stick to.
So it seems like that.
Developers want to click UAC with the mouse button on startup.
Anyway, I'm writing this well.
:)

**Comment by Veal-Uneasily4** [comment]
Can something be done on my side about it?
