### ISSUE TITLE
[Bug] Doesn't seem to work on Windows 11

### ISSUE THREAD

**Issue by SanctusStreams** [henrypp/simplewall#1336]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

Most recent (made sure to update it)

### Windows version

Windows 11

### Steps to reproduce

Open simplewall
turn on filter
refresh

### Expected behavior

Before I went to windows 11 I was able to allow discord internet access, and it showed all the apps on my computer both system apps, exe's downloaded from the internet and Microsoft store apps. 

### Actual behavior

Discord and basically all apps on the computer are invisible from the main UI app section.  
![sshot-2022-11-05-13-39-35](https://user-images.githubusercontent.com/105398391/200133670-d46c4bfb-4716-45c1-ae01-159eb996743f.png)

**Comment by ccodykid** [comment]
On Windows 11 22H2 with the same problem.

**Comment by henrypp** [comment]
What is not worked?

**Comment by ccodykid** [comment]
> What is not worked?

Apps that are running does not show up in Apps tab. See screenshot in original issues.

**Comment by henrypp** [comment]
You're notifications not wotking, but app is working.

**Comment by henrypp** [comment]
#841
