### ISSUE TITLE
How to disable all WAN/internet traffic without blocking LAN?

### ISSUE THREAD

**Issue by mikae1** [henrypp/simplewall#1338]
Hi! I've been unable to create a rule that blocks all internet traffic. I still want all LAN traffic to work. 

Is someone able to help?

---

App version: 3.6.7
Windows version: Windows 10 19043.1110

**Comment by oklokl** [comment]
This program does not provide such a feature.
As far as I know, yes.

But it also has this function. See link. This is a Windows 10-11 feature.
https://learn.microsoft.com/en-gb/windows/security/threat-protection/security-policy-settings/network-security-restrict-ntlm-incoming-ntlm-traffic
`RestrictReceivingNTLMTraffic`
https://www.windows-security.org/0b3f9681dbd7a82788e160b34197f3c5/network-security-restrict-ntlm-incoming-ntlm-traffic
