### ISSUE TITLE
[Bugfix - DELETEME] 2.2 Beta not displaying notifications from previously deleted items

### ISSUE THREAD

**Issue by xEBFE** [henrypp/simplewall#134]
I've provided a comparison of the displayed notification behavior between 2.1.4 (good) vs. 2.2 (broken).

## **simplewall 2.1.4**
**Mode:** Whitelist
**Steps to reproduce:**
```
1) Run a program (e.g., test.exe) that requests network access.
2) simplewall's notification dialog will pop up. Click "Allow" for test.exe.
3) If test.exe is still running, close it.
4) Open up simplewall's main window, select test.exe listed underneath "Allowed apps", and delete it (Del or right-click > Delete).
5) Re-run test.exe.
6) Because we manually removed test.exe in [4], a new simplewall notification dialog will pop up at the same time adding test.exe underneath "Blocked apps".
   If we choose to click "Allow", test.exe will move from "Blocked apps" into "Allowed apps", if we click "Ignore" or [X], test.exe will remain underneath "Blocked apps".
```
   
## **simplewall 2.2 Beta**
**Mode:** Whitelist
**Steps to reproduce:**
```
1) Run a program (e.g., test.exe) that requests network access.
2) simplewall's notification dialog will pop up. Click "Allow" for test.exe.
3) If test.exe is still running, close it.
4) Open up simplewall's main window, select test.exe listed underneath "Allowed apps", and delete it (Del or right-click > Delete).
5) Re-run test.exe.
6) Because we manually removed test.exe in [4] we should expect a new simplewall notification dialog and at the same time adding test.exe underneath "Blocked apps".
   Unlike version 2.1.4, no simplewall notification dialog is displayed but test.exe does get added underneath "Blocked apps".
```
The behavior of 2.2 Beta displaying notifications from previously deleted items should be corrected to behave like 2.1.4. The reason being is that unless you kept simplewall's main window up when trying to run test.exe and happened to notice it added itself under "Blocked apps", you would have absolutely no indication that it was trying to request network access.

**Comment by tokariu** [comment]
out of curiosity i tried to reproduce this, also with whitelist mode in simplewall v2.2 beta.

but I was unable to reproduce. I tried it with a firefox portable version. but even after closing it and removing the app entry in SW, when i start firefox portable again, simplewall asks for permission via notification.

**Comment by xEBFE** [comment]
I should've been more clear about how I was using the non-portable version (simplewall-2.2-bin.exe) and that if I closed out of simplewall 2.2 Beta and re-opened it, I would see the notifications again. But, as long as I kept simplewall 2.2 Beta open after having manually removing test.exe from the list, no subsequent notification dialogs ever popped up for me until I closed out of simplewall 2.2 Beta completely and re-opened it.

**Comment by xEBFE** [comment]
After further testing, I realized I had been trying to re-open test.exe within the timeframe specified by "Timeout between same notifications (sec.)" which explains why I had not been seeing the subsequent notification dialogs. After adjusting that setting to a very low value and re-opening test.exe after I had deleted it from the IDC_LISTVIEW, I was again seeing the notifications.

**Comment by tokariu** [comment]
Ah okay.

BTW: the default settings for "Timeout between same notifications (sec.)" and the "Notification timeout (sec.)" could get a bit more tweaked:

For instance, whenever I install simplewall the first thing i do is to change these values to something like:

> "Notification timeouts": 120sec.
> "Timeout between same notifications (sec.)": 20sec.

These values are more on par with other firewall software settings and proved to be working out pretty good. of course other people might want different settings.
