### ISSUE TITLE
[Question] Does anybody know how to block Proton VPN inbound connections?

### ISSUE THREAD

**Issue by Shituation** [henrypp/simplewall#1341]
I'm hosting a game server online. The game is way too basic for any kind of advanced filtering and it just bans IP addresses. The trolls started using VPN's to re gain access to the server.
Is there any way to ban ProtonVPN IPs inbound connections? (I mean an easy way... not one by one...)

**Comment by Ry0OBSSc9H8VjeVE** [comment]
If you use WireGuard, then your local IP for virtual interface (TUN) is always static. You can use to disallow any inbound traffic to that local IP.

**Comment by Shituation** [comment]
Not using VPN's for the server, the attackers use the vpns (apparently proton in this case) to connect.
I ended up adding ip ranges that I think are from proton and so far I haven't seen the offenders again. If someone has a better approach or have a good list of proton addresses to block, that would be helpful. I fear that I might be blocking too much too.
