### ISSUE TITLE
[Question] How to allow apps automatically in a specific folder?

### ISSUE THREAD

**Issue by tonyrulez** [henrypp/simplewall#1344]
There are apps which are (automatically) updated by downloading a new .exe and executing it. For example, every time the Bitwarden desktop app updates itself, I have to set the rule for the new installer:

![kép](https://user-images.githubusercontent.com/27233005/205506139-63e53628-e768-4756-8119-e5378cdc2b87.png)

Since all .exes go to the same folder with the same naming scheme, could I create a rule to allow **bitwarden-installer-*.exe** in the specific folder they get donwloaded? It's annoying to always allow these apps.
The problem is that you wouldn't know if they were malicious, so I would manually allow them all the time. I have no way of knowing if I can trust the next _.exe_, so there is no real benefit in always prompting me = there is no more danger in straight up allowing them blindly.

---

App version: v3.6.7
Windows version: W10 22H2

**Comment by henrypp** [comment]
Only user interaction required.

**Comment by tonyrulez** [comment]
Yep, that's what I mean by manually allowing it, via the popup window. And since the update is done via chocolatey, updating a **lot** of apps, not only bitwarden, it means the update process will hang at this point.
