### ISSUE TITLE
[Feature] Option to apply rules to "subprocesses" of certain app

### ISSUE THREAD

**Issue by i0xHeX** [henrypp/simplewall#1348]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.6.7

### Problem you are trying to solve

There are apps that can create and run another process, therefore bypassing the firewall.

For example, when I run Pomatez, it unpacks another executable in a temporary path and runs it, that instance get updates and install them (first screenshot from Process Hacker):
![image](https://user-images.githubusercontent.com/33582973/209473686-484aa00c-0d99-48a9-87d1-8fe5e2b2c4dd.png)
![image](https://user-images.githubusercontent.com/33582973/209473861-273a8ad1-eb24-4742-bb11-0da59fcad681.png)

The rule is valid and filters were enabled (all connections allowed except this one rule):
![image](https://user-images.githubusercontent.com/33582973/209473839-2191373e-2433-4152-9cc0-5198eab0f29a.png)
![image](https://user-images.githubusercontent.com/33582973/209473843-6009f6b6-6c53-4962-87ed-d60e0a0fa4cb.png)

### Suggested solution

Add an option to also apply rules to processes, which were run by process in rules. Or just apply rules without an option, if there are no other rules for certain process/app.

**Comment by henrypp** [comment]
I cannot be done at all.
