### ISSUE TITLE
[UI] 2.2 Beta - Consider not boldening "simplewall.exe" (self) in the IDC_LISTVIEW

### ISSUE THREAD

**Issue by xEBFE** [henrypp/simplewall#135]
@henrypp Thank you for addressing #106 in a fair way.
I'm fine with simplewall automatically whitelisting itself if it's not on the "Allowed apps" or "Blocked apps":
```
3097	_app_addapplication (hwnd, app.GetBinaryPath (), 0, false, (app.ConfigGet (L"Mode", ModeWhitelist).AsUint () == ModeWhitelist) ? true : false, true);
```
And I'm fine with it exempting itself from deletion since we can toggle it between being Allowed/Blocked.
```
8335	apps_undelete[config.myhash] = true; // disable deletion for me ;)
```
These two changes are fair and sufficient but I don't agree with simplewall boldening itself in the IDC_LISTVIEW. It seems to just distract from the simplistic UI and looks out of place in the IDC_LISTVIEW.
```
1516		if (hdc && hash == config.myhash && config.hfont_bold)
1517			SelectObject (hdc, config.hfont_bold);
```
I hope you consider not boldening it to look consistent and conform to the display of the other items in the IDC_LISTVIEW.

**Comment by tokariu** [comment]
i think that is criticism on a very high level, but I would agree that optically simplewall.exe doesn't need to be highlighted over the other apps, as long as it is undeletable and blockable by userchoice.
