### ISSUE TITLE
[Question] Can't get rid of nagging "Turn on Windows Firewall" notification in Win11 22H2

### ISSUE THREAD

**Issue by fatalhalt** [henrypp/simplewall#1350]
Does anybody have a working solution to disable bloody "Turn on Windows Firewall" notifications? I tried various commands and group policies to no avail:
> netsh advfirewall set allprofiles state off
> Set-NetFirewallProfile -All -Enabled False
> disabling "Windows Defender Firewall: Protect all network connections" in gpedit.msc:  Local Group Policy Editor > Local Computer Policy > Computer Configuration > Administrative Templates > All Settings

![win fw notification](https://user-images.githubusercontent.com/3224548/210124542-5c991029-0bea-434b-9349-1e46b6d5c6b4.jpg)

App version: latest
Windows version: Win11 22H2

**Comment by Theo-user** [comment]
Unless I missed some step I'm not getting this notification anymore.

![Screenshot 2023-01-04 184416](https://user-images.githubusercontent.com/75871295/210627383-95529a76-b8cd-4109-97cd-fe97e32f4baa.png)

![Screenshot 2023-01-04 184429](https://user-images.githubusercontent.com/75871295/210627425-0a64e9e0-2954-4d0a-af6f-5e13c6c7084e.png)

**Comment by fatalhalt** [comment]
@Theo-user thanks for you input, I'm trying it out, for reference I enabled:
_Computer Configuration->Administrative Templates->All Settings: Windows Defender Firewall: Prohibit notifications_

**Comment by Theo-user** [comment]
Did it work?

**Comment by fatalhalt** [comment]
It's working on only 1 out of 3 PCs, I gave up, I disabled Windows Notifications altogether, too annoying and useless.
