### ISSUE TITLE
[Bug] Phone Link app is allowed in UWP apps but still gets blocked

### ISSUE THREAD

**Issue by SeriousHoax** [henrypp/simplewall#1353]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.6.7

### Windows version

Windows 11 Enterprise

### Steps to reproduce

Phone Link app is allowed in UWP app list but still gets blocked and notifies me if I don't create a separate rule for PhoneExperienceHost.exe.

The UWP app rule already covers this exe, so not sure what's happening. 
The allowed rule is "Outbound Only" which a user rule. Other apps and UWP apps are also set to use this user rule and they work without any issue. 
![1](https://user-images.githubusercontent.com/29574622/210337806-6b18d740-5092-4294-b12b-5e38de08e386.png)
![2](https://user-images.githubusercontent.com/29574622/210337823-bbf36dbf-815c-48f8-b115-53b5dc4f6226.png)
![3](https://user-images.githubusercontent.com/29574622/210337829-57ab2d93-78eb-464a-a99d-522028ce2a43.png)

### Expected behavior

It should work like it does for other apps.

### Actual behavior

UWP app rule doesn't work for the Phone Link app.

### Logs

"‎03-‎Jan-‎23 ‏‎3:53:39 PM","***-PC\*UserName","C:\program files\windowsapps\microsoft.yourphone_1.22102.229.0_x64__8wekyb3d8bbwe\phoneexperiencehost.exe","192.168.0.200","1101","13.107.5.88","443 (https)","tcp","FWPM_LAYER_ALE_AUTH_CONNECT_V4","Internal\BlockConnection","#72119","Outbound","Blocked"

"‎03-‎Jan-‎23 ‏‎3:58:05 PM","WiN-PC\AniK","C:\program files\windowsapps\microsoft.yourphone_1.22102.229.0_x64__8wekyb3d8bbwe\phoneexperiencehost.exe","192.168.0.200","1191","13.107.6.158","443 

(https)","tcp","FWPM_LAYER_ALE_AUTH_CONNECT_V4","Internal\BlockConnection","#72119","Outbound","Blocked"
"‎03-‎Jan-‎23 ‏‎3:58:07 PM","WiN-PC\AniK","C:\program files\windowsapps\microsoft.yourphone_1.22102.229.0_x64__8wekyb3d8bbwe\phoneexperiencehost.exe","192.168.0.200","1192","13.107.6.158","443 

(https)","tcp","FWPM_LAYER_ALE_AUTH_CONNECT_V4","Internal\BlockConnection","#72119","Outbound","Blocked"
"‎03-‎Jan-‎23 ‏‎3:58:09 PM","WiN-PC\AniK","C:\program files\windowsapps\microsoft.yourphone_1.22102.229.0_x64__8wekyb3d8bbwe\phoneexperiencehost.exe","192.168.0.200","1193","13.107.6.158","443 

(https)","tcp","FWPM_LAYER_ALE_AUTH_CONNECT_V4","Internal\BlockConnection","#72119","Outbound","Blocked"
"‎03-‎Jan-‎23 ‏‎3:58:11 PM","WiN-PC\AniK","C:\program files\windowsapps\microsoft.yourphone_1.22102.229.0_x64__8wekyb3d8bbwe\phoneexperiencehost.exe","192.168.0.200","1197","13.107.6.158","443 

(https)","tcp","FWPM_LAYER_ALE_AUTH_CONNECT_V4","Internal\BlockConnection","#72119","Outbound","Blocked"
"‎03-‎Jan-‎23 ‏‎3:58:12 PM","WiN-PC\AniK","C:\program files\windowsapps\microsoft.yourphone_1.22102.229.0_x64__8wekyb3d8bbwe\phoneexperiencehost.exe","192.168.0.200","1198","13.107.6.158","443 

(https)","tcp","FWPM_LAYER_ALE_AUTH_CONNECT_V4","Internal\BlockConnection","#72119","Outbound","Blocked"
"‎03-‎Jan-‎23 ‏‎3:58:14 PM","WiN-PC\AniK","C:\program files\windowsapps\microsoft.yourphone_1.22102.229.0_x64__8wekyb3d8bbwe\phoneexperiencehost.exe","192.168.0.200","1199","13.107.6.158","443

**Comment by TLCPlusPlus** [comment]
Strange, I have this app and it works for me. 

Even in UWP apps, phone link is under "apps without internet access"
But in Apps, it has full internet privileges.

The phone link app works as expected.

**Comment by henrypp** [comment]
only dropped packets log can solve your problem
