### ISSUE TITLE
[Bug] Blocklist blocks linkedin, NTP (time.windows.com), smartscreen

### ISSUE THREAD

**Issue by fusionneur** [henrypp/simplewall#1354]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.6.7

### Windows version

11

### Steps to reproduce

Under blocklist, block microsoft applications => the blocklist rule extra_13.107.42.14 will be enabled to block

ping/nslookup on linkedin resolves on exactly 13.107.42.14 and gives general failure. The linkedin website is not working. That IP is on Microsoft Azure. I believe that this ip shouldn't be blocked.

My expectation was that blocking microsoft applications should block default windows apps access such as weather, news etc.

### Expected behavior

linkedin should work

### Actual behavior

linkedin not reachable

**Comment by henrypp** [comment]
It is 0iq issue.

**Comment by henrypp** [comment]
break os functionality? like what? you can't use you'r os?

**Comment by Lordvader81** [comment]
It's evident that there are no intentions to tackle the issue. The same problem has been repeatedly pointed out in various posts by many users over more than a year, yet it persists. I understand that this is a free open-source application, but one would assume that such projects are initiated in the hope that they might evolve into a commercial product available through subscription or a one-time fee. However, with the persistent bugs in this application that remain unfixed, likely due to Henry's apparent arrogance, it seems unlikely.... Good Luck !!!

**Comment by amonteproduction** [comment]
> It's evident that there are no intentions to tackle the issue. The same problem has been repeatedly pointed out in various posts by many users over more than a year, yet it persists. I understand that this is a free open-source application, but one would assume that such projects are initiated in the hope that they might evolve into a commercial product available through subscription or a one-time fee. However, with the persistent bugs in this application that remain unfixed, likely due to Henry's apparent arrogance, it seems unlikely.... Good Luck !!!

There's an endless list of FOSS applications out there whose creators have zero desire to commercialize them cause they want more to provide a service than a source of income for themselves. Not judging anyone that does the latter, it's fair to want to make a living from your hard work- but that's not an inherent goal of all open source software

I get the way the creator is replying in all these threads about linkedin/etc being blocked is rude but security is a double edged sword  where you have to trade some level of convenience and functionality depending on what type of security you're seeking. Microsoft using the same addresses to communicate several different things is an issue inherent to the mission statement and circumventing this isn't as easy as people make it seem, from what I know at least. Sorry if I'm wrong or misinforming anybody here but that's about my level of understanding
