### ISSUE TITLE
[Bug] Windows Update not blocked intermittently

### ISSUE THREAD

**Issue by synthc** [henrypp/simplewall#1355]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.6.7

### Windows version

Windows 11 Pro 22H2

### Steps to reproduce

1.  Set blocklist --> Windows Update to Block.
2. Open Windows Update and check for updates.

### Expected behavior

Windows Update fails to connect to the update servers to check for updates.

### Actual behavior

Sometimes Windows Update succeeds in checking for updates and is also able to download and install them.  This also raises concerns about the reliability of telemetry blocking.

**Comment by henrypp** [comment]
WSB is not update at almost a year.

**Comment by synthc** [comment]
What is WSB?  Are you saying this feature is not supported?
