### ISSUE TITLE
[Feature] scroll rules on popup

### ISSUE THREAD

**Issue by fusionneur** [henrypp/simplewall#1356]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.6.7

### Problem you are trying to solve

when the interactive popup asking to allow/block an app, i should be able to select a rule from the ones created.
 however only some of the rules are presented

### Suggested solution

if the created rules list is too big, show them all in a scrollable menu

**Comment by henrypp** [comment]
It does not needed.
