### ISSUE TITLE
Problem with virtualbox

### ISSUE THREAD

**Issue by NightFlexer** [henrypp/simplewall#1358]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.6

### Windows version

windows 10 ltsc

### Steps to reproduce

The virtualbox network just doesn't work even though the simplewell didn't ask for permission. After disabling all the simplewell rules, the virtual machine worked fine.

### Expected behavior

Request permissions for virtualbox

### Actual behavior

No network access request

**Comment by NightFlexer** [comment]
I used the latest version Virtuallbox ver 7.0.6 r155176

**Comment by Pandaa-P** [comment]
Allow Virtuallbox and its network services that are blocked (you find them in services tab)

**Comment by henrypp** [comment]
All network can access through virtualboxvm.exe.
