### ISSUE TITLE
[Feature] `OneDrive` `Edge` random folder.. process support.. problem.

### ISSUE THREAD

**Issue by oklokl** [henrypp/simplewall#1360]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.6.7

### Problem you are trying to solve

`OneDrive` `Edge` random folder.. process support.. problem.

The ms OneDrive program `filecoauth.exe` process spawns in a random folder and is bothering me.
And when I clear OneDrive, 'msedgewebview2.exe' is waiting for me. My computer is virus free. Also no problem.

This symptom occurs when I right-click on a file from then on.
I want an external connection.

`C:\Users\1234\AppData\Local\Microsoft\OneDrive\23.007.0109.0004\filecoauth.exe`
process location

`C:\Program Files (x86)\Microsoft\Edge\Application\109.0.1518.70\msedgewebview2.exe`

`\23.007.0109.0004\`
`\109.0.1518.70\`
This random folder is bugging me.

It does an update every time and I have to allow it.
I tried suggesting ms but to no avail.

It would be nice if the `simplewall` program automatically recognizes random folders as well.
Easy to understand.. When the ms program updates, it automatically detects.
Recognize the digital signature of `filecoauth.exe` or `msedgewebview2.exe` in the same folder. I would like to register automatically.

And the user does not need to give additional permission.
Once registered, it would be nice to be automatically accepted.

My planning idea.

I am already co-disabled.
```
REG ADD "HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\OneDrive" /v "EnableHoldTheFile" /t REG_DWORD /d 0 /f
REG ADD "HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\OneDrive" /v "SilentAccountConfig" /t REG_DWORD /d 0 /f
REG ADD "HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\OneDrive" /v "EnableAllOcsiClients" /t REG_DWORD /d 0 /f 
```

### Suggested solution

After ms process update. the program detects
Added ability to register subfolders automatically allowed.
The `simplewall` process verifies the file's digital credentials and .
If they are the same, they are automatically accepted.
Trusted File Acceptance Automated Features.

For example.. I asked someone else.. I used the below command for a while.
`for /f "delims=" %a in ('dir /a-d /b /o /s "%ProgramFiles(x86)%\Microsoft\EdgeWebView\Application\msedgewebview2.exe"') do (netsh advfirewall firewall add rule name="EdgeWebView_Allow" dir=out program="%a" action=Allow)`
This way... I was able to allow even random folders. As I said before, it was written with great difficulty with the advice of others. I don't know how to make these difficult commands.

And credentials.. I don't know about verification. But it seems possible if you create a command.

### Screenshots / Drawings / Technical details

![3](https://user-images.githubusercontent.com/1571600/216110285-efe342b0-2248-475f-bc4e-d84dc93d9e65.png)
![33](https://user-images.githubusercontent.com/1571600/216110300-66cd5084-120f-48af-b920-4ab1a7faf117.png)
![44](https://user-images.githubusercontent.com/1571600/216112832-130c1232-0880-4177-bd74-e85601b7435d.png)

He's threatening me every few minutes haha

**Comment by Pandaa-P** [comment]
Maybe `blocklist -> Microsoft applications -> allow` will solve it. I don't have a way to test it but I assume that will allow Microsoft apps with recognized digital signature to run without warning
