### ISSUE TITLE
[Question] What does "prevent port scanning" do, exactly?

### ISSUE THREAD

**Issue by mtomassoli** [henrypp/simplewall#1362]
The option "prevent port scanning" is enabled in the settings, but some ports are still open, according to [Shields Up!!](https://www.grc.com/x/ne.dll?bh0bkyd2). I'm on a fully updated Windows 10.

---

App version: 3.6.7 Release, 64-bit (Unicode)

**Comment by henrypp** [comment]
It does what his name does

**Comment by mtomassoli** [comment]
Thank you for a completely useless answer. Good day.
