### ISSUE TITLE
[Bug] The app stop working after weeks

### ISSUE THREAD

**Issue by Cyberdr3am** [henrypp/simplewall#1363]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.6.7

### Windows version

11

### Steps to reproduce

1. Install and use the application
2. Update windows 11
3. After some days / weeks the application stop working ( no new notification for new application who use internet )

### Actual behavior

The application don't work for now. I try to reboot and change some settings but it don't work

**Comment by Pandaa-P** [comment]
try these steps and see it it does that again
- Remove fully and install again
- make it start at start up
- give it admin permission so it can use windows Windows Filtering Platform (WFP)  without problems 
- disable Windows native firewall

**Comment by Cyberdr3am** [comment]
Sorry for the late reply, when i remove my custom rules the app work again. I don't know why but it work now. Thx
