### ISSUE TITLE
[Feature] Dark theme

### ISSUE THREAD

**Issue by fusionneur** [henrypp/simplewall#1364]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

all

### Problem you are trying to solve

app needs dark theme

### Suggested solution

windows 11 provides means of using dark theme

**Comment by henrypp** [comment]
As i say, M$ is don't doing anything in that way.

Anyway, windows already have dark feature for ui (win10+), but M$ is completely fucked assholes, because it have no open documentation for this feature.

>SW is uses Windows API to use native theme support, but problem is in Microsoft is not being open documentation for this and no one know when M$ add native support for dark theme for win32 applications.

**Comment by henrypp** [comment]
@Uj947nXmRqV2nRaWshKtHzTvckUUpD 
M$ describes nothing (as always) to made dark theme/mode for C (and C++) app, but all its API is written in C, funny!

u think it's funny? this idiots STILL doesn not have fix for it's win11 and middle click on sys. tray (22635.3420, and ofc official 22631.3374), still funny?

ps: me so lazy to fiind and put issues (who buys by M$) in github, it already have more than 9000 (not a joke)

**Comment by henrypp** [comment]
@Uj947nXmRqV2nRaWshKtHzTvckUUpD

only found as fixed in insider preview build, does not really know what build
