### ISSUE TITLE
[Feature] Please add a link to your pgp key to the Readme

### ISSUE THREAD

**Issue by firefoxlover** [henrypp/simplewall#1367]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

x

### Problem you are trying to solve

The .sig is essential, everyone should use it, but useless without a PGP key.

I dont know if I am missing something stupid, but was not able to find your public key.

Please add it to every release or add a link to it, preferrable of course on another site, as attackers could just replace all files.

### Suggested solution

please add a link to the public key in your readme and every release. The key should be stored on another site like key.openpgp.org (you will probably already have this but I cant find it)

**Comment by Shituation** [comment]
why is it so essential? (curious)

**Comment by firefoxlover** [comment]
because without a cryptographic public key you cant verify that the package comes from the developer himself.

A checksum (sha256, sha512, e.g.) is a line of numbers that would change if you would edit one single letter in the code. But any malicious actor could just edit both, so Checksums on the same website are 100% useless.

But if you sign that checksum with your private PGP key (that in theory only you possess) then users can verify that the program with that signed checksum comes from you. But only of they can easily download your public key.

But then in theory any hacker could just replace that public key with their own one, that they used to sign the false hash of the false binary (precompiled) program, and you still wouldnt know.

So

1. Every program needs a cryptographically signed hash if it doesnt come from a secure repository compiling it themselves (Just "as is" like Libreoffice and others, or hash-only like a lot too is not enough)
2. The public key needs to be easy or even in any way possible to find, otherwise that signing is useless as noone can verify it.

or is there a way to get the public key from the sign?
