### ISSUE TITLE
Blocklists: Difference between Disable and Allow ?

### ISSUE THREAD

**Issue by Clouds123** [henrypp/simplewall#1369]
I assume that Block will block all connections to IP's in blocklist.

But, what's difference between Disable and Allow ? 

I would expect Disable to just not use the blocklist and, allow all connections to those IP addresses, but would also expect Allow to just allow all IP's in blocklist which, surely does the same thing ?

---

App version: 3.6.7
Windows version: Win 10

**Comment by henrypp** [comment]
You answered your own question.
