### ISSUE TITLE
User rule "allow" don't works

### ISSUE THREAD

**Issue by ne-cyber** [henrypp/simplewall#1372]
simplewall is a create tool!
But I have some notice. For example I create User rule: "block all". After that I create User rule: "allow all". And what I have? all is blocked, and user rule "allow all" is not working. I don't understand something? Please explain me how it's work!

**Comment by roadarsi** [comment]
Hello. Please read to clarify
https://github.com/henrypp/simplewall/issues/1048

**Comment by henrypp** [comment]
I really do not understand why you create rule "block all", and after that you create another rule "allow all". Even with telepathy i cannot understand.
