### ISSUE TITLE
[Bug] Portable setup updates to Program Files

### ISSUE THREAD

**Issue by yw4z** [henrypp/simplewall#1373]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.6.7

### Windows version

10

### Steps to reproduce

1. wait for next update :)
2. use auto update

### Expected behavior

Auto update should update app on existing folder

also similar topic in here https://github.com/henrypp/simplewall/issues/996
but i guess he/she didn't describe problem correctly

### Actual behavior

I extracted simple wall to ProgramData\Apps\Simplewall but autoupdate installs to program files folder

Thanks for your efforts on this app

**Comment by henrypp** [comment]
fixd,mb
