### ISSUE TITLE
[Feature] Show if the connection is outgoing or incoming

### ISSUE THREAD

**Issue by Shituation** [henrypp/simplewall#1378]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.6.7

### Problem you are trying to solve

Right now I don't know if a particular connection is outgoing or incoming.

### Suggested solution

Add a column saying either "outgoing" or "incoming" or something so we can see what is that connection doing.

### Screenshots / Drawings / Technical details

![1](https://user-images.githubusercontent.com/43975882/222446120-982228b1-e315-4d28-9d60-cc88465a6d4f.png)

**Comment by henrypp** [comment]
Wee, os do not know it also, it can't be done
