### ISSUE TITLE
[Bug] If wusvc.exe (created by 'Allow Windows Update' (AWU)) is in use, and AWU is disabled, windows update still have internet access.

### ISSUE THREAD

**Issue by TontyTon** [henrypp/simplewall#1381]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

v3.6.7

### Windows version

Windows 10 22H2

### Steps to reproduce

1. Turn on 'Allow Windows Update'.
2. Open Windows settings and check for updates.
3. Turn off 'Allow Windows Update'

### Expected behavior

Windows Update's internet access get blocked.

For current working of app, wusvc.exe get deleted.

### Actual behavior

Windows Update have internet access.

For current working of app, wusvc.exe don't get deleted.

### Logs

Please read - 
For now, when 'Allow Windows Update' is turned on, SW creates wusvc.exe, links Windows Update and Delivery Optimization service to it using registry and allows internet access to wusvc.exe. And on disabling 'Allow Windows Update', SW undo all of this. Right? (Read this from #677 )

I would suggest that you create a toggle in Settings which creates wusvc.exe and links Windows Update and Delivery Optimization service to it using registry but don't set firewall settings for wusvc.exe.
And create a 'Windows Update' 'User Rule'/'System Rule', which allows internet access to wusvc.exe. 
Now I as user will have the option to use this Rule, or create my own rule where I only allow particular ports/IPs/protocols to wusvc.exe . This gives me more control, and windows update (wusvc.exe) don't get unrestricted internet access.

Please implement this.

If you don't understand any part, please ask.

**Comment by User486375** [comment]
What exactly do you want to be able to do that you can't already? Unless you mean to say it's impossible to block updates besides disabling IPs via Blocklist after ever clicking 'Allow Windows Update' toggle once, when that wasn't the case before toggling it?

If you want to explicitly block or allow windows update, why don't you just use the Blocklist toggle for 'Microsoft Updates' or disallow wuauserv internet access?

AFAIK 'Allow Windows Update' was never put there as a block/allow toggle. It's those who want to block svchost and still couldn't get updates to work even with various system rules and whitelisting of services.

**Comment by TontyTon** [comment]
@User486375 If 'Allow Windows Update' is enabled, user can't block internet access to 'wusvc.exe'. To simplify what I have written under 'Please read', I want that 'Allow Windows Update' don't forcefully allow full internet access to wusvc.exe.

**Comment by henrypp** [comment]
Are you dumb or what? You allowed windows update option and wonder, why is windows update are allowed. It is really stupid.

**Comment by TontyTon** [comment]
@henrypp Please read first comment, 'Expected Behaviour' and 'Actual Behaviour' sections. The issue is that even after disabling 'Allow Windows Update', Windows Update still have internet access (if the created wusvc.exe is in use by system, which will be whenever windows update is at work) .

**Comment by henrypp** [comment]
'Allow Windows Update' is working [as expected](https://github.com/henrypp/simplewall/blob/master/src/helper.c#L2267).

If you have problem with it, it maybe error on your side. Try reset your settings.

**Comment by TontyTon** [comment]
@henrypp Enabling and disabling 'Allow Windows Update' works fine if windows update is not at work in the background.
If windows update is running in background, disabling 'Allow Windows Update' don't work. The option do get unchecked, but wusvc.exe still exists with internet access.

I reported the issue after reproducing it multiple times. Try 'Step to reproduce'.

BTW, I am on Windows 10 22H2. Maybe you can ask someone else too to try reproducing the issue, if you want to confirm.
