### ISSUE TITLE
Powershell and cmd can still access internet (no allow rule, new install).

### ISSUE THREAD

**Issue by s-c-p** [henrypp/simplewall#1382]
I sideloaded (and installed) simplewall, cmder and WinPython on my new Windows 10 laptop. Then I connected to wifi and started coding on a pending task (didn't open Firefox/Chrome).

Meanwhile I disallowed OEM bloatware's internet access whenever I got pop-ups from simplewal, working great!

I needed to `pip install something` and got ufortunately cmd/powershell were able to access not only PyPI but also other internet sites.

---

App version: 3.6.4
Windows version: Win 10 Pro (laptop attached)

**Comment by henrypp** [comment]
I really do not have telepathy.
