### ISSUE TITLE
[Feature] Improve search performance

### ISSUE THREAD

**Issue by pilsnerbeer** [henrypp/simplewall#1383]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.6.7

### Problem you are trying to solve

App often freezes when searching via toolbar due to the fact it updates the search every character. searching longer strings takes unecessarily long time because of this.

![image](https://user-images.githubusercontent.com/36133540/226185878-26518652-1676-4706-aa28-c9cef21ee851.png)

### Suggested solution

Let user write down the search term and then search for it using the ENTER key.

**Comment by User486375** [comment]
Can't reproduce. Define "long time"? Maybe with a video?

Do you purge unused apps often with Ctrl+Shift+X?

**Comment by pilsnerbeer** [comment]
It is issue mainly with long lists, in my case looking through "Connections" is problematic. It is not apparent on the video but I am typing with standard speed and as you can see the letters are appearing very slowly. Just before I recorded this the app froze on me for a couple of seconds

https://user-images.githubusercontent.com/36133540/227975554-95aa40c8-9ece-42b1-8b86-6a77b5a6325d.mp4

**Comment by User486375** [comment]
I see. The slowness there is an issue that can probably be improved a lot depending on your computers speed. I thought you may have meant a more serious kind of freeze. It's never really bothered me or been that noticeable.

**Comment by henrypp** [comment]
I cant reproduce it too. So, really what processor do you have (pentium1?) if you have freezes in filtering search?

**Comment by pilsnerbeer** [comment]
I have tested with with 6core AMD ryzen and i7. The search is badly designed as it can sometimes freeze the app but I understand if you don't want to fix it.

**Comment by Theo-user** [comment]
It's still behaving slowly and odd for me.

3.7.1


https://github.com/henrypp/simplewall/assets/75871295/690da6e4-d6b4-4dbb-9390-e0a6837e71b4
