### ISSUE TITLE
[Feature] Install Mode

### ISSUE THREAD

**Issue by Marabunta159** [henrypp/simplewall#1384]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.6.7

### Problem you are trying to solve

Issues while installing new software and inital failing, because it is blocked, but the software does not retry.

### Suggested solution

Allow only new unknown (and optionally existing) Software for a limited time - but also ask to set the permanent permissions, that will apply after the Timer runs out.
So the installation is successful, the setup-client loses access after some time and the application will work.

**Comment by User486375** [comment]
What piece of software exactly are you having trouble with? 

It's really on the Devs of the programs to be able to work with on access firewalls, not firewall creators to deal with terrible devs who spawn unique processes every time you click their installer or only have their program attempt a connection once.

A workaround would be to temporarily whitelist the specific domain/IP in simplewall that the installer is trying to use.

**Comment by SpiroCx** [comment]
I would like a similar feature but for a different reason.  I always use 2 min timers at the start of the day (instead of block) but then block that same app's request after that.  This lets the app check for updates (say, once on startup).  If simplewall had rules that can handle timers, I would set 95% of my firewall controlled apps to have 2 min internet access once at the start of the day.  It is like this Install Mode idea except I want it daily (or reset on power cycle/reboot/logout) not once off.

**Comment by Marabunta159** [comment]
Installing with powershell/python - they need internet and may use something like curl - curl needs internet now, but doesn't try to reconnect. Instead the installation fails and I have to reinstall, sometimes even clean-up before. It is just the first example I had in mind, but there are many more.

**Comment by henrypp** [comment]
`
Installing with powershell/python - they need internet and may use something like curl - curl needs internet now, but doesn't try to reconnect. Instead the installation fails and I have to reinstall, sometimes even clean-up before. It is just the first example I had in mind, but there are many more.
`

And where is the problem to get access for anything you want?

**Comment by Marabunta159** [comment]
The problem is not that it does not work at all. 
Many Installations just do often not work (at least) the first time. Therefore a feature request.

A continuous annoying problem would be Roblox or Visual Studio backgrounddownload(updater with a random folder in %temp%)
