### ISSUE TITLE
Block Nvidia telemetry? 

### ISSUE THREAD

**Issue by deroverda** [henrypp/simplewall#1386]
Hi, 

I was wondering if there are blocklists that will disable Nvidia telemetry? 

---

App version: <Version 3.6.7 Release, 64-bit>
Windows version: <Windows 10 Enterprise N>

**Comment by User486375** [comment]
Simplewall doesn't make the blocks lists, WindowsSpyBlocker does https://github.com/crazy-max/WindowsSpyBlocker.

This is out of scope. You can remove all Nvidia tracking components, you can't remove all Microsoft components from Microsoft Windows. If you want to block Nvidia's telemetry you're much better off uninstalling all their tracking components with [Display Driver Uninstaller](https://www.guru3d.com/files-details/display-driver-uninstaller-download.html) and installing the minimal version of the driver without GeForce Experience.
https://github.com/ElPumpo/TinyNvidiaUpdateChecker
https://github.com/ElPumpo/TinyNvidiaUpdateChecker/wiki/Fully-utilize-the-minimal-installer-feature
https://github.com/ElPumpo/TinyNvidiaUpdateChecker/wiki/Quiet-runs-on-user-login
https://github.com/ElPumpo/TinyNvidiaUpdateChecker/wiki

https://github.com/ElPumpo/TinyNvidiaUpdateChecker/wiki/Running-the-GeForce-Experience-Overlay-without-signing-into-GeForce-Experience
This also lists tracking hosts to block in host files if you want to keep GeForce Experience around.
```
0.0.0.0 ls.dtrace.nvidia.com
0.0.0.0 telemetry.gfe.nvidia.com
0.0.0.0 accounts.nvgs.nvidia.com
0.0.0.0 accounts.nvgs.nvidia.cn
0.0.0.0 nvidia.tt.omtrdc.net
0.0.0.0 api.commune.ly
0.0.0.0 login.nvgs.nvidia.com
0.0.0.0 login.nvgs.nvidia.cn
```

**Comment by henrypp** [comment]
Do not install nv telemetry with nvslimmer https://www.bytesin.com/software/NVIDIA-driver-slimming-utility-NVSlimmer-/
