### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by kreon1** [henrypp/simplewall#1387]
I made a thread about half year ago and nothing has changed. I changed windows 10 pro to the latest win 11 2h22 pro (clean install). The application after each start asks to allow programs  - it does not remember my rules from the previous day.
Please help  What process /services does Simplewall require for proper operation? Maybe I have something turned off that I don't know?or what has changed in the code since version 3.61 that this behavior exists?
The last 100% working version is 3.61 and I use it all the time.
I thought after upgrading windows I would be able to use the latest version.

Version 3.61 works normally.
versions 3.62-3.67 do not remember the rules from the previous run.Please help, because this is the best firewall overlay ever.

**Comment by henrypp** [comment]
I dont know why you cannot save rules/apps. Maybe your profile.xml have readonly attribute or something else? Or you are using some of the readonly arguments.
