### ISSUE TITLE
[Bug] Entry Point not found

### ISSUE THREAD

**Issue by volga45** [henrypp/simplewall#1390]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.6.7

### Windows version

win 7 pro running on VirtualBox as client

### Steps to reproduce

1. Program installed ok
2. click on desktop icon
3. window pops up saying 'Entry Point not found' 'The procedure entry point SetDefaultDllDirectories could not be located in the dynamic link library Kernel32.dll

### Expected behavior

Program should start

### Actual behavior

error message

**Comment by henrypp** [comment]
Minimum supported client:

`Windows 8 [desktop apps only],KB2533623 on Windows 7, Windows Server 2008 R2, Windows Vista, and Windows Server 2008`

Maybe updates not installed?
