### ISSUE TITLE
[Question] 2ip Firewall Tester - test failed

### ISSUE THREAD

**Issue by debobrov** [henrypp/simplewall#1391]
I use this utility to check the connection from the inside (2ip Firewall Tester https://2ip.ru/firewalltest), the firewall test fails, does not block the connection and does not signal, and there is nothing in the logs.
I use this utility to check the connection from the inside, the firewall test fails, does not block the connection and does not signal, and there is nothing in the logs.

If you search the logs by the name of the FireWallTest program, there is nothing, therefore the program uses some other connection methods that the simplewall does not "see".

simplewall version 3.6.7
windows x64 pro 22H2 19045.2846

**Comment by henrypp** [comment]
Tested, it bring when it starts:

`firewalltest.exe, ‎20.‎04.‎2023 ‏‎14:18:00, 192.168.2.2, DESKTOP-OE6GE1E, 53903, 195.201.201.32, 2ip.ru, 80 (http), tcp, Outbound, [B] Internal\BlockConnection`

**Comment by debobrov** [comment]
Here are my logs by filter, there is nothing, neither by
firewalltest nor firewalltest.exe
https://radikal.host/i/XYfsM1
https://radikal.host/i/XYfNO4

**Comment by henrypp** [comment]
My telepathy is really restricted.

**Comment by debobrov** [comment]
I added the program to the "Without access to the network" list, for some reason this does not help. I am attaching a screenshot.
https://radikal.host/i/XYg6tu

**Comment by debobrov** [comment]
> @debobrov You can use the [System Informer](https://systeminformer.sourceforge.io/nightly.php)'s Firewall tab to see which WFP filter allowed or blocked a program:
> 
You suggest me to use a trojan,  cool.
https://www.virustotal.com/gui/file/a4f05198d2ee505de6bb24e008b28228320548aeb32bf8e534ec2409bd1422cf

**Comment by tnodir** [comment]
> You suggest me to use a trojan, cool.

It's not a [trojan](https://github.com/winsiderss/systeminformer/issues/1668).

Anyway you can use other tool to view which WFP filter is allowing that test.

**Comment by henrypp** [comment]
> My telepathy is really restricted.

It is still.

I can't (i really can't) know what rules do you have.

**Comment by debobrov** [comment]
> > My telepathy is really restricted.
> > It is still.
> > I can't (i really can't) know what rules do you have.
I used the tcpview program (SYSINTERNALS) that's what it catches when you use the filter by name.
At the same time, the program is in the list without access to the Internet and in the list with a notification.
Unless global rules allow to ignore the program as the list, and out of the list?
https://radikal.host/i/XY2EPg

**Comment by henrypp** [comment]
My telepathy is really restricted.
And what it can help me?

>I used the tcpview program (SYSINTERNALS)...
