### ISSUE TITLE
[Bug] windows 11 3.6.x dont work, 3.5.3 work

### ISSUE THREAD

**Issue by developpeur-php** [henrypp/simplewall#1392]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.6.x

### Windows version

11

### Steps to reproduce

windows 10 work
windows 11 dont work only with 3.6.x
with the exact same basic config

### Expected behavior

...

### Actual behavior

...

**Comment by henrypp** [comment]
what does not work? any crash dump? or log?

**Comment by henrypp** [comment]
So, it is worked. I am working over Windows 11, so this issue is a not a bug.
