### ISSUE TITLE
[Bug] Linkedin blocked

### ISSUE THREAD

**Issue by yw4z** [henrypp/simplewall#1393]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.6.7

### Windows version

10

### Steps to reproduce

Opening linkedin with vivaldi (i guess other browsers will be same)
Try to sign

### Actual behavior

Browser says no internet connection on sign in or most of other pages on linkedin
i find which ip causing this
Blocklist > extra_13.107.42.14

**Comment by henrypp** [comment]
And, where is the problem to see in packets log what exactly is blocking your goddamn linkedin?

**Comment by yw4z** [comment]
do you need any further information, just wanted to inform you
short story 13.107.42.14 ip from simple wall blocklist is blocking linkedin. i guess it should not block a popular site by default
i dont have any problems with other sites and my browser is allowed for internet access
thanks

**Comment by henrypp** [comment]
>do you need any further information, just wanted to inform you
my logic already informed that:

many sites has hosted by cdn, which means that his not a single ip address, linkedin has hosted by cdn, so...
