### ISSUE TITLE
[Question] can windows firewall not be re-enabled after stopping simplewall?

### ISSUE THREAD

**Issue by popums** [henrypp/simplewall#1395]
when selecting the option to "disable filters", which prompts you to re-enable the windows firewall, afformentioned windows firewall does not in fact get re-enabled, and is blocked through seemingly a group policy - one that can not be found in the group policy editor.
![image](https://user-images.githubusercontent.com/84488356/234842016-815dbd99-a2ba-470e-891d-678a2c451a14.png)

**Comment by henrypp** [comment]
simplewall do not changing group policy
