### ISSUE TITLE
[Question] Simplewall queries files a LOT, preventing HDD from spinning down. 

### ISSUE THREAD

**Issue by coworo** [henrypp/simplewall#1396]
Describe the question with as much detail as possible.
![image](https://user-images.githubusercontent.com/98850730/235350104-18a54ade-3e00-4e18-9277-cb34f62b9709.png)

(refresh filters when storage devices are connected is off)

Is this an inherent requirement for how the app works? I imagined it would not need this for checking for running process. Maybe its for "Purge unused apps" function? If so is there way to make that check only happen on user request?

---

App version: 3.6.7
Windows version: 11 2H2H

**Comment by henrypp** [comment]
@Uj947nXmRqV2nRaWshKtHzTvckUUpD  u cant use settings? see here #1665

**Comment by henrypp** [comment]
@Uj947nXmRqV2nRaWshKtHzTvckUUpD why u need procmon, he dont show really *stats*

**Comment by henrypp** [comment]
@Uj947nXmRqV2nRaWshKtHzTvckUUpD

really stats is a counts of readed/writed number:

![sshot-002](https://github.com/henrypp/simplewall/assets/3902025/63eb29a6-082e-4e35-ae98-72207c0603b3)

use [process hacker](https://systeminformer.sourceforge.io/nightly.php) as example

**Comment by henrypp** [comment]
@Uj947nXmRqV2nRaWshKtHzTvckUUpD

> i looked into system informer as well and indeed there doesn't seem to be disk activity.

lol, every process have disk statistics counts how many he read/write

and it does not worry me about ur A LOT of disk activity
