### ISSUE TITLE
[Feature] Use sqlite instead xml

### ISSUE THREAD

**Issue by surf08** [henrypp/simplewall#1397]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.6.7

### Problem you are trying to solve

xml -> compressed sql

### Suggested solution

Can the compressed sqlite database be used instead of xml to store the profile? I see that everything (although not a firewall software) uses the compressed sqlite database to store the profile, and then add a setting item for the user to choose the storage location of the database.

**Comment by henrypp** [comment]
It needs a little more than nothing. Xml is working from beginning.
