### ISSUE TITLE
[Feature] Next to "Block connection" button, option to kill the task

### ISSUE THREAD

**Issue by FilthyChef** [henrypp/simplewall#1398]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.6.7

### Problem you are trying to solve

Hello! My favorite type of firewall is one that shows a pop-up asking to block internet connection for process that tries to grab some of it. When processes remind me of themselves like that, I sometimes feel like they not only deserve that access, but neither deserve to live.

### Suggested solution

If it isn't too much to ask, I (and probably many others) would appreciate an extra drop-down option to Block button: Kill process. Which would create a rule that prevents said process from running.

**Comment by vuslatx** [comment]
Good suggestion. I support it.
