### ISSUE TITLE
[Bug] Deleting svchost.exe from app list

### ISSUE THREAD

**Issue by nji9nji9** [henrypp/simplewall#1399]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.6.7

### Windows version

7

### Steps to reproduce

Deleting svchost.exe from the list is allowed/ offered by Simplewall as for all other apps
(really? "System"?). 

### Actual behavior

But doing this svchost is not removed.

So either the deleting is buggy,
or deleting should be grayed/ unabled for it.

Imho. Greetings!

**Comment by henrypp** [comment]
it is impossible, because it is stupid

**Comment by nji9nji9** [comment]
> it is impossible, because it is stupid

Do I get you right:
You call my feedback stupid?
And you state it's technical impossible?
The first would be ignorant and impudent,
the second would be simply wrong.

Maybe consider checking your testosterone level.

**Comment by henrypp** [comment]
No, but it has no logic at all. Because svchost is trying to go to inet like a 9000k in a hour, where is the logic to delete it from a list? Maybe set it as disable notifications, nothing more will help.

**Comment by nji9nji9** [comment]
OK, if it doesn't make sense to delete it, then you shouldn't allow the user to choose that. Even more you pop up a dialog that explicitely asks if svchost should be deleted. If you agree to that... nothing happens. So my suggestion for a good UI is to disable/ gray the option to delete it. Anything else would be a kind of deception of the user. I hope you understand what I mean this time (Same with "System" entry ... didn't try).

Hey man, I'm trying to help to improve your baby with my feedback, not to damage it. So be nice, please.

**Comment by nji9nji9** [comment]
... on the other side: it is an argument for sure to keep SimpleWall as small as possible, and not bloat it with a 100% GUI.
