### ISSUE TITLE
[enhancement] rule

### ISSUE THREAD

**Issue by perdolka** [henrypp/simplewall#140]
Option - Prevent an applications from opening a default web browser.  
Applications which specified by the rule.

**Comment by perdolka** [comment]
P.S. Чтобы не засорять  Issues тут спрошу - по какому принципу работают:
- Purge unused apps
- Purge invalid apps
?

Грубо говоря, по каким критериям они удаляют из списка?

**Comment by henrypp** [comment]
> Purge unused apps

Удаляет неиспоьзуемые приложения

> Purge invalid apps

Удаляет приложения с ошибками

По сабжу вообще не понял что вы от меня хотите
