### ISSUE TITLE
[Feature]  (Excellent work), You can put administrator password to modify

### ISSUE THREAD

**Issue by HugoBoror** [henrypp/simplewall#1400]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.6.7

### Problem you are trying to solve

(Excellent work), You can put administrator password to modify

### Suggested solution

(Excellent work), You can put administrator password to modify

### Screenshots / Drawings / Technical details

simplewall 
thanks

**Comment by henrypp** [comment]
What exactly do you need, i dont understand and why it can help

**Comment by necros2k7** [comment]
I think issue starter meant thay app should have an option to password protect app settings from say kids/users who want to mess with it,  I agree it can be a useful option
