### ISSUE TITLE
[Question] Is this a bug?

### ISSUE THREAD

**Issue by trythisd** [henrypp/simplewall#1401]
I allowed Chrome to access the Internet yesterday for a few hours with the Timer.  Now it's in the "Apps without internet access" list, but Chrome has access to the Internet and multiple connections are listed in the Apps section of the  Connections tab.  Why does Chrome still have access to the Internet when the Timer has expired?

---

App version: 3.6.7
Windows version: 10 21H2

**Comment by henrypp** [comment]
> Why does Chrome still have access to the Internet when the Timer has expired?

You are idiot or what?

**Comment by trythisd** [comment]
When the timer expired chrome.exe moved from "Apps with timer" to "Apps without internet access". Why is chome.exe in "Apps without internet access" while connections are showing in the Connections tab? And Chrome is loading web pages.  Shouldn't it be blocked from internet access?  Seems like the firewall's not working.
I restarted simplewall and now it prompts when I try to load a web page in Chrome.  Why was it allowing access without prompting before the restart?

**Comment by trythisd** [comment]
Everything works fine until I hibernate. When I start Windows after hibernation new connections are allowed even though the timers have long expired and the apps are in the no-access list.  This doesn't always happen and I can't get it to fail consistently and I can't determine the exact circumstances that make it happen. Since you know the code, can you think of why it might occur?  I'm pretty sure this is a bug. BTW, I love simplewall, it works great except for this one problem.

**Comment by trythisd** [comment]
After resuming from hibernation sometimes simplewall denies internet access to applications without prompting. The prompting starts working again a few minutes after resuming.
