### ISSUE TITLE
outlook doesn't connect [Question]

### ISSUE THREAD

**Issue by micheleod** [henrypp/simplewall#1402]
How do I make outlook work with simplewall? 
I'm using the desktop version of outlook, it says it can't connect to the server.

I've allowed the outlook app (indeed, I've tried to allow every single app) and it still doesn't work. I've also tried to allow all microsoft services through the blocklist tab.

(It only fails to connect to the email account that's on microsoft exhange)

Thank you!

---

App version: <enter app version here>
Windows version: 10

**Comment by henrypp** [comment]
Maybe packets log can help?

**Comment by micheleod** [comment]
Thanks, that helped. I had to allow the app "work or school account" under the tab UWP apps, I didn't know there were apps there too. Thanks a lot!
