### ISSUE TITLE
[Feature] Show app's time left before timer expiration

### ISSUE THREAD

**Issue by outyx** [henrypp/simplewall#1403]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.6.7

### Problem you are trying to solve

I can't see when an app's timer is going to expire unless I hover over the app and wait for the tooltip.

### Suggested solution

Add a column to the Apps tab showing the time left before expiration.

**Comment by henrypp** [comment]
not needed
