### ISSUE TITLE
[Bug] Asks permission for network access again when some apps are located at ramdisk

### ISSUE THREAD

**Issue by necros2k7** [henrypp/simplewall#1404]
@henrypp , @Henry2o1o 
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.6.7

### Windows version

win11

### Steps to reproduce

Apply rules for ramdisk located apps, reboot

### Expected behavior

Not asking again for app net access

During win11 boot - some apps are copied to ramdisk

### Actual behavior

Every time PC reboots yout have to allow ramdisk located apps to access network

As I see the problem is with following - files are copied to ramdisk AFTER Simplewall started and during start Simplewall don`t see them located on past paths and marks it as absent, so in order to work again one needs to confirm app access to net again and again after reboot (

**Comment by henrypp** [comment]
now it done 3.7.4
