### ISSUE TITLE
[Feature] Add keyboard shortcut system for blocking / unblocking certain apps network access

### ISSUE THREAD

**Issue by necros2k7** [henrypp/simplewall#1405]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.6.7

### Problem you are trying to solve

It will be useful for apps which doesn`t need network access for 24/7

### Suggested solution

for example I`d like to give Oculus services network access only for VR sessions, as soon as I exit game it should be blocked
a shortcut for blocking such apps would bl for apps which doesn`t need network access for 24/7
for example I`d like to give Oculus services network access only for VR sessions, as soon as I exit game it should be blocked
a shortcut for blocking such apps would be great
It also can be used between Steam, Epic, Origin, SteamVR , Virtual desktop sessions
It would also be useful for VM sessions when no network needed (Vmware, Virtualbox)

**Comment by henrypp** [comment]
You can select any app in list and press Space, thats all. This is doing the same.
