### ISSUE TITLE
[Bug] No permission pop-ups for apps that have previously had temporary access

### ISSUE THREAD

**Issue by iQuadCore** [henrypp/simplewall#1409]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.6.7

### Windows version

Windows 10 LTSC

### Steps to reproduce

1. Allow app to access internet with timer
2. Have your PC enter sleep mode
3. Switch the PC back on after timer should've expired

### Expected behavior

The app doesn't have internet access, and I'm asked to allow or deny it

### Actual behavior

Internet access is blocked for the app, but there's no pop-up asking for internet permission

**Comment by henrypp** [comment]
My telepathy is out of town, as always.
