### ISSUE TITLE
win7 bluescreen with fltMgr.sys

### ISSUE THREAD

**Issue by tokariu** [henrypp/simplewall#141]
I just got a BSOD as I double-clicked on the simplewall tray-icon.

```

fltMgr.sys
0x0000007e (0xffffffffc0000005, 0xfffff880019b7599, 0xfffff88009d6d348,  0xfffff88009d6cbb0)
--

```

OS setup: win7x64, simplewall 2.2 beta

**Comment by henrypp** [comment]
Install win7 updates, there is no simplewall reason.

**Comment by tokariu** [comment]
I'm currently on windows update level 2018/02, that is pretty up to date.
I thought it might have something to do with it, because simplewall just adds another filter layer and the BSOD happened with fltMgr.sys.
I'll check for new updates anyway and hope it won't happen again.

**Comment by henrypp** [comment]
`fltMgr.sys` is a filesystem filter driver (not network) and does not concerns with simplewall.

**Comment by tokariu** [comment]
allright! thanks for clarifying
