### ISSUE TITLE
Add Simplewall as a firewall provider

### ISSUE THREAD

**Issue by mdogancay** [henrypp/simplewall#1413]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.6.7

### Problem you are trying to solve

After windows firewall disable and simplewall got the firewall management, windows security throwing firewall disabled alerts. It's annoying. We need to register simplewall as a firewall provider.

### Suggested solution

There is an api in windows security described on here:
[Registering with Windows Firewall And Taking Ownership of Firewall Policy Management](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/ics/c-registering-with-windows-firewall-ownership)
i think this will do the trick.

If i got awailable time i will develop the feature. Otherwise those who have time can look.

**Comment by soilentgreen** [comment]
I had this problem. 
All I had to do is go to "local group policy" - "administrative templates" - "all settings",
find "windows defender firewall protect all network connection"  and disabled both.
its stop the alerts, and the icon back to green.

**Comment by henrypp** [comment]
dup #1440
