### ISSUE TITLE
does not work after changing motherboard

### ISSUE THREAD

**Issue by g1bber1sh** [henrypp/simplewall#1416]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

latest

### Windows version

10

### Steps to reproduce

change motherboard
= no outgoing connections are blocked even if the app (say firefox) is set to blocked in the firewall

### Expected behavior

keep blocking

### Actual behavior

lets the connection through

**Comment by henrypp** [comment]
ahahaha, changing motherboard is going to not working sw? where is the fucking logic? are you idiot or what?
