### ISSUE TITLE
[Feature] It would be nice if there was a function to register rules as a command

### ISSUE THREAD

**Issue by oklokl** [henrypp/simplewall#1417]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.6.7

### Problem you are trying to solve

netsh advfirewall firewall add rule name="Riot Games Outbound" dir=out action=allow program="D:\riot games\riot client\riotclientservices.exe" enable=yes protocol=TCP remoteport="80,443,2099,5222-5223,5000-5500,8393-8400"
Example.

I used to register and use it as above.

Although I manually registered with the firewall. Detected and blocked by simplewall.exe process.

I'm using the firewall and the simplewall.exe process at the same time.

### Suggested solution

simplewall.exe add rule name="Riot Games Outbound" dir=out action=allow program="D:\riot games\riot client\riotclientservices.exe" enable=yes protocol=TCP remoteport="80,443,2099,5222-5223,5000-5500,8393-8400"

Currently, this function is not available, but I hope it will be changed so that it can be easily registered.
I hope it is registered in the simplewall.exe process rules.
Registering one by one through the GUI takes a long time and is cumbersome.

The command I made is just an example.
I think it would work if I expressed it more simply.

thank you.
I am using it well.

I've come up with a suggestion idea.

application doodles (Additional notes)
for /f "delims=" %a in ('dir /a-d /b /o /s "D:\riot games\riotclientservices.exe"') do (netsh advfirewall firewall add rule name="Riot Games Outbound" dir=out action=allow program="%a" enable=yes protocol=TCP remoteport="80,443,2099,5222-5223,5000-5500,8393-8400")
Search and find. It is a command. I also register like this. this is an example

for /f "delims=" %a in ('dir /a-d /b /o /s "D:\riot games\riotclientservices.exe"') do (simplewall.exe add rule name="Riot Games Outbound" dir=out action=allow program="%a" enable=yes protocol=TCP remoteport="80,443,2099,5222-5223,5000-5500,8393-8400")

netsh advfirewall firewall = simplewall.exe > simplewall.exe GUI
netsh advfirewall firewall to simplewall.exe > simplewall.exe GUI
It is recognized in the same format. The difference is that it is registered in the "simplewall.exe GUI" process.

If I use simplewall.exe command
It is registered only in the simplewall.exe GUI process.
Idea content summary

When using the command "simplewall.exe," it will register with the "simplewall.exe GUI process" and not with the WF.msc Windows Firewall as before. In summary, to register it, you can use the "netsh advfirewall firewall" command or utilize the internal process functions of "simplewall.exe." There are various methods to consider as potential ideas.

**Comment by henrypp** [comment]
#1406
