### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by dave363636** [henrypp/simplewall#1418]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.67

### Windows version

Windows 10 22H2

### Steps to reproduce

With Simplewall I was able to sort by date with version 3.66, with version 3.67 this seems to be no longer possible and the apps with/without internet access are sorted alphabetically. Can this be changed?

### Expected behavior

With Simplewall I was able to sort by date with version 3.66, with version 3.67 this seems to be no longer possible and the apps with/without internet access are sorted alphabetically. Can this be changed?

### Actual behavior

With Simplewall I was able to sort by date with version 3.66, with version 3.67 this seems to be no longer possible and the apps with/without internet access are sorted alphabetically. Can this be changed?

**Comment by henrypp** [comment]
sort it by second column, where is the problem?

**Comment by henrypp** [comment]
sort it by second column, where is the problem?

**Comment by dave363636** [comment]
All right, clicking on the column works fine. Thought it was because of the new version. Therefore no bug but a human error. Sorry for that!
