### ISSUE TITLE
[Bug] Windows Updates not working when windows firewall is disabled

### ISSUE THREAD

**Issue by kdovale** [henrypp/simplewall#1420]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.6.7

### Windows version

2016 2019 hyperv-2019 hyperv-2016

### Steps to reproduce

1. install and enable simple wall, enable it and disable windows firewall
2. enable system, windows update service and wU delivery service
3. enable windows update under blocklist
4. settings rules allow windows update enabled
5.  try get updates..  down download or show.
6. disable simplewall and enable windows firewall
7. try get updates they list and download.

### Expected behavior

I dont want to use both wFirewall and simplwall, I want to use simple wall, but it seems some ips etc are still blocked. I need iit to be able tyo update automatically with simplewall enabled.

### Actual behavior

it doesnt allow updates to be downloaded.

**Comment by kdovale** [comment]
Seems like this ip is missing.. 209.197.3.8 I will check with other servers and see if there is other ips as well.

**Comment by soilentgreen** [comment]
I had this problem and I was able to fix it from this [link](https://github.com/henrypp/simplewall/issues/677) 
> ![BlocklistSettings](https://user-images.githubusercontent.com/3519946/192893665-da4e8821-175f-4838-8261-15dd5276af26.png)
> 
> ![SystemRulesSettings](https://user-images.githubusercontent.com/3519946/192898957-5d794648-88cf-405c-961d-d566c00f4e40.png)
> 
> ![ServicesSettings](https://user-images.githubusercontent.com/3519946/192899129-bd692394-da26-4446-96b4-9e20e8bb161e.png)

**Comment by kdovale** [comment]
Did you whitelist all traffic on port 443 and 80 to this with no ip restrictions ?Sent from my Galaxy
-------- Original message --------From: soilentgreen ***@***.***> Date: 2023/06/13  20:23  (GMT+02:00) To: henrypp/simplewall ***@***.***> Cc: kdovale ***@***.***>, Author ***@***.***> Subject: Re: [henrypp/simplewall] [Bug] Windows Updates not working when
  windows firewall is disabled (Issue #1420) 
I had this problem and I was able to fix it from this link

**Comment by soilentgreen** [comment]
I installed  today simplewall for the first time, and windows update didn't work.
After I follow the steps from the pics it fixed.
I didn't whitlist any traffic.

At first I only "allow windows update" under rules and the update was stuck on 0%. After that I went to settings - blocklist - and block microsoft spying, allow microsoft update and block microsoft apps, the update "work", but on reboot it stuck on 30%, and after the boot, I got notification that windows fail to update.
Aftet all of that I did the steps from the pics and windows updated successfully.

**Comment by soilentgreen** [comment]
I installed  today simplewall for the first time, and windows update didn't work.
After I follow the steps from the pics it fixed.
I didn't whitlist any traffic.

At first I "allow windows update" under rules and went to settings - blocklist - and block microsoft spying, allow microsoft update and block microsoft apps.
The update was stuck on 0%. After that I enabled rules of "windows update  delivery service and "windows uodate service". The update "work". Windowd download and install the update but on reboot it stuck on 30%, and after the reboot, I got notification that windows fail to update becuse it didn't download all the update or somthing like that, cant remember.
Aftet all of that I did the steps from the pics and windows updated successfully.

**Comment by kdovale** [comment]
I will try this thank you for your adviseGet Outlook for Android

**Comment by soilentgreen** [comment]
Did you fix it?
And didn't understand about Outlook for android.

**Comment by kdovale** [comment]
I tried it, it seems to sort out the issue, but it still seems as if its looking for something, but I want to do it on a few systems first, the one im on is not the fastest, but it looks like it works.

 

Kind Regards

 

Keith Dovale

**Comment by kdovale** [comment]
I have got it working fine using the wusvc option, I run a few hyperv core
servers, and there seems to be a process to update the svchost to get it to
work, first copy the svchost to wusvc then edit the registry service to
point to the wusvc file. Then disable any rules allowing windows update
svchost. Then enable the allow windows updates in the menu option Settings >
rules > allow windows updates, once done allow windows updates in the
blocklist  section as well as allow windows apps. Then under simplewall
check that the wuauserv service is pointing to the wusvc file and then under
system rules allow the windows update service, and windows delivery service,
then create a user rule to allow wusvc to ports 443 and 80. This seems to
allow the updates to process fine after this.. 

 

I can install cumulative updates etc all fine on these servers. Will keep an
eye on this tho

 

 

 

Kind Regards

 

Keith Dovale

**Comment by kdovale** [comment]
still seems this  update issue is a problem, some updates seem to update while others dont, if you disable simple wall and restart the windows update service it picks up other updates.. not sure what will be the best solution to resolve this properly.
