### ISSUE TITLE
[Feature] A add application (executable) manually 

### ISSUE THREAD

**Issue by swanknight** [henrypp/simplewall#1421]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.6.7

### Problem you are trying to solve

~~I want to block an application that's currently not running, and I don't want to run it before I can block it.~~ 
~~I want to browse, and select the executable file, and add it to the rule. Similar to Windows firewall.~~ 

### Suggested solution

~~An option to browse for the executable, instead of relying solely on the list.~~ 

### Screenshots / Drawings / Technical details

My bad, I found it under **File > Add Application**.

**Comment by Redundanz** [comment]
oh ! ohhh now i see. yup my bad. i see it now too

**Comment by swanknight** [comment]
> oh ! ohhh now i see. yup my bad. i see it now too
> 
> edit lol nevermind. i misread again... you can do what you want already...

No, you're right. I think I found it, but it's in a different place. It's under **File > Add Application** for some reason.
And then I had to right-click it, and create the rule. It's weird, but it works.
