### ISSUE TITLE
[Bug] Can't upload screenshots to Steam Cloud or send media in Steam chat

### ISSUE THREAD

**Issue by Jimochiri** [henrypp/simplewall#1423]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.6.7

### Windows version

Windows 8.1 / 10

### Steps to reproduce

Apply default blocklist including the `spy_20.60.20.4` rule.
Attempt to upload screenshot to Steam Cloud or send media in Steam chat using the Steam client for Windows.

### Expected behavior

Screenshot should be uploaded to Steam Cloud as normal, media should be sent in chat.

### Actual behavior

Screenshot is not uploaded to the Steam Cloud, giving a `"Failed to upload screenshot."` error.
Media is not sent in chat, giving a `"Failed to upload image data to cloud server."` error.

### Rules used
Spy-blocking rules enabled by default including the `spy_20.60.20.4` rule

This issue is also mentioned here: https://github.com/crazy-max/WindowsSpyBlocker/issues/503

### Logs

"‎20.‎06.‎23 ‏‎23:58:36","Admin-PC\Admin","C:\program files (x86)\steam\steam.exe","192.168.1.61","58528","20.60.20.4","443 (https)","tcp","FWPM_LAYER_ALE_AUTH_CONNECT_V4","Blocklist\spy_20.60.20.4","#165560","Outbound","Blocked"

"‎20.‎06.‎23 ‏‎23:57:50","Admin-PC\Admin","C:\program files (x86)\steam\bin\cef\cef.win7\steamwebhelper.exe","192.168.1.61","58523","20.60.20.4","443 (https)","tcp","FWPM_LAYER_ALE_AUTH_CONNECT_V4","Blocklist\spy_20.60.20.4","#165560","Outbound","Blocked"

**Comment by henrypp** [comment]
And? Where is the problem to just disable spy_20.60.20.4 rule?

**Comment by Jimochiri** [comment]
Maybe disable it by default so people don't get confused when their favorite gaming platform doesn't work correctly?

**Comment by henrypp** [comment]
I think to people who can see in log and can take decision, and this is no problem for her at all.

**Comment by Jimochiri** [comment]
So no dumb people allowed. Okay, I got it.

**Comment by henrypp** [comment]
Do not like idiots. nothing horrible.

**Comment by Jimochiri** [comment]
Being an idiot (like, mentally impaired) and just not being tech savvy enough to understand all that networking stuff are a bit different things, don't you think? Like, if your grandma doesn't know what IP, logs, etc. are - she's not an idiot, right? She could be a PhD in biology or physics, but following your reasoning, she's an idiot if she can't read a network log.
