### ISSUE TITLE
[Feature] Enhancement to Simplewall Microsoft Update so it properly works

### ISSUE THREAD

**Issue by XSpark0** [henrypp/simplewall#1427]
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.6.7

### Problem you are trying to solve

Problem: When i allow Microsoft Update from File > Settings > Blocklist since i want to update Windows, Windows Update still wont work. Until i manually enable internet access to services related to Windows Updates in Simplewall > Services [tab] and in System rules [tab]. It is annoying to manually enable and disable internet access to services related to Windows Updates every time in Simplewall > Services [tab] or having to click Disable Filters button.

### Suggested solution

Solution: It would great if Simplewall automatically enables and disables internet access to services related to Windows Updates in Simplewall > Services and in System rules [tab] whenever i allow or block/disable Microsoft Update from File > Settings > Blocklist.

This would allow Windows Update to work properly and i wont have to click Disable Filters button every time i want to Update Windows and unwillingly allow Microsoft spying and telemetry and risk bunch of other apps and services i don't want accessing internet without my permission while i have Filters Disabled during Windows Update.

**Comment by henrypp** [comment]
> Problem: When i allow Microsoft Update from File > Settings > Blocklist

WU is enabled in different way https://github.com/henrypp/simplewall#q-how-to-fix-windows-update-internet-access
