### ISSUE TITLE
[enhancement] add sort options for app-list

### ISSUE THREAD

**Issue by tokariu** [henrypp/simplewall#143]
I know there is a search function in simplewall, but I'm still missing a sort function for the app-list.

especially something that lets us sort the apps by "name" alphabetically asc/desc and "date-added".

**Comment by tokariu** [comment]
I just found out there is already a way to sort by app-name - by clicking on the path column.

**Comment by perdolka** [comment]
Anyway, it would be great to add a sorting by color.
