### ISSUE TITLE
[Bug] Repeatedly prompted for the same applications after they install an update

### ISSUE THREAD

**Issue by harveybolton** [henrypp/simplewall#1432]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.6.7

### Windows version

11, 22H2

### Steps to reproduce

If you make use of applications that contain their version numbers in their filepath (e.g. C:\Program Files\Microsoft OneDrive\23.124.0613.0001\FileCoAuth.exe) when one of these applications has an update which changes the filepath, SimpleWall behaves as though it's never seen it before and asks what I'd like to do. For a single app this would be tolerable but for many of the core Microsoft ones the popups are too frequent and annoying.

Frequent offenders appear to be first-party apps from Microsoft including but not limited to: "filecoauth.exe", "filesynchelper.exe", "microsoft.sharepoint.exe" and "msedgewebview2.exe"

### Expected behavior

I expected to be able to adjust the rules slightly to accommodate the slightly odd behaviour these applications exhibit during an update. Examples of what I'd need SimpleWall to do for this to be a non issue:

- Ignore the path and just evaluate the filename and signature: filename contains filecoauth.exe and signature contains Microsoft
- Wildcard part of the path: C:\Program Files\Microsoft OneDrive*\FileCoAuth.exe

Windows filtering platform doesn't support wildcards but it should be trivial for @henrypp to not prompt the user for the same app and instead just automatically adjust the windows filtering rules.

### Actual behavior

Repeatedly prompts me about the same file because it's had an update installed and the path has now changed to reflect the new version:

![image](https://github.com/henrypp/simplewall/assets/10099646/cc790b80-29b3-400e-82d2-8bdf941fa1d8)

**Comment by henrypp** [comment]
Yes, it is not existing issue, just use fucking search to find them. As example just search by "FileCoAuth.exe" you will see at least 10 items, ##1428.

**Comment by henrypp** [comment]
> should probs fix it then

What to fix, lol?

**Comment by harveybolton** [comment]
This problem multiple people are having
https://github.com/henrypp/simplewall/issues/1368#issuecomment-1500348772
https://github.com/henrypp/simplewall/issues/463#issuecomment-531023524

**Comment by Lordvader81** [comment]
It's evident that there are no intentions to tackle the issue. The same problem has been repeatedly pointed out in various posts by many users over more than a year, yet it persists. I understand that this is a free open-source application, but one would assume that such projects are initiated in the hope that they might evolve into a commercial product available through subscription or a one-time fee. However, with the persistent bugs in this application that remain unfixed, likely due to Henry's apparent arrogance, it seems unlikely.... Good Luck !!!
