### ISSUE TITLE
Crashes when Firefox is blocked ( Beta 2.2 )

### ISSUE THREAD

**Issue by v-i-r-u-s** [henrypp/simplewall#144]
Version ( Simplewall ) : Beta 2.2
Version ( Firefox )      : 56.0.2 ( 64Bit )
Version ( Win )          : Win10 Home 1709 (Build.: 16299.248) ( 64Bit )

Simplewall Beta 2.2 unfortunately crashes reproducibly when you block Firefox and call a URL.

**Comment by henrypp** [comment]
2.1.4 Stable is the same thing?
