### ISSUE TITLE
[Suggestion] To properly fix Windows nagging about Windows Firewall being turned off by having Simplewall recognized by Windows Security Center

### ISSUE THREAD

**Issue by XSpark0** [henrypp/simplewall#1440]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.6.7

### Problem you are trying to solve

Windows nagging everyday about Windows Firewall being turned off in Notifications at start-up.

### Suggested solution

Have Simplewall recognized by Windows Security Center. This will stop Windows from nagging without having to turn off entire Notifications system which i don't want to.

Windows Security Center should show something like this in this example image once it recognizes Simplewall as Third-party Firewall being used just like it does for Third-party Antivirus programs.

![193ss311](https://github.com/henrypp/simplewall/assets/136996874/0d05e7c3-7950-44ef-8e61-ee46ea71dc74)

Third-party Antivirus program example recognized by Windows Security Center:

![002046](https://github.com/henrypp/simplewall/assets/136996874/6fd357a1-070d-44e1-b1b2-c67e347ea90f)

**Comment by henrypp** [comment]
> I have used the search function to see if someone else has already submitted the same feature request.

Really? #364
