### ISSUE TITLE
How to create a rule to always allow One Drive to work without getting bored with blocking pop-ups?[Question]

### ISSUE THREAD

**Issue by Mac3DX** [henrypp/simplewall#1443]
Is there a way to always allow OneDrive to connect without having to keep bypassing this annoying blocking window? Every time, Microsoft.SharePoint.exe gets blocked by the SW.

Thanks
Ricardo
---

App version: 3.6.7
Windows version: 11

**Comment by henrypp** [comment]
you cant use seach? #853 #463

**Comment by Mac3DX** [comment]
I'm sorry but I'm very new dealing with firewall, and I really couldn't find a single tutorial on YouTube demonstrating the tool or how to use its rules functionalities. I wonder why?
Anyway, I appreciate your time.
