### ISSUE TITLE
Translations of 3 strings lost for many languages

### ISSUE THREAD

**Issue by ltguillaume** [henrypp/simplewall#1446]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

Recent commit

### Windows version

10

### Steps to reproduce

The commit https://github.com/henrypp/simplewall/commit/0399ff9558cf81ee562a285ed9f27cfbab997931 has reverted 3 string translations back to English for all languages:

```
IDS_USECERTIFICATES_CHK
IDS_SECUREFILTERS_CHK
IDS_SECUREFILTERS_HINT
```

The English (source) string hasn't changed, so this seems to have happened by mistake.

### Actual behavior

Translated strings should be recovered.

**Comment by henrypp** [comment]
this options was removed

**Comment by ltguillaume** [comment]
Ah ok, securing the filter (from being changed) isn't necessary anymore?

**Comment by henrypp** [comment]
it enabled by default,same for digital signatures
