### ISSUE TITLE
[Question] How to allow or ignore a process that uses different paths?

### ISSUE THREAD

**Issue by skupjoe** [henrypp/simplewall#1451]
How can I always allow or ignore a process that spawns under random/different/variable folders? 

For reference, here is one app that I have that constantly launches under different folders under `%LOCALAPPDATA%/temp` (5-10x times per day).

![image](https://github.com/henrypp/simplewall/assets/5000412/a6352bfb-24b0-4111-9a69-846f3c72b53f)

You can see that it is filling up my rules with junk:
![image](https://github.com/henrypp/simplewall/assets/5000412/57ac2f51-ac24-4262-9b65-3666ba9b64e3)

(I am trying to find a workaround for https://github.com/henrypp/simplewall/issues/1441 please)

**Comment by henrypp** [comment]
no way #853 #463

**Comment by skupjoe** [comment]
Please support wildcard based rules. This is needed desperately
