### ISSUE TITLE
The app crashes randomly after update to 3.7 version on windows 10

### ISSUE THREAD

**Issue by headzzzz** [henrypp/simplewall#1455]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7

### Windows version

Windows 10 22H2 (build 19045.3271)

### Steps to reproduce

Randomly crashing application
[simplewall-1690476470.zip](https://github.com/henrypp/simplewall/files/12185979/simplewall-1690476470.zip)
![crash](https://github.com/henrypp/simplewall/assets/140740850/4a93550f-5ff7-43dc-99e6-1226d1e7023d)
Means: "The instruction at address 0x%p referenced memory address 0x%p. Unable to perform memory operation: %s. (0xC0000005)"

### Expected behavior

After crash, application is ended

### Actual behavior

Crashed

**Comment by t0ma5** [comment]
![sshot-2023-07-27-23-10-51](https://github.com/henrypp/simplewall/assets/32952971/d1373ea0-0582-493f-9291-1fb178237f02)

I get this all the time since the latest update

**Comment by dlong500** [comment]
I can't get it to stay running for more than a few minutes at a time.  Same issue as OP.

**Comment by czz404** [comment]
This situation also occurs on win11 22H2

**Comment by g-k-m** [comment]
Same issue this is my crashdump 
[simplewall-1690502496.zip](https://github.com/henrypp/simplewall/files/12188936/simplewall-1690502496.zip)

**Comment by Sph1nX-GER** [comment]
Same for me, Win11 latest

*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************


KEY_VALUES_STRING: 1

    Key  : AV.Dereference
    Value: NullPtr

    Key  : AV.Fault
    Value: Read

    Key  : Analysis.CPU.mSec
    Value: 530

    Key  : Analysis.Elapsed.mSec
    Value: 847

    Key  : Analysis.IO.Other.Mb
    Value: 5

    Key  : Analysis.IO.Read.Mb
    Value: 0

    Key  : Analysis.IO.Write.Mb
    Value: 7

    Key  : Analysis.Init.CPU.mSec
    Value: 296

    Key  : Analysis.Init.Elapsed.mSec
    Value: 24150

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 146

    Key  : Failure.Bucket
    Value: NULL_POINTER_READ_c0000005_simplewall.exe!Unknown

    Key  : Failure.Hash
    Value: {176fd940-9c9c-e81b-2841-89265f4f8ae9}

    Key  : Timeline.OS.Boot.DeltaSec
    Value: 644

    Key  : Timeline.Process.Start.DeltaSec
    Value: 605

    Key  : WER.OS.Branch
    Value: ni_release

    Key  : WER.OS.Version
    Value: 10.0.22621.1

    Key  : WER.Process.Version
    Value: 3.7.0.0


FILE_IN_CAB:  simplewall-1690517941.dmp

CONTEXT:  (.ecxr)
rax=0000000000000001 rbx=0000000000000000 rcx=0000000000000005
rdx=0000000000000000 rsi=0000000000000000 rdi=0000000000000005
rip=00007ff67ff383b2 rsp=000000e75a1ffcf0 rbp=0000000000000000
 r8=0000000000000018  r9=0000000042d9c23c r10=0000000000000000
r11=0000023fb947a6c8 r12=0000000000000ecc r13=0000023fbfa11df0
r14=0000023fbfa11e80 r15=0000023fb95d3860
iopl=0         nv up ei pl zr na po nc
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010246
simplewall+0x283b2:
00007ff6`7ff383b2 488b1a          mov     rbx,qword ptr [rdx] ds:00000000`00000000=????????????????
Resetting default scope

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007ff67ff383b2 (simplewall+0x00000000000283b2)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000000
   Parameter[1]: 0000000000000000
Attempt to read from address 0000000000000000

PROCESS_NAME:  simplewall.exe

READ_ADDRESS:  0000000000000000 

ERROR_CODE: (NTSTATUS) 0xc0000005 - Die Anweisung in 0x%p verwies auf Arbeitsspeicher bei 0x%p. Der Vorgang %s konnte im Arbeitsspeicher nicht durchgef hrt werden.

EXCEPTION_CODE_STR:  c0000005

EXCEPTION_PARAMETER1:  0000000000000000

EXCEPTION_PARAMETER2:  0000000000000000

STACK_TEXT:  
000000e7`5a1ffcf0 00007ff6`7ff3ad30     : 00000000`00000000 00000000`0000018d 00000000`00000000 00000000`00000005 : simplewall+0x283b2
000000e7`5a1ffd30 00007ff6`7ff21bce     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : simplewall+0x2ad30
000000e7`5a1ffdc0 00007ffa`839a26ad     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : simplewall+0x11bce
000000e7`5a1ffe00 00007ffa`8512aa68     : 00000000`00000000 00000000`00000000 00000000`00000000 80000000`00000800 : kernel32!BaseThreadInitThunk+0x1d
000000e7`5a1ffe30 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x28


STACK_COMMAND:  ~3s; .ecxr ; kb

SYMBOL_NAME:  simplewall+283b2

MODULE_NAME: simplewall

IMAGE_NAME:  simplewall.exe

FAILURE_BUCKET_ID:  NULL_POINTER_READ_c0000005_simplewall.exe!Unknown

OS_VERSION:  10.0.22621.1

BUILDLAB_STR:  ni_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

IMAGE_VERSION:  3.7.0.0

FAILURE_ID_HASH:  {176fd940-9c9c-e81b-2841-89265f4f8ae9}

Followup:     MachineOwner
---------

[crashdump.zip](https://github.com/henrypp/simplewall/files/12190118/crashdump.zip)

**Comment by henrypp** [comment]
i think this is fixed now, but you can disable option "monitor apps changing" for now

**Comment by FiddleStickers** [comment]
Crash dump if it helps
[simplewall-1690629320.zip](https://github.com/henrypp/simplewall/files/12206960/simplewall-1690629320.zip)

**Comment by dubesor** [comment]
Having the same issues since the last update. No crashes before update to 3.7 

[dumpsummary.txt](https://github.com/henrypp/simplewall/files/12207107/dumpsummary.txt)
