### ISSUE TITLE
[Bug] No tray icon from 3.7 installing it from scoop.sh

### ISSUE THREAD

**Issue by frederikhors** [henrypp/simplewall#1460]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7

### Windows version

Win 10 22H2

### Steps to reproduce

- Remove every setting
- Reset the persist directory (where scoop write settings)
- Install it with Scoop

### Expected behavior

Tray icon is visible

### Actual behavior

Tray icon is not visible

**Comment by henrypp** [comment]
change SW file path to display icon

**Comment by frederikhors** [comment]
What path? I'm using Scoop.

**Comment by henrypp** [comment]
sw

**Comment by frederikhors** [comment]
I don't understand what you mean...

**Comment by FreePlague** [comment]
Great answer

**Comment by frederikhors** [comment]
> Great answer

Which one?

**Comment by frederikhors** [comment]
Also because we cannot change the path is it's a scoop installation.

**Comment by redactedscribe** [comment]
Every time I want to configure simplewall, which is often, I have to use the start menu because the tray icon isn't showing any more. The tray icon was working before version 3.7. Can this please be fixed @henrypp?

> change SW file path to display icon

I want to continue using simplewall via Scoop. What path should it be changed to? This would been all Scoop programs would have to have their path changed which isn't a good solution.

**Comment by FreePlague** [comment]
Fixed in 3.7.2

**Comment by FreePlague** [comment]
Broken again in 3.7.3

**Comment by redactedscribe** [comment]
> Broken again in 3.7.3

I also noticed this regression.

As a temporary workaround, you can run it from the 3.7.3 Scoop apps directory if you want the tray item to display.

**Comment by redactedscribe** [comment]
No improvement in 3.7.4. Please fix this @henrypp.

**Comment by FreePlague** [comment]
Fixed in 3.7.5

**Comment by FreePlague** [comment]
Oh no, it happened again in 3.7.6
