### ISSUE TITLE
[Bug] Cant start program, api-ms-win-core-version-l1-1-0.dll was not found (Windows 7)

### ISSUE THREAD

**Issue by syneekis415** [henrypp/simplewall#1461]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7

### Windows version

Windows NT 6.1.7601

### Steps to reproduce

1. Install version 3.7
2. Start it
3. Youll see the error

### Expected behavior

Open normally, Windows 7 was still supported according to website so I hope this is just an bug and will be fixed.

### Actual behavior

Shows error: "api-ms-win-core-version-l1-1-0.dll" is missing.
![errori](https://github.com/henrypp/simplewall/assets/80713560/569ecea5-5d1d-4c1c-8abc-3e3977a46706)
Heres word to word translation of the image:
simplewall.exe - Systemerror
Program can't start, because api-ms-win-core-version-l1-1-0.dll is missing. Try fixing problem by reinstalling the program again.

**Comment by idealth** [comment]
you can get simplewall to start by grabbing the missing x64 dll and moving it to `C:\Windows\System32`
https://www.dll-files.com/api-ms-win-core-version-l1-1-0.dll.html
to avoid the (0xC000025F) error mentioned [above](https://github.com/henrypp/simplewall/issues/1461#issuecomment-1655765699) you need to move the file below to `%appdata%\Henry++\simplewall` or if it's a portable installation you need to move it to where simplewall.exe is located
https://github.com/henrypp/simplewall/raw/master/bin/profile_internal.xml

**Comment by asmwarrior** [comment]
> you can get simplewall to start by grabbing the missing x64 dll and moving it to `C:\Windows\System32` https://www.dll-files.com/api-ms-win-core-version-l1-1-0.dll.html to avoid the (0xC000025F) error mentioned [above](https://github.com/henrypp/simplewall/issues/1461#issuecomment-1655765699) you need to move the file below to `%appdata%\Henry++\simplewall` or if it's a portable installation you need to move it to where simplewall.exe is located https://github.com/henrypp/simplewall/raw/master/bin/profile_internal.xml

Hi, I have the same issue as OP reported. And I have followed your advice, and download that dll in the save folder as the simplewall.exe, but unluckily, I still can not start the exe.

**Comment by rddim** [comment]
Same here

![simplewall_api](https://github.com/henrypp/simplewall/assets/8998791/9f6ce5a6-cefc-4b37-9264-544ca38b72df)

**Comment by idealth** [comment]
> > you can get simplewall to start by grabbing the missing x64 dll and moving it to `C:\Windows\System32` https://www.dll-files.com/api-ms-win-core-version-l1-1-0.dll.html to avoid the (0xC000025F) error mentioned [above](https://github.com/henrypp/simplewall/issues/1461#issuecomment-1655765699) you need to move the file below to `%appdata%\Henry++\simplewall` or if it's a portable installation you need to move it to where simplewall.exe is located https://github.com/henrypp/simplewall/raw/master/bin/profile_internal.xml
> 
> Hi, I have the same issue as OP reported. And I have followed your advice, and download that dll in the save folder as the simplewall.exe, but unluckily, I still can not start the exe.

i apologize as i should have made my original message more clear, you need to drag the dll to `C:\Windows\System32`

**Comment by geextahslex** [comment]
I had the same issue on Windows 7 today. Tried 3.7 and had to revert to 3.6.7

**Comment by henrypp** [comment]
Just rename version.dll to api-ms-win-core-version-l1-1-0.dll, or fucking stop using win7 for chist sake

**Comment by asmwarrior** [comment]
> Just rename version.dll to api-ms-win-core-version-l1-1-0.dll, or fucking stop using win7 for chist sake

Hi, I just make a copy of the file `C:\Windows\System32\version.dll` to `C:\Windows\System32\api-ms-win-core-version-l1-1-0.dll`.

And Now, I can start the simplewall.exe version 3.7.1 under Win7 64bit.

But when the application started, there is a dialog jump out, I have to click the "close" button to let it continues.

Here is the screen shot of the dialog box:

![image](https://github.com/henrypp/simplewall/assets/561818/cd0bb240-72d2-4837-b097-bab7cb3c7cdd)

Is this related the dll changes?

Thanks.

**Comment by asmwarrior** [comment]
> > > you can get simplewall to start by grabbing the missing x64 dll and moving it to `C:\Windows\System32` https://www.dll-files.com/api-ms-win-core-version-l1-1-0.dll.html to avoid the (0xC000025F) error mentioned [above](https://github.com/henrypp/simplewall/issues/1461#issuecomment-1655765699) you need to move the file below to `%appdata%\Henry++\simplewall` or if it's a portable installation you need to move it to where simplewall.exe is located https://github.com/henrypp/simplewall/raw/master/bin/profile_internal.xml
> > 
> > 
> > Hi, I have the same issue as OP reported. And I have followed your advice, and download that dll in the save folder as the simplewall.exe, but unluckily, I still can not start the exe.
> 
> i apologize as i should have made my original message more clear, you need to drag the dll to `C:\Windows\System32`

Hi, this method does not work in my Win7. My guess is that the download dll file is not compatible with the my Win7 system.

**Comment by asmwarrior** [comment]
> > Just rename version.dll to api-ms-win-core-version-l1-1-0.dll, or fucking stop using win7 for chist sake
> 
> Hi, I just make a copy of the file `C:\Windows\System32\version.dll` to `C:\Windows\System32\api-ms-win-core-version-l1-1-0.dll`.
> 
> And Now, I can start the simplewall.exe version 3.7.1 under Win7 64bit.
> 
> But when the application started, there is a dialog jump out, I have to click the "close" button to let it continues.
> 
> Here is the screen shot of the dialog box:
> 
> ![image](https://user-images.githubusercontent.com/561818/257152703-cd0bb240-72d2-4837-b097-bab7cb3c7cdd.png)
> 
> Is this related the dll changes?
> 
> Thanks.

I see that when I started the 3.7.1 in my Win7, and I just check the panel named "System rules", and I see its empty.

So, I guess that I can't use this version. I revert back to 3.6.7, and it works fine. The "System rules" panel has many rules predefined.

**Comment by henrypp** [comment]
No, just copy to profile directory, and restart SW

**Comment by asmwarrior** [comment]
> No, just copy to profile directory, and restart SW

Where is this profile directory? I dont see it in the installed folder where the simplewall.exe locates.

**Comment by henrypp** [comment]
where profile.xml located

**Comment by asmwarrior** [comment]
> where profile.xml located

OK, put the `profile_internal.xml` in the folder `%APPDATA%\Henry++\simplewall`, and I see the 3.7.1 version start fine now. Thanks.

BTW: I found this info from this post: https://github.com/henrypp/simplewall/issues/206#issuecomment-439871996

**Comment by dethknite** [comment]
WIn7 is EOL, and has not received any security updates since Jan. 14, 2020. If you are on Win7, a firewall GUI is the least of your worries. As for applications supporting deprecated / unsupported OS levels, one should expect that they will either have to remain on older versions of applications, or update their OS, as developers need to continue to improve upon, and update their applications to support newer OSs and security models.

**Comment by henrypp** [comment]
@elandorr you really know that is win10 have huge memory usage because of telemetry and other shit? it really started at vista that uses worst memory manager, even hello world uses 70mb of memory, you can check it yourself by vmmap.

**Comment by tamr** [comment]
> Hi, this method does not work in my Win7. My guess is that the download dll file is not compatible with the my Win7 system.

Pick that one 2.5 kb

> even huffman compression, why you use this shit?
> or fucking stop using win7 for chist sake

🙄
