### ISSUE TITLE
[Question] "Do not load icons" option behaviour

### ISSUE THREAD

**Issue by huldf** [henrypp/simplewall#1462]
The "Do not load icons" option is not immediately effective when checked/unchecked (i.e. nothing changes) even by pressing "Refresh" or "F5". The changes are only effective by quitting and relaunching the application.
Is it a normal behaviour?

---

App version: 3.7
Windows version: Windows 10 Enterprise N LTSC (21H2)

**Comment by henrypp** [comment]
it is dont load icons,when you enable this option,otherwise it displays already loaded icons
