### ISSUE TITLE
[Bug] Memory reference bug

### ISSUE THREAD

**Issue by TLCPlusPlus** [henrypp/simplewall#1464]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7

### Windows version

11 (22H2)

### Steps to reproduce

1. Keep simplewall running
2. get a popup box that says that a referenced memory error occured randomly.

### Expected behavior

Simplewall to work as expected in previous versions.

### Actual behavior

A dialogue error window popped up saying the following (copied from the popup window):

The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s. (0xC0000005)

### Logs

(no logs exist)

**Comment by henrypp** [comment]
when?

**Comment by TLCPlusPlus** [comment]
Just for reference on how bad this is, I had simplewall crash over 10 times already. I downgraded to the previous version to resolve the issue until it can be fixed.

**Comment by 00xBAD** [comment]
+1, same config: Win 10 Home 21H2 x64. I have simplewall on my desktop and my laptop, then after *today* update same memory reference error...

**Comment by henrypp** [comment]
#1455
