### ISSUE TITLE
[Bug] Import xml files not found

### ISSUE THREAD

**Issue by ImMakSpy** [henrypp/simplewall#1466]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7

### Windows version

10

### Steps to reproduce

1. Menu File > Import...
2. Go To Folder, where profile xml files exist
3. No files *.xml are shown due to a typo in "Profile files (*.sp, *xml)"
Correct is "Profile files (*.sp, ***.**xml)

### Expected behavior

all files *.xml are shown like in version 3.6.x

### Actual behavior

No files *.xml are shown

### Logs

![simplewall-3 7-profile-files](https://github.com/henrypp/simplewall/assets/86108248/7c7639c3-e886-4766-9b00-e4b4a345fd80)

**Comment by henrypp** [comment]
all files do not work too?
