### ISSUE TITLE
[Bug] Exception raised :(

### ISSUE THREAD

**Issue by aklakan17** [henrypp/simplewall#1468]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.0

### Windows version

Windows 11

### Steps to reproduce

<a href="https://fastpic.org/view/122/2023/0729/d2a0c3af8d5c5087fcbb63ec1ccd31e4.jpg.html" target="_blank"><img src="https://i122.fastpic.org/thumb/2023/0729/e4/d2a0c3af8d5c5087fcbb63ec1ccd31e4.jpeg" border="0"></a>

### Actual behavior

<a href="https://fastpic.org/view/122/2023/0729/d2a0c3af8d5c5087fcbb63ec1ccd31e4.jpg.html" target="_blank"><img src="https://i122.fastpic.org/thumb/2023/0729/e4/d2a0c3af8d5c5087fcbb63ec1ccd31e4.jpeg" border="0"></a>

**Comment by aklakan17** [comment]
[https://fastpic.org/view/122/2023/0729/d2a0c3af8d5c5087fcbb63ec1ccd31e4.jpg.html](url)

**Comment by aklakan17** [comment]
[https://i122.fastpic.org/big/2023/0729/e4/d2a0c3af8d5c5087fcbb63ec1ccd31e4.jpg?md5=3iNgXSBdDoTEFEQ_zqwFiw&expires=1690614000](url)

**Comment by aklakan17** [comment]
How can i fix it? This window appears every 10-15 minutes

**Comment by aklakan17** [comment]
Инструкция по адресу 0x%p обратилась к памяти по адресу 0x%p. Память не может быть %s. (0xC0000005)

**Comment by KloneBaker** [comment]
[simplewall-1690610731.zip](https://github.com/henrypp/simplewall/files/12206415/simplewall-1690610731.zip)

Same error, here's the dump.

**Comment by aklakan17** [comment]
The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s. (0xC0000005)

**Comment by henrypp** [comment]
#1455

**Comment by aklakan17** [comment]
again this error
[simplewall-1690627463.zip](https://github.com/henrypp/simplewall/files/12207050/simplewall-1690627463.zip)
