### ISSUE TITLE
loopback connections getting dropped despite allowing them in settings

### ISSUE THREAD

**Issue by tokariu** [henrypp/simplewall#147]
I've found an issue with the "Allow Loopback connections" setting (Settings -> Rules -> "Allow Loopback connections (recommended)".

I enabled this setting because I'm using a lot of software that depends on loopback connections. for instance, all the adobe programs use loopback connections. I enabled this setting and was wondering why photoshop took suddenly soooo long until it started up.. it hung for around one minute until it was loaded. 

I suspected a simplewall issue right away because it was the only thing that changed on my system. So i reviewed the dropped packet logs and found that (shortened):

> [‎03.‎2018 ‏] photoshop.exe (host\user) [Remote: 127.0.0.1:58989 (host)] [Local: 127.0.0.1:58988 (host)] (TCP) simplewall\BlockInboundConnectionsV4 [OUT-Loopback]

Despite enabling "Allow Loopback connections" in the program options, it is blocking/dropping the loopback connections from photoshop in this case.

I then created a custom global rule to allow both in/out connections for 127.0.0.1 and then started photoshop again: it's loading up within seconds, no dropped loopback connections in the simplewall log anymore.

so I suspect the setting in simplewall is not doing what it is supposed to do: allow loopback connections. I currently use the workaround with the custom rule to allow loopback connections.

**Comment by henrypp** [comment]
Do you understand what loopback means? Form wiki:

> refers to the routing of electronic signals, digital data streams, or flows of items back **to their source** without intentional processing or modification

Adobe software uses inter-process communication (IPC) through sockets _from one process to another_, it means there is NO LOOPBACKS AT ALL.

Just create rule to allow connections for a `127.0.0.1` address and apply them for a `adobe qt32 server.exe`, `dynamiclinkmediaserver.exe`, `dynamiclinkmanager.exe`, `lightroom.exe` and `photoshop.exe` processes.

**Comment by tokariu** [comment]
I'm sorry, I thought photoshop was connecting to itself on 127.0.0.1 and maybe it does, but it also does IPCs to dynamiclinkmediaserver.exe and the like, and probably i mixed those up. However, is it dangerous to allow 127.0.0.1 in/out globally? why should I specify localhost to some processes only?
