### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by johnbbbbbb** [henrypp/simplewall#1472]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7

### Windows version

10

### Steps to reproduce

Updating to 3.7

### Actual behavior

After the last update I get a popup window saying something like "memory at xx doesn't exist". See attached crashdump (zipped because github didn't allow for .dmp file)

### Logs

[simplewall-1690627936.zip](https://github.com/henrypp/simplewall/files/12207247/simplewall-1690627936.zip)

**Comment by henrypp** [comment]
> I have used the search function to see if someone else has already submitted the same bug report.

fucking hell #1455
