### ISSUE TITLE
[Bug] App keeps crashing after lastest update

### ISSUE THREAD

**Issue by wallbangz** [henrypp/simplewall#1474]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

v.3.7

### Windows version

Windows 11 10.0.25915 Build 25915 Insider Preview

### Steps to reproduce

Just run the application and let it run for about 10 minutes or so, crashdump attached.

### Actual behavior

App works for around 10 minutes and keeps randomly crashing for some reason

### Logs

[simplewall-1690644327-CRASHDUMP.zip](https://github.com/henrypp/simplewall/files/12207480/simplewall-1690644327-CRASHDUMP.zip)

**Comment by henrypp** [comment]
> I have used the search function to see if someone else has already submitted the same bug report.

fucking hell #1455

**Comment by wallbangz** [comment]
MY BAD
