### ISSUE TITLE
Simple Wall 3.7 Crash In Windows 11 PRO - July 2023 [Bug]

### ISSUE THREAD

**Issue by IagoMarlon** [henrypp/simplewall#1475]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7

### Windows version

Windows 11

### Steps to reproduce

Update Simple Wall Via SimpleWall Update Notification
After Update Nothing ACT
After 4 Minutes SimpleWall Crash With Message Of Memory Problem

### Expected behavior

Stability

### Actual behavior

Crash

### Logs

The Instruction 0x%p make referencie for memory at 0x%p. The memory could not be %s. (0xC0000005)

**Comment by aceace15** [comment]
got the same bug as here, this is the crash dump for me
[simplewall-1690650988.dmp.zip](https://github.com/henrypp/simplewall/files/12207653/simplewall-1690650988.zip)

version 3.7 Release, 64-bit (Unicode)

**Comment by henrypp** [comment]
> I have used the search function to see if someone else has already submitted the same bug report.

fucking hell #1455
