### ISSUE TITLE
[Bug] After recent update to 3.7 simplewall crashes regularly

### ISSUE THREAD

**Issue by KDAM71** [henrypp/simplewall#1476]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7 64-bit

### Windows version

windows 11 home 22H2  22621.2070

### Steps to reproduce

Have simplewall running.
I don't know the  cause of the crash.
It happens about every 10 minutes.

### Expected behavior

No crash.

### Actual behavior

Notification window saying:
The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s. (0xC0000005)
App isn't running anymore.
This happens about every 10 minutes.

### Logs

[simplewall-1690662432.zip](https://github.com/henrypp/simplewall/files/12207936/simplewall-1690662432.zip)

**Comment by hossein7r** [comment]
I think I get the same bug after the update.
Mine is giving me an "Exception raised :(" error. with the following error message and then crash:
The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s. (0xC0000005)

**Comment by henrypp** [comment]
> I have used the search function to see if someone else has already submitted the same bug report.

fucking hell #1455

**Comment by KDAM71** [comment]
I'm fucking hell sorry. I fucking hell did. I fucking hell don't know what went wrong.
