### ISSUE TITLE
[Bug] Regression , superslow app search in Ctrl-F Search menu

### ISSUE THREAD

**Issue by necros2k7** [henrypp/simplewall#1477]
@henrypp 
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.1 x64

### Windows version

11

### Steps to reproduce

Type any app name from the list to filter in Search menu (Ctrl-F)

### Expected behavior

Almost instant search, worked in previous version

### Actual behavior

Slow search in a list of apps

**Comment by necros2k7** [comment]
@AaronKnowls  press Thumb up to vote for issue

**Comment by Gahwa-Gahwa** [comment]
👍 Search in v3.7.1 is so slow, I had to downgrade to v3.6.7

**Comment by henrypp** [comment]
fixed, check new version
