### ISSUE TITLE
[Feature] Kill Switch

### ISSUE THREAD

**Issue by MysteriousShadow** [henrypp/simplewall#1478]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.7

### Problem you are trying to solve

Especially with this new update, simplewall tends to crash. I don't want unwanted applications sending any data via network when this happens.

### Suggested solution

Similar to VPNs, add a kill switch where if simplewall crashes or exits/disables unexpectedly, immediately kill all internet access.

**Comment by dethknite** [comment]
I may be incorrect, but it seems the WFP filters remain in WFP and active until removed (via the app), or reboot. Thus if the application is closed or killed, it will continue functioning with the current applied rules / filters. I tested this much and it seems to function this way.

**Comment by henrypp** [comment]
> I have used the search function to see if someone else has already submitted the same bug report.

fucking hell #1455

**Comment by MysteriousShadow** [comment]
@henrypp dude the focus of this post isn't about the bug. I only mentioned it to emphasize the potential usefulness of this feature. It's true I didn't know that the filters are still active even after the app closes/crashes, but this is not another bug report.

You also didn't even quote it right:
"I have used the search function to see if someone else has already submitted the same **feature** request."
