### ISSUE TITLE
Crash after update[Bug]

### ISSUE THREAD

**Issue by Oguzcan9** [henrypp/simplewall#1480]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7

### Windows version

Windows 11 Pro 64

### Steps to reproduce

Afder the update, it's keep crashing

### Actual behavior

When restart windows and and software still crash again

### Logs

[crashdump.zip](https://github.com/henrypp/simplewall/files/12208858/crashdump.zip)
![Screenshot_1](https://github.com/henrypp/simplewall/assets/140944322/03cd38e6-41ee-47d6-a223-a11995f4b109)

**Comment by henrypp** [comment]
> I have used the search function to see if someone else has already submitted the same bug report.

fucking hell #1455
