### ISSUE TITLE
[Bug] Crash

### ISSUE THREAD

**Issue by yw4z** [henrypp/simplewall#1481]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7

### Windows version

10 64-bit LTSC

### Steps to reproduce

-

### Actual behavior

-

### Logs

Randomly crashes with "The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s. (0xC0000005)"

Here crash dump
[simplewall-1690718372.zip](https://github.com/henrypp/simplewall/files/12209183/simplewall-1690718372.zip)

I changed some network adapter settings yesterday, it might be related with that, not sure which one causing that

My other apps working normal, simplewall crashes after 5-30 min

Thanks

**Comment by henrypp** [comment]
> I have used the search function to see if someone else has already submitted the same bug report.

fucking hell #1455
