### ISSUE TITLE
[Bug] Exception raised :(

### ISSUE THREAD

**Issue by mdogancay** [henrypp/simplewall#1482]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.0.0 Release 64bit

### Windows version

Windows 10 Pro 22H2

### Steps to reproduce

I did nothing, it's happened randomly

My Machine:
Processor	Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz   3.40 GHz
Installed RAM	16,0 GB
Edition	Windows 10 Pro
Version	22H2
OS build	19045.3208
Experience	Windows Feature Experience Pack 1000.19041.1000.0

### Actual behavior

![image](https://github.com/henrypp/simplewall/assets/3320364/665ca598-73e6-49b4-aeec-d636508913fd)

The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s. (0xC0000005)

### Logs

"Error","‎28.‎07.‎2023 ‏‎09:56:31","CreateFile","0x00000002","C:\Windows\system32\wusvc.exe","3.7","10.0 build 19045"
"Error","‎28.‎07.‎2023 ‏‎18:21:21","CreateFile","0x00000002","C:\Windows\system32\wusvc.exe","3.7","10.0 build 19045"
"Error","‎29.‎07.‎2023 ‏‎08:18:18","CreateFile","0x00000002","C:\Windows\system32\wusvc.exe","3.7","10.0 build 19045"
"Error","‎29.‎07.‎2023 ‏‎12:17:39","CreateFile","0x00000002","C:\Windows\system32\wusvc.exe","3.7","10.0 build 19045"
"Error","‎29.‎07.‎2023 ‏‎15:35:59","CreateFile","0x00000002","C:\Windows\system32\wusvc.exe","3.7","10.0 build 19045"
"Error","‎30.‎07.‎2023 ‏‎07:14:53","CreateFile","0x00000002","C:\Windows\system32\wusvc.exe","3.7","10.0 build 19045"
"Error","‎30.‎07.‎2023 ‏‎07:18:09","CreateFile","0x00000002","C:\Windows\system32\wusvc.exe","3.7","10.0 build 19045"
"Error","‎30.‎07.‎2023 ‏‎08:34:40","CreateFile","0x00000002","C:\Windows\system32\wusvc.exe","3.7","10.0 build 19045"
"Error","‎30.‎07.‎2023 ‏‎15:25:59","_wfp_createrulefilter","0x00000000","S-1-15-2-490905099-2794809881-2632752266-3514030558-4166392763-3416490339-321513134","3.7","10.0 build 19045"
"Error","‎30.‎07.‎2023 ‏‎15:26:00","CreateFile","0x00000002","C:\Windows\system32\wusvc.exe","3.7","10.0 build 19045"
"Error","‎30.‎07.‎2023 ‏‎15:36:33","CreateFile","0x00000002","C:\Windows\system32\wusvc.exe","3.7","10.0 build 19045"
"Error","‎30.‎07.‎2023 ‏‎15:36:35","_wfp_createrulefilter","0x00000000","S-1-15-2-490905099-2794809881-2632752266-3514030558-4166392763-3416490339-321513134","3.7","10.0 build 19045"
"Error","‎30.‎07.‎2023 ‏‎15:46:54","CreateFile","0x00000002","C:\Windows\system32\wusvc.exe","3.7","10.0 build 19045"
"Error","‎30.‎07.‎2023 ‏‎15:46:57","_wfp_createrulefilter","0x00000000","S-1-15-2-490905099-2794809881-2632752266-3514030558-4166392763-3416490339-321513134","3.7","10.0 build 19045"
"Error","‎30.‎07.‎2023 ‏‎16:02:47","CreateFile","0x00000002","C:\Windows\system32\wusvc.exe","3.7","10.0 build 19045"

**Comment by henrypp** [comment]
> I have used the search function to see if someone else has already submitted the same bug report.

fucking hell #1455

**Comment by mdogancay** [comment]
> 

This is a major problem @henrypp, so u have to FUCKING update the software if it already fixed. Or don't close the FUCKING issues. FUCKING github ONLY SEARCH FUCKING OPENED ISSUES BY DEFAULT.
