### ISSUE TITLE
Crashing after newest update [Bug]

### ISSUE THREAD

**Issue by g-k-m** [henrypp/simplewall#1483]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7

### Windows version

10 22H2 19045.3208

### Steps to reproduce

I booted my pc on, of course first thing in the morning after i wake up is to check for simplewall updates. I get the latest update. I close simplewall. which keeps running in tray icon, continue doing my stuff and then 2 mins later it crashes

### Expected behavior

Not crash

### Actual behavior

Crash

### Logs

Here's the crash dump
[simplewall-1690738673.zip](https://github.com/henrypp/simplewall/files/12209784/simplewall-1690738673.zip)

**Comment by henrypp** [comment]
> I have used the search function to see if someone else has already submitted the same bug report.

> fucking hell #1455
