### ISSUE TITLE
[Bug] Release 3.7 terminates with error dialog referencing memory

### ISSUE THREAD

**Issue by Mike737377** [henrypp/simplewall#1484]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7

### Windows version

Windows 10 (10.0.19045)

### Steps to reproduce

1. Run application
2. Application will terminate randomly with an error message. This could occur within seconds of starting to 20 minutes later.

### Actual behavior

Application displays error dialog and terminates.
Error dialog message is `"The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s. (0xC0000005)".`

### Logs

Last 2 crash dumps: [crashdump.zip](https://github.com/henrypp/simplewall/files/12210369/crashdump.zip)

`simplewall-debug.log` last entry for last crash:
`"Error","‎31/‎07/‎2023 ‏‎9:40:53 AM","CreateFile","0x00000002","C:\users\michael\appdata\local\microsoft\onedrive\onedrivestandaloneupdater.exe","3.7","10.0 build 19045"`

**Comment by jadegamestudio** [comment]
I am reporting the same exact problem. 

Today, simplewall 3.7 updated itself right after Windows 10 booted up. Moments later, it crashed with the same error as Mike's.

[simplewall-1690766742.zip](https://github.com/henrypp/simplewall/files/12210731/simplewall-1690766742.zip)

**Comment by HPSysteme** [comment]
same for me
[simplewall-1690778111.zip](https://github.com/henrypp/simplewall/files/12211530/simplewall-1690778111.zip)

**Comment by henrypp** [comment]
> I have used the search function to see if someone else has already submitted the same bug report.

fucking hell #1455
