### ISSUE TITLE
[Bug] uninstall.exe and associated regkeys being reported as a trojan by windows defender

### ISSUE THREAD

**Issue by xekablu** [henrypp/simplewall#1487]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7

### Windows version

10 22H2

### Steps to reproduce

Event viewer logs of Windows Defender:

_Microsoft Defender Antivirus has detected malware or other potentially unwanted software.
 For more information please see the following:
https://go.microsoft.com/fwlink/?linkid=37020&name=Trojan:Win32/Sonbokli.A!cl&threatid=2147728983&enterprise=0
 	Name: Trojan:Win32/Sonbokli.A!cl
 	ID: 2147728983
 	Severity: Severe
 	Category: Trojan
 	Path: file:_C:\Program Files\simplewall\uninstall.exe; file:_C:\Users\XXX\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\simplewall\Uninstall.lnk; regkey:_HKLM\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\UNINSTALL\simplewall; startup:_C:\Users\XXX\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\simplewall\Uninstall.lnk; uninstall:_HKLM\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\UNINSTALL\simplewall
 	Detection Origin: Local machine
 	Detection Type: FastPath
 	Detection Source: System
 	User: NT AUTHORITY\SYSTEM
 	Process Name: Unknown
 	Security intelligence Version: AV: 1.393.1910.0, AS: 1.393.1910.0, NIS: 1.393.1910.0
 	Engine Version: AM: 1.1.23060.1005, NIS: 1.1.23060.1005_

----------------

Got this notification today about an hour ago. As far as I can tell this was just shortly after a definitions update, as per event viewer a few minutes before:

----------------------

_Microsoft Defender Antivirus used cloud protection to get additional security intelligence.
 	Current security intelligence Version: 1.393.1910.0
 	Security intelligence Type: 
 	User: \
 	Current Engine Version: 1.1.23060.1005
 	Cloud protection intelligence Type: Security intelligence update
 	Persistence Path: C:\ProgramData\Microsoft\Windows Defender\Scans\RtSigs\data\ba95b038528aee1e4f583dfd20d238b6517ae4ee
 	Cloud protection intelligence Version: 1.393.1910.1
 	Cloud protection intelligence Compilation Timestamp: 31/07/2023 12:11:31
 	Persistence Limit Type: VDM version
 	Persistence Limit: 1.393.1910.1_

----------------

Leaving it quarantined for now, unsure if it's a false positive, but i do note something was changed regarding the uninstaller in 3.7. Not entirely sure how to safely get a checksum of the quarantined file to confirm if it was the original uninstaller.exe, or if this was due to it being replaced by something else. 

Presumably if this is happening to other people, they'll chime in shortly.

First bug report on here, apologies, let me know if i can supply anything else useful.

### Actual behavior

See above.

**Comment by henrypp** [comment]
ш вщте сфку

**Comment by shadeIess** [comment]
@xekablu I have the same issue as you.
Great response from the dev, sounds very trustworthy.
Will remove the app and will run several offline virus scans now.
Will let you know, if anything comes up.
