### ISSUE TITLE
[Question] uninstall.exe flagged as trojan

### ISSUE THREAD

**Issue by shadeIess** [henrypp/simplewall#1488]
While trying to update from 3.7 to 3.7.1, Windows defender flagged uninstall.exe as a trojan.
What gives?

---

App version: 3.7
Windows version: Win 10 22H2

![image](https://github.com/henrypp/simplewall/assets/51620694/4db44b7b-da36-4bf4-b0e6-655ae074b2b9)

**Comment by henrypp** [comment]
i dont care
