### ISSUE TITLE
Windowsw Antivirus quarantined files from Simplewall

### ISSUE THREAD

**Issue by Guttermedic1620** [henrypp/simplewall#1489]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7 64bit

### Windows version

Windows 11

### Steps to reproduce

I allowed the app to update per the auto updater to v3.7 64bit. this morning 7/31/23 
before noon I got an alert from Windows security that a file was quarantined from Simplewall ie the uninstall.lnk
app.

Trojan:Win32/Sonbokli.A!cl

![Screenshot 2023-07-31 144928](https://github.com/henrypp/simplewall/assets/141072519/3335b1bd-a71e-46df-a298-cf4610b1070a)

### Expected behavior

I understand about false positives. The app at this point seems to be working as needed. I will updated on any changes,
I did not quarantine.

### Actual behavior

App seems to be working. Unclear if there is any other issue at this time.

**Comment by Lexply** [comment]
Same here, it randomly popped up a few minutes ago. Except its "Trojan:Win32/Wacatac.B!ml" in _"C:\PROGRA\~1\SIMPLE~1\UNINST\~1.EXE"_

And when I restored it, windows defender quarantined it again as the same trojan but in  _"\\\localhost\C$\Program Files\simplewall\UNINST\~1.EXE"_

**Comment by henrypp** [comment]
i dont care
