### ISSUE TITLE
[Question] Why can't certain connections be closed/filtered?

### ISSUE THREAD

**Issue by MysteriousShadow** [henrypp/simplewall#1490]
I've tried to block all connections possible, filter out all apps, etc, but when I open resource monitor, there's still internet usage. In the Connections tab in Simplewall, normally, I can right click a connection and choose close connection, but in certain apps (not necessarily system apps), that option is greyed out. Any reason why, and in general, is it possible to achieve absolute zero network activities?

**Comment by Redundanz** [comment]
so, which connections are still using the internet? do you mind sharing a screenshot of yout connection overview with these apps that you can't block?

**Comment by XaaRii** [comment]
Might be a permissions issue? Like not running as administrator. Without any image with aforementioned "problematic" connections, we can hardly help you. Although you may be trying to see issues where there are none. There can be connections purely inside the computer, without any real outbound activity. These can be very useful, maybe even mandatory for OS to function properly.
