### ISSUE TITLE
[Bug] application crashes

### ISSUE THREAD

**Issue by biofibre** [henrypp/simplewall#1497]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

version 3.7.1 x64 install

### Windows version

Microsoft Windows 10 Pro 10.0.19045.3208

### Steps to reproduce

The application just ran in the tray

### Actual behavior

Crash sometimes, why, I don't know. Attached dump file.

### Logs

[simplewall-1690645314.zip](https://github.com/henrypp/simplewall/files/12232844/simplewall-1690645314.zip)

**Comment by kdovale** [comment]
ok happened again here is a crashdump 
[simplewall-1690912180.zip](https://github.com/henrypp/simplewall/files/12239463/simplewall-1690912180.zip)
