### ISSUE TITLE
Windows 7 support removed?

### ISSUE THREAD

**Issue by thatguy344** [henrypp/simplewall#1501]
With the most recent release from last week, every time i try to run simplewall it tells me that api-ms-win-core-version-l1-1-0.dll is missing and that it can't start due to this. 

I reverted back to the previous release from september and there are no issues whatsoever with that one. I'm on Windows 7 Ultimate x64, was support for Windows 7 removed in the newest release?

- Regards

**Comment by henrypp** [comment]
#1461
