### ISSUE TITLE
[Bug] update server connection error status 12007

### ISSUE THREAD

**Issue by Morasithil** [henrypp/simplewall#1503]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7

### Windows version

Windows 10

### Steps to reproduce

I have set simplewall to autostart when my computer boots.
Since the latest update i'm getting an error everytime i boot the machine.
This error happens because i always boot my pc offline to prevent the windows ping sender (boot and shutdown ping),
During the boot process simplewall is not active, i simply don't want microsoft to recive the pingsender so i boot offline.
That's why simplewall shows this error on every single boot: "update server connection error status 12007".

I could ofcourse just disable the autostart and if that doesn't work then disable the update checker but i don't want to do that.
Can i mute/gag/disable this error popup anyhow? It's getting a bit annoying over time.

### Expected behavior

explained already.

### Actual behavior

explained already.

**Comment by henrypp** [comment]
> This error happens because i always boot my pc offline to prevent the windows ping sender

aga, and why it is sw bug?

> 12007

means: "The server name or address could not be resolved"
