### ISSUE TITLE
[Bug] Exception raised - invalid parameter passed to service or function 0xC000000D

### ISSUE THREAD

**Issue by Morasithil** [henrypp/simplewall#1505]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7

### Windows version

Windows 10

### Steps to reproduce

As described in #1503 there an annoying update error since the 3.7 update when booting offline which i always do.
So i've decided to disable "periodically check for updates".
I tought this would solve my issue, turns out no it doesn't because now i got another error instead.
Exception raised - invalid parameter passed to service or function 0xC000000D

### Expected behavior

explained already.

### Actual behavior

explained already.

**Comment by henrypp** [comment]
#1486
