### ISSUE TITLE
MSFS can't start, after update simplewall

### ISSUE THREAD

**Issue by iKortev** [henrypp/simplewall#1506]
Subj stopped starting, reporting that there was no disk inserted. At the same time, the xbox app application works, the network sees and you can log into your account.
The bottom line is this: if I turn off "disable filters" in simplewall, then msfs starts without problems (access to the network for the flightsimulator.exe file is initially allowed).
If you run msfs with filters enabled, simplewall will ask for permission to access the file on the network every time you try to start msfs, but when permission is enabled, no result occurs until filtering is disabled.
The problem appeared just after upgrading from version 3.7.0 to version 3.7.1
In simplewall, I did not change anything, I just updated the application.
Firewall windows is off, I do not use any antiviruses.
In principle, I am an advanced user, but I don’t really delve into network matters.
Need your help, thanks!

---
App version: SimpleWall 3.7.1
Windows version: Windows 10 x64 ltsc eng

**Comment by iKortev** [comment]
I will add one more thing: earlier, on previous versions of simplewall, a similar problem also occurred, but it was floating and rare, there were such cases from two to five times a month and it could be fixed by simply restarting the computer, and I did not think that this could be related with simlewall, since in theory the firewall works on the on / off principle and there is nothing to break there.
Here are some thoughts.

**Comment by sds20020024** [comment]
Yep, exact same issue. I updated simplewall to 3.7.1, and then flightsimulator.exe stops working.
Everytime I open it, simplewall pops up asking for a decision to allow or block connection, and when I allow it, nothing happens.

When I hover over the .exe hyperlink, it shows 'Invalid (file not found or filter problem).
The file flightsimulator.exe is still there even when msfs is not launching, so it's not a temporary file.

Seems like a very specific issue with how flightsimulator.exe (which is a uwp app by nature) handles network connections?

I'll go back to 3.7.0 and see if it fixes it

**Comment by henrypp** [comment]
@pacitoman only debug log can see what happened

**Comment by pacitoman** [comment]
> @pacitoman only debug log can see what happened

Excuse my ignorance, where do I find the debug log?

**Comment by pacitoman** [comment]
> > > @pacitoman only debug log can see what happened
> > 
> > 
> > Excuse my ignorance, where do I find the debug log?
> 
> profile directory
[simplewall_debug.log](https://github.com/henrypp/simplewall/files/12320677/simplewall_debug.log)

Ah, here it is.

**Comment by henrypp** [comment]
@pacitoman you have error 0xC00000BA that is described as: "The file that was specified as a target is a directory and the caller specified that it could be anything but a directory."

**Comment by pacitoman** [comment]
> @pacitoman you have error 0xC00000BA that is described as: "The file that was specified as a target is a directory and the caller specified that it could be anything but a directory."
I don't understand. How can that file be a directory? And how was it fixed just by downgrading to v3.7.0? 
Weird.

**Comment by pacitoman** [comment]
> @pacitoman you have error 0xC00000BA that is described as: "The file that was specified as a target is a directory and the caller specified that it could be anything but a directory."

I don't understand. How can that file be a directory? And how was it fixed just by downgrading to v3.7.0?
Weird.

**Comment by Deathmaw** [comment]
Having the same issue, had no problems till v3.7x, not sure if started .0 or .1 but anything through the Game Pass app is having issues where the firewall is saying the file isn't valid even after I just allowed it through, at first thought it was just Redfall when I booted that the other day but then it happened to me again with Quake II that just came out on the service.

**Comment by henrypp** [comment]
there is only telepathy can help,if no debug logs than all is ok
