### ISSUE TITLE
[Question] New button in popout notification

### ISSUE THREAD

**Issue by Pozix** [henrypp/simplewall#1508]
Describe the question with as much detail as possible.

After you added the "Terminate Process" option from the notification popout, there is a new button (last screenshot) without a tooltip and I don't see it mentioned anywhere in the changelogs. 

What is it for? Is it to allow only this connection to this IP:Port without creating a rule? Does it create a rule? Is it a skip button like it used to be?

Please add a tooltip to explain what it's for.

![image](https://github.com/henrypp/simplewall/assets/16487174/7302599e-1cfd-4898-ba49-ace64cdd2e9a)
![image](https://github.com/henrypp/simplewall/assets/16487174/726130d2-c554-4d2d-aa2d-fe0ec7ca183a)
![image](https://github.com/henrypp/simplewall/assets/16487174/7a23bc58-6339-47f7-a431-a8ccbe094b66)
![image](https://github.com/henrypp/simplewall/assets/16487174/c8963fde-c7ff-472a-9439-9f82daf45c63)
![image](https://github.com/henrypp/simplewall/assets/16487174/0349b176-1c74-42d9-8716-348b2e42b810)

---

App version: 3.7
Windows version:  20H2-19042.804

**Comment by Pozix** [comment]
I'm guessing it's this action ?

![image](https://github.com/henrypp/simplewall/assets/16487174/dd240d1b-a340-400e-9005-c13f0f1a2826)

**Comment by henrypp** [comment]
yes
