### ISSUE TITLE
[Question] Can't install SimpleWall, complains about missing api-ms-win-core-path-l1-1-0.dll

### ISSUE THREAD

**Issue by EduardJacobs** [henrypp/simplewall#1509]
Describe the question with as much detail as possible.

Can't install SimpleWall, complains about missing api-ms-win-core-path-l1-1-0.dll. I downloaded this dll file and copied into System32 directory. Still complains about it. Installed Visual C++ redistributable 2019, still complains about missing dll  

My guess I'm missing some Windows updates that are need for the program to run

---

App version: 3.7.1
Windows version: 7 32Bit, SP1

**Comment by henrypp** [comment]
i really dont care,stop using win7 garbage
