### ISSUE TITLE
"disable notifications for this app" is gone in 2.2.2 (Beta)

### ISSUE THREAD

**Issue by AzimsTech** [henrypp/simplewall#151]
<img src="https://i.imgur.com/mjlm06S.png"></img> 

I found this feature is really **helpful,** please consider bring it back.

**Comment by henrypp** [comment]
![456](https://user-images.githubusercontent.com/3902025/38034220-9b024092-32c3-11e8-90b4-00a509360ca5.png)
Waych this.

**Comment by AzimsTech** [comment]
I mean the button, not the checkbox. Why cannot we have both?

**Comment by ddd111ddd** [comment]
Because with a single button you can't "Allow and Disable notifications", something that's very useful when you add custom rules to an exe. The checkbox is way better.
