### ISSUE TITLE
[Feature] Add a whitelist for the "monitor apps changing" option

### ISSUE THREAD

**Issue by huldf** [henrypp/simplewall#1510]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.7.1

### Problem you are trying to solve

Prevent specific apps from being monitored by this option (e.g. an app that you know is frequently changing due to frequent updates).

### Suggested solution

Adding a whitelist to specify apps you want to exclude from monitoring. For example, it could be added as a new tab in the app where you can check the apps you want to exclude + the option to exclude the app when opening the "edit" window.

### Screenshots / Drawings / Technical details

![1](https://github.com/henrypp/simplewall/assets/98712264/db36d883-857f-4fbd-b535-71d1f12b929e)
![2](https://github.com/henrypp/simplewall/assets/98712264/559078e6-24c7-4ccc-9ac8-079df6014798)

**Comment by henrypp** [comment]
unused
