### ISSUE TITLE
[Bug] Update popup window

### ISSUE THREAD

**Issue by AaronKnowls** [henrypp/simplewall#1511]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.1 64-bit

### Windows version

10

### Steps to reproduce

1. Windows starts and SimpleWall loads on startup
2. A popup window appears telling you that it's looking for updates.
3a. If there are any updates, it helps you updating it (which is great)
3b. If there are no updates, a popup window tells you just that. And it doesn't close until you accept it.

### Expected behavior

When there are no updates, no window should show up. 
Only when there are updates.
Just as it used to happen in previous versions (I'm not sure when this changed).

I couldn't find any solution to this either online, here or in the settings, and I don't want to disable updates. I apologize if I missed something. 
I wonder if by using some argument on my end this can be silenced. But I couldn't find any info about this apart for the installing and uninstalling arguments.

Thank you so much for this amazing and very useful software, Henry.

### Actual behavior

It shows a popup telling you there are no updates (unnecessary)
And you have to close it (annoying)

**Comment by henrypp** [comment]
sw didnt display message that is checking for updates

**Comment by eiszfuchs** [comment]
But... it does? I get this popup every time I boot. 🤔 
![20230825-194006-aebab342](https://github.com/henrypp/simplewall/assets/240167/90a80960-c433-4e0d-990a-8974f05a026e)

**Comment by henrypp** [comment]
it displayed ONLY when manually checking for updates, dont know what you do

**Comment by jacob-44** [comment]
Just to clarify: this pop-up appears every time you boot.

**Comment by chris-kwl** [comment]
Same here, I also get the pop-up since a few week after most (but not all) boots.

Simplewall 3.7.1, Windows 11 22H2
simple reinstalling Simplewall 3.7.1 via Setup (without removing it before) doesn't solve the problem

**Comment by davidebeatrici** [comment]
Confirmed, on multiple machines.

**Comment by henrypp** [comment]
fixed, check new version
