### ISSUE TITLE
Can windows do MAC address based filtering and would simplewall support this

### ISSUE THREAD

**Issue by pvswie** [henrypp/simplewall#1512]
The regular windows firewall allows rules that implement filtering at IP level. I am searching for a way to make MS-windows do MAC address based filtering in addition. I would like a windows based computer to only allow traffic to/from one specific device, a very uncommon setup. I came across Windows WFP that seems to support MAC based filtering and simplewall which looks like a user interface to WFP. After having installed simplewall cannot find how to create MAC based filters. Questions:
- Am I right that WFP would support MAC address based filtering?
- If so: can someone please point me towards how to use simplewall to do so
- If MAC address based filtering is supported by WFP but not by simplewall: can someone mention one or more alternative solutions

---

App version: 3.7.1
Windows version: 10 & 11

**Comment by henrypp** [comment]
no
