### ISSUE TITLE
[Bug] Crash after automatically looking for updates

### ISSUE THREAD

**Issue by ltguillaume** [henrypp/simplewall#1514]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.1

### Windows version

10 x64

### Steps to reproduce

1. Have simplewall loaded on system startup

### Expected behavior

Simplewall quietly looks for updates automatically.

### Actual behavior

1. Simplewall looks for updates automatically, but acts like the search for updates was triggered by the user. It shows the following dialog out of nowhere:
    ![image](https://github.com/henrypp/simplewall/assets/4777345/618c66d2-2b09-4d17-b541-31d70af3efcd)
2. When the dialog isn't immediately closed by the user (and the user instead clicks somewhere else focusing another program, simplewall crashes:
   ![image](https://github.com/henrypp/simplewall/assets/4777345/57626317-27d6-4298-92cd-8b37f3dbaf69)

### Logs

[crashdump.zip](https://github.com/henrypp/simplewall/files/12329294/crashdump.zip)

**Comment by huldf** [comment]
Also got that popup from time to time right after booting up the computer but didn't tried to click somewhere else. I will try to next time it appears.

**Comment by huldf** [comment]
> Also got that popup from time to time right after booting up the computer but didn't tried to click somewhere else. I will try to next time it appears.

Same crash error when not closing the popup. I also tested by manually searching for updates using the in-app button and I managed to get the same crash error too.

Steps that I made:
1 - Click the "Check for updates" button
2 - Press Win+D to get to desktop (I assume this works by doing other actions)

**Comment by kdovale** [comment]
We are seeing and experiencing various issues since version 3.7, this ranges from the app hanging and slowing the machine down, crashing and closing, and generally making the machines slow. This is ranging from windows 19 hyper-v core, windows 2008r2, windows 2016 std, windows 2019 and windows 10 and 11, there is definitely some issue that is now causing this issue. Can we revert back to 3.6 somehow ?

**Comment by ltguillaume** [comment]
> We are seeing and experiencing various issues since version 3.7, this ranges from the app hanging and slowing the machine down, crashing and closing, and generally making the machines slow. This is ranging from windows 19 hyper-v core, windows 2008r2, windows 2016 std, windows 2019 and windows 10 and 11, there is definitely some issue that is now causing this issue. Can we revert back to 3.6 somehow ?

I would recommend putting this in a _separate_ issue and providing more specific information:
1. `simplewall-??????????.dmp` files from the `crashdump` folder
2. Related entries from the Windows event log
3. Maybe information from the Windows Performance Monitor about simplewall's process

**Comment by kdovale** [comment]
Sometimes there are no dump files, it just raises and exception and closes, other times there are and the slowness or cpu hang doesn’t give any log or crashdump..

 

 

Kind Regards

 

Keith Dovale

**Comment by huldf** [comment]
Even if you can't get the crash dump file, it would be better to open a new issue for each separate problem (as @ltguillaume said) since this one only concerns the update popup issue, not performance issue or anything else.

**Comment by kdovale** [comment]
Here is the bug logs on my win 11 after the simple wall opens and checks for updates, the issues on the server seem also to be related to once you logon and simple wall is opened. 

 

 

 

Kind Regards

 

Keith Dovale

**Comment by ltguillaume** [comment]
@kdovale There are no bug logs attached to your post. I don't think attachments via mail are included here on GitHub.

**Comment by kdovale** [comment]
ok here they are dosnt support rar files.. :-). This issue occured once 3.7 was upgraded. it seems to be across all the platforms that this issue happens. Sometimes its fine with no issues, then all of a sudden a window pops up with a crash report. Other times it can be when you login and it opens up then it just closes with no crash report. Other times it just hangs and nothing can be done until you end task it and then reopen it. There is no specific procedure or way to replicate this it is totally random. I do see a higher cpu usage it its logging the failed connections to the screen. but that drops if you turn it off. 

[crashdump.zip](https://github.com/henrypp/simplewall/files/12352174/crashdump.zip)

**Comment by RH-BD** [comment]
I'm also facing the same problem in the last couple of days (win 10 x64). Also, when I click to restart it, laptop gets hanged momentarily...

**Comment by fahadif** [comment]
The crash issue actually happens after installing the latest update from 07-08-2023. Better skip this "Language Pack" update to avoid crashing.

**Comment by ltguillaume** [comment]
> The crash issue actually happens after installing the latest update from 07-08-2023. Better skip this "Language Pack" update to avoid crashing.

I **cannot** reproduce this: I copied back the language file from the release, started simplewall and checked for updates: the program still crashes when e.g. pressing Win+D for desktop while the window below is focused:

![image](https://github.com/henrypp/simplewall/assets/4777345/6c8178e2-5004-4ac4-b0ab-46135cdeced6)

**Comment by RH-BD** [comment]
![image](https://github.com/henrypp/simplewall/assets/71523303/65c0ec01-d025-4ca2-b8b1-363736515553)
Can you please help to solve this problem?

**Comment by mat-st** [comment]
Same error here. :\

App version

3.7.0 - 3.7.1

Windows version
11 x64 Version 2Y2 (Build 22621.2134)

The error started after updating to 3.7.0 as far as I can remember.

![simplewall_kX5G5ELOdv](https://github.com/henrypp/simplewall/assets/74657146/81f8f939-8ff0-4d92-a517-95bbe2fe65f9)

**Comment by kdovale** [comment]
is there no further fix to this issue ? It is constantly crashing now across all machines,  constant crash with no dump files being created.. I might stop using it now as its a PITA to keep having these crashes.

**Comment by huldf** [comment]
> is there no further fix to this issue ? It is constantly crashing now across all machines, constant crash with no dump files being created.. I might stop using it now as its a PITA to keep having these crashes.

You can simply temporarily disable the "Periodically check for updates" option so that the app does not search for updates until you do it manually, or you can also click the close button, which won't cause the app to crash.

**Comment by ivivaitylin** [comment]
I'm also getting the same crash issue occasionally after turning my PC on and the update check happens. Win 10 Pro build 19045. Zipped two crash dumps together.

Restarting simplewall always seems to fix the issue, so while it's not an urgent problem for me, it's an annoyance that I'd certainly appreciate getting fixed!
[crash dumps.zip](https://github.com/henrypp/simplewall/files/12457738/crash.dumps.zip)

**Comment by ltguillaume** [comment]
> I'm also getting the same crash issue occasionally after turning my PC on and the update check happens. Win 10 Pro build 19045. Zipped two crash dumps together.
> 
> Restarting simplewall always seems to fix the issue, so while it's not an urgent problem for me, it's an annoyance that I'd certainly appreciate getting fixed! [crash dumps.zip](https://github.com/henrypp/simplewall/files/12457738/crash.dumps.zip)

@ivivaitylin It would be good to know for sure if these crashes stop happening if the option "Periodically check for updates" is disabled.

**Comment by ivivaitylin** [comment]
> @ivivaitylin It would be good to know for sure if these crashes stop happening if the option "Periodically check for updates" is disabled.

Just disabled it, I'll report back if it crashes again. If I don't reply, assume it didn't!

**Comment by huldf** [comment]
@ltguillaume I tested it on a PC for several days and encountered no problems. Since it only crashes after looking for an update, I guess this is normal.

**Comment by fahadif** [comment]
> @ivivaitylin It would be good to know for sure if these crashes stop happening if the option "Periodically check for updates" is disabled.

Tried for a few days after disabling this option, but the issue was not solved. It still crashes sometimes.

**Comment by henrypp** [comment]
@fahadif because this is a dup of #1486, and not because of update checking

**Comment by ltguillaume** [comment]
It's probably not _completely_ the same, though. There may be a separate issue that comes with this one: whatever is causing the crash may not have anything to do with the fact that at start-up the dialog "No updates available" pops up while it shouldn't.

![](https://user-images.githubusercontent.com/4777345/260296019-618c66d2-2b09-4d17-b541-31d70af3efcd.png)
