### ISSUE TITLE
Log subscribe failed. Try again later

### ISSUE THREAD

**Issue by Danstiv** [henrypp/simplewall#1515]
Hello!

After updating simplewall, I periodically get the popup with error "Log subscribe failed. Try again later".
What does it mean and how can I solve this problem?
Thanks in advance for your reply.

---

App version: 3.7.1 Release, 64-bit (Unicode)
Windows version: Windows 10 22H2 (x64) build 19045.3324

**Comment by henrypp** [comment]
maybe error log or error code?

**Comment by Danstiv** [comment]
`"Warning","‎13.‎08.‎2023 ‏‎18:31:48","FwpmNetEventSubscribe","0x00000005","(null)","3.7.1","10.0 build 19045"`

**Comment by henrypp** [comment]
this means acces denied,dont know why,and do not do anything

**Comment by Danstiv** [comment]
This popup occurs when the program starts, as well as when windows wakes up from sleep mode.
It's a little annoying, can I debug this somehow?

**Comment by henrypp** [comment]
i dont know what bullshit you installed and/or configured

**Comment by t0ma5** [comment]
> This popup occurs when the program starts, as well as when windows wakes up from sleep mode. It's a little annoying, can I debug this somehow?

I have had the same problem for months.. none of the recent updates fixed it

**Comment by Rarlock** [comment]
**1. You need to write to the developer about simplewall problems (there are contacts in the program itself), apparently the simplewall update is to blame, I have been using the program with the latest updates for years without problems, but today the error log started flying out, the subscription failed, try again later. Status: 0x00000003, 2 things happened, deletion with registry cleaning. And installing a new one, rebooting and deleting the last added programs in the filter did not help. Only installing the old version of simplewall-3.6.1-setup helped. The case of imported filters with the new version does not cause an error now.

2. Надо писать  разработчику simplewall проблему(контакты в самой программе есть),  видимо виновато обновление simplewall, я пользовался  программой с последними обновлениями годами  без проблем, но сегодня начала вылетать ошибка log subscribe failed try again later Status: 0x00000003 причем 2 штуки, удаление с чисткой реестра и установка по новой, перезагрузка удаление последних добавленных в фильтр программ не помогли.  Помогло только установка старой версии simplewall-3.6.1-setup причем импортированные фильтры с новой версии сейчас не вызывают ошибку.

3. Debes escribir al desarrollador de simplewall sobre el problema (hay contactos en el programa en sí), aparentemente la culpa es de la actualización de simplewall, he estado usando el programa con las últimas actualizaciones durante años sin problemas, pero hoy aparece el error. la suscripción al registro falló, intente nuevamente más tarde Estado: 0x00000003 y 2 de ellos, la desinstalación limpiando el registro e instalando uno nuevo, reiniciando y eliminando los últimos programas agregados al filtro no ayudó. Solo ayudó la instalación de la versión anterior de simplewall-3.6.1-setup, y los filtros importados de la nueva versión ahora no causan ningún error.**

**Comment by Danstiv** [comment]
@t0ma5 @Rarlock 
I'm not sure, but this is probably happening if In Windows all programs are running on behalf of the administrator.
Sometimes such settings poorly affect some Windows API, perhaps this is just such a case.
On a clean Windows 11, with a run on behalf of the administrator setting disabled, I do not have a problem described here.
