### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by MKlown** [henrypp/simplewall#1518]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.1

### Windows version

11

### Steps to reproduce

Accept the invite to update.

### Expected behavior

Update

### Actual behavior

Seems to update.
Then reoffer to update a couple of days later the same version.
I belive 4 or 5 times already.
Not attached to any reboot. It seems completely random. It propose to reupdate the same version.
Accepting the update seems to work.
Till the next time it ask again for it.
Do the same on 2 different computers both on w11.

**Comment by huldf** [comment]
> * [x]  I have used the search function to see if someone else has already submitted the same bug report.

Please name your issues and read the existing ones before posting (#1513).
