### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by doctord919** [henrypp/simplewall#1519]
When windows boots, simplewall starts and starts scanning files on the disk. Everything slows down (I have a weak computer, but I have an ssd). The question is why? Can't we just apply the rules?

App version: All last version...
Windows version: 10

**Comment by agiz10** [comment]
Simplewall applications just adds rules to WFP.
When application is not running, rules that were set are still in effect and are blocking/allowing connections everything else is blocked. When application is running, you get additional functions (apps askeing (popup) for permissions to connect).

**Comment by henrypp** [comment]
sw dont scan any files
