### ISSUE TITLE
[Question] What does the play button in the tray pop-up do?

### ISSUE THREAD

**Issue by danielmmmm** [henrypp/simplewall#1520]
The pop-up in the tray area shows a new button (play symbol) on the bottom right that doesn't have a tooltip. What does it do?

---

App version: <3.7>
Windows version: <10>
![Tray pop-up](https://github.com/henrypp/simplewall/assets/3389179/7bca7ae7-ffe7-4ee0-adaf-073fbe1747c9)

**Comment by GrandFa** [comment]
> What does it do?

Next file.

**Comment by danielmmmm** [comment]
> > What does it do?
> 
> Next file.

Could you elaborate?

I clicked the play button, and the pop-up disappeared. There was no next file.
Also, does the current file get blocked or allowed? Is a rule created?
