### ISSUE TITLE
[Bug] The "next file" button in the tray pop-up can be clicked even when there is no next file to show

### ISSUE THREAD

**Issue by danielmmmm** [henrypp/simplewall#1523]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.1

### Windows version

10

### Steps to reproduce

Start a new app that tries to access the internet.
=> Simplewall shows the network alert pop-up with a "next file" button (without tooltip) on the lower right.

### Expected behavior

1) When only one new app asks for internet access, the "next file" play button should be greyed out and deactivated.
2) A tooltip should be shown when the mouse hovers over the button: "Next file (block current file)" or "Next alert (block current file)"

### Actual behavior

The "next file" button is clickable. It dismisses the pop-up ... and ads the current file to the list of apps without internet access?

**Comment by henrypp** [comment]
dup #1511

**Comment by henrypp** [comment]
it not a bug, and this button is good
