### ISSUE TITLE
[Feature] A colum with full path of files in the Apps tab

### ISSUE THREAD

**Issue by danielmmmm** [henrypp/simplewall#1524]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.7.1

### Problem you are trying to solve

In the Apps tab, some apps can have the same name (e.g. setup.exe) or a none-descriptive name. Currently, the full file path is only shown in a tool tip for one app at a time, when moving the mouse cursor over the app file name.

### Suggested solution

Add a column to the Apps tab that shows the full file path.
Since the app list only has two columns, "Name" and "Added", there is plenty of space for "Path".

A "Path" column could also be made available in "Connections" and "Packets log", but maybe disabled by default, because these two tabs already show a lot of information.

### Screenshots / Drawings / Technical details

`Name            Path                        Added`
`Setup.exe       C:\SomeApp\SomeWhere\       24.12.2022`

**Comment by henrypp** [comment]
fucking hell, what about already disable option "Show filenames option"?

**Comment by danielmmmm** [comment]
For fucks sake, sorry for not seeing the "View -> disable Show filenames option" or not thinking it would be there 🙄

**Comment by danielmmmm** [comment]
Also: I still think it would be useful to have filename to the left and path to the right of it. Users could identify the app quickly, and still get the path information for when it is needed. But I understand that it is a small change and that may not be worth the effort.
