### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by RChadwick7** [henrypp/simplewall#1525]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.7

### Problem you are trying to solve

There are many cases, such as setting up a printer, or a program that installs a service or driver that doesn't work. Is it Simplewall? It's not always clear.

### Suggested solution

What Tinywall does is have a 'Show Connections' feature. You can refresh to see activity in near realtime. Often you recognize the name of the program. Sometimes, as soon as you run the non-working application, you see a blocked system function that the program uses. It makes configuring and troubleshooting MUCH easier. It would be great if similar functionality was included in Simplewall.

**Comment by henrypp** [comment]
no,its not a sw

**Comment by RChadwick7** [comment]
I don't understand. It's not a sw? What is a sw? Thanks.
