### ISSUE TITLE
[Question] autostart only after execution prompt every time

### ISSUE THREAD

**Issue by firefoxlover** [henrypp/simplewall#1526]
I have the latest Github release.

When checking autostart, this only works after manually pressing "okay" on the "should this app run?" Dialog.

I think before it runs this means it leaks internet? 

I dont like Portmaster, but that has an early connection blocking service. It also doesnt have this startup prompt, how can it be removed?

**Comment by henrypp** [comment]
what a fuck are you talking about,sw already have boot-time filters

**Comment by firefoxlover** [comment]
wow strange language.

When loggin in (administrator user) in Windows 10 or 11, after some seconds the popup "execute simplewall?" pops up. This is not automatic and you need to click on it. It happens on two seperate machines, both administrator users.

Why are you simply closing this issue?

**Comment by henrypp** [comment]
because not anyone have this popup

**Comment by firefoxlover** [comment]
I have exactly this window of windows prompting me if I want to run this application on two seperate machines with two seperate OSses! The only similarity may be 

- I enabled "autostart on boot" in the settings
- I have blocked internet acccess for the windows scan thing
- I disabled antivirus
