### ISSUE TITLE
[Bug]Crash after  updates  to 3.7.1

### ISSUE THREAD

**Issue by atpersian** [henrypp/simplewall#1527]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.6.7

### Windows version

10 22H2

### Steps to reproduce

after update to new version it get crash on windows startup.

### Actual behavior

get black  it close

**Comment by henrypp** [comment]
>  I have used the search function to see if someone else has already submitted the same bug report.

Aha, believe
