### ISSUE TITLE
[Bug] invalid (file not found or filter problem) after adding a rule for a file that has a - in the directory name

### ISSUE THREAD

**Issue by helpfulBro** [henrypp/simplewall#1528]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.1

### Windows version

10x64

### Steps to reproduce

Add a rule (using the auto pop-up) for a file that is in a directory with a - in the name e.g.

G:\xboxgames\the texas chain saw massacre - pc edition\content\bbqgame\binaries\wingdk\bbqclient-wingdk-shipping.exe

### Expected behavior

A firewall rule should be added and the application can now access the internet

### Actual behavior

The rule is added but shows red as "Invalid file could not be found"

### Logs

Reverting back to 3.7 fixes the issue, the previous rule that was red now works OK.

**Comment by henrypp** [comment]
what error code in log

**Comment by helpfulBro** [comment]
1. Even if there is an existing rule SW asks to add another
![image](https://github.com/henrypp/simplewall/assets/25915621/40601474-bd93-4d0d-bf14-ba97e65b0aef)
2. Once added it looks like this
![image](https://github.com/henrypp/simplewall/assets/25915621/c23c4c9c-d512-41e9-bb99-ef7eda6fb46f)
3. Here is the Packet log
![image](https://github.com/henrypp/simplewall/assets/25915621/145f86d6-1502-403f-bfca-41595df9211d)

**Comment by henrypp** [comment]
fucking debug log

**Comment by helpfulBro** [comment]
lol - where do I find the fucking debug log?

**Comment by henrypp** [comment]
in profile directory

**Comment by helpfulBro** [comment]
"Error","‎26/‎08/‎2023 ‏‎7:10:31 PM","FwpmGetAppIdFromFileName","0xC00000BA","G:\xboxgames\the texas chain saw massacre - pc edition\content\bbqgame\binaries\wingdk\bbqclient-wingdk-shipping.exe","3.7.1","10.0 build 19045"

**Comment by isaacsu** [comment]
Since upgrading from version 3.7 to version 3.7.1, I've been encountering a similar problem with several of my Xbox games too, even if they do not have a ` - ` in their directory name.

Here are the relevant entries from my debug log:

```
"Error","‎29/‎08/‎2023 ‏‎7:17:26 PM","FwpmGetAppIdFromFileName","0xC00000BA","C:\xboxgames\minecraft dungeons\content\dungeons\binaries\win64\dungeons.exe","3.7.1","10.0 build 19044"
"Error","‎29/‎08/‎2023 ‏‎7:17:26 PM","FwpmGetAppIdFromFileName","0xC00000BA","C:\xboxgames\the elder scrolls v- skyrim special edition (pc)\content\skyrimse.exe","3.7.1","10.0 build 19044"
"Error","‎29/‎08/‎2023 ‏‎7:17:26 PM","FwpmGetAppIdFromFileName","0xC00000BA","C:\xboxgames\dishonored® definitive edition (pc)\content\binaries\win64\dishonored.exe","3.7.1","10.0 build 19044"
"Error","‎29/‎08/‎2023 ‏‎7:17:26 PM","FwpmGetAppIdFromFileName","0xC00000BA","C:\xboxgames\sniper elite 5\content\bin\sniper5_dx12.exe","3.7.1","10.0 build 19044"
"Error","‎29/‎08/‎2023 ‏‎7:17:26 PM","FwpmGetAppIdFromFileName","0xC00000BA","C:\xboxgames\sniper elite 5\content\launcher\sniperelite5.exe","3.7.1","10.0 build 19044"
"Error","‎29/‎08/‎2023 ‏‎7:17:36 PM","FwpmGetAppIdFromFileName","0xC00000BA","C:\xboxgames\minecraft dungeons\content\dungeons\binaries\win64\dungeons.exe","3.7.1","10.0 build 19044"
```

Downgrading to version 3.7 fixes the issue.

**Comment by henrypp** [comment]
author and @isaacsu: check this build [simplewall.zip](https://github.com/henrypp/simplewall/files/12506072/simplewall.zip)

**Comment by helpfulBro** [comment]
![image](https://github.com/henrypp/simplewall/assets/25915621/b4cbf9c2-8b8d-4127-afb6-beb0f8077ab5)
Same as before

**Comment by helpfulBro** [comment]
Thanks @henrypp - still the same as above even with the new file.

**Comment by demonkingzaine** [comment]
Having the same issue even with the latest test build.

**Comment by henrypp** [comment]
@helpfulBro same error code or what? specified apps still no inet access?

**Comment by helpfulBro** [comment]
Hey @henrypp - here is the error from the log. 

Same app, no internet access.
Same behaviour, constantly asks to allow/deny.

"Error","‎5/‎09/‎2023 ‏‎9:48:18 AM","FwpmGetAppIdFromFileName","0xC0000022","G:\xboxgames\the texas chain saw massacre - pc edition\content\bbqgame\binaries\wingdk\bbqclient-wingdk-shipping.exe","3.7.1","10.0 build 19045"

"Error","‎7/‎09/‎2023 ‏‎1:36:09 PM","FwpmGetAppIdFromFileName","0xC0000022","G:\xboxgames\the texas chain saw massacre - pc edition\content\bbqgame\binaries\wingdk\bbqclient-wingdk-shipping.exe","3.7.1","10.0 build 19045"


BTW as a suggestion for feature enhancement it would be helpful to have a link to 'debug log files' in the UI? Help -> Open debug log

**Comment by henrypp** [comment]
@helpfulBro & @isaacsu okay, i see, now check this build [simplewall.zip](https://github.com/henrypp/simplewall/files/12557391/simplewall.zip).

**Comment by demonkingzaine** [comment]
With that build everything appears to be working as intended on my end. All filters related to Xbox App titles are working both new and old. 

Thanks for all the hard work!

**Comment by helpfulBro** [comment]
Yep confirmed it's OK now. Thanks @henrypp

**Comment by Iruberiam** [comment]
This problem has reappeared, not sure when as I've only just started using Game Pass.

excerpt from debug log.

```

"Error","‎11/‎03/‎2024` ‏‎22:17:00","FwpmGetAppIdFromFileName","0xC00000BA","G:\games\lies of p\content\liesofp\binaries\wingdk\lop-wingdk-shipping.exe","3.7.1","10.0 build 22631"
"Error","‎11/‎03/‎2024 ‏‎22:18:19","FwpmGetAppIdFromFileName","0xC00000BA","G:\games\lies of p\content\liesofp\binaries\wingdk\lop-wingdk-shipping.exe","3.7.1","10.0 build 22631"
"Error","‎11/‎03/‎2024 ‏‎22:20:21","FwpmGetAppIdFromFileName","0xC00000BA","G:\games\lies of p\content\liesofp\binaries\wingdk\lop-wingdk-shipping.exe","3.7.1","10.0 build 22631"
"Error","‎11/‎03/‎2024 ‏‎22:23:35","FwpmGetAppIdFromFileName","0xC00000BA","G:\games\lies of p\content\liesofp\binaries\wingdk\lop-wingdk-shipping.exe","3.7.1","10.0 build 22631"
"Error","‎11/‎03/‎2024 ‏‎22:37:21","FwpmGetAppIdFromFileName","0xC00000BA","G:\games\lies of p\content\liesofp\binaries\wingdk\lop-wingdk-shipping.exe","3.7.1","10.0 build `22631"
```

**Comment by h7896v7347** [comment]
Just got Xbox Game Pass, and have the same problem when running 3.8.4.0. Clicking allow does nothing - game does not connect and packet log shows 40 records like that. 

`cod.exe, ‎18.‎10.‎2024 ‏‎20:30:42, 192.168.0.19, M, 2850, 4.209.244.239, 443 (https), tcp, Outbound, [B] Internal\BlockConnection`

Downgrade to 3.7.2.0 allows me to play games.

 When i switch back to 3.8.4.0 and export rules it is truncating game path to just c: and is blocking game.

`<item path="C:\" timestamp="1729276112" is_enabled="true"/>`

![image](https://github.com/user-attachments/assets/c6306128-d0e9-4fb5-a108-a870d2379306)


File - Add App -> cod.exe end with error you need admin permissions 

Only lines in debug log

`""Error","18.10.2024 20:34:07","_wfp_createrulefilter","0x00000000","S-1-15-2-3206916597-2687442160-1101572673-481554874-1490292038-318123121-2058052176","3.8.4","10.0 build 22631"
"Error","‎18.‎10.‎2024 ‏‎20:40:12","_r_fs_createfile","0xC000003A","C:\users\m\appdata\local\arenabreakoutinfiniteminiloader\arenabreakoutinfiniteminiloader.exe","3.7.2","10.0 build 22631"
"Error","‎18.‎10.‎2024 ‏‎20:40:12","_r_fs_createfile","0xC000003A","C:\users\m\appdata\local\arenabreakoutinfiniteminiloader\tiny_dl\versionservice.exe","3.7.2","10.0 build 22631"
"Error","‎18.‎10.‎2024 ‏‎20:40:16","_wfp_createrulefilter","0x00000000","S-1-15-2-3206916597-2687442160-1101572673-481554874-1490292038-318123121-2058052176","3.7.2","10.0 build 22631"
"Error","18.10.2024 20:41:12","FwpmFilterGetSecurityInfoByKey0","0x80320003","D:\projects\simplewall\src\notifications.c:120","3.8.4","10.0 build 22631"
"Error","18.10.2024 20:41:12","FwpmFilterGetSecurityInfoByKey0","0x80320003","D:\projects\simplewall\src\notifications.c:120","3.8.4","10.0 build 22631"
"Error","18.10.2024 20:41:12","FwpmFilterGetSecurityInfoByKey0","0x80320003","D:\projects\simplewall\src\notifications.c:120","3.8.4","10.0 build 22631"
"Error","18.10.2024 20:41:12","FwpmFilterGetSecurityInfoByKey0","0x80320003","D:\projects\simplewall\src\notifications.c:120","3.8.4","10.0 build 22631"`

**Comment by henrypp** [comment]
@h7896v7347 0xC000003A is a error code means file not found, it is not SW problem, correct your computer!

**Comment by h7896v7347** [comment]
> @h7896v7347 0xC000003A is a error code means file not found, it is not SW problem, correct your computer!

You are referring to log about other game, it was working fine with it, game was uninstalled. 

Problem is with games in Xbox Game pass on newer SW

Clicked Allow:
![sgHYgrK](https://github.com/user-attachments/assets/5e1575c7-accf-4c34-8225-c05de6f795b3)

Connections are blocked:
![1Xi4HcT](https://github.com/user-attachments/assets/96221931-107b-4f01-af53-459445609b9b)

cod.exe rule is changing path to c:/ after simplewall restart or system reboot:
![image](https://github.com/user-attachments/assets/48d08a77-c616-440a-a850-5ecdd42517f4)

After reboot:
![image](https://github.com/user-attachments/assets/35037703-7dcb-494f-b83a-6125cf2f664a)


Bellow are cleared logs after unused apps purge, and 3 attempts to start game with 3.8.4.0 version:

`"Error","26.10.2024 12:33:31","_wfp_createrulefilter","0x00000000","S-1-15-2-3206916597-2687442160-1101572673-481554874-1490292038-318123121-2058052176","3.8.4","10.0 build 22631"
"Error","26.10.2024 12:39:01","_wfp_createrulefilter","0x00000000","S-1-15-2-3206916597-2687442160-1101572673-481554874-1490292038-318123121-2058052176","3.8.4","10.0 build 22631"
"Error","26.10.2024 12:40:51","_wfp_createrulefilter","0x00000000","S-1-15-2-3206916597-2687442160-1101572673-481554874-1490292038-318123121-2058052176","3.8.4","10.0 build 22631"
`

3.7.2.0 - is working fine with same game from xbox gamepass. Newer versions are asking for permission every game start, and game has no network connectivity.

**Comment by FCPerfectO** [comment]
what rules/programs I have to enable, so my XBOX app on Windows 11 23H2 can download games? I have to disable SW at all, so XBOX app can download a new game from the MS Store.

**Comment by 8176135** [comment]
@h7896v7347 I can replicate the issue that you mentioned. You can also see with WFP Explorer the path that gets added to WFP is just the base drive, not the full path to the binary that I added the rule to. 

Works fine on 3.7.8
