### ISSUE TITLE
[Bug] Exception raised: Invalid parameter(0xC000000D)

### ISSUE THREAD

**Issue by Kamilkampfwagen-II** [henrypp/simplewall#1530]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.1

### Windows version

Windows 10 21H2 (19044.1288)

### Steps to reproduce

1. Start simplewall
2. Everything works fine. Access prompt shown multiple times at random before the crash happens.
3. At random (an app might be requesting access) it throws an exception & exits. 

### Actual behavior

![resim](https://github.com/henrypp/simplewall/assets/84380947/91daaedd-4ec4-4335-a3b4-5aff36737f88)

### Logs

Crash Dump
[simplewall-1693573270.zip](https://github.com/henrypp/simplewall/files/12498274/simplewall-1693573270.zip)

Logs (stripped entries before the latest boot)
[simplewall_debug.log](https://github.com/henrypp/simplewall/files/12498294/simplewall_debug.log)

**Comment by henrypp** [comment]
> I have used the search function to see if someone else has already submitted the same bug report.

aga,believe... #1486

**Comment by Kamilkampfwagen-II** [comment]
In my case it doesn't crash at startup nor it happens frequently. I haven't read all the comments but the title specifically says Windows 11
