### ISSUE TITLE
[Feature] Please remove "No updates available" alert that requires pressing the button.

### ISSUE THREAD

**Issue by jacob-44** [henrypp/simplewall#1531]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.7.1

### Problem you are trying to solve

Please remove "No updates available" alert that requires pressing the button.

### Suggested solution

Please remove "No updates available" alert that requires pressing the button.

### Screenshots / Drawings / Technical details

<img width="265" alt="48395743" src="https://github.com/henrypp/simplewall/assets/56795574/e55a2d23-d40b-4f0b-8b54-f8136a1978e9">

**Comment by henrypp** [comment]
#1511
