### ISSUE TITLE
[Question] Is the Firewall component needed for simplewall to work as itended?

### ISSUE THREAD

**Issue by geextahslex** [henrypp/simplewall#1532]
Hi I am about to debloat my Windows 10 ISO and I want to know if the "Windows Firewall" (System component) is needed for simplewall to work as itended. I also remove Defender, Security etc.
I know that simplewall works when the Firewall service is disabled, but I never removed that component.

Thank you

**Comment by henrypp** [comment]
not needed

**Comment by geextahslex** [comment]
Thats good. Thank you
