### ISSUE TITLE
[Feature] Why was the feature "Enable protection of installed filters" (and some others) removed?

### ISSUE THREAD

**Issue by gettysburg** [henrypp/simplewall#1533]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.7.1

### Problem you are trying to solve

Hello,

simplewall used to have a check-box to deny access to the filter-set from unprivileged applications:

IDC_SECUREFILTERS_CHK

The following other checkboxes were also seemingly removed:

IDC_USECERTIFICATES_CHK
IDC_USEREFRESHDEVICES_CHK

Here is a screenshot from the last version that had those check-boxes (3.6.7):

![image](https://github.com/henrypp/simplewall/assets/2256003/e433ca35-1cc3-4248-aee2-cbe21e0edd81)

These were some really useful features, and especially the filter protection code that simplewall had made sure that no other application could tamper with it's filters, or it at least made it harder to do so.

Security wise, I think this is a huge step back, **unless** the code is still active, but just the user-choice has been removed (GitHub's search is kind of bad when it comes to searching older branches / tags).

Also, this gives the user less of a choice, if these features had bugs in them, please do not remove them, but fix the bugs instead, we are patient and will wait for an update, but don't just take away useful features please.

Right now I am forced to down-grade to v3.6.7, just because you removed these features.

### Suggested solution

Please re-implement these features and their regarding config options, so that the user can choose if they want them or not.

**Comment by henrypp** [comment]
because options is useless,and now is enabled by default

**Comment by gettysburg** [comment]
How about adding the other features back?

**Comment by henrypp** [comment]
like what?

**Comment by gettysburg** [comment]
Refresh on device insertion and signature verification.
