### ISSUE TITLE
[Feature] Option to not inform user of an update not being available

### ISSUE THREAD

**Issue by herrenP** [henrypp/simplewall#1534]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.7.1

### Problem you are trying to solve

Whenever I log in to Windows I get a dialog window from simplewall saying that there is no update available.

### Suggested solution

Do not inform user if there is no update. This, in my experience, is the default for most apps. I do not need to know that there was no update available. I do want to know when there is one available however. This could be an optional setting.

### Screenshots / Drawings / Technical details

![2023-09-04_22-03](https://github.com/henrypp/simplewall/assets/7075636/3455e52b-c697-47bc-99ed-31a432ca75bf)

**Comment by henrypp** [comment]
dup #1511

**Comment by herrenP** [comment]
Weird. I searched for "update" but did not find the original issue. Thanks!
