### ISSUE TITLE
Starting version 3.7 the application won't run - Error: api-ms-win-core-libraryloader-l1-1-0.dll is missing even when Visual Studio 2015, 2017, 2019, and 2022 is installed

### ISSUE THREAD

**Issue by mcodr** [henrypp/simplewall#1538]
When installing the application / Nor trying to use the portable version.
![image](https://github.com/henrypp/simplewall/assets/7112407/cfe9c692-5f99-48c6-84d5-1e5f34349941)

---

App version: 3.7 and up
Windows version: Windows 7 x86

**Comment by henrypp** [comment]
i dont care
