### ISSUE TITLE
[Bug] Gamepass games not seen by simplewall?

### ISSUE THREAD

**Issue by Manimap** [henrypp/simplewall#1539]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.1

### Windows version

10 build 22h2

### Steps to reproduce

1- Install a game from the xbox / gamepass application. I've seen this issue with forza horizon 5.
2- Allow traffic completely for the main exe.

### Expected behavior

Traffic should be allowed.

### Actual behavior

I still got popups asking me to allow traffic despite it being pretty much any out open.

### Logs

When I looked at the rule I got this : 
![image](https://github.com/henrypp/simplewall/assets/13313380/beb8797d-3eb2-48e3-984a-ca8b18af4c2b)

In the logs when I tested a week ago I had this : 

![image](https://github.com/henrypp/simplewall/assets/13313380/5b2713c3-f3af-4105-a715-b16258aa346d)

Looks like a right issue to me, since games in gamepass are locked down (well, the executable files at least)
But it works with the standard windows firewall.

**Comment by henrypp** [comment]
@1528
