### ISSUE TITLE
simple wall makes the PC's HOTSPOT not able to provide internet to other devices. 

### ISSUE THREAD

**Issue by I3ordo** [henrypp/simplewall#1540]
I am trying to share my wired internet connection as a "hotspot" but the devices connected to this computer's hotspot despite able to get ip adress, cant connect to internet unless i disable all filters (disable simplewall)

So, there are various apps that i still  needblocked, so how can i keep using simplewall while still able to use my pc as hotspot since something not visible is being blocked. by visible i mean, everything is enabled to to access the internet both as apps and services...
---

App version: <3.7.1>
Windows version: <windows 10 x64>

**Comment by henrypp** [comment]
#425
