### ISSUE TITLE
[Bug]Zugriff verweigert (0x00000005)

### ISSUE THREAD

**Issue by Toxcis** [henrypp/simplewall#1543]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.1

### Windows version

10

### Steps to reproduce

Open Simplewall
Filter Activasion
Pop Up Problem
Zugriff verweigert (0x00000005)

### Expected behavior

Activat the Filter

### Actual behavior

![2023-09-11 15_12_25-simplewall](https://github.com/henrypp/simplewall/assets/97459499/d38a08b7-b127-4573-93c1-3cdc13f8b42d)

**Comment by henrypp** [comment]
fucking hell, you cant read or what? #1486
