### ISSUE TITLE
"Load on system startup" doesn't work as expected with non privileged (not an admin) user.

### ISSUE THREAD

**Issue by shurushetr** [henrypp/simplewall#1545]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7

### Windows version

Microsoft Windows 11 Enterprise Version	10.0.22621 Build 22621

### Start conditions:
- Fresh legal original windows installation.
- Built in admin is disabled.
  - ![image](https://github.com/henrypp/simplewall/assets/765095/8f7ea3bf-0bfb-4ef5-87f7-6a1a16daf726)
- New **Admin** user created (during windows installation process).
  -  **Admin** user is verified to be a member of "Administrators" group.
- New  **Regular** user created.
  - **Regular** user is verified to **NOT** be a member of "Administrators" group.
-  **Regular** user is used to login and operate the workstation. Running admin commands with elevated privileges through UAC requests.
- **Regular** user installs SimpleWall to **%programfiles%**, elevated privileges **granted** for installation.
- **Regular** user starts SimpleWall application, UAC requests elevated privileges - **Granted**.
- **Regular** user goes into File => Settings => General.
  - Enables following options:
    - "Load on system startup"
    - "Skip UAC prompt warning"
    -  ![image](https://github.com/henrypp/simplewall/assets/765095/e0cf3e55-d886-45f0-82f3-568e3f5a6984)
   - Settings closed.
 - **Regular** user proceeds to restart the workstation to verify the enabled options are working as desired.

### Expected behavior

- Immediately after system is back from the restart, **Regular** user logs in
- SimpleWall expected to autostart, with interface available to regular user.
- Notifications originated from SimpleWall available for **Regular** user to interact with.

### Actual behavior

SimpleWall doesn't start.

### Logs

Further investigation shows the following:
- Simple wall creates a task with Task Scheduler - Exported - [simplewallTask.xml.txt](https://github.com/henrypp/simplewall/files/12608684/simplewallTask.xml.txt)
  - The task has no triggers, and never picked up for executing:
    - ![image](https://github.com/henrypp/simplewall/assets/765095/26620dc0-6eca-4480-8fef-b461cfe11b64)
  - The task supposed to be executed with **Admin** user, only when **Admin** is logged on. As per task settings. 
- After adding a trigger "At log on of any user" - Exported updated task - [simplewallTask.xml.txt](https://github.com/henrypp/simplewall/files/12608781/simplewallTask.xml.txt)
  - ![image](https://github.com/henrypp/simplewall/assets/765095/40af3ebb-e5f9-4830-b526-41da0b7c506b)
- And changing the Run option to "Run weather user is logged on or not" - the task was saved.
- Workstation rebooted, **Regular** user logged in.
   - The simplewall.exe process appeared in the Task Manager as result of task execution.
   - No tray icon or other UI is available to **Regular** user for interaction.
   - **Notification** sound generated by simplewall informs **Regular** user about simplewall attempts to show a notification window to current user.
   - No actual notifications displayed.

There is no way for a **Regular** user to interact with application at this point.

**Comment by henrypp** [comment]
where u read it is app for regular user?
