### ISSUE TITLE
[Feature] Portability of XML w/Multiple PCs

### ISSUE THREAD

**Issue by Rgamer84** [henrypp/simplewall#1546]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.7.1

### Problem you are trying to solve

It would be nice if Simplewall supported different configurations for multiple PCs automatically if using a portable INI.  In some cases, I might want to have something like Adobe talk out to the internet on one computer but not another when I'm running the application.  I recognize that I can select Import/profilename.xml each time and just load each one every time.

Obviously, this is just a nice to have.  Feel free to close if I'm just being too lazy by having to do two extra clicks. :)

### Suggested solution

If using portable mode, have simplewall request the hostname when opening and automatically load the proper .xml for the computer being used if specified.

**Comment by henrypp** [comment]
ok
