### ISSUE TITLE
Launch of several copies of the application

### ISSUE THREAD

**Issue by flarens** [henrypp/simplewall#1547]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.6.7 -> 3.7.1

### Problem you are trying to solve

I use the Aster program so that several people can work on one physical computer simultaneously. The fact is that starting with the Simplewall 3.7 version, the application no longer launches a second copy. Prior to this, the application, although not in the mode conceived by the developer, but worked properly. I launched a separate independent portable folder with a firewall from both users. And when the Internet is requested, a notification appears with both users. Blocking occurs only if both users simultaneously ban this connection.

### Suggested solution

Can you remove it back is this harmful restriction that limits the launch of several copies of the program? An ideal option would be to modify the application to support the multiplayer environment. In order for the notification to appear only with the user, on whose name the Internet program is launched, and in the case of the system program you can leave a notification for everyone. But something tells me that you will not take up such a specific individual task, so I ask you to at least allow copies of the program to work. Thank you!

**Comment by henrypp** [comment]
there is no logic at all with launch 2 copies of app

**Comment by flarens** [comment]
The logic is that each user launches his applications and there should be a choice to let these applications on the Internet or not.
If you run the firewall only on the account of the main user, when the second user will open, for example, a browser, then only the first user will have a notification of the resolution of network activity of the browser.
He does not know what kind of application was launched by his neighbor and this should not touch him.
Therefore, we launch our copy of the application for each user so that everyone gets notifications.
But it is better to receive only your notifications, not being distracted by strangers.
Two different folders with portable firewalls are needed so that when turning off the computer, do not conflict saving filtering rules.

**Comment by henrypp** [comment]
okay, i see, and i found where is bug, and wait for next release
