### ISSUE TITLE
[Feature] Command line to add rules to specific .exe

### ISSUE THREAD

**Issue by dougg0k** [henrypp/simplewall#1548]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

Latest

### Problem you are trying to solve

I am trying to build a geofence solution that usually involves blocking many IPs and IP Ranges, but that is hard with simplewall since it's all on the UI.

### Suggested solution

If there were a way to set via command line, that could be automated and viable. Ideally a way to add and get rules. Since knowing what is already there would help prevent duplications, unless there were a way to not allow duplicated values.

**Comment by dougg0k** [comment]
If you didnt do this or didnt want before due to security reasons, you could do something like the Secure Profile from WFC, having it enabled by default.

![2023-10-12_19-54](https://github.com/henrypp/simplewall/assets/10801221/31c7ccfd-91bf-449e-a245-fb0efebb2916)

**Comment by henrypp** [comment]
#1406

**Comment by dougg0k** [comment]
> #1406

Enable or disable are completely different from what was requested, but no problem. WFC works.
