### ISSUE TITLE
Version 3.7.1 is crashing on Windows 10

### ISSUE THREAD

**Issue by g-k-m** [henrypp/simplewall#1549]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.1

### Windows version

Windows 10 22H2 Build 19045.3448

### Steps to reproduce

Start pc

### Actual behavior

Simplewall crashed on boot with error 0x000000000, not sure exactly how many zeroes there were but there were ONLY zeroes in the error code, no other symbols. I also saw another issue of simplewall crashing, but that issue was for Windows 11 so i thought to make a new issue for Windows 10 since the OSes are different. There's also a 3-5 second lag when starting simplewall, assuming it doesn't crash. This lag was not here prior to version 3.7 (or 3.7.1?)

### Logs

[simplewall-1695224916.zip](https://github.com/henrypp/simplewall/files/12675205/simplewall-1695224916.zip)

Uploading relevant lines of the error log as well, lots of error lines

[simplewall_debug.zip](https://github.com/henrypp/simplewall/files/12675223/simplewall_debug.zip)

**Comment by henrypp** [comment]
> I have used the search function to see if someone else has already submitted the same bug report.

aga,believe ##1486
