### ISSUE TITLE
[Bug] Several anti-virus programs identified simplewall-3.7.2-setup.exe as malicious.

### ISSUE THREAD

**Issue by dg0072** [henrypp/simplewall#1550]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.2

### Windows version

Windows 11 Pro Version	22H2

### Steps to reproduce

Edition	Windows 11 Pro
Version	22H2
Installed on	‎09-‎09-‎2023
OS build	22621.2283
Experience	Windows Feature Experience Pack 1000.22662.1000.0

With [Smart App Control](https://support.microsoft.com/en-gb/topic/what-is-smart-app-control-285ea03d-fa88-4d56-882e-6698afdb7003) set to On. 

[VirusTotal](https://www.virustotal.com/gui/file/bae715db54ac2bdf3947d79a12e1343ee82decf878a347cae03380f62413601a)

![Setup](https://github.com/henrypp/simplewall/assets/130278192/9fb360b9-1656-4bcb-b51b-3f8783d42356)
![Updater](https://github.com/henrypp/simplewall/assets/130278192/adf6ac90-c445-43f4-bd12-a2a42bc8b909)

### Actual behavior

Not able to Install/Update 3.7.2 build.

**Comment by henrypp** [comment]
you have wonderful decision to compile source by yourself, and you see that compiled binary have SAME hashes (because of /brepro option) and you see new shit was detected too, so dont waste my time
