### ISSUE TITLE
Windows defender Trojan:Script/Phonzy.B!ml

### ISSUE THREAD

**Issue by esaasae** [henrypp/simplewall#1552]
Windows defender Trojan:Script/Phonzy.B!ml

https://www.virustotal.com/gui/file/bae715db54ac2bdf3947d79a12e1343ee82decf878a347cae03380f62413601a/detection

---

App version: 3.7.2
Windows version: 11

**Comment by nekronk** [comment]
![image](https://github.com/henrypp/simplewall/assets/18485600/34a0f5a2-7978-49f5-9355-ce723b6acf34)

Version 3.7.1
Windows 11
