### ISSUE TITLE
[Bug] Error when opening log viewer application

### ISSUE THREAD

**Issue by ltguillaume** [henrypp/simplewall#1555]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.2

### Windows version

10 x64

### Steps to reproduce

1. Specify any log viewer app in the settings
2. Click the icon to show the log
3. See the crash

### Expected behavior

The log viewer app should open.

### Actual behavior

![image](https://github.com/henrypp/simplewall/assets/4777345/0c6d36f3-03c6-4d81-88ec-318e5f7fec65)

### Logs

There is no mention of this crash in `simplewall_debug.log`

**Comment by henrypp** [comment]
i so have csvfileview (to watch csv file format), but latest (2.6.4), and do not have this problem at all.

**Comment by henrypp** [comment]
what verion do you have?

**Comment by ltguillaume** [comment]
Doesn't matter which log viewer I use. Just setting notepad.exe results in the same error.

**Comment by henrypp** [comment]
what windows ver?

**Comment by ltguillaume** [comment]
That's in the first post: Win10 x64

**Comment by henrypp** [comment]
new version fixed
