### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by VidarrKerr** [henrypp/simplewall#1556]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.1

### Windows version

win10

### Steps to reproduce

On startup I get an error: "update server connection error status 12007".

This started after the latest update. 

### Actual behavior

Spits out this error. I restart the app, or reboot. 

### Logs

Can't find the dump file.

**Comment by henrypp** [comment]
u have no inet
