### ISSUE TITLE
Path not found error [Bug]

### ISSUE THREAD

**Issue by dm413** [henrypp/simplewall#1557]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.2

### Windows version

Windows 11 pro x64

### Steps to reproduce

1. Install simplewall version 3.7.2 on a new Windows 11 Pro x64 computer.
2. Run simplewall

### Expected behavior

No error message

### Actual behavior

I get an error:

Could not load profile
(Path not found)
The path %hs does not exist
Status 0xC000003A

I close that error message and continue, and simple wall behaves as normal. I can enable filters, adjust settings, etc. However, after reboot I get the same error and all my settings are gone.

I tried to export my settings, and got the same message, but this time it included a path below the error message (not replacing the %hs, but below the entire text of the error message). The path shown is C:\Users\<username>\Documents\Profile.xml. That directory exists. The file, of course, does not as simplewall was supposed to create it.

I uninstalled and installed version 3.7.1. This version works without errors. I went back to 3.7.2 and it failed again, same error. Back to 3.7.1 and it works. 

I have a win10 pro x64 computer where I have been using simplewall for years, and I installed 3.7.2 there, and do not see this error.

**Comment by henrypp** [comment]
fix [simplewall.zip](https://github.com/henrypp/simplewall/files/12738079/simplewall.zip)

**Comment by KiaArmani** [comment]
The provided executable (assuming what needs to be done is to replace the existing one with the attached one) does _not_ resolve the issue on a Win11 22H2 machine.

**Comment by SDeLaVida** [comment]
currently the only fix for me (win10 installed with chocolatey) is to downgrade to 7.1

**Comment by l-t-m-f** [comment]
the new executable on oct 7 is working for me.
but auto update fails to connect to server.

**Comment by dm413** [comment]
I am the OP. Version 3.7.3 released 2023-Oct-12 fixed this problem for me.

Thanks, @henrypp!

**Comment by 81albert** [comment]
Hi @henrypp I downloaded and installed version 3.7.2 and from first launch I got the path not found message, the app was working fine, thing is I can´t export the profile and every time I start the computer SW starts all over again, the apps list as default, here is a picture of the error
![SW](https://github.com/henrypp/simplewall/assets/148296715/dd5143a0-5fda-4586-940d-d5516ea7e360)
Today I downloaded and installed the latest version (3.7.3) and still got the same error. 
I have KAV installed, tryed closing it, and still the same, I have Windows 10 22H2. Any ideas on this error?
Thanks for the good work

**Comment by HenryLe88** [comment]
@81albert  I got the same problem with you. @henrypp please fix this bug on Windows 10 22H2.

**Comment by 81albert** [comment]
> @81albert I got the same problem with you. @henrypp please fix this bug on Windows 10 22H2.

Hi, the current solution is the one posted by @Ud4ba First install version 3.7 (it doesn´t have that issue) and then upgrade with the 3.7.3 I did it this way and it worked, I hope it does for you too
