### ISSUE TITLE
[Bug] On system start up and on refresh button click, all unused under "apps without internet access" section getting cleared

### ISSUE THREAD

**Issue by reddyshyam** [henrypp/simplewall#1558]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.2

### Windows version

Windows 11 23H1 64bit Pro

### Steps to reproduce

On system start up, clicking on simplewall tray icon, opens in full screen mode clearning all unused apps (even though I want them which are under apps without internet access)

### Expected behavior

Clicking on simplewall tray icon, should just open in normal window

### Actual behavior

On system start up, clicking on simplewall tray icon, opens in full screen mode clearning all unused apps (even though I want them which are under apps without internet access)

**Comment by reddyshyam** [comment]
> You don't even have to restart windows. Just clicking on the refresh button in simplewall seems to reset the list of applications without internet access (the ones that aren't silent). Not sure if it's done intentionally. @henrypp could you confirm?

Thanks @mojo-jojo-7 for confirming. If it is intentionally then I would need it to be an option under settings for the user to decide. I use the list of applications without internet access a lot, to enable when required.

**Comment by reddyshyam** [comment]
Hi @henrypp, sorry to bother but how do I disable Auto purge? I want to do it manually. I looked everywhere and didnot see this option. Can you guide me please?

**Comment by Chefloq** [comment]
> Hi @henrypp, sorry to bother but how do I disable Auto purge? I want to do it manually. I looked everywhere and didnot see this option. Can you guide me please?
> 
> Found the option. Thanks again! 🙏👍👌👏

Hello friend! Where is the option to disable autopurge? I can't see it in 3.7.8. I have been having this problem for days

**Comment by reddyshyam** [comment]
> > Hi @henrypp, sorry to bother but how do I disable Auto purge? I want to do it manually. I looked everywhere and didnot see this option. Can you guide me please?
> > Found the option. Thanks again! 🙏👍👌👏
> 
> Hello @reddyshyam ! Where is the option to disable autopurge? I can't see it in 3.7.8. I have been having this problem for days

Hi @Chefloq,

Right click on any item on the list, proceed as highlighted below . Hope this helps.

![image](https://github.com/henrypp/simplewall/assets/12392746/4c1a4da1-c71f-421f-b263-b4790a3b0813)

**Comment by Chefloq** [comment]
Thank you very much @reddyshyam , I thought there was a general option for all rules, not an individualized one, but it works!
