### ISSUE TITLE
[Question] version 3.7.2 defined as a virus

### ISSUE THREAD

**Issue by debobrov** [henrypp/simplewall#1560]
Version 3.7.2 defined as a virus. I'm attaching the link
https://www.virustotal.com/gui/file/bae715db54ac2bdf3947d79a12e1343ee82decf878a347cae03380f62413601a
---
Are you going to do something about the file signature or is the problem somewhere else?

**Comment by debobrov** [comment]
Anyone who cares about security will not install a program with such a report (it is especially important that the Microsoft antivirus responded there), but will wait for a version without so many detections.

Instead of a detailed answer, for some reason you threw a bone to the dog - “false positive”. I could reassure myself with such an answer, but you are a developer.
This means that we will have to switch to FortFirewall for now - it does not have such a problem yet.

**Comment by henrypp** [comment]
lol, yet
