### ISSUE TITLE
[Bug] 3.7.2 Update Error - Windows Firewall - Trojan

### ISSUE THREAD

**Issue by maxwood** [henrypp/simplewall#1561]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.1

### Windows version

11

### Steps to reproduce

Update available - do you want to install it now?

OK

Error message

### Actual behavior

Operation did not complete successfully because the file contains a virus or potentially unwanted software. (0x000000E1)

C:\Users\Max\AppData\Roaming\Henry++\simplewall\cache\update-simplewall-lzgxqow.exe

![image](https://github.com/henrypp/simplewall/assets/2072219/05c6aea8-9a52-4446-83f6-3ee3f6e6b738)

![image](https://github.com/henrypp/simplewall/assets/2072219/67b85077-d891-4d96-835a-978080bc008c)

**Comment by maxwood** [comment]
No comments @henrypp? Never had this issue before with simplewall.

**Comment by henrypp** [comment]
@Donniewr

> I didn't download anything

aga,i believe
