### ISSUE TITLE
[Bug] simplewall-3.7.2-setup.exe detected as PWS:Win32/Zbot!ml (False Positive)

### ISSUE THREAD

**Issue by miukumac** [henrypp/simplewall#1562]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.2

### Windows version

Windows 10

### Steps to reproduce

Download .exe from GitHub.

### Actual behavior

Windows Defender not being a pile of garbage when trying to install said executable :-)

### Logs

Just wanted to note that as of 23.09.2023 the .exe version on GitHub is marked as Malware by Windows Defender. 

Reported it as False Positive via their tools but my guess is they care about as much as they do with people complaining about Windows 11 being a pile of garbage so I doubt they'll do anything about it anytime soon.

You can still get around it by downloading the .zip and running the .exe with --install.

**Comment by henrypp** [comment]
you complete blind???

**Comment by miukumac** [comment]
It was meant to be a note for people who wanted to know if they can still install it despite being reported as a false positive.
