### ISSUE TITLE
[Bug] Microsoft Defender quarantining autoinstaller and installer from website

### ISSUE THREAD

**Issue by treydun** [henrypp/simplewall#1563]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.2

### Windows version

Windows 10

### Steps to reproduce

On startup, receive notice about update from 3.7.1 to 3.7.2
Click install
When downloaded click OK
Microsoft Defender Quarantines

Go to henrypp.org/product/simplewall
Click [simplewall-3.7.2-setup.exe](https://github.com/henrypp/simplewall/releases/download/v.3.7.2/simplewall-3.7.2-setup.exe)
When finished downloading
Microsoft Defender Quarantines

The portable package does not have the same issue.
Scans fine with Defender

### Actual behavior

Application is prevented from installing
![Autoupdate](https://github.com/henrypp/simplewall/assets/4534509/dc9b5d99-b7a4-4737-a3dc-559b6c91ca03)

![Installer from site](https://github.com/henrypp/simplewall/assets/4534509/ffe845ba-648b-4fc2-89ee-3f02633eb979)

### Logs

Microsoft Defender Antivirus has detected malware or other potentially unwanted software.
 For more information please see the following:
https://go.microsoft.com/fwlink/?linkid=37020&name=Trojan:Script/Phonzy.B!ml&threatid=2147772967&enterprise=0
 	Name: Trojan:Script/Phonzy.B!ml
 	Severity: Severe
 	Category: Trojan
 	Path: file:_C:\Program Files\simplewall\cache\update-simplewall-tefpuvv.exe
 	Detection Origin: Local machine
 	Detection Type: FastPath
 	Detection Source: Real-Time Protection
 	User: MyPC\Trey
 	Process Name: C:\Program Files\simplewall\simplewall.exe
 	Security intelligence Version: AV: 1.397.1450.0, AS: 1.397.1450.0, NIS: 1.397.1450.0
 	Engine Version: AM: 1.1.23080.2005, NIS: 1.1.23080.2005

**Comment by henrypp** [comment]
u blind or what?

**Comment by treydun** [comment]
I am very sorry Henry.

I really appreciate your software. It is excellent.

I now realize when I click search on bug reports it automatically adds the
"is open" filter to my search box. So searching does not show the 15
reports filed before me. I did look.

I understand why you are frustrated with the situation.

Perhaps leaving just one "false positive" report open in your github
"issues" would help with the wasting your time. You could open one yourself
just letting people know the current situation.

Thank you for your time and effort. Again, best firewall program of all
time.
