### ISSUE TITLE
Auto update fails to install 3.7.2 , trough program and Winget[Bug]

### ISSUE THREAD

**Issue by jonnaya** [henrypp/simplewall#1565]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.1

### Windows version

win 10 home latest

### Steps to reproduce

1 update notification 3.7.2
2 Downloading (succeed)
3 install: Fails.

Winget scenario:
(1/1) Found simplewall [Henry++.simplewall] Version 3.7.2
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 2

### Expected behavior

Updating

### Actual behavior

Downloading but not installing.

**Comment by fredgolightly** [comment]
Similarly, updating through the app itself I get:

`Operation did not complete successfully because the file contains a virus or potentially unwanted software. (0x000000E1)

C:\Users\User\AppData\Roaming\Henry++\simplewall\cache\update-simplewall-hxzezyh.exe`

Downloading the setup file and running says it's potentially a virus or an unwanted program

Windows 10 Pro 19045.3448

On a side note, I've never found the update 'install' button to respond, the panel locks, but it's not a new issue

**Comment by henrypp** [comment]
you can download as a zip and unpack, it happens because of idiotic av

**Comment by mudaio** [comment]
> you can download as a zip and unpack, it happens because of idiotic av

I have the same issue with no av and windows defender turned off. It asks if I want to install new version an then nothing happens.

**Comment by henrypp** [comment]
@mudaio disable your fucking defender

**Comment by henrypp** [comment]
@mudaio NOTHING ELSE WILL MARKED THIS BINARY

**Comment by mudaio** [comment]
Lol what?

**Comment by skupjoe** [comment]
The same issue is happening to me and I installed directly (not through Winget or whatever). It downloads but the installation does not happen. IIRC this worked in previous versions, but not 3.7.1 -> 3.7.2

Windows Defender was not triggered so I don't think that is it, and I don't have any additional security/AV software installed.

Also not seeing anything logged in my System, Application, Setup, or Security logs. I am on Window 10 Pro 22H2 19045.3448.

**Comment by keerah** [comment]
Yes. Windows defender reports: Trojan:Win32/Wacatac.B!ml in this update

**Comment by KolodyazhnyyI** [comment]
while updating in win 10 to 3.7.2 get windefender caution
file: C:\Users\User\AppData\Roaming\Henry++\simplewall\cache\update-simplewall-vbdcozr.exe
PWS:Win32/Zbot!ml

Win Def didnt have any problems with the previous versions of SimpleWall, im guessing someone contributed malicious code to it please revise

**Comment by fredgolightly** [comment]
3.7.3 is being flagged by multiple vendors, incorrectly or not: https://www.virustotal.com/gui/file/a1982fe0a893d90db36d7b0690dea294b33155fed5ff9371f3fd9eafc82092e3

`BitDefenderTheta
Gen:NN.ZexaF.36738.Ou0@au7r6gpi
Bkav Pro
W32.AIDetectMalware
Cynet
Malicious (score: 100)
SecureAge
Malicious
Trapmine
Suspicious.low.ml.score`

**Comment by jacob-44** [comment]
<img width="445" alt="image" src="https://github.com/henrypp/simplewall/assets/56795574/268c4823-aa5a-4127-b7df-2bd2c2f1b4e4">

**Comment by 78tacos** [comment]
I believe the updater is in silent mode so it doesn't notify you that it cannot write because Simplewall is still running. When updating manually the installer tells you that it cannot write. I don't have access to the nsis files so i can't confirm this.
![simple update](https://github.com/henrypp/simplewall/assets/28722167/1089b71a-9e67-46a3-9c18-d21dc171c074)

**Comment by phonosys** [comment]
auto update from the program itself also fails with no error.
happens on all 3 last versions for me , currently happens on 3.7.4.

workaround is just to manual re-install

**Comment by RH-BD** [comment]
What happened? is this issue abandoned? This issue is keep happening from last few months..

**Comment by henrypp** [comment]
@RH-BD it already fixed, and release ine near future

**Comment by RH-BD** [comment]
In which version it will be fixed? I just manually installed 3.7.5

**Comment by henrypp** [comment]
@RH-BD in next, it because of invalid mutex name of sw it cannot close current running sw

**Comment by zMohawk** [comment]
Atm I can't still get the program to autoupdate it as it says there is a new update I download it, and it doesn't work, once downloaded, installed it stays version 3.7.3

**Comment by henrypp** [comment]
@zMohawk u complete have not hands?

**Comment by zMohawk** [comment]
I do, it's just would be grateful and as me others if you could explai how to proceed to 3.7.5 without issues.
Or maybe 3.7.3 is still safe. Strangely also windows (KB5032189) security update of Nov 14th doesn't get delivered (100%.. but no install) I don't know if it's simple wall getting in the way.

**Comment by henrypp** [comment]
fxd

**Comment by reddyshyam** [comment]
Still doesnot work. v3.7.5 currently. Downloaded setup and manually installed.

**Comment by zMohawk** [comment]
> I installed manually to 3.7.6 but it is not in the system tray. It is disappearing/disappeared!! I'm a non-techy; so don't even know whether or not it is working or not?!?

Hi, you don't need to see it in the system tray for it to be running. Anyway some settings allow to set what the program does once minimized or once the system starts etc. Maybe some of those settings do interfere with the presence of the icon in the tray section of windows bar.
You can still have it in the task bar. And click it open from there.
