### ISSUE TITLE
[Bug] backgroundTaskHost.exe - System Error

### ISSUE THREAD

**Issue by SPDurkee** [henrypp/simplewall#1567]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.2

### Windows version

Windows 10 Pro Version	22H2 build 19045.3448

### Steps to reproduce

1. Install sinplewall
2. Activate filters

### Actual behavior

Almost all applications will cause the following error when opening and running:
![image](https://github.com/henrypp/simplewall/assets/2486134/785243cb-498f-478c-93f3-6c95a937f5e9)

Once I figure out the filter rule set required to allow internet access for a particular application, the error will no longer be displayed when opening/using THAT application.

Viewing the packet log confirms the error message is directly tied to connection attempts.

I am surprised to see no-one has run across this issue, I hope it can be replicated somehow. This is happening so often, it is almost unusable.

I recently turned off windows firewall and installed simplewall after looking for a true firewall with packet level control. I am really enjoying this software so far but need this fixed so I can use the software log term.

**Comment by henrypp** [comment]
filters cannot provide this error
