### ISSUE TITLE
{Path Not Found} The path %hs does not exist.  Status: 0xC000003A

### ISSUE THREAD

**Issue by Ud4ba** [henrypp/simplewall#1569]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.2

### Windows version

10 Latest update

### Steps to reproduce

When PC launches and Simple wall starts im getting this error and all settings of the app are lost.

### Actual behavior

Start normally and keep the settings.

**Comment by etty80** [comment]
The same error, bug on Windows 11, rules are not saved after restart of program.

**Comment by lwpwfw** [comment]
Yes, I agree, I have the same problem on Windows 10. Only switching to version 3.7.1 helped and the error disappeared.

**Comment by etty80** [comment]
I tried to switch to portable mode in installer and its working now. So this looks like a solution.

Reinstalling without portable checkbox reproduces error.

**Comment by henrypp** [comment]
dup #1557
