### ISSUE TITLE
[Bug] error

### ISSUE THREAD

**Issue by Lobadii** [henrypp/simplewall#1570]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

simplewall

### Windows version

Windows 10 (64 bit)

### Steps to reproduce

![simplewall](https://github.com/henrypp/simplewall/assets/146268343/1ace38c1-0f71-48f7-9ab5-2202988f07af)

### Actual behavior

![simplewall](https://github.com/henrypp/simplewall/assets/146268343/d8df5b2d-f701-4922-8f51-aab3ca351a10)

**Comment by henrypp** [comment]
##1557
