### ISSUE TITLE
Updating on Windows 8.1 from 3.7.1 to 3.7.2

### ISSUE THREAD

**Issue by fimmspin** [henrypp/simplewall#1571]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.1

### Windows version

Win 8.1

### Steps to reproduce

I try to update, it downloads it but it doesn't do anything and version remains at 3.7.1.
I see Win8 will no more be supported since 3.7.2: any warning or message to alert about this when updating manually and avoiding re-download?
Please check and if possible release another Win8 update, it would be good to at least update rules and blocklist also on older Win8 systems in future.

### Expected behavior

update or warning

### Actual behavior

no feedback to user about 'end of life'.

**Comment by fimmspin** [comment]
For Win 8.1 users coming from older versions (and not updating for long time) it could be nice to update to 3.7.1 instead of 3.7.2 as it is the latest possible version to install. Also check this.

**Comment by henrypp** [comment]
it already haved,just search
