### ISSUE TITLE
[Bug] VCRUNTIME140_1.dll not found

### ISSUE THREAD

**Issue by MCSE-2000** [henrypp/simplewall#1572]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.2

### Windows version

Windows 10 x64 22H2

### Steps to reproduce

With the new Version 3.7.2 i get an error "VCRUNTIME140_1.dll" not found.
The previous version 3.7.1 worked fine.
I use the portable (ZIP) Version.

### Actual behavior

-

**Comment by henrypp** [comment]
install c redistributeble
