### ISSUE TITLE
installer for simplewall-3.7.2-setup.exe[Bug]

### ISSUE THREAD

**Issue by 10011968** [henrypp/simplewall#1574]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.2

### Windows version

11

### Steps to reproduce

double click on installer
check "i agree"
next
failed to install

### Expected behavior

install simplewall-3.7.2 update

### Actual behavior

failed to install

### Logs

![image](https://github.com/henrypp/simplewall/assets/111970244/cbe1d3a7-b529-4f4e-99ca-828b018396b6)
![image](https://github.com/henrypp/simplewall/assets/111970244/15511ce5-2da3-42d6-9fe9-523cf7c870c8)

**Comment by henrypp** [comment]
you idiot or what???

**Comment by 10011968** [comment]
Sometimes I wonderSent from my iPhoneOn 29 Sep 2023, at 16:52, henrypp ***@***.***> wrote:﻿
you idiot or what???

**Comment by henrypp** [comment]
its not about wondering, its about LOGIC, you let me see error image that installer CANNOT REPLACE FILE BECAUSE IT IS IN USE... it is not fucking logically???????

**Comment by 10011968** [comment]
It was not stating that Sent from my iPhoneOn 29 Sep 2023, at 17:24, henrypp ***@***.***> wrote:﻿
its not about wondering, its about LOGIC, you let me see error image that installer CANNOT REPLACE FILE BECAUSE IT IS IN USE... it is not fucking logically???????
