### ISSUE TITLE
‎ 

### ISSUE THREAD

**Issue by jgp0** [henrypp/simplewall#1576]

**Comment by henrypp** [comment]
and others apps give notification window? and where is debug log??

**Comment by jgp0** [comment]
Yes, the other applications do give notification. Also, I have tried to install previous versions of SimpleWall but it doesn't work either, it will be a new hidden update of Discord that causes incompatibility, because this has never happened to me, until now it had been perfect

**Comment by henrypp** [comment]
@jgp0 what is "hidden update"? are you stupid or what? in fs do not anyane hava been "hidden".
