### ISSUE TITLE
[Bug] {Path Not Found} 

### ISSUE THREAD

**Issue by ven-ox** [henrypp/simplewall#1578]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.2

### Windows version

10 x64

### Steps to reproduce

Every time the application starts there is a problem in loading / saving the config.

"File menu > Export > Save" gives the same error.

![bandicam 2023-10-02 17-25-20-590](https://github.com/henrypp/simplewall/assets/37386673/67f5145e-2468-42d1-8ce3-586b3fb18c16)

### Expected behavior

Save and load all the rules and settings.

### Actual behavior

Save the settings and re-apply them at startup.

### Logs

```
{Path Not Found}
The path %hs does not exist.

Status: 0xC000003A

C:\Users\Administrator\Documents\profile.xml
```

_No response_

**Comment by henrypp** [comment]
@1557

**Comment by henrypp** [comment]
fucking github mobile convert @ items to usernames, but not a issues...

so, answer is here: #@1557
