### ISSUE TITLE
What might cause the allow/disallow notifications to not appear?

### ISSUE THREAD

**Issue by mindflvx** [henrypp/simplewall#1579]
I'm not sure when the issue appeared but I just realized today that I haven't seen the Simplewall notifications about allowing or disallowing network access for some time, and after testing it I confirmed that they are not being displayed when the application is unknown and no filters are defined. 

Anyone have any ideas what might cause the issue?

---

App version: 3.7.2
Windows version: Windows 11 Pro 10.0.22621 Build 22612

**Comment by henrypp** [comment]
telepaths are in vacation, as always
