### ISSUE TITLE
Suggestions for Blocklist

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#158]
1. Create 3 separate groups for spy, update and extra, with a check mark in from of the group name, so that an entire group can be checked/unchecked.
2. Automatically update blocklist and, if such a group is enabled, automatically block new entries within that group. If only some items of that group are selected, I think it would be best to still enable new entries by default. If the group is completely unchecked, only add new entries, but don't enable them.

On a sidenote, there's been a new release 2 days ago, but simplewall hasn't updated yet. Perhaps it would be better to not maintain the blocklist yourself, but directly parse the files from https://github.com/crazy-max/WindowsSpyBlocker/tree/master/data/simplewall?

**Comment by ltGuillaume** [comment]
@henrypp #2 is implemented, fantastic! :)

**Comment by henrypp** [comment]
Other stuff is hard to implement
