### ISSUE TITLE
[Bug] the instruction at 0x%p referenced memory at 0x%p. the memory could not be %s. (0xc0000005)

### ISSUE THREAD

**Issue by majorwinnar** [henrypp/simplewall#1580]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.2

### Windows version

Windows 11

### Steps to reproduce

Do not know why Simplewall randomly crashes with error: "the instruction at 0x%p referenced memory at 0x%p. the memory could not be %s. (0xc0000005)"

### Actual behavior

Error: the instruction at 0x%p referenced memory at 0x%p. the memory could not be %s. (0xc0000005)

### Logs

[simplewall-1696390991.zip](https://github.com/henrypp/simplewall/files/12799044/simplewall-1696390991.zip)

**Comment by henrypp** [comment]
fucking hell, do you can update to the latest 3.7.2????

**Comment by henrypp** [comment]
@Rubber-Duckie #1686
