### ISSUE TITLE
[Bug] Random crash

### ISSUE THREAD

**Issue by dougg0k** [henrypp/simplewall#1582]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.2

### Windows version

11 22H2

### Steps to reproduce

It happens randomly, no way to reproduce. When I press Close, it completely closes simplewall and I have to open it manually.

It happened multiple times before, but only now I am reporting it. Same problem. But random. Some days it doesnt happen, some does. Without doing anything to it.

### Actual behavior

![simplewall](https://github.com/henrypp/simplewall/assets/10801221/34cdd666-0e2f-4c0e-b334-305f859a7d42)

**Comment by henrypp** [comment]
crash dump?

**Comment by dougg0k** [comment]
I didnt get, next time.

**Comment by dougg0k** [comment]
I will probably not get the crash dump, since I will stop using simplewall due to this https://github.com/henrypp/simplewall/issues/1584 

Feel free to close if you want.

**Comment by UNDEFINED-BEHAVIOR** [comment]
Same issue here after today's update
Would this be enough
![image](https://github.com/henrypp/simplewall/assets/8407331/da2ac3e7-fc3a-46b7-bd4f-21c5d1711cc7)

**Comment by henrypp** [comment]
@UNDEFINED-BEHAVIOR only dump can help

**Comment by davidhan3** [comment]
I got the same error, here's my crashdump that I pulled. 
[simplewall-1696791575.zip](https://github.com/henrypp/simplewall/files/12841483/simplewall-1696791575.zip)

**Comment by Zzyzzx** [comment]
I got an identical error message, here's my crashdump.

[simplewall-1696791575.zip](https://github.com/henrypp/simplewall/files/12841497/simplewall-1696791575.zip)

**Comment by henrypp** [comment]
@Zzyzzx are you dumb or what? i dont interest 3.7.0

**Comment by Rgamer84** [comment]
I've had the same issue on win11 22H2.  It's very random, and seems like its more frequent after my computer wakes back up.  Next time I see it if it's not posted already I'll grab the crash dump.

**Comment by orangelizard** [comment]
Same here on Windows 10 and 11. I'll grab a crash dump for each next time .

**Comment by henrypp** [comment]
@orangelizard but before posting crash dump, please upgrade your binary to the latest, yesterday i changed it

**Comment by dougg0k** [comment]
I removed simplewall due to other limitations, so I cannot get the dump anymore. And that I already created request issues for them, so, if anyone confirm this to be fixed, it can be closed.
