### ISSUE TITLE
Sound Notification

### ISSUE THREAD

**Issue by cyberpunkbln** [henrypp/simplewall#1583]
Hello,

is that right that simplewall triggers the "Notification about eMail"? Is the same as i use when i receive emails:(.

Is it possible to make this the normal "Notification" ? Or that i can choose the Sound Notification File?

thx

**Comment by henrypp** [comment]
what you fucking talking???

**Comment by cyberpunkbln** [comment]
i have mean: simplewall do a sound when the nofification appears and this sound are not the standard notification sound from windows. simplewall triggers the internal sound of the email notification. I have tested it with two soundfiles one for the standard notification sound and one for the email notofication sound. When the simplwall notification appears it triggers the email notofication sound from windows.

I have a robot sound "You have email" in my windows settings and everytime simplewall tells me that a app will have access the robot sound "You have email" played.

**Comment by henrypp** [comment]
9 month for answer,really?

> simplewall do a sound when the nofification appears and this sound are not the standard notification sound from windows.

lol, what? what sound do i use then?

**Comment by henrypp** [comment]
@tnodir i think MailBeep is better than others

**Comment by cyberpunkbln** [comment]
@tnodir yes exactly thats what i mean.
@henrypp what do you think of an option for the users? For me is Notification.Default better. Especially horny if you could also choose the sound (wav) and i can search for an wav like "Firewall needs Confirmation":). But the simple option between notification and mailbeep was cool enough. :)
