### ISSUE TITLE
[Bug] "Log subscribe failed." and "Exception raised :(" errors after installing v.3.7.2

### ISSUE THREAD

**Issue by rudolphos** [henrypp/simplewall#1585]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.2

### Windows version

Windows 10 19045.3516

### Steps to reproduce

1. Install simplewall
2. Open simplewall .exe
3. Click on _Enable filters_

### Actual behavior

I installed the latest version and there is an increase of CPU usage for a while and these are the errors I got upon starting simplewall and clicking on 'Enable filters':

```
[Main Instruction]
Log subscribe failed. Try again later.
[Content]
STATUS_WAIT_3
Status: 0x00000003
[Footer]
This information may provide clues as to what went wrong and how to fix it.
```

```
[Main Instruction]
Exception raised :(
[Content]
An invalid parameter was passed to a service or function.
Status: 0xC000000D
[Crash dumps] [Copy] [Close]
[Footer]
This information may provide clues as to what went wrong and how to fix it.
```
![simplewall](https://github.com/henrypp/simplewall/assets/4366810/11eee001-3a80-474e-9e0b-36e17fd368e0)

Simplewall also doesn't show any notifications and I can't use any browser because outbound and inbound connections seem to be blocked. So, I had to uninstall simplewall completely and use a different firewall.

**Comment by henrypp** [comment]
and of coursre not any crash dump

**Comment by henrypp** [comment]
and of course not any crash dump

**Comment by t0ma5** [comment]
I have had the same problem for months.. none of the recent updates fixed it

**Comment by Whasabi** [comment]
Greetings, the simplewall is giving me the same problem, when activating the filters it throws the error "Log subscribed failed..." I have tried to solve it by uninstalling and reinstalling and even with other versions but the error continues to persist. Any information on how to activate it would be very helpful.

**Comment by Rarlock** [comment]
**1. You need to write to the developer about simplewall problems (there are contacts in the program itself), apparently the simplewall update is to blame, I have been using the program with the latest updates for years without problems, but today the error log started flying out, the subscription failed, try again later. Status: 0x00000003, 2 things happened, deletion with registry cleaning. And installing a new one, rebooting and deleting the last added programs in the filter did not help. Only installing the old version of simplewall-3.6.1-setup helped. The case of imported filters with the new version does not cause an error now.

2. Надо писать  разработчику simplewall проблему(контакты в самой программе есть),  видимо виновато обновление simplewall, я пользовался  программой с последними обновлениями годами  без проблем, но сегодня начала вылетать ошибка log subscribe failed try again later Status: 0x00000003 причем 2 штуки, удаление с чисткой реестра и установка по новой, перезагрузка удаление последних добавленных в фильтр программ не помогли.  Помогло только установка старой версии simplewall-3.6.1-setup причем импортированные фильтры с новой версии сейчас не вызывают ошибку.

3. Debes escribir al desarrollador de simplewall sobre el problema (hay contactos en el programa en sí), aparentemente la culpa es de la actualización de simplewall, he estado usando el programa con las últimas actualizaciones durante años sin problemas, pero hoy aparece el error. la suscripción al registro falló, intente nuevamente más tarde Estado: 0x00000003 y 2 de ellos, la desinstalación limpiando el registro e instalando uno nuevo, reiniciando y eliminando los últimos programas agregados al filtro no ayudó. Solo ayudó la instalación de la versión anterior de simplewall-3.6.1-setup, y los filtros importados de la nueva versión ahora no causan ningún error.**

**Comment by t0ma5** [comment]
issue persists after all the recent updates that followed the first report
@henrypp please do not ignore the issue, I am attaching a crush dump file
[simplewall-1709030862.dmp](https://github.com/henrypp/simplewall/files/14823094/simplewall-1709030862.dmp)

**Comment by henrypp** [comment]
@t0ma5 its 3.7.7, dont be stupid

**Comment by henrypp** [comment]
@t0ma5 you send crash dump for old version and tell me to be more constructive? there is no logic at all!
