### ISSUE TITLE
[Feature] Include Visual C++ Runtimes with portable version

### ISSUE THREAD

**Issue by ltguillaume** [henrypp/simplewall#1587]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.7.2

### Problem you are trying to solve

Apparently, the new version requires the following runtimes:

msvcp140.dll
vcruntime140.dll
vcruntime140_1.dll

### Suggested solution

It would be great if these 3 runtime libraries were included with the portable packages, so that simplewall can always be run.

Note that currently, copying these 3 files next to `simplewall.exe` does __not__ solve the issue (they have to be installed or in %SystemRoot%\System32).

Also, if this is not the case already, to prevent issues the installer should request the installation of the runtime libraries.

**Comment by henrypp** [comment]
I think i made a bad decision to made msvcrt as required, so in next version it will be changed.
