### ISSUE TITLE
[Question] Filters duration

### ISSUE THREAD

**Issue by l-t-m-f** [henrypp/simplewall#1588]
Hi,

I remember using this app before and it was great. I could customize all my filters.

Fast forward to this month, I reinstalled the app, but now, I swear there is no way to keep filters forever.
They reset at PC startup and I have to click 50+ popups every morning for the firewall.

To the point where I am sure I am doing something incorrectly. Please advise me.

I am on Window 11 Pre-release.

Bests,

**Comment by henrypp** [comment]
i am win 11 user too, but i never meet this problem at all.

only solution:
see where is problem happened in debug log.

**Comment by henrypp** [comment]
any 3rd parties can prevent write to profile.xml or change wft access rights to bullshit

**Comment by l-t-m-f** [comment]
I will report back with more information!

**Comment by l-t-m-f** [comment]
@henrypp I've identified that this issue occurs if you **don't** choose to store the profile.xml in the installation diretory. I also had the path not found %hs error which was reported earlier this month and used you fix of 10/07. 

The "filter forgetting" issue seems to be deeply connected to the path not found error reported by another user.
