### ISSUE TITLE
[Bug] Syntax errors due to forward slashes

### ISSUE THREAD

**Issue by Matthaiks** [henrypp/simplewall#1589]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.3

### Windows version

10 22H2 x64

### Steps to reproduce

1. Upgrade from 3.7.2 to 3.7.3
2. Check the User rules

### Expected behavior

User rules that contain addresses with forward slashes should be working fine.

### Actual behavior

User rules that contain addresses like 192.168.0.0/16 are marked as invalid. New rules with forward slashes cannot be created (syntax error).

**Comment by henrypp** [comment]
fixed, try this [simplewall.zip](https://github.com/henrypp/simplewall/files/12873245/simplewall.zip)

**Comment by Matthaiks** [comment]
Yes, it's fixed.
