### ISSUE TITLE
[Bug] bright red rule

### ISSUE THREAD

**Issue by privacyguy123** [henrypp/simplewall#1590]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.3

### Windows version

10

### Steps to reproduce

What does this mean?

![image](https://github.com/henrypp/simplewall/assets/50337995/b60b0244-b7ce-49b7-b626-9769ea979a35)

### Expected behavior

Was never red before

### Actual behavior

Probably should be yellow like the others

**Comment by henrypp** [comment]
i completely did not have telepathy, may #1589 this help

**Comment by privacyguy123** [comment]
Sorry - would never have thought to search "syntax"
