### ISSUE TITLE
[Bug] CIDR blocks in user rules are suddenly invalid expressions

### ISSUE THREAD

**Issue by ltguillaume** [henrypp/simplewall#1591]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.3

### Windows version

10 x64

### Steps to reproduce

1. Have an allow rule using a CIDR block like
    ![image](https://github.com/henrypp/simplewall/assets/4777345/3845f708-a4b7-4435-a12f-e841130b2adc)
2. This worked nicely in 3.7.2, but after updating to 3.7.3:
    ![image](https://github.com/henrypp/simplewall/assets/4777345/4954efc4-6976-4807-b084-996f3728c66f)
3. Try to recreate the CIDR block:
    ![image](https://github.com/henrypp/simplewall/assets/4777345/ccd700c4-2092-44d7-bb75-f6d5347bae56)

### Expected behavior

The user rule allows the traffic.

### Actual behavior

The traffic is blocked. Seems like the exact opposite of #70.

**Comment by henrypp** [comment]
#1589
