### ISSUE TITLE
[Bug] [Breaking] Rule IP / Endpoint parsing fails. Might cause Firewall to not work at all!

### ISSUE THREAD

**Issue by Silberling** [henrypp/simplewall#1592]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.3

### Windows version

Windows 10 Pro for Workstations 22H2 19045.3570

### Steps to reproduce

I found this error when in log packages appeared where ALLOW rules were made for. My whole local network software does not work anymore with this simplewall version. When I checked my rules for errors I found this:

1. Go To User rules
2. Edit any rule
3. Go to Rule tab
4. Add remote with 192.168.0.0/24
5. ERROR: "Syntax error in rule!"

### Expected behavior

I expect previous rules to work
I expect example syntax to work
I kindly suggest adding unit tests to the code, even for such simple things, to avoid this in the future.

### Actual behavior

Firewall stops traffic
Rules not editable
False error messages

**Comment by Silberling** [comment]
Found this when updating to specified version. Just reverted back to 3.7.2 -> Everything fine again. Suggest to flag 3.7.3 and avoid installing.

**Comment by henrypp** [comment]
it is already fixed, redownload 3.7.3
