### ISSUE TITLE
[Bug] im idiot and cant enter right title

### ISSUE THREAD

**Issue by MCHALMEI** [henrypp/simplewall#1593]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.3

### Windows version

Windows 10 Home x64 Compilation 19042.3448 Windows Feature Experience Pack 1000.19044.1000.0

### Steps to reproduce

Right click on SW tray icon, click the "Enable/Disable filters" and user gets the error message in question. And then, as already told, it does not refresh the said list.

### Expected behavior

Thanks for your dev efforts. I really appreciate it. I intend to do a small donation in the near future.

Refreshing the app list on the "Apps" tab, which simplewall does not refresh at all, and that's since long past previous versions of the program. Not even under WinPE it's able to do this. Also, I keep getting the error message "STATUS_WAIT_3 Status: 0x000000003" whenever enabling or disabling the filters function.

### Actual behavior

<img width="265" alt="SP_erromessageshot" src="https://github.com/henrypp/simplewall/assets/62504905/b9f319af-f6de-48d0-bfb4-e74ff763984a">

It simply does not update the "Refresh" list of apps with or without access to the web.

### Logs

[simplewall_debug.log](https://github.com/henrypp/simplewall/files/12880856/simplewall_debug.log)

**Comment by NixonSchool** [comment]
And this one is a new one, i don't need to open a new issue:

**Comment by NixonSchool** [comment]
![image](https://github.com/henrypp/simplewall/assets/139177099/c14065cb-4195-4819-b7ad-024fef8f82e3)


I can't run simplewall at all on a new windows 10.

**Comment by NixonSchool** [comment]
[simplewall-1698942360.dmp](https://github.com/henrypp/simplewall/files/13243609/simplewall-1698942360.dmp)
[simplewall-1698945129.dmp](https://github.com/henrypp/simplewall/files/13243610/simplewall-1698945129.dmp)
[simplewall-1698951973.dmp](https://github.com/henrypp/simplewall/files/13243611/simplewall-1698951973.dmp)
[simplewall-1698925497.dmp](https://github.com/henrypp/simplewall/files/13243612/simplewall-1698925497.dmp)
[simplewall-1698926701.dmp](https://github.com/henrypp/simplewall/files/13243614/simplewall-1698926701.dmp)
[simplewall-1698936404.dmp](https://github.com/henrypp/simplewall/files/13243615/simplewall-1698936404.dmp)
[simplewall-1698939966.dmp](https://github.com/henrypp/simplewall/files/13243616/simplewall-1698939966.dmp)

**Comment by henrypp** [comment]
@NixonSchool it is very interesting to parse dump from 3.7.0 when 3.7.5 is available

**Comment by NixonSchool** [comment]
sorry for disturbing, my fault i never pressed the update button, i thought
i had updated and that the dumps were from 3.7.5

**Comment by henrypp** [comment]
@NixonSchool

![sshot-001](https://github.com/henrypp/simplewall/assets/3902025/69793801-04da-49c0-85ab-7f3c2d3ce297)

i believe, maybe

**Comment by NixonSchool** [comment]
You are right. 3.7.5 is going good. No issues. I also noticed that it was
crashing coz i was missing quality updates from windows.

**Comment by henrypp** [comment]
@NixonSchool you can get crash dump
