### ISSUE TITLE
[Bug] Could not save profile! on Windows Server Datacenter 2022

### ISSUE THREAD

**Issue by Bluscream** [henrypp/simplewall#1594]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.3 x64

### Windows version

10.0.20348.587

### Steps to reproduce

download
install
start
save

### Expected behavior

save

### Actual behavior

```
{Path Not Found}
The path %hs does not exist.

Status: 0xC000003A
```

### Logs

![](https://i.imgur.com/xp6K2kS.png)
<hr>

![](https://i.imgur.com/VUUCRRZ.png)

**Comment by Bluscream** [comment]
More bugs:

![](https://i.imgur.com/YBMB0LS.png)

**Comment by Bluscream** [comment]
> Same bug in here like the last bug it seems last versions have many issues; I will stick with older versions for now.

Which version do you use? For me last version that works is 3.7

**Comment by henrypp** [comment]
you have encrypted/compressed profile? if yes, change to plain

**Comment by Bluscream** [comment]
> you have encrypted/compressed profile? if yes, change to plain

tried that already, didn't fix it.

**Comment by henrypp** [comment]
`STATUS_INVALID_IMAGE_HASH 0xC0000428L` displayed only when hash is incorrect, but hash is checking only when profile type is compressed or encrypted, no other way

**Comment by Bluscream** [comment]
> `STATUS_INVALID_IMAGE_HASH 0xC0000428L` displayed only when hash is incorrect, but hash is checking only when profile type is compressed or encrypted, no other way

i have had compressed first but changed to plain after

**Comment by unc926** [comment]
> > `STATUS_INVALID_IMAGE_HASH 0xC0000428L` displayed only when hash is incorrect, but hash is checking only when profile type is compressed or encrypted, no other way
> 
> i have had compressed first but changed to plain after

I solved it this way:
Run installer as administaror
Select this option during installation: **Store settings in application directory ( portable mode )**

**Comment by Maypehl** [comment]
> > > `STATUS_INVALID_IMAGE_HASH 0xC0000428L` displayed only when hash is incorrect, but hash is checking only when profile type is compressed or encrypted, no other way
> > 
> > 
> > i have had compressed first but changed to plain after
> 
> {Path Not Found} The path %hs does not exist. Status: 0xC000003A
> 
> I solved it this way: Run installer as administrator Select this option during installation: **Store settings in application directory ( portable mode )**

Thank you! That solved it for me. I was getting all kinds of errors both on 3.7.2 and 3.7.3, which caused it to fail reaching the update server, save any changes and remembering the profile I've imported.

I was forced to stay on 3.7.1, which did not have those issues, but portable mode fixed it all!
Not running any Antiviruses here btw. Windows Defender is disabled with registry edits, yet I still had all those issues for some reason.

**Comment by nyanpasu64** [comment]
Using procmon I found that it was trying to access files in `C:\Users\nyanpasu64\AppData\Roaming\Henry++\simplewall`, which failed to be created. After creating `Henry++` by hand, simplewall created the simplewall subdirectory by itself.

I think you forgot to use a recursive directory creation routine after moving application data to a subdirectory.

**Comment by henrypp** [comment]
Now it is fixed, thanks @nyanpasu64

[simplewall.zip](https://github.com/henrypp/simplewall/files/13060858/simplewall.zip)

**Comment by NixonSchool** [comment]
I downloaded the old version 3.7 then updated it, and the issue was gone...😶

**Comment by bino1x1** [comment]
> > > `STATUS_INVALID_IMAGE_HASH 0xC0000428L` displayed only when hash is incorrect, but hash is checking only when profile type is compressed or encrypted, no other way
> > 
> > 
> > i have had compressed first but changed to plain after
> 
> {Path Not Found} The path %hs does not exist. Status: 0xC000003A
> 
> I solved it this way: Run installer as administrator Select this option during installation: **Store settings in application directory ( portable mode )**

I Have Same bug, in windows 11  PRO 23h2. I try em portable mode.

**Comment by bino1x1** [comment]
Yes, tried a portable mode, this bug  {Path Not Found} The path %hs does not exist. Status: 0xC000003A, are dispear. Fixed. In normal instalation, have this bug.
