### ISSUE TITLE
[Feature] Ability to import rules from windows firewall

### ISSUE THREAD

**Issue by Bluscream** [henrypp/simplewall#1595]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.7.3 x64

### Problem you are trying to solve

Initial setup when you only have remote connections like ssh/rdp is tedious and i always forget something and then i only see it a few days later popping up when i log back in

### Suggested solution

Convert and Import Windows Firewall rules to simplewall before disabling firewall

**Comment by henrypp** [comment]
i think it useless

**Comment by Bluscream** [comment]
Your app is useless then
