### ISSUE TITLE
[Feature] Simulated/Dry-run mode

### ISSUE THREAD

**Issue by Bluscream** [henrypp/simplewall#1596]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.7.3 x64

### Problem you are trying to solve

I am running on a windows server and whenever i first start simplewall it will kick me out of RDP/SSH and i can't get back in because i can't accept the prompts.

### Suggested solution

So a mode where it will show blocked stuff so i can allow it without actually blocking anything until setup is done is needed.

**Comment by henrypp** [comment]
complete not understand where is problem

**Comment by Bluscream** [comment]
> complete not understand where is problem

What do you not understand? If you need a network connection like RDP to control simplewall, but simplewall blocks these apps, there is no way to control the PC anymore

**Comment by henrypp** [comment]
where is the problem to allow RDP ?

**Comment by Bluscream** [comment]
> where is the problem to allow RDP rule on remote and local machine?

I can't add RDP rule when simplewall is on because i can't control it anymore

**Comment by henrypp** [comment]
not needed to add rule, it already in system rules

**Comment by Bluscream** [comment]
> not needed to add rule, it already in system rules

it is not enabled and cant be enabled
