### ISSUE TITLE
[Bug] Crash at startup and massive slowdown

### ISSUE THREAD

**Issue by g-k-m** [henrypp/simplewall#1599]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.2, latest updated (i check for update every single day)

### Windows version

Windows 10 22H2 19045.3570

### Steps to reproduce

When pc boots, thus when simplewall starts, the whole pc freezes for around 5 secs. This only happens when simplewall is launched, doesn't happen with other programs, I think this started happening with version 3.7

Today when i booted pc i was greeted with this msg

![image](https://github.com/henrypp/simplewall/assets/37273303/6017a9d2-86fe-43b7-96bd-caa8f9bf347c)

Here's crash dump
[simplewall-1697388852.dmp](https://github.com/henrypp/simplewall/files/12910167/simplewall-1697388852.dmp)

Also by the way, another minor bug report, when a notification pops up and you close it, the previous notification before that shows up

### Actual behavior

.

**Comment by henrypp** [comment]
You cant use new version? 3.7.3

**Comment by g-k-m** [comment]
> You cant use new version? 3.7.3
> 
> upd: but this is already from 3.7.3 so it is dup of #1582

I misstyped 2 instead of 3, i meant 3.7.3, i have latest version cuz i check for updates every single day
