### ISSUE TITLE
Popups appearing when custom rules already apply

### ISSUE THREAD

**Issue by undesiredpopup** [henrypp/simplewall#160]
For example:

Create a custom rule blocking UDP 1900 applying to all apps and enable it.
The request is blocked but a popup is still generated for chrome.exe when it tries to do SSDP.

**Comment by henrypp** [comment]
you add custom rule to block 1900 port and are surprised why popups for "your rule" displays when it's blocked?

**Comment by undesiredpopup** [comment]
I guess I wasn't clear about this feature request, so I'll try describing it again.

If possible I would like more granularity for disabling notifications for an application. Using a browser as an example, I would like the ability to be able to disable notifications for blocked requests on port 80 BUT still receive notifications for requests on other ports for that app and not disable notifications completely.
