### ISSUE TITLE
[Bug] Couldn't save profile

### ISSUE THREAD

**Issue by DetectiveSunshine** [henrypp/simplewall#1600]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.3

### Windows version

Windows 10 Pro

### Steps to reproduce

Couldn't save profile, portable version works tho. Bug still persists from 3.7.2 version.
error - https://i.imgur.com/yrzjUnl.png

### Actual behavior

There wouldn't be an error

**Comment by duzers** [comment]
I confirm, I have the same.

**Comment by henrypp** [comment]
> I have used the search function to see if someone else has already submitted the same bug report.

orly?

**Comment by technot80** [comment]
confirm, with version 3.7.3 fresh install on a freshly installed windows 11 pro.
Choosing portal install during installation fixes the issue for me as well.
