### ISSUE TITLE
[Bug] Windows update weirdness - Windows update only works when Simplewall UI is running

### ISSUE THREAD

**Issue by Poonsta** [henrypp/simplewall#1602]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.3

### Windows version

10 Pro 22h2 

### Steps to reproduce

1. Set up Simplewall to allow windows update
2. Exit Simplewall UI
3. Go to Settings (in Windows)
4. Go to Update (from Settings)
5. One of two things is possible:
   a. Windows can find an update, but cannot download it giving an error message, or the update just sitting at 0%. If I start Simplewall UI at this point, the Settings window crashes, but when restarting the Settings window, it starts downloading.
   b. Check for updates. Windows can check, but cannot download, or cannot even check. Start the Simplewall UI, check for update again, no problem.

### Expected behavior

Windows update working with or without the Simplewall UI running.

### Actual behavior

Windows update working only when Simplewall UI is running

### Logs

No logs whatsoever. Sorry.

**Comment by henrypp** [comment]
you believe in flat earth?

**Comment by Poonsta** [comment]
Nah, but I believe I'll have a beer.

**Comment by Glycyrrhizin** [comment]
> you believe in flat earth?

Do you believe in fixing your broken software instead of making fun of people?

**Comment by henrypp** [comment]
@Glycyrrhizin what broken? WU not interfere with any WFP provider.
no, because 0iq people give me a fun, lol
