### ISSUE TITLE
[Bug] Version 3.7.3 is not installing itself

### ISSUE THREAD

**Issue by jacob-44** [henrypp/simplewall#1604]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.1

### Windows version

10

### Steps to reproduce

Do you want to install it? Yes

### Actual behavior

Nothing happens

**Comment by henrypp** [comment]
very interesting

**Comment by jacob-44** [comment]
closed as completed? hmm....

**Comment by henrypp** [comment]
wtf? you cannot install by yourself? insted you create duplicate issue, it is very interesting

**Comment by jacob-44** [comment]
what the fuck I cannot install it by myself? let me try what the fuck.
