### ISSUE TITLE
[Question] does simplewall protect a local account

### ISSUE THREAD

**Issue by jl-dg** [henrypp/simplewall#1606]
simplewall is installed on an admin account on my PC. it requests launch permission when opening the admin session, and it appears in the list of processes. 
when I log in with a local account, on the same machine, no authorization request, and simplewall does not appear in the list of processes. on the other hand, the Microsoft firewall stay disconn
ected.. Does simplewall monitor the connections of the local account?  or is there no firewall anymore??

if I run the app simplewall as administrator in the local account, nothing appears..
please clarify if the pc is protected or not in the local account..
thank you..

---

App version: <3.7.1
Windows version: win 11 home 22h2

**Comment by jl-dg** [comment]
more precise observation:
simplewall works with a standard account if it is the only account connected! (but no icon appears in the taskbar).
If a standard account and an admin account are both connected, simple wall only responds in the first connected account.

How protected is the account logged in second??

the task manager does not indicate a simplewall process, and windows defender is disconnected!

thanks for the clarifications..

**Comment by henrypp** [comment]
protect? from what?
