### ISSUE TITLE
%hs profile not found upon enabling simplewall

### ISSUE THREAD

**Issue by NixonSchool** [henrypp/simplewall#1607]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

Latest, october 24th 2023

### Windows version

Windows 10 and Windows 11(have both)

### Steps to reproduce

![image](https://github.com/henrypp/simplewall/assets/139177099/66e68574-2203-4e87-bbb9-8501f8c06680)

### Expected behavior

I want to just block all apps, but this %hs keeps appearing upon enabling simplewall.

It reoccurs to any app that gets blocked, so it's a pain in the neck, trying to close those 1 billion %hs popups, from my 350 applications that get blocked.

It's just started disturbing me since I got the latest update. The previous version doesn't give me this weird error. 

Henry++ please fix it coz that's a minus minus.😑
### Actual behavior

It should just block stuff and not bring up weird C code errors.

**Comment by henrypp** [comment]
>  I have used the search function to see if someone else has already submitted the same bug report.

lol #1594

**Comment by edge540T** [comment]
Here on new windows 10 computer.
![imagen](https://github.com/henrypp/simplewall/assets/123776322/8a6af19c-2163-4c4b-be7c-4f6a26d8fefa)
Copy says the same.
{Path Not Found}
La ruta %hs no existe.

Status: 0xC000003A

**Comment by delima2001** [comment]
i hava the same error

{Path Not Found}
La ruta %hs no existe.

Status: 0xC000003A

**Comment by henrypp** [comment]
@delima2001 you complete idiot or not found new version?
