### ISSUE TITLE
[Question]Are a second user's internet connections filtered?

### ISSUE THREAD

**Issue by jl-dg** [henrypp/simplewall#1608]
excuse me for the poor wording of question 1606.
What happens if two users are logged in simultaneously (admin and standard).
Simple wall gui only responds for the first logged in user.
In the task manager, simplewall only appears in the processes of the first connected user.
The Windows firewall appears disabled in the second user.
(Second refers to the user who logged in after)

Are the second user's internet connections filtered? Are they filtered by simpleWall?

Thank  you for help

App version: 3.7.3 x64
Windows version: <windows 11 22h2

**Comment by henrypp** [comment]
sw processes ALL users

> simplewall only appears in the processes of the first connected user

wtf?
