### ISSUE TITLE
simplewall.exe cannot be blocked in v3.7.3

### ISSUE THREAD

**Issue by woodsy7** [henrypp/simplewall#1609]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.3

### Windows version

Windows 11 22H2

### Steps to reproduce

I have disabled the checkbox from simplewall.exe. (permanently rules)

### Actual behavior

It is active again every time the computer is restarted.

**Comment by henrypp** [comment]
now it fixed, try this and wait for next release [simplewall.zip](https://github.com/henrypp/simplewall/files/13179373/simplewall.zip)

**Comment by woodsy7** [comment]
Thank you very much.
