### ISSUE TITLE
[Bug] Random crush on startup

### ISSUE THREAD

**Issue by Tindal** [henrypp/simplewall#1611]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.3.

### Windows version

Windows 10 Pro 22H2

### Steps to reproduce

It's randomly, no way to reproduce it

### Actual behavior

![image](https://github.com/henrypp/simplewall/assets/18662980/6e88a7d1-1fd1-4c1d-b571-1612f037de83)

### Logs

[simplewall-1698346796.dmp](https://github.com/henrypp/simplewall/files/13181730/simplewall-1698346796.dmp)
[simplewall-1698341867.dmp](https://github.com/henrypp/simplewall/files/13181731/simplewall-1698341867.dmp)

**Comment by henrypp** [comment]
> I have used the search function to see if someone else has already submitted the same bug report.

lol #1582
