### ISSUE TITLE
[Question] Is the Simplewall Internal Blocklist Up-to-date?

### ISSUE THREAD

**Issue by XSpark0** [henrypp/simplewall#1612]
I ask this because WindowsSpyBlocker https://github.com/crazy-max/WindowsSpyBlocker doesn't seem to have updated blocklist since May 16, 2022, since Simplewall uses blocklist from WindowsSpyBlocker.

Issue found there: https://github.com/crazy-max/WindowsSpyBlocker/issues/505

update.txt not updated since May 16, 2022: https://github.com/crazy-max/WindowsSpyBlocker/blob/master/data/hosts/update.txt
and spy.txt: https://github.com/crazy-max/WindowsSpyBlocker/blob/master/data/hosts/spy.txt

**Comment by henrypp** [comment]
no, it uses latest revision from its repo, but it does not updayed 1.5 years because author is busy, i think i update when him release new version...
