### ISSUE TITLE
[Bug] Services and UWP apps deleted & Disable removal rule enabled by default in v3.7.4

### ISSUE THREAD

**Issue by Alcazer** [henrypp/simplewall#1616]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.4

### Windows version

Windows 11 Pro 22H2 & Windows 11 Pro for Workstations 22H2 

### Steps to reproduce

1. Go to Services or UWP apps
2. Click on Refresh
3. You will see that they are all deleted and some are duplicated
4. Right click on any Services or UWP apps then check Rules section
5. You will see "Disable removal" is enabled

### Actual behavior

Services and UWP apps deleted and duplicated
Disable removal rule enabled for Services and UWP apps

**Comment by Alcazer** [comment]
@henrypp its critical

**Comment by henrypp** [comment]
this is fixed now. you can replace binary by this [simplewall.zip](https://github.com/henrypp/simplewall/files/13196288/simplewall.zip)

**Comment by henrypp** [comment]
it fixed now, you can replcate binary [simplewall.zip](https://github.com/henrypp/simplewall/files/13196301/simplewall.zip)

**Comment by Alcazer** [comment]
Thanks, this worked partially. I found a new bug.

### Steps to reproduce

1. Go to UWP apps
2. Enable some apps
3. Click Help -> Check for updates
4. Downloading update finished.
5. You will see all UWP apps are red and seems like it was deleted
6. Click on Refresh
7. You will see Enabled ones are deleted

Note : If your language files up to date or "No updates available." please remove simplewall.lng in simplewall folder and re-open simplewall. Repeat the steps

**Comment by Alcazer** [comment]
I found a new bug again

### Steps to reproduce

1. Go to UWP apps
2. Enable some one
3. Click Edit -> Purge unused apps or Press Ctrl + Shift + X
4. You will see App without internet access are gone (deleted)
5. Go to Services
6. Enable some one
7. Click Edit -> Purge unused apps or Press Ctrl + Shift + X
8. You will see most of them are gone (deleted)

Note : If your language files up to date or "No updates available." please remove simplewall.lng in simplewall folder and re-open simplewall. Repeat the steps

**Comment by Alcazer** [comment]
I found a new bug again

### Steps to reproduce

1. Go to UWP apps
2. Enable some one
3. Click Edit -> Purge unused apps or Press Ctrl + Shift + X
4. You will see App without internet access are gone (deleted)
5. Go to Services
6. Enable some one
7. Click Edit -> Purge unused apps or Press Ctrl + Shift + X
8. You will see most of them are gone (deleted)

**Comment by henrypp** [comment]
fixed
[simplewall.zip](https://github.com/henrypp/simplewall/files/13196595/simplewall.zip)

**Comment by Alcazer** [comment]
Thanks again, it's look nice but when update completed still UWP apps are red renamed and seems like it was deleted (ss added). Sometimes crashed (dmp file added). If it doesn't crash then clicked refresh it looks nice. 

![simplewall-1698527618](https://github.com/henrypp/simplewall/assets/3519946/d3ba778c-47fe-49af-845a-fd67f853e4b3)

[simplewall-1698527618.dmp](https://github.com/henrypp/simplewall/files/13196734/simplewall-1698527618.dmp)

**Comment by showmak** [comment]
> fixed [simplewall.zip](https://github.com/henrypp/simplewall/files/13196595/simplewall.zip)

Replacing the .exe will fix the issue?

**Comment by henrypp** [comment]
> > fixed [simplewall.zip](https://github.com/henrypp/simplewall/files/13196595/simplewall.zip)
> 
> Replacing the .exe will fix the issue?

where is ur logic??

**Comment by Alcazer** [comment]
@henrypp thanks again. Now only UWP apps renamed. Others fine.

### Steps to reproduce

1. Go to UWP apps
2. Enable some apps
3. Click Help -> Check for updates -> Downloading update finished.
5. You will see all UWP apps renamed
6. Click on Refresh or Press F5
7. You will see all names coming back, getting better

Note : If your language files up to date or "No updates available." please remove simplewall.lng in simplewall folder and re-open simplewall. Repeat the steps

**Comment by Alcazer** [comment]
> @henrypp thanks again. Now only UWP apps renamed (forgets app name) . Others fine.
> 
> ### Steps to reproduce
> 1. Go to UWP apps
> 2. Enable some apps
> 3. Click Help -> Check for updates -> Downloading update finished.
> 4. You will see all UWP apps renamed (forgets app name)
> 5. Click on Refresh or Press F5
> 6. You will see all names coming back, getting better
> 
> Note : If your language files up to date or "No updates available." please remove simplewall.lng in simplewall folder and re-open simplewall. Repeat the steps

@henrypp in 3.7.6 still not fixed

**Comment by Alcazer** [comment]
@henrypp in 3.7.7 still not fixed

**Comment by henrypp** [comment]
@Alcazer uwp & services do not deleted

**Comment by Alcazer** [comment]
> @Alcazer uwp & services do not deleted

Yep but all apps renamed (forgets app name) as in the picture

![renamed](https://github.com/henrypp/simplewall/assets/3519946/4165bac1-f20d-4869-9f54-b51c2c948b26)

**Comment by Alcazer** [comment]
@henrypp in 3.8 still not fixed. UWP apps renamed (forgets app name)

### Steps to reproduce

1. Go to UWP apps
2. Enable some apps
3. Click Help -> Check for updates -> Downloading update finished.
5. You will see all UWP apps renamed (forgets app name)
6. Click on Refresh or Press F5
7. You will see all names coming back, getting better

Note : If your language files up to date or "No updates available." please remove simplewall.lng in simplewall folder and re-open simplewall. Repeat the steps

![2024-04-01 133000](https://github.com/henrypp/simplewall/assets/3519946/87a08417-6409-48b0-ba04-f750ad746357)

**Comment by Alcazer** [comment]
@henrypp in 3.8.3 still not fixed. UWP apps renamed (forgets app name)

![image](https://github.com/user-attachments/assets/892c83e3-29ec-401c-8189-59f7499e16d2)
