### ISSUE TITLE
[Bug] Log subscribe failed.

### ISSUE THREAD

**Issue by LuisfTV** [henrypp/simplewall#1617]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.4 x64

### Windows version

Windows 10 Pro x64

### Steps to reproduce

1. Boot the computer
2. SimpleWall loads/starts automatically when Windows start
3. I get the error message:  Log subscribe failed. Try again later.  Access is denied. Status: 0x00000005

### Expected behavior

The expected behavior is not to see this error message.

### Actual behavior

The app is showing a pop-up error message as soon as the app loads.

### Logs

<img width="265" alt="Simplewall Error" src="https://github.com/henrypp/simplewall/assets/149227525/20ee4f84-ee40-4176-b888-f760dc618e75">

**Comment by henrypp** [comment]
it not normal, i agree, but only you know who was made changes in wfp acl, check your 3rd party software, do not know who can made it because i dont use bullshit on my compute

**Comment by t0ma5** [comment]
I have had the same problem for months.. none of the recent updates fixed it
