### ISSUE TITLE
[Bug] UWP app rules do not persist; they get erased when the app exits

### ISSUE THREAD

**Issue by skycommand** [henrypp/simplewall#1619]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.4

### Windows version

10.0.19045

### Steps to reproduce

1. Install SimpleWall
2. Run it
3. Run several UWP apps such as Mail, Calendar, To Do, Xbox Game Bar, Weather, Calculator, etc.
4. When prompted Allow their Internet access
5. Exit SimpleWall using File > Exit command. Restarting the system has the same effect.
6. Run SimpleWall again.

### Expected behavior

When I permit Internet access to a UWP app, the rule must remain available regardless of how many times I exit SimpleWall or restart my computer.

![Expected behavior](https://github.com/henrypp/simplewall/assets/17097175/b37d82e2-98fa-4e2a-892e-3376597213c0)

### Actual behavior

UWP app list reset to empty each time SimpleWall exits

![Actual behavior](https://github.com/henrypp/simplewall/assets/17097175/049c77ce-d3ac-499f-9411-32fe7064b844)

**Comment by henrypp** [comment]
>  I have used the search function to see if someone else has already submitted the same bug report.

lol #1616

**Comment by skycommand** [comment]
> lol #1616

@henrypp How am I supposed to know it is the same thing when the title is misleading? It reads: "Services and UWP apps deleted & Disable removal rule enabled by default." It means SimpleWall deletes service (or their registrations) and UWP apps! (It would be horrible, though.)

I used the search function but I'm not a mind reader.
