### ISSUE TITLE
[Bug] Rules for UWP apps disappear after F5

### ISSUE THREAD

**Issue by Alickop** [henrypp/simplewall#1620]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.4

### Windows version

10

### Steps to reproduce

1. Run any UWP app
2. Enable all connections for it in SF
3. Go to UWP Apps tab 
4. Press F5

### Expected behavior

Rule for UWP apps stay permanent as desired 

### Actual behavior

Rule for this app disappear

**Comment by henrypp** [comment]
> I have used the search function to see if someone else has already submitted the same bug report.

lol, check 1616
