### ISSUE TITLE
[Bug] Processes locked by simplewall

### ISSUE THREAD

**Issue by Uj947nXmRqV2nRaWshKtHzTvckUUpD** [henrypp/simplewall#1621]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.4

### Windows version

11 (22H2 build 22621.2428)

### Steps to reproduce

attempt to update android studio (the previous version before 2023.2.1 canary) from within the app
restart android studio ide, when prompted

### Expected behavior

simplewall doesn't lock the processes

### Actual behavior
Cannot update android studio because simplewall locks its processes
![image](https://github.com/henrypp/simplewall/assets/7840350/e1300deb-9e90-41e2-a18f-ab3679821b5e)

I never encountered this issue until recently. i enabled "monitor apps changing" in simplewall some days ago. could it be related?
Where is this feature documented?

Quitting simplewall from tray, allows android studio updating, as expected.

Thanks

**Comment by henrypp** [comment]
yes it fixed, wait for tomorrow!

[simplewall.zip](https://github.com/henrypp/simplewall/files/13219120/simplewall.zip)
