### ISSUE TITLE
[Bug] random crash

### ISSUE THREAD

**Issue by DrainLife0** [henrypp/simplewall#1624]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.4

### Windows version

Win10 22H2 x64

### Steps to reproduce

With v3.7.4 simplewall It crashes randomly.
This happens (not all the time, of course) when it pops up a new program and I select the action to take (mostly reject).

So, I can't really provide steps to reproduce the error.
I'd say it's like a new pop-up, and then I click 'reject.'

I've attached the dump file.

### Actual behavior

After I refuse internet access to a new program, SimpleWall crash.

### Logs

[simplewall-1698684266.dmp](https://github.com/henrypp/simplewall/files/13209050/simplewall-1698684266.dmp)

**Comment by henrypp** [comment]
How often it happens when notification dialog appears?

**Comment by DrainLife0** [comment]
It happened twice in a row, but nothing since then... I think I've had around 20 alerts so far.
