### ISSUE TITLE
[Question] Windows defender reports 3.7.5 setup as Trojan:Script/Phonzy.B!ml

### ISSUE THREAD

**Issue by victorzzt** [henrypp/simplewall#1627]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.5

### Windows version

10.0.19045.3570

### Steps to reproduce

1. The problem is only with the simplewall-3.7.5-setup.exe, downloading the zip and unzip does not have the positive, so it's the setup packager's problem likely.

### Actual behavior

2. Windows Defender reports as Trojan:Script/Phonzy.B!ml
3. A report from [VirusTotal Report](https://www.virustotal.com/gui/file/7804edc4a726f39a94cb08197a9cad5818eda2854c9cf64d84aadf58ecf3d4a9)
4. Given past [3.7.2](https://github.com/henrypp/simplewall/issues/1560) situation possibly a false positive.

So just throw it here if anyone else is having similar problem that just download the zip and overwrite the file manually if you don't want to take the chance.

**Comment by henrypp** [comment]
i dont care, compile youself
