### ISSUE TITLE
[Feature] Allow any connection except those that are explicitly blocked

### ISSUE THREAD

**Issue by outcast1000** [henrypp/simplewall#1628]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.7.5

### Problem you are trying to solve

I want to block certain apps. Anything else should be allowed to connect without asking.

### Suggested solution

Have an operation modes like:
"Allow All"
"Normal" (Allow those that are defined to be allowed - Block those are defined to be blocked - Ask anything else)
"Allow All except blocked"
"Block All"

**Comment by LtqxWYEG** [comment]
That could also be done by inverting a rule, like i asked for (and maybe got) here: https://github.com/henrypp/simplewall/issues/1637
so... it could be already done. :)

**Comment by henrypp** [comment]
ye

**Comment by outcast1000** [comment]
Well @LtqxWYEG my request was the opposite than yours. Block only certain apps, do not ask me for anything else. Lets wait & see. Thanks @henrypp

**Comment by henrypp** [comment]
u already can do this without any problem, if u have logic u can
