### ISSUE TITLE
How can I update Simplewall?

### ISSUE THREAD

**Issue by Boristhemoggy** [henrypp/simplewall#1630]
Simplewall keeps popping up with a note that a new version is available. But I have it as a portable program, and when I click to update it doesn't update. How can I update it please?

---

App version: <Version 2.7.3 Release 64bit>
Windows version: <10.0.19045 Build 19045>

**Comment by henrypp** [comment]
u cant instal manually??

**Comment by Boristhemoggy** [comment]
I can replace the program that is already there, but then what happens to my rules list?
