### ISSUE TITLE
[Question] Windows 10 wont let me install

### ISSUE THREAD

**Issue by levidehaan** [henrypp/simplewall#1632]
I have tried all 3 installs using chocolatey
i then downloaded it, and chrome wouldnt let me open it.
so i downloaded it with firefox and windows wouldnt let me open it.
so i allowed it and windows Wont start it.
soooo. do i need to wipe this computer now?

---

App version: latest
Windows version: 10

**Comment by henrypp** [comment]
why wipe?

**Comment by levidehaan** [comment]
Windows 7?

**Comment by henrypp** [comment]
it was dropped

**Comment by levidehaan** [comment]
Yeah I mean I don't care if it's supported or not, I just want to see outgoing connections. 

I'll compile it, git submodules and all. But how annoying huh, how does it even get a signature match when the codebase is available to the Same Company... Sometimes MS... Sometimes...
