### ISSUE TITLE
[Question] How to compile this program?

### ISSUE THREAD

**Issue by dellasorte** [henrypp/simplewall#1633]
How do I compile this sofrware from this source? I have installed Visual Studio 2022 Community Edition. The error I meet says that routine.h, rapp.h and some other header files are missing. Is this full repository? or you hiding some code parts? is it open-source project?

Here is a list of missing files:

ntapi.h
ntrtl.h
rapp.h
rconfig.h
routine.h
rtypes.h
rapp.c
routine.c

I checked your project dependencies (NuGet package manager) - everything seems fine. The only one dependency is installed in my system. So I really don't understand  what is going on

**Comment by henrypp** [comment]
gitmodules is so hatd
