### ISSUE TITLE
[Bug]WIndows Update workaround not working in 3.7.4 and 3.7.5

### ISSUE THREAD

**Issue by luckygitt** [henrypp/simplewall#1636]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.4/3.7.5

### Windows version

10

### Steps to reproduce

Tick: Settings > Rules > Allow Windows Update

### Expected behavior

Should give internet access to wusvc.exe.

### Actual behavior

Nothing, it's broken / doesn't work!

**Comment by henrypp** [comment]
fx
