### ISSUE TITLE
[Feature] Checksum test to avoid substitution leak

### ISSUE THREAD

**Issue by Pierre4012** [henrypp/simplewall#1638]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.7.5 (lastest)

### Problem you are trying to solve

simplewall does not check for changes to executables, so it is possible for malware to replace a common and already authorized executable to gain Internet access (substitution leak).

This behavior can be reproduced with any program or using the tool available on this page: [https://www.grc.com/lt/leaktest.htm](url)
To test, download this program, and replace a program already authorized by it (same folder and same executable name). It will have Internet access without simplewall warning.

### Suggested solution

A checksum test could be performed on authorized executables.
This could be an option to choose (each program update would generate a warning to validate).

**Comment by henrypp** [comment]
every program has already test for replacement, see monitor apps changing? not any replcaed program can have inet access, because SW test it change and disable it...

**Comment by Pierre4012** [comment]
The "Monitor apps changing" option is checked on my computer, but therefore it does not work as expected, the replaced executable accesses the Internet without reporting.

Would you be interested in a video recording?
