### ISSUE TITLE
[Bug] Simplewall blocks access to shared folders

### ISSUE THREAD

**Issue by vgiv** [henrypp/simplewall#1639]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.5 (64 bit, Unicode)

### Windows version

Windows 10 Pro (22H2, build 19045.3086)

### Steps to reproduce

1) Enable system rules 'SMB (inbound)' and 'SMB (outbound)'.
2) Enable service 'Shared access'.
3) Create and enable a user rule: any protocol, any family inbound connections is enabled for ip 192.168.1.1-192.168.1.255 (the full range of the local network addresses).
4) Try to connect to a shared folder of the computer from another device (both are in the same local network). The result is a kind of 'SMB2 CONNECT: failed to connect to /192.168.1.2 (port 445) from /192.168.1.35 (port 50418)'.
5) Disable all filters of Simplewall.
6) Repeat step 4. The connection to the shared folder is successful.

Steps 2 and 3 seem redundant, but are added just in case.

### Expected behavior

The shared folder is to be accessed.

### Actual behavior

The shared folder cannot be accessed until all Simplewall filters are disabled. There are no pop-up messages warning you about any blocking.

**Comment by henrypp** [comment]
orly? and packets logs is not helped?

**Comment by vgiv** [comment]
Thanks, it helped.
But I realized that I do not understand rules priorities in SImplewall. Say, I create two rules: (1) blocks all inbound traffic and (2) allows it to a specific port. I believed that the particular rule (2) should take precedence over the more general (1). But it isn't the case.
