### ISSUE TITLE
High CPU usage on System Startup

### ISSUE THREAD

**Issue by Zeguim** [henrypp/simplewall#1642]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.5

### Windows version

22H2

### Steps to reproduce

1. Go to taskschd.msc
2. Create a task for simplewall.exe to start only when user is logged on
3. reboot the PC

### Expected behavior

Deppending on the beefyness of your system, you'll experience serious slow down of the system because of the high cpu usage caused by firewall for something about 5 to 10 seconds until it goes back to normal.

### Actual behavior

You should disregard the other simplewall entrance there because I had two tasks on taskschd.msc, for some reason. But that was not the cause. I disabled one and the issue still persisted. The usage goes up to 92%.

![Simplewall High CPU Usage on System Startup](https://github.com/henrypp/simplewall/assets/127639589/15cd1746-87d5-428e-b7f0-9825c1c9ae66)

**Comment by Vegajav** [comment]
I have the same problem. I've noticed raise of CPU usage since 3.7.5 update.

**Comment by courrier1** [comment]
I have the same issue with disk usage since many apps blocked are in the hdd, I turned off "Check apps for digital signatures" and it still happens.

**Comment by henrypp** [comment]
fx

**Comment by dr04e606** [comment]
> I have the same problem. I've noticed raise of CPU usage since 3.7.5 update. If I turn off "Enable packets logging interface" flag in SimpleWall settings, CPU consumption returns to normal.

Thank you for pointing this out. I've also noticed that on my relatively underpowered laptop, enabling the "packets logging" feature in simplewall can significantly increase CPU load. It's the most noticeable when there is substantial network activity, irrespective of whether it involves allowed or blocked applications. Interestingly enough, (at least in v3.7.8) minimizing simplewall to the tray results in much lower CPU load, even with the "packets logging" feature still enabled.

Additionally, performing a simple search using either an app name or an IP address can also lead to spikes in CPU usage. Overall, the user interface feels quite sluggish during searches, even on more powerful machines.
