### ISSUE TITLE
[Bug] 3.7.3 not updating to 3.7.5

### ISSUE THREAD

**Issue by Phaalus** [henrypp/simplewall#1644]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.3

### Windows version

Win10 64bit

### Steps to reproduce

This is for manual update only

-Load Simplewall
-Tap update
-Shows, 3.7.5 is availble
-Download
-Asks to install
-Tap yes
-Nothing happens
-Simplewall runs as expected

### Expected behavior

As usual I expect it to update. Never had an issue with this.

### Actual behavior

No update. v3.7.3 is held, and simplewall runs normally

**Comment by henrypp** [comment]
no eyes? #1565
