### ISSUE TITLE
[Bug] Blue screen when trying to open log

### ISSUE THREAD

**Issue by feelingok** [henrypp/simplewall#1645]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.5

### Windows version

10

### Steps to reproduce

Open simplewall
click "open log" button
Clicking once does nothing
The second click causes Blue screen

### Actual behavior

"CRITICAL_PROCESS_DIED" blue screen after trying to open log through the program. I tried changing from notepad to another app throught settings but it didn't fix it.

**Comment by henrypp** [comment]
lol, and it is my fault?

**Comment by feelingok** [comment]
Well sorry if this came across rudely, I just updated and encountered this, thought it was worth reporting.

**Comment by henrypp** [comment]
maybe not a bsod, just error message?

**Comment by feelingok** [comment]
If no one else has this issue it's probably just my windows / SSD dying. It consistently BSODs every time i try to open the log. I can open it externally though so it's not a problem

**Comment by henrypp** [comment]
if ur ssd dying <s>buy new one</s> where is the problem to use logging in UI?
