### ISSUE TITLE
[Feature] Rule for app name only, ignore location

### ISSUE THREAD

**Issue by ahdung** [henrypp/simplewall#1646]
### Checklist

- [ ] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.7.5

### Problem you are trying to solve

I want allow `A.exe`, no matter where it is, and no matter case, `a.eXe` should allowed too.

### Suggested solution

soso

### Screenshots / Drawings / Technical details

![image](https://github.com/henrypp/simplewall/assets/12094247/4a75a132-89a8-446a-828b-5bb56ee50dd6)

**Comment by azenapow** [comment]
I agree with this feature.
Some applications have relative paths,
eg. "C:\program files\windowsapps\91750d7e.slack_4.29.149.0_x64__8she8kybcnzg4\app\slack.exe"

**Comment by henrypp** [comment]
> I have used the search function to see if someone else has already submitted the same feature request.

aga, and n1635 and 9000+ other issues with same request u not found

**Comment by ahdung** [comment]
@henrypp Sorry for disturbed you, I did searching before, this is my view:

![image](https://github.com/henrypp/simplewall/assets/12094247/e02ffc7e-8634-452f-8449-c2990ae2898b)
