### ISSUE TITLE
[Bug] Rules > Allow Windows Update not working

### ISSUE THREAD

**Issue by opusforlife2** [henrypp/simplewall#1648]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.5

### Windows version

Windows 10

### Steps to reproduce

1. Enable this rule.
2. Check for Windows updates.

### Expected behavior

Windows Update should be allowed through the firewall.

### Actual behavior

"We couldn't connect to the update service. We'll try again later, or you can check now. If it still doesn't work, make sure you're connected to the Internet."

Also, this might be connected to 2 other bugs:

1. Once this rule is enabled, it cannot be disabled, at least according to the UI. The status bar shows that it is applying the filters, but the tick doesn't go away once it is enabled, no matter how much you try to disable it. It just says "applying filters" and stays enabled.
2. The rule gets reset to disabled on every restart of the OS. (Or rather, I should say that the tick goes away. I don't know whether the rule is still applied or not.)

Update: I confirmed by checking the ini settings file that the WU-fix-enabled parameter never switches to true. Even manually setting it to true after closing Simplewall doesn't work. It switches back to false when Simplewall is started.

**Comment by strotee** [comment]
This is what I do to make WU work with Simplewall:

**Services** tab: give BITS internet access.
**System rules** tab: enable Windows Update (2 of them)
**User rules** tab: enable HTTP
Last but not least: menu Blocklist -> MS Update -> Allow

**Comment by VonDach** [comment]
I have the same problem that you for at least a month under Windows 11, latest version.

**Comment by henrypp** [comment]
now it is fixed, see it in next version or... [simplewall.zip](https://github.com/henrypp/simplewall/files/13505554/simplewall.zip)

**Comment by privacyguy123** [comment]
This bug is back - can't get the rule to persist reboot.
