### ISSUE TITLE
Not showing in system tray since update

### ISSUE THREAD

**Issue by Boristhemoggy** [henrypp/simplewall#1649]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.5

### Windows version

Win 10 22H2, build 19045

### Steps to reproduce

Start computer, simplewall not activated. Manually start simplewall, windows update is unticked, whereas it was ticked earlier. Close simplewall to systemtray. It does not appear in the system tray. Restart simplewall. Simplewall is running in the background, but I can't see it. If I want to alter any filter I need to go through the process as if I am starting it up for the fist time.

### Expected behavior

When I close it it has always closed to the system tray

### Actual behavior

When I close it it disappears and I have to start it again to see it

**Comment by henrypp** [comment]
this problem was solved,dont know which 3rd party app dont show required icons in your system,check your pc with av

**Comment by henrypp** [comment]
solution https://github.com/henrypp/simplewall/issues/1695#issuecomment-1885857698
