### ISSUE TITLE
Edge refused to download 3.7.6

### ISSUE THREAD

**Issue by rexebin** [henrypp/simplewall#1651]
Describe the question with as much detail as possible.

Thanks for the awesome tool!

somehow edge or windows refuses to download the latest version 3.7.6
![image](https://github.com/henrypp/simplewall/assets/10893959/648f2f50-b015-4dc1-9c4e-a7cff3bd6e82)

---

App version: <enter app version here>
Windows version: <enter windows version here>

**Comment by henrypp** [comment]
u cant download? where is the problem to disable fucking defender and idiotic smartscreen?

**Comment by rexebin** [comment]
I get where you are coming from. My intention of the issue was to remind
you that the idiotic smart screen works against your software. Apologies if
it offended you.
