### ISSUE TITLE
Simplewall 3.7.6 installer won't start on Windows 8.1

### ISSUE THREAD

**Issue by basilisk0315** [henrypp/simplewall#1652]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.6

### Windows version

Windows 8.1 x64

### Steps to reproduce

1. Download the installer (simplewall-3.7.6-setup.exe).
2. Run the installer by double clicking it.

### Expected behavior

Simplewall 3.7.6 installs.

### Actual behavior

A dialogue box appears stating that simplewall 3.7.6 requires Windows 8.1 or later.

**Comment by basilisk0315** [comment]
Update: running simplewall 3.7.6 from the zip package (simplewall-3.7.6-bin.zip) seems to work ok.

**Comment by henrypp** [comment]
its installer problem as i see,need to rewrite

**Comment by nestorkea** [comment]
Hello there! I second that. This morning I tried to update the app and faced a warning 
![warning](https://github.com/henrypp/simplewall/assets/149029677/c29670ab-5488-452f-be6b-cf82ba38c3d9)
By the way, is it necessary to delete the old version of the app before installing a new one (to make it function properly), or it's ok installing a new version over previous one?

**Comment by henrypp** [comment]
fx
