### ISSUE TITLE
[Question] What do I have to enable to use the WhatsApp dektop app ?

### ISSUE THREAD

**Issue by AXiSource** [henrypp/simplewall#1654]
I have to disable filters to use Whatsapp.
Microsoft Update is on "Allow" 
Microsoft Application is on "Allow"

Are there settings that allow me to keep filters enabled please ?

Same for Microsoft Store please ?
---
App version: 3.7.6
Windows version: 10

**Comment by henrypp** [comment]
all in log

**Comment by AXiSource** [comment]
What does "all in log" mean please ?

I have no clue.

**Comment by henrypp** [comment]
from main page;

> Definitely for advanced users.
