### ISSUE TITLE
[Question] Can I block domains with simplewall?

### ISSUE THREAD

**Issue by HydraDragonAntivirus** [henrypp/simplewall#1656]
Hi I have 5.5 million unique website and ip list and all of them infected. Can I add domains to block that.
---

App version: <3.7.6>
Windows version: <Windows 10>
![image](https://github.com/henrypp/simplewall/assets/142328963/e8089759-ed01-4ef4-bc2b-0a4086eab915)

**Comment by henrypp** [comment]
u cannot use dnscrypt?

**Comment by HydraDragonAntivirus** [comment]
You are awesome.

**Comment by henrypp** [comment]
not understand anything, dnscrypt not needed GUI at ALL, and latest release is 4 months ago

https://github.com/DNSCrypt/dnscrypt-proxy/releases/tag/2.1.5

**Comment by HydraDragonAntivirus** [comment]
Well I created a Antivirus application and neeed a firewal or dns blocker l to block malicious things. Thanks for help so maybe user need change settings manually without GUI but that's not a problem. GUI version is 3 years old.

**Comment by HydraDragonAntivirus** [comment]
Okay I fixed problem by using dnscrypt without GUI.
