### ISSUE TITLE
[Feature] Adding a "Comment" field to created rules

### ISSUE THREAD

**Issue by AquiloSpiritus** [henrypp/simplewall#1664]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.7.6

### Problem you are trying to solve

There is no option to add text information to a rule

### Suggested solution

When you open a rule, there is an additional tab or field in which you can write arbitrary text, which will be available the next time you turn on the program.

**Comment by henrypp** [comment]
done!
