### ISSUE TITLE
[Question] High disk usage at program start (part 2)

### ISSUE THREAD

**Issue by opusforlife2** [henrypp/simplewall#1665]
Hi. As described in https://github.com/henrypp/simplewall/issues/1056#issuecomment-1836883088, the setting that was suggested to be turned off to reduce disk usage doesn't seem to work.

Is there any other setting that also needs to be changed? Is high disk usage on startup normal? Simplewall almost maxes out my SSD disk usage while it is starting up.

---

App version: 3.7.6
Windows version: 10 21H2

**Comment by henrypp** [comment]
u can use logic to made decision

**Comment by henrypp** [comment]
sw doing it just for lulz

**Comment by henrypp** [comment]
@ltguillaume 
1) it only enabled hash checking for files, and nothing more, and can be translated as is.
2) not true

**Comment by henrypp** [comment]
his telling not right things (enabling hash checking is not monitor apps changes), release notes is problem that i can change soon, in changelog.md is right issue.

**Comment by henrypp** [comment]
hash checking is just reading sha256 of files,nothing more
monitor - is checking files for change and disable it (if it was enabled) if changed.

is it not simple? not remember where u read another.

**Comment by henrypp** [comment]
> Ok, and then what do you do with it? I see they're saved into the profile, but to what end, other than potentially being used for the monitor app changes feature?

u read message? i already answered "nothing more"

> Then what's the use of Check apps for sha-256 hash without using Monitor apps changing?

no, not now

> And I still don't know what Check apps for digital signatures actually does. What are the consequences if an application doesn't have a digital signature? Or what happens if the signature changed?

it check apps for digital signatures

> Or what happens if the signature changed?

nothing
