### ISSUE TITLE
[Bug] Cannot compile latest "Source code" from release

### ISSUE THREAD

**Issue by User82931** [henrypp/simplewall#1666]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.6

### Windows version

10

### Steps to reproduce

Hi, I apologise in advanced if I am doing something wrong, I spent over 2 hours trying to compile the source code from the latest "release" but no luck. I can compile the master branch no problem, but I want to compile the source code published latest "release" so I can match the hash values etc. I am using latest Visual Studio 2022.

So when trying to compile it, I get this error
![image](https://github.com/henrypp/simplewall/assets/154102091/12b2107b-116e-4142-b594-ba4f24b2a2e4)
![image](https://github.com/henrypp/simplewall/assets/154102091/82090814-b51a-46dc-8ab4-428764e9e35a)

Am I doing something wrong? 

Thank you for your time.

### Actual behavior

Error compiling

**Comment by henrypp** [comment]
its not latest, sync repository

**Comment by User82931** [comment]
But how? When I try simplewall from Oct 11, and the Routine from Oct 11, as well as the latest builder in release, trying to compile that throws errors too.

**Comment by henrypp** [comment]
`_math_createguid` changed on last week, what shit are u talking?

**Comment by User82931** [comment]
Dude I'm not talking "shit", literally all I want to be able to do is compile one of your "releases" and verify that the compiled hashes, match to what you have published, why is that so difficult to understand for you? 

The issue with your source code is you have dependencies of "routine" and "builder" which are published separately and obviously incompatible with some versions.

I managed to compile successfully this version, and downloaded routine/builder around same date
![image](https://github.com/henrypp/simplewall/assets/154102091/debda839-8d92-43a2-9441-3e39fa735d84)


But it is giving me completely different hashes to what you have published. I'm sorry not everyone is a genius like you, usually I don't have any issues compiling source code from published projects..

**Comment by User82931** [comment]
The correct sha256 hash is supposed to be
![image](https://github.com/henrypp/simplewall/assets/154102091/ea59f095-5b8a-4296-95ca-2d6842e41107)

But what I compiled gave me:
![image](https://github.com/henrypp/simplewall/assets/154102091/3f5e1ac5-76e2-47d8-aba4-4a73cafd9c01)

What am I doing wrong?

**Comment by henrypp** [comment]
> But it is giving me completely different hashes to what you have published, the simplewall.exe I compile doesn't match the hashes included. I'm sorry not everyone is a genius like you, usually I don't have any issues compiling source code from published projects..

wrong routine or win sdk why should i know?

>I'm sorry not everyone is a genius like you

where is u had seen genius?

**Comment by User82931** [comment]
Because I am just asking questions and your answers are very aggressive for no reason. If you hate people asking you questions which you find stupid you could just not answer, but you choose to spend time answering anyway not very productive time being aggressive. I just would really like your help or clear instructions for stupid people like me who do not understand how to do things properly.

I used this
![image](https://github.com/henrypp/simplewall/assets/154102091/9e8555b4-a0a2-4749-8431-e800241084a4)
![image](https://github.com/henrypp/simplewall/assets/154102091/01a35cf7-8be0-42a9-84e7-9e77ef916a93)
![image](https://github.com/henrypp/simplewall/assets/154102091/61b0d7d3-dcf4-4568-b350-4e4eb7e4a285)

I download the "source code" from these three, I extract them like this.
![image](https://github.com/henrypp/simplewall/assets/154102091/7e578bfc-aa24-4d76-88ec-027e1507a2b1)
I open visual studio 2022, and "build solution"
![image](https://github.com/henrypp/simplewall/assets/154102091/dbde7dbe-2dd3-4558-b219-b6fa9deba2f4)

It builds successfully, the log below with some "warnings"
https://pastebin.com/ECRt6cjG

Now the outcome I get is this
![image](https://github.com/henrypp/simplewall/assets/154102091/69df2924-067b-42c9-ae1d-7bd5deabdcaf)

Which is different sha256 to the exe provided in SW. Did I do something wrong? If so, could you please tell me what? Thank you.

**Comment by henrypp** [comment]
where u see agression,lol? u nevere been on the <s>babangida concert</s> street or what?

using routine 2.5.1 for building and waiting for hash match it is not idiotic for u?

ed: not any warning on compilation i not see...

**Comment by User82931** [comment]
Is not idiotic to me because my logic is, you release SW 3.7 on July 27th, so my thought process was to try routine close to that date...I tried other routine releases too but I cannot get this working.

Could you just help me please? You take your time to reply but you are not providing a solution but just mocking me for doing it wrong. Yes I am stupid, yes I am doing idotic things. Ok now that we are done with insulting me, can you just tell me what to do?

What routine version, or what exactly do I need to do so when I compile the exe, it matches the hash you provide?

**Comment by henrypp** [comment]
only now u get version 3.7 of sw u trying to compile,lol

wat u need to do i dont know and dont need it either

**Comment by User82931** [comment]
What do you mean? I literally showed you screenshot above of me downloading SW 3.7, routine 2.5.1 which were released around similar date.

I already said what I want. All I want to do, is to be able to compile one of your latest SimpleWall releases, any version past 3.7 I don't care which one, and the .exe which I get from the source code, I want its hash to match with what you provide.
![image](https://github.com/henrypp/simplewall/assets/154102091/717378c6-18e9-4687-a87d-7b0cc6348814)

How do I do that? Could you just tell me?

**Comment by User82931** [comment]
I even found an old post, which you made, saying to someone "compile the source code and you will get same hash"
![image](https://github.com/henrypp/simplewall/assets/154102091/369e7604-2401-4c56-8013-be3df284cffb)

That's all I want to do, I want to compile the source code and get same hash. How?

**Comment by User82931** [comment]
LOL ok mark me as timer waster. It's just crazy to me, you managed to reply so many times but not provided a solution once on how I can do this. Definitely doesn't make your published executable suspicious at all.

**Comment by henrypp** [comment]
> Definitely doesn't make your published executable suspicious at all.

i know it

**Comment by User82931** [comment]
I legit don't get it though, is this an ego thing? Fetish thing? You spend your time replying, you don't provide a solution, you call people who aren't as knowledgeable as you idiots and time wasters.

**Comment by henrypp** [comment]
why i need provide <s>solution</s> information how to build old version of app, it is not idiotic?

**Comment by User82931** [comment]
Because you told me it's not possible to build v.3.7.6? I tried to build v.3.7.6 and I had errors, not the original error in the start of my post but some other errors. I will try again and provide screenshots in next few mins..

**Comment by User82931** [comment]
![image](https://github.com/henrypp/simplewall/assets/154102091/714be7ce-fcfb-48bc-8c1f-5f7ea8329d65)
Here. This is SW 3.7.6 and Routine v.2.6. I get compile errors. All I want to do is to build your source code and match your SHA256. I don't care which SW version, any, just tell me how please.

**Comment by henrypp** [comment]
ohuet', git clone routine blyad', not download release

**Comment by User82931** [comment]
Ok well you win I see I will not get help.

Thank you for your project and your time.

**Comment by User82931** [comment]
> ohuet', git clone routine blyad', not download release

Cloned routine, SW v3.7.6 source code from release
![image](https://github.com/henrypp/simplewall/assets/154102091/d61440b0-21ba-4d4c-985d-4249949c3b6f)

**Comment by User82931** [comment]
Thank you that worked to compile, however my sha256 hash is different. What I do wrong? How fix?
![Uploading image.png…]()

Build log: https://pastebin.com/0TrkDxw3

**Comment by henrypp** [comment]
mb u use wrong sw src code, not in release but commits in <s>sw</s> this repo some later as release time

**Comment by User82931** [comment]
I use this
![image](https://github.com/henrypp/simplewall/assets/154102091/5b463427-11f1-405e-9731-ef49f3f774d4)

Is this wrong?

**Comment by henrypp** [comment]
not from release, second or first commit after release idk (same as routine)

**Comment by User82931** [comment]
Are you saying the hashes from "simplewall-3.7.6.sha256" are not for the "source code" found in my screenshot but for second or first commit after release? Why?

I also tried compiling SW [v.3.7.5] with routine c5f13d6c989a719842687576c733ea6cf89d925b and I get different sha256 to the sha256 for SW 3.7.5 too.

**Comment by User82931** [comment]
Tried first three commits after SW 3.7.6 release but still mismatching sha256
![image](https://github.com/henrypp/simplewall/assets/154102091/313d442c-307b-4925-8586-1cdd4538bd68)

112aedac053112a50fbe8800998b54735ea7df62 was same sha256 as 48457bc917ef3568b8ec90e7abfaa6764d7a6d2b

**Comment by henrypp** [comment]
try later routine, i really dont remeber what src i compiled [and it do not worries me]

**Comment by User82931** [comment]
Tried, later or earlier versions of routine give compiler errors, only 86a26fdef18c0a19e37d9382a7d76ca03c23e987 works to actually compile.

Well it's okay, if you don't remember and have no further suggestions it's fine. Thanks.
