### ISSUE TITLE
[Feature] A new tab to help find applications which need internet access

### ISSUE THREAD

**Issue by p-groarke** [henrypp/simplewall#1671]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.7.6

### Problem you are trying to solve

I always find it very difficult to find what to enable connections too when using either UWP apps or builtin Windows features (like printing / scanning for example). I currently use the Connections tab to try and figure out what needs enabling, but that rarely works.

The only solution is disabling filters completely, which is unsecure and tedious. For example, when I need to scan a document, I simple disable all filters, do my scans, re-enable filters.

### Suggested solution

A new tab to help us discover what needs internet access. This tab would :

- List 1 entry per exe, unlike "Connections" which has 1 entry per connection.
- List exes by order of last attempted connection.
- Keep exes in the list for longer, giving us time to see what tried to connect.
- Have some sort of right click > Create rule... , just like Connections, so we can enable connections.
- Apps, services and UWP apps would be mixed together, not in separate groups.

I think this is one approach to help, thank you!

**Comment by henrypp** [comment]
notification not working or wtf?

**Comment by p-groarke** [comment]
hmmm? Is everything alright buddy? I'm not sure but you sound angry about the feature request. If true, you can disable issue pages in your repo settings. That way you wont receive feedback :)

Anyways, happy holidays!

**Comment by henrypp** [comment]
i dont understand why needed new tab to find apps who need access, it is completely useless & unneeded, because there is already have notification/log feature.

aga,u too
