### ISSUE TITLE
Panic button[Feature]

### ISSUE THREAD

**Issue by Onair-santa** [henrypp/simplewall#1672]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.7.4

### Problem you are trying to solve

We really need a big Panic button to shut down the entire network with one click

### Suggested solution

One button in menu and in app

**Comment by idwowrack** [comment]
Is this button execute the powershell command > Get-Process -Name simplewall | Stop-Process && Start-Process -FilePath "C:\Program Files\simplewall\simplewall.exe" ?

**Comment by Onair-santa** [comment]
![image](https://github.com/henrypp/simplewall/assets/42511409/d8fbda2e-68a9-4dbe-89af-1aae9c8843bb)
Need in toppanel and in context menu
Off all internet

**Comment by HeresJonny** [comment]
Or you could add a shortcut in Windows to disable your network adapter...

**Comment by Onair-santa** [comment]
Yes
netsh interface set interface "Ethernet" disable
