### ISSUE TITLE
[Feature] Categories within Apps with internet access 

### ISSUE THREAD

**Issue by mad-ben** [henrypp/simplewall#1673]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.7.6

### Problem you are trying to solve

I have Bitdefender antivirus installed, and I have like 10 exe files and other executables to allow antivirus to scan for updates and internet connections and files. So my section for apps with enabled internet access looks very cluttered. I attached image as well.

![antivirus](https://github.com/henrypp/simplewall/assets/53571019/23f37230-a578-4b93-84d0-f6efa69bbfb2)

So If possible I would like to be able to create categories inside apps with internet access and separate/collapse these sections. 

Thank you.

### Suggested solution

Create sections with possibility of collapsing and naming them.

### Screenshots / Drawings / Technical details

Same UI style but nested inside apps with internet access.

**Comment by henrypp** [comment]
> I have used the search function to see if someone else has already submitted the same feature request.

lol, #1671
