### ISSUE TITLE
Multiple Local IP's break rules

### ISSUE THREAD

**Issue by GY8VSdYYzvL8-K6T** [henrypp/simplewall#1674]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.6

### Windows version

11

### Steps to reproduce

Scenario A:
1. Block all inbound and outbound traffic in "Settings>Rules"
2. In a single rule allow outbound traffic for App.exe from 1 specific local IP, such as real adapter local IP

Scenario A Outcome: 
- App.exe can make outbound connections from local IP specified within the rule

Scenario B:
1. Block all inbound and outbound traffic in "Settings>Rules"
2. In a single rule allow outbound traffic for App.exe from 2 specific local IP's on different subnets, such as real adapter local IP and VPN adapter local IP

Scenario B Outcome: 
- App.exe canNOT make outbound connections from any local IP's specified within the rule

### Expected behavior

Scenario B should result in App.exe being able to make outbound connections from either of the specified local IP's specified in the rule.

### Actual behavior

Scenario B results in App.exe NOT being able to make outbound connections from any of the specified local IP's specified in the rule.

**Comment by henrypp** [comment]
not understanding, complete
