### ISSUE TITLE
[Bug]Installed a program, wasn't blocked by default

### ISSUE THREAD

**Issue by RChadwick7** [henrypp/simplewall#1676]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.5

### Windows version

Windows 10 Enterprise

### Steps to reproduce

1. Install Creality Print
2. See that Creality Print has full network access.

### Expected behavior

I expected that, once I installed the Creality Print  application, it would block all network access by default and give me a chance to unblock it if needed

### Actual behavior

The newly installed application had full Internet access. I couldn't find the program in any of the lists. Trying to block it blocked my web browser and now I have to turn the firewall off to browse the web.

**Comment by henrypp** [comment]
and wtf is happened wit u u lefr on me?

**Comment by RChadwick7** [comment]
I don't understand.

**Comment by RChadwick7** [comment]
Since Simplewall website is down, does your response mean Simplewall is dead?

**Comment by henrypp** [comment]
dont understand ur logic!

"website is down it is means project is dead", idiotic

**Comment by RChadwick7** [comment]
I don't understand what you were trying to say when you responded to me. I installed a program, it wasn't blocked by default, I couldn't block it. If you're not making a working firewall anymore, why bother answering me with nonsense?

**Comment by henrypp** [comment]
u already described this in topic

and what? **u tink there is telepaths????????**
