### ISSUE TITLE
[Bug] No notifications from Simplewall

### ISSUE THREAD

**Issue by irondave** [henrypp/simplewall#1680]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.6

### Windows version

64-bit

### Steps to reproduce

Fresh installation of Simplewall, filters enabled, start an application that connect to the internet (es: Firefox), Simplewall doesn't notify about the new connection enstablished.
As result the application cannot connect to the internet and I have to search it into the "connection" page and enable it.

### Expected behavior

I expect an immediate response from Simplewall with a notification when an application or service tries to connect to the Internet.

### Actual behavior

No notifications when an application or service tries to connect to the Internet.

**Comment by henrypp** [comment]
any error code? see in log

**Comment by irondave** [comment]
No error codes beside this one when Simplewall starts:
![Senza titolo2](https://github.com/henrypp/simplewall/assets/8292014/3bd2d7cf-9f59-4889-ab7d-66eefd936216)

When I try to open the log I receive this error:
![Senza titolo](https://github.com/henrypp/simplewall/assets/8292014/9e0d5fc1-e576-480b-80b9-76917a716b4a)

Sorry for the italian part into the screenshot, it stays in italian althought I set the english language.
In english it would be: "The object path component was not a directory object."

Thank you for your help and patience.

**Comment by henrypp** [comment]
try to restart comuter,it is not a simplewall problem

**Comment by irondave** [comment]
Already did several times

**Comment by henrypp** [comment]
i trying to tell u: wfp (log subscribe) function in winapi did not return this error code at all (in msdn even docs has no winows error codes, only wfp/rpc), only ur windows configuration respond for this error...

**Comment by rudolphos** [comment]
I had a similar problem on W10: https://github.com/henrypp/simplewall/issues/1585

**Comment by henrypp** [comment]
@rudolphos and author, please check how it works in 3.8.2?
