### ISSUE TITLE
[Feature] Block by domain names instead of IP ranges

### ISSUE THREAD

**Issue by merklijm** [henrypp/simplewall#1681]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.7.6

### Problem you are trying to solve

I think it would be interesting to block by domain names, this would avoid having to enter many address ranges for a number of them. 
Thank you for your job.

### Suggested solution

Ability to enter domain name in the rules

### Screenshots / Drawings / Technical details

![Image1](https://github.com/henrypp/simplewall/assets/10416882/5808ea3d-060c-47dc-817d-157f77d1d35c)

**Comment by henrypp** [comment]
use dnscrypt proxy for this
