### ISSUE TITLE
[Question]crashes

### ISSUE THREAD

**Issue by Evertonlps** [henrypp/simplewall#1683]
Describe the question with as much detail as possible.

Nas versões acima de 3.7.5 tenho tido Pequenos travamentos quando notifica conexão de novos aplicativos e na inicialização/boot  e também noto isso assim que abro pela primeira vêz após instalar, então permaneço na 3.7.5 ou 3.7.2(melhor para mim) por isso, será algo no computador?
---
In versions above 3.7.5 I have had small crashes when notifying the connection of new applications and at startup/boot and I also notice this as soon as I open it for the first time after installing, so I stay on 3.7.5 or 3.7.2(best for me), is it something on the computer?
App version: <3.7.5~3.7.6>
Windows version: <10 20H2 and 22H2>

**Comment by henrypp** [comment]
crash dump?

**Comment by Evertonlps** [comment]
> crash dump?
Also, but I think I should have used another word, but I'm not sure how to say it in English and translators aren't that good, but I would say that when opening or when a blocked app notification appears, the PC freezes quickly, the pointer of the mouse, if it is being used on the monento, it also freezes quickly in new versions and I'm not sure what it could be.
3.7.2 has always worked well, after updates I have either strange crashes or freezes or the rules/profile when restarted are erased or reset, I forgot to mention that.
`I'm sorry, if you can't understand that's okay, I'll solve it by going back to 3.7.2 - Speaking through a translator doesn't always work lol`

**Comment by Evertonlps** [comment]
Thank you, 3.7.7 improved everything, thank you for the good work, I don't use antivirus, just Simplewall or another similar firewall so it's very important for me.
