### ISSUE TITLE
[Bug] 3.7.7 Portable Update Server connection error.

### ISSUE THREAD

**Issue by 0lm** [henrypp/simplewall#1688]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.7

### Windows version

Windows 10 64bit

### Steps to reproduce

1. Download simplewall 3.7.7 portable.
2. Start Update
3. Language Pack 04.01.2024 is found
4. Click "yes", but it will give update server connection error: status 1073741738 (0xc0000056)

### Expected behavior

Working Updates

### Actual behavior

I am sorry in advance if this issue is related to only me and not for general. But since I tried it on different devices at home, it didn't work anywhere. I remember the languge pack before this newest one worked and it could be installed. But since portable v3.7.7, I don't seem to be able to update the language pack anymore.

**Comment by henrypp** [comment]
installer/portable version binaries are the same, so it fixed (check last version), i think, if not - reply
