### ISSUE TITLE
Simplewall makes microphone stop working.

### ISSUE THREAD

**Issue by Zeguim** [henrypp/simplewall#1689]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.7

### Windows version

Windows 10 Pro 22H2 OS Build 19045.3693

### Steps to reproduce

I'm not sure how to reproduce it. I just updated and was greeted with this problem.

### Expected behavior

I updated from 3.7.6, to finally get rid of the high cpu usage (hopefully) but then I was greeted with a few system freezes and my microphone stops working, making me having to reboot the computer for it to happen again. And yes I tried opening mmsys.cpl to check if I was jut muted there but no. I checked everything and it was everything normal but the mic just didn't work

### Actual behavior

I also had an error before simplewall crashed (it always crashes. It happens like this. I reboot my pc, the mic comes back to life and it works; simplewall launches, my pc freezes a bit and then no more microphone; a bit later, I receive this:

The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

Status: -1073741819 (0xC0000005)

### Logs

Sorry. I didn't save the dump and I already went back to the 3.7.6. When I have time I'll update to 3.7.7 and I'll come back here to drop the crash dump and debug log if I find it

**Comment by henrypp** [comment]
it is crashing or ur microfon not working? it, as i see, another idiotic issue

**Comment by Zeguim** [comment]
> it is crashing or ur microfon not working? it, as i see, another idiotic issue

Both. First it make the microphone stops then it crashes and the microphone continues to not work until the reboot

**Comment by henrypp** [comment]
u can see on older issue, it crashed and it was fixed, and download link for fixed binary there,u can only search/list 2-3 before this

**Comment by henrypp** [comment]
and sw did not interfere with mic, at all
