### ISSUE TITLE
Use not only IP addresses for filtering, but also URL addresses

### ISSUE THREAD

**Issue by RWDZ** [henrypp/simplewall#1691]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.7.7

### Problem you are trying to solve

They suggest adding the ability to filter not only based on IP addresses, but also URL based on DNS addresses.
I mean possibility to use address like "facebook.com" instead of "31.13.72.36".
This is need because some servers with the same URL can change IP time to time.

### Suggested solution

1. Need to add additional field URL. When URL field is filled, IP filed should be updated.
2. simplewall should check at start all used URL.
3. It would also be ideal for simplewall to monitor all system requests for DNS data updates and automatically update the URL-IP correspondence.

**Comment by henrypp** [comment]
u dont know what is dnscrypt proxy?

**Comment by RWDZ** [comment]
dnscrypt proxy is optional feature, witch is not used bu default.

**Comment by henrypp** [comment]
same as ur requirements
