### ISSUE TITLE
[Bug] Memory Issue

### ISSUE THREAD

**Issue by contracourse** [henrypp/simplewall#1692]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.7

### Windows version

Windows 10 64bit

### Steps to reproduce

After updating to Version 3.7.7 my Simplewall app unexpectedly crashed. 

### Actual behavior

Application Exists 

### Logs

The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

Status: -1073741819 (0xC0000005)

**Comment by henrypp** [comment]
#1686
