### ISSUE TITLE
[Bug] Not showing up in the tray when minimized. 

### ISSUE THREAD

**Issue by Xelbayria** [henrypp/simplewall#1695]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.7

### Windows version

10-2H22

### Steps to reproduce

1. Just run the portable executable of Simplewall
2. wait for it to finish loading and fully running. 
3. Check your tray to see the icon: 
![Simpewall-issue](https://github.com/henrypp/simplewall/assets/12866666/f2b67ed6-06aa-45a0-8508-a278381eba9b)

### Expected behavior

I expected the icon of Simplewall to show up in the tray. 

### Actual behavior

The icon of Simplewall doesn't show up in Tray (I've confirmed Simplewall is fully running).  The issue also exists in **v3.7.6**. I had to downgrade to **v3.7.5** where it's working. 

the version of Simplewall is portable from `simplewall-3.7.7-bin.zip`. I cleaned out the profile and setting data to see if that fixed the issue and nope!

### Logs

n/a

**Comment by henrypp** [comment]
what shitted OS u using which did not display tray?

i tested all versions on vanilla Windows builds and never tray icon did not displayed.

try reset tray icon cache by run this:

[reset_explorer_tray.zip](https://github.com/henrypp/simplewall/files/13895242/reset_explorer_tray.zip)

**Comment by Xelbayria** [comment]
> what shitted OS u using which did not display tray?
> 
> i tested all versions on vanilla Windows builds and never tray icon did not displayed.
> 
> try reset tray icon cache by run this and recheck:
> 
> [reset_explorer_tray.zip](https://github.com/henrypp/simplewall/files/13895242/reset_explorer_tray.zip)

`reset_explorer_tray` fixed it. what was the cause? if you don't mind explain in more detail?

**Comment by henrypp** [comment]
idk

**Comment by Xelbayria** [comment]
dang! no worries.

**Comment by tsmr77** [comment]
Thanks for the Fix Mister.

**Comment by codeXXjs** [comment]
> > > what shitted OS u using which did not display tray?
> > > i tested all versions on vanilla Windows builds and never tray icon did not displayed.
> > > try reset tray icon cache by run this and recheck:
> > > [reset_explorer_tray.zip](https://github.com/henrypp/simplewall/files/13895242/reset_explorer_tray.zip)
> > 
> > 
> > `reset_explorer_tray` fixed it. what was the cause? if you don't mind explain in more detail?
> 
> The cause is Windows.
> 
> Windows stores Icon information in the Registry. But if you change the path of an existing icon, then it will get confused, for whatever reason. And changing pathes often can happen with portable versions of a software.
> 
> Example:
> 
> You are using Simplewall 3.7.7 portable and the folder SW is in, is called, lets say, "sw377"
> 
> Now you update it and it turns to v3.7.8. And if you rename the folder name, i.e. "sw378", then Windows will stop displaying the icon in the taskbar menu, because the icon is still the same, but the path changed. For some reason, it doesn't refresh its icon memory. So, in other words, Windows burned it into its memory, that the icon for simplewall is connected to the folder "sw377". But the moment you change names and stuff, the Icon won't be displayed anymore unless you delete some registry files. - (at least, that's how this "icon missing" issue happened to me)
> 
> Computer\HKEY_CURRENT_USER\SOFTWARE\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\TrayNotify
> 
> That's the Registry path where the Icon information are stored. By manually deleting "IconStreams" and "PastIconsStream" and then restarting explorer.exe you can solve the problem, too. I just checked the "reset_explorer_tray.bat" - it is doing the same what described.

Thanks for the elaborate respond. I also faced the same issue and now I know why

**Comment by RH-BD** [comment]
I just tried with the method explained at #1695 (I downloaded the zip file and run the bat file) but didn't work! I again had to close all the process in the task manager and then reopen simple wall...

**Comment by codeXXjs** [comment]
> I just tried with the method explained at #1695 (I downloaded the zip file and run the bat file) but didn't work! I again had to close all the process in the task manager and then reopen simple wall...

After one or two tries after running the reset explorer bat file it should fix it. You will have no issues moving forward.

**Comment by notsyncing12309** [comment]
I have the same problem, but I didn't use debloater. I tried to solve it by clearing the tray cache via a bat file, but it still doesn't work.
