### ISSUE TITLE
[Bug] Missing tooltip for "ignore" button on popup

### ISSUE THREAD

**Issue by crash5** [henrypp/simplewall#1696]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.7

### Windows version

Windows 11

### Steps to reproduce

When popup enabled, all buttons has tooltip on mouse hover except the right most one which "ignores/closes" the popup.

### Expected behavior

A tooltip appears with the function of the button

### Actual behavior

Nothing appears.

**Comment by marcello-pietrobon** [comment]
What a coincidence, I came here exactly because I wanted to open a new issue about this.

Well, at least now I know what that buttons does.
