### ISSUE TITLE
Crash dump on update [Bug]

### ISSUE THREAD

**Issue by nickisghosty** [henrypp/simplewall#1699]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.7

### Windows version

11 23H2

### Steps to reproduce

Click update when there was an update available. 

### Expected behavior

Update.

### Actual behavior

Crashed and not sure if it actually updated?

### Logs

I have a crash dump that was generated 
[simplewall-1705225491.dmp](https://github.com/henrypp/simplewall/files/13930973/simplewall-1705225491.dmp)
[simplewall-1705225492.dmp](https://github.com/henrypp/simplewall/files/13930974/simplewall-1705225492.dmp)

**Comment by NixonSchool** [comment]
[simplewall-1705407532.dmp](https://github.com/henrypp/simplewall/files/13949779/simplewall-1705407532.dmp)
[simplewall-1705407720.dmp](https://github.com/henrypp/simplewall/files/13949780/simplewall-1705407720.dmp)
[simplewall-1705407746.dmp](https://github.com/henrypp/simplewall/files/13949781/simplewall-1705407746.dmp)
16th january 2024 dumps

**Comment by henrypp** [comment]
> [simplewall-1705407532.dmp](https://github.com/henrypp/simplewall/files/13949779/simplewall-1705407532.dmp)
> [simplewall-1705407720.dmp](https://github.com/henrypp/simplewall/files/13949780/simplewall-1705407720.dmp)
> [simplewall-1705407746.dmp](https://github.com/henrypp/simplewall/files/13949781/simplewall-1705407746.dmp)
> 16th january 2024 dumps

it was fixed already #1686
