### ISSUE TITLE
FTP Error

### ISSUE THREAD

**Issue by pm0123** [henrypp/simplewall#1701]
Whilst trying to FTP using windows file explorer the following error is received after entering correct credentials. No error is received if simplewall is disabled 

FTP Folder Error
An error occurred opening that folder on the FTP Server.  Make sure you have permission to access that folder.
Details:
An internal error occurred in the Microsoft Internet extensions.

FTP has been enabled.

Any ideas what may be the issue

Many thanks 

---

App version: 3.7.7
Windows version: 11

**Comment by henrypp** [comment]
u cant create rule for ftp port? or look at log (what is trying to inet)?

**Comment by pm0123** [comment]
Hi. We have selected FTP service from user rules. But no luck. We receive the error mentioned. Any ideas on if anything else needs to be enabled?

Many thanks

**Comment by henrypp** [comment]
![sshot-001](https://github.com/henrypp/simplewall/assets/3902025/ebe575f8-1c01-44b1-95a5-95e902073999) here is ALL information can u help, no other variants

**Comment by pm0123** [comment]
Many thanks

Is it svchost.exe or explorer.exe? We are trying to FTP from Windows file explorer.

We have tried just setting to a custom rule with remote port 20-21 and host as "any" and direction as any.

We have selected FTP service from user rules also.

Have you seen this message before 

FTP Folder Error
An error occurred opening that folder on the FTP Server. Make sure you have permission to access that folder.
Details:
An internal error occurred in the Microsoft Internet extensions.

**Comment by henrypp** [comment]
> Is it svchost.exe or explorer.exe?

ALL IN LOG

**Comment by pm0123** [comment]
Many thanks and understood, but for FTP surely we would be port dependant rather than process dependent eg. If we select port 20-21 on the FTP setting in simplewall it will apply to all processes. Unless I am mistaken. So I am missing something else to set?

Also just to say your app is excellent 👌

**Comment by henrypp** [comment]
it will apply to selected apps or ALL apps, all in rule config

**Comment by pm0123** [comment]
Correct. So it has FTP selected in user rules applying to all apps. Please advise what else I am missing to cause the error or is it a bug?

Many thanks

**Comment by pm0123** [comment]
Please can you advise if in rules you can specify hostname rather than ip. If we put hostname it comes as syntax error.

Many thanks

**Comment by henrypp** [comment]
bcs, it is not domain resolution toolkit, use dnscrypt for crist sake
