### ISSUE TITLE
Does enabling rules on the "Blocklist" (and "System rules and "User rules") enable blocking or enable the connection...? 

### ISSUE THREAD

**Issue by zdat** [henrypp/simplewall#1702]
I have every rule enabled on the blocklist. I assume this means all the rules are active and are blocking... but now I'm not so sure...?

**Comment by Piehthyte** [comment]
Click on any rule to view its details. If the "Action" is set to "Block" and the "Enable Rule" option is checked, the rule is active and blocking.
![Here's an example of the details window of an enabled rule that is set to block any connections wanting to be made outbound](https://github.com/henrypp/simplewall/assets/5201076/7c58a769-a575-408e-9b4a-db37b5cfc533)
If you want an easy way without having to go into each and every rules details, Identify blocking rules by the red ![**RED**](https://github.com/henrypp/simplewall/assets/5201076/b1514dad-0c0c-4fff-949b-7cc47ac81762) sign and allow rules by the green ![**GREEN**](https://github.com/henrypp/simplewall/assets/5201076/36cb4487-5363-42c9-9477-5fc43bef0ee9) checkmark.
