### ISSUE TITLE
Crash in the Connections tab[Bug]

### ISSUE THREAD

**Issue by AleWiccan** [henrypp/simplewall#1703]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.7

### Windows version

Windows 10 21H2

### Steps to reproduce

I open the Connections tab and within seconds it crashes

### Expected behavior

It shouldn't crash on that tab

### Actual behavior

After a few seconds on the tab, the application crashes:

La instrucción en 0x%p hace referencia a la memoria en 0x%p. La memoria no se pudo %s.

Status: -1073741819 (0xC0000005)

### Logs

[simplewall-1705671940.dmp](https://github.com/henrypp/simplewall/files/13989767/simplewall-1705671940.dmp)
[simplewall-1705670572.dmp](https://github.com/henrypp/simplewall/files/13989768/simplewall-1705670572.dmp)
[simplewall-1705671562.dmp](https://github.com/henrypp/simplewall/files/13989769/simplewall-1705671562.dmp)
/

**Comment by henrypp** [comment]
https://github.com/henrypp/simplewall/issues/1686#issuecomment-1880805690
