### ISSUE TITLE
[Question] Is simplewall protected from malware silently changing its rules?

### ISSUE THREAD

**Issue by dr04e606** [henrypp/simplewall#1706]
Ever since watching [this video](https://www.youtube.com/watch?v=UfaRLUZK8No), I've been trying not to use Windows Firewall on any of my systems. 
I know that I shouldn't have any malware on my system in the first place, let alone the one that silently changes Windows Firewall rules, but, anything can happen and it's quite scary how easy it is to silently add a rule to Windows Firewall with a simple `netsh advfirewall` command execution...

I saw [the explanation](https://github.com/henrypp/simplewall?tab=readme-ov-file#nota-bene) in the README, but I'm not sure if I understood it correctly, so a clarification would be greatly appreciated.

**Comment by agiz10** [comment]
Afaik as long as you have UAC enabled (and did not run anything elevated) or are not local administrator, such commands are not able to change firewall settings (or WFP settings).

**Comment by dr04e606** [comment]
> Afaik as long as you have UAC enabled (and did not run anything elevated) or are not local administrator, such commands are not able to change firewall settings (or WFP settings).

My UAC settings are set to default (_Notify me only when programs try to make changes to my computer_). 
My user account is a member of the "Administrators" user-group.

**Comment by dr04e606** [comment]
The least privilege principle has its perks, no doubt about it. 
Still, I'm curious – does simplewall have anything like MWFC to keep its rule set safe from being tampered with?

![image](https://github.com/henrypp/simplewall/assets/52504986/2f54adbb-fd6f-44af-8586-3b74e6cdec7a)

**Comment by henrypp** [comment]
>  Still, I'm curious – does simplewall have anything like MWFC to keep its rule set safe from being tampered with?

**Comment by henrypp** [comment]
@dr04e606
>  Still, I'm curious – does simplewall have anything like MWFC to keep its rule set safe from being tampered with?

already have, before 3.7 it has a option for this, but starting with 3.8 it was removed and enabled by defautlt

**Comment by dr04e606** [comment]
> already have, before 3.7 it has a option for this

Do you mean this option? 
[Settings -> Profile type -> Encrypted]
![image](https://github.com/henrypp/simplewall/assets/52504986/6f53da43-449b-4e63-be3f-22e7c0f15a76)

**Comment by henrypp** [comment]
no

**Comment by henrypp** [comment]
it means profile.xml is encrypted, i think it is obvious
