### ISSUE TITLE
[Bug] No Tray Icon

### ISSUE THREAD

**Issue by tsmr77** [henrypp/simplewall#1708]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.7

### Windows version

10

### Steps to reproduce

Simple Problem

### Actual behavior

I have no Tray Icon since the last Update.
i've installed the setup.exe -> No Icon
Portable also.
But my Task Manager says it runs...

**Comment by henrypp** [comment]
#1695
