### ISSUE TITLE
[Bug] When I enter the menu(connections).. Status: -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by oklokl** [henrypp/simplewall#1711]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.7

### Windows version

windows11 [Version 10.0.22631.3007] korea

### Steps to reproduce

I press the menu(connections) and this error appears afterwards.
<img width="937" alt="1" src="https://github.com/henrypp/simplewall/assets/1571600/228ec8d0-98d6-49ee-a798-c0f5d1eca053">
<img width="266" alt="2" src="https://github.com/henrypp/simplewall/assets/1571600/b8091879-c0d4-4473-8e42-641ba4f459dd">

The command in 0x%p referenced memory in 0x%p. Memory cannot be %s.

Status: -1073741819 (0xC0000005)

### Expected behavior

The program(simplewall ) will be terminated.

### Actual behavior

Bugs occur after menu(connections) selection.

### Logs

[simplewall-1706291336.dmp](https://github.com/henrypp/simplewall/files/14067925/simplewall-1706291336.dmp)
[simplewall-1706181208.dmp](https://github.com/henrypp/simplewall/files/14067927/simplewall-1706181208.dmp)

**Comment by henrypp** [comment]
#1686

**Comment by Kolesan666** [comment]
bump
the same bug win 11

**Comment by henrypp** [comment]
@Kolesan666 that is not  3.8.7 here, and no dump attached
