### ISSUE TITLE
[Installer Bug] Installer opens simplewall by default, even though on last page there is a checkbox asking if it should be launched.

### ISSUE THREAD

**Issue by gettysburg** [henrypp/simplewall#1714]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.8

### Windows version

Version 23H2 (OS Build 22631.3085)

### Steps to reproduce

1.) Run `simplewall-3.7.8-setup.exe`
2.) Install the application.

In the installation log, you will see that the installer automatically launches the extracted binary:

![image](https://github.com/henrypp/simplewall/assets/2256003/2059f402-ae56-4612-976e-76a90e3f6851)

Then, on next page, you are asked if you want to run simplewall (again):

![image](https://github.com/henrypp/simplewall/assets/2256003/2cbf232d-61e1-4857-b5fa-c32319bb0b1b)

### Expected behavior

Installer should not auto-launch extracted .exe, but wait for user input on next page of installer.

### Actual behavior

Binary is launched always.

**Comment by henrypp** [comment]
ok, fixed
