### ISSUE TITLE
[Bug] App unrecognized by Microsoft Defender SmartScreen since v3.7.6

### ISSUE THREAD

**Issue by tagatac** [henrypp/simplewall#1717]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.7.8

### Windows version

11

### Steps to reproduce

1. Download https://github.com/henrypp/simplewall/releases/download/v.3.7.8/simplewall-3.7.8-setup.exe to the desktop.
2. Double-click the executable to run it.
3. Observe the Microsoft Defender SmartScreen warning.

### Expected behavior

A warning pops up that the app isn't Microsoft-verified:
![Screenshot 2024-02-03 044459](https://github.com/henrypp/simplewall/assets/1304425/9cbe0a05-60ea-45c3-bc80-c96bbe0f6e6e)

This was the behavior for releases prior to v3.7.6.

### Actual behavior

A warning pops up that the app is unrecognized:
![Screenshot 2024-02-03 043436](https://github.com/henrypp/simplewall/assets/1304425/e78c6c37-c489-4147-9499-ebd9efb5adef)

**Comment by henrypp** [comment]
dont care

**Comment by tagatac** [comment]
I've submitted the setup file for analysis by Microsoft per [this guide](https://learn.microsoft.com/en-us/microsoft-365/security/intelligence/submission-guide). Submission details are [here](https://www.microsoft.com/en-us/wdsi/submission/c5d0fdee-9671-424e-9873-5888e5aeb34f) (need to be logged in to a Microsoft account as myself or sforce5@mail.ru to view).

**Comment by henrypp** [comment]
anyway, [no one is detected](https://www.virustotal.com/gui/file/602962ba85a6d0af7ac5834473727b4a729b113e2a1f78251f7bac3cf68a0576/detection) as MW

**Comment by umarbutler** [comment]
I get the same warning as well with v3.7.8. VirusTotal says three vendors and one sandbox flag the installer as malicious: https://www.virustotal.com/gui/file/8f7e18c3f65dd2727e3bbb083832d232279a7dcb5b637d47ab653718260ce431

**Comment by tagatac** [comment]
Ugh. The submission to Microsoft timed out 🤦‍♂️
> Failed to process within SLA. If processing is still needed, please resubmit the submission.

I've resubmitted and shared access with @umarbutler: https://www.microsoft.com/en-us/wdsi/submission/a4a80fdd-8b50-4b38-b6ba-c2d779f3bad8

**Comment by henrypp** [comment]
this idiots can't solve [problem](https://github.com/HavenDV/H.NotifyIcon/issues/82) for more than 2 years in his system, and you expect <s>M$</s> them to respond?

**Comment by henrypp** [comment]
another lulz:

how he's <s>ai</s> Васян made a work
![sshot-004](https://github.com/henrypp/simplewall/assets/3902025/78acf370-3255-485b-89b8-0c76806352d0)

i just changed location in DOM of the <s>M$</s>
