### ISSUE TITLE
[Question] How do I find out which filter or setting in SimpleWall is blocking telegram?

### ISSUE THREAD

**Issue by marcello-pietrobon** [henrypp/simplewall#1718]
I updated telegram today, like many other times, but this time telegram is not loading data unless I disable filters in SimpleWall, then telegram immediately works

I uninstalled telegram and reinstalled telegram and this time SimpleWall sees the change and I press Allow to let internet access to it. Yet, telegram still seems to be blocked from internet and is not loading data.

I didn't change anything else on SimpleWall beside enabling telegram.
On the Packets log I don't see anything appearing in the few minutes after I start telegram.

How can I best find out which filter or setting in SimpleWall is now blocking telegram?

---

SimpleWall version: 3.7.8 64-bit
Windows version: Windows 10 Pro 22H2 19045.3693 (on desktop)

**Comment by henrypp** [comment]
dropped packets log have everything u want
![sshot-002](https://github.com/henrypp/simplewall/assets/3902025/b9426b6a-a7c4-4717-a9e9-b0e397a33425)

**Comment by marcello-pietrobon** [comment]
Thank you, I see now the problem I had was a different firewall that somehow I thought to have fixed already.
