### ISSUE TITLE
Timers rules added on popups do not take effect

### ISSUE THREAD

**Issue by LazyZhu** [henrypp/simplewall#172]
simplewall 2.2.5 х64
Windows 10

Timers rules added on popups do not take effect.

**Comment by pwn0r** [comment]
same on 2.2.6 -- only manually enabling apps in simplewall UI works. The apps get added to the allowed list but for whatever reason still get blocked on outbound connections (I use simplewall in whitelist mode).

**Comment by henrypp** [comment]
check 2.2.7
