### ISSUE TITLE
googledrivefs.exe always asking again after every update? [Question]

### ISSUE THREAD

**Issue by jan-the-maker** [henrypp/simplewall#1721]
Hello,

wanted to ask if it is normal, that simplewall is always asking again for googledrivefs.exe (the official google drive client for windows) after every update. I know that the google drive client updates in the background silently. Is there a way to set this "permanently" without the need to set policies for each version again? It gets a little annoying.

---

App version: 3.7.8
Windows version: Win11

**Comment by xMisio72** [comment]
I google and wanted to ask the same question here:
Is it possible to tell SimpleWall to always allow a program, regardless of the version?

**Comment by porter9992** [comment]
Since it wasn't clear I'll mention, the different versions are the issue is Google changes the path to the .exe everytime.  They do the same with Google Chrome too.  I had this type of issue with Tinywall too.

**Comment by jan-the-maker** [comment]
> Since it wasn't clear I'll mention, the different versions are the issue is Google changes the path to the .exe everytime. They do the same with Google Chrome too. I had this type of issue with Tinywall too.

Ah ok, i already suspected this. Is there a way to solve this by some kind of rule setting (path + x)? Just asking else we have to live with it ...

**Comment by herrenP** [comment]
Hopefully devs implement #1727 to mitigate this.

**Comment by henrypp** [comment]
asking what?"

**Comment by henrypp** [comment]
#1729
