### ISSUE TITLE
0xC0000005 error de referencia a la memoria

### ISSUE THREAD

**Issue by FlashLight99** [henrypp/simplewall#1724]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

cualquiera 

### Windows version

22h2 win10pro 2023

### Steps to reproduce

![Uploading photo_2024-02-15_04-01-20.jpg…]()

### Expected behavior

![Uploading photo_2024-02-15_04-01-20.jpg…]()

### Actual behavior

![Uploading photo_2024-02-15_04-01-20.jpg…]()

### Logs

![Uploading photo_2024-02-15_04-01-20.jpg…]()

como puedo corregir este error

**Comment by henrypp** [comment]
and crash dump?

**Comment by henrypp** [comment]
and use latest version?

**Comment by henrypp** [comment]
@Misaria and use latest version?

**Comment by Misaria** [comment]
@henrypp It's 3.7 Release - 64bit.
The update that is available (that seemingly downloads then asks to be installed but isn't) is 3.7.8.

**Comment by FlashLight99** [comment]
ojala tenga solucion esto ya que es el mejor cortafuegos de todo el mercado es el mejor donde vivo no puedo hacer donacion pero encantado de la vida apoyo el proyecto al 500000%
saludos desde CUBA
