### ISSUE TITLE
User rules with hosts/domains cause error: DnsQuery() failed

### ISSUE THREAD

**Issue by LazyZhu** [henrypp/simplewall#173]
simplewall 2.2.5 х64
Windows 10

User rules with hosts/domains cause error: 
`DnsQuery() failed with error code 0x000005b4`

**Comment by henrypp** [comment]
you, obviously, restricted internet access for simplewall.exe

**Comment by LazyZhu** [comment]
No, simplewall has full access to the internet.

**Comment by henrypp** [comment]
So error code `0x000005b4` is tell me, no internet access for DNS requests, maybe you do not tell me something

**Comment by LazyZhu** [comment]
I'm running a local dns cache server and with 127.0.0.1:53 for adapter, maybe related to the Issue, need tested.
