### ISSUE TITLE
[Feature] write descriptions for windows internal programs that create outbound connections

### ISSUE THREAD

**Issue by vlado2222** [henrypp/simplewall#1733]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.7.8

### Problem you are trying to solve

I have set simplewall to automatically ask whenever a program without an existing rule tries to create an outbound connection. When I first set it this way, simplewall started to bombard me with questions if I want to allow programs to create outbound connections. So I started to search the internet on what do those programs do and what will happen if I block their outbound connections. I found it incredibly difficult to find descriptions for the embedded windows programs like "apphostregistrationverifier.exe", "msiexec.exe", "ntoskrnl.exe", "wuauclt.exe", "dashost.exe", "devicecensus.exe", "systemsettings.exe" etc. what they do, what will happen if I block them, etc.

### Suggested solution

Write short descriptions only for windows internal programs that create outbound connections and what will happen if user blocks that program. Put the description into the popup window that asks the user to allow/deny/ignore a connection. This will incredibly help all new users that first install simplewall and set it to ask on new outbound connections.

**Comment by vlado2222** [comment]
One more thing: show the description only for windows internal programs that pass the digital signature check. We don't want to show those descriptions on malware that tries to disguise itself as windows internal program.

**Comment by henrypp** [comment]
u already have feature to add comment for whatever u want apps and rules! if i dont understand ur issue, reply!

**Comment by vlado2222** [comment]
> if i dont understand ur issue, reply!
Hi. Unfortunately you don't understand what I was trying to solve. If a new user installs simplewall and set it to block outgoing connections. It will start bombarding the user with queries whether you want to block or allow windows internal programs. Then the user has to start searching the internet to find information about those programs and what will happen when when they are blocked. It's difficult for novices to find reliable information for windows internal programs that are creating outbound connections and what will happen if he blocks those outgoing connections. So why not have those descriptions already included in every new install of simplewall? Let me know if it's still not crear what I try to achieve. Thanks!
