### ISSUE TITLE
[Question] Access to the internet for some programs.

### ISSUE THREAD

**Issue by PerfectOua** [henrypp/simplewall#1738]
Hello,

Thank you for the great app. Can you help me to configure Simplewall (SW) to allow access to the internet for some programs, please?

1. Ace Stream HD + Ace Player HD for online stream watch - stream doesn't start, only after I disable SW, it starts.
2. RivaTuner Statistic Server - program with MSI Afterburner.

Also, when I try to update SW, it's updater downloads a new version, but during installation it says that SW is running and need to close it. after the closing, nothing happens. so I have to download a new version of SW manually from here and start installation again.

My blocked list:

<details> 

![image](https://github.com/henrypp/simplewall/assets/30981401/794a2632-69a0-4e45-a445-5a6f7660cba6)

</details> 

---

App version: 3.7.8
Windows version: Windows 11 Pro 23H2

**Comment by henrypp** [comment]
all in packet log
