### ISSUE TITLE
Support for other blocklists

### ISSUE THREAD

**Issue by ROCKNROLLKID** [henrypp/simplewall#174]
I have been looking for a tool like this for a long time, something that blocks traffic at windows level, rather then having to use a ad blocker in Firefox.

So I would like to suggest supporting and integrating other block lists, such as Easylist, Malware domains, Adguard spyware list, etc. and other host files such as MVPS host and hphosts.

**Comment by beerisgood** [comment]
Why not just use a tool for that? Anyway i recommend PiHole

**Comment by henrypp** [comment]
Use hosts file
