### ISSUE TITLE
[Question]I have been using this software normally, but one day for some unknown reason, there was no connection prompt when installing new software?

### ISSUE THREAD

**Issue by sacreaker** [henrypp/simplewall#1745]
I have been using this software normally, but one day for some unknown reason, there was no connection prompt when installing new software?
This will cause some of my software to be unable to connect to the Internet. I have to turn off filtering before I can access the Internet. I have been using this small and powerful firewall. I hope my problem can be solved.
I tried to upgrade to version 3.7.8, but new problems appeared and the original problems still existed.
![photo_2024-03-24_18-42-08](https://github.com/henrypp/simplewall/assets/59469078/0a34f8f3-cd9e-41ff-a4df-b2c544c74568)

@henrypp
App version: All version 
Windows version: <win10 21h1  19043.2006>

**Comment by sacreaker** [comment]
@henrypp

**Comment by henrypp** [comment]
@microsoft are required for answer!

**Comment by henrypp** [comment]
even @microsoft do not answer (as always), lol
