### ISSUE TITLE
[Question]How do I allow Command Prompt (Ping) Internet Access?

### ISSUE THREAD

**Issue by luckygitt** [henrypp/simplewall#1748]
Describe the question with as much detail as possible.

---

App version: <3.7.8>
Windows version: <10>

Hi.
I tried to ping a site using Command Pompt and and it gives the error "General Failure". If I disable filters it works fine but "cmd.exe" isn't even in the Apps list.
So, my question is, how do I grant/allow cmd.exe internet access?

Thanks,
Lucky

**Comment by henrypp** [comment]
icmp?

**Comment by secured2k** [comment]
cmd.exe is a command processor that doesn't directly access the network. Allow the protocol or the apps. For example, allow ping.exe.

**Comment by uniqss** [comment]
@secured2k you are right! Thanks very much!
