### ISSUE TITLE
new Version ccrashed STATUS_STACK_BUFFER_OVERRUN

### ISSUE THREAD

**Issue by MCSE-2000** [henrypp/simplewall#1752]

**Comment by henrypp** [comment]
dump?

**Comment by MCSE-2000** [comment]
Where?
How can i creat a crush dump?

**Comment by Alcazer** [comment]
> Where? How can i creat a crash dump?

start %AppData%\Henry++\simplewall\crashdump

**Comment by MCSE-2000** [comment]
here a crashdump on my test-system win8.1 32 bit

![2024-04-03 12_50_49-simplewall](https://github.com/henrypp/simplewall/assets/84094043/f2c1a14e-eae4-487d-ad3d-6a7d6990339c)
[Event.txt](https://github.com/henrypp/simplewall/files/14850326/Event.txt)
[simplewall.exe.3388.dmp.zip](https://github.com/henrypp/simplewall/files/14850344/simplewall.exe.3388.dmp.zip)

**Comment by MCSE-2000** [comment]
A BUG is A BUG....
