### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by vasilyvaganov** [henrypp/simplewall#1755]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.8

### Problem you are trying to solve

I have a file that is decompressed in TEMP and asks for internet access every time (because there is a new path)

### Suggested solution

Add the ability to allow Internet access to applications regardless of its path

**Comment by henrypp** [comment]
found urself
