### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by gimmik84** [henrypp/simplewall#1759]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.8

### Windows version

10

### Steps to reproduce

Install iCloud from windows store
Install simplewall
Two factor authentication on iCloud stops working (no codes are sent to the devices). 
Disable simple wall: codes are immediately sent to the devices but iCloud app is not able to reach Apple ID server.

### Expected behavior

Apple iCloud wo factor authentication should work

### Actual behavior

Two factor authentication on iCloud stops working (no codes are sent to the devices).

**Comment by henrypp** [comment]
it is not of the subject problem, but you:
blocks 2fa servers, what exactly u can see only in packets log.

**Comment by gimmik84** [comment]
Hi, 
can you please explain it better? Do you want me to enable packet logs and check what is blocked?
What I see is that the only way to make Apple two factor authentication work is disable simple wall filters. 
All Apple programs and services requests were obviously allowed. It may be a problem in some ip in the block list?

**Comment by henrypp** [comment]
yes, u can use log in ui, not in file instead.

**Comment by henrypp** [comment]
maybe u enable blocklist filters which is blocks apple 2fa
