### ISSUE TITLE
[Bug] Inconsistent search selection context

### ISSUE THREAD

**Issue by brian6932** [henrypp/simplewall#1760]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.8

### Windows version

10

### Steps to reproduce

1. <kbd>CTRL</kbd>+<kbd>F</kbd> bind
1. Enter a search term
1. <kbd>ENTER</kbd> key
1. <kbd>CTRL</kbd>+<kbd>A</kbd> bind
1. <kbd>DEL</kbd> key
1. Every single item has been selected to be deleted

### Expected behavior

<kbd>CTRL</kbd>+<kbd>A</kbd> should use the context of the current view.

### Actual behavior

It selects every item in the pane, outside of view. This is super annoying and fucks with my muscle memory each time I want to delete a every rule matching a search.

**Comment by henrypp** [comment]
this is maybe a fix, try it!
[simplewall.zip](https://github.com/henrypp/simplewall/files/15080587/simplewall.zip)

**Comment by gettysburg** [comment]
@brian6932 dumb weeaboo nigger lover

**Comment by gettysburg** [comment]
@brian6932 kill yourself spook

**Comment by gettysburg** [comment]
@brian6932 faggot

**Comment by brian6932** [comment]
Ok, so this issue still occurs just a little differently from the title.

To reproduce
1. search for something
1. select the 2nd item in the results
1. <kbd>SHIFT</kbd>+<kbd>END</kbd>
1. <kbd>DEL</kbd>

**Comment by henrypp** [comment]
and? shift end are select required items, and?

**Comment by brian6932** [comment]
huh?

**Comment by gettysburg** [comment]
@brian6932 Please provide more information next time, images or videos are very helpful, also be aware of the fact that the creator of simplewall does not speak English natively so please describe in greatest possible detail.

Sadly I switched away from Windows to ArchLinux a long time ago so I can not see or confirm if this really still occurs or not, or if it is an issue at all.
