### ISSUE TITLE
How do I make SimpleWall work in the opposite manner?

### ISSUE THREAD

**Issue by chinagreenelvis** [henrypp/simplewall#1766]
By default SimpleWall aggressively blocks anything and everything, apparently; I want everything to be allowed as normal unless I manually block it. How can I set it up like this?

**Comment by henrypp** [comment]
Settings -> Rules -> Block all outgoung connections

**Comment by chinagreenelvis** [comment]
This doesn't seem to do the trick for me entirely; I've noticed that even with the rules unchecked, qBitTorrent keeps getting added to the blocklist. Should I not be running with filters active?
