### ISSUE TITLE
[Bug] Second SimpleWall.exe instance/process in 3.8.1

### ISSUE THREAD

**Issue by ghost** [henrypp/simplewall#1769]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.8.1

### Windows version

Win10 19045

### Steps to reproduce

Launch SimpleWall 3.8.1 (64bit) and check Task Manager. There will be 2 SimpleWall.exe processes. One is elevated and has High priority. Second one is not elevated and has Normal priority.

### Expected behavior

There should be only one SimpleWall.exe process.

### Actual behavior

Version 3.8.1 creates 2 SimpleWall.exe processes instead of one.

### Logs

None

**Comment by henrypp** [comment]
simplewall cannot create second process, check second process by virustotal, if it is the same process then i do not know why, sw did not needed it, and even not elevated

**Comment by SSJPKXL** [comment]
I checked many times and it happened even on a fresh installation of Windows 11 22631.3527 and nothing else installed.

Unelevated process (only present in SimpleWall 3.8.1)
Priority Class - Normal
Command Line - "C:\Program Files\SimpleWall\SimpleWall.exe"
Directory - C:\Program Files\SimpleWall\
Parent Console - Explorer.exe
Parent Process - Explorer.exe

Elevated process (present in all SimpleWall versions)
Priority Class - High
Command Line - "C:\Program Files\SimpleWall\SimpleWall.exe" "C:\Program Files\SimpleWall\SimpleWall.exe" 
Directory - C:\Program Files\SimpleWall\
Parent Console - SvcHost.exe
Parent Process - SimpleWall.exe

**Comment by xramboxx** [comment]
I have the same problem. It occurs when I run SW with unchecked "Skip UAC prompt" or from a limited user account.
Windows 10 19044.4291

**Comment by SSJPKXL** [comment]
Yes. Thank you for narrowing it down. "Skip UAC Prompt" is not needed for who disable UAC account-wide. I think this will be an easy for developer.

**Comment by SSJPKXL** [comment]
Same issue persists in 3.8.2.

**Comment by SSJPKXL** [comment]
Just tested Windows 11 and it had the same exact bug with 3.8.1 and 3.8.2.

**Comment by henrypp** [comment]
now it is fixed, it is routine problem, check for new version on this month
