### ISSUE TITLE
[Question] Does profile encryption depend on Windows login credentials, LSASS.exe or SAM hive?

### ISSUE THREAD

**Issue by SSJPKXL** [henrypp/simplewall#1775]
It would be helpful to know a bit more about SimpleWall profile encryption happens.

Does SimpleWall use administrator Windows login credentials to encrypt SimpleWall profile? Is it best to re-encrypt if administrator Windows login credentials change? Does SimpleWall access LSASS.exe or SAM (Security Accounts Manager) registry hive to encrypt profiles?

**Comment by henrypp** [comment]
no, it uses his own key

**Comment by SSJPKXL** [comment]
Good to hear! Thank you! I hope its not the posted one "Gc(j1EptodnKP?{ZT!SlMVip[fJIs&Ci3fOqjATfp@h,q0(]QVaGs5Iht3)/b:Ll" - https://github.com/henrypp/simplewall/commit/06538d9b047f7db67d97ff8b0d6f1a572086c8df#diff-a98524a5e4320bb477e79535c4c87bdc3a5a4799cc8a0c68ac7eb790ddfda531
