### ISSUE TITLE
[Question] Managing Simple Wall's Administrative Access on Windows

### ISSUE THREAD

**Issue by codeXXjs** [henrypp/simplewall#1776]
Hi Henry,

Every time I start up my Windows system, I'm consistently prompted to grant administrative access to Simple Wall. This repetitive request is becoming quite bothersome. Is there a way to set it to automatically allow access without needing my permission each time?
Thank you 

App version: 3.8.1
Windows version: Windows 10 Pro N 22H2

**Comment by henrypp** [comment]
skip uac option?

**Comment by grolongo** [comment]
Hi @henrypp, why is this option not enabled by default? Since we already have to answer the UAC prompt during installation, I'm pretty sure it's safe to assume people who want simplewall enabled at startup don't want to be asked each time.

**Comment by henrypp** [comment]
@grolongo it is not enabled by default because user made its own decision

**Comment by grolongo** [comment]
@tnodir I'm not talking about disabling UAC globally, only for simplewall **after** the installation.

**Comment by codeXXjs** [comment]
@grolongo 
![Capture](https://github.com/user-attachments/assets/60dd36a5-df48-4a08-83dd-ce993415d2f3)

**Comment by grolongo** [comment]
@codeXXjs Thanks but I was asking why is it not ticked by default.

**Comment by codeXXjs** [comment]
> @codeXXjs Thanks but I was asking why is it not ticked by default.
I assume Henrypp does not want to enforce UAC on users, leaving it up to us to make that decision. However, many users may not notice this option. Generally skipping UAC by default could pose security risks, as it may allow unauthorized changes to the system without user consent. Therefore, perhaps adding a checkbox in the startup of prompt that allows users to disable the UAC skip would be a better solution.
