### ISSUE TITLE
Strange characters in log file

### ISSUE THREAD

**Issue by OlsiIgitt** [henrypp/simplewall#1778]
I detected strange characters in the date/time section of data entries (rows) in log file.
See Screenshot...
This can lead to problems when using esternal viewers, e.g. LogViewPlus.

![PP_2024-05-05 15 35 09](https://github.com/henrypp/simplewall/assets/64005227/013babff-3cb0-4894-9907-4ece86be2d82)

---

App version: <simplewall v 3.8.1>
Windows version: <11 pro>

**Comment by henrypp** [comment]
not confirm, use [correct text editor](https://github.com/rizonesoft/Notepad3/releases).
