### ISSUE TITLE
Huge reads every 10 minutes.

### ISSUE THREAD

**Issue by borkfomb** [henrypp/simplewall#1783]
Hi, simplewall does ~200mb reads at 10min intervals for as long as it's running, which prevents idling. Any idea what it's doing?

![sshot-2024-05-08-11-55-11](https://github.com/henrypp/simplewall/assets/169256676/2c9789b2-b87e-4310-b0ae-655b94eb9544)

App version: 3.7.8
Windows version: 19044.1288

**Comment by henrypp** [comment]
> prevents idling

u activate option monitor app changes and waits something else?

**Comment by vertuk** [comment]
I have the same issue. I see the same behavior (~200 MB/s reads every 10 minutes) via Task Manager. Along with that the 'System' process (C:\Windows\System32\ntoskrnl.exe) starts using disk with about 10-50% of Simplewall's process' disk read speeds and also takes 20-60% of the whole CPU usage.
There's no predictable pattern behind it, but it more often happens in times of a high load like a game. But maybe that's where I just notice it better.
This combined heavily lags my gaming performance, especially of the games installed on the system drive.

Another thing that might matter is that I am using [Nekoray](https://github.com/MatsuriDayo/nekoray) in Tun mode and qBittorrent. It happens significantly less often when I close qBittorrent.

App version: 3.8.2
Windows version: 19045.4291

**Comment by henrypp** [comment]
@vertuk [same answer](https://github.com/henrypp/simplewall/issues/1783#issuecomment-2100645401)

**Comment by vertuk** [comment]
I'm sorry but I have no idea what you are trying to say by that. There's no option "Monitor app changes" in any menus I open.

**Comment by henrypp** [comment]
@vertuk 
![sshot-002](https://github.com/henrypp/simplewall/assets/3902025/beb31148-31c5-4229-a685-67c4716722c8)
