### ISSUE TITLE
App Specific / Global range rules are consistently ignored in 2.2.7 RC 64bit

### ISSUE THREAD

**Issue by working-name** [henrypp/simplewall#179]
Hi there,

Glad to see you figured out the constant crash situation on Windows 10 👍 

The issue now seems to be that rules that employ IP ranges are ignored by all apps. In my screenshot I have blocked the whole netblock NVIDIA uses to gather telemetry and check for updates and applied it to all apps. I'm still asked to confirm what to do with a connection to an IP that is part of that range.

Technically all I ever do is confirm blocking an IP part of ranges I've already blocked globally (all apps). This is not intended behavior, is it?
![ranges-do-not-work](https://user-images.githubusercontent.com/16505052/40262730-e15d7304-5ad7-11e8-9fe3-cffa13bfb16e.JPG)

### Update 
- blocking a specific port will not have any effect, it has to be the IP, and one IP per block rule otherwise it won't work.

**Comment by henrypp** [comment]
fixed in 2.2.8, anyway, please check it.
