### ISSUE TITLE
[Feature] Close rules window on Escape key

### ISSUE THREAD

**Issue by eugenesvk** [henrypp/simplewall#1798]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.8.2

### Problem you are trying to solve

Conveniently closing rules' window with a keyboard 

### Suggested solution

Make <kbd>Escape</kbd> fulfill it's expected role and closed the modal window with a rule

(interestingly enough, it can close the main app's window, but not the "smaller" rules window)

**Comment by henrypp** [comment]
every window already have close on escape

**Comment by eugenesvk** [comment]
No they don't, check out this video - you can't close the rule modal with Escape right away. Though during more testing I've discovered that Escape starts to work once you alt-tab (or in the video click on the desktop then click on the rule window)

https://github.com/henrypp/simplewall/assets/12956286/bbcb4f50-6e2e-4b75-a3ad-88fc5798d7b7

**Comment by henrypp** [comment]
it because it required to select any control, press to any input

**Comment by eugenesvk** [comment]
And it shouldn't, Escape should close the active modal window regardless of any interaction just like it does for the main window or other apps. Why are these modals so special and hard to quit?
