### ISSUE TITLE
[Feature] Allow to create rules that match a file path

### ISSUE THREAD

**Issue by mslivo** [henrypp/simplewall#1802]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.8.2

### Problem you are trying to solve

A lot of windows services .exe files get replaced with every update (gamingservices.exe, widgets.exe), and when they do they pop up again and again even though there are already rules for this.

Creating the rule without any TCP/IP/PORT restrictions still do not apply because the .exe file itself is not same anymore.

### Suggested solution

If we could create a rule that just matches the file path with a regex this could be solved by creating a rule like C:\\.*\windowsapps.\\.*widgets.exe to be done with this app once and for all

**Comment by tormit** [comment]
This is longwaited feature #1727 , years unsolved.
Very annoying these exe-s that change itself or change their path.
