### ISSUE TITLE
[Question] Doesnt block all connections when vpn is working

### ISSUE THREAD

**Issue by zzmishgun** [henrypp/simplewall#1804]
When my socks protocol is toggled on, microsoft edge, python, and i guess some other apps simply dont care, that they are actually blocked. When i turn my vpn off, everything works as it should be. Maybe thats my personal mistake somewhere?

App version: <3.7.8>
Windows version: <22h2>

**Comment by henrypp** [comment]
i need to speak with with magicians to understand?
