### ISSUE TITLE
The program is getting better but the UX is getting worse. The "simple" philosophy should be kept in mind

### ISSUE THREAD

**Issue by whytho2000** [henrypp/simplewall#181]
Since the Special rules apps section update simplewall started to have a lot of glitches, as you can see from other issues like the rules not being correctly applied or having to press F5 to see changes.

It makes the program more complex without a reason. Implementing tags under the name of the app could be used as an alternative.

SRA contains programs both from the whitelist and from the blacklist. The checkbox behavior could confuse new (and current) users.

It seems I'm not the only one finding that the UI/UX is getting too confusing 
https://github.com/henrypp/simplewall/issues/148#issuecomment-375735526
https://github.com/henrypp/simplewall/issues/69

Since this is going to get closed without any feedback I'll just add another clear problem:
https://github.com/henrypp/simplewall/blob/master/bin/blocklist.xml is hardcoded. The user should be able to update the list manually from https://github.com/crazy-max/WindowsSpyBlocker and the issues from 148#issuecomment-375735526 could be fixed in the same update since there's no way to diff the changes.

I've been using simplewall for over a year and this is the first time I'm getting the feeling the program is heading in the wrong direction. I took the time to write this but I'll understand if you don't care since I don't contribute any code. Thanks for making this amazing program.

**Comment by EC-O-DE** [comment]
Sometimes the app ignores apps seeking through firewall~And there I am~waiting for the popup to not appear... when it should though,,
