### ISSUE TITLE
[Bug] Deleting multiple apps from a filtered list also removes unfiltered apps

### ISSUE THREAD

**Issue by pbarney** [henrypp/simplewall#1810]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.8.2

### Windows version

Windows 10 22H2 19045.4291

### Steps to reproduce

1. Select the "`Apps`" tab
2. Press <kbd>CTRL</kbd>+<kbd>F</kbd> to search
3. Enter a search query that results in multiple items being displayed
4. Highlight the list
5. Press <kbd>Delete</kbd>

### Expected behavior

It should only remove the selected items

### Actual behavior

It removes all entries in between the first highlighted item and last highlighted item including items that aren't currently being displayed.

If this is not a bug that will be fixed, then it would be helpful to have an "undo" feature available to help mitigate issues like this.

**Comment by henrypp** [comment]
#1794
