### ISSUE TITLE
[Question] How to get the news teams to work with simplewall on Win11?

### ISSUE THREAD

**Issue by SvenBent** [henrypp/simplewall#1811]
Describe the question with as much detail as possible.

New teams keep giving me "We've run into a sever error/ Some functions might not work right now but you can continue to use the app".
This has the affect that i am unable to join teams meetings, however 1to1 call are fine
I have been unable to locate what process I'm missing to allow internet of what changes to do to make this works, and om hoping someone can tell me how.
If I disable simplewall and go back to windows firewall, teams works fine.

Microsoft Application: Allow
Microsoft updates Allow
Microsoft Telemetry and spying : Block (I tried with on allow but it did not help

Windows processes blocked that might be interesting
compatelrunner.exe
Deveicecensus.exe
msmpeng.exe
photos.exe
systemsettings.exe
widgets.exe
wmplayyers.exe

Teams process I have allowed
ms-teams.exe (currently have a  connection)
Ms-teamsupdate.exe (no connection atm)

---

App version: 3.8.2
Windows version: Windows 11 - Version 10.0.22631 Build 22631

**Comment by DmitryStrunevsky** [comment]
Unblocking the application named "msedgewebview2.exe" helped me.

**Comment by henrypp** [comment]
allow msedgewebview, thats all
