### ISSUE TITLE
[Question] There is no new Release 3.8.3 but simplewall wants to update to this version?

### ISSUE THREAD

**Issue by SourceTrees** [henrypp/simplewall#1812]
See title.

Where are the update information and the new sources pulled from? Isn't it github?
Update is failing saying Update Server is not reachable?

---

App version: 3.8.2
Windows version: win10 22H2

**Comment by frunzales** [comment]
Using the Help -> Check for Updates option I see:

Update Available. Download and install now? simplewall - 3.8.3

followed by:

Update server connection error

Description:

The server returned an invalid or unrecognized response

Status:
12152 (0x00002F78)

**Comment by henrypp** [comment]
sorry, it my problem, now it fixed
