### ISSUE TITLE
Updates are broken

### ISSUE THREAD

**Issue by tokariu** [henrypp/simplewall#182]
I get update-available notifications in v2.2.x but when I click on install, the program fails to install the updates. It downloads the update, but it fails to install it. it closes the simplewall app and then asks to install the update. when I click on okay to install, nothing happens. it's repeatable. I finally say "no" then the old version of simplewall starts up again, no update was installed. the whole procedure is repeatable.

to update i need to download the latest release manually from github, close simplewall and install the downloaded installer. not quite how it's supposed to work, i guess.

**Comment by aphextwins** [comment]
I also experience this.

It notifies about a new update.
I click yes, it downloads something and restarts simplewall.
but when it restarted, It notifies about the same update, and when i check the version, it did not update.

**Comment by tokariu** [comment]
i experience strange behaviour after last update, from v2.3.1 to v2.3.2.
Suddenly all my user-level autostart programs were missing, not just one or two.. more like 6 or 7 autostart programs. the system-level/driver autostart programs were still loading though. could it be something with a simplewall update?
