### ISSUE TITLE
[Feature] Show PID in packets log.

### ISSUE THREAD

**Issue by bashimao** [henrypp/simplewall#1823]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.8.2

### Problem you are trying to solve

The **packets log** is a great tool to understand what is going on. However, it only shows the name of the process, but not its PID. So if there are multiple processes with the same name, let's say for example `svhost.exe`, it is currently impossible to identify which instance of the executable made the request.

### Suggested solution

Add a column `PID` to the packets log.

**Comment by henrypp** [comment]
dup: #1047, #88

and where/how i can get PID?
![sshot-001](https://github.com/user-attachments/assets/4ab9d0cd-efb8-491d-b17d-961ae3aeb1d1)

**Comment by bashimao** [comment]
@henrypp: Originally, I thought that you probably get the PID reported by the FW and then resolve it into a name. At least that would have sounded logical to me.

Now that I looked at the API, I see your problem. Beside the `appId` field in the `FWPM_NET_EVENT_HEADERx` there is not much. And that one seems to point to the name of the executable.

As said, I am surprised the API is constructed like this. Boggles me. Still, being able to tell apart processes in the log would be a super useful feature.

**Comment by henrypp** [comment]
> Now that I looked at the API, I see your problem. Beside the appId field in the FWPM_NET_EVENT_HEADERx there is not much. And that one seems to point to the name of the executable.

only executable path, not anymore, or you give a example how to get PID from `FWPM_NET_EVENT_HEADERx`?
