### ISSUE TITLE
[Question] what's the difference between Block and Next buttons?

### ISSUE THREAD

**Issue by eugenesvk** [henrypp/simplewall#1824]
For new app network request there are two buttons (**Block** and **Next**) both block access, only one adds to "apps without access (silent)" group and another to "apps without access", but then what does "silent" mean here?

Thanks!

I'd assume that "Next" would just ignore the app (e.g., block this attempt, but let it ask again later) so you're skipping making a decision, but this doesn't seem to be the case

---

App version: 3.8.2
Windows version: 10

**Comment by henrypp** [comment]
there is no "silent" button, Next button just skip this app and in future it will be notified again!
