### ISSUE TITLE
[Feature] add columns like path etc. in main view

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [henrypp/simplewall#1832]
^

**Comment by henrypp** [comment]
"View" -> "Show file names only" already exists

**Comment by henrypp** [comment]
if disable this option, then show

**Comment by jamesdeluk** [comment]
I also think it would be useful to have a separate path column, as I'd rather have the apps sorted by name (so I can easily see what they are and find them in the list), yet also quickly see the path. For example, I have six python.exes, all in different locations - I want to have them together in the list, but also see their path at a glance. As it currently is, sorting by path, all apps in 'program files' are grouped, all in 'appdata' are grouped, etc, which isn't very intuitive - and, in the previous example, the python.exes are split up, almost impossible to find.
