### ISSUE TITLE
[Question] does packet logging only include disallowed apps?

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [henrypp/simplewall#1836]
I'm wondering that on my other machine I saw some packet logs from allowed apps, but on this one it only logs blocked packets.
Is this correct?

---

App version: 3.8.2
Windows version: w10. 22h1

**Comment by henrypp** [comment]
no

**Comment by smritisubh** [comment]
no , because packet logging can capture all network traffic not just disallowed app, depending upon how it is configured.
