### ISSUE TITLE
VirusTotal for v.3.8.3 a bit too many positives

### ISSUE THREAD

**Issue by th3m** [henrypp/simplewall#1838]
Version 3.8.3 is getting a "15/75 security vendors flagged this file as malicious"

[https://www.virustotal.com/gui/file/134c36f0aa54691dd9a4b0e2b9bf784186fab90394f720aa05d504330d156cac](https://www.virustotal.com/gui/file/134c36f0aa54691dd9a4b0e2b9bf784186fab90394f720aa05d504330d156cac)

Comparing to 3.8.1 and 3.8.2, for example, which both are getting only 2/75 (obviously false positives)
[https://www.virustotal.com/gui/file/db6c4d0c0228c5b06c081b9cc363cb0ab1524f8ce65ac5c9a28418b138910074](https://www.virustotal.com/gui/file/db6c4d0c0228c5b06c081b9cc363cb0ab1524f8ce65ac5c9a28418b138910074)
[https://www.virustotal.com/gui/file/1b823fd110fd766dd0b0d9858a9850ef883c86d3a4f20dcf7ac4eba7c088ebdc](https://www.virustotal.com/gui/file/1b823fd110fd766dd0b0d9858a9850ef883c86d3a4f20dcf7ac4eba7c088ebdc)

Is this normal?

**Comment by henrypp** [comment]
it ALWAYS decide as malicious unsigned binaries, logic 1 sort

**Comment by henrypp** [comment]
you can recompile and result with the SAME SHA256 hashes, but use 26100.1 sdk and vs 2022 17.10.5, linker has /BREPRO which makes exactly the same executable...

**Comment by henrypp** [comment]
and IDGAF what malicious in installer?

**Comment by henrypp** [comment]
@tnodir 

aga, [installer are very harmful](https://github.com/henrypp/builder/blob/master/src/setup_script.nsi), lol!

**Comment by andry81** [comment]
> @tnodir
> 
> aga, [installer are very harmful](https://github.com/henrypp/builder/blob/master/src/setup_script.nsi?rgh-link-date=2024-08-09T21%3A21%3A38Z), lol!

It depends on NSIS compiler and applied plugins. May be something of these has contained "harmful" code.

**Comment by henrypp** [comment]
@andry81 it build on vanilla NSIS <s>installer</s> compiler

**Comment by henrypp** [comment]
@tnodir 

DeleteRegValue removes bullshit from registry which can left, only maybe nsExec::Exec

> Try to move them to .exe -uninstall.

not all apps run as admin!
