### ISSUE TITLE
[Bug]Another failed update do to severe trojan

### ISSUE THREAD

**Issue by NunnyaBis** [henrypp/simplewall#1839]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.8.2

### Windows version

11

### Steps to reproduce

Splash screen shows new update
click update
Windows and Malwarebyte shows Severe Trojan
Trojan:Script/Wacatac.B!ml
This will not let the update to continue
You sure do have a lot of fails positives 

### Expected behavior

For there not to be a threat in the first place. You have one about every few month.

### Actual behavior

Trojan Quarantined but have to shut down Simplewall and restart.

### Logs

![Screenshot 2024-08-08 164953](https://github.com/user-attachments/assets/bc34a8f1-09f4-4bcd-b75a-9a062938de9a)

**Comment by henrypp** [comment]
dup #1838
