### ISSUE TITLE
What means "enable rule"?

### ISSUE THREAD

**Issue by PapaiMark** [henrypp/simplewall#1840]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.8.3

### Problem you are trying to solve

In my native idiom or in English, I don't understand what means "Enable rule".
 Does it mean that MS is permitted do keep doing what it does or
 does it mean that the rule is an app rule and I suppose that is to block the app / service to access internet?
 Instead of "rule", please use something clear like BLOCK marked checkboxes. 

### Suggested solution

Instead of use "rule" , use BLOCK marked checkboxes.

**Comment by w64bit** [comment]
A rule it's like a doorman.
One knows who to let in.
Another can deny the entrance.
Another can allow the exit.
Another can deny the exit.
Enable rule = you choose what doorman to be active. You can have as many as you want.
