### ISSUE TITLE
[Bug]タスクトレイにアイコンが表示されない

### ISSUE THREAD

**Issue by TARO9547** [henrypp/simplewall#1841]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

v.3.8.3

### Windows version

Windows 11

### Steps to reproduce

わからない

### Actual behavior

わからない

**Comment by henrypp** [comment]
https://github.com/henrypp/simplewall/issues/1695
