### ISSUE TITLE
v3.8.3 bug

### ISSUE THREAD

**Issue by OLDvHUNTER** [henrypp/simplewall#1843]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.8.3

### Windows version

11

### Steps to reproduce

allow 

### Actual behavior

after I click allow on call of duty it does not provide internet to this app I roll back to 3.8.2 and it did provide internet

**Comment by henrypp** [comment]
what do you have i dont know, i am not a telepath!
