### ISSUE TITLE
[Bug] Simplewall 3.8.3 does not show up in tray menu at boot

### ISSUE THREAD

**Issue by g-k-m** [henrypp/simplewall#1844]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.8.3

### Windows version

Windows 10 22H2 v19045.4717

### Steps to reproduce

After updating to 3.8.3, when simplewall launches as i boot windows, the notification tray does not show up (and thus i can't open the GUI). I keep opening the shortcut and new simplewall.exe processes keep launching but no tray shows up. Only if i close all simplewall.exe processes and then start it again from the shortcut then the tray shows up. This happens every single time, 100% consistent behaviour. Without the tray i can't open the GUI, so it's kind of a big problem.

### Actual behavior

-

### Logs

Clicking on Show log does not open anything

**Comment by RH-BD** [comment]
Same is also happening to me. I second this. Please fix asap.

**Comment by henrypp** [comment]
does not visible pinned issue #1695 ?

**Comment by RH-BD** [comment]
I just tried with the method explained at #1695 but didn't work! I again had to close all the process in the task manager and then reopen simple wall...

**Comment by Mac3DX** [comment]
Yes, same issue here over Win 11. On the startup it doesn't show on the system tray. That started after the last update.

**Comment by henrypp** [comment]
@Mac3DX fix your OS, it is not main problem

**Comment by woodholly** [comment]
How to reproduce - install tiny10 version of windows 10 (probably LTSE too), install simplewall, add start with windows option, reboot. After restart simplewall does not show in the tray and does not work, it can be fixed by killing simplewall process and starting it manually.
For anyone interested - version 3.8.2 works fine, just downgrade.

**Comment by Mac3DX** [comment]
Interesting thing is, after restarting Windows when you go to check task manager there are two process running for SW. You must kill them and open up SW again n order to work. Then you got just one process as usual and icon tray shows up. That's not my system I believe as many others are reporting the same issue. Something is causing that.

**Comment by henrypp** [comment]
@woodholly

tested on VM https://archive.org/download/tiny-10-23-h2/tiny10%20x64%2023h2.iso (A11116C0645D892D6A5A7C585ECC1FA13AA66F8C7CC6B03BF1F27BD16860CC35), all tray icons are right displayed!

**Comment by Mac3DX** [comment]
Maybe it can be solved by reinstalling it, but I wouldn't like to lose all my blocking list. It's a pain when you start using it from scratch. Pop ups every single time.

**Comment by henrypp** [comment]
@woodholly you may check this build [simplewall.zip](https://github.com/user-attachments/files/16626745/simplewall.zip), it can be fixed!

**Comment by woodholly** [comment]
@henrypp no idea why it works for you, but tiny10 and previously LTSE install had this bug. Probably locale related ?

**Comment by henrypp** [comment]
@woodholly english

**Comment by woodholly** [comment]
I think this bug is related to https://github.com/Sycnex/Windows10Debloater, without it bug does not show up.

**Comment by woodholly** [comment]
Yes, I rechecked it. I even know which option makes simplawall fail - "Uninstall Onedrive", this messes with toolbar settings and after applying it simplewall fails to start.

**Comment by henrypp** [comment]
@woodholly not right, i every VM configure with [Windows10Debloater](https://github.com/Sycnex/Windows10Debloater) (+ "Uninstall Onedrive")

> this messes with toolbar settings and after applying it simplewall fails to start.

we here working on tray icon or what?

**Comment by woodholly** [comment]
Yes, this is related to absent tray icon AND simplewall not starting at all. But 3.8.2 works.

**Comment by henrypp** [comment]
@woodholly i do not have issue about simplewall 3.8.3 not starting at all.

**Comment by woodholly** [comment]
Roadmap for fail: tiny10, password protected windows user, install simplewall
change settings: load on startup, start minimized, APPLY RULES.
start debloater GUI, click "remove onedrive"
reboot
login user, wait for simplewall autostart
simplewall does not start, no tray icon, process kill required

**Comment by henrypp** [comment]
@woodholly create issue, with reference to this issue for me to remember

**Comment by garchomps** [comment]
> @woodholly you may check this build [simplewall.zip](https://github.com/user-attachments/files/16626745/simplewall.zip), it can be fixed!

I've tried both this build and the reset_explorer_tray.zip file posted in another thread regarding a problem similar to this one with no changes. The tray icon still doesn't appear after the system has completed booting and the only way for me to get it to appear is to end the Simplewall process from inside of Task Manager and then restart it again. I also tried several different ways of getting it autostart on boot other than the option to do so from inside of the program itself. I am on Windows 10 Pro N 22H2 19045.4780.

**Comment by notsyncing12309** [comment]
I have the same problem, but I didn't use debloater. I tried to solve it by clearing the tray cache via a bat file from a neighboring thread, but it still doesn't work.

**Comment by henrypp** [comment]
@notsyncing12309 fix here https://t.me/henrypp_dev/84?comment=1898

**Comment by Riaulo** [comment]
The problem with the new executable seems almost completely solved. But the icon does not appear when a user logs out and logs back in.

**Comment by reddyshyam** [comment]
Same here, on boot, tray icon does not come up. Invoking from Start menu adds second process and both will not be accessible. When I kill both and invoke again from start menu, it works well i.e. appears on system tray and is responsive.

I am on latest Windows 11 64 bit (23H2 22631.4037)

**Comment by henrypp** [comment]
@reddyshyam https://github.com/henrypp/simplewall/issues/1844#issuecomment-2295340003

**Comment by reddyshyam** [comment]
> @reddyshyam [#1844 (comment)](https://github.com/henrypp/simplewall/issues/1844#issuecomment-2295340003)

Hi @henrypp, thanks for getting back. The above link takes me to telegram and I do not understand what it says. I am not on telegram. Can you let me know what the solution is please?

**Comment by henrypp** [comment]
@reddyshyam complete fixes tray icon

**Comment by reddyshyam** [comment]
> @reddyshyam complete fixes tray icon

Hi @henrypp, sorry to be silly, what fixes the tray icon? Is there a build, hack or something? Can I have the solution here please? I am clueless. Terribly sorry!

**Comment by googie-g15** [comment]
Just to add another voice regarding this issue, the fix from #1695 (using `reset_explorer_tray.bat`) didn't work for me on Win11 either. I tried various methods of auto start but the only thing that was successful was downgrading Simplewall to 3.8.2.

This is a pretty serious issue IMO as it's not just the fact that you can't get to the GUI with it happening, but it blocks Simplewall from being able to send pop-up notifications regarding packet requests to approve/deny. Hoping this can be fixed with the next release so I'm not stuck using an old version forever.

**Comment by nerdsalot** [comment]
Same issue here with 3.8.3. The dev offers no clear fix, just links to telegram instead. My mistake for ignoring the huge red flag that he likes to call people idiots. Back to TinyWall.

**Comment by henrypp** [comment]
@nerdsalot telegram already has a fix, but you complain? another red flaged!

**Comment by nerdsalot** [comment]
Try this: 

Log out of your Telegram account, delete its cookies, then click on your Telegram fix link. What do you see?
In other words, people without Telegram accounts can't see the fix, we only see this:
![Henry++_–_Telegram](https://github.com/user-attachments/assets/4557cb10-2f10-4352-9182-ed614e2b8303)

Why don't you post the fix here, in English?

> Same issue here with 3.8.3. The dev offers no clear fix, just links to telegram instead. My mistake for ignoring the huge red flag that he likes to call people idiots. Back to TinyWall.

> @nerdsalot telegram already has a fix, but you complain? another red flaged!

**Comment by henrypp** [comment]
@nerdsalot

bcs, me so lazy, and why you dont like telegram? you like [white flag](https://twitter.com/BNONews/status/1827449143360684210)? (lol)

**Comment by reddyshyam** [comment]
> @nerdsalot
> 
> bcs, me so lazy, and why you dont like telegram? you like [white flag](https://twitter.com/BNONews/status/1827449143360684210)? (lol)

Hi @henrypp, I am not on social platform and ofcourse you are entitled to use and communicate however you wish but this is the official place for simplewall to report issues, get help and thank you. 

I will not agree that you are lazy as you reply to almost every genuine request or issues almost immediately 🙂and in this particular case still replying on a closed issue thread.

You could have just given out the solution here for some old folks like me 🙂instead of asking us to refer elsewhere but will leave that to you.

Guys, if anyone has seen telegram and got the solution, can one of you be kind enough to post the fix here please? 🙏

**Comment by henrypp** [comment]
> almost every genuine request or issues almost immediately

lol, i am on computer 24/7

> You could have just given out the solution here for some old folks like me

it better than in telega, because it compiled a hour ago 
[simplewall.zip](https://github.com/user-attachments/files/16741848/simplewall.zip)

**Comment by henrypp** [comment]
[reddyshyam](https://github.com/reddyshyam)

> almost every genuine request or issues almost immediately

lol, i am on computer 24/7

> You could have just given out the solution here for some old folks like me

it better than in telega, because it compiled a hour ago 
[simplewall.zip](https://github.com/user-attachments/files/16741848/simplewall.zip)

**Comment by henrypp** [comment]
@reddyshyam

> almost every genuine request or issues almost immediately

lol, i am on computer 24/7

> You could have just given out the solution here for some old folks like me

it better than in telega, because it compiled a hour ago 
[simplewall.zip](https://github.com/user-attachments/files/16741848/simplewall.zip)

**Comment by reddyshyam** [comment]
> @reddyshyam
> 
> > almost every genuine request or issues almost immediately
> 
> lol, i am on computer 24/7
> 
> > You could have just given out the solution here for some old folks like me
> 
> it better than in telega, because it compiled a hour ago [simplewall.zip](https://github.com/user-attachments/files/16741848/simplewall.zip)
> 
> > case still replying on a closed issue thread.
> 
> notifications

Thanks @henrypp. I really appreciate your time and patience to compile and post it here once again. I have taken the fix, rebooted and the icon appears in system tray. I will wait for couple of days to confirm if the fix is permanent. Please bear with me.

Thanks again! 🙏🙏🙏
