### ISSUE TITLE
[Bug] 3.8.2 not updated to 3.8.3 (as with all updates)

### ISSUE THREAD

**Issue by Salivan464** [henrypp/simplewall#1846]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.8.2

### Windows version

Windows 7 Professional SP1 x64

### Steps to reproduce

1. When Windows start (and simplewall runs with administrator rights (I work on behalf of the user with UAC)) see window - "Update available. Download and install now? simplewall 3.8.3";
2. I press "Yes", and waiting, see window - "Downloading update...";
3. Then window - "Update available. Do you want to install it now?". If i press "Yes" - this window closed and the version remains 3.8.2.
Such bugs occur with updates all the time.
Why can't I see that the update is ended? In 2007, programs were already able to install updates without bugs, but here there are always bugs with updates.
Thank you and forgive my language!
----------------------------------------------
1. Когда Мастдай запущен (и незатейливаястена бежит c администратора правыми (я работаю согласно от имени из пользователя с Союза аэрокосмической корпорации)) я гляжу окно - "Модернизация доступно. Грузить и ставить сейчас? незатейливаястена 3.8.3";
2. Я жму - "Конечно", и жду, гляжу окно - "Загрузка модернизация...";
3. Дальше окно - "Модернизация имеется. Делать ты хочешь для установки сейчас?". Если я жму "Конечно" - это окно закрывается и версия посмертные произведения 3.8.2.
Такие жуки приходят на ум с постоянными модернизациями.
Почему я не вижу, что модернизация закончилась? В 2007 году программы были уж готовы могущими для установки без жуков, но здесь там являются всегда жуки с модернизацией.
Благодарить ты и не взыскивать мой язык!

### Expected behavior

Update from 3.8.2 to 3.8.3
----------------------------
Модернизация с 3.8.2 до 3.8.3

### Actual behavior

3.8.2 not updated to 3.8.3
----------------------------
3.8.2 не модернизируется до 3.8.3

**Comment by henrypp** [comment]
i dont know what happened on your computer, in 70% it defender remove setup file #1838, remove realtime protection of this shit

if you need correct translator: use this https://www.deepl.com

**Comment by Salivan464** [comment]
There is no Defender and no real-time protection either. This crap started a long time ago (approximately from version 3.7, sometimes it updated normally, sometimes not). Tested on 2 PCs with Win 7 x64 and Win 10 x64. Always the same. Only reinstallation helps (update from .exe). Maybe there is a way to diagnose from some logs?
Thank you!
-----------------------------------------------------
Страж не на посту и щитом храм с электронами не ограждает. Сия оказия взросла издавно (на глаз с  с версии 3.7, бывало исправно подкраивалась, бывало иначе ). Отсмотрено на 2 избушках-пекушках с Оконцем седьмым на 64 ставни и Оконцем 10 с теми же ставнями. Отож - с рождения мира вереница тянется. Подсобить вольна - токмо сызнова изба возведённая (на новый лад с учу переставленная). Может статься есть тропинка для созерцания летописных грамот?
Благодарствую!
