### ISSUE TITLE
[Bug] simplewall-3.8.3 triggers Windows Defender with Win32/Puamson alert

### ISSUE THREAD

**Issue by TalAstrix** [henrypp/simplewall#1847]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.8.2

### Windows version

Windows 10 Home 22H2 19045.4780

### Steps to reproduce

1. Download the latest version from Releases
2. Double click to run
3. Defender alerts (but doesn't automatically block the executable as its classified as low severity)

### Actual behavior

The installation crashes, however it seems I'm able to update straight from the software. While it triggers Windows Defender it doesn't stop with the update, however I decided to stop the update and remove the file until this is fixed.

### Logs

![Screenshot 2024-08-14 132035](https://github.com/user-attachments/assets/bec7be42-78ea-44ca-a34b-d20bc7d281a9)

**Comment by henrypp** [comment]
#1838
