### ISSUE TITLE
[Serious] Issue with SimpleWall 3.8.3 Setup File Detected as Threat

### ISSUE THREAD

**Issue by codeXXjs** [henrypp/simplewall#1849]
Description:
I installed SimpleWall version 3.8.3 and did not encounter any issues for a week. However, today I noticed that the setup file for SimpleWall 3.8.3 (simplewall-3.8.3-setup.exe) is being flagged multiple times as a threat by my antivirus software.

Steps to Reproduce:

    Download the SimpleWall 3.8.3 setup file from the official source.
    Attempt to run the setup file.
    Observe the antivirus software detecting it as a threat.

Expected Behavior:
The setup file should run without being flagged as a threat.

Actual Behavior:
The setup file is detected as a threat by my antivirus software.

Additional Information:

    SimpleWall version: 3.8.3 (installed)
    Setup file version: 3.8.3
    Antivirus software: Windows Defender, Malwarebytes and Virus Total Scan
    Operating System: Windows 10 22h2

Request for Assistance:
Could you please investigate this issue? Is there a known problem with the 3.8.3 setup file, or could this be a false positive from my antivirus software?
![Capture](https://github.com/user-attachments/assets/5dd762e0-0bb9-4de1-a112-64ff0de37dca)
![Capture2](https://github.com/user-attachments/assets/13bfa1cf-8940-41cd-badf-331cb6eedcc9)

Thank you!

**Comment by henrypp** [comment]
#1838
