### ISSUE TITLE
[Bug] Иногда не запускается при автозагрузке

### ISSUE THREAD

**Issue by Contact553** [henrypp/simplewall#1851]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.8.3

### Windows version

Windows 11

### Steps to reproduce

1. Вход в систему
2. Автозапуск программы

### Expected behavior

Ожидается, что интерфейс приложения запуститься (значок в трее), что будут работать уведомления.

### Actual behavior

Фактически процесс запущен (можно увидеть в Диспетчере задач), но интерфейс не запущен, значка в трее нету, уведомления для разрешения/блокировки нету

**Comment by Contact553** [comment]
Спасибо за ваши труды!

**Comment by dronab** [comment]
I confirm - it does not always start, the process at system startup takes up 8 megabytes of RAM, which is not in the tree. It is necessary to close and start manually.
Windows 10

**Comment by Contact553** [comment]
Это началось после обновления программы до версии 3.8.3

**Comment by henrypp** [comment]
[здесь фикс](https://t.me/henrypp_dev/84?comment=1898)
