### ISSUE TITLE
[Question] The same application requests

### ISSUE THREAD

**Issue by lukasv77** [henrypp/simplewall#1852]
Hi, I often get requests to grant permission for the same applications (especially from Microsoft – the most annoying and frequent ones include, among others: phoneexperiencehost.exe; microsoft.sharepoint.exe). Can someone explain why this happens and how to configure Simplewall so that it doesn't ask again for these and a few other entries?

---

App version: Simplewall 3.8.3
Windows version: 10.0.19045 Build 19045

**Comment by henrypp** [comment]
in notification, press "block" or in apps list select required app and right click "rules" -> "disable notifications"
