### ISSUE TITLE
[Question] Under the Win11 system, sometimes even though the startup has been turned on, it still hasn't started, and then manually opening it doesn't load anymore. After uninstalling and reinstalling, it returns to normal

### ISSUE THREAD

**Issue by suvern2647** [henrypp/simplewall#1854]
Under the Win11 system, sometimes even though the startup has been turned on, it still hasn't started, and then manually opening it doesn't load anymore. After uninstalling and reinstalling, it returns to normal

**Comment by henrypp** [comment]
https://github.com/henrypp/simplewall/issues/1851#issuecomment-2295982173
