### ISSUE TITLE
Tray icon not showing when run from Task Scheduler with 3.8.3, but not 3.8.2

### ISSUE THREAD

**Issue by eglimpse** [henrypp/simplewall#1855]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.8.3

### Windows version

Windows 11

### Steps to reproduce

Create Task with Task Scheduler to run SimpleWall at user login.

### Expected behavior

Show tray icon for SimpleWall.

### Actual behavior

Did not show tray icon for SimpleWall, even though process is running.
Only happens in 3.8.3, not with 3.8.2, so this issue was introduced in 3.8.3.

**Comment by henrypp** [comment]
[fix here](https://t.me/henrypp_dev/84?comment=1898)

**Comment by lieblinger** [comment]
@henrypp Facing the same issue with 3.8.5.0. Unfortunately the mentioned fix isn't available anymore. Could post the solution here? Thanks in advance!
