### ISSUE TITLE
[Question] Firefox DNS issue

### ISSUE THREAD

**Issue by N1N74** [henrypp/simplewall#1857]
Hello, I am running simplewall on windows and firefox randomly throws an error about not being able to find the DNS. Happens on first startup and will go away once simplewall is disabled, interestingly after re-enabling simplewall, no such error is throw, and it sometimes even survives restarting the application. 
I have played around with different DNS settings in Firefox and I don't assume that's the issue.
I have also added all the exe files in `C:\Program Files\Mozilla Firefox`.
This has been an issue for very long which I am only writing about now.

![image](https://github.com/user-attachments/assets/57475596-d4ed-4ea3-9c4d-cf725c103975)

App version: 3.7.1
Windows version: 21H2

**Comment by henrypp** [comment]
subj is not DNS provider

**Comment by henrypp** [comment]
you need to see dropped packets log to realize what ip's are blocked to understand what is not right, thats all!

**Comment by N1N74** [comment]
Hello, it seems today finally this has been working perfectly. 

I'm also reporting all four check marks at cloudflare's [SNI checker](https://www.cloudflare.com/ssl/encrypted-sni/) and no DNS error is thrown for any new sites I visit. I don't know if I changed the DNS setting into something favorable in firefox or if it's because of the latest simplewall (v3.7.1) or firefox but if anyone has the same problem I recommend updating simplewall/firefox and try adding `https://1.1.1.1/dns-query` as a custom DNS provider in firefox under maximum protection settings to see if it makes any difference.
