### ISSUE TITLE
[Question] have to reinstall everytime to get it to update

### ISSUE THREAD

**Issue by xedious** [henrypp/simplewall#1859]
Built new machine. Simplewall usually has updates every 1-2 days. Not getting any notifications. I open app and click 'check for updates' it says none available. I know there are because I have another machine that works fine.

I reinstall the app and click check for updates and it says updates available.

Thought it might be because it was running before my wifi connected, but the check for updates button should work as long as  I am connected.

---

App version: 3.8.3
Windows version: windows 11 pro

**Comment by henrypp** [comment]
orly, 3.8.3 does not have updates?

**Comment by xedious** [comment]
I thought the updates that used to come through were updates to the block list, not the application itself? If it is the application, then I guess there isn't an issue.

**Comment by henrypp** [comment]
app already has latest blocklist version

**Comment by xedious** [comment]
Thanks.
