### ISSUE TITLE
[Bug] При использовании "Удалить все таймеры" (ctrl + shift + T) приложение закрывается

### ISSUE THREAD

**Issue by 01ingsit1** [henrypp/simplewall#1860]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.8.3

### Windows version

Windows 10 PRO 64bit Version 22H2 (OS Build 19045.4291)

### Steps to reproduce

Разрешить любому приложению доступ по таймеру, нажать ctrl + shift + T.

### Expected behavior

Таймер удаляется, приложение теряет доступ в интернет.

### Actual behavior

Программа просто закрывается.

### Logs

Данная проблема присутствует только в версии 3.8.3, я проверил специально предыдущую версию (3.8.2), в ней все работает как положено.

**Comment by henrypp** [comment]
да,проблема есть, и она исправлена, можешь (https://t.me/henrypp_dev/87?comment=2027)[скачать исправленый бинарь]
