### ISSUE TITLE
[Bug] startup launch fail.

### ISSUE THREAD

**Issue by 074769** [henrypp/simplewall#1861]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.8.3

### Windows version

Windows 11 Pro 23H2

### Steps to reproduce

There are no steps to reproduce, after the latest windows update, simplewall, launches in the background but fails to start, so it just remains in a limbo, until i end it and re-launch it. If there is a way to log it, please let me know.

### Actual behavior

Launch on start up, and be in the tray.

**Comment by henrypp** [comment]
complete do not know what this means

**Comment by 074769** [comment]
When windows starts, simplewall starts, but it gets stuck in loading itself, so it becomes stuck until you end the process from task manager, i hope this explains it better.

**Comment by henrypp** [comment]
[test it](https://t.me/henrypp_dev/87)
