### ISSUE TITLE
[Bug] Simplewall doesnt start anymore

### ISSUE THREAD

**Issue by Buop32545** [henrypp/simplewall#1862]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.8.3

### Windows version

11

### Steps to reproduce

I can install it normaly but after a reboot it cant start up anymore i tried it on 2 devices idk what happend

### Actual behavior

Nothing

**Comment by henrypp** [comment]
[fix](https://t.me/henrypp_dev/87?comment=2027)
