### ISSUE TITLE
[Bug] Since Version 3.8.3 no start with batch

### ISSUE THREAD

**Issue by Manaplayer** [henrypp/simplewall#1864]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.8.3

### Windows version

Windows 11 23H2 / 10 22H2

### Steps to reproduce

Until version 3.8.2 i have started it with batch on windows 10 and 11.
Simplewall startets visible in task manager, but the icon does not appear in taskbar, even if a task will be doen, that is not in the settings and does not block apps.
I had delete all settings von simplewall to be clear.
Always if i use version 3.8.2, everything is ok. If start simplewall 3.8.3 without batch-script, it starts ok

### Actual behavior

Always if i use version 3.8.2, everything is ok.

**Comment by henrypp** [comment]
https://github.com/henrypp/simplewall/issues/1861#issuecomment-2323316572
