### ISSUE TITLE
[Bug] Can't start Simplewall or Uninstall it

### ISSUE THREAD

**Issue by KS1401** [henrypp/simplewall#1865]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.8.3

### Windows version

Windows 10 22H2

### Steps to reproduce

1. Go to Program Files
2. Start Simplewall as Administrator
3. And just wait

### Expected behavior

Simplewall should start as normal when starting as administrator, Also I have enabled start with startup in windows settings and such.

### Actual behavior

The mouse cursor will show a loading symbol but nothing happens.
Simplewall is running in the task manager.

In safe mode I'm able to remove and uninstall it, but the filters are still enabled. I know while uninstalling you're supposed to disable filters first, But I'm not able to even start simplewall so I'm not able to get the GUI to disable the filters.

I've tried safe mode to remove everything related to Simplewall but still the issue persists. The filters are enabled as the apps which I disabled are still disabled. I'm not able to install other version of simplewall as well. An error apears saying can't write in that location.

Please do help me out :)

**Comment by henrypp** [comment]
https://github.com/henrypp/simplewall/issues/1861#issuecomment-2323316572
