### ISSUE TITLE
[Bug]no UI / no tray icon at startup 

### ISSUE THREAD

**Issue by coupedevillechill** [henrypp/simplewall#1867]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.8.3

### Windows version

10

### Steps to reproduce

uninstall sw and remove map. reinstall

### Expected behavior

clean install should resolve

### Actual behavior

sw sometimes starts and works as expected, other times only the process is in task manager but does not seem to function. killing process and starting sw again does seem to solve the issue.

**Comment by henrypp** [comment]
pinned u didnt see?

**Comment by coupedevillechill** [comment]
Ah, I did not see it. Github noob 💯 

Thanks!!
