### ISSUE TITLE
[Question] Log Subscribe Failed

### ISSUE THREAD

**Issue by AtomixAlpha** [henrypp/simplewall#1868]
I use a batch script on my Windows computer to remove empty folders and temporary files. Recently, I've been encountering an error message that I'm not familiar with. Could you help me identify the path it's referring to and on how to resolve the issue?

![simplewall_ZF1RwPyIGQ](https://github.com/user-attachments/assets/7e7fbf24-def1-4418-9c34-474e5bf611d2)

---

App version: 3.8.3
Windows version: Windows 10 21H2 19044.4780

**Comment by henrypp** [comment]
[simplewall.zip](https://github.com/user-attachments/files/16907362/simplewall.zip)

check it, and tell me

**Comment by AtomixAlpha** [comment]
If you looking for the debug log this is what I got:
"Warning","07-09-2024 00:06:18","FwpmNetEventSubscribe","0x00000003","(null)","3.8.3","10.0 build 19044"

Also, if I click on Crash dumps, it redirects to my Desktop.

I got the following error once too:

Message:
{Path Not Found}
The path %hs does not exist.

Status:
-1073741766 (0xC000003A)

**Comment by henrypp** [comment]
this errors from zip?

**Comment by henrypp** [comment]
>  -1073741766 (0xC000003A)

this tells that it cant load library, but code is [absolute normal](https://github.com/henrypp/routine/blob/e6565859f4a54180c7e8e43c529bb058030ded5e/src/routine.c#L10335)

**Comment by henrypp** [comment]
can you find on system disk "fwpuclnt.dll"????

**Comment by AtomixAlpha** [comment]
> this errors from zip?

This error was from the your zip file (I get this from both installed and zip):
Status:
3 (0x00000003)

This I got once, both the installed app and your zip apps were running, not sure from which:
Status:
-1073741766 (0xC000003A)

> can you find on system disk "fwpuclnt.dll"???? in system32, no other directories use `loadlib` func!

![everything_K3mfQRD05D](https://github.com/user-attachments/assets/225d98cf-4ddb-42dc-9dd1-10fd0a304d70)

**Comment by henrypp** [comment]
can you write me on Telegram (in profile)? i can fix it, really
