### ISSUE TITLE
[Bug]In Windows 11 Enterprise LTSC, even though "Load on system startup" is checked, the Simplewall program does not appear after startup.

### ISSUE THREAD

**Issue by Subtly7360** [henrypp/simplewall#1870]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

v.3.8.3

### Windows version

Windows 11 Enterprise LTSC(24H2-26100.1457-Windows Feature Experience Pack 1000.26100.11.0)

### Steps to reproduce

In Windows 11 Enterprise LTSC, even though "Load on system startup" is checked, the Simplewall program does not appear after startup. However, when you open the Windows Task Manager, you can see Simplewall running. If you right-click and end the task, then manually start the Simplewall program, you can see it running.

### Actual behavior

In Windows 11 Enterprise LTSC, even though "Load on system startup" is checked, the Simplewall program does not appear after startup. However, when you open the Windows Task Manager, you can see Simplewall running. If you right-click and end the task, then manually start the Simplewall program, you can see it running.

**Comment by henrypp** [comment]
https://github.com/henrypp/simplewall/issues/1861#issuecomment-2323316572
