### ISSUE TITLE
[Question]VirusTotal Report for installer

### ISSUE THREAD

**Issue by Sanesecurity** [henrypp/simplewall#1873]
Hi,

Just a heads up that the latest installer has hits on VirusTotal:

https://www.virustotal.com/gui/file/134c36f0aa54691dd9a4b0e2b9bf784186fab90394f720aa05d504330d156cac/community

The Zip version is fine:

https://www.virustotal.com/gui/file/e65dfe9291348af6e09d3c6bea6f1709cd5833caeba0b4f2d81b38baec9fd700

**Comment by henrypp** [comment]
#1838
