### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by jonpotz** [henrypp/simplewall#1877]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

 v.3.8.4

### Windows version

windows 10

### Steps to reproduce

1. Upgrade to latest version 3.8.4 from 3.8.3.
2. Start Windows VM in VMWare Workstation
3. Not be able to connect to internet in VM.

### Expected behavior

1. Be able to connect to internet in VM.

### Actual behavior

1. Wasn't able to connect to VM until I reverted back to 3.8.3.

**Comment by henrypp** [comment]
Wasn't able to connect to VM, what it is?

**Comment by henrypp** [comment]
VirtualBox 7.10

![sshot-001](https://github.com/user-attachments/assets/aaafde80-c40a-4408-806b-0276f6fe4375)

**Comment by jonpotz** [comment]
VMWare Workstation.

Sep 12, 2024, 9:18 AM by ***@***.***:

**Comment by jonpotz** [comment]
Please close this. I beleive it was a VPN issue on my end. Sorry!

Sep 12, 2024, 9:49 AM by ***@***.***:
