### ISSUE TITLE
Text filter in main window

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#188]
Since the main window now has several groups, it's increasingly difficult to quickly find an item in the list by typing the filename: the file may be in the Special rules apps group, but you're stuck in the Allowed apps group until you've typed in the entire filename. Or worse, a filename from one folder is whitelisted, while the same filename in another folder isn't. There's no way to head to that file by typing in its name. Moreover, it's completely impossible to jump to items by typing when you show the path names.

So, I'd like to suggest that as soon as the user starts to type in the main window, a filter field would pop up and the items that don't include the typed string will be hidden from the list (until the user presses ESC or clicks a button next to the filter input field).

**Comment by whytho2000** [comment]
Adding to the thread: the colors makes it even more difficult since you can't always clearly see the highlight color. Example: select the first app you have and start typing the name of an item close to the end of the list. It always takes me a few seconds to find the selection if the item is grey (disabled notifications) or similar.

> Special rules apps makes the program more complex without a reason. Implementing tags under the name of the app could be used as an alternative.

https://github.com/henrypp/simplewall/issues/181

Many people use Glasswire even with the program itself being shit. Why? The UI/UX is really "pretty" and that's a selling point for many. I care more about the **UX** than having a pretty UI but it's something to keep it in mind.

**Comment by aphextwins** [comment]
he just removed the search feature LOL. @ltGuillaume 

> "v.2.2.7 changelog:
> removed search feature (do not used by anyone)"

I used it from time to time

**Comment by aphextwins** [comment]
The search feature was just removed LOL.

> v.2.2.7 Changelog
> removed search feature (do not used by anyone)

I did use it when it was still there. but u can actually just start typing.
for example I wanna find firefox?
I just type firefox and it finds it

**Comment by perdolka** [comment]
@aphextwins It didn't work for me.

**Comment by ltGuillaume** [comment]
No, you can't just use typing (in many cases), as I explained.

Search and filter is very different, a filter would work a lot nicer imho.

**Comment by aphextwins** [comment]
![2018-06-06_19-36-17](https://user-images.githubusercontent.com/37220822/41189174-ecd66e36-6bc9-11e8-9dd3-9329d0be6999.gif)
it works but its not a good experience

**Comment by aphextwins** [comment]
![2018-06-09_09-45-28](https://user-images.githubusercontent.com/37220822/41189183-034c66c0-6bca-11e8-8eff-be25419b53f8.gif)
It works but its not a good experience lol

**Comment by ltGuillaume** [comment]
It's "not a good experience" in the sense that you won't be able to reach some items at all.

**Comment by ltGuillaume** [comment]
It would also be great to have a filter field in Preferences -> Blocklist/System Rules/User Rules.
