### ISSUE TITLE
[Bug] simplewall.exe does not start or show the main window

### ISSUE THREAD

**Issue by deepaktrama** [henrypp/simplewall#1881]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

simplewall-3.8.4-bin.zip downloaded from github releases page

### Windows version

win 11 21h2 (os build 22000.795)

### Steps to reproduce

run simplewall.exe
simplewall.exe does not start or show the main window
the rules are still in effect because i notice that the blocked apps can still not connect to the internet.
simplewall version: simplewall-3.8.4-bin.zip downloaded from github releases page
windows version: win 11 21h2 (os build 22000.795)

tried this but to no difference:
executed simplewall\64\simplewall.exe
executed simplewall\64\simplewall.exe with run as admin
executed simplewall\32\simplewall.exe
downloaded new version simplewall-3.8.4-bin.zip and executed

suggestions:
simplewall did popup asking to upgrade but i refused, maybe this has triggered it.

### Expected behavior

main window should come up

### Actual behavior

nothing happens

**Comment by henrypp** [comment]
cant reproduce, any error log in profile directory? can you made process dump?

**Comment by henrypp** [comment]
where is simplewall.ini placed for dump [use this](https://github.com/winsiderss/[systeminformer](https://github.com/winsiderss/systeminformer))

**Comment by deepaktrama** [comment]
simplewall is working now - I am not sure why this issue occured or if it will occur again.
if it has written any kind of log then let me know the path and I can forward it to you.
additional details below.

dir listing
c:\DeepakStuff\apps\simplewall\64\profile.xml.bak
c:\DeepakStuff\apps\simplewall\64\portable.dat
c:\DeepakStuff\apps\simplewall\64\simplewall.exe
c:\DeepakStuff\apps\simplewall\64\simplewall.ini
c:\DeepakStuff\apps\simplewall\64\simplewall.lng
c:\DeepakStuff\apps\simplewall\64\simplewall.exe.sig
c:\DeepakStuff\apps\simplewall\64\History.txt
c:\DeepakStuff\apps\simplewall\64\License.txt
c:\DeepakStuff\apps\simplewall\64\Readme.txt
c:\DeepakStuff\apps\simplewall\64\profile.xml

contents of simplewall.ini below.
[simplewall]
CheckUpdatesLast=1726587685
WF_State=true
IsWUFixEnabled=false
BackupTimestamp=1726587433
SettingsLastPage=116
BlocklistUpdateState=1
CurrentTab=106
[simplewall\notification]
Position=363,246
[simplewall\window]
IsMaximized=true

profile.xml contents:
<?xml version="1.0" encoding="UTF-8"?>
<root version="5" type="3" timestamp="1726588042">
	<apps>
		<item path="CryptSvc" timestamp="1622895065" is_undeletable="true"/>
		<item path="Dhcp" timestamp="1622895065" is_undeletable="true"/>
		<item path="Dnscache" timestamp="1622895117" is_undeletable="true"/>
		<item path="DoSvc" timestamp="1657856962" is_undeletable="true"/>
		<item path="NlaSvc" timestamp="1622895064" is_undeletable="true"/>
		<item path="Spooler" timestamp="1622895064" is_undeletable="true"/>
		<item path="UsoSvc" timestamp="1622895064" is_undeletable="true"/>
		<item path="wlidsvc" timestamp="1622895117" is_undeletable="true"/>
		<item path="wuauserv" timestamp="1651205551" is_undeletable="true"/>
		<item path="S-1-15-2-2015459320-3065076763-404414554-287452219-753456662-3251378790-3436244644" timestamp="1724702671" is_silent="true"/>
		<item path="S-1-15-2-1344983377-2937691957-1007372696-2796762694-2894907387-1141423975-3266206130" timestamp="1724595797" is_silent="true"/>
		<item path="S-1-15-2-2967553933-3217682302-2494645345-2077017737-3805576244-585965800-1797614741" timestamp="1724704413" is_silent="true"/>
		<item path="S-1-15-2-283421221-3183566570-1718213290-751554359-3541592344-2312209569-3374928651" timestamp="1724702615" is_silent="true"/>
		<item path="C:\Windows\system32\SppExtComObj.exe" timestamp="1724911572" is_undeletable="true"/>
		<item path="C:\Windows\system32\lsass.exe" timestamp="1724911572" is_undeletable="true"/>
		<item path="C:\DeepakStuff\apps\simplewall\64\simplewall.exe" timestamp="1724911572" is_undeletable="true" is_enabled="true"/>
		<item path="System" timestamp="1724911572" is_undeletable="true" is_silent="true"/>
		<item path="C:\Windows\system32\svchost.exe" timestamp="1724911572" is_undeletable="true" is_silent="true"/>
		<item path="C:\program files (x86)\microsoft\edge\application\msedge.exe" timestamp="1724911650" is_silent="true"/>
		<item path="C:\program files\google\chrome\application\chrome.exe" timestamp="1724911652" is_silent="true" is_enabled="true"/>
		<item path="C:\program files\nvidia corporation\nvcontainer\nvcontainer.exe" timestamp="1724911656" is_silent="true"/>
		<item path="C:\program files\common files\microsoft shared\clicktorun\officeclicktorun.exe" timestamp="1724911740" is_silent="true"/>
		<item path="C:\windows\system32\smartscreen.exe" timestamp="1724911753" is_silent="true"/>
		<item path="C:\deepakstuff\apps\thorium_119.0.6045.214\bin\thorium.exe" timestamp="1724911785" is_enabled="true"/>
		<item path="C:\windows\lenovo\imcontroller\pluginhost86\lenovo.modern.imcontroller.pluginhost.device.exe" timestamp="1724911968" is_silent="true"/>
		<item path="C:\program files (x86)\google\googleupdater\129.0.6651.0\updater.exe" timestamp="1724912741" is_silent="true"/>
		<item path="C:\programdata\microsoft\windows defender\platform\4.18.24040.4-0\mpdefendercoreservice.exe" timestamp="1724913087" is_silent="true"/>
		<item path="C:\windows\system32\taskhostw.exe" timestamp="1724914585" is_silent="true"/>
		<item path="C:\program files (x86)\bravesoftware\update\braveupdate.exe" timestamp="1724915439" is_silent="true"/>
		<item path="C:\windows\system32\devicecensus.exe" timestamp="1724915455" is_silent="true"/>
		<item path="C:\program files\common files\microsoft shared\clicktorun\officec2rclient.exe" timestamp="1724915455" is_silent="true"/>
		<item path="C:\windows\immersivecontrolpanel\systemsettings.exe" timestamp="1724919191" is_silent="true"/>
		<item path="C:\program files\microsoft office\root\office16\sdxhelper.exe" timestamp="1724920042" is_silent="true"/>
		<item path="C:\windows\system32\wermgr.exe" timestamp="1724921156" is_silent="true"/>
		<item path="C:\windows\uus\amd64\mousocoreworker.exe" timestamp="1724921871" is_silent="true"/>
		<item path="C:\users\abcd\appdata\local\nhnotifsys\nahimic\nahimicnotifsys.exe" timestamp="1724924387" is_silent="true"/>
		<item path="C:\windows\system32\rundll32.exe" timestamp="1724926795" is_silent="true"/>
		<item path="C:\windows\syswow64\werfault.exe" timestamp="1724928252" is_silent="true"/>
		<item path="C:\program files (x86)\microsoft\edgeupdate\microsoftedgeupdate.exe" timestamp="1724932602" is_silent="true"/>
		<item path="C:\deepakstuff\apps\operaportable64\68.0.3618.56\opera.exe" timestamp="1724940772" is_enabled="true"/>
		<item path="C:\deepakstuff\apps\operaportable64\68.0.3618.56\opera_autoupdate.exe" timestamp="1724940775" is_silent="true"/>
		<item path="C:\windows\system32\wbem\wmiprvse.exe" timestamp="1724965906" is_silent="true"/>
		<item path="C:\windows\system32\sihclient.exe" timestamp="1724967111" is_silent="true"/>
		<item path="C:\programdata\microsoft\windows defender\platform\4.18.24040.4-0\mpcmdrun.exe" timestamp="1725037868"/>
		<item path="C:\programdata\microsoft\windows defender\platform\4.18.24070.5-0\mpdefendercoreservice.exe" timestamp="1725037929" is_silent="true"/>
		<item path="C:\program files\windowsapps\microsoftwindows.client.webexperience_421.20070.565.0_x64__cw5n1h2txyewy\dashboard\widgets.exe" timestamp="1725038073" is_silent="true"/>
		<item path="C:\windows\system32\werfault.exe" timestamp="1725044698" is_silent="true"/>
		<item path="C:\windows\system32\driverstore\filerepository\nvlt.inf_amd64_9bfed4a7b51c0204\display.nvcontainer\nvdisplay.container.exe" timestamp="1725044699" is_silent="true"/>
		<item path="C:\windows\system32\dashost.exe" timestamp="1725102160" is_silent="true"/>
		<item path="C:\windows\lenovo\imcontroller\pluginhost\lenovo.modern.imcontroller.pluginhost.device.exe" timestamp="1725102298" is_silent="true"/>
		<item path="C:\windows\lenovo\imcontroller\service\lenovo.modern.imcontroller.exe" timestamp="1725105428" is_silent="true"/>
		<item path="C:\windows\system32\drivers\lenovo\udc\service\udclientservice.exe" timestamp="1725370880" is_silent="true"/>
		<item path="C:\program files (x86)\microsoft\edgewebview\application\122.0.2365.92\msedgewebview2.exe" timestamp="1725445093" is_silent="true"/>
		<item path="C:\deepakstuff\apps\rpcs3-v0.0.33-16892-7e3b8b5c_win64\rpcs3.exe" timestamp="1725474210" is_enabled="true"/>
		<item path="C:\program files (x86)\nvidia corporation\nvnode\nvidia web helper.exe" timestamp="1725959142" is_silent="true"/>
		<item path="C:\program files (x86)\x-rite color assistant\xritecolorassistant.exe" timestamp="1725959145" is_silent="true"/>
		<item path="C:\deepakstuff\apps\systeminformer-3.0.7660-release-bin\amd64\systeminformer.exe" timestamp="1726587878" is_silent="true"/>
	</apps>
	<rules_custom>
	</rules_custom>
	<rules_config>
	</rules_config>
</root>

**Comment by henrypp** [comment]
maybe you use 3.8.3 which have bug with starting? but upgrade to 3.8.4 and all works well

**Comment by deepaktrama** [comment]
Thanks for your support, so is this known issue in 3.8.3 64 bit?

**Comment by henrypp** [comment]
y

**Comment by deepaktrama** [comment]
it's happening again right now and i have found a workaround, it seems the simplewall.exe process is still running in the background and after killing it using task manager and running 3.8.4 executable it works but my rules are all gone, then i exit 3.8.4 and run the 3.8.3 executable and that works too. I have now upgraded it from within 3.8.3 gui and my rules are back.
