### ISSUE TITLE
[Bug] Heavy Load makes SimpleWall unresponsive

### ISSUE THREAD

**Issue by EnfLzSp** [henrypp/simplewall#1885]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.8.4

### Windows version

Windows 11

### Steps to reproduce

Start JediSurvivor.exe (Denuvo removed in the latest patch). The game keep trying to make so many connections that SimpleWall simply becomes unresponsive and requires manual restart to continue working.

### Expected behavior

SimpleWall continues to be responsive even under heavy load.

### Actual behavior

SimpleWall stops being responsive under heavy load.

### Logs

None

**Comment by henrypp** [comment]
![sshot-001](https://github.com/user-attachments/assets/c8cebe03-b133-461a-830f-b7bd842551f7)

already has option for this, check your settings

**Comment by EnfLzSp** [comment]
Packet notification was disabled completely. SimpleWall became unresponsive when there were many connection attemps when looking at "Package Log" section. Again, Packet notification was not enabled.

**Comment by henrypp** [comment]
if "packets log ui" unresponsive, use log to file, i think i can made more responsivenes for "packets log ui", in future!
