### ISSUE TITLE
[Bug] Simplewall looses app rule when app file is deleted

### ISSUE THREAD

**Issue by OneForgottenMan** [henrypp/simplewall#1886]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.8.4

### Windows version

Windows 7 SP1

### Steps to reproduce

1. Run SFX app, which unpacks itself into temp folder (path is always the same)
2. Give unpacked app access to internet
3. Close app (the unpacked app is deleted from temp)
4. Run app again

### Expected behavior

Simplewall should check that application with that path already exists in list and use existing rule. (This was the case when I was on 3.6, I just recently jumped to 3.8)

### Actual behavior

Simplewall looses an added application after its file is deleted, as a result, a deleted application in the list now points to just "C:\".
![explorer_3EZGZWCV2T](https://github.com/user-attachments/assets/e1b09878-0b4c-4595-bd33-bd223edde1f9)

**Comment by henrypp** [comment]
https://github.com/henrypp/simplewall/issues/1887#issuecomment-2371818015
