### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by 10011968** [henrypp/simplewall#1888]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.8.4

### Windows version

11

### Steps to reproduce

1 go to service tab 2 scroll down to apps without internet access 3 the list of app with internet access keeps updating 

### Expected behavior

when i scroll down i need time to identify the service i want to enable and click on it

### Actual behavior

the list keeps refreshing so the lines of services is in motion, very difficult to select and click

**Comment by henrypp** [comment]
> 1 go to service tab 2 scroll down to apps without internet access 3 the list of app with internet access keeps updating

**Comment by 10011968** [comment]
Strange,,, did you spend more than ten seconds reading through the services list? It starts refreshing and moves down making it  quasi impossible to follow a specific one you'd want to click onto to enable web access.

**Comment by henrypp** [comment]
where?
https://github.com/user-attachments/assets/2294be63-d774-40af-8c02-330077138e7c

**Comment by Janaue** [comment]
@henrypp 
hi, i suffer from the same bug, it's only the tab "Services" which always reload. I thought I was the only one having this  bug lol.

windows is w10 version 10.0.19044.6937 and simplewall is portable simplewall-3.8.7-bin. Stock profile and config. I made a little gif.

 
<img width="1902" height="960" alt="Image" src="https://github.com/user-attachments/assets/4872f116-0a71-44d4-b837-7ed7ca629b51" />

**Comment by Janaue** [comment]
the last bug-free version is simplewall-3.7.8-bin for me

**Comment by henrypp** [comment]
@Janaue 

try restart app

**Comment by Janaue** [comment]
do you mean close simplewall and launch it again ? if so this UI bug occurs at each launch

**Comment by henrypp** [comment]
@Janaue

try this bin,, it latest commit, if same with tab then dump with processhacker SW process and uplod dump here

[simplewall.zip](https://github.com/user-attachments/files/26762446/simplewall.zip)

**Comment by Janaue** [comment]
@henrypp 
okay first simplewall_8.7 bug UI is the dump from the release in august 2025
https://www.mediafire.com/file/uqzahbtk398klg9/simplewall_8.7_bug_UI.dmp/file
this is the dump for the modified exe
https://www.mediafire.com/file/n8fbguxref3nzv4/simplewall.exe.dmp/file

**Comment by Janaue** [comment]
it is corrected in 3.9.1 nice !
