### ISSUE TITLE
Override blocklist rules, Allow inconsistency

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#189]
1. Enable all extra_* blocklist rules
2. Disable `Exclude blocklist entries` in `Dropped packets log`
3. Try to open Outlook web mail

A pop-up shows that the IP is blocked. The pop-up suggests that it is possible to create a custom rule in order to allow the IP (e.g. only for this browser). Clicking Allow will give no visual feedback that it actually didn't create a custom rule at all.

Personally, I think it should indeed be possible for custom rules to override the blocklist entries (for a specified application). Currently, simplewall does not, but it also doesn't tell the user that it can't.

**Comment by henrypp** [comment]
No. Blocklist are undeniable until you switch entry off.
And i did not understand why do you use _extra_ entries and wonder why outlook did not worked, _extra_ entries is not spying, its a M$ 3-rd party services (like Outlook and other shit).

**Comment by ltGuillaume** [comment]
I was making a point about simplewall's behavior by using the extra_* rules
as an example. Not just about user rules that really should be able to
override the blocklist rules, but about how simplewall gives the suggestion
that you in fact  _can_ create such a user rule via the pop-up dialog.

A use case where overriding the blocklist rules comes in handy is when
you're testing in a virtual machine: I would like to test some Microsoft
feature that seems broken in a virtual machine in order to find out if it
is indeed one of the blocklist rules that causes the issue, without the
host system itself being affected by the disabling of the block rule. For
example, in the past both a spy and an update rule had been preventing the
Store from working.

If this technically impossible to realize, that's a different thing
altogether, but I would imagine that WFP rules work like CSS rules: the
more specific the rule, the higher priority.
