### ISSUE TITLE
[Bug] Impossible to make a permanent rule for a specific app

### ISSUE THREAD

**Issue by sbbddz** [henrypp/simplewall#1891]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.8.4

### Windows version

10.0.22621.4169

### Steps to reproduce

1. Start, in this case, Microsoft Flight Simulator.
2. Notification of app wanting to get internet access appears.
3. Accept it. Restart the game for it to check internet for its activation protocol.
4. Notice the notification of the app wanting to get internet access appears another time.
5. Check in the control panel for the rule: 
![imagen](https://github.com/user-attachments/assets/ebabc5ed-be84-4f0d-86cd-18e28f3eb9cd)
Rule is there.
6. Refresh with the refresh button and watch it disappear and notification appearing another time.
![imagen](https://github.com/user-attachments/assets/b45d2177-c8ac-4ef1-aa57-72356ca94839)

I also tryed adding it manually and got permission denied to the executable (even running simplewall as admin), could this be related to the issue?
![imagen](https://github.com/user-attachments/assets/195f50bc-484c-43e6-9c9e-8619d1caa221)

### Expected behavior

App to actually being allowed to access internet

### Actual behavior

App never gets allowed internet access. Can't add manually and allowing in the notification popup is not working.

**Comment by osagem** [comment]
the same for me.
microsoft flight simulator 1.38.2.0. flightsimulator.exe is allowed, but the blocked message pop-up always again.
check the exe file has not signed.
Is there a solution to this recurring popup?

**Comment by thesimg** [comment]
Same here, with minecraft.exe, the Minecraft Launcher. I have tried to make specific rules for it, accept the notification popup, and allow the address that it is requesting. None have been successful.

**Comment by h7896v7347** [comment]
Same problem with new call of duty BO6 on Xbox Game Pass PC. It is working fine on older  3.7.2 build.

Gamepass game install path is  protected, and newer versions of Simplewall are removing game path even when exported. 

Gamepass games also have problems with other apps - Geforce Experience/Shadowplay; Mouse keybinds detection in Steelseries

**Comment by laine** [comment]
Using [https://github.com/henrypp/simplewall/issues/1528#issuecomment-1711294888](This build) fixed all issues from me.

**Comment by sbbddz** [comment]
Can confirm that 3.7 release works fine for me

**Comment by element0xE** [comment]
There are several open issues related to the same problem.

This issue affects all games on the Xbox App. Using version 3.7 serves as a workaround, but it is an outdated build, over a year old. I recommend marking this as a bug.

**Comment by henrypp** [comment]
@element0xE, @sbbddz

 hello, can you test this build, please?

i think problem is gone

[simplewall.zip](https://github.com/user-attachments/files/17739337/simplewall.zip)

**Comment by laine** [comment]
@henrypp that update seems to work for me on the latest winver & on latest cod title update, thank you!

**Comment by Eniti-Codes** [comment]
Sorry for being a few days late. I was busy at work.
So for some reason, Simple Wall will not allow me to keep Minecraft getting internet connection.

Here's a video of what's happening.
https://youtu.be/xqQSBUZDGBg
