### ISSUE TITLE
[Feature] Automatically download update if one is found after automatic check

### ISSUE THREAD

**Issue by GingrPowr** [henrypp/simplewall#1892]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.8.4

### Problem you are trying to solve

At launch, SP check for new updates, and if one is found it asks the user if they want to download it.

### Suggested solution

Add an option to automatically download an update if one is found, instead of prompting to the user.

**Comment by henrypp** [comment]
you did not see checkbox?
![sshot-001](https://github.com/user-attachments/assets/d0f3f3ca-ec1d-4bc0-abcc-8f237768f2ed)

**Comment by GingrPowr** [comment]
The app didn't update past 3.7.1, so I didn't realised there were new versions :|
