### ISSUE TITLE
[Question] Default No Filtering after installing

### ISSUE THREAD

**Issue by idwowrack** [henrypp/simplewall#1897]
On remote access, installing this superb application for filtering will be an issue without direct/shell/terminal access on the host.
**How to install this application with default no filtering at the first runtime**, since looks like it will be interrupting the mstsc/remote desktop connection?

---

App version: 3.7.8
Windows version: 22H2 (19045)

**Comment by henrypp** [comment]
no filtering is default state after starting, thats all time will be
