### ISSUE TITLE
No ability to utilise DNS C-NAME resolve in firewall filters' configuration. Perhaps using a configuration specified DNS server could be acceptable.

### ISSUE THREAD

**Issue by MMihelic** [henrypp/simplewall#19]
Without the ability to resolve host IP in filter configuration some services hosted at short-lived DNS names are impossible to use. An example of such service is a SSTP based VPN on a dynamic host. 
Without the IP, one has to resort to an extremely generic port based rule (allow TCP 443) for some Microsoft core processes thereby giving them very broad permissions.
These also seem to be an anomaly in DNS resolving in Windows 10 during VPN initiation phase of the built-in VPN. Until I have explicitly allowed UDP communication on port 53 the VPN was unable to resolve the hostname configured - even with the system rule "DNS+LLMNR" enabled! The process trying to resolve the IP was "svchost.exe."
I know that I can probably use a HOSTS updater to get around the DDNS VPN hostname resolution, but a general solution would be more user friendly.

**Comment by henrypp** [comment]
are you used OpenVPN?

**Comment by MMihelic** [comment]
No, I am using SoftEther.
Regards, Matej.
