### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by perdolka** [henrypp/simplewall#190]
У меня в Windows 10 (1803) не работает опция Spotlight (Интересное) - 
компонент Content Delivery Manager, просто не скачивает новые картинки.
Никакие перерегистрации и прочие советы из гугла не помогают.

Может ли одно из правил SimpleWall (spy-правила или мой чёрный список) 
блокировать работу Content Delivery Manager?

Я пробовал временно выключить фильтрацию (с включением брандмауэра Windows) - это не помогло (spy-правила не выключал).

**Comment by henrypp** [comment]
Ну если отключали фильтрацию и это не помогло, то это не simplewall. Правила при выключенной фильтрации не работают.
