### ISSUE TITLE
[Question] Need help restoring pre-download behavior

### ISSUE THREAD

**Issue by Natix1** [henrypp/simplewall#1903]
Describe the question with as much detail as possible.

I have installed this software as I was tired with having to add 4 different rules in default windows firewall app just to open a port, and now I am left with most applications having no internet access. I only launched the app, tried adding a UDP rule and pressed enable filtering, and now even after multiple reinstalls of the app and PC restarts all my apps have no internet. I couldn't find anything in the windows firewall. I am also sure it's simplewall at fault. Note this is my first time using this software.

I simply want to restore app internet access and never touch this again

Thanks,
Nathan

App version: v.3.8.4
Windows version: Windows 11 Home 23H2 (OS build 22631, 4391)

**Comment by henrypp** [comment]
that because WF do not block access for ALL applications, in SW it simple as life, just watch notifications and press for allow/block, all you need you get, not easy?

**Comment by Natix1** [comment]
Thank you for the helpful instructions to resolve the issue

But seriously, following your "all you need you get" l, the only thing I need is to never touch this awful project and you to be brutally murdered.

**Comment by henrypp** [comment]
> ...to be brutally murdered.

LOL
