### ISSUE TITLE
[Question] Internet stops working if Windows Firewall is enabled along with simplewall

### ISSUE THREAD

**Issue by thatspix** [henrypp/simplewall#1904]
I am not sure what happened but when I enable windows firewall while simplewall is running and the filters are enabled, my internet stops working. I am relatively new to using simplewall so I don't know much of the deep end 😅

---

App version: v3.8.4
Windows version: Windows 11 Pro 24H2 (Build: 26120.2200)

**Comment by henrypp** [comment]
so, shut it down
