### ISSUE TITLE
[Question] minecraft launcher has no internet connection

### ISSUE THREAD

**Issue by Eniti-Codes** [henrypp/simplewall#1905]
So I am currently having a problem with the Minecraft Java Edition launcher not getting internet connection. I have enabled all these services that I can possibly enable, through simple firewall. Without compromising my security.

I have tried doing research and trying various other methods, even looking at Windows firewall to see what service is trying to call out. But I got no hits. The only way that I'm able to play with the Minecraft launcher is Using Windows built-in firewall.

I would consider myself a advanced Windows user, but I am still currently learning simple firewall, so I could have messed up something as well.

---
App version: 3.8.4
Windows version: Windows 10 Home 22H2
---

Note.
I have internet connection to all the other Microsoft products that I use on a daily basis other than the Minecraft launcher. It seems like that's the only problem.

**Comment by thormster-renard** [comment]
Same problem here. Only deactivating simplewall allows the launcher to regain internet connection.
