### ISSUE TITLE
Windows Firewall remains on?

### ISSUE THREAD

**Issue by leekslk** [henrypp/simplewall#191]
Hey there, great work on the simplewall, I really like this piece of software. Been using it ever since I migrated from macOS to Windows 10.

Just a question (I'm sorry for posting it as an issue on GitHub), the new update seems to ignore the fact that Windows Firewall is running at the same time? I have an impression that a couple of months ago, it would disable Windows Firewall running in the background (or something along those lines).

Let me know if it is normal behavior of the new update.

**Comment by beerisgood** [comment]
Windows Firewall is part of Windows Security and you cant fully disable it. So its okay to have it enabled

**Comment by leekslk** [comment]
thanks, but it's just that I get two prompts when starting a new application / protocol. Once from the windows firewall, then again from simplewall

**Comment by henrypp** [comment]
On Windows 10 RS4 (and above) You can disable WF profiles through command line (admin rights):

> netsh advfirewall set allprofiles state off

when you need to restore profiles then use:

> netsh advfirewall set allprofiles state on

**Comment by leekslk** [comment]
@henrypp thanks! thought I was missing something. Cheers!

**Comment by henrypp** [comment]
[Added to FAQ](https://github.com/henrypp/simplewall/wiki/FAQ#how-can-i-disable-windows-firewall)
