### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Evertonlps** [henrypp/simplewall#1911]
À partir da última versão, aparece o disco C: na lista de permissões e (não sei se por isso) tive problemas de boot logo após a instalação do firewall e primeiro reinicio do sistema , necessitando de uma nova instalação, pois não foi possível recuperar o boot. Isso pode ser por causa do Simplewall?

> Google Translate:

Since the latest version, disk C: appears in the permissions list and (I don't know if that's why) I had boot problems right after installing the firewall and restarting the system for the first time, requiring a new installation, as it was not possible to recover the boot. Could this be because of Simplewall?

I don't have a screenshot, as I formatted it and didn't install it again.

App version: 3.8.4
Windows version: Windows 11 24H2

**Comment by jim0** [comment]
I came here to ask about the same thing... it looks very odd, and I was never asked to add or block this "C:\" entry.
