### ISSUE TITLE
[Bug] Log file cannot be saved to directory with "Space" in the name

### ISSUE THREAD

**Issue by cinke** [henrypp/simplewall#1912]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.8.4

### Windows version

Win 11 Pro, 22631.4460

### Steps to reproduce

1. Have a user name with a space in it (John Doe)
2. Click on Open log file icon
3. Error message: C:\Users\John doesn't exist, create is?
4. Save it to any other directory, and it is OK.

### Expected behavior

Save log file to C:\Users\John Doe\simplewall.log

### Actual behavior

Log file not opened, error message displayed.

**Comment by henrypp** [comment]
now checked and cannot reproduce, on win11 notepad open log correctly with spaces in path

**Comment by cinke** [comment]
It is an issue with notepad++, which I used as log file viewer. 
It seems it only catches the section of the log file path, that is after the space. 

Switching the log file viewer app to windows notepad resolved this issue.

**Comment by henrypp** [comment]
it is already fixed, so wait for release
