### ISSUE TITLE
[Suggestion] Option to only raise the notification popup for new apps

### ISSUE THREAD

**Issue by kmsdne** [henrypp/simplewall#192]
Would be cool to have an option to only raise the notification popup window for newly added apps.

It wouldn't change anything about the current notification behavior, it just wouldn't show the notification popup on the screen (onTop) but if you hover over the simplewall tray icon the notification window would be there like normally.

Why? For apps that you don't want to disable notifications but still want to know if they tried to connect without showing the annoying notification all the time. The workaround would be to disable notifications and manually look at the log but that's too much work.

We wouldn't need this option if there was a way to check the parsed log directly in the UI, with app icons and some nice formatted table but I don't know if that's something the project owner would like to add.

**Comment by ProNoobGH** [comment]
Download csvfileview.exe utility from Nirsoft. [https://www.nirsoft.net/utils/csv_file_view.html](url)
Add line "LogViewer=.\csvfileview.exe" in simplewall.ini.

**Comment by henrypp** [comment]
@ProNoobGH [added to FAQ](https://github.com/henrypp/simplewall/wiki/FAQ#how-can-i-use-3-rd-party-software-to-view-log)

**Comment by henrypp** [comment]
@kmsdne you can set "Timeout between same notifications" to maximum to do not show same apps every 5 seconds.

**Comment by perdolka** [comment]
@henrypp
А какой максимум? 
Больше 1800 сек. - сбрасывается. 
Может увеличить лимит?

**Comment by henrypp** [comment]
Yoy can set 

> NotificationsTimeout=43200

in simplewall.ini and then restart simplewall. In next release range will be increased.
