### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by tokariu** [henrypp/simplewall#193]
I commonly see simplewall taking huge amounts of RAM, by huge I mean more than 3 GB of RAM. After I've seen that I restarted simplewall just to see that after about 4mins of runtime it's again heading towards 3 gigs of ram usage. 

![simplewall](https://user-images.githubusercontent.com/7195846/41243637-f3770e1e-6da2-11e8-98a5-2b6ddf136d69.gif)

I don't know if this is normal, but it seems a bit odd to take this amount of ram for it's normal usage.

(simplewall v2.2.12 x64)

**Comment by tokariu** [comment]
seems I can narrow the leak to a certain process/game right now. I was playing Tomb Raider 4, and i think it asked to connect to the internet (notification) and I blocked it and dismissed further notifications. I think the notification process was rundll32.exe.  After that the memory usage of simplewall.exe exploded literally to almost 4GB of ram over a short amount of time.

`rundll32.exe *32 | C:\Windows\system32\rundll32.exe C:\Windows\system32\gameux.dll,GameUXShim {8bc9195c.....806fba};C:\games\Tomb4\tomb4.exe,8824`

**Comment by henrypp** [comment]
Can you have Process Hacker? If you please open simplewall.exe process properties and go to Threads tab. Take a picture please.
![sshot_1](https://user-images.githubusercontent.com/3902025/41301307-8ad4c300-6e89-11e8-9ec1-7ed74362834d.png)

**Comment by tokariu** [comment]
here it is:
![swall](https://user-images.githubusercontent.com/7195846/41342023-8492b17e-6efb-11e8-967e-c6d9565b6989.png)

**Comment by henrypp** [comment]
hey, check this binaries, it's pre-2.3 beta (but named 2.2.666 LOL)
i hope some misstakes and critical bugs was fixed.

ps: all worked well, except `hosts does not worked` and ` new rules editor does not finished`. 

https://www.henrypp.org/files/r/

**Comment by ProNoobGH** [comment]
> ps3: @tokariu so old PH - less info displayed.

Not version PH. He needs to set necessary settings. https://wj32.org/processhacker/faq.php

Options PH > Symbols Tab >
C:\Windows\system32\dbghelp.dll
srv*http://msdl.microsoft.com/download/symbols

**Comment by ProNoobGH** [comment]
[v2.2.x] Memory leak when calling "Refresh F5" function.

**Comment by henrypp** [comment]
@ProNoobGH, fixed, check build 667

**Comment by ltGuillaume** [comment]
666 was indeed evil: upon minimize or close, the tray icon disappeard :-P 667 works.
What's more, I got this the first time it started, although I get this often since any v2.2 version.
![image](https://user-images.githubusercontent.com/4777345/41374457-7e59c6fa-6f53-11e8-8556-98e992f11da3.png)

**Comment by henrypp** [comment]
@ltGuillaume 
> What's more, I got this the first time it started, although I get this often since any v2.2 version.

let me see your `rules_custom.xml` file

**Comment by ltGuillaume** [comment]
There you go (link expires in a month): https://bin.disroot.org/?e5c9b56c5832d514#uUK+PSp7xZI9/bM7o9vuM2V5/hNT9exwcP43iZ4xiuw=

**Comment by henrypp** [comment]
@tokariu @ltGuillaume memory leak was fixed, but how about notifications? Still missing? #154

**Comment by henrypp** [comment]
@@ltGuillaume this rule is not being worked.
![sshot_1](https://user-images.githubusercontent.com/3902025/41424228-43ef0eb8-701f-11e8-8e41-f26d08d24f4f.png)

**Comment by henrypp** [comment]
Hi! There is opened Telegram channel to discuss about new hotfix 2.3 pre-release.
New pre-release versions will be published on this channel, no official beta testing will be, only Telegram discussion.

Please follow:
https://t.me/simplewall_beta

**Comment by ltGuillaume** [comment]
@henrypp Yeah, not using that anyway. Basically I'd like to have a custom rule that allows Windows' IKEv2 VPN traffic, without allowing any other Windows services' traffic to seep through.

**Comment by henrypp** [comment]
Memory leaks (2) was fixed in 2.3
