### ISSUE TITLE
[Feature] Allow Internet Connectivity Indicator through Simplewall

### ISSUE THREAD

**Issue by Hunanbean-Collective** [henrypp/simplewall#1931]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

3.8.5

### Problem you are trying to solve

Internet connectivity icon is not valid of actual state.   Simplewall is blocking the ping that allows internet connectivity icon to work.  

### Suggested solution

please allow through, or explain How to allow through.

**Comment by henrypp** [comment]
already have, system rules, enable "NCSI"

**Comment by Hunanbean-Collective** [comment]
![image](https://github.com/user-attachments/assets/aaa29dda-d97c-4815-8027-e497920a0518)
Already Enabled.   Could there be another setting?
Also, sorry i missed that. i checked open issues, but neglected to check closed issues

**Comment by Hunanbean-Collective** [comment]
@henrypp In case it was missed.  The Rule is and was enabled already and it still does not allow it to work properly.

**Comment by henrypp** [comment]
@Hunanbean-Collective subj has packets logging, you can see what is blocked and open required ports
