### ISSUE TITLE
Windows Firewall entries in log is ok?

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#195]
I have enabled simplewall in whitelist mode and disabled Windows (Defender) Firewall. I have confirmed it's off via the "Windows Defender Firewall with Advanced Security" dialog.

In the simplewall logs I see entries like these:
`AUTHORITY\LOCAL SERVICE,C:\windows\system32\svchost.exe,192.168.x.x:53 (myrouter) (Remote),192.168.x.x:56551 (mypc) (Local),UDP,Microsoft Windows Defender Firewall Provider\Blocks all inbound traffic for services who have been network hardened,#925525,OUT`

Is this the desired behavior?

**Comment by henrypp** [comment]
Do you try reboot? WF cannot be disabled entirely in win10RS4+.

**Comment by ltGuillaume** [comment]
I'm not using RS4, I'm on 1709 (RS3). I know that the service can't be disabled, but as said I can see some actual rules that are still active. Does this also fall under "WF cannot be disabled entirely"?

**Comment by henrypp** [comment]
Try [this](https://github.com/henrypp/simplewall/wiki/FAQ#how-can-i-disable-windows-firewall) and then reboot.

**Comment by ltGuillaume** [comment]
`netsh advfirewall set allprofiles state off` works, the others return Access Denied (in elevated Command Prompt), so either it's already RS3 that prevent full disabling, or one of the cumulative Updates changed this behavior in RS3. (I have done an NTLite'd Host Refresh with the June 12 Cumulative Update yesterday).
