### ISSUE TITLE
multiple issues found in new 2.3

### ISSUE THREAD

**Issue by LazyZhu** [henrypp/simplewall#198]
1. rules are limited to 128 bytes now
[reserved ips](https://en.wikipedia.org/wiki/Reserved_IP_addresses) rule not working anymore:
`0.0.0.0/8;10.0.0.0/8;100.64.0.0/10;127.0.0.0/8;169.254.0.0/16;172.16.0.0/12;192.0.0.0/24;192.0.2.0/24;192.88.99.0/24;192.168.0.0/16;198.18.0.0/15;198.51.100.0/24;203.0.113.0/24;224.0.0.0/4;240.0.0.0/4;255.255.255.255/32`
`::/128;::1/128;::ffff:0:0/96;64:ff9b::/96;100::/64;2001::/32;2001:10::/28;2001:20::/28;2001:db8::/32;2002::/16;fc00::/7;fe80::/10;ff00::/8`
2. broken rule will stop simplewall block apps, you need make sure your rule are valid.

**Comment by henrypp** [comment]
It's all working, but maximum rule length will decreased to [128 words length](https://github.com/henrypp/simplewall/blob/f47987ba94d9823dc94d76d7d7c0ca15636989f3/src/main.hpp#L116) for technical purposes. you have 359.

**Comment by LazyZhu** [comment]
Are you even tested before close this issue?

because 128 limited,old version rule like `::/128;::1/128;::ffff:0:0/96;64:ff9b::/96;100::/64;2001::/32;2001:10::/28;2001:20::/28;2001:db8::/32;2002::/16;fc00::/7;fe80::/10;ff00::/8` will cut to `::/128;::1/128;::ffff:0:0/96;64:ff9b::/96;100::/64;2001::/32;2001:10::/28;2001:20::/28;2001:db8::/3 2;2002::/16;fc00::/7;fe80::/1`. this rule is invalid because `fe80::/1` is  invalid and can't process, result in simpewall will not block any apps.

Test Step:
1. install old version before 2.3, add rule `::/128;::1/128;::ffff:0:0/96;64:ff9b::/96;100::/64;2001::/32;2001:10::/28;2001:20::/28;2001:db8::/32;2002::/16;fc00::/7;fe80::/10;ff00::/8`
2. close simplewall and upgrade to 2.3, start  simplewall, run any blocked apps, you will found simplewall didn't block internet connect.

PS:
RULE_RULE_CCH_MAX  shpuld add to 256

**Comment by 123321** [comment]
suggestion

https://stackoverflow.com/questions/7026824/example-of-unit-tests-preventing-regression

https://github.com/search?l=C%2B%2B&o=desc&q=test&s=stars&type=Repositories

https://stackoverflow.com/questions/520064/what-is-unit-test-integration-test-smoke-test-regression-test

**Comment by henrypp** [comment]
> 3.Found another rule bug:
> with rule <item name="Reserved.ipv4" rule="0.0.0.0/8;10.0.0.0/8;127.0.0.0/8;192.168.0.0/16;224.0.0.0/4;255.255.255.255/32" rule_local="0.0.0.0/8;10.0.0.0/8;127.0.0.0/8;192.168.0.0/16;224.0.0.0/4;255.255.255.255/32" dir="2" is_block="false" is_enabled="true" />

Where bug? It's incorrect configured rule.

**Comment by henrypp** [comment]
Anyway most of loopback addresses ([reserved ips](https://en.wikipedia.org/wiki/Reserved_IP_addresses)) are included in "Allow loopback connections" configuration.

**Comment by LazyZhu** [comment]
Where bug? It's incorrect configured rule. Same remote and same local ip means loopback.

But the log shows are different ips.
Do you mean `rule` and `rule_local` can't have the same ip?
