### ISSUE TITLE
app crashes 2.3

### ISSUE THREAD

**Issue by pwn0r** [henrypp/simplewall#199]
```
Faulting application name: simplewall.exe, version: 2.3.0.0, time stamp: 0x5b290799
Faulting module name: simplewall.exe, version: 2.3.0.0, time stamp: 0x5b290799
Exception code: 0xc0000005
Fault offset: 0x0000000000001542
Faulting process id: 0x5a8
```

did not work here on windows LTSB 1607 -- after installation FC every time trying to start UI. 

Did work on my other machine running 1803 build though.

**Comment by henrypp** [comment]
FC WTF?
-- 
www.henrypp.org | github.com/henrypp

**Comment by pwn0r** [comment]
sorry, it means app crashes on that machine for some reason. Part of the error message taken from the log as per above.

**Comment by henrypp** [comment]
fixed
