### ISSUE TITLE
LAN problem

### ISSUE THREAD

**Issue by duttyend** [henrypp/simplewall#202]
Dear @henrypp ,

Thanks again for this wonderfull app.

There is a regression between version 2.2.12 (everything was working perfectly for my usage scenario) and version 2.3 (LAN connectivity is broken).

Using FreeFileSync, I get those error messages :
**Cannot read file attributes of "\\**...[my other PC]\...[the shared folder]**".**
**Error Code 53: The network path was not found. [GetFileAttributes]**

My simplewall configuration is as follows (and was the same with 2.2.12) :
Settings > Rules > System rules > **SMB (shared network)** _enabled_

Thanks a lot for your time and dedication !

**Comment by henrypp** [comment]
fixed system rules

**Comment by duttyend** [comment]
Thank you so much, version 2.3.1. fixed the problem ! 
I saw that you added granularity (separation between SMB inbound and outbound), that's awesome !!!
