### ISSUE TITLE
v2.3 separation of local/remote rules causes issue with RDP

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#203]
Minor issue.

Since the update to v2.3, I suddenly couldn't create an RDP connection from outside of my local network anymore (local worked fine). It turns out that it's because the system rule for RDP specifies port 3389 as _remote_ port instead of _local_ port. Many people use an alternative listen port in the router and map it to 3389 locally. If simplewall allows the local port 3389, instead of the remote port 3389, it will work for those people again.

**Comment by henrypp** [comment]
updated system rules.
