### ISSUE TITLE
Your GPG binary signing key is invalid since 2018-06-11

### ISSUE THREAD

**Issue by beerisgood** [henrypp/simplewall#204]
While the main key is okay until 2019-06-11, the subkey with which you sign the binarys is invalid now.
As result we got now that is binary is correct signed, but the key is invalid which is nearly the same that the key is wrong.

**Comment by henrypp** [comment]
fixed

**Comment by beerisgood** [comment]
Also for guys which search the GPG key, look here:
https://www.henrypp.org/product/simplewall

> 
    Public key: pubkey.asc (ha.pool.sks-keyservers.net)
    Key ID: 0x5635B5FD
    Fingerprint: D985 2361 1524 AB29 BE73 30AC 2881 20A7 5635 B5FD
