### ISSUE TITLE
[enhancement] hold packets in queue and don't drop them while waiting for user interaction/decision

### ISSUE THREAD

**Issue by tokariu** [henrypp/simplewall#207]
Currently if a new program wants to connect to the internet, simplewall throws a notification popup waiting for the user to decide what to do with the packets.. should it be blocked, or allowed? 
However, while simplewall is waiting for the user to interact the current pending packets which caused the notification gets dropped and lost.
If the user decides to allow the pending packets to go through the firewall, the packets aren't available anymore, because simplewall just dropped them.
The program then needs to be restarted first, before it creates the same requests / packets again. then simplewall allows the packets because the user created the rule a step before.

As said, this leads many times to the situation that you have to restart the application first, after applying a rule in the notification popup.

Other software firewalls seem to handle this differently. They somehow seem to buffer the packerts/requests of applications while asking the user what to do with them. And after the user decided what to do, it proceeds with the buffer/packet queue depending on the created rule / user decicion.

would it be possible to let simplewall handle it the same way?

**Comment by henrypp** [comment]
> Other software firewalls seem to handle this differently. They somehow seem to buffer the packerts/requests of applications while asking the user what to do with them. And after the user decided what to do, it proceeds with the buffer/packet queue depending on the created rule / user decicion.

Other software firewalls used kernel-mode WFP driver, simplewall had designed only for user-mode WFP.

> would it be possible to let simplewall handle it the same way?

No, I have no plans for use kernel-mode WFP driver in near future. It costs money for authenticode and lots of time for debugging.

**Comment by tokariu** [comment]
@henrypp does this restrict the way the firewall works? for instance, if simplewall runs in user-mode, is it still being able to block system-level processes?

**Comment by henrypp** [comment]
@tokariu simplewall do not block anything, [do you read FAQ](https://github.com/henrypp/simplewall/wiki/FAQ#how-it-works)? It's all do Base Filtering Engine driver and of cource it block kernel-mode level too.
