### ISSUE TITLE
simplewall not working with Windows 10 v10.0.17134.112

### ISSUE THREAD

**Issue by DmitriyK-CPKIO** [henrypp/simplewall#208]
For now I experience this problem with 2.3.2 version — no matter what's enabled or not, all software has net access. I will post more when check this out on my Win7 machine.

**Comment by DmitriyK-CPKIO** [comment]
Reinstalling version 2.3 made everything working ok.

**Comment by f0xlz** [comment]
Please close the issue in this case.
