### ISSUE TITLE
SW still not 1.42 blocking traffic through VPN 

### ISSUE THREAD

**Issue by MCHALAO** [henrypp/simplewall#21]
I am sorry to report, pal, that simplewall (1.42) is still not filtering traffic when used with VPN software. For example, when using a VPN program, I can easily browse the Web. SimpleWall lists the VPN program, which though, for navigating anonymously, I have to give it permission (that is, mark it, the VPN executable, as allowed). This time I used Simplefirewall default settings with White list mode on, but, sorry, the problem persists. 

By the way, have you ever heard for evorim.com firewall? Its latest version can block VPN traffic. May you could get some programming help for solving the problem from them?

**Comment by ltGuillaume** [comment]
What's the current state of this?

**Comment by henrypp** [comment]
I'm interested too!

**Comment by ltGuillaume** [comment]
I'm currently getting these entries in simplewall.log:
>D:\programs\internet\someprogram (Computer\User) [Remote: (IPv6-address):43611] [Local: (IPv6-address):57543] (UDP) WindscribeIPV6FirewallSublayer [Out]
>C:\windows\system32\svchost.exe (NT AUTHORITY\NETWORK SERVICE) [Remote: (IPv4-myRouter):53] [Local: (IPv4-myPC):54121] (UDP) OpenVPN [Out]

**Comment by henrypp** [comment]
@ltGuillaume, What OS? Try enable "Enable proxy support" on Win8 and above.

**Comment by ltGuillaume** [comment]
Thanks
