### ISSUE TITLE
Aplication crashes every time I plug in USB HDD

### ISSUE THREAD

**Issue by wjk82** [henrypp/simplewall#215]
Hi! This is happening everytime I plug in external HDD into USB port:

> Problem signature:
Problem Event Name:	APPCRASH
Application Name:	simplewall.exe
Application Version:	2.3.3.0
Application Timestamp:	5b41c175
Fault Module Name:	simplewall.exe
Fault Module Version:	2.3.3.0
Fault Module Timestamp:	5b41c175
Exception Code:	c0000005
Exception Offset:	000000000001ca15
OS Version:	6.1.7601.2.1.0.256.4
Locale ID:	1045
Additional Information 1:	48a5
Additional Information 2:	48a52e2fc28defbd6e7a026a360adfa1
Additional Information 3:	188a
Additional Information 4:	188a5845844dbb52e672170e73639212

**Comment by henrypp** [comment]
Please let me see apps.xml and drive letter of your plugged in usb drive.

**Comment by Loughty** [comment]
This problem still happening on the 3.0.3 beta 64 bit version. The program crash when I plug an USB flash.

**Comment by henrypp** [comment]
@Loughty 
I confirm.
Temporary solution is disable refreshing filters on device arrival. In settings.
