### ISSUE TITLE
simplewall does not create any entries for interpreters

### ISSUE THREAD

**Issue by HJLBX** [henrypp/simplewall#22]
Windows 7
WIndows 10 Version 1607 OS Build 14393.693

Run any network commands or interpreters to connect out via the network.

For example,

cmd.exe
ping.exe
nslookup.exe
wscript.exe
cscript.exe
powershell.exe
etc
etc

simplewall does not create entries for cmd, cmd utilities nor interpreters.

I have reported this issue before.

**Comment by henrypp** [comment]
[#23](https://github.com/henrypp/simplewall/issues/23#issuecomment-283416618)

**Comment by henrypp** [comment]
latest version (1.6.5) still do not create?
