### ISSUE TITLE
Info  - simplewall doesn't load on system startup

### ISSUE THREAD

**Issue by Peuj** [henrypp/simplewall#220]
Hello,

Just for information, I couldn't make simplewall load on system startup with both options "Load on system startup" and "Skip "User Account Control" prompt warning".

The key added by "Load on system startup" in HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run doesn't work (at least for me).

The task "simplewallSkipUac" created by the option "Skip "User Account Control" prompt warning" cannot work because there is no trigger defined (the argument seems wrongly defined also).

The solve the problem I've created a new task then:
- in General tab: check the "Run with highest Privileges"
- in Triggers tab: add a trigger to start "At log on" ("At system startup" doesn't for me)
- in Actions tab: add the path to simplewall (I've also added "/minimized" as argument)

optional
 - disable the two options "Load on system startup" and "Skip "User Account Control" prompt warning" not needed anymore

**Comment by henrypp** [comment]
moved to #336
