### ISSUE TITLE
New option

### ISSUE THREAD

**Issue by black-cerberon** [henrypp/simplewall#228]
Hello. Please add option - "Allow connections for apps with digital signature".
Thank.

**Comment by joeparkerz** [comment]
+1 !!!!!

**Comment by beerisgood** [comment]
Nah. Nowadays malware comes with valid sig from big companys. No good idea

**Comment by joeparkerz** [comment]
Ugh thats a bad excuse!

**Comment by aphextwins** [comment]
> 
> 
> Ugh thats a bad excuse!

how to get a virus? blindly trust anything with a digital signature
