### ISSUE TITLE
Need a way to filter-out loopback dropped packets from dropped packets notifications

### ISSUE THREAD

**Issue by HJLBX** [henrypp/simplewall#23]
Windows 7
Windows 10 Version 1607 OS Build 14393.693

As I user I want to enable dropped packet notifications - but at the same time - I do not want constant dropped packets notifications for loopback.

Also, if disable dropped packet notifications, but keep WFwAS enabled, simplewall will display dropped packet notifications.

I have reported these issues before.

**Comment by henrypp** [comment]
Windows Firewall filters have high priority and processed before simplewall filters.
simplewall was displayed notifications for all WFP providers.
Thats why you need to disable Windows Firewall.

**Comment by HJLBX** [comment]
Loopback dropped packet notifications still appear with WFwAS disabled.

**Comment by henrypp** [comment]
@HJLBX, What do you mean by the word "loopback"?
need to see the log.

**Comment by MCHALAO** [comment]
Hi, Henry:

Sorry for replying for HJLBX: Loopback is "localhost traffic". See bellow.

Shorter Wiktionary (En-En)
loopback
noun
The routing of a signal, data stream, etc. from its origin back to the origin, primarily as a means of testing the transmission or transportation infrastructure.

Regards.

**Comment by henrypp** [comment]
1.4.3 was some little changes about loopback, it will allow entire loopback (all packets with "loopback" flag).
and added more description about global filters (like "Block all outbound/inbound/listen traffic").
you need use latest (1.4.4) ver, and show me log, i cannot say anything without log.
and i cannot know about your configuration - who are allowed, what mode do you use etc.

**Comment by henrypp** [comment]
> Loopback dropped packet notifications still appear with WFwAS disabled.
sometimes need reboot after WF disabled, simplewall does not block any loopback connections.
