### ISSUE TITLE
Ninte problem

### ISSUE THREAD

**Issue by chump2010** [henrypp/simplewall#231]
Ninite (ninite.com) which is an updater program appears to cause problems with Simplewall. 

I have tried to allow the app through permanently but that does not work.

The reason for this is each time ninite runs, it creates itself here:

C:\Windows\Temp\*********************\ninite.exe

Note: the stars represent a wildcard. This means it creates a random folder name and creates a ninite.exe file which is the one that wants to access the internet.

![image](https://user-images.githubusercontent.com/40383228/45684465-5b5d2e80-bb3e-11e8-9cb0-1c587cbfe026.png)

![image](https://user-images.githubusercontent.com/40383228/45684543-95c6cb80-bb3e-11e8-8191-8192e26ec27a.png)

I have tried allowing it by IP address - but this seems to change after a few weeks.

Any thoughts would be most welcome.

**Comment by beerisgood** [comment]
C:\windows\temp is no path a normal program should use. Same for this strange folder name. Sound more like malware

Are you sure the program is safe?

**Comment by chump2010** [comment]
Hi there. The program is safe. It has been around for ages. It basically installs other programs for you, without toolbars and no installation options required. 

However, do not take my word for it. Here are some reviews from respected sources:

https://lifehacker.com/the-best-app-updater-for-windows-1445085301

https://www.howtogeek.com/201354/ninite-is-the-only-safe-place-to-get-windows-freeware/

https://www.pcworld.com/article/2013169/review-ninite-turns-setting-up-a-new-computer-into-a-quick-painless-process.html

https://www.zdnet.com/article/ninite-is-fast-easy-and-foistware-free/
