### ISSUE TITLE
simplewall blocks IDM Integration Module in chrome

### ISSUE THREAD

**Issue by EDK-TheONE** [henrypp/simplewall#236]
simplewall blocks IDM Integration Module in chrome. even added these files (IDMan.exe   idmBroker.exe   IDMGrHlp.exe IDMIntegrator64.exe IEMonitor.exe) to white-list but still is not working. the only way is disable simplewall!

**Comment by henrypp** [comment]
https://github.com/henrypp/simplewall/issues/111#issuecomment-353171368

**Comment by setsunati** [comment]
@EDK-TheONE Alternatively you can just use XDM instead. http://xdman.sourceforge.net/ It is open source unlike IDM.
