### ISSUE TITLE
Don't connect to internet before simplewall is running option

### ISSUE THREAD

**Issue by Jtasiu** [henrypp/simplewall#239]
Thanks for the great program @henrypp. 

Usually there is 30 second to 1 minute delay before simplewall is fully started after logon. Can option be added to start simplewall before all programs after computer startup/logon and to not connect to internet before simplewall is completely initialized and running?

**Comment by henrypp** [comment]
All blocking filters (and other) are working even if simplewall is not running.

**Comment by Jtasiu** [comment]
@henrypp 

Ok Thanks. Just to confirm this means all rules and allowed/blocked apps settings still take effect without needing to keep running simplewall all the time and it is mainly a GUI to easily add and remove rules?

**Comment by heforfree** [comment]
@Jtasiu yes

**Comment by setsunati** [comment]
@Jtasiu There is "Enable boot-time filters" option in Settings > Rules.
