### ISSUE TITLE
System rules & popup notifications

### ISSUE THREAD

**Issue by pucherot** [henrypp/simplewall#24]
When I mark  system rules (i.e. DNS, DHCP, IGMP) some popup notifications appears for System and svchost processes.

System and svchost are allowed and while list activated.

Is there a way to prevent popup notifications from processes System & svchost when DNS, DHCP, IGMP system rules are selected?

Thank you very much.

**Comment by henrypp** [comment]
can you provide dropped packets log (where system & svchost are blocked)?
i'm no say anything without log.

**Comment by pucherot** [comment]
hi, please find attach simplewall.log with svchost dropped packets.
Regards

[simplewall.log.txt](https://github.com/henrypp/simplewall/files/871600/simplewall.log.txt)

**Comment by henrypp** [comment]
in log filters have no name, it maybe because Windows Firewall do not disabled.

you can disable WF by this command in CMD:

`
sc stop mpssvc
sc config mpssvc start= disabled
`

do you try latest version (1.4.4), it will can show information about provider (who have been blocked any request).

**Comment by pucherot** [comment]
Hi Henrypp

Windows firewall are disabled and I still recive popup notifications for processes System & svchost.
Attached you can find log file.

Regards
[simplewall.log.txt](https://github.com/henrypp/simplewall/files/890875/simplewall.log.txt)

**Comment by henrypp** [comment]
No, WF are not disabled. Do you see that in log?
> Proveedor de Firewall de Windows de Microsoft
It means WF services are not disabled.

**Comment by pucherot** [comment]
Thanks Henrypp, I restarted the laptop and no more popups.

Regards.
