### ISSUE TITLE
Whitelist/blacklist only selected ip connections of an app

### ISSUE THREAD

**Issue by kyelbek** [henrypp/simplewall#242]
I know this program is created to be simple as possible but I would like to see there an option to add rules from active connections list if it's possible.

**Comment by ltGuillaume** [comment]
That's already possible via user rules.

**Comment by kyelbek** [comment]
@ltGuillaume Tell me where then because I don't see anything like that. You can only enter these rules manually so you need to check active connections from .exe via netsh for example.

**Comment by ltGuillaume** [comment]
Ah, I misunderstood. So you want to have a visual representation of the
connections a certain program has set up, so you can select them in order
to be blocked. That would indeed be nice.

For now, perhaps TCPview by Nirsoft will be useful?

**Comment by kyelbek** [comment]
Yep. That could speed up whole process, especially when you're using trial and error method. Of course I forgot about Nirsoft tools as a workaround for a while, thanks for a reminder!
