### ISSUE TITLE
Cannot update Windows Store and its apps

### ISSUE THREAD

**Issue by acicovic** [henrypp/simplewall#244]
Hi,
First of all, thank you for this great software!

I cannot download Windows Store app updates. Does anyone know what I must do to allow this?

Thanks!

**Comment by ltGuillaume** [comment]
1. In the blocklist, don't check the items with "update".
2. Have the Windows Update service running (yuck).
2. Be sure that the Store is allowed to access the network. If it's not in the list yet, right-click in the simplewall application window, choose Add -> Package -> Store.

**Comment by acicovic** [comment]
Thank you very much! I'll try this next time when it tries to update and doesn't work.

**Comment by acicovic** [comment]
I tried but with no results. Apparently, the store or certain apps require Windows Firewall to get updated:

https://answers.microsoft.com/en-us/windows/forum/windows_8-windows_store/cannot-install-apps-get-error-code-0x80073d0a/604fbd8e-7cfd-4512-a3db-e87aba8765cf

So the only apparent solution for me is to disable filtering and to enable Windows Firewall during the update.

**Comment by ltGuillaume** [comment]
Maybe the Background Intelligent Transfer Service is disabled?

**Comment by acicovic** [comment]
BITS Service is set on Manual and I have no problem with Windows Updates, so it seems OK to me. I only have this issue with the store and the apps. Everything else seems to be working fine.

**Comment by Tom4tot** [comment]
If I may, Henry++, it may be related to the Windws update issue ( https://github.com/henrypp/simplewall/issues/206 ). I'm on Windows 1809 and I can't update microsoft apps either until I allow svchost.exe (even if I allow Windows Store).

**Comment by henrypp** [comment]
Please go to this thread #206, because of duplicate
