### ISSUE TITLE
Aero Dark Theme for win32

### ISSUE THREAD

**Issue by alterdaemon** [henrypp/simplewall#248]
I hope it's not too much to ask.
Thing is that after MS introduced dark file explorer it's getting to be a standard, even for the win32 applications ;)

**Comment by henrypp** [comment]
Where it is and how?

**Comment by dgutkowsky** [comment]
it's a good example of what I mean:

https://draculatheme.com

I hope it won't be too hard to implement ;-)

**Comment by henrypp** [comment]
No, @dracula themes is for apps with internal themes engine (like text editors etc.). And i got some google search for dos and think is hard to introduce "dark file explorer" theme for _win32_ app.

**Comment by dgutkowsky** [comment]
Hi
there is an example of someone who has made a custom dark theme via installer for the qbittorrent
https://github.com/suratovvlad/qbittorrent-installer

Anyway, it's a nice to have - Simplewall is already magnificent! :)

**Comment by ackys** [comment]
Oh how i whould love a dark theme for Simplewall. And thank you for creating a great piece of software Henry. Hope you can make dark theme one day. Cheers.

**Comment by AzimsTech** [comment]
very cool

**Comment by Iruberiam** [comment]
This has been closed, isn't there some kind of work around for the checkboxes? Can we see a screenshot with the theme applied please?

**Comment by henrypp** [comment]
3.0.3 fixed issue with checkbox, what the question?

**Comment by hl2guide** [comment]
a dark mode would be wonderful 👍

**Comment by henrypp** [comment]
> Oh how i whould love a dark theme for Simplewall.

> a dark mode would be wonderful 👍

You can use dark style with [SecureUxTheme](https://github.com/namazso/SecureUxTheme) workaround for not signed themes (secureux is recommended, because of do not change system files).

![simplewall-dark-style](https://user-images.githubusercontent.com/3902025/105608654-2a3f3980-5d9c-11eb-9322-ddb0b4723aaa.png)

ps: [macOS Big Sur Dark](https://skinpacks.com/macos-big-sur-dark-skinpack-for-windows-10/) theme used.

Yes.

> Thing is that after MS introduced dark file explorer

Hmm, M$ introduced API and documentation for this feature?

**Comment by alterdaemon** [comment]
Well, there are some quite fresh news from Microsoft with a guidance
https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/apply-windows-themes

**Comment by Iruberiam** [comment]
This is great new, thank you.

**Comment by majkinetor** [comment]
@henrypp , why not reopening this since its now possible to do in the app?

**Comment by GImDX** [comment]
wonfix😄

**Comment by henrypp** [comment]
@majkinetor how?

**Comment by majkinetor** [comment]
https://github.com/henrypp/simplewall/issues/248#issuecomment-1330039049

**Comment by henrypp** [comment]
@majkinetor 
The apps in the article is not win32, it is UWP bullshit.

@microsoft you still not get dark mode for win32 apps, sad.

**Comment by NikoMuffin** [comment]
simplewall is the best and I am very grateful for all the time spent in it.

That said the only thing I yearn for in this app is dark mode :(

**Comment by henrypp** [comment]
@NikoMuffin u can check new feature [here](https://t.me/henrypp_dev/58)

**Comment by codeXXjs** [comment]
@henrypp  Thank you so much for adding Dark Theme support. We are all grateful to you for this amazing app.

**Comment by Iruberiam** [comment]
Thank you so much for adding the Dark theme.
