### ISSUE TITLE
Can't update

### ISSUE THREAD

**Issue by p-groarke** [henrypp/simplewall#249]
Updater requires simplewall process to be terminated. Quitting simplewall kills updater.

**Comment by GHosTiKuS** [comment]
For me some kind of workaround works. When SW asks about update click "yes", wait for warning and click "exit" in right-click-menu of SW's icon, then click "repeat" in warning window (may not work for first time)
(also if you have some delay before warning you cant wait for it, but you need to find right moment ;)

**Comment by p-groarke** [comment]
I think it was fixed in with the latest update :) Will reopen if that isn't the case.

**Comment by p-groarke** [comment]
Still happening, this is ridiculous come on buddy

**Comment by henrypp** [comment]
There need to do some work with [sdk](https://github.com/henrypp/routine)

**Comment by p-groarke** [comment]
@henrypp Sorry if I didn't sound calm. I'll be patient :)
