### ISSUE TITLE
The latest version (2.3.6) is unbearable.

### ISSUE THREAD

**Issue by german87ger** [henrypp/simplewall#251]
The latest version (2.3.6) is unbearable. He does not keep the rules and is constantly asking about the applications every time I open any application. S.O.S Thank you.

**Comment by german87ger** [comment]
Hi good day. It's not about that. It is that when I open certain programs that I had previously opened and assigned rules Simplewall again warns me to create a rule as if I had not done it before. It is with some programs, such as Sketchup.
Thanks for your attention

**Comment by SimpleUs** [comment]
Да,эта версия ни с того ни с сего просто замирает.Перестаёт определять новые приложения просящиеся в интернет. Просто никак не реагирует. Помогает "выход" и заново запуск.(Но это же не правильно) На прошлой версии такого не наблюдал.

**Comment by pwn0r** [comment]
agreed. Such slowdowns do happen. Sometimes takes like 15-20s to open a notification window that a new application tries to access the internet.

**Comment by henrypp** [comment]
check 2.3.7

**Comment by ltGuillaume** [comment]
I still don't get pop-ups with 2.3.7. The entries won't show up in the log file either. Sometimes restarting will help, for a while.

Windows 10 x64 1709.

**Comment by pwn0r** [comment]
I'm still on LTSB (i.e. 1607) and waiting for 1809 LTSC, not upgrading every six months. 
For me it seems that the issue was solved. Even after a few hours uptime the notification windows appears almost immediately. Of course we need a few days uptime to tell for sure.

**Comment by henrypp** [comment]
fixed 2.3.8

**Comment by henrypp** [comment]
@ltGuillaume when no notifications tray menu item "Install filters" is greyed out?

**Comment by ltGuillaume** [comment]
No, filters are installed. It only says "Disable filtering..." (not greyed out)

**Comment by german87ger** [comment]
Thanks. The problem has been resolved. Greetings.
