### ISSUE TITLE
Simplewall not working

### ISSUE THREAD

**Issue by rayman3003** [henrypp/simplewall#257]
Simplewall 2.3.8
Windows 10 x64 Pro 1803

[simplewall_error.log](https://github.com/henrypp/simplewall/files/2572674/simplewall_error.log)

Recently "Simplewall" shows an error log, every time it starts & also "Simplewall" stops blocking or showing warning message for any new app that wants to connect to internet.

I tried reinstalling the new (2.3.8) or previous older versions (2.3.7 - 2.3.6 - 2.3.5), But it didn't helped.

The log file has been attached.

Please help.

**Comment by henrypp** [comment]
Windows Defender enabled? Any AV installed?

**Comment by rayman3003** [comment]
> 
> 
> Windows Defender enabled? Any AV installed?

My Anti-Virus is "360 Total Security". "Windows Defender" disabled automatically after installing "360 Total Security".

Note: I can add softwares to simplewall manually to make them block or allow to internet, But only manually.

**Comment by beerisgood** [comment]
Sounds like your AV is the problem.
With Windows Defender everything works

**Comment by rayman3003** [comment]
> Sounds like your AV is the problem.

Maybe u r right. But whats the solution?

**Comment by rayman3003** [comment]
> 
> 
> I think it happens because your AV block access to WFP for simplewall, maybe need add SW to whitelist in AV settings!

But I already did that before & it didn't helped:

![yt5yh5](https://user-images.githubusercontent.com/17022701/49935538-827d8f00-fee6-11e8-8b81-763a083c86bf.jpg)

**Comment by beerisgood** [comment]
Then deactivate or deinstall your AV

**Comment by rayman3003** [comment]
> 
> 
> Then deactivate or deinstall your AV

Deactivating the AV won't help.
Deinstalling the AV, is not a good solution.

> 
> 
> What is for checkbox? Maybe you miss something?

Checkbox is for removing the app from Trust List of AV.

**Comment by rayman3003** [comment]
I uninstalled my AV ("360 Total Security"), But still get the same error. So the error is nothing to do with my AV.
Still waiting for solution.

**Comment by TontyTon** [comment]
I earlier faced the issue, I reinstalled but with importing apps and rules, which didn't solved the problem. Then tried reinstalling without importing and everything worked fine. Also empty the directory.
(Install latest version-2.3.13)

**Comment by rayman3003** [comment]
> 
> 
> I earlier faced the issue, I reinstalled but with importing apps and rules, which didn't solved the problem. Then tried reinstalling without importing and everything worked fine. Also empty the directory.
> (Install latest version-2.3.13)

I think maybe this problem occurs bcuz of the huge numbers of blocked & allowed apps in the simplewall, Bcuz I have added so many apps to the simplewall. Lets say if I remove all apps & rules, the simplewall gets back to normal; But what happens again if I add these apps & rules after some weeks again? The error will be back again?

**Comment by TontyTon** [comment]
No I don't think so, because there are more apps on my list than earlier and everything working fine.

**Comment by rayman3003** [comment]
> 
> 
> No I don't think so, because there are more apps on my list than earlier and everything working fine.

OK, I uninstalled simplewall, Cleaned the registry & then reinstalled the simplewall.
But still from the first clean start of simplewall (0-app), It shows the same error. 

So the error & problem has nothing to do with my added apps or my preferred settings of simplewall.

**Comment by rayman3003** [comment]
> 
> 
> Share the latest error log

Here u go:

[simplewall_error.zip](https://github.com/henrypp/simplewall/files/2727612/simplewall_error.zip)

**Comment by TontyTon** [comment]
Enable skip uac prompt warning in settings>General, or start Simplewall (SW) as administrator for now.

[Clear the log file(make a backup if you want to), this will make easy for you to find latest errors]

**Comment by rayman3003** [comment]
> 
> 
> Enable skip uac prompt warning in settings>General, or start Simplewall (SW) as administrator for now.
> 
> [Clear the log file(make a backup if you want to), this will make easy for you to find latest errors]

"skip uac prompt warning" was always enabled.
I ran the "simplewall" with "run as admin" from yesterday, But still get the error.

One other thing that I must mention:

Each time that I plug-in a usb device (flash drive - optical usb drive - ...) to my pc, simplewall shows the error log notification.

Here is the last error log file:

[simplewall_error.zip](https://github.com/henrypp/simplewall/files/2727993/simplewall_error.zip)

**Comment by TontyTon** [comment]
I am unable to find a solution. Maybe someone else may help.
Still not getting notifications for new apps??!!!!

**Comment by rayman3003** [comment]
> 
> 
> I am unable to find a solution. Maybe someone else may help.
> Still not getting notifications for new apps??!!!!

Thank u for your help & time.

Yes, still no notifications for new apps. (only manually adding, works) :(

**Comment by henrypp** [comment]
@rayman3003 

I think 360 is corrupt access rights for write into `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\BFE\Parameters\Policy` and need reset access rights for this key and all subkeys

**Comment by rayman3003** [comment]
> 
> 
> @rayman3003
> 
> I think 360 (or someone else) is corrupt access rights for write into `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\BFE\Parameters\Policy` and need reset access rights for this key and all subkeys

This is the screenshot of the reg key u r mentioning. What I must to do?

![reg](https://user-images.githubusercontent.com/17022701/51756218-bc14ee80-207d-11e9-86b0-85dda0f8985e.jpg)

I already said that "360 security" has been uninstalled. Also I tried "simplewall+360 security" on another PC & simplewall worked perfect without problem there.

**Comment by henrypp** [comment]
In 2.4.x versions security information for WFP internals are reworked and, i think, this is better to get test latest 2.4.3 version!

**Comment by rayman3003** [comment]
> 
> 
> In 2.4.x versions security information for WFP internals are reworked and, i think, this is better to get test latest 2.4.3 version!

Thank u that u r still trying helping me.
I installed the last version (2.4.3), But still my problem exists! :(

**Comment by rayman3003** [comment]
Update: My problem solved.

I upgrade my Windows 10 from build 1803 to 1809, And now Simplewall works without a problem.

Simplewall is awesome.
Thank u.

**Comment by nk-666** [comment]
Hi Henry

I believe this error is back again...with 3.7.2

![image](https://github.com/henrypp/simplewall/assets/54146957/89b18660-20bd-4c6a-937f-9414b85e123d)

**Comment by henrypp** [comment]
@nk-666 fucking search did not exists?
