### ISSUE TITLE
Short Questions about ip range and cidr

### ISSUE THREAD

**Issue by cyberpunkbln** [henrypp/simplewall#258]
Hello,
short question:
an ip range
127.0.0.1-127.0.0.255
can i make it with a cidr notation like
127.0.0.1/32
127.0.0.0/32
the ip range works, the cidr not? Misunderstood what?
thx

**Comment by henrypp** [comment]
> 127.0.0.1/32
> 127.0.0.0/32

127.0.0.x/32 is loopback addresses and this had another option "Allow loopback connections"

**Comment by cyberpunkbln** [comment]
Ah thx, my failure. Now it's functioned, but at the moment i have more control with the from - to rule;).
Thx
