### ISSUE TITLE
Aplication crashes every time I plug in USB HDD

### ISSUE THREAD

**Issue by guilhas** [henrypp/simplewall#263]
Hello,

When I connect a external drive with applications in, that are present in simplewall allow list, simplewall crashes.

Error log:
> 21/‎11/‎2018 ‏‎17:41:32,FwpmGetAppIdFromFileName(),0x00000003,G:\steam\steam.exe,2.3.4
‎> 21/‎11/‎2018 ‏‎17:41:32,FwpmGetAppIdFromFileName(),0x00000003,G:\steam\bin\cef\cef.win7x64\steamwebhelper.exe,2.3.4
‎> 21/‎11/‎2018 ‏‎17:41:32,FwpmGetAppIdFromFileName(),0x00000003,G:\steam\steamapps\common\the talos principle\bin\talos.exe,2.3.4
‎> 21/‎11/‎2018 ‏‎17:41:32,FwpmGetAppIdFromFileName(),0x00000003,G:\steam\bin\cef\cef.win7\steamwebhelper.exe,2.3.4

Regards,

**Comment by henrypp** [comment]
Even if this thread is duplicate, 2.3.4 is very old version
