### ISSUE TITLE
Build from source EXE simple exits

### ISSUE THREAD

**Issue by qilinaditya** [henrypp/simplewall#264]
Hi
Upon building from source, I get a simplewall.exe in the bin folder.
It simple exits on starting it. I do not get any GUI.
Am I missing something?

**Comment by qilinaditya** [comment]
if (dwRealChecksum != dwFileChecksum)
				return false;

This seems to be the culprit in rapp.cpp !
 If I comment this then it starts fine

**Comment by henrypp** [comment]
@qilinaditya if you are do not **use Visual Studio** and proect will not **have Set Checksum (/RELEASE)** option, your build will pass, but not starting up, i think!
