### ISSUE TITLE
IP Address allowing doesn't have effect

### ISSUE THREAD

**Issue by Jtasiu** [henrypp/simplewall#265]
For example when the notification pops up i click allow for this IP address (not specifying port) it still doesn't work for some weird reason. I noticed this with local address mainly like 127.0.0.1 but could also happen for remote ones. For whatever reason if I edit the allow rule to 127.0. it works.

**Comment by heforfree** [comment]
explain better.title say ip address blocking
content say you allow.
if you want block ip from notification 
tick create rule for a "1.1.1.1" address
then click block.

**Comment by heforfree** [comment]
explain better so maybe someone help you better.title say ip address blocking
content say you allow.
if you want block ip from notification
tick create rule for a "1.1.1.1" address
then click block.

**Comment by Jtasiu** [comment]
I did mean allowing in the title but the same issue could be there for blocking.

**Comment by heforfree** [comment]
which windows and what program? i am running windows 7sp1 no problem
no idea.lets see someone else can help you :)
some programs try connect to many ip and stack to first ip i allowed
and i have to restart program then it reach second ip so allow second ip
then it will work.so seems problem is from other program.not sure

**Comment by henrypp** [comment]
Itt's not a bug, 127.0.0.1 are loopback address. Loopback & Listen connections allowed?

**Comment by Jtasiu** [comment]
@henrypp I have allow listen connections ticked but loopback connections unticked. Would that be reason why this is happening? If so, just ticking the allow loopback connections option should make 127.0.0.1 allow rules work, yes?
