### ISSUE TITLE
Update entries in blocklist gone

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#268]
It probably has to do with https://github.com/henrypp/simplewall/issues/206, but why were all the update entries removed from the blocklist? If people want to use Windows Updates/Windows Store, they'd have to be stupid to enable the update entries. So why remove them from blocklist.xml?

Could you please add them back?

**Comment by ltGuillaume** [comment]
I see blocklist_custom.xml still includes the update entries, should I just add the file to the simplewall folder, leaving blocklist.xml in tact?

**Comment by ltGuillaume** [comment]
There's a new release by the way: https://github.com/crazy-max/WindowsSpyBlocker/releases/tag/4.18.2

**Comment by ltGuillaume** [comment]
@henrypp Sooo??

**Comment by henrypp** [comment]
I think update entries may confuse some people, anyway, i am returned old blocklist!

**Comment by ltGuillaume** [comment]
Thanks! And to be honest, if people are confused, they shouldn't enable the blocklist anyway. At least not until they did some research on their own.

**Comment by henrypp** [comment]
@ltGuillaume, yes, for "advanced users" ONLY!

**Comment by ltGuillaume** [comment]
@henrypp https://github.com/crazy-max/WindowsSpyBlocker/releases/tag/4.28.0
