### ISSUE TITLE
Portable Version with PortableApps

### ISSUE THREAD

**Issue by RoyiAvital** [henrypp/simplewall#27]
Hello,

Could you create a Portable Version with collaboration with [PortableApps](https://portableapps.com/)?

Thank You.

**Comment by henrypp** [comment]
No. Native portable exists.

**Comment by RoyiAvital** [comment]
They have a platform.
It is not only for the feature of portability.
It is about being part of the eco system.
Another upside is exposure to a large user base.

**Comment by rddim** [comment]
Portable version released here https://portableapps.com/node/58779

**Comment by RoyiAvital** [comment]
Does it require Administrator Rights or could it or without (With some limited options)?

**Comment by rddim** [comment]
I think it is required. My computer is with disabled `UAC`. Also it is not a good idea to use the options for `Load at system startup` and/or `Skip "User Account Control" prompt warning` because they are stored in the registry and it is hard or imposible to deal with it. The portable version only deal with the `*.xml`, `*.bak`, `*.log` and `*.ini` files - they are moved between the `32/64` and `Data` folders.

**Comment by RoyiAvital** [comment]
I meant to use it without Administrator Rights (Let's say on a computer with Guest User).
Will it work?

**Comment by RoyiAvital** [comment]
I don't understand.
When you run it, does it ask for Administrator Privileges?

**Comment by RoyiAvital** [comment]
It doesn't work unless Administrator Privileges are granted,
Could we solve this and have limited functionality mode which doesn't require Administrator Privileges?

**Comment by rddim** [comment]
Yes, it will ask for Administrator Privileges. I test it with `Guest` account today. This can not be solved by the portable launcher. It is by `simplewall.exe` and `Windows`. Sorry m8...

**Comment by RoyiAvital** [comment]
@henrypp , Any way making it working without the need for Administrator Privileges? I know it means most features won't work, but even view only mode.

@rddim , Could you have a look on https://github.com/wokhansoft/WFN as well?

**Comment by RoyiAvital** [comment]
What about version 3.x? Does it allow working without Admin Rights?

**Comment by rddim** [comment]
@RoyiAvital , No, it still ask for Admin Rights
