### ISSUE TITLE
start with filtering enabled

### ISSUE THREAD

**Issue by user1313** [henrypp/simplewall#273]
First of all, thanks for a great tool, discovered this gem just yesterday. I have a feature request which is somehow oposite to what was requested in #2. Would it be feasible to either add a command line argument, or a configuration file option to start already with filtering enabled?

**Comment by henrypp** [comment]
I think i can introduce "Welcome tutorial" at first run (when filters are not installed, of cource) to ask user install filters or not!

**Comment by user1313** [comment]
Rather than this welcome tutorial which would be very good to introduce the user, my request is rather for automated unattended installation, like the /S switch which you already have. At the moment the user must be present and press the button. There is no way to deploy the tool to many computers in workgroups like ours.
