### ISSUE TITLE
 Misleading: Checkbox of items in "special rules apps" list enables full internet access instead of turning rules on and off

### ISSUE THREAD

**Issue by LtqxWYEG** [henrypp/simplewall#274]
Hi

I was expecting the latter behavior. This seemed more logic to me. Could you make it more visible what is being turned on and off with the checkboxes?

Thank you!

**Comment by henrypp** [comment]
What rule?

**Comment by LtqxWYEG** [comment]
![simplewall-github](https://user-images.githubusercontent.com/44180911/49779733-6e2d6c80-fd03-11e8-822a-ef7677d9012c.png)
There. Those rules or entry in the list. Checking one of them is enabling all internet access, right?

**Comment by henrypp** [comment]
> Checking one of them is enabling all internet access, right?

Yes, but if app with special rule have block rule, this rule will work for app as indeed!

**Comment by LtqxWYEG** [comment]
It is very unclear and there is no documentation or information available that would tell users what this really does. That's why I suggested changing something to make this clear. I don't know what or how in the current design, though. IMO you'd have to redo the whole GUI. :/

I'm sure you come up with a better solution. :)
(I'm not the only one having or seeing a problem with it. See wilderssecurity forum)

**Comment by henrypp** [comment]
Yes, you're right, there is no documentation and any other help and need taking time to understand the sick logic of author of simplewall, and i try to made UI changes in future, but...

...there, in my logic, special (and global) rules filters have higher priority than apps filters. Thats why app with checkbox and special rules stay on special rules group!

I think, i am answered your question!
