### ISSUE TITLE
Java programs bypass Simplewall

### ISSUE THREAD

**Issue by Jtasiu** [henrypp/simplewall#275]
Any .jar executable or java program can connect to the Internet bypassing Simplewall rules.

**Comment by henrypp** [comment]
`.jar` is **NOT** an executable and working through Java Framework executable, and, obviously, this executable is in allowed list.

**Comment by Jtasiu** [comment]
The .jar I ran isn't running it via the Java executable (I assume you mean javaw.exe?). I use whitelist mode. What do you mean by allowed list? The jar file I ran connects to the internet without showing any notifications to allow/block program.

**Comment by Jtasiu** [comment]
Actually now when I run the .jar it doesn't connect automatically and first shows notification to allow or deny for javaw.exe. Weird....I don't know why it didn't show up before.

**Comment by henrypp** [comment]
Yes, through `javaw.exe` and allowed list is a simplewall main window list separated by groups (allowed/blocked), and if you allowed `javaw.exe` then this app has checkbox in main window and is in allowed group!
