### ISSUE TITLE
Enabling/disabling rules in Settings panel takes long time

### ISSUE THREAD

**Issue by Jtasiu** [henrypp/simplewall#276]
For example I create some user rules for a few programs to follow. Whenever I tick or untick the tickbox next to the rule Simplewall always freezes up around 20 seconds before unfreezing and showing the rule as ticked. Happens for both enabling and disabling.

**Comment by henrypp** [comment]
What rule?

**Comment by Jtasiu** [comment]
Custom user rule. Trying creating a user rule like this: rule (remote) 127.0., direction all, protocol all, family all, action allow then under enable rule (for apps) select 1 or 2 programs.

**Comment by Jtasiu** [comment]
@henrypp this is still happening on 2.3.13. Sometimes it even takes longer now..

**Comment by henrypp** [comment]
Maybe error log?

**Comment by Jtasiu** [comment]
@henrypp

Error log below (same custom rule mentioned above with 3 programs ticked). You can notice it takes 1 minute to just enable the rule and even longer if more programs are ticked.

"‎06-‎Mar-‎19 ‏‎2:46:49 PM","DnsQuery()","0x0000232b","127.0.","2.4.1"
"‎06-‎Mar-‎19 ‏‎2:47:00 PM","GetAddrInfoEx()","0x00002af9","127.0.","2.4.1"
"‎06-‎Mar-‎19 ‏‎2:47:00 PM","_app_parserulestring()","0x000004be","[127.0. (127.0.)]","2.4.1"
"‎06-‎Mar-‎19 ‏‎2:47:12 PM","DnsQuery()","0x0000232b","127.0.","2.4.1"
"‎06-‎Mar-‎19 ‏‎2:47:24 PM","GetAddrInfoEx()","0x00002af9","127.0.","2.4.1"
"‎07-‎Mar-‎19 ‏‎2:47:24 PM","_app_parserulestring()","0x000004be","[127.0. (127.0.)]","2.4.1"
"‎07-‎Mar-‎19 ‏‎2:47:36 PM","DnsQuery()","0x0000232b","127.0.","2.4.1"
"‎07-‎Mar-‎19 ‏‎2:47:47 PM","GetAddrInfoEx()","0x00002af9","127.0.","2.4.1"
"‎07-‎Mar-‎19 ‏‎2:47:47 PM","_app_parserulestring()","0x000004be","[127.0. (127.0.)]","2.4.1"

**Comment by henrypp** [comment]
`127.0.` is not a hostname! Check your rules syntax!

**Comment by Jtasiu** [comment]
@henrypp

Yes, because I want to allow all 127.0.x.x addresses! Is there any other way to do that?

**Comment by henrypp** [comment]
`127.0.` is incorrect address rule, maybe something like this is better `127.0.0.0/32`
