### ISSUE TITLE
Notification shows even if a program is not running

### ISSUE THREAD

**Issue by kayanco1** [henrypp/simplewall#277]
Hi,

Simplewall is a great firewall and I am thankful to the author. 

I notice a small bug:

- You open any program and see a notification from Simplewall. Good.
- Then close the notification using the x/cross on top-right, and notification will go away. Good.
- But, if you exit the other program, Simplewall will still give notification again, even though that program is not running. Not good (bug).

If you ignore/close a notification, then exit that program, Simplewall should not give notification again (because the program is not even running).

**Comment by TontyTon** [comment]
Hey @kayanco1 ,  many programs keep on running in background even after you close them. Check it out in Task Manager's 'Details' tab.

**Comment by henrypp** [comment]
@kayanco1 thats right, simplewall does not monitoring processes, and even if them closed/terminated, notification will stay visible until you made a decision.
