### ISSUE TITLE
Temporary block, like in WFC

### ISSUE THREAD

**Issue by kayanco1** [henrypp/simplewall#278]
Hi,

There should be a **temporary** block option, **without** adding a new rule - like in WFC ("Windows Firewall Control" by Binisoft). WFC has a button "Bock now and remind me later", this temporarily blocks the request, but no permanent rule is created. So next time, the same program is run, WFC will popup notification again. 

With Simplewall if you close the notification (with x/cross), it still creates a new rule in "Blocked apps". This clutters the section and makes it too long. Better would be an option to temporarily block or ignore, **so no new rule is created.** 

Also if possible: 
Please add a search function to rules (WFC also has this).

Thank you.

**Comment by ltGuillaume** [comment]
I fully agree and have opted for this on multiple occasions.

Even the close button could do this. I have no idea what it is for if Block does the exact same thing anyway (i.e. "Close" still adds a permanent rule afaik).
