### ISSUE TITLE
What are pico app?

### ISSUE THREAD

**Issue by TontyTon** [henrypp/simplewall#282]
Recently I saw some apps named "0", "192.168.1.1" with note "Pico App", what are these?

Edit- In notifications I saw that "192.168.1.1" was trying to connect to 192.168.1.1 and "0" to some ipv6 address. (didn't get the time to note, it wasn't long maybe local).

Got these first time, even when didn't made system changes recently and hadn't done something new.

**Comment by beerisgood** [comment]
How we should know what software you installed?
Upload it to virustotal if it's unknown for you

**Comment by heforfree** [comment]
v1.4.5 added pico support (subsystem for unix-based applications) for win10

**Comment by TontyTon** [comment]
I didn't enabled WSL, and didn't installed anything related to it. Then why I am seeing the pico apps.

**Comment by henrypp** [comment]
Its a bug. Please, watch this thread #283
