### ISSUE TITLE
malformed exe name and path nvidia share.exe

### ISSUE THREAD

**Issue by fosterbuddy** [henrypp/simplewall#283]
What is happening here? I installed the latest nVidia drivers as normal, then I blocked nvidia share.exe. I am getting notifications from simplewall about nvidia share wanting to access the internet but the exe name and/or path names are malformed, is that the right term?

The correct location for nvidia share is "C:\program files\nvidia corporation\nvidia geforce experience\NVIDIA Share.exe" and the exe is indeed digitally signed, but when i get those notifications the exe is not found and not digitally signed. They show up on the block list in red highlight meaning the "file not found"
![screenshot 741](https://user-images.githubusercontent.com/31551910/50372660-72c61080-05a0-11e9-9490-21941188a875.png)
They all try to connect to these IPs which belong to nVidia

Filter: BlockOutboundConnectionsV4
Destination IP:
8.36.80.192:443
8.36.80.215:443
8.36.80.192:443
8.36.113.113:443
8.36.80.192:443
8.36.113.113:443
8.36.80.215:443
8.36.80.192:443
![screenshot 742](https://user-images.githubusercontent.com/31551910/50372664-807b9600-05a0-11e9-88c3-3c4bd77b7b47.png)

Here's a pico app trying to connect to nvidia ip and the file is not found
![screenshot 740](https://user-images.githubusercontent.com/31551910/50372658-6d68c600-05a0-11e9-8f85-d6d525fbe2c0.png)

**Comment by henrypp** [comment]
It's a bug. Need time!
