### ISSUE TITLE
 Generating Errors

### ISSUE THREAD

**Issue by pinal1234** [henrypp/simplewall#287]
I am using your code in Microsoft Visual studio 2017, It is generating Error that ..\routine\routine.cpp': No such file or directory, it cannot open include file: 'routine.hpp'.If it has to be include than Please Provide the remaining Files.
 Cannot open source file: '..\routine\routine.cpp'
Cannot open source file: '..\routine\rapp.cpp'
Cannot open source file: '..\routine\rstring.cpp'

**Comment by henrypp** [comment]
`../routine`
