### ISSUE TITLE
[Notification] Grammar

### ISSUE THREAD

**Issue by narayagh** [henrypp/simplewall#288]
A cosmetic one but still:

https://i.imgur.com/g60EGYt.png

"are" -> "is"

**Comment by AzimsTech** [comment]
what program are you use to show connection speed?

**Comment by narayagh** [comment]
@AzimsTech It's called NetSpeedMonitor - I absolutely love it but it can't be downloaded anymore (used to be here: http://www.floriangilles.com). Thankfully, I have an installer.
