### ISSUE TITLE
Can't restrict w32time to only access local time server on router

### ISSUE THREAD

**Issue by Samaru-Zoka** [henrypp/simplewall#289]
Hi,

I can't restrict the service w32time to only use my local time server on my router. I created a custom rule using w32time as the application, and specified a remiote address of 192.168.44.1 which is my router. And when I tried to use Control Panel > Date and Time > Internet Time to update the time using time.windows.com - it succeeded ?

**Comment by Samaru-Zoka** [comment]
Hi,

I would also like to restrict the DNScache service to only use my dns server on my own router. If it can be done.

**Comment by henrypp** [comment]
https://defaultreasoning.com/2009/11/16/synchronize-time-with-external-ntp-server-on-windows-server-2008-r2/

**Comment by Samaru-Zoka** [comment]
Hi
I got w32time to work correctly and forbid access to windows .time . But
now I am having trouble forbidding access to any DNS server except my
router.

How we clear the firewall state table. I tried disabling the network
adapter and that didn't work. I have opendns specified in ipv4 settings and
the router ip specified in the dnscache service allow rule, and DNS still
works

Thanks and happy new year

**Comment by Samaru-Zoka** [comment]
Hi,

Could you please add PID on the notifications dialog box? This is so that a
user can use Task Manager to locate the Service when the notification is
regarding SVCHOST

Thanks.

**Comment by Samaru-Zoka** [comment]
Hi,

I have found out how to restrict DNS to use only my router. I had to
disable  DNS in System Files. Then specify a Allow rule using my router as
Remote ip.

I would still need your help to please include the PID in the pop up
Notifications,  so that when a user gets notified of a SVCHOST packet, they
can lookup the PID in Task Manager to find out which Service it is, and
make a Rule for that Service.

Thanks in advance.
