### ISSUE TITLE
creating host rule for this address generate error

### ISSUE THREAD

**Issue by hesss5** [henrypp/simplewall#290]
Hello
https://671078.org/
seems this type of address not supported
‏2019/‏01/‏02 ‎‏05:38:28 PM,_app_parserulestring(),0x000004be,[671078.org (671078.org)],2.3.12

**Comment by hesss5** [comment]
hi
still able to connect website
‏‏`‏2019/‏01/‏03 ‎‏06:35:12 PM,FwpmEngineSetOption(),0x8032000e,FWPM_ENGINE_COLLECT_NET_EVENTS,2.3.13
‏2019/‏01/‏03 ‎‏06:35:12 PM,FwpmFilterAdd(),0x80320010,671078.org,2.3.13
‏2019/‏01/‏03 ‎‏06:35:12 PM,FwpmFilterAdd(),0x8032001c,671078.org,2.3.13
‏2019/‏01/‏03 ‎‏06:35:12 PM,FwpmFilterAdd(),0x8032001c,671078.org,2.3.13
‏2019/‏01/‏03 ‎‏06:35:37 PM,DnsQuery(),0x0000232c,671078.org,2.3.13`

**Comment by hesss5** [comment]
disable  rule
‏
PM,FwpmEngineSetOption(),0x8032000e,FWPM_ENGINE_COLLECT_NET_EVENTS,2.3.13
‏2019/‏01/‏26 ‎‏09:34:03 PM,FwpmTransactionBegin(),0x8032000e,#3944,2.3.13
‏2019/‏01/‏26 ‎‏09:34:05 PM,FwpmTransactionBegin(),0x8032000e,#3944,2.3.13

**Comment by hesss5** [comment]
‏2019/‏01/‏28 ‎‏05:01:38 AM,FwpmEngineSetOption(),0x8032000e,FWPM_ENGINE_COLLECT_NET_EVENTS,2.3.13
‏2019/‏01/‏28 ‎‏02:26:17 PM,FwpmTransactionBegin(),0x8032000e,#9750,2.3.13
‏2019/‏01/‏28 ‎‏02:27:05 PM,FwpmTransactionCommit(),0x8032000d,#4422,2.3.13

**Comment by hesss5** [comment]
simplewall_debug.log
"‏21/‏02/‏2019 ‎‏04:06:07 ب.ظ","DnsQuery()","0x000005b4","roboform.com","2.4"
"‏25/‏02/‏2019 ‎‏03:52:22 ب.ظ","DnsQuery()","0x000005b4","671078.org","2.4"
"‏25/‏02/‏2019 ‎‏03:54:17 ب.ظ","DnsQuery()","0x000005b4","imdb.com","2.4"
"‏25/‏02/‏2019 ‎‏03:54:22 ب.ظ","FwpmFilterSetSecurityInfoByKeySID()","0x8032000e","{B4A15587-03DB-49B3-AA27-7B341C3DF4AE}","2.4"
"‏25/‏02/‏2019 ‎‏03:54:22 ب.ظ","FwpmFilterSetSecurityInfoByKeyACL()","0x8032000e","{B4A15587-03DB-49B3-AA27-7B341C3DF4AE}","2.4"
"‏25/‏02/‏2019 ‎‏03:54:22 ب.ظ","FwpmFilterSetSecurityInfoByKeySID()","0x8032000e","{3C180B77-2FCA-488C-9073-E7B91D8C77D4}","2.4"
"‏25/‏02/‏2019 ‎‏03:54:22 ب.ظ","FwpmFilterSetSecurityInfoByKeyACL()","0x8032000e","{3C180B77-2FCA-488C-9073-E7B91D8C77D4}","2.4"
"‏25/‏02/‏2019 ‎‏03:54:22 ب.ظ","FwpmFilterSetSecurityInfoByKeySID()","0x8032000e","{013493EC-79F4-4882-97FD-9D7B865D69B2}","2.4"
"‏25/‏02/‏2019 ‎‏03:54:22 ب.ظ","FwpmFilterSetSecurityInfoByKeyACL()","0x8032000e","{013493EC-79F4-4882-97FD-9D7B865D69B2}","2.4"
"‏25/‏02/‏2019 ‎‏03:54:22 ب.ظ","FwpmFilterSetSecurityInfoByKeySID()","0x8032000e","{99A96784-9F86-421B-B916-18D51A3BEA50}","2.4"
"‏25/‏02/‏2019 ‎‏03:54:22 ب.ظ","FwpmFilterSetSecurityInfoByKeyACL()","0x8032000e","{99A96784-9F86-421B-B916-18D51A3BEA50}","2.4"
"‏25/‏02/‏2019 ‎‏03:54:22 ب.ظ","FwpmFilterSetSecurityInfoByKeySID()","0x8032000e","{B9A0535F-212A-4816-A4DE-7829AE5EE616}","2.4"
"‏25/‏02/‏2019 ‎‏03:54:22 ب.ظ","FwpmFilterSetSecurityInfoByKeyACL()","0x8032000e","{B9A0535F-212A-4816-A4DE-7829AE5EE616}","2.4"
"‏25/‏02/‏2019 ‎‏03:54:22 ب.ظ","FwpmFilterSetSecurityInfoByKeySID()","0x8032000e","{003BD669-6066-4E2C-AF56-AAADE86D72E6}","2.4"
"‏25/‏02/‏2019 ‎‏03:54:22 ب.ظ","FwpmFilterSetSecurityInfoByKeyACL()","0x8032000e","{003BD669-6066-4E2C-AF56-AAADE86D72E6}","2.4"
"‏25/‏02/‏2019 ‎‏03:54:22 ب.ظ","FwpmTransactionBegin()","0x8032000e","#11775","2.4"
"‏25/‏02/‏2019 ‎‏03:54:17 ب.ظ","DnsQuery()","0x000005b4","imdb.com","2.4"

**Comment by hesss5** [comment]
`"‏21/‏02/‏2019 ‎‏04:06:07 ب.ظ","DnsQuery()","0x000005b4","roboform.com","2.4"
"‏25/‏02/‏2019 ‎‏03:52:22 ب.ظ","DnsQuery()","0x000005b4","671078.org","2.4"
"‏25/‏02/‏2019 ‎‏03:54:17 ب.ظ","DnsQuery()","0x000005b4","imdb.com","2.4"
"‏25/‏02/‏2019 ‎‏03:54:22 ب.ظ","FwpmFilterSetSecurityInfoByKeySID()","0x8032000e","{B4A15587-03DB-49B3-AA27-7B341C3DF4AE}","2.4"
"‏25/‏02/‏2019 ‎‏03:54:22 ب.ظ","FwpmFilterSetSecurityInfoByKeyACL()","0x8032000e","{B4A15587-03DB-49B3-AA27-7B341C3DF4AE}","2.4"
"‏25/‏02/‏2019 ‎‏03:54:22 ب.ظ","FwpmFilterSetSecurityInfoByKeySID()","0x8032000e","{3C180B77-2FCA-488C-9073-E7B91D8C77D4}","2.4"
"‏25/‏02/‏2019 ‎‏03:54:22 ب.ظ","FwpmFilterSetSecurityInfoByKeyACL()","0x8032000e","{3C180B77-2FCA-488C-9073-E7B91D8C77D4}","2.4"
"‏25/‏02/‏2019 ‎‏03:54:22 ب.ظ","FwpmFilterSetSecurityInfoByKeySID()","0x8032000e","{013493EC-79F4-4882-97FD-9D7B865D69B2}","2.4"
"‏25/‏02/‏2019 ‎‏03:54:22 ب.ظ","FwpmFilterSetSecurityInfoByKeyACL()","0x8032000e","{013493EC-79F4-4882-97FD-9D7B865D69B2}","2.4"
"‏25/‏02/‏2019 ‎‏03:54:22 ب.ظ","FwpmFilterSetSecurityInfoByKeySID()","0x8032000e","{99A96784-9F86-421B-B916-18D51A3BEA50}","2.4"
"‏25/‏02/‏2019 ‎‏03:54:22 ب.ظ","FwpmFilterSetSecurityInfoByKeyACL()","0x8032000e","{99A96784-9F86-421B-B916-18D51A3BEA50}","2.4"
"‏25/‏02/‏2019 ‎‏03:54:22 ب.ظ","FwpmFilterSetSecurityInfoByKeySID()","0x8032000e","{B9A0535F-212A-4816-A4DE-7829AE5EE616}","2.4"
"‏25/‏02/‏2019 ‎‏03:54:22 ب.ظ","FwpmFilterSetSecurityInfoByKeyACL()","0x8032000e","{B9A0535F-212A-4816-A4DE-7829AE5EE616}","2.4"
"‏25/‏02/‏2019 ‎‏03:54:22 ب.ظ","FwpmFilterSetSecurityInfoByKeySID()","0x8032000e","{003BD669-6066-4E2C-AF56-AAADE86D72E6}","2.4"
"‏25/‏02/‏2019 ‎‏03:54:22 ب.ظ","FwpmFilterSetSecurityInfoByKeyACL()","0x8032000e","{003BD669-6066-4E2C-AF56-AAADE86D72E6}","2.4"
"‏25/‏02/‏2019 ‎‏03:54:22 ب.ظ","FwpmTransactionBegin()","0x8032000e","#11775","2.4"
"‏25/‏02/‏2019 ‎‏03:54:17 ب.ظ","DnsQuery()","0x000005b4","imdb.com","2.4"`

**Comment by hesss5** [comment]
`"‏25/‏02/‏2019 ‎‏03:55:10 ب.ظ","DnsQuery()","0x000005b4","roboform.com","2.4"
"‏25/‏02/‏2019 ‎‏04:50:58 ب.ظ","FwpmGetAppIdFromFileName()","0x00000003","W:\nfreader.exe","2.4"
"‏25/‏02/‏2019 ‎‏05:01:22 ب.ظ","FwpmEngineSetOption()","0x8032000e","FWPM_ENGINE_MONITOR_IPSEC_CONNECTIONS","2.4"
"‏25/‏02/‏2019 ‎‏05:01:22 ب.ظ","FwpmEngineSetOption()","0x8032000e","FWPM_ENGINE_COLLECT_NET_EVENTS","2.4"
"‏25/‏02/‏2019 ‎‏05:01:22 ب.ظ","FwpmEngineSetOption()","0x8032000e","FWPM_ENGINE_PACKET_QUEUING","2.4"
"‏25/‏02/‏2019 ‎‏05:15:58 ب.ظ","FwpmFilterSetSecurityInfoByKeySID()","0x8032000e","{D28EAAD5-35BC-4681-9E4C-917D3E9353EF}","2.4"
"‏25/‏02/‏2019 ‎‏05:15:58 ب.ظ","FwpmFilterSetSecurityInfoByKeyACL()","0x8032000e","{D28EAAD5-35BC-4681-9E4C-917D3E9353EF}","2.4"
"‏25/‏02/‏2019 ‎‏05:15:58 ب.ظ","FwpmFilterSetSecurityInfoByKeySID()","0x8032000e","{BF43B970-EF18-4EEA-B676-DC5C41430AA6}","2.4"
"‏25/‏02/‏2019 ‎‏05:15:58 ب.ظ","FwpmFilterSetSecurityInfoByKeyACL()","0x8032000e","{BF43B970-EF18-4EEA-B676-DC5C41430AA6}","2.4"
"‏25/‏02/‏2019 ‎‏05:15:58 ب.ظ","FwpmFilterSetSecurityInfoByKeySID()","0x8032000e","{22C4474C-50DC-4FB6-9A5A-5DC6FD134007}","2.4"
"‏25/‏02/‏2019 ‎‏05:15:58 ب.ظ","FwpmFilterSetSecurityInfoByKeyACL()","0x8032000e","{22C4474C-50DC-4FB6-9A5A-5DC6FD134007}","2.4"
"‏25/‏02/‏2019 ‎‏05:15:58 ب.ظ","FwpmFilterSetSecurityInfoByKeySID()","0x8032000e","{A2601BD0-266F-42A1-807B-D95B46DAE7BE}","2.4"
"‏25/‏02/‏2019 ‎‏05:15:58 ب.ظ","FwpmFilterSetSecurityInfoByKeyACL()","0x8032000e","{A2601BD0-266F-42A1-807B-D95B46DAE7BE}","2.4"
"‏25/‏02/‏2019 ‎‏05:15:58 ب.ظ","FwpmFilterSetSecurityInfoByKeySID()","0x8032000e","{DFC3830A-B4A5-4DFA-A4A6-05B6D6747DEF}","2.4"
"‏25/‏02/‏2019 ‎‏05:15:58 ب.ظ","FwpmFilterSetSecurityInfoByKeyACL()","0x8032000e","{DFC3830A-B4A5-4DFA-A4A6-05B6D6747DEF}","2.4"
"‏25/‏02/‏2019 ‎‏05:15:58 ب.ظ","FwpmFilterSetSecurityInfoByKeySID()","0x8032000e","{EEA427B7-7699-4FF4-AEE6-EED8ED942328}","2.4"
"‏25/‏02/‏2019 ‎‏05:15:58 ب.ظ","FwpmFilterSetSecurityInfoByKeyACL()","0x8032000e","{EEA427B7-7699-4FF4-AEE6-EED8ED942328}","2.4"
"‏25/‏02/‏2019 ‎‏05:15:58 ب.ظ","FwpmTransactionBegin()","0x8032000e","#11775","2.4"
"‏26/‏02/‏2019 ‎‏12:35:37 ق.ظ","DnsQuery()","0x0000267c","671078.org","2.4"
"‏26/‏02/‏2019 ‎‏12:35:37 ق.ظ","GetAddrInfoEx()","0x00002af9","671078.org","2.4"
"‏26/‏02/‏2019 ‎‏12:35:37 ق.ظ","_app_parserulestring()","0x000004be","[671078.org (671078.org)]","2.4"`

**Comment by henrypp** [comment]
Oh shi~ my eyes, no crlf and formatting!

**Comment by hesss5** [comment]
> 
> 
> Oh shi~ my eyes, no crlf and formatting!
hi sorry
check here
https://gist.github.com/hesss5/103532d755ebe63cf707209740a4c78a#file-simplewall-debug

**Comment by hesss5** [comment]
only new one seems not improtant
https://gist.github.com/hesss5/e17982ae5a63a22927550b13ee4221b4#file-nn

**Comment by hesss5** [comment]
https://gist.github.com/hesss5/26921a044efd755816ee97f584e8d38b#file-gistfile1-txt

**Comment by hesss5** [comment]
https://gist.github.com/hesss5/11a5c20026be3e3d57da1b37f940307a

**Comment by hesss5** [comment]
some more log for beta 3.0.5
https://gist.github.com/hesss5/fda3df4cbe8ad1981816cae3cee2c617

**Comment by henrypp** [comment]
There is no bug, SW use your computer default DNS configuration, and this errors means your dns resolver does not have any information about this host.
