### ISSUE TITLE
programs that are located on mounted/removable drives -still- don't get recognized after unmount/mount

### ISSUE THREAD

**Issue by tokariu** [henrypp/simplewall#291]
Sorry to re-re-open this issue again, but it is still not fixed and very annoying in everydays simplewall usage. I'm still eager but patiently waiting for a fix even after a year. the handling of programs affected by this issue is very cumbersome each day and hard to get used to.

this is still replicable, see: 
https://github.com/henrypp/simplewall/issues/128
https://github.com/henrypp/simplewall/issues/128#issuecomment-388785691

what's going on with this issue?
can't be fixed? don't want to be fixed? no solution found on how to fix this issue? low priority?

**Comment by hesss5** [comment]
this is what happen for me
plugged in usb drive run program allow access internet in simplewall
now unpluged usb,program in simplewall become red
then re-plug usb,program in simplewall become green has access to internet
now restart simplewall still has access internet
again unplugged usb + exit simplewall
run simplewall (red) then plugin usb drive become green again(icon not updated its icon  is just like svchost) but still has internet access
at some point hidden error happen but all time have access internet
‏2019/‏01/‏03 ‎‏10:51:12 PM,FwpmGetAppIdFromFileName(),0x00000003,H:\myfiles\dnsbench.exe,2.3.13

now tested with softperfect ram disk
you should have ram disk created and enabled
now copy program in it save ramdisk
run program allow it now it has internet access
unmount ram disk (red highlight)
mount ramdisk (convert to green highlight)
run program it ask for internet access(so here again ask it,in usb wont ask but has access internet)
i wont allow access but restart simplewall
now it has internet access again

**Comment by ltGuillaume** [comment]
A fix seems to be in the works, judging from the updated language files.
