### ISSUE TITLE
Firewall Profiles for simplewall - Important

### ISSUE THREAD

**Issue by ghost** [henrypp/simplewall#293]
Request for introduce Firewall Profiles feature for simplewall
it'll let certain programs assign to each profile groups and able change them anytime.
  
ex: 
- home profile
  google chrome,firefox

- office profile
  teamviewer/ logmein

- free-time profile
  google chrome/teamviewer/cargame 

+ so those each profile assigned softwares only able connect internet
+ also same software can be assign for multiple profiles depend on time of work

i hope that will useful like for everyone also users who want restrict connectivity deeply.

----------
see: https://support.eset.com/kb3478/?locale=en_US&viewlocale=en_US
(navigate > Create your Personal firewall profile)

**Comment by GintokiHub** [comment]
It would be a real neat feature to have some sort of community build set of firewall profiles which, 
then be able to activate within the client to block or allow certain ports apps and specific use cases.

Should I create a different 'issue' for this?

**Comment by geonanorch** [comment]
I was also looking for this feature :-)

Similar to the great but aging Privacyware's PrivateFirewall, I think that it would make more sense to associate the profile with a specific set of local adapter IPs (e.g. home is `192.168.0.0/16`, work is `10.0.0.0/8`, etc...). Once the profile is set, rules can be defined as usual within the profile.
An advantage of that approach is that the current profile can be auto-selected on IP-change (again like PrivateFirewall).
