### ISSUE TITLE
cmd switches for silent installing

### ISSUE THREAD

**Issue by truefriend-cz** [henrypp/simplewall#294]
Do you can add cmd argument for silent install app?
I tested switched as /SILENT and /VERYSILENT but show install window only.
If test use switch /S no show any window (its ok) but no installed product.

Thanks

**Comment by truefriend-cz** [comment]
No. Is it not true. If running with /install /silent switches then show dialog for instalation.

`simplewall-2.4.6-setup.exe /install /silent`

**Comment by henrypp** [comment]
Switches are not for setup, it's for simplewall itself.

`simplewall.exe /install /silent`

**Comment by truefriend-cz** [comment]
Why not for setup?

**Comment by henrypp** [comment]
Because setup is not designed for this!
