### ISSUE TITLE
Question: If I specify WhiteList Mode, then I don't need any Block Rules, right?

### ISSUE THREAD

**Issue by Samaru-Zoka** [henrypp/simplewall#296]
Hi,
If I select WhiteList mode, then all that's needed is Allowed Programs ? Meaning all other programs will be block outbound and will not be allowed to receive traffic inbound ? 

Will non-blocked-non-specified programs create a Firewall State before being blocked outbound? That is, will inbound traffic be allowed to a program that has no block rule ? For instance, ZoneAlarm free has a setting for a program \windows\system32\ApplicationFrameHost.exe ? Now by default, it is set to Auto, and has ? specified for inbound and outbound. If I don't specify a rule for that program in SimpleWall, no inbound traffic to that program will be allowed, correct ?

The bad thing I found with ZoneAlarm Free is that at first run, it recognized 56 programs, and set them to Auto. Then at next program run, it recognized 80 programs. I just wonder if this list will keep on growing. And what is going to happen when a program it does not recognize when incoming or outgoing traffic arrives. I am hoping that SimpleWall whitelist will stop everything outgoing or incoming if I don't have an allow rule.

**Comment by uBlock-user** [comment]
>Meaning all other programs will be block outbound and will not be allowed to receive traffic inbound ?

Yes, that's what whitelist mode is by definition. You have to create whitelist rules to allow network connections to work.
