### ISSUE TITLE
translation - resource.rc

### ISSUE THREAD

**Issue by Henry2o1o** [henrypp/simplewall#300]
```
<empty>

IDS_STATUS_EMPTY "<empty>"
```

![image](https://user-images.githubusercontent.com/6131799/51310031-037bf900-1a46-11e9-92e8-4eca7d9e2d9a.png)

**Comment by henrypp** [comment]
Whats question?

**Comment by Henry2o1o** [comment]
translation: <empty>
german: <Leer>

**Comment by henrypp** [comment]
of cource its empty, because this string is not translated https://github.com/henrypp/simplewall/blob/master/bin/i18n/German.ini#L165

ps: simplewall.lng is _always_ read-only!

**Comment by Henry2o1o** [comment]
Thanks, it works.
