### ISSUE TITLE
Custom grouping

### ISSUE THREAD

**Issue by Jtasiu** [henrypp/simplewall#306]
Is there a way to add custom groups? For example I have a few work programs with different names but they need to be enabled/disabled together from time to time. Can there be added a way to add custom groups and which group order to show them in the interface when there are multiple groups? Also if added a right-click on the group name and showing enable/disable option for the entire group will be very useful.

**Comment by TontyTon** [comment]
You can use 'User Rules', and select the required apps.
Everything except 
> which group order to show them in the interface when there are multiple groups
is already available.

**Comment by henrypp** [comment]
No, only 2 groups and 3-rd (special rules) are optional

**Comment by Jtasiu** [comment]
@henrypp

Can I make request to have feature to be able to make custom groups...or is that no?
