### ISSUE TITLE
Add folder

### ISSUE THREAD

**Issue by Jtasiu** [henrypp/simplewall#307]
Is there a way to add entire folder of programs to simplewall? I see it is possible to select multiple .exes/other files but is it possible to add a folder including subfolders?

**Comment by ltGuillaume** [comment]
Now you're just lazy ;-) :-P

**Comment by dima-lisolyub** [comment]
There are applications that change their path each update. League of Legends and Discord, for example. I need these five files allowed to have the game working. As you see, there are folders with numbers. Next update there will be other numbers. This add folder feature would be very convenient.

League of Legends\RADS\solutions\lol_game_client_sln\releases\0.0.1.255\deploy\League of Legends.exe
League of Legends\RADS\projects\league_client\releases\0.0.0.183\deploy\LeagueClientUx.exe
League of Legends\RADS\projects\league_client\releases\0.0.0.183\deployLeagueClient.exe
League of Legends\RADS\projects\league_client\releases\0.0.0.182\deploy\LeagueClientUx.exe
League of Legends\RADS\projects\league_client\releases\0.0.0.182\deployLeagueClient.exe

**Comment by skupjoe** [comment]
Wildcard support would work for this and also solve this issue if it could somehow be implemented.

Or if we could just go by relative program name (no fully declared path)

 #1441 for more thoughts/discussion
