### ISSUE TITLE
When an application updates, keep allowing existing rules to work

### ISSUE THREAD

**Issue by ryanbr** [henrypp/simplewall#31]
Everytime Battlenet/Overwatch updates it shows up as an filter application (unticked), currently I have 3 battle.net.exe processes listed. tl;dr basically if I whitelist battlenet then it updates it should keep the exisiting whitelisted process and not treat the update it as completely new app everytime.

**Comment by henrypp** [comment]
update does not ignore existing configuration.
are you use portable package or not?

**Comment by ryanbr** [comment]
Example; http://i.imgur.com/iyoo5JZ.png

Using Win10, non-portable version. Also I have multiple copies listed of other applications which also updated. (googleupdate.exe and "google play music desktop player.exe")

Seems everytime an application updates itself, simplewall then believes its a new application and blocks it. Requiring to whitelist it again.

**Comment by henrypp** [comment]
simplewall gives access to application by its path, maybe because Battlenet/Overwatch after update itself change his path and cannot access to the internet.

**Comment by ryanbr** [comment]
Same path, nothing changes here. Becomes annoying after a while if I have to keep whitelisting updated apps that should just work. I guess simplewall probably isn't for me

**Comment by henrypp** [comment]
on your screenshot 1 "battle.net.exe" is checked, but marked red, it means "file not found", and other 2 "battle.net.exe" executables tells me contained in different folders, isn't it?

maybe isn't for you. i dont know.
