### ISSUE TITLE
Question about Rules editor

### ISSUE THREAD

**Issue by StphamZ** [henrypp/simplewall#313]
In Rules editor have two rule: **Rule (Remote)** and **Rule (Local)**, what that mean?, I was read wiki and as introduction have one rule but now in app have two and I don't understand, can someone explain me more?

**Comment by rwilliamsit** [comment]
I wondered the same thing.  I learned by trial/error.  Remote=destination, Local=source.  So if you want to allow traffic to port 80 as a destination, put 80 in the Remote box.

**Comment by H9j8** [comment]
Thank @rwilliamsit, now I was understand it 🕺
