### ISSUE TITLE
UI improvement [user rule] [feature request] [UI]

### ISSUE THREAD

**Issue by pwn0r** [henrypp/simplewall#322]
One very overdue feature is an expansion on the remote rule edit field. 

While one can enter MANY ip addresses / ranges etc it is VERY hard to even read that if there are too many. A real usage case here -- some scriptkiddies want to brute force my VPS machine on windows and they use a few tens of different IP addresses for that. So I want to ban them all -- but even entering them into the current edit field is annoying. 

Reading and removing entries in case there are more them 4-5 of them -- is a real bother. 

Alternative, and perhaps an ideal solution would be a banlist. <3
But of course it needs to be very efficient from programming POV, perhaps maybe on the level of legendary UBlock0rigin performance :) In this case you need a button next to the field, and therefore you can avoid e.g. a list box (which saves user UI space in the window). 
Then the rule will effectively pick up a TEXT FILE on the system and parse all  remote rules from there. The rest of the options can be still set up in the same window. 

Of course the file then must be in a simple text format, no XML/JSON/whatever BS and no delimiters, just one rule per line, as follows:

192.168.10.0/24
192.168.1.255
10.10.0.0/16

etc etc. 
In this case I would be able to e.g. download an existing ban list of detected botnets etc and just enable it on the firewall. Unless there are some performance considerations, it would be nice to allow many entries per file, perhaps thousands.

**Comment by TontyTon** [comment]
+1 from me. It was very annoying for me to add many Google IP addresses range, but I created a text file and copy & pasted to SW. 
FOR NOW, you may use it . But remember to take care of [Rules Syntax](https://github.com/henrypp/simplewall/wiki/Rules-editor).

[Also Enter doesn't work, all IPs should be in one line :( ]

**Comment by pwn0r** [comment]
indd, 

in this particular case even windows firewall is better -- it allows entering / IP addresses / IP blocks / in listboxes, so you can add, remove and modify entries easily.

Current edit fields allows maybe at best 15 IP block entries (i.e. with /24 etc suffix at the end). 
At work we have a few windows servers including available online. One server has only windows firewall, which is not good but in this case it has around 100 ip *blocks* entries and that more or less reduced hacking attempts to bare minimum.
