### ISSUE TITLE
Does a blacklist need to enabled if I use whitelist only method?

### ISSUE THREAD

**Issue by Lucaas87** [henrypp/simplewall#323]

**Comment by henrypp** [comment]
what blacklist?

**Comment by Lucaas87** [comment]
The blocklist which blocks Windows spying etc.

https://github.com/henrypp/simplewall/issues/243#issuecomment-428550931

Does it need to enabled if I use whitelist mode?

**Comment by henrypp** [comment]
@Lucaas87 
blocklist working on both (whitelist/blacklist) modes.
and if you <s>understand</s> need it - enable them.
