### ISSUE TITLE
Geolocation

### ISSUE THREAD

**Issue by pwn0r** [henrypp/simplewall#324]
One obvious feature missing in this wonderful app is geolocation. 

In fact, that would be pretty easy to implement, as there are _free and regularly updated_ databases available online. And yes, I would actually prefer specifically _offline geolocation mode_ rather than constant online lookups. 

So in short it is pretty easy -- the database most recommended is GeoLite2:
https://dev.maxmind.com/geoip/geoip2/geolite2/

it comes as an archive with a few CSV files in it, also has a few languages included for location names. 

Ideal solution would be to request a user to download an archive and copy it to simplewall folder. 
Then simplewall can take this CSV files in the language required and use them for offline lookup. For starters, country lookup is fine, more precise location could be the next step after that, if at all required. IP4toCountry databases even in CSV format are not that large, only about 15mb. IP6toCountry is much less, around 3mb. 

The main thing is not just to report a country in the notification UI, but to enable such rules on the firewall. I.e. the ultimate feature would be an ability to restrict connections to certain countries only.

These databases (there is one other service software77.net) are what some NirSoft tools  use and come recommended by their developer.

**Comment by GintokiHub** [comment]
If this is ever implemented please add the option to either enable or disable this, I assume you will but just putting it out there.
Or are you simply suggesting an auto-resolve geoip by IP range, which then shows a flag on every connection shown? This would be a nice feature to have.

**Comment by henrypp** [comment]
dup #298

**Comment by elico** [comment]
I am unsure if this was given an option.
There are many geoip plain cidr files out there.
Is it possible to define a list file and block/allow by it? maybe checking for updated periodically(minutes/hours/days)?
