### ISSUE TITLE
[вопрос]

### ISSUE THREAD

**Issue by perdolka** [henrypp/simplewall#325]
Контекстное меню программы предлагает удалить (из списка) неиспользуемые приложения (их у меня 65).
Это приложения, которые долго не "просились" в интернет? 
А какое именно время установлено?

UPD
Уже вижу, что удаляет просто всё из списка заблокированных.
В таком случае, возможно было бы лучше назвать эту функцию:
 "Очистить список заблокированных приложений" ? 
Это звучало бы более однозначно.

А фичу, о которой я изначально ошибочно подумал (возможность очищать списки от программ, которые N времени не стучались в интернет), было бы неплохо иметь в программе. ;)

**Comment by henrypp** [comment]
> В таком случае, возможно было бы лучше назвать эту функцию:
> "Очистить список заблокированных приложений" ?

Нет, эта функция удаляет неиспользуемые (приложения к которым никакие настройки и правила не применены). Так что всё логично!

> А фичу, о которой я изначально ошибочно подумал (возможность очищать списки от программ, которые N времени не стучались в интернет), было бы неплохо иметь в программе. ;)


Пока не планируется!
