### ISSUE TITLE
programs that are located on mounted/removable drives *still* don't get recognized after unmount/mount

### ISSUE THREAD

**Issue by tokariu** [henrypp/simplewall#329]
What shall I say.. I feel sorry again for re-opening this neverending issue. But the problem is still not fixed.

The issue: https://github.com/henrypp/simplewall/issues/128#issuecomment-388785691 is still applicable and reproducable with simplewall v2.4, despite the changelog item: fixed duplicate filters callback on device arrival (issue #291)

Please try to reproduce the issue from the above comment for yourself and you will notice in simplewall_debug.log the same error as before:

,"FwpmGetAppIdFromFileName()","0x00000003","X:\jdownloader v2.0\jre\bin\javaw.exe","2.4"
,"FwpmGetAppIdFromFileName()","0x00000003","X:\jdownloader v2.0\jdownloader2.exe","2.4"

the program is whitelisted in simplewall. But still after mounting the volume the program keeps getting blocked by simplewall until I manually hit F5/refresh app-list in simplewall-UI.

Just another thought: does it make a difference for simplewall whether the device is mounted as removable device or as a non-removable device?
Ok, I've just tested it when mounting as non-removable device, but it doesn't make a difference. It won't work until hitting F5/refresh the applist.

**Comment by pwn0r** [comment]
I have seen recently same behaviour. I have one drive which is often unmounted, and I have some applications running from that volume. The applications are in the simplewall list. Still, temporarily unblocking them and then mounting the volume does not work. Simplewall would show notification about these applications.

**Comment by tokariu** [comment]
just an update: the problem is still an issue with v3.0 beta.

**Comment by tokariu** [comment]
@henrypp, this issue is a neverending story. it is still not fixed, yet it has been closed for the 3rd time. please re-open until it is really fixed.

**Comment by tokariu** [comment]
@henrypp I'm sorry, it's still not working as expected. 

at the beginning of the issue, simplewall didn't even message me about blocked packets from applications on removable/mounted disks. I had to manually add an allow-rule each time I start that program

then, after some simplewall updates and fixes the behaviour has changed. and this is the state until today:
if I start a program from such a removable/mounted disk, simplewall shows a pop-up and asks if I allow the traffic. it does taht each time I start the program for the first time after a boot. It -never- remembers my decision to allow the programs traffic, despite choosing so. 

so until this day, it's like: you always have to allow traffic for the program at least one time after each reboot.

I'd consider this issue fixed if simplewall also remembers my decision so it doesn't ask each time again after a reboot.
