### ISSUE TITLE
how to remove red X on windows security center?

### ISSUE THREAD

**Issue by yula11** [henrypp/simplewall#333]
hello, how to remove red X frome windows security center? ( without activating windows firewall )

![image](https://user-images.githubusercontent.com/48089616/53562467-b0c64e80-3b66-11e9-8436-dd389fdf6ca2.png)

**Comment by henrypp** [comment]
Maybe [google](https://www.howtogeek.com/244539/how-to-disable-the-action-center-in-windows-10/)? No?
