### ISSUE TITLE
block local connection

### ISSUE THREAD

**Issue by Teloerr** [henrypp/simplewall#334]
hi, for securiy add block local connection feature , it can prevent some attack from local network.

**Comment by henrypp** [comment]
hi, i dont know

**Comment by Teloerr** [comment]
some vpn android app and windows vpn such as openvpn for android or airvpn have feature block local connection to prevent accessing to local connection. you can add to simplefirewall

also, i  can not find a way to block IP ! i can block app or service only with some IPs that you enter to block spy.
is there any way to block different IPs or url ?

**Comment by henrypp** [comment]
Yes.
https://github.com/henrypp/simplewall/wiki/Rules-editor
