### ISSUE TITLE
v2.4.x crashes or gets into loop on disconnection

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#337]
This seemed to have been fixed in v2.2-2.3, but since v2.4 I'm seeing this again on a regular basis after my (IKEv2) VPN connection disconnects.

![image](https://user-images.githubusercontent.com/4777345/53683539-35999f80-3d02-11e9-918b-a32cb80392ab.png)

With v2.4.x, I either get the crash above, or simplewall.exe takes up 50% CPU after a disconnect.

Could this have anything to do with the fact that on a disconnect, Windscribe forcibly closes all sockets in order to prevent any leaking? If not, it's some issue with a regular Windows 10 IKEv2 VPN connection.

**Comment by henrypp** [comment]
Sometimes it happens again on 2.4.2 =(

**Comment by ltGuillaume** [comment]
I tried to downgrade to 2.3.1, then simplewall just gave me hundreds of error messages, trying to delete rule #5. When upgrading to 2.4.2, the error messages stopped (and there was nog simplewall_error.log), but it jumped to 50% CPU and then silently crashed. There's not even a Windows  event log entry of the crash.

**Comment by TontyTon** [comment]
Why this is closed, the bug is still there.
I have to turn off Auto start and have to open SW eachtime I want to change some rules.

**Comment by henrypp** [comment]
@ltGuillaume you cannot be downgrade to 2.3.x when 2.4.x option "Secure filters" is enabled.
@TontyTon becoz it fixd - reliz soon!

**Comment by ltGuillaume** [comment]
Yeah I figured it would be that, so I upgraded again, disabled "secure filters" and downgraded.

**Comment by henrypp** [comment]
@ ltGuillaume 2.4.3 is fixed crashes, so you can use it!

**Comment by ltGuillaume** [comment]
Thx! I'll download it now!

**Comment by TontyTon** [comment]
@henrypp Facing the same issue in v2.4.3 
Have to exit Simplewall to be able to use PC

**Comment by ltGuillaume** [comment]
I found that updating something as simple as the language file tends to crash simplewall 2.4.x, too.

**Comment by ltGuillaume** [comment]
The latest language update (11-Mar-19 08:41) is "stuck": simplewall 2.4.x keeps notifying there's an update, but there isn't.

**Comment by TontyTon** [comment]
@ltGuillaume I don't think it is the problem because SW is not showing me any updates, it says 'No updates available'.

Also we are facing the crash from long before 11 March

**Comment by ltGuillaume** [comment]
@TontyTon You're right, this is sloppy of me: I shouldn't have mentioned this separate crash in this issue.

**Comment by TontyTon** [comment]
@ltGuillaume Ooops! You were mentioning a seperate crash and I thought that you were giving a possible reason of the orginal crash of this issue. (⁄ ⁄•⁄ω⁄•⁄ ⁄)

**Comment by henrypp** [comment]
@TontyTon @ltGuillaume, when 2.4.3 crashed? If on system restore (from sleep/hibernation), then i know and now fixed this!

**Comment by ltGuillaume** [comment]
Ok, this is odd. After getting this again, and again, and again:
![image](https://user-images.githubusercontent.com/4777345/54380230-45629d80-468b-11e9-9f26-f828a91b08d3.png)
I went to the simplewall folder and simplewall.lng suddenly had the read-only attribute! Well, I guess that's solved then, although I haven't a clue why the attributes would have been changed...

**Comment by henrypp** [comment]
@ltGuillaume its already fixed!
