### ISSUE TITLE
2.4.2 is buggy

### ISSUE THREAD

**Issue by Jtasiu** [henrypp/simplewall#339]
I upgraded to 2.4.2 beta portable x64 and found it was very buggy. Some problems I faced:

1. Using whitelist mode but none of the rules work. Even programs which don't have allow rule can access the internet

2. Only happened once but the first time I upgraded I lost all my apps settings and only custom rules was still there (luckily still had backup to restore some settings). After trying to upgrade again I didn't lost any app settings but the 1st problem mentioned above was still there.

I had to install 2.4.1 and restart to get simplewall working again. If I just downgrade to 2.4.1 I still have the problem of programs which don't have allow rule that can access the internet but for some reason if I restart then 2.4.1 works properly.

**Comment by henrypp** [comment]
With 2.4.3 the same?

**Comment by Jtasiu** [comment]
@henrypp

The problem happens when I upgrade from old portable version to newer version. For some reason then simplewall doesn't work. Once I restart then it works properly.
