### ISSUE TITLE
Make the binary more secure (sign+GPG)

### ISSUE THREAD

**Issue by beerisgood** [henrypp/simplewall#34]
Please sign the exe so Windows show it as valid.

Also it would be nice if you provide a GPG.asc signature for the binary so we can check if the file is realy from you. The checksum only provide a integrity test.

**Comment by henrypp** [comment]
nice idea! how?

**Comment by beerisgood** [comment]
As for digital signing i have no idea. But i'm sure it exist tutorials on internet

But for GPG signature thats easy: install GPG, create a 4096bit key with valid contact info (mail and your real name or your username here), upload your public key to the GPG server, sign the binary and provide the .asc file under downloads. You need then sign every binary
With the .asc file and your public key we can verify the binary is realy from you.

And we can sign your public key to strengh it.
Also you need to publish your public key ID with fingerprint on https://github.com/henrypp/simplewall so all users can import your key and can check if the key ID is correct

**Comment by henrypp** [comment]
+ Now added GPG key to GitHub and this will be sign all commits.

**Comment by beerisgood** [comment]
Nice!

Please post your GPG Key (with fingerprint) on https://github.com/henrypp/simplewall so we can use it.

**Comment by beerisgood** [comment]
*push*
i still miss your GPG key info. See my post above

**Comment by henrypp** [comment]
i think where do i post this key, because i will sign all apps and post it on all repos is not rational.
maybe add information into "readme.md" with link for key on a keyserver and fingerprint.
anyway, what do i post - secret key or public (or both of them)?

**Comment by beerisgood** [comment]
Into readme with key ID & finterprint is enough.
You just need to post your public key ID (_0x_**YOUR KEY ID**) with the fingerprint.
For example here mine:
0x**620F071D** (github show 97F9E213**620F071D** but i dont know why) - fingerprint: 3D3A A8EA 763A A97D A252  0714 97F9 E213 620F 071D

Also you should NEVER post anywhere your secret key. This is very important and should be always offline.

**Comment by beerisgood** [comment]
*push*
Also it would be nice if you can sign the latest version and make a new release, maybe 1.6.5**.1** because its a small change and dont change the code

**Comment by henrypp** [comment]
done! version is NOT changed!

http://www.henrypp.org/product/simplewall#gpg

**Comment by beerisgood** [comment]
Nice!

Now we need the .asc file for the binary so we can check the signature.

Also it would be good if you can copy your pubkey.txt to GitHub so you have in case of infected own server a secure copy on GitHub.
I sign your key (5635B5FD) with my key (620F071D) so it get more trustworthy.

**Comment by henrypp** [comment]
Attach .asc to _every_ binary i can't. I put key id and link to hkps.pool.sks-keyservers.net on a website.
I think this is enough!

**Comment by beerisgood** [comment]
But we need the .asc files to check the signature. Without it isnt possible!
The command is **gpg --verify [[ sigfile ] [ signed-files ]]**

See here for create that asc files: https://www.gnupg.org/gph/en/manual/x135.html

Also the SHA256 checksum is now wrong for the signed binary

**Comment by henrypp** [comment]
With simplewall sha256 is A-ok.

Sign .exe with: **gpg --output [ sigfile ] --detach-sign [ signed-files ]**

And upload pubkey to all repos.

**Comment by beerisgood** [comment]
We cant get the .asc file.
You need to publish it.
And without it we cant verify the binary with your key

**Comment by henrypp** [comment]
Why you cant? Here: https://raw.githubusercontent.com/henrypp/simplewall/master/pubkey.asc

**Comment by beerisgood** [comment]
Because that doesnt work.
If i try "gpg --verify pubkey.asc simplewall-1.6.5-setup.exe" i got a unknown error.
Same when i rename pubkey.asc to simplewall-1.6.5-setup.exe.asc

**Comment by henrypp** [comment]
- pubkey.asc isn't signature, it's a public key for import into local gpg database.
- _simplewall.sig_ is a signature and signed only binaries simplewall.exe (32/64)

`gpg --verify simplewall.sig simplewall.exe`

**Comment by beerisgood** [comment]
Yeah i know.
But where i get the simplewall.sig file?

**Comment by henrypp** [comment]
Near with simplewall.exe

**Comment by beerisgood** [comment]
So you only signed the binarys from the packed .zip version and the installed binarys from installer .exe version?
For installer version that isnt good. Better signed the whole installer.exe because we need to verify it before we start the .exe with adminrights

**Comment by henrypp** [comment]
Okay, i hear you

**Comment by henrypp** [comment]
Done. All is done.

**Comment by beerisgood** [comment]
Thank you!
Works fine now
