### ISSUE TITLE
Custom timers

### ISSUE THREAD

**Issue by Jtasiu** [henrypp/simplewall#340]
Can there an option to add more timer options?

I would love to use some other timings like 2 mins, 5 mins, 12 hrs, 24hrs, 3 days etc.

**Comment by pwn0r** [comment]
seconded.

We use to have 1 min timer and it was very useful. Now I use 10min for installations (many programs want internet access during install phase, sometimes I give access to them). I think 1 or 2min for a short duration timer would be best.
