### ISSUE TITLE
不要关闭系统防火墙

### ISSUE THREAD

**Issue by chibuhu** [henrypp/simplewall#341]
不知道从那个版本开始，会关闭win10系统防火墙，请修复

**Comment by henrypp** [comment]
In english please!

**Comment by chibuhu** [comment]
Software opening will automatically shut down the system's own firewall, what settings can not shut down the system's own firewall? Can software and system firewalls coexist?

**Comment by chibuhu** [comment]
simplewall

**Comment by henrypp** [comment]
- Windows Firewall enginered using Windows internal (WFP) engine
- simplewall enginered using Windows internal (WFP) engine

Yes, it can work together, even WF was disabled!
