### ISSUE TITLE
Windows update kb4489899 reset simplewall filters

### ISSUE THREAD

**Issue by fredgolightly** [henrypp/simplewall#346]
I've just installed kb4489899 on Windows 10 x64 via Windows update and restarted, now simplewall is completely reset, no apps are listed, all settings are as default. I installed simplewall ie it's not run in portable mode. Has anyone else had this happen?

**Comment by henrypp** [comment]
How you determine is kb4489899 concern with simplewall profile?

**Comment by fredgolightly** [comment]
I booted & sw was fine, installed update & sw was reset, so I restored my macrium system image from the weekend & sw was as before, installed update & rebooted & sw was reset again. Could be something else but no idea what

**Comment by henrypp** [comment]
@fredgolightly i am updated my comment, check it!

**Comment by fredgolightly** [comment]
Yes, I explained in my comment that I'm not running portable version, but system install, which shouldn't be affected by updates

**Comment by henrypp** [comment]
check `%APPDATA%\Henry++\simplewall` for `apps.xml` and other xml's

**Comment by fredgolightly** [comment]
No such folder in local or roaming. Guess my install is messed up, I'll start again

**Comment by henrypp** [comment]
Change simplewall installation path.

**Comment by fredgolightly** [comment]
To where? It's installed to the default ie c:\program files\simplewall

**Comment by henrypp** [comment]
And you want to run _portable_ version from `c:\program files\simplewall`? Im afraid it's impossible because of UAC, period!

**Comment by fredgolightly** [comment]
Nope, I don't want to run the portable version, as I stated earlier. I simply want uac not to have to enter the admin password on every single boot by every non-admin user. It's installed in program files as mentioned

**Comment by henrypp** [comment]
simplewall working only under admin account, if you run this one from non-admin then it has no access to profile directory

**Comment by fredgolightly** [comment]
Why wouldn't it as it's run as admin on every boot due to the uac prompt which can't be skipped

**Comment by henrypp** [comment]
I think you are starting up under non-admin.

**Comment by fredgolightly** [comment]
Sorry if you can't understand, I have repeatedly stated that it's running on all non-admin accounts, but as it's requiring admin rights it's running as admin every time, so it's running as admin on all accounts

**Comment by henrypp** [comment]
Yes, i know
