### ISSUE TITLE
Notifications for rules (Feature Request/ Proposal)

### ISSUE THREAD

**Issue by nji9nji9** [henrypp/simplewall#347]
The scenario:
An app requires communication, simplewall gives a notification.
By looking at the kind of communication say I think that
exactly that communication type is OK. So I add a rule.
And don't wanna be bothered by notification OF THAT RULE.
But still want notifications, if the app requires another type
of communication.
As far is I understand, in simplewall it is only possible to disable
notifications for the app, but not for a rule.

I don't know much about all those things.
So maybe my proposal is not useful for some reason?
But my intention in the scenario maybe is?

**Comment by henrypp** [comment]
No. Individual (by destination) exclusion list is hard to implement, sorry!

**Comment by nji9nji9** [comment]
OK.
I thought it would be easy to implement - as just a more refined filtering.

For the user it means then: "All or nothing" for an app?
A malicious app could disguise by doing harmless communication first,
and after some time nasty ones.

**Comment by pwn0r** [comment]
> For the user it means then: "All or nothing" for an app?
> A malicious app could disguise by doing harmless communication first,
> and after some time nasty ones.

Methodologically speaking, IT IS all or nothing per se. Either a program fully trusted, or it is not. Allowing any communication outside of the local area network can be used in principle by a malicious app. I.e. you should not be allowing any communication to outside of your LAN for any application, unless there is a very good reason for it. That includes windows system applications, alot of them want to connect to outside.

**Comment by henrypp** [comment]
> 
> 
> The scenario:
> An app requires communication, simplewall gives a notification.
> By looking at the kind of communication say I think that
> exactly that communication type is OK. So I add a rule.
> And don't wanna be bothered by notification OF THAT RULE.
> But still want notifications, if the app requires another type
> of communication.
> As far is I understand, in simplewall it is only possible to disable
> notifications for the app, but not for a rule.
> 
> I don't know much about all those things.
> So maybe my proposal is not useful for some reason?
> But my intention in the scenario maybe is?

SW does not show nnotifications for User Rules at all (open Settings > Notifications > Exclusion list > Check "Exclude user rules")
