### ISSUE TITLE
Block Only Internet or Only LAN Rule

### ISSUE THREAD

**Issue by ghost** [henrypp/simplewall#349]
I'm noob, I want learn to do two kinds of rules:

First Rule: Block some softwares to access Internet allowing they access only LAN

Second Rule: Block some softwares to access LAN allowing they access only Internet

Please how I need set Rule (Remote) and Rule (Local) for each Rule? I think it can help not just me but others, maybe after can be added to wiki.

**Comment by mrochaaa** [comment]
any help? Is much hard do this rules?

**Comment by henrypp** [comment]
- Disallow loopback option
- Create rule with local network IP preset (like `192.168.0.0/32`)
- Aooly rule to the apps

**Comment by mrochaaa** [comment]
Thanks the answer, just some questios:

LAN Only Rule:

I disabled "Allow Loopback connections for all" in General Configuration.

My questions:

I use local network IP for Rule (Remote) and Rule (Local)? For Both?

And Direction I use Both also?

**Comment by subaru22b** [comment]
would like to know this also, 

@henrypp 
is that for rule one or rule two?

**Comment by mrochaaa** [comment]
@subaru22b this partial explanation is just for LAN Only rule... 

@henrypp I use local network IP for Rule (Remote) and Rule (Local)? I just leave Rule (Local) empty?

And Direction I use Both sure?

**Comment by mrochaaa** [comment]
anyone other than  @henrypp  can explain this simplewall settings? Is an question much hard to reply? Some softwares have potencial but the lack of support is an deal breaker, the simplewall documentation in an "very simple" and the support is even more "simple". Tinywall have features to restrict softwares to use just LAN easily, but with simplewall you need leard alone, haven't any manual or support, an question with two words is an pain to developer, maybe is genius with know all things and a superior human, sorry my ignorance ok? Including the ignorance of trying you software, which in last version is very bugged in Win 7, I continue use it? Going to Tinywall...
