### ISSUE TITLE
WindowsSpyBlocker rules

### ISSUE THREAD

**Issue by crazy-max** [henrypp/simplewall#35]
Hi @henrypp 

I'm the developer of [WindowsSpyBlocker](https://github.com/crazy-max/WindowsSpyBlocker) and i'm glad to see that you're using these rules ;)
I wanted to know if it would interest you that I integrate and directly generates the blocklist.xml in my repository?

The structure would look like this:

```
data/simplewall/win7/extra.xml
data/simplewall/win7/spy.xml
data/simplewall/win7/update.xml
```

Then instead of copy / paste the rules from my repository you just have to download directly from your app the rules. A project called [HostsMan](http://www.trishtech.com/2013/02/automatically-update-hosts-in-windows-with-hostsman/) can manage multi sources from the web and update automatically. I think it might interest you and why not also handle the blocking of domain names.

Let me know if you are interesting.

Thanks

**Comment by henrypp** [comment]
hi, @crazy-max

nice idea, but why do you categorize rules by OS (`win7`, `win81`, `win10`), not just by `spy`, `extra` and `update`?

> why not also handle the blocking of domain names.
i think it possible, but hosts file is better by speed (i think)!

**Comment by crazy-max** [comment]
@henrypp Because some probes are OS specific but many are common.

**Comment by crazy-max** [comment]
The simplewall data format has been added : https://github.com/crazy-max/WindowsSpyBlocker/tree/master/data/simplewall

**Comment by ryanbr** [comment]
Would this break users testing the Windows Insider Programme? (Testing beta/alpha pre-release windows)

**Comment by henrypp** [comment]
@ryanbr, yes it may.

**Comment by ltGuillaume** [comment]
Apparently, Blocklist rules take priority over custom rules. I wanted to allow a VirtualBox.exe instance to ignore the Blocklist rules I've selected for the host system, but still it blocks the connections.

**Comment by ltGuillaume** [comment]
@henrypp New release 18hrs ago: https://github.com/crazy-max/WindowsSpyBlocker/releases/tag/4.13.0

**Comment by ltGuillaume** [comment]
@henrypp New release: https://github.com/crazy-max/WindowsSpyBlocker/releases/tag/4.16.1

**Comment by ltGuillaume** [comment]
@henrypp New release: https://github.com/crazy-max/WindowsSpyBlocker/releases

**Comment by ltGuillaume** [comment]
@henrypp https://github.com/crazy-max/WindowsSpyBlocker/releases/tag/4.19.1

**Comment by ltGuillaume** [comment]
@henrypp https://github.com/crazy-max/WindowsSpyBlocker/releases

**Comment by henrypp** [comment]
@crazy-max,

Hello, Windows 10 1903 has a problem - it has a new ip addresses for update servers.

https://github.com/henrypp/simplewall/issues/206#issuecomment-495123198

**Comment by crazy-max** [comment]
Hi @henrypp, thans for your input, keep you in touch.

**Comment by ltGuillaume** [comment]
@henry https://github.com/crazy-max/WindowsSpyBlocker/releases/tag/4.22.0
