### ISSUE TITLE
Language file in release is read-only

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#350]
In the zip-file of the last releases, simplewall.lng has the read-only attribute. This causes problems when a language file update is available: simplewall keeps trying to update the file, but fails (without telling the user about it).

**Comment by henrypp** [comment]
It was fixed in 2.4.4

**Comment by henrypp** [comment]
So simplewall can rewrite read-only files!

**Comment by ltGuillaume** [comment]
Aha... And you're setting it to read-only in order to prevent people from changing it manually, and then lose the changes via language file updates? Got it!
