### ISSUE TITLE
Option "Enable special rules group" what for?

### ISSUE THREAD

**Issue by nji9nji9** [henrypp/simplewall#352]
Can please anybody explain what this does?
Haven't found anything about that.

**Comment by pwn0r** [comment]
yes, it was a concealed feature implemented on request from a few users here, myself included if I'm not mistaken:)  IMO it should be a default option anyway :) 

It is not correct, methodologically speaking, to include _special rules apps_ into the **BLOCKED APPS** group. These apps simply have extra user rules enabled, so they are not blocked per se. 

E.g. if you allow an application to access your LAN network, it cannot be placed neither in allowed apps (where apps have full access subject to system-wide blocking rules) nor in the blocked apps. So a special group is needed.

**Comment by nji9nji9** [comment]
Thankyou.
But there is a misunderstanding.
Actually I would like to know what "Enabling special rules group" does at all.
There is no explanation anywhere what enabling/ disabling does.
And I don't see any difference.
It doesn't make much sense to have a feature that is not explained anywhere.
At least for ... ehm ... simple user like me ;-)

**Comment by henrypp** [comment]
It's UI feature only. If you do not have any custom rules applyed for the app, then you do not see this.

**Comment by nji9nji9** [comment]
The menu entry "Enabling special rules group" is always there!?!
I would expect, if I enable that ... something happens ... somewhere ...
But I don't see anything.
And there is no explanation anywhere.
Could you please give an example, and an advice how to use it?

**Comment by henrypp** [comment]
It adds apps with special rules to special rules group in main window UI.
