### ISSUE TITLE
Apply "ftp" for app [*]/ Apply "http" for ...

### ISSUE THREAD

**Issue by nji9nji9** [henrypp/simplewall#353]
Can please anybody explain what exactly this does?
Haven't found anything about that.

**Comment by henrypp** [comment]
Its predefined rules

**Comment by nji9nji9** [comment]
Thank you.
But, despite @pwn0r answer in https://github.com/henrypp/simplewall/issues/347
I can very well do a selective notification?
I dissallow any communiction for an app with the expection of a rule.
By that I still get notifications if it tries anything else/ "unusual".
If I get it right this time ... (?)
