### ISSUE TITLE
Opening Website by menu Help / Website or About

### ISSUE THREAD

**Issue by nji9nji9** [henrypp/simplewall#354]
When opening the browser by this, it is started
with unusual menu icons (not the ones normally used).
Simplewall seems to call it with special parameters?
Unwanted.

**Comment by nji9nji9** [comment]
OK, no special parameters, just
ShellExecute (hwnd, nullptr, _APP_WEBSITE_URL, nullptr, nullptr, SW_SHOWDEFAULT);
Still the effect is there (at Firefox).
Anybody to confirm?
Maybe it's because of https?
However everything OK with other apps, for example 7zip.

**Comment by henrypp** [comment]
Screenshot?

**Comment by nji9nji9** [comment]
As wanted ...
"Typical" is the way my firefox normally looks. Here invoked by 7-zip menu.
"By-simplewall" is the way the browser opens when invoked by simplewall.
BTW: both https.
![typical](https://user-images.githubusercontent.com/29798181/55087155-e8fb7700-50a9-11e9-9d3e-5acb5c8414da.jpg)
![by_simplewall](https://user-images.githubusercontent.com/29798181/55087166-ed279480-50a9-11e9-8ebe-c63d5f73fdcf.jpg)

**Comment by nji9nji9** [comment]
Got it!
I forgot that simplewall is ran from another account (the admin one).
And from that the browser is started, which has another profile there.
One more reason to point to https://github.com/henrypp/simplewall/issues/336
