### ISSUE TITLE
Unused apps, invalid apps (in status bar)

### ISSUE THREAD

**Issue by nji9nji9** [henrypp/simplewall#358]
How are they defined?
And how can I identify them?

**Comment by nji9nji9** [comment]
Get the answer for invalid apps: Simplewall highlights them, so I can identify them.
But still the question with unused apps: definition, identification?

**Comment by henrypp** [comment]
Unused is apps without applied rules or/and settings.

**Comment by nji9nji9** [comment]
Still don't understand, sorry.
In simplewall's main window in the pane "Allowed apps (7)", in "Blocked apps (16).
In the status bar: Total apps: 23, Unused apps: 1, invalid apps = 0, timer apps = 0.
But which is the "unused app"?
Why does it come where to, when it has no "applied rules or/and settings"?

**Comment by KruegerDead** [comment]
Unused it means that app not allowed, and notifications are enabled.
example: [https://imgur.com/a/rxEvQag](url)

**Comment by nji9nji9** [comment]
Thank you very much. Especially for the art! :-))
Now I know what is meant by "unused app" in simplewall.
Still:
There should be an explanation for that anywhere.
As:
I don't think the word "unused" is a matching description
for a blocked app with notifications, in contrast to the one
with disabled notifications.
To me the combination of blocked and with enabled notifications
looks like a wrong one that doesn't make sense in any case.
But, maybe I'm wrong, having not much experience in all that?
