### ISSUE TITLE
How to allow Windows Defender to update?

### ISSUE THREAD

**Issue by subaru22b** [henrypp/simplewall#359]
Hello

I like simplewall whitelisting, I want to allow windows defender to get new definitions, how to do it?

Thanks

**Comment by perdolka** [comment]
Try to add "svchost.exe" to the whitelist.

**Comment by nji9nji9** [comment]
But with svchost you open a barn door for all kind of window's unwanted communication
(See also @pwn0r answer in #347).

And then: MSE on Win7 updates definitions although I blocked svchost.

Meanwhile there seems a lot quite obscure at this "simplewall".
Best way to scare off potential users.

**Comment by subaru22b** [comment]
@nji9nji9 

i agree opening up svchost is a big problem. I would have to manually download the update.  
Thanks everyone!

**Comment by henrypp** [comment]
3.0.1 can allow Microsoft apps/update servers in-built!

**Comment by PunnyBoi** [comment]
@henrypp what is the procedure to allow Microsoft defender updating its virus definition automatically. I am on 3.0.1, but the defender is still not updating automatically?

**Comment by perdolka** [comment]
@PunnyBoi
I have two rules for allowing this:

1
![зображення](https://user-images.githubusercontent.com/24720263/59163149-a02e5880-8b05-11e9-8919-3d4bc4d98c85.png)
Remote string:
`*.prod.do.dsp.mp.microsoft.com;*.windowsupdate.com;*.dl.delivery.mp.microsoft.com;*.update.microsoft.com;*.delivery.mp.microsoft.com;tsfe.trafficshaping.dsp.mp.microsoft.com;ctldl.windowsupdate.com;80;433`

2
![зображення](https://user-images.githubusercontent.com/24720263/59163153-aa505700-8b05-11e9-9dd7-ebcba80153a9.png)

**Comment by henrypp** [comment]
@perdolka,

sorry bro, your rule sets is incorrect:

1) domain (and other) masks are not supported, so * is pointless.
2) `ctldl.windowsupdate.com;80;433` it will open port 80 and 443 not for specified site (i hope you will do something like this `ctldl.windowsupdate.com:80;ctldl.windowsupdate.com:433`, or just simple `ctldl.windowsupdate.com` is enough)
3) local rule is not portable at all - local address can change at any time, so write mask like this is good for ya `192.168.0.0/16`

**Comment by henrypp** [comment]
@PunnyBoi 3.0.1 have in-built rule sets for that (Open settings -> Rules -> Blocklist and set allow checkboxes on).

**Comment by perdolka** [comment]
@henrypp Thanks for your explanation. 👍 

Simplewall didn't show **syntax error** when I created the rule with masks " * " 
so I mistakenly decided that the mask is supported but not documented in the **wiki/Rules-editor**

**Comment by perdolka** [comment]
UPD
Strange, but my rules not working if I delete masks " * ".
If I replace
`*.prod.do.dsp.mp.microsoft.com;*.windowsupdate.com;*.dl.delivery.mp.microsoft.com;*.update.microsoft.com;*.delivery.mp.microsoft.com;tsfe.trafficshaping.dsp.mp.microsoft.com;ctldl.windowsupdate.com`
with
`prod.do.dsp.mp.microsoft.com; windowsupdate.com; dl.delivery.mp.microsoft.com; update.microsoft.com; delivery.mp.microsoft.com; tsfe.trafficshaping.dsp.mp.microsoft.com; ctldl.windowsupdate.com`
Defender updates are blocked.

**Comment by henrypp** [comment]
@perdolka 

Your previous rule is incorrect and pass all svchost traffic, thats why. I tell you again - 3.0.1 have in-built rule sets for that, no need for adds another rules to allow WU servers, just enable tick in settings.

**Comment by nji9nji9** [comment]
@henrypp
If all svchost traffic would be passed, then Defender updates shouldn't be blocked (as @perdolka wrote).
Probably they are blocked because of the disabled in-built rule?
Also I agree with perdolka that an invalid rule should give an error message.
Under no circumstances an invalid rule should cause an all-pass.
What do you think?

**Comment by perdolka** [comment]
I don't know why, but my Defender doesn't get updates, even if these settings enabled:
![зображення](https://user-images.githubusercontent.com/24720263/59199963-dfa98300-8b9f-11e9-99ae-f625a52660ed.png).
That's why I created custom rules.
Windows 10 x64, ver 1809 (Build 17763.437)
Simplewall 3.0.1

Also, if I create rule with "Remote" string: 
`prod.do.dsp.mp.microsoft.com; windowsupdate.com; dl.delivery.mp.microsoft.com; update.microsoft.com; delivery.mp.microsoft.com; tsfe.trafficshaping.dsp.mp.microsoft.com; ctldl.windowsupdate.com`
the rule is marked red, as invalid:
![зображення](https://user-images.githubusercontent.com/24720263/59200993-1d0f1000-8ba2-11e9-849f-d7180f55db44.png)

**Comment by PunnyBoi** [comment]
When I turned off the option 'Allow M$ update servers' and clicked on check for update in the defender, it showed an error. But when I turned on the option, the defender didn't give an error this time (although it didn't update so maybe I have the latest security update). So, I think that the option is working.

Also, @henrypp could you tell us what are the other consequences of enabling the option 'Allow M$ update servers'? Does it allow only defender update or it opens a gate for other (privacy related) things too? Should I be concerned about something after enabling this option?

**Comment by perdolka** [comment]
>  so maybe I have the latest security update

I think you receive a new update if you try to temporarily allow svchost and push "check for update" again.
In my case the Defender isn't showing error but also not download an update.
SW Log shows a lot of blocked outbound connections of svchost (when I force defender to check for update).

**Comment by nji9nji9** [comment]
@henrypp
A question that arose to me:
What happens if I do different settings in the blocklist versus own rules?
For example: Do not allow M$ applications in blocklist, but create a rule for say M$ live?
And vice versa.

Another thing:
Blocklist should list items in a consistent way (ALL Block or ALL Allow, but not mixed).

My serious proposal to build an usable up-to-date description/ doc how everything is meant.
There wouldn't be all the same questions, and by writing the doc you maybe come to the one
and other inconsistency for yourself.

**Comment by PunnyBoi** [comment]
> I think you will get a new update if you try to temporarily allow svchost and push "check for update"

@perdolka yes you are correct. I allowed svchost and try to update the defender and it got a new update. I was wrong when I said that I may have the latest security update.

**Comment by nji9nji9** [comment]
However manually temporarily ... is no solution for arbitrary events (like updates) ...

**Comment by PunnyBoi** [comment]
Hi @henrypp, would you mind re-opening this issue again. The defender is still not updating automatically. Till now, I am downloading the definitions from the website manually in order to update the defender.

**Comment by Janaue** [comment]
> 
> 
> Hi @henrypp, would you mind re-opening this issue again. The defender is still not updating automatically. Till now, I am downloading the definitions from the website manually in order to update the defender.

it works for me. can you try with a new profile for simplewall?

**Comment by Janaue** [comment]
> 
> 
> Hi @henrypp, would you mind re-opening this issue again. The defender is still not updating automatically. Till now, I am downloading the definitions from the website manually in order to update the defender.

i have the same problem with a STOCK profile

**Comment by Janaue** [comment]
so the way to get updates now is to allow svhost for 2minutes AND remove the default  enabled block list.

**Comment by Fixer-007** [comment]
Experienced same problem with defender updates, but I have different question, this "Allow MS application servers" block list... does it include MS Office/Defender? ETC part is bothering me :)

P.S. I really like your firewall, keep up the good work.

**Comment by Chaython** [comment]
Do one step at a time as to not allow too many things
Disable MSFT blocks in sw settings
If there's a defender app allow it
Systemsettings.exe
Service: wuauserv [windows update]
If I recall it only uses windows update, but if it's still not working:
Services:
WinDefend
SecurityHealthService

If all else fails try Allow svchost.exe with remote rule outbound 49671
