### ISSUE TITLE
how I can allow skype?

### ISSUE THREAD

**Issue by John3** [henrypp/simplewall#36]
how I can allow skype?
thanks good firewall 👍

**Comment by henrypp** [comment]
add Skype executable to simpewall and check it.

**Comment by John3** [comment]
that way I already have. I add even a custom rules but don't works. 

It have something to do with the telemetry block :D

**Comment by henrypp** [comment]
>  I add even a custom rules but don't works.

Why?

> It have something to do with the telemetry block :D

Do not need to check extra/update rules in blocklist without cause!

**Comment by John3** [comment]
Yep was some of the extra rules. Thanks.
