### ISSUE TITLE
v.2.4.5 urgent bug, with Win 7

### ISSUE THREAD

**Issue by mrochaaa** [henrypp/simplewall#360]
v.2.4.5 is crashing many times with Win 7, and last time cleaned all my whitelist, some times crash even without an opened UI

**Comment by tokariu** [comment]
have a look at the C:\Program Files\simplewall\simplewall_error.log file if there is any more information why it might crash. I recommend sticking with the v2.3.13 until the v2.4.x version is more stable.

**Comment by mrochaaa** [comment]
have any error log in SW folder,

**Comment by mrochaaa** [comment]
version 2.2 work well here

**Comment by henrypp** [comment]
When SW was crashed? It concern with dropped packets logging, it's only one i know.
