### ISSUE TITLE
Filtering does not work with all programs

### ISSUE THREAD

**Issue by ers07869** [henrypp/simplewall#361]
Unfortunately, filtering does not work with all my programs.
Here is the example of "EasyJoin", which I have in the whitlist (windows firewall is disabled) and additionally i tried to create a user rule, nevertheless the traffic is blocked.

simplewall.log:
![simplewall](https://user-images.githubusercontent.com/48952091/54997925-30f89c00-4fcd-11e9-8900-cfdb0f6ab67e.png)

simplewall 2.4.5 (tried previous versions as well)
Windows 10 1809 x64

**Comment by KruegerDead** [comment]
try this rule
`192.168.0.1/24`

**Comment by ers07869** [comment]
Thanks for the reply.
Unfortunately the rule brings a syntax error.
![grafik](https://user-images.githubusercontent.com/48952091/55169427-0e08ec00-5175-11e9-8f5c-acfaf20c6aea.png)

Because of the whitlist entry the additional rule should not be necessary at all, right?

btw:
In the meantime I updated to version 2.4.6, without any changes.

**Comment by ers07869** [comment]
> 
> 
> try this rule
> `192.168.0.0/24`
> FIXED

Also with this rule, traffic is blocked.

Same entry in the logfile as before

**Comment by henrypp** [comment]
In log file there is not simplewall filters, because name is just "EasyJoin" (no SW prefix)

**Comment by ers07869** [comment]
Thanks for the clarification.
I wasn't aware that the log file didn't just contain the sw filters...
don't know where the entry comes from

Any idea how to get rid of the rule?
I already tried to reset it over Windows Firewall Advanced Security without success.
At the moment I'm trying it with "netsh ipsec static delete filter ..." unfortunately without success so far. :/

**Comment by ers07869** [comment]
Found the program that applied the rule. :)
