### ISSUE TITLE
Automatically disable notification and block option

### ISSUE THREAD

**Issue by Jtasiu** [henrypp/simplewall#362]
If installed on new computers a lot of programs notifications will keep popping up and the user needs to manually disable notification and block requests for each program. Can there be added a "Disable notification and block" option when using the program in whitelist mode to automatically do this?

**Comment by henrypp** [comment]
You can disable notifications entirely.

**Comment by Jtasiu** [comment]
Oh. Where is the option, I can't find it?

**Comment by henrypp** [comment]
`Settings` -> `Dropped packets logging` -> `Enable notifications`

**Comment by Jtasiu** [comment]
@henrypp

Thanks. So the option will automatically add any new programs requesting internet access to the "Blocked Apps list" and also disable notifications for it?
