### ISSUE TITLE
Report/register as firewall in Windows 10

### ISSUE THREAD

**Issue by fredgolightly** [henrypp/simplewall#364]
As it takes over from win firewall it would be good if SW could register itself as an installed & running firewall as every boot I get a message saying the firewall is disabled as SW doesn't register itself as controling it. Windows Security says firewall is off also because of this. Can this be done?

**Comment by beerisgood** [comment]
(Sadly) from FAQ:
[Windows Security center integration (impossible)](https://stackoverflow.com/questions/3698285/how-can-i-tell-the-windows-security-center-that-im-an-antivirus/3698375#3698375)

**Comment by fredgolightly** [comment]
> 
> 
> (Sadly) from FAQ:
> [Windows Security center integration (impossible)](https://stackoverflow.com/questions/3698285/how-can-i-tell-the-windows-security-center-that-im-an-antivirus/3698375#3698375)

Damn. Thanks anyway!

**Comment by pwn0r** [comment]
just saying -- other programs I think work fine with that, like antiviruses with built-in firewalls? There are also commercial firewalls? 

The paragraph in the linked text above refers specifically to an antivirus, which is very reasonable. 

Sidenote: in fact 90% test on comparatives or avtest is actually pretty BS result, even windows defender should have no trouble in achieving it :)  Any antivirus worth installing, not even saying buying a subscription, should score 100% on the list of most common current malware (1000 samples) and 97-98% at the very least on the general sample (which is usually hundreds of thousands samples).
