### ISSUE TITLE
Add SEPA (IBAN & BIC) donation

### ISSUE THREAD

**Issue by beerisgood** [henrypp/simplewall#365]
If you can add this, i would donate

**Comment by pwn0r** [comment]
not really a question to me but i'm experienced somewhat in similar things -- since our respected comrade developer is from Russia there is no SEPA for him :)  

Paypal though does work in russia and I did use it to send funds to russian guys :)

**Comment by henrypp** [comment]
@beerisgood,
IBAN `KZ706010012004847494`, i will add this to donation page soon!

@pwn0r,
almost guessed, but i am from Kazakhstan ;)

**Comment by beerisgood** [comment]
Thanks!

Can you add the BIC too?

**Comment by henrypp** [comment]
BIC `KZKOKZKX`

**Comment by beerisgood** [comment]
Thanks! Will donate then

I close this here as solved

**Comment by henrypp** [comment]
I did not recieve anything! What is payent status?

**Comment by beerisgood** [comment]
Stay cool.
Which name should i use for recipient?

Also you should that info & BIC beside IBAN on your website too
(Thanks for adding IBAN info)

**Comment by beerisgood** [comment]
@henrypp

**Comment by beerisgood** [comment]
Looks like no interest exist to add the missing data

**Comment by henrypp** [comment]
Sorry, now i am open new card in another bank, and trying to investigate all for precise about information!

**Comment by henrypp** [comment]
It's done

https://www.henrypp.org/donate
