### ISSUE TITLE
Backup rules?

### ISSUE THREAD

**Issue by optomux** [henrypp/simplewall#366]
How to backup rules for deployment?

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\BFE\Parameters\Policy ?

**Comment by KruegerDead** [comment]
C:\Users\<username>\AppData\Roaming\Henry++\simplewall\rules_custom.xml

**Comment by optomux** [comment]
That will only work if firewall is installed :) 

I am talking about fresh windows install for BFE.

**Comment by henrypp** [comment]
You can create install script to xml copy and then run SW with `/install /silent` argument.
