### ISSUE TITLE
PIDs for svchost identification

### ISSUE THREAD

**Issue by xnoreq** [henrypp/simplewall#367]
Hello,

the problem is that currently simplewall just shows "svchost.exe" without any way for the user to discriminate which particular process or service it is. (Also see issue #88.)

A modern Windows 10 with enough RAM may run 70+ svchost.exe processes.
See the following screenshot from Process Hacker:
![grafik](https://user-images.githubusercontent.com/4028859/55277824-979af400-5304-11e9-86cd-d6650a3bd166.png)

Would it be possible to at least **show the PID of the process** in simplewall?

**Comment by xnoreq** [comment]
Here's some sample code on how to grab the process id:
https://social.msdn.microsoft.com/Forums/windows/en-US/72abf245-6c19-4d52-b6fe-7b18284c2a5f/retrieving-source-port-and-process-id-of-a-new-outbound-tcp-connection?forum=wfp

**Comment by asvc** [comment]
Cross-referencing https://github.com/henrypp/simplewall/issues/516#issuecomment-524632858

**Comment by henrypp** [comment]
#88
