### ISSUE TITLE
RDP

### ISSUE THREAD

**Issue by pwn0r** [henrypp/simplewall#37]
Thanks for this app, it certainly looks promising. 

Now I'm testing it on a remote VM machine running on that ridiculous Win10 (at home I'm still on 8.1. and using sadly no longer developed tinywall).

So I'm rather confused by the UI of the app. There is no system-wide rule for RDP and making a custom rule changes nothing. After some tests (for which I needed accesses to host machine as otherwised RDP is blocked) apparently I need to open svchost.exe...  After that RDP works but that's way too permissive.

What is the actual way to allow only RDP connections but not allowing anything else?

**Comment by henrypp** [comment]
you can apply rules individual for apps. add custom rule "3389" (rdp port) and do not enable it, then on main window click on svchost.exe -> Settings and set check on rdp rule to enable access.

**Comment by pwn0r** [comment]
aha, though I did something wrong as I did a rule before. Tried again -- same result. If I uncheck svchost -- the RDP connection drops and unable to recover. Custom rule for 3389 all protocols and both inbound and outbound.

Log file:

`[‎09-‎Jul-‎17 ‏‎20:24:31] C:\windows\system32\svchost.exe (NT AUTHORITY\NETWORK SERVICE) [TCP:----:16720] simplewall\Block inbound traffic [Remote]
[‎09-‎Jul-‎17 ‏‎20:24:31] C:\windows\system32\svchost.exe (NT AUTHORITY\NETWORK SERVICE) [TCP:----:3389] simplewall\Block inbound traffic [Local]`

first IP is my home computer IP and second one is target machine IP (it has a direct IPv4 address assigned to it)

**Comment by henrypp** [comment]
are you checked your new rule as i say?

**Comment by pwn0r** [comment]
[https://s9.postimg.org/ug6lxun9r/3389.png](url)

is this a correct rule? this rule did not work if checked either globally or on svchosts only. 
And to confirm, if checkbox is checked on the application itself that means it can do _both_ inbound and outbound connections, right?

**Comment by henrypp** [comment]
No. Wrong syntax. Set rule to "3389". You have no seen any error message?????

https://s18.postimg.org/8ax91dvg9/sshot-1.png
you can uncheck this rule in and enable this rule individual (only for svchost.exe)

**Comment by pwn0r** [comment]
aha, now I can see what was the problem. yeah, RDP now fixed (global custom rule on 3389 -- with unchecked svchosts.

And that is correct -- no error message. In fact I was able to put any junk into that field like abcde etc and it allows that. No error message. I guess the best way would be to highlight the field on-the-fly when entering or modifying a rule if it fails data validation.

**Comment by henrypp** [comment]
> And that is correct -- no error message.

no, it's not correct. if rule isn't processed, you've got this error message. maybe errorlog disabled in config?

> [‎xx:xx:xx] ParseNetworkString() failed with error code 0x00000057 (Rule 3389) [2.0]

**Comment by pwn0r** [comment]
I see now. Error notifications were disabled but it was saving to file.  Again, all these mostly due to UI. 

Suggestions:
1. Immediate validation for the rule inside same window. That is before clicking Apply. 
2. If rule fails validation, it should not be checked a priori. 
3. It is better to show errors in the UI itself, as notifications are often ignored anyway. 

In this case if error notifications are not shown the rule can still be checked as if it was legit.

**Comment by pwn0r** [comment]
@henrypp : I noticed you put RDP as a system rule in the file update. Just a correction here: RDP is more advanced than during winXP/win7 times so now it uses either UDP or TCP, and UDP is a priority (for fast connections).  More specifically from RDP v8.0 UDP is supported and prioritized (if you install updated client/server on Win7 you can also use UDP connections).

**Comment by henrypp** [comment]
@pwn0r roger that!
