### ISSUE TITLE
Does the program not involve drivers?

### ISSUE THREAD

**Issue by muse117** [henrypp/simplewall#374]
Hi, henrypp:

Does this program not involve the driver layer?

**Comment by henrypp** [comment]
No, SW uses user-mode with WFP.

**Comment by muse117** [comment]
> No, SW uses user-mode WFP.

Are you considering joining driver development, Such as, ndis lwf and WFP kernel-mode

**Comment by henrypp** [comment]
Yes, i am interested in driver development, buut at this time SW not required that, anyway it's already done by WFP frontend called https://github.com/basil00/Divert so if i need WFP driver - i used this library!

**Comment by muse117** [comment]
> Yes, i am interested in driver development, but at this time SW does not required that.
> 
> Anyway it's already done by WFP frontend called https://github.com/basil00/Divert so if i need WFP driver - i used this library!

Great! I also hope to increase NDIS LWF driver.
