### ISSUE TITLE
undeclared identifier errors after code refactoring commit

### ISSUE THREAD

**Issue by sugarZ** [henrypp/simplewall#376]
compile error on commit 2c4e9580780f334fa1368d95f825a69169f1bb55 [2c4e958]
error C2065: "IDC_APPS_PROFILE": 
error C2065: "IDC_APPS_SERVICE": 
error C2065: "IDC_APPS_PACKAGE": 
error C2065: "IDC_RULES_BLOCKLIST"
error C2065: "IDC_RULES_SYSTEM": 
error C2065: "IDC_RULES_CUSTOM": 
error C2065: "IDC_APPS_PROFILE":

**Comment by muse117** [comment]
I have the same problem.
