### ISSUE TITLE
Anyone used "Blacklist mode"?

### ISSUE THREAD

**Issue by henrypp** [henrypp/simplewall#377]
I think to completely remove this feature and implement profiles!

**Comment by beerisgood** [comment]
I use whitelist mode. Otherwise this tool would be useless so I agree with your idea to remove blacklist mode

**Comment by SimpleUs** [comment]
Полностью согласен.

**Comment by perdolka** [comment]
+

**Comment by KruegerDead** [comment]
>Blacklist mode
Первый раз слышу

**Comment by AzimsTech** [comment]
Make a strawpoll.

**Comment by henrypp** [comment]
@AzimsTech where?
