### ISSUE TITLE
[Feature Request] Exception for Folder/Path

### ISSUE THREAD

**Issue by nkay08** [henrypp/simplewall#379]
I don't know if it is possible, since Windows Firewall doesn't support this.
But it would be nice if there was an option to have a list of folders where each application on these folders is allowed/blocked.
Maybe check if an application is run within these paths and instead of showing the notification, a new rule to allow/block this application is added.

Some applications like League of Legends change the location of the executable every patch, which is slightly annoying.

Thanks.

**Comment by henrypp** [comment]
#307 
https://github.com/henrypp/simplewall/issues/136#issuecomment-389056619
