### ISSUE TITLE
Install-Info not updated when new version is installed

### ISSUE THREAD

**Issue by nji9nji9** [henrypp/simplewall#382]
Have the newest, but in program install list it still says 2.3.13 etc.

**Comment by henrypp** [comment]
Maybe because you are not used installer, but portable, thats why.

**Comment by nji9nji9** [comment]
As far as I remember, it was updated by SimpleWall's update mechanism ...

**Comment by henrypp** [comment]
No, installer only

**Comment by nji9nji9** [comment]
My proposal:
Reopen this issue, mark as bug.
Program install list should be updated by all means.
