### ISSUE TITLE
Connections blocked while using ExpressVPN

### ISSUE THREAD

**Issue by ugahm** [henrypp/simplewall#383]
Since March update many of my applications are blocked while connected to expressvpn on Windows 7. I can not connect to the gateway of my router while VPN is connected 

Some examples in the dropped packet log: 

Blocks access to gateway for router portal: 
"‎4/‎12/‎2019 ‏‎7:34:16 PM","xxxxxxxxxxxx","xxxxxxxxxxxxxxxxxxxxxxxxx\chrome.exe",192.168.1.1:443 (Remote),192.168.xxx.xxx:7398 (Local),TCP,"Provider\ExpressVPN WFP Tool - block all ipv4 outbound filter",#3802321,IN,BLOCK 

Blocks Logitech keyboard  
"‎4/‎12/‎2019 ‏‎7:45:45 PM",xxxxxxxxxxxxxxxxxxxxxxxx","xxxxxxxxxxx\logitech gaming software\lcore.exe",192.168.xxx.xxx (Remote),192.168.xxx.xxx:54915 (Local),UDP,"Provider\ExpressVPN WFP Tool - block all ipv4 outbound filter",#3804713,OUT,BLOCK

**Comment by ltGuillaume** [comment]
That is what ExpressVPN itself blocks. Just like Windscribe, it adds a new sublayer to the Windows Filtering Platform (which is what simplewall does, too). It **should** block other gateways, such as your router's, otherwise you'll get leaks outside the VPN tunnel.
