### ISSUE TITLE
Automatic certificate install fails

### ISSUE THREAD

**Issue by nji9nji9** [henrypp/simplewall#384]
Since April 8th I get many entries in windows'
application event list (every 10 minutes).

It says it couldn't update certificates.

Source: Windows CAPI2
from: http://ctldl.windowsupdate.com/msdownload/update/v3/static/trustedr/en/590D2D7D884F402E617EA562321765CF17D894E9.crt 
   12029 (0x2efd) 

(All terms translated be me from German).

I suspect it's because of simplewall?
What should, what can be done?

**Comment by henrypp** [comment]
3.0.1 can allow Microsoft update servers in-built!
