### ISSUE TITLE
[Feature request] Automatic rules backup

### ISSUE THREAD

**Issue by indig0F10w** [henrypp/simplewall#388]
Please add automatic rules backup interval into options. My PC sometimes doesn't wake up from sleep as it should and the result is Windows crash. I loose all rules in Simplewall as the secondary effect, every time.

Doesn't need to be anything fancy.

Thank you.

**Comment by perdolka** [comment]
I agree. Currently I'm using **GameSave Manager** :)

**Comment by perdolka** [comment]
@henrypp Я правильно понимаю, что файлы apps.xml.bak, rules_config.xml.bak, rules_custom.xml.bak являются автоматическим бекапом и этот реквест исполняют?

**Comment by henrypp** [comment]
Auto-Backup already implemented. I understand the question is in new option, to change period and something like this.
