### ISSUE TITLE
Rule

### ISSUE THREAD

**Issue by Afinys** [henrypp/simplewall#389]
Hello everyone, Help me, After installing Simplewall, Firefox is connected to the Internet without any rules, by default, and I don't find its rules anywhere. how can I block it? Thank. And what other programs by default without rules are connected to the Internet?

**Comment by beerisgood** [comment]
Did you maybe use the blacklist mode instead of whitelist mode?

**Comment by Afinys** [comment]
No, I have the white list mode, and I have never even turned on the black list ..

**Comment by henrypp** [comment]
It's all depends on how you configure SW. I dont know this, like as you.
On log you can see all of this information.

**Comment by Afinys** [comment]
I figured it was the fault of Sophos, as soon as I deleted it, everything began to work fine ..
