### ISSUE TITLE
simplewall randomly (?) loses all rules

### ISSUE THREAD

**Issue by xnoreq** [henrypp/simplewall#391]
Hey,

running version 2.4.6 64-bit on Windows 10.
Today, I again lost all rules after resuming the PC up from sleep/standby. This is the second time.

Is there any reason why simplewall would throw away all filters?

(I just found #387 which mentions a similar issue.)

**Comment by 0lm** [comment]
i can confirm this. it literally never happened to me. but just a few minuted ago i restarted my computer and lost all my whitelist rules for the first time.

**Comment by Tom4tot** [comment]
I think the same happened to me but it could be related to #388 as I've been facing BSOD lately. So I can't confirm it but it did happen to me a few times since last update (2.4.6)

**Comment by perdolka** [comment]
> (I just found #387 which mentions a similar issue.)

https://github.com/henrypp/simplewall/issues/168
https://github.com/henrypp/simplewall/issues/387
https://github.com/henrypp/simplewall/issues/388
https://github.com/henrypp/simplewall/issues/378#issuecomment-481291932

**Comment by no-1d** [comment]
Same issue, lost all my rules 2 times already, no BSODs, log file indicated nothing. 2.4.5 and 2.4.6 might be affected.

**Comment by henrypp** [comment]
3.0 are fixed this.

**Comment by Tom4tot** [comment]
I can confirm I haven't encountered any issue since 3.0 beta.

**Comment by a1346054** [comment]
> 
> 
> 3.0 are fixed this.

3.0 is in a pre-release stage, is there a workaround for the latest stable v.2.4.6 release?

**Comment by henrypp** [comment]
@a1346054 hello,

sorry, but no, i cannot maintenance old versions, it's hard for one man!

**Comment by meadows19** [comment]
Not fixed in 3.0.1 
Same thing happened to me

**Comment by henrypp** [comment]
@meadows19 Any proof?

Same for [this](https://github.com/henrypp/simplewall/issues/110#issuecomment-1038707303).

**Comment by meadows19** [comment]
That's a strange question.
What proof do you need?
This issue has been reported multiple times by multiple people.
In my case, it was not preceded by a BSOD or a crash. 
Simple reboot, and it turns out that all filters (over a years worth) have been deleted without a trace.

**Comment by henrypp** [comment]
@meadows19,

That's a strange answer.

> This issue has been reported multiple times by multiple people.
Yes, this issue has been reported multiple times - last reported at **September 2019**.

> What proof do you need?
> In my case, it was not preceded by a BSOD or a crash.
> Simple reboot, and it turns out that all filters (over a years worth) have been deleted without a trace.

I am not a telepath to know your computer and program configuration, so prove it.

**Comment by henrypp** [comment]
@@meadows19,

> Not fixed in 3.0.1

Oh shi~, i did not noticed that you are using beta version released 3 years ago, lol.

Good luck with that!
