### ISSUE TITLE
Checksum calculation for the apps

### ISSUE THREAD

**Issue by baMain** [henrypp/simplewall#394]
Hi,
From what i see in the code of Simplewall there is no mechanism that check that the app binary's haven't been replaced,
this can be used to hijack the rules that are relevant for this app.

*a solution for this might cause a performance issue and might also be annoying(because of application updates)

**Comment by pwn0r** [comment]
That would be wonderful but requires imo much more work. Effectively simplewall has to compute hashes (SHA256 for instance) and compare running processes against that hash.

However there's one more problem, and that is windows itself. Old good DLL hijacking has been used to circumvent firewalls for centuries :)

And not just windows built-in firewall, some paid firewalls as well. The easiest way around is to use IE to send/get data. That is why normally you need to keep IE blocked on simplewall. It is not too difficult for a program running as admin/system privileges to inject a DLL into a target process space and run arbitrary code in that process context. And that would be rather hard for simplewall to detect.
