### ISSUE TITLE
Startup issue Windows 10

### ISSUE THREAD

**Issue by Username-is-not-already-taken** [henrypp/simplewall#400]
Enabled load on startup, boottime filters - no effect.
Added shortcut to "startup" and "common startup" folder - no effect.
Added registry sting (HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Run) - no effect.
After reboot i see the app in Task Manager "Strartup" tab, but in reality no running processes from app in "Processes" tab.
Official Win10 x64 ENG 1809 LTSC. 
Any idea how to fix it? Thanks!

**Comment by beerisgood** [comment]
Why you don't use the internal feature for enable at startup?
Works for me without problems

**Comment by Username-is-not-already-taken** [comment]
Solved. It works fine on real "Administrator" account (that one profile that hidden by default). On "user-administrator" - no chance.

**Comment by beerisgood** [comment]
You shouldn't use the *real* Admin account! Security issue.

I also use the *normal* Admin account with UAC on hightest level and SimpleWall works as intented

**Comment by Username-is-not-already-taken** [comment]
What build of Win10 you use? Maybe you have some non-obvious suggestions? I tried multiple times from default "user-admin", that one that created during Win install, and it works when launched manually, but won't load automatically on system startup (installed as admin, run as admin, always run as admin in .exe properties, etc).
As i'm the only user of PC, i see no use of UAC, working firewall is more important.

**Comment by beerisgood** [comment]
I use Windows 10 (Pro) 1809 64Bit

Maybe your problem is not using UAC. As I said I run it at highest level - which is btw recommend!
And that works without any problems.
Just use the internal option in simplewall

**Comment by Username-is-not-already-taken** [comment]
Performed clean install 3rd time, and now it works from normal admin account. 
Not 100% sure, but i suspect conflict with "O&O ShutUp10" security tool. That time i installed Simplewall first, activated internal start-up function, rebooted, and only after it successfully launched automatically after reboot, applied O&O settings.

**Comment by beerisgood** [comment]
That's the reason why you shouldn't use such tools.
Make the settings by yourself.

Also please close this isse, it's invalid
