### ISSUE TITLE
Settings-Rules-Advanced have not hover tip

### ISSUE THREAD

**Issue by fredgolightly** [henrypp/simplewall#407]
I'd like to know what the Settings-Rules-Advanced options do, but none of them have hover tips explaining like all other options do.

**Comment by henrypp** [comment]
I think it''s obvious:

- Resolve network address - resolving ip addresses as host
- Check apps for digital signatures - checking apps digital signatures
- Refreshing filters on device connection... refreshing filters on device ariival!

I think now you know what is this!

**Comment by ltGuillaume** [comment]
That last one is not exactly clear imho. Does this mean that the rules are refreshed when you plug in a removable storage device?

**Comment by henrypp** [comment]
It means SW will do apply filters on new mounted devices, if app placed in removable media, when it comes SW create required filters.

It related:
#128 
#291 
#329

**Comment by ltGuillaume** [comment]
Ok, thx. Just to be sure.
