### ISSUE TITLE
Better Windows 'Security Center' integration 

### ISSUE THREAD

**Issue by CHEF-KOCH** [henrypp/simplewall#41]
When using the filters and you get the offer to disable windows own firewall, windows own security center bothers you with the popup that there is no firewall activated. There should be an something implemented similar like in 3th party firewalls to integrate/detect SimpleWall and allow to choose it in the security center to 'trust' this firewall. 

[Windows Security Center API sample](https://code.msdn.microsoft.com/windowsdesktop/Windows-Security-Center-e4bcb429). Maybe via `WscGetSecurityProviderHealth`. Dunno, never touched security center myself.

**Comment by henrypp** [comment]
No. https://stackoverflow.com/questions/3698285/how-can-i-tell-the-windows-security-center-that-im-an-antivirus/3698375#3698375

**Comment by CHEF-KOCH** [comment]
That is only for antivirus not for firewall, as mentioned MS provide examples already free to use.

**Comment by henrypp** [comment]
No. This is example only for QUERY information, not to set.

**Comment by CHEF-KOCH** [comment]
Maybe before you Google without having a clue, even only need to query because we using the windows firewall on top of it which means we not registry s new product. 

Just say you're lazy and I would accept this instead of finding excuses.

**Comment by henrypp** [comment]
Okay, i try to explain to you, because you so lazy to open msdn:

- To install security center provider and tell him "am a firewall/antivirus" you...

> "Must be a member of the Microsoft Virus Initiative." or "Must be a member of AVPD or a member of EICAR or must sign and adhere to a code of ethics relating to malware research and malware handling."

- You cannot work with WF and simplewall together, thats why you need to power it off.

**Comment by CHEF-KOCH** [comment]
For ignorant like you we are working with wfp which is already registered - you get it? No need to register anything, besides this it would be free. 

Simple detection of if wfp disable hide warning is too much to ask it seems...

**Comment by henrypp** [comment]
WFP (Windows Filtering Platform) and (WF) Windows Firewall are different things, man.

**Comment by CHEF-KOCH** [comment]
Wfp provides the API interface which is nessary. 

You really should give up coding you proofed yourself you have no clue, quoting and copy code from stackoberflow never ends up good.

**Comment by henrypp** [comment]
> Wfp provides the API interface which is nessary.

WFP API or Security Center? Define at last. If WFC better use it, and do not push shit in my ears.
