### ISSUE TITLE
siplewall do not work with psiphon !!!

### ISSUE THREAD

**Issue by yoeltyke** [henrypp/simplewall#413]
i have use psiphon (https://psiphon.ca) . (ssh proxy)
when i connect to psiphon your app block list (block firefox or edge or chrome)  do not work and all data send and recive on my browsers
and i can load all site on firefox or chrome or edge

**Comment by xnoreq** [comment]
Do you use "VPN mode"?

**Comment by shiftyshady** [comment]
Do latest psiphon versions have "VPN mode"? or in other words, is it possible to prevent psiphon from routing all traffic?

**Comment by xevapu** [comment]
psiphon (windows version) routing all traffic ssh and ssh+ tunnel by default
when i connect to psiphon simplewall couldn't block **browsers traffic** and all data on browser bypass simplewall
