### ISSUE TITLE
Please show to which service/packet a process in the notification window belongs

### ISSUE THREAD

**Issue by DavidXanatos** [henrypp/simplewall#415]
Please show to which service/packet a process in the notification window belongs
this is especially needed for svchost.exe
As it is now I can not really use SW to discriminate between services and find out which once are trying to do what.

I want to block svc hosts most communication to MSFT but not break window supdate

**Comment by ltGuillaume** [comment]
+1

**Comment by pwn0r** [comment]
yes, that would be very good for troubleshooting etc. 

And same thing for Network Connections (beta). It only shows svchosts pools, not actual services there.

**Comment by kekukui** [comment]
**Very important feature** 👍🏼👍🏼👍🏼

Working example:

![Untitled](https://user-images.githubusercontent.com/20834957/91041957-f1c5e480-e5de-11ea-9f3c-c9d395ff725f.png)
_________________
![Untitled2](https://user-images.githubusercontent.com/20834957/91042267-7b75b200-e5df-11ea-87ef-91ff2250718e.png)
________________
https://github.com/processhacker/processhacker/

**Comment by fusionneur** [comment]
or at least PID..

**Comment by SimonEast** [comment]
Yes, I'd also like to know why this is invalid. 

I frequently encounter services asking for internet access and am unable to identify exactly which service it is, and end up temporarily allowing `svchost.exe` which is also likely to allow all sorts of telemetry through. Is there a way around this UX issue?

**Comment by henrypp** [comment]
@Uj947nXmRqV2nRaWshKtHzTvckUUpD & @SimonEast because M$ did not provide this information.
