### ISSUE TITLE
Weather (Windows store app) лезет в интернет

### ISSUE THREAD

**Issue by perdolka** [henrypp/simplewall#419]
Этого приложения нет в белом списке simplewall, но оно успешно выходит в интернет:
![зображення](https://user-images.githubusercontent.com/24720263/57378200-e150e700-71ac-11e9-86a7-8d479472f017.png)
Как?
Даже напротив, процесс в чёрном списке (а Windows Firewall отключён):
![зображення](https://user-images.githubusercontent.com/24720263/57377993-73a4bb00-71ac-11e9-8c5d-31ce2537a3a9.png)

Предполагаю, что он может вылазить через svchost.exe (он в белом списке):
![зображення](https://user-images.githubusercontent.com/24720263/57378289-178e6680-71ad-11e9-87f8-d62ae0106499.png)
Но так ли это?
Раньше процесс приложения "Погода" лез в интернет "самостоятельно".

**Comment by henrypp** [comment]
1) Ничего сказать не смогу не зная что вы там набедокурили в правила.
2) В логе сбросов есть возможность посмотреть все записи (пропущенные и сброшенные), он должен помочь.

**Comment by perdolka** [comment]
Правила вообще не менял никакие.
Я **только** добавляю нужные приложения в белый список.

В лог сбросов почему-то попадает всё, кроме непосредственно Microsoft.Msn.Weather.exe
Хотя на вкладке "Соединения (Beta)", как видите, Microsoft.Msn.Weather.exe есть.
Но иногда (когда я делаю что-либо в приложении "Погода", чтобы оно попало в лог) попадается svchost.exe, что, возможно, подтверждает мою догадку:

"‎10.‎05.‎2019 ‏‎12:57:43","User-PC\User","C:\windows\system32\svchost.exe",52.114.75.79:443 (Remote),192.168.1.101:54394 (Local),TCP,"simplewall\spy_52.114.75.79",#830439,OUT,BLOCK

**Comment by henrypp** [comment]
Тогда смотри какое правило пропускает в логе.

https://github.com/henrypp/simplewall/issues/79#issuecomment-491228398

**Comment by henrypp** [comment]
Разрешать svchost.exe это очень глупо, имхо

**Comment by perdolka** [comment]
Вот результат:
```
"‎10.‎05.‎2019 ‏‎16:15:25","XXXX-PC\XXXX","C:\program files\windowsapps\microsoft.bingweather_4.28.10351.0_x64__8wekyb3d8bbwe\microsoft.msn.weather.exe",<empty> (Remote),<empty> (Local),TCP,"<empty>",#0,OUT,ALLOW
"‎10.‎05.‎2019 ‏‎16:15:25","XXXX-PC\XXXX","C:\program files\windowsapps\microsoft.bingweather_4.28.10351.0_x64__8wekyb3d8bbwe\microsoft.msn.weather.exe",152.195.39.165:443 (Remote),192.168.1.101:54988 (Local),TCP,"simplewall\MSN Weather",#833411,OUT,ALLOW
"‎10.‎05.‎2019 ‏‎16:15:25","XXXX-PC\XXXX","C:\program files\windowsapps\microsoft.bingweather_4.28.10351.0_x64__8wekyb3d8bbwe\microsoft.msn.weather.exe",<empty> (Remote),<empty> (Local),TCP,"<empty>",#0,OUT,ALLOW
"‎10.‎05.‎2019 ‏‎16:15:25","XXXX-PC\XXXX","C:\program files\windowsapps\microsoft.bingweather_4.28.10351.0_x64__8wekyb3d8bbwe\microsoft.msn.weather.exe",<empty> (Remote),<empty> (Local),TCP,"<empty>",#0,OUT,ALLOW
"‎10.‎05.‎2019 ‏‎16:15:25","XXXX-PC\XXXX","C:\program files\windowsapps\microsoft.bingweather_4.28.10351.0_x64__8wekyb3d8bbwe\microsoft.msn.weather.exe",<empty> (Remote),<empty> (Local),TCP,"<empty>",#0,OUT,ALLOW
"‎10.‎05.‎2019 ‏‎16:15:25","XXXX-PC\XXXX","C:\program files\windowsapps\microsoft.bingweather_4.28.10351.0_x64__8wekyb3d8bbwe\microsoft.msn.weather.exe",178.250.2.151:443 (Remote),192.168.1.101:54989 (Local),TCP,"simplewall\MSN Weather",#833411,OUT,ALLOW
"‎10.‎05.‎2019 ‏‎16:15:25","XXXX-PC\XXXX","C:\program files\windowsapps\microsoft.bingweather_4.28.10351.0_x64__8wekyb3d8bbwe\microsoft.msn.weather.exe",213.155.156.185:443 (Remote),192.168.1.101:54991 (Local),TCP,"simplewall\MSN Weather",#833411,OUT,ALLOW
"‎10.‎05.‎2019 ‏‎16:15:25","XXXX-PC\XXXX","C:\program files\windowsapps\microsoft.bingweather_4.28.10351.0_x64__8wekyb3d8bbwe\microsoft.msn.weather.exe",202.131.200.84:443 (Remote),192.168.1.101:54990 (Local),TCP,"simplewall\MSN Weather",#833411,OUT,ALLOW
"‎10.‎05.‎2019 ‏‎16:15:25","XXXX-PC\XXXX","C:\program files\windowsapps\microsoft.bingweather_4.28.10351.0_x64__8wekyb3d8bbwe\microsoft.msn.weather.exe",<empty> (Remote),<empty> (Local),TCP,"<empty>",#0,OUT,ALLOW
"‎10.‎05.‎2019 ‏‎16:15:25","XXXX-PC\XXXX","C:\program files\windowsapps\microsoft.bingweather_4.28.10351.0_x64__8wekyb3d8bbwe\microsoft.msn.weather.exe",18.153.11.10:443 (Remote),192.168.1.101:54992 (Local),TCP,"simplewall\MSN Weather",#833411,OUT,ALLOW
"‎10.‎05.‎2019 ‏‎16:15:25","XXXX-PC\XXXX","C:\program files\windowsapps\microsoft.bingweather_4.28.10351.0_x64__8wekyb3d8bbwe\microsoft.msn.weather.exe",<empty> (Remote),<empty> (Local),TCP,"<empty>",#0,OUT,ALLOW
"‎10.‎05.‎2019 ‏‎16:15:25","XXXX-PC\XXXX","C:\program files\windowsapps\microsoft.bingweather_4.28.10351.0_x64__8wekyb3d8bbwe\microsoft.msn.weather.exe",<empty> (Remote),<empty> (Local),TCP,"<empty>",#0,OUT,ALLOW
"‎10.‎05.‎2019 ‏‎16:15:25","XXXX-PC\XXXX","C:\program files\windowsapps\microsoft.bingweather_4.28.10351.0_x64__8wekyb3d8bbwe\microsoft.msn.weather.exe",185.33.223.202:443 (Remote),192.168.1.101:54993 (Local),TCP,"simplewall\MSN Weather",#833411,OUT,ALLOW
"‎10.‎05.‎2019 ‏‎16:15:25","XXXX-PC\XXXX","C:\program files\windowsapps\microsoft.bingweather_4.28.10351.0_x64__8wekyb3d8bbwe\microsoft.msn.weather.exe",2.23.109.238:443 (Remote),192.168.1.101:54994 (Local),TCP,"simplewall\MSN Weather",#833411,OUT,ALLOW


```
Но Microsoft.Msn.Weather.exe в чёрном списке (скрин в оп-посте).

svchost.exe я тоже отправил в ЧС, но не помогло.
Изначально я разрешал ему доступ потому что иначе Дефендер не получает обновления: #359

Виндовс фаервол отключён.

**Comment by henrypp** [comment]
А в чём проблема то тогда если у теб правило рарешающее стоит???

`"simplewall\MSN Weather",#833411`

**Comment by perdolka** [comment]
> MSN weather это UWP приложение, которое во вкладке пакеты находится, а не в общем списке

В этом и была проблема. :/
Извини что морочил голову, просто сбило с толку то, что Microsoft.Msn.Weather.exe в общем списке был в ЧС, но лез в инет.
Во вкладку "пакеты" я не догадался заглянуть, потому что, если не ошибаюсь, до версии 3.0 все UWP приложения были в общем списке.
Получается, приложение "Погода" как бы "раздвоилось" между вкладками - в общем списке как исполняемый файл и как UWP в пакетах. Это немного сбивает с толку.
