### ISSUE TITLE
Patched UXtheme breaks SimpleWall GUI

### ISSUE THREAD

**Issue by CHEF-KOCH** [henrypp/simplewall#42]
* [SimpleWall v2.0.2b](https://github.com/henrypp/simplewall/releases/tag/v.2.0.2b)
* Windows 10 (1607) v14393.1537
* [UxThemepatcher](https://www.syssel.net/hoefs/software_uxtheme.php?lang=en)
* [ADAPTA theme](http://niivu.deviantart.com/art/Adapta-675581778)
* [Example](https://ibb.co/j5pEPv)

Steps to reproduce:
* Install above mentioned OS/software
* Install SimpleWall enable all filters
* Restart

Breaks the SimpleWall GUI from rendering correctly. A workaround is to kill simplewall and restart it.

**Comment by henrypp** [comment]
All works.
