### ISSUE TITLE
window sizing with ahk doesn't stick

### ISSUE THREAD

**Issue by stffdtiger** [henrypp/simplewall#421]
this is not a big deal, as it's not a security issue, just thought i'd bring it up because it does bother me a little.

i use AutoHotkey to resize my windows to specific dimensions. now, there seems to be a Windows issue that makes it so that i must maximize then restore a window after resizing it this way in order for the new size to be retained. although, even after doing this to the simplewall window, the new size doesn't stick. if i resize the window with AHK then maximize/restore, the new size will stay until i close the program and re-open it. after relaunching, the simplewall window will be set to the dimensions used before the AHK resize. resizing normally by dragging the window edge seems to be the only way to get a new size to persist.

i don't know if this is fixed in the 3.0 beta, as i am using 2.4.6.

**Comment by henrypp** [comment]
```cpp
SetWindowPos (hwnd, nullptr, 0, 0, width, height, SWP_NOMOVE | SWP_NOACTIVATE | SWP_NOZORDER | SWP_NOOWNERZORDER);
```

This code are working as well!

**Comment by henrypp** [comment]
Проблема скорей всего в UIPI, гугли **ChangeWindowMessageFilterEx**

**Comment by stffdtiger** [comment]
did you actually try what i was talking about?

**Comment by henrypp** [comment]
im not using ahk nor autoit
