### ISSUE TITLE
Network Beta -- connections missing from the list?

### ISSUE THREAD

**Issue by pwn0r** [henrypp/simplewall#423]
Not sure if it is [UI] issue or something else here.

funny enough I don't see one particular connection in the list, actually four of them. 

They are displayed thru **netstat -a-b** though. 

Since I have local IPv6 enabled as well, I should be seeing four listening connections on 3389, i.e. 

>   TCP    0.0.0.0:3389           df:0                   LISTENING
>   TermService
>  [svchost.exe]

two UDP, two TCP, two IPv4, two IPv6 all for 3389. Yet I dont see any of them in network beta. Windows 10 1607.

**Comment by henrypp** [comment]
same with 3.0.2?
