### ISSUE TITLE
Ability to rename executables via right click -> rename

### ISSUE THREAD

**Issue by CHEF-KOCH** [henrypp/simplewall#43]

**Comment by henrypp** [comment]
No. This is not file manager. However, double click opens file directory.

**Comment by CHEF-KOCH** [comment]
It would avoid confusion and clicks, because when you work with executables which have the same name it will list as the same name within SimpleWall GUI. This doesn't have anything to do with been a file manager, it's to clarify which .exe it really is. 

For example:
```
C:\Program Files\Git\bin\git.exe
C:\Program Files\Git\cmd\git.exe
C:\Program Files\Git\mingw64\bin\git.exe
C:\Program Files\Git\mingw64\libexec\git-core\git.exe
```

So you have 4 git.exe by default listed as git.exe.

**Comment by henrypp** [comment]
GUI have abbility to show fullpath of application. (View->Show filenames only (uncheck))

**Comment by CHEF-KOCH** [comment]
Still makes less sense if it shows 3 times git.exe or program files... I give up too much ignorance.

**Comment by henrypp** [comment]
No, this is not ignorance, this is my point of view.
