### ISSUE TITLE
Questions about the rules

### ISSUE THREAD

**Issue by perdolka** [henrypp/simplewall#430]
1
When I create (or apply) a rule for the selected application,
this rule works **only** within the Protocol selected,
without limiting the traffic of other protocols?
**Or** all application traffic is limited by the Protocol selected in the rule?

2
I need to just limit the outgoing connection to host/port, 
for example only www.microsoft.com:443 - I put it in the "Remote" field,
so, can I leave empty the field "Local"? 
Or do I need to enter there, for example, 192.168.1.1 ?

___

1
Когда я создаю (или применяю) правило для выбранного приложения,
это правило работает **только** в пределах выбранного в нём протокола, 
не ограничивая трафик  других протоколов?
**Или же** весь трафик приложения ограничивается только протоколом, выбранным в правиле?

2
Если мне нужно просто ограничить исходящее соединение хостом/портом, например только www.microsoft.com:443 - я вписываю это в поле "Remote", 
а поле "Local" могу оставить пустым или вписать туда, например, 192.168.1.1 ?

**Comment by ltGuillaume** [comment]
1. All traffic should be blocked, except for the address, port and/or protocol in the rule you created. Be sure that the application you want to limit is NOT checked in the list of apps, because that would allow _all_ traffic for that application, no matter what extra _Allow_ rule you create.

2. You don't have to specify anything in the "Local" field.

**Comment by perdolka** [comment]
> Be sure that the application you want to limit is NOT checked in the list of apps

So, this application can be listed in "Disabled apps" list or just unlisted, before add the rule?

**Comment by ltGuillaume** [comment]
It should be listed under "Apps with special rules" if you have selected `View -> Group apps with special rules`, otherwise it should be under "Disabled apps".

**Comment by perdolka** [comment]
Sorry, I'm not sure I understand how it works.
Example:

Rules for **svchost.exe**
![зображення](https://user-images.githubusercontent.com/24720263/57935829-603fd100-78cb-11e9-857f-9cf40546d506.png)
![зображення](https://user-images.githubusercontent.com/24720263/57936008-aeed6b00-78cb-11e9-98ff-c0efdce545ea.png)

TCP rule is off
UDP rule is on
SW Log after Update request forcing:

```
"‎17.‎05.‎2019 ‏‎17:37:49","XXXX-PC\XXXX","C:\windows\system32\svchost.exe",<empty> (Remote),<empty> (Local),TCP,"<empty>",#0,OUT,ALLOW
"‎17.‎05.‎2019 ‏‎17:37:49","XXXX-PC\XXXX","C:\windows\system32\svchost.exe",51.143.109.194:443 (Remote),192.168.1.101:63471 (Local),TCP,"simplewall\svchost.exe",#866781,OUT,ALLOW
"‎17.‎05.‎2019 ‏‎17:37:51","XXXX-PC\XXXX","C:\windows\system32\svchost.exe",<empty> (Remote),<empty> (Local),TCP,"<empty>",#0,OUT,ALLOW
"‎17.‎05.‎2019 ‏‎17:37:51","XXXX-PC\XXXX","C:\windows\system32\svchost.exe",65.52.108.90:443 (Remote),192.168.1.101:63472 (Local),TCP,"simplewall\svchost.exe",#866781,OUT,ALLOW
```

TCP rule is on
UDP rule is off
SW Log after Update request forcing:
```
"‎17.‎05.‎2019 ‏‎17:38:55","NT AUTHORITY\NETWORK SERVICE","C:\windows\system32\svchost.exe",<empty> (Remote),<empty> (Local),UDP,"<empty>",#0,OUT,ALLOW
"‎17.‎05.‎2019 ‏‎17:38:55","NT AUTHORITY\NETWORK SERVICE","C:\windows\system32\svchost.exe",<empty> (Remote),<empty> (Local),UDP,"<empty>",#0,OUT,ALLOW
"‎17.‎05.‎2019 ‏‎17:38:55","NT AUTHORITY\NETWORK SERVICE","C:\windows\system32\svchost.exe",8.8.8.8:53 (Remote),192.168.1.101:65415 (Local),UDP,"simplewall\DNS",#866620,OUT,ALLOW
"‎17.‎05.‎2019 ‏‎17:38:55","XXXX-PC\XXXX","C:\windows\system32\svchost.exe",<empty> (Remote),<empty> (Local),TCP,"<empty>",#0,OUT,ALLOW
"‎17.‎05.‎2019 ‏‎17:38:55","XXXX-PC\XXXX","C:\windows\system32\svchost.exe",20.44.77.24:443 (Remote),192.168.1.101:63491 (Local),TCP,"simplewall\svchost.exe",#866781,OUT,ALLOW
"‎17.‎05.‎2019 ‏‎17:38:57","XXXX-PC\XXXX","C:\windows\system32\svchost.exe",<empty> (Remote),<empty> (Local),TCP,"<empty>",#0,OUT,ALLOW
"‎17.‎05.‎2019 ‏‎17:38:57","XXXX-PC\XXXX","C:\windows\system32\svchost.exe",65.52.108.90:443 (Remote),192.168.1.101:63492 (Local),TCP,"simplewall\svchost.exe",#866781,OUT,ALLOW
"‎17.‎05.‎2019 ‏‎17:38:58","NT AUTHORITY\LOCAL SERVICE","C:\windows\system32\svchost.exe",192.168.1.1:1025 (Remote),239.255.255.250:1900 (Local),UDP,"simplewall\SSDP [inbound]",#866688,IN,ALLOW
"‎17.‎05.‎2019 ‏‎17:38:58","NT AUTHORITY\LOCAL SERVICE","C:\windows\system32\svchost.exe",192.168.1.1:1025 (Remote),239.255.255.250:1900 (Local),UDP,"simplewall\SSDP [inbound]",#866688,IN,ALLOW
"‎17.‎05.‎2019 ‏‎17:38:58","NT AUTHORITY\LOCAL SERVICE","C:\windows\system32\svchost.exe",192.168.1.1:1025 (Remote),239.255.255.250:1900 (Local),UDP,"simplewall\SSDP [inbound]",#866688,IN,ALLOW
"‎17.‎05.‎2019 ‏‎17:38:58","NT AUTHORITY\LOCAL SERVICE","C:\windows\system32\svchost.exe",192.168.1.1:1025 (Remote),239.255.255.250:1900 (Local),UDP,"simplewall\SSDP [inbound]",#866688,IN,ALLOW
"‎17.‎05.‎2019 ‏‎17:38:58","NT AUTHORITY\LOCAL SERVICE","C:\windows\system32\svchost.exe",192.168.1.1:1025 (Remote),239.255.255.250:1900 (Local),UDP,"simplewall\SSDP [inbound]",#866688,IN,ALLOW
"‎17.‎05.‎2019 ‏‎17:38:58","NT AUTHORITY\NETWORK SERVICE","C:\windows\system32\svchost.exe",<empty> (Remote),<empty> (Local),UDP,"<empty>",#0,OUT,ALLOW
"‎17.‎05.‎2019 ‏‎17:38:58","NT AUTHORITY\NETWORK SERVICE","C:\windows\system32\svchost.exe",<empty> (Remote),<empty> (Local),UDP,"<empty>",#0,OUT,ALLOW
"‎17.‎05.‎2019 ‏‎17:38:58","NT AUTHORITY\NETWORK SERVICE","C:\windows\system32\svchost.exe",8.8.8.8:53 (Remote),192.168.1.101:57582 (Local),UDP,"simplewall\DNS",#866620,OUT,ALLOW
"‎17.‎05.‎2019 ‏‎17:38:58","NT AUTHORITY\LOCAL SERVICE","C:\windows\system32\svchost.exe",192.168.1.1:1025 (Remote),239.255.255.250:1900 (Local),UDP,"simplewall\SSDP [inbound]",#866688,IN,ALLOW
"‎17.‎05.‎2019 ‏‎17:38:58","NT AUTHORITY\LOCAL SERVICE","C:\windows\system32\svchost.exe",192.168.1.1:1025 (Remote),239.255.255.250:1900 (Local),UDP,"simplewall\SSDP [inbound]",#866688,IN,ALLOW
"‎17.‎05.‎2019 ‏‎17:38:58","NT AUTHORITY\NETWORK SERVICE","C:\windows\system32\svchost.exe",208.67.222.222:53 (Remote),192.168.1.101:57582 (Local),UDP,"simplewall\DNS",#866620,OUT,ALLOW
"‎17.‎05.‎2019 ‏‎17:38:58","NT AUTHORITY\LOCAL SERVICE","C:\windows\system32\svchost.exe",192.168.1.1:1025 (Remote),239.255.255.250:1900 (Local),UDP,"simplewall\SSDP [inbound]",#866688,IN,ALLOW
"‎17.‎05.‎2019 ‏‎17:38:58","NT AUTHORITY\LOCAL SERVICE","C:\windows\system32\svchost.exe",192.168.1.1:1025 (Remote),239.255.255.250:1900 (Local),UDP,"simplewall\SSDP [inbound]",#866688,IN,ALLOW
"‎17.‎05.‎2019 ‏‎17:38:58","NT AUTHORITY\LOCAL SERVICE","C:\windows\system32\svchost.exe",192.168.1.1:1025 (Remote),239.255.255.250:1900 (Local),UDP,"simplewall\SSDP [inbound]",#866688,IN,ALLOW
```

**Comment by ltGuillaume** [comment]
It's like you have a rule that allows all outgoing traffic. Are you sure you disabled Windows Firewall?

**Comment by perdolka** [comment]
`Are you sure you disabled Windows Firewall?`
Yes

**Comment by ltGuillaume** [comment]
That `#0` rule looks like it's not by simplewall. I'm hoping someone else can help you out here, I'm not sure what's going on then.

**Comment by perdolka** [comment]
@henrypp Есть какие-то идеи с чем это может быть связано?
Действительно ли правило #0 (которое в логах https://github.com/henrypp/simplewall/issues/430#issuecomment-493482644) не связанно с simplewall и может быть причиной почему у меня правила не ограничивают процесс svchost? 
У меня полностью отключен виндовый фаерволл. 
Кроме simplewall других установленых/активных фаерволов в системе нет.

**Comment by henrypp** [comment]
> That #0 rule looks like it's not set by simplewall. I'm hoping someone else can help you out here, I'm not sure what's going on then.

No, #0 rule ids it's WFP bug which passes NULL as filter id sometimes. It's SW, or not, i dont know.

**Comment by ltGuillaume** [comment]
Let's review `rules_custom.xml` then.

**Comment by perdolka** [comment]
1
Вчера ещё попробовал просто включить Виндовс Апдейт в системных правилах, (пользовательские правила отключил, svchost оправил в блэклист).
Логи SW смотрел после нажатия на кнопку "Проверить наличие обновлений" Дефендера. 
![зображення](https://user-images.githubusercontent.com/24720263/57982740-26e59d80-7a52-11e9-87aa-52f13c4bbea1.png)
Это тоже не помогло - часть TCP / UDP svchost проходит, часть блокируется, 
обновление Дефендера **не** приходило, пока я просто не отправил svchost в enabled apps.
Состояние системного правила "Виндовс Апдейт" на обновление Дефендера не влияло.

2
К тому же, пользовательские правила у меня "не очень", судя по статье https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1809-endpoints мне пришлось бы добавить в remote-список просто кучу всего для корректной работы. 
Но это в теории, на практике в любом случае есть какая-то проблема, из-за которой TCP / UDP "протекает".

<br>
@ltGuillaume
> Let's review rules_custom.xml then.

```
<?xml version="1.0"?>
<root timestamp="1558273049" type="1">
	<item name="Defender Update Allow UDP" rule="definitionupdates.microsoft.com:443" dir="2" protocol="17" apps="%SystemRoot%\system32\svchost.exe" />
	<item name="Defender Update Allow TCP" rule="definitionupdates.microsoft.com:443" dir="2" protocol="6" apps="%SystemRoot%\system32\svchost.exe" />
</root>
```

**Comment by perdolka** [comment]
Проблема была смехотворной - всего-то **НЕ** нужно ставить галочку в чекбокс:
![зображення](https://user-images.githubusercontent.com/24720263/58380501-9b708d00-7fba-11e9-8681-d6ebbecc5e0c.png) 
Что, как мне кажется, не очевидно (не интуитивно), 
хотя теперь я уже понимаю логику такого решения. 
Смешно в этой ситуации то, что @ltGuillaume в самом начале треда объяснил мне это:
> that the application you want to limit is NOT checked in the list of apps 
но я ошибочно принял это на счёт списка Enabled apps и невнимательно прочёл. 
Посыпаю голову пеплом. :man_facepalming:
