### ISSUE TITLE
Another firewall product also named "Simplewall"

### ISSUE THREAD

**Issue by cloudgreen** [henrypp/simplewall#432]
Maybe some of you already knew this, but I just found out there's _another_ firewall product also named "SimpleWall" (although with different capitalization), see below.

There might be risk for confusion?! :( At least I was fooled already, ending up there as I was searching for the Github version...

https://www.simplewallsoftware.com/

**Comment by ltGuillaume** [comment]
Time to rename to µWall (microWall) or something, then?

**Comment by Tom4tot** [comment]
It's been years it exists.

Unfortunately SimpleWall is not a very distinctive name for a firewall, so it's not very surprising.

µWall reminds me of µTorrent, which is not a good think I think...

It's up to Henry++ of course, but I don't think it's a huge issue.
