### ISSUE TITLE
Log maximum size

### ISSUE THREAD

**Issue by SamLino** [henrypp/simplewall#434]
Hello,

Could the log maximum size allow up to 1gb? keeping the default the same as is now.

**Comment by henrypp** [comment]
No, maybe incremental backups will be, but 1gb is too large for one text file, i think

**Comment by pwn0r** [comment]
the current default size is too small anyway. Since each line takes quite a lot of space, default size it not enough even for 500 lines or so. A computer in LAN with various spamming devices on network can get 500 lines in less than an hour.
