### ISSUE TITLE
change font in toolbar and show text

### ISSUE THREAD

**Issue by hesss5** [henrypp/simplewall#437]
hi
check screenshot text not showing fully in startup of sw
also please change font of that toolbar to match with other 
![sshot-2](https://user-images.githubusercontent.com/23487445/57937946-4e1a5e80-78dc-11e9-98f6-29ab99cb0575.png)

**Comment by hesss5** [comment]
font fixed
but above screenshot not.if it should like that no problem
resizing column in network tab then resize sw window, resized column will reset to default state

**Comment by henrypp** [comment]
Yes, button is half painted when it's grayed out, i dont know why, but on release i hope this will be fixed.
