### ISSUE TITLE
[2.4.6/3.0] Application silently crashes

### ISSUE THREAD

**Issue by rpav2004** [henrypp/simplewall#439]
I'm getting an issue on Windows 10 insider preview build 18898. The application attempts to launch but silently fails. Both current stable and beta (3.0) throw the same error upon launch.
`
Faulting application name: simplewall.exe, version: 2.4.6.0, time stamp: 0x5c9b9cf0 
Faulting module name: MrmCoreR.dll, version: 10.0.18898.1000, time stamp: 0x18c6c0c3 
Exception code: 0xc0000005 Fault offset: 0x000000000000e975 
Faulting process id: 0x352c Faulting application start time: 0x01d50e058293a45f 
Faulting application path: C:\Program Files\simplewall\simplewall.exe 
Faulting module path: C:\WINDOWS\SYSTEM32\MrmCoreR.dll 
Report Id: af67f8d1-1339-4c0c-b291-b617c95d00ab 
Faulting package full name: 
Faulting package-relative application ID:
`
and
`Faulting application name: simplewall.exe, version: 3.0.0.0, time stamp: 0x5cd139ea 
Faulting module name: MrmCoreR.dll, version: 10.0.18898.1000, time stamp: 0x18c6c0c3 
Exception code: 0xc0000005 Fault offset: 0x000000000000e975 Faulting process id: 0x37a0 
Faulting application start time: 0x01d50e07f2b004b4 
Faulting application path: C:\Program Files\simplewall\simplewall.exe 
Faulting module path: C:\WINDOWS\SYSTEM32\MrmCoreR.dll 
Report Id: fcd57190-820a-4cb2-96a7-f67a55f462a7 
Faulting package full name: 
Faulting package-relative application ID: `

**Comment by henrypp** [comment]
#375
