### ISSUE TITLE
blocklist

### ISSUE THREAD

**Issue by haze242** [henrypp/simplewall#441]
А зачем убрали возможность отключать отдельные правила блоклиста?
Теперь если что-то сломалось только отключать весь список...

Мне например нужно отключить 13.107.21.200 в extra, чтобы иметь возможность использовать сервисы Bing ( перевод в qtranslate и textractor, поиск по картинкам в браузерах ), а теперь я это могу сделать только отключив весь список extra ( пытался вручную создать правило, но видимо блоклист имеет более высокий приоритет ).

**Comment by ltGuillaume** [comment]
I agree, this is awful. I'm going back to v2 because of this...

What's even worse: I had all rules enabled, but after updating to v3.x only the telemetry rules were enabled. Without any notification, my settings were abruptly changed!

**Comment by henrypp** [comment]
>Without any notification, my settings were abruptly changed!
Previous rules are backed up.

**Comment by henrypp** [comment]
Ничего менять не буду.
#384 
#395 
#370 
#206 
#229 
#240 
#244 
#359 
#11

**Comment by haze242** [comment]
> Ничего менять не буду.

Как вариант, можно было бы запилить какой-нибудь "режим эксперта"... ( ну это если интересно )

А нет какого-нибудь способа вручную сделать исключение для одного айпишника?

**Comment by ltGuillaume** [comment]
Another solution would be to be able to allow certain IP's from the blocklists for specific apps via custom rules. This way, you could keep the new behavior, but wouldn't be an all-or-nothing solution anymore (which isn't a solution all imho). This also hooks into [this idea](https://github.com/henrypp/simplewall/issues/380).

**Comment by Matthaiks** [comment]
IMHO, simplewall should have an option to load self-provided WindowsSpyBlocker's blocklist.xml files.

**Comment by ltGuillaume** [comment]
@Matthaiks I disagree. The WindowsSpyBlocker lists change regularly, so providing your own list would create a false sense of blocking all traffic. If the implementation would allow for a blocklist rule to be temporarily disabled (so, with a timer), I think simplewall's implementation would be great.
