### ISSUE TITLE
Why does "Refresh" also reapply the filters?

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#442]
I just tried to refresh the current network connections in the Network (beta) tab. However, this apparently also reapplies all filters. Why is that? I feel this is very counterintuitive: refresh (F5) stands for reloading the screen information, i.e. the presented rules or network connections. Reapplying filters is something entirely different. As such, I opt for two separate functions:

1. Edit -> Reapply filters
2. View -> Refresh (F5)

**Comment by henrypp** [comment]
- Refresh is maded for this.
- Connections are updated automatically.

Any questions?

**Comment by ltGuillaume** [comment]
I read in the issues here that the Connections tab needed a manual refresh, I suppose that has been changed then.

In this case I would propose a rename of the feature to "Reapply filters", in order to actually describe what it does :)

**Comment by henrypp** [comment]
No, "Refresh" button will stay as is, and no additional, unnecessary, buttons will be.

**Comment by ltGuillaume** [comment]
I understand. I was only referring to the description, which caused confusion for me, so probably for others, too.

**Comment by henrypp** [comment]
Refresh is doing what is name got. Its loads information about apps and rules from profile and displays it.

**Comment by ltGuillaume** [comment]
So it does NOT reapply the filters? Because it says so when "refreshing". I'm sorry, I don't want to be annoying or anything, I just want to know exactly what's doing what (which is obviously critical when it comes to software one relies on for security).

**Comment by henrypp** [comment]
Yes it does, because of apps and rules reloading.
