### ISSUE TITLE
v 3.0.1 : Block by default Microsoft apps/updates [in-built fix]

### ISSUE THREAD

**Issue by dunocijim** [henrypp/simplewall#443]
v 3.0.1 you have block outlook.com and live.com address default on simplewall !!!

**Comment by xnoreq** [comment]
You don't have "Allow M$ Applications" checked in the settings.

File - Settings - Rules - Allow M$ Applications.

**Comment by henrypp** [comment]
Yes, by default this is blocked!

**Comment by fredgolightly** [comment]
Honestly, blocking MS update servers by default & hiding in settings & not showing in filters list and not mentioning it on SW app update is an awful move. I've just spend 2 days trying to find out what was causing this on 3 pcs all running sw and I finally found this. I'd urge you to by default allow ms update servers for users to get security updates else you're leaving people open to unpatched risks in windows.

**Comment by nji9nji9** [comment]
Being a newbie ... I would like to propose to make a distinction between update-services and M$ Applications.
If possible in SimpleWall.
All or nothing (and moreover quite hidden) is not so good.
SimpleWall is doing a quite responsible job ... that should always be considered.

**Comment by xnoreq** [comment]
>Being a newbie ... I would like to propose to make a distinction between update-services and M$ Applications.

Open your eyes. Seriously.

**Comment by nji9nji9** [comment]
First ... as said ... I'm no expert, but just use SimpleWall.
Second ... for that responsible task of firewalling I don't use betas,
and therefore interpreted fredgolightly's post in the way of my post.

You're so kind. Seriously.

**Comment by hesss5** [comment]
auto login of outlook blocked have to use "allow M$ update servers"
**login.live.com**
i think this log related to it
https://gist.github.com/hesss5/931a0a4cb5340dbdb09262c147d7e4b5
