### ISSUE TITLE
Cannot delete app in 3.0.1 beta

### ISSUE THREAD

**Issue by xnoreq** [henrypp/simplewall#444]
I'm trying to delete a system app svchost, but it doesn't do anything.

It prompts "Delete 1 item(s)?". I click Yes, nothing happens.

**Comment by GitCurious** [comment]
There are several items that can not be deleted

fdphost, fdrespub, ssdpsrv, svchost, system, termservice, upnphost.....

This is not a new thing with v3.x - they they were not removable with earlier versions either.

I think they are hardcoded in and can not be removed for some reason.
