### ISSUE TITLE
update: you should add this rule to simplewall system rule to windows update work correctly

### ISSUE THREAD

**Issue by bugefo** [henrypp/simplewall#446]
hi, when disable svchost.exe and system windows update do not work at all.
should i enable these rule? if i enable all svchost process access the internet?
what i do? i whouldn't all svchost process access the internet, i want windows update work correctly only

![Annotation 2019-05-23 091107](https://user-images.githubusercontent.com/50939595/58226545-563f2780-7d3c-11e9-9677-792b2e3c2624.png)

**Comment by bugefo** [comment]
i have creat new rule for **svchost TCP port 443** for windows update and windows update is enable without other svchost process go online :)
you should add this rule to **system rules for windows update**

**Comment by Tom4tot** [comment]
> 
> 
> i have creat new rule for **svchost TCP port 443** for windows update and windows update is enable without other svchost process go online :)
> you should add this rule to **system rules for windows update**

Can you explain the exact steps to create such a rule please? Thanks.

**Comment by beerisgood** [comment]
Why not using the internal rule for Windows update?!

**Comment by bugefo** [comment]
user rules tab > right click > creat rule.. > protocol TCP ,  rule (remote) 443  and choos svchost.exe from list

**Comment by bugefo** [comment]
> Why not using the internal rule for Windows update?!

i didn't undrestand exactly but simplewall don't have internal rule for windows update!

**Comment by Tom4tot** [comment]
> 
> 
> user rules tab > right click > creat rule.. > protocol TCP , rule (remote) 443 and choos svchost.exe from list

Doesn't work for me... I still have an error when I try to update. 

https://i.imgur.com/By4Irel.png

**Comment by bugefo** [comment]
if you use v 3.0.1 go to setting > Rules > Blocklist > mark Allow M$ update server

**Comment by henrypp** [comment]
https://github.com/henrypp/simplewall/issues/206#issuecomment-494810204
