### ISSUE TITLE
[Feature Request] DPI Scaling / Zoom in

### ISSUE THREAD

**Issue by Chaython** [henrypp/simplewall#447]
The font is really small on my monitors [3840x2160]
Can you please add the option to dynamically scale `[CTRL] [+]` and/or add the option to change the font under interface settings?
It's still legible but sometimes I have to squint/adjust my seating
Thanks for the great software <3

**Comment by henrypp** [comment]
You can change font weight. View->Font...

**Comment by Chaython** [comment]
Thank you, still maybe useful to add zooming in the future; but knowing this will really help with eye strain <3
