### ISSUE TITLE
Problems with FireFox 67. Is last stable SimpleWall (2.64) the cause?

### ISSUE THREAD

**Issue by nji9nji9** [henrypp/simplewall#448]
Is it possible that last stable SimpleWall prevents
the latest FireFox 67 (Win7 64) to work with its AddOns?
("Old type", not configurable/ deletable etc.)

**Comment by beerisgood** [comment]
No problem here with SimpleWall (2.64) and Firefox 67 under Windows 10

**Comment by henrypp** [comment]
What problem? No problem here with SimpleWall (2.64) and Firefox 67 under Windows 10

**Comment by nji9nji9** [comment]
The cause doesn't seem to be SimpleWall but the AddOn certification issue of the former FF (66.x).
