### ISSUE TITLE
[Clarification] App file vs Service

### ISSUE THREAD

**Issue by pwn0r** [henrypp/simplewall#449]
An interesting stuff here with the 3.0x change.

1. Some apps spawn services. For instance again gaming platforms. These services normally off but get started when a platform (like Steam) is running. 

2. Before the 3.x branch I used to open just an application file in the apps list for that. 

3. Now we have services in a separate tab. So now I have these services listed both in the apps window and in the services window. 

So the question is the correct way of enabling these services temporarily? Do I need to enable both entries, apps and services?  Or just use new services tab? In any case enabling them in one UI tab does not show them as enabled in another tab.

**Comment by henrypp** [comment]
- 1. apps/services/uwp filters are different, all what you need to apply is cantained in Dropped packets log.
- 2. services as filters can be applied in 2.x too, now it just catalog of all services listed in system.
- 3. what services? services or its binaries?
