### ISSUE TITLE
Some applications become unresponsive when not allowing internet access

### ISSUE THREAD

**Issue by nulledone** [henrypp/simplewall#45]
I have found out that Steam, Steam Webhelper and some other apps become unresponsive for a time (10 seconds to more than a minute) as long as you block the connection.

In this scenario I have allowed steam access but not webhelper so it became unstable.

**Comment by CHEF-KOCH** [comment]
I can't confirm this behavior. Steam is based on Chrome/Chromium so whenever a application like the wrapper to display the content is blocked then there is nothing to show and t trys to reconnect after xy amount of time. This is an expected behavior.

**Comment by henrypp** [comment]
What version? Allow listen connections for all is checked or not?

**Comment by nulledone** [comment]
1.6.5 - not checked

**Comment by henrypp** [comment]
so check it.
