### ISSUE TITLE
[Feature Request] Security: block all traffic if simplewall is closed/undetected

### ISSUE THREAD

**Issue by Chaython** [henrypp/simplewall#451]
[Feature Request] Security: block all traffic if simplewall is closed/undetected
I install most of my software to my external HDD. I forgot to plug it in, so I had no firewall for awhile....
Would it be possible to have a security feature, to block all traffic if simplewall is missing or closed, or at least a feature to re-enable windows firewall if simplewall is missing or closed?

If you close simplewall it will warn you that filters will work even if it's closed, but what if it was missing as described? There is just no protections right?

**Comment by perdolka** [comment]
https://github.com/henrypp/simplewall/issues/239#issuecomment-424966327

**Comment by Chaython** [comment]
As stated, not sure if rules work if simplewall is MISSING, not just not running. 
Also was wondering if the option can be added to only allow traffic if simplewall is active. [many VPNs have a driver to auto disconnect internet when a connection isn't established]

**Comment by fredgolightly** [comment]
> 
> 
> As stated, not sure if rules work if simplewall is MISSING, not just not running.
> Also was wondering if the option can be added to only allow traffic if simplewall is active. [many VPNs have a driver to auto disconnect internet when a connection isn't established]

Simplewall works as a front end to managing firewall rules - once they're set they're set, and are in place all the time, not just when the app is running - the app is more a rules moderator of the firewall whereas the Windows firewall itself is always running, simplewall present or not.

**Comment by henrypp** [comment]
> Simplewall works as a front end to managing firewall rules

Сorrection: SW works as front end of Windows Filtering Platform (WFP), not an Windows Firewall (WF)
