### ISSUE TITLE
Network Rules aren't working

### ISSUE THREAD

**Issue by Chaython** [henrypp/simplewall#452]
I am trying to block this IP, because it's always appearing as established 64.30.228.84
So I create a rule
Remote: 64.30.228.84
Local: 192.168.0.10
All apps
direction: both
TCP
ALL
Block
64.30.228.84 Still loads...
I tried multiple rules and none seem to work

**Comment by henrypp** [comment]
Incorrect rule, local address not needed

**Comment by Chaython** [comment]
When Right click - create rule, why does it by default have a local IP if it breaks the rules?
Blocking a specific port?
Maybe add option to default local to blank, to add rules faster?
Thanks as always <3
