### ISSUE TITLE
Listen & Loop Back

### ISSUE THREAD

**Issue by Chaython** [henrypp/simplewall#453]
I have disabled both listen and loopback but in the network tab many are still listening and loopbacking
Loop Back
`firefox.exe 127.0.0.1:21789 (Chaythons_PC) 127.0.0.1:22045 (Chaythons_PC) TCP Established
firefox.exe 127.0.0.1:22045 (Chaythons_PC) 127.0.0.1:21789 (Chaythons_PC) TCP Established
firefox.exe 127.0.0.1:22301 (Chaythons_PC) 127.0.0.1:22557 (Chaythons_PC) TCP Established
firefox.exe 127.0.0.1:22557 (Chaythons_PC) 127.0.0.1:22301 (Chaythons_PC) TCP Established
firefox.exe 127.0.0.1:23069 (Chaythons_PC) 127.0.0.1:23325 (Chaythons_PC) TCP Established
firefox.exe 127.0.0.1:23325 (Chaythons_PC) 127.0.0.1:23069 (Chaythons_PC) TCP Established
firefox.exe 127.0.0.1:24605 (Chaythons_PC) 127.0.0.1:24861 (Chaythons_PC) TCP Established
firefox.exe 127.0.0.1:24861 (Chaythons_PC) 127.0.0.1:24605 (Chaythons_PC) TCP Established`
Listening
`CDPSvc 0.0.0.0:45075 (Chaythons_PC) 0.0.0.0 (Chaythons_PC) TCP Listen
EventLog 0.0.0.0:262 (Chaythons_PC) 0.0.0.0 (Chaythons_PC) TCP Listen
EventLog :::262 (Chaythons_PC) :: (Chaythons_PC) TCP Listen
lsass.exe 0.0.0.0:1798 (Chaythons_PC) 0.0.0.0 (Chaythons_PC) TCP Listen
lsass.exe :::1798 (Chaythons_PC) :: (Chaythons_PC) TCP Listen
PolicyAgent 0.0.0.0:1286 (Chaythons_PC) 0.0.0.0 (Chaythons_PC) TCP Listen
PolicyAgent :::1286 (Chaythons_PC) :: (Chaythons_PC) TCP Listen
RpcSs 0.0.0.0:34560 (Chaythons_PC) 0.0.0.0 (Chaythons_PC) TCP Listen
RpcSs :::34560 (Chaythons_PC) :: (Chaythons_PC) TCP Listen
Schedule 0.0.0.0:518 (Chaythons_PC) 0.0.0.0 (Chaythons_PC) TCP Listen
Schedule :::518 (Chaythons_PC) :: (Chaythons_PC) TCP Listen
services.exe 0.0.0.0:1030 (Chaythons_PC) 0.0.0.0 (Chaythons_PC) TCP Listen
services.exe :::1030 (Chaythons_PC) :: (Chaythons_PC) TCP Listen
Spooler 0.0.0.0:774 (Chaythons_PC) 0.0.0.0 (Chaythons_PC) TCP Listen
Spooler :::774 (Chaythons_PC) :: (Chaythons_PC) TCP Listen
steam.exe 0.0.0.0:40041 (Chaythons_PC) 0.0.0.0 (Chaythons_PC) TCP Listen
steam.exe 127.0.0.1:46185 (Chaythons_PC) 0.0.0.0 (Chaythons_PC) TCP Listen
System 192.168.0.10:35584 (Chaythons_PC.hitronhub.home) 0.0.0.0 (Chaythons_PC) TCP Listen
System 192.168.56.1:35584 (Chaythons_PC) 0.0.0.0 (Chaythons_PC) TCP Listen
System 0.0.0.0:48385 (Chaythons_PC) 0.0.0.0 (Chaythons_PC) TCP Listen
System 0.0.0.0:60692 (Chaythons_PC) 0.0.0.0 (Chaythons_PC) TCP Listen
System :::48385 (Chaythons_PC) :: (Chaythons_PC) TCP Listen
System :::60692 (Chaythons_PC) :: (Chaythons_PC) TCP Listen
wininit.exe 0.0.0.0:6 (Chaythons_PC) 0.0.0.0 (Chaythons_PC) TCP Listen
wininit.exe :::6 (Chaythons_PC) :: (Chaythons_PC) TCP Listen`

I know Firefox will crash without loopback, but is there anyway to block it anyways? Malicious software could use a loopback to connect to the web through a whitelisted application[?] So I want to block all by default.
Most of these listening are system services  but even with all MS blocked in rules tab they're still listening; I know listening is not an active connection rather waiting for a connection, and I have "installed filter protection" enabled, but  is there anyway a listening connection could be opened? Anyways not really worried about the listening more so about loopback is there anyway to identify if a loopback could be malicious? I assume the only way is to watch the destinations of all traffic from an application with loopback? Or that an application is only porting to itself not porting to/from another application?

**Comment by henrypp** [comment]
Answer for all question is "NO".

But SW is not an antivirus and does not determine any malicious traffic and disabling listen & loopback is not a solution too.
