### ISSUE TITLE
MS Edge & MS Store rules [v3.0.1 Beta]

### ISSUE THREAD

**Issue by Matthaiks** [henrypp/simplewall#454]
MS Edge & MS Store rules in User rules are doubled (Pico + UWP). Restarting simplewall changes these UWP apps into Pico apps in custom rules. Both Pico & UWP apps must be enabled to work correctly.
Windows 10 x64 1809.

**Comment by henrypp** [comment]
What apps, dude. I am not telepath!

**Comment by Matthaiks** [comment]
Before restart;
![Before](https://user-images.githubusercontent.com/3577122/58436228-8b44d480-80c4-11e9-858c-592d997668cd.png)
After restart:
![After](https://user-images.githubusercontent.com/3577122/58436236-a31c5880-80c4-11e9-9710-ec2db5fdc69d.png)

**Comment by henrypp** [comment]
So it doesn't tell me anything, too

**Comment by Matthaiks** [comment]
New discoveries: in User rules, any UWP apps (green icons) are being converted to Pico apps (generic icons) after restarting simplewall or refreshing its filters. And UWP apps "converted" to Pico apps cannot make any connections.

Go to User rules, create a new rule with any UWP app, save, refresh (or restart simplewall), check new rule's properties and there will be the broken Pico app.
