### ISSUE TITLE
Is there a way to shut the firewall up and auto allow/block/timer based on path pattern?

### ISSUE THREAD

**Issue by UNDEFINED-BEHAVIOR** [henrypp/simplewall#456]
![image](https://user-images.githubusercontent.com/8407331/58741737-859a1680-8457-11e9-81ea-0415f3c6f442.png)

ex:
C:\windows\temp\vxf3heoc.jve\resources\app\servicehub\services\microsoft.visualstudio.setup.service\backgrounddownload.exe

**Comment by Tom4tot** [comment]
https://github.com/henrypp/simplewall/issues/307
https://github.com/henrypp/simplewall/issues/379
https://github.com/henrypp/simplewall/issues/136#issuecomment-389056619

I suppose that's the feature you wanted?

**Comment by henrypp** [comment]
No, sorry!

https://github.com/henrypp/simplewall/issues/136#issuecomment-389056619

**Comment by UNDEFINED-BEHAVIOR** [comment]
@henrypp 
w8 m8
Isn't notification panel outside WFP jurisdiction? 
Why not just auto-allow on UI side base on regex path, pretty plz.

**Comment by mikefirefly** [comment]
I know this is closed but I'm facing this annoying issue right now and I think I found a working solution. Please see here: https://i.imgur.com/q33bn3h.png
