### ISSUE TITLE
Periodically auto-export app.xml and custom_rules.xml with date and time

### ISSUE THREAD

**Issue by PunnyBoi** [henrypp/simplewall#458]
Sometimes when my laptop wakes up from hibernation, all my filtered apps and rules get deleted. Also, the default XML file gets updated. So, I have to add all the apps to blocklist again and set the rules again.

After the first time this happened, I started to export the app.xml and custom_rules.xml so that whenever the apps get auto-deleted, I would import them from the saved XML file.

I was wondering if the export process could be automated, i.e. the apps are automatically exported to apps_{date}{time}.xml and rules to custom_rules_{date}{time}.xml after a particular period (daily or weekly) or say after adding a new app to the blocked list.

**Comment by perdolka** [comment]
Use the last version of SW (3.0.1): https://github.com/henrypp/simplewall/issues/391#issuecomment-491314105
Also, you have a `profile.xml.bak` file in simplewall folder.

**Comment by henrypp** [comment]
duplicate #391
