### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by Chaython** [henrypp/simplewall#459]
Some apps like visual studio has 7 "apps" 
How about some sort of categorizing or a parent /child list?

**Comment by pwn0r** [comment]
i second that. 

Real life example, again gaming -- i play two online games. 
One needs FOUR exceptions (two apps and two services for that matter!)
gaming/shopping platform + their service, then the game itself and an anticheat service. 
If at least one is disabled, the game will not start properly :) 


Another game needs three more exceptions. And if I played e.g. CSGO as a third game, that thing needs another 3 or 4 exceptions.

**Comment by henrypp** [comment]
@pwn0r, why it's so complicated? I mean this:

> One needs FOUR exceptions (two apps and two services for that matter!)

To allow Steam (and it's games) working properly you just need to allow "steam", "gameoverlayui" and "csgo" executables (no services required to allow), why you need another bloatware features - it just 3 checkboxes (same for visual studio)

**Comment by pwn0r** [comment]
> 
> 
> @pwn0r, why it's so complicated? I mean this:
> 
> > One needs FOUR exceptions (two apps and two services for that matter!)
> 
> To allow Steam (and it's games) working properly you just need to allow "steam", "gameoverlayui" and "csgo" executables (no services required to allow), why you need another bloatware features - it just 3 checkboxes (same for visual studio)

Technically that would allow only csgo as per example. For other games you need to add more.
But that it steam (and i'm kinda sure you need a 4th one but not at the gaming computer to check right now).

But not everything is csgo :)
Lets take the painful thing, apex, for starters. Here I'm more than experienced -- you need 4 exceptions for gaming, and actually a 5th one during patch installs. 

You can count yourself -- origin and apex apps, origin client service (otherwise it would not connect to friends etc) and EAC service. And if you have a client patch then you need a 5th exception for an installer exe.

**Comment by Chaython** [comment]
XblAuthManager ‎2019-‎06-‎07 ‏‎8:22 PM
XblGameSave ‎2019-‎06-‎07 ‏‎8:22 PM
XboxGipSvc ‎2019-‎06-‎07 ‏‎8:22 PM
XboxNetApiSvc ‎2019-‎06-‎02 ‏‎3:44 AM
gamebarpresencewriter.exe ‎2019-‎05-‎23 ‏‎5:44 AM
gamingservices.exe ‎2019-‎06-‎16 ‏‎4:26 AM
svchost.exe ‎2019-‎04-‎20 ‏‎2:51 PM
xbox.exe ‎2019-‎06-‎16 ‏‎11:40 PM
Microsoft Store ‎2019-‎04-‎25 ‏‎3:26 AM
Microsoft.Windows.CloudExperienceHost_10.0.18912.1001_neutral_neutral_cw5n1h2txyewy ‎2018-‎10-‎02 ‏‎6:32 PM
Microsoft.Windows.ContentDeliveryManager_10.0.18912.1001_neutral_neutral_cw5n1h2txyewy ‎2019-‎04-‎20 ‏‎7:19 PM
Microsoft.XboxGameCallableUI_1000.18912.1001.0_neutral_neutral_cw5n1h2txyewy ‎2018-‎10-‎02 ‏‎6:32 PM
Gaming Services ‎2019-‎06-‎09 ‏‎12:30 AM
Halo ‎2019-‎05-‎02 ‏‎2:46 AM
Halo Wars 2 ‎2019-‎03-‎23 ‏‎10:13 PM
Xbox (Beta) ‎2019-‎06-‎09 ‏‎4:54 PM
Xbox Game Bar ‎2019-‎05-‎22 ‏‎5:52 PM
Xbox Game Bar Plugin ‎2019-‎05-‎22 ‏‎5:52 PM
Xbox Identity Provider ‎2019-‎05-‎22 ‏‎5:52 PM
Xbox Insider Hub ‎2019-‎05-‎22 ‏‎6:22 PM
Xbox TCUI ‎2019-‎03-‎23 ‏‎10:13 PM
To install /play halo + have achievements + multiplayer w/ xbox game pass

**Comment by henrypp** [comment]
@Chaython 
@pwn0r
No, i hope user need his own decision what is need to be allowed and this is not a solution. Sorry!

**Comment by Chaython** [comment]
Yes; I didn't expect you to make categories yourself. I just wanted the option to make categories. I have over 300 apps installed; would be nice to minimize most of them to categories. I could also toggle categories on or off; when I am doing different tasks. As often certain things require an internet connection to launch an app; but run in the background after initialization... I thought that would be an easy thing to add. Sorry.

**Comment by caviidae** [comment]
@Chaython I allowed everything that I could find related to xbox on my list but still when I try the Xbox Networking check in  Windows Settings it fails the test. But it works fine with Simplewall disabled. Did you do anything else special to make it work? Halo 3 multiplayer fails for me and I think it might be Teredo related.

**Comment by Chaython** [comment]
Teredo should only be needed for achievements/ progress tracking note for Xbox live networking.
![image](https://user-images.githubusercontent.com/6486343/90268868-efac9a80-de14-11ea-8df9-cc5ed3d3d56e.png)
"Spying & Telemetry" include Teredo
If you're using MS store you also have to allow the MS apps.
You can also check your hosts file, %SystemRoot%\System32\drivers\etc\hosts
Or change your DNS provider.

If it's the steam edition, multiplayer works fine, by just allowing the app. 
![image](https://user-images.githubusercontent.com/6486343/90269208-7eb9b280-de15-11ea-9c54-689d85863d40.png)
You may also need to allow the EAC service if you're launching in EAC mode, time desync can also cause rejection, so allow w32time and as it's a steam game you must allow steam. 
![image](https://user-images.githubusercontent.com/6486343/90269453-e112b300-de15-11ea-9d4b-c06d28d872a5.png)
![image](https://user-images.githubusercontent.com/6486343/90269480-ee2fa200-de15-11ea-928c-4014a6e9196d.png)
![image](https://user-images.githubusercontent.com/6486343/90269552-07d0e980-de16-11ea-9143-eb8d68f6470d.png)

For the XBL edition you need 
Your Account [UWP]
Xbox Game UI [UWP]
MCCLauncher [The UWP game id]
MCC and MCC launcher [app ids]
The Xbox services
![image](https://user-images.githubusercontent.com/6486343/90269798-72822500-de16-11ea-8130-db771157ae1f.png)
For the Xbox live network test you need to allow the settings app and some related services.
UWP apps are spaghetti code cancer that run in sys and are completely broken. If you bought on MS store apply for a refund and buy on steam.

If everything is allowed then you need to open ports in your various firewalls. [Modem, router, simplewall, whatever other ones you have...] To play on XBL with opened NAT it's best to set your system in your networks DMZ, or setup an IP passthrough with your ISP. This however does remove a layer of security, and I generally recommend running windows in a virtual machine.

**Comment by Chaython** [comment]
> 
> 
> @Chaython
> @pwn0r
> No, i hope user need his own decision what is need to be allowed and this is not a solution. Sorry!

With things like visual studio that's a cancerous spaghetti code of 20 apps that demand network access install breaks, because something is blocked and there's no check. You basically have to disable simplewall to install it without breakage or find an offline installer. IK it's not your fault nor problem that most companies make terrible online installers. But without enabling dependencies you basically have to disable it, which is much less secure. But again originally I was just promoting self written categories that would enable the user to allow or disable a list at once. Though this can be done by swapping profiles it's not very efficient compared to a GUI element.
Sorry for bringing this back up, it's just becuase this other guy's necro.
Love you, thanks for the application.
