### ISSUE TITLE
Decreased rights for started programs

### ISSUE THREAD

**Issue by nji9nji9** [henrypp/simplewall#460]
Programs that are started by SimpleWall (i.e. browser)
should be called with decreased rights, and not as admin.
(I use admin rights only when necessary - and never online.)

**Comment by henrypp** [comment]
> should be called with decreased rights.

No, [this technique is dirty.](https://devblogs.microsoft.com/oldnewthing/20131118-00/?p=2643)

**Comment by nji9nji9** [comment]
I never mentioned a TECHNIQUE.
What I mean is a BEHAVIOUR of SimpleWall (And calling a browser with admin privileges is anything but secure, if you want my opinion).
In the article you mention above there is described how to achieve the safe behaviour.
BTW. In recent version of SimpleWall "Help Website" and "Donate" are de-activated
- which is good, as long as called as admin - "Check for updates" works.

Why did you close the issue??? You do not describe if / how you solved it...?
