### ISSUE TITLE
Windows Update

### ISSUE THREAD

**Issue by upxdouglas121** [henrypp/simplewall#461]
Hi, 

I am using the 3.01 beta version with the allow Windows update option enabled. 

I can't get Windows to check for updates like that. 

The only way is to enable svchost.exe

Is there any suggestion or solution to his?

**Comment by perdolka** [comment]
First, try this:
![зображення](https://user-images.githubusercontent.com/24720263/59512183-dfbbc280-8ec0-11e9-8476-a50f4b723c94.png)

**Comment by PunnyBoi** [comment]
I think enabling the option 'Allow windows update' is enough for windows update. But if you want to update windows defender, then you have to enable svchost.exe.

**Comment by henrypp** [comment]
All blocked packets dumping into log, you can see what blocked there/
