### ISSUE TITLE
Semicolons in exe file paths cause invalid entries when exporting and importing custom rules

### ISSUE THREAD

**Issue by Robot1me** [henrypp/simplewall#462]
How to verify this bug:
1. Add a program to Simplewall that has a semicolon somewhere in its file path.
2. Create a custom rule. Select multiple programs, including the one with the semicolon.
3. Export rules_custom.xml
4. Import rules_custom.xml
5. The application splits the affected program paths earlier than expected due to the semicolon in the file path, which creates trash entries. Applications that don't have any semicolon in their path or name are unaffected and those paths are parsed correctly.

Suggestion: Perhaps it's a good idea to switch to a pipe ( | ) to separate paths in rules? Because that is for sure an illegal path character in Windows file paths.

Thanks for your time.

**Comment by henrypp** [comment]
ok, fixed. replaced `;` with `|`
