### ISSUE TITLE
Allow user rules without "Rule (Remote)" and/or "Rule (Local)" value

### ISSUE THREAD

**Issue by ieno** [henrypp/simplewall#464]
Just started using the v3.0.1 BETA, and I like it alot.

However, maybe I'm missing something, but it would be nice if adding user rules **without** a remote or local value would be possible. Say if I for instance want to allow outbound ICMP protocol for a specific app, to and from **all** IP's/ports. The save button currently simply remains disabled, as either "Rule (Remote)" or "Rule (Local)" is apparently mandatory.

The predefined system rules seem to have empty values for these fields, so syntax wise it appears to be possible...

**Comment by SimpleUs** [comment]
> The save button currently simply remains disabled, as either "Rule (Remote)" or "Rule (Local)" is apparently mandatory.

Try to put a "*" in these fields.

**Comment by ieno** [comment]
> Try to put a "*" in these fields.

Ah, wildcards are accepted and usable!
Thanks alot, it seems to be working 👍
