### ISSUE TITLE
simple wall still deletes rules

### ISSUE THREAD

**Issue by 0lm** [henrypp/simplewall#465]
unfortunately simplewall deletes all my set up rules after a while. it happens occassionally after a restart of my computer, there is no real pattern (at least i didnt notice a pattern). since that happens, i backed up all my rules but after only a few days it deleted them all again. 
there already was an issue for this but i couldnt find it anymore and looks like its still deleting rules. any ideas wha could be the cause?

**Comment by Tom4tot** [comment]
Update to 3.01. (beta).

( https://github.com/henrypp/simplewall/issues/391#issuecomment-491314105 )

**Comment by 0lm** [comment]
thank you for your comment. i couldnt find that issue anymore, thats why i re-posted the issue. and since simple wall has auto update, i didnt check for any new versions on the "releases" tab. i will try it out.

greetings.
