### ISSUE TITLE
"Add process" for RAMdrive does not work properly

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#466]
When I try to add a process to simplewall via right-click -> Add process, the path is incorrect when that process is run from a RAMdrive. Instead of `A:\process.exe`, the process is added as `\device\imdisk0\process.exe`. As such, it will NOT be allowed network access when the process is then checked in simplewall.

Could you please make sure that in these cases, the drive letter is used instead of the "device path"?

**Comment by henrypp** [comment]
simplewall is working well with device paths, understand this and create normal filters for that.
this happened when device cannot drive letter or some other reasons
