### ISSUE TITLE
Time Sync is blocked

### ISSUE THREAD

**Issue by meadows19** [henrypp/simplewall#467]
Hi

1) Windows time sync is blocked and can't synchronise the time of the PC with internet time servers

2) Spotlight is blocked and the lock screen picture does not change

the only Windows services i'm blocking are:

msiexec,exe
compattelrunner.exe 
devicecensus.exe 

In rules, I have not clicked 'allow M$ applications'

How do I fix this?
Thank you.

**Comment by beerisgood** [comment]
I think you answer the solution by yourself

**Comment by meadows19** [comment]
These functions are part of the OS, not separate MS programs like Skype or Outlook etc.

**Comment by perdolka** [comment]
>     2. Spotlight is blocked and the lock screen picture does not change

1. Allow M$ applications
2. Add **Microsoft Content** UWP to **Enabled apps** list (**Packages** tab).

**Comment by cloudgreen** [comment]
@perdolka Spotlight won't work even though I have enabled "Allow Microsoft application servers" and also added _Microsoft Content_ to _Enabled apps_ under _Packages_... any ideas what to check?

**Comment by henrypp** [comment]
use ntp system rule

**Comment by cloudgreen** [comment]
Thanks @henrypp !

But I was actually referring to "Windows Spotlight", the feature that changes the picture on the the lock screen. :)

It's a bit confusing that this thread is mainly about NTP, but the OP also mentioned Spotlight. :)

**Comment by meadows19** [comment]
> It's a bit confusing that this thread is mainly about NTP, but the OP also mentioned Spotlight. :)

My spotlight also stopped working a few weeks ago, even though Microsoft Update servers and MS applications are allowed in settings.
