### ISSUE TITLE
Inbound connection filter applied to outbound connection?

### ISSUE THREAD

**Issue by ieno** [henrypp/simplewall#468]
Occassionally I get notified that an outbound connection attempt is filtered by an inbound connection filter:
![simplewall_outbound-inbound](https://user-images.githubusercontent.com/7884796/59762849-73faa080-9298-11e9-9418-c101ca0fd9e2.png)

The odd thing is, that even after creating a rule based on this notification (allowing outbound traffic, matching the protocol and port), these kinds of notifications keep popping up. If however I create a similar rule matching **inbound** traffic instead of outbound, the notifications stop.

Could it be the notification is wrongly showing the attempt as being outbound, while in fact it is an inbound connection, or does udp always require a matching inbound rule or something?

**Comment by henrypp** [comment]
Hello, this is not a bug. It's incorrect filter names for `recv()` `accept()` actions.
My misstake!

**Comment by ieno** [comment]
@henrypp thanks, I've just updated to 3.0.2, but I think something is still not right in determining the direction. The following rule is currently active:
> item name="mDNS" rule="5353;5355" dir="2" protocol="17" apps="C:\windows\system32\svchost.exe" is_enabled="true"

However, this packet was just dropped & logged by simplewall:
> "‎23-‎Jun-‎19 ‏‎00:31:51","NT AUTHORITY\NETWORK SERVICE","C:\windows\system32\svchost.exe","<IPv6-IP>:5353","mdns","UDP","simplewall\BlockRecvAcceptConnectionsV6","#82489","**Outbound**","Blocked"

Since I also have WFP logging enabled, I checked the Event Viewer where this was the event entry for the same (dropped) connection:
> The Windows Filtering Platform has blocked a packet.
> 
> Application Information:
> 	Process ID:		2076
> 	Application Name:	\device\harddiskvolumeX\windows\system32\svchost.exe
> 
> Network Information:
> 	Direction:		**Inbound**
> 	Source Address:		<the same IPv6 IP>
> 	Source Port:		5353
> 	Destination Address:	ff02::fb
> 	Destination Port:		5353
> 	Protocol:		17
> 
> Filter Information:
> 	Filter Run-Time ID:	82489
> 	Layer Name:		Receive/Accept
> 	Layer Run-Time ID:	46

So to me it seems like the actual direction that simplewall shows is not correct?
