### ISSUE TITLE
Allowed apps are still blocked

### ISSUE THREAD

**Issue by cmbail** [henrypp/simplewall#469]
On reviewing the log, I see that several "Allowed apps" are still regularly blocked. e.g.:

"‎6/‎20/‎2019 ‏‎11:23:59 AM","...","C:\windows\system32\svchost.exe",52.114.132.21:443 (Remote),192.168.2.112:52507 (Local),TCP,"simplewall\spy_52.114.132.21",#89110,OUT,BLOCK
"‎6/‎20/‎2019 ‏‎11:29:40 AM","...","C:\users\...\appdata\local\microsoft\onedrive\onedrive.exe",52.114.128.44:443 (Remote),192.168.2.112:52772 (Local),TCP,"simplewall\spy_52.114.128.44",#89106,OUT,BLOCK
"‎6/‎20/‎2019 ‏‎11:31:51 AM","NT AUTHORITY\SYSTEM","C:\program files\common files\microsoft shared\clicktorun\officeclicktorun.exe",52.114.158.50:443 (Remote),192.168.2.112:52924(Local),TCP,"simplewall\spy_52.114.158.50",#89120,OUT,BLOCK

**Comment by henrypp** [comment]
It's blocklist entries, disable it if you do not needed

**Comment by cmbail** [comment]
Thank you for answering so quickly! And for building and maintaining such a powerful and lightweight product. I did google for this issue first, but didn't find it, so hope this helps others.

Makes sense - so you have identified Microsoft telemetry whose primary purpose is spying/tracking rather than app features.
