### ISSUE TITLE
Allow access Repeat

### ISSUE THREAD

**Issue by Saadi1988** [henrypp/simplewall#471]
Hi. i'm using Simplewall for a few weeks. it shows allow access alert minimum every one hour for one of "Visual Studio" components that runs in windows temp folder and when i allow or block it, it will show again a few later(maximum:1h) again. it run on a new path every time. plz see:
![Untitled](https://user-images.githubusercontent.com/42292489/59969203-baccec80-955d-11e9-9816-0bf9414683c8.png)

**Comment by henrypp** [comment]
Do you clicked any button in notification window?

**Comment by Saadi1988** [comment]
yea, some times i choosed allow.

**Comment by Saadi1988** [comment]
also it connects to different IPs.

**Comment by henrypp** [comment]
You can set period between notification of same app in settings. Thats all!

**Comment by Saadi1988** [comment]
but this application is not signed and every time run in a different
temporary folder. However, after upgrading VS 16.1.1 to 16.1.3 the
problem seems to be fixed.

**Comment by Saadi1988** [comment]
the problem is back. seems Visual Studio is auto-updating. but every time runs in a different temporary folder. How i can fix the problem? is there any way? thanks.
