### ISSUE TITLE
add app as timer

### ISSUE THREAD

**Issue by hesss5** [henrypp/simplewall#472]
tested latest beta
when clicking allow or block both will be added as timer app
1190 hr

**Comment by henrypp** [comment]
No, timer action is only for "Allow", it always was, it always be

**Comment by hesss5** [comment]
but for me but clicking allow or block will make app timer
without selecting timer
![ss](https://user-images.githubusercontent.com/23487445/59975195-85121d00-95ca-11e9-91a5-31c51cc4c765.png)

**Comment by henrypp** [comment]
Ohhh, it's seems bug

**Comment by henrypp** [comment]
can you describe what do you do, step by step?

**Comment by hesss5** [comment]
run SW try extract setup file with universal extractor  then give me popup if i click block it go to enabled app as timer one same happen if i click allow i just use that button don't touch anything else
its portable version and its upgraded from Previous beta
