### ISSUE TITLE
Check boxes almost invisible with dark theme applied

### ISSUE THREAD

**Issue by ieno** [henrypp/simplewall#473]
The check boxes shown in right-click options menu are very hard to see when the dark theme is applied:
![Dark_theme](https://user-images.githubusercontent.com/7884796/59975794-77ee3180-95bc-11e9-8bd7-db377fa41013.png)
Would it be possible to make them stand out more, or else make the dark theme optional (as I currently don't see any option to disable it)?

**Comment by henrypp** [comment]
I think to replace graphics is good idea

**Comment by Jtasiu** [comment]
@henrypp will you to add full dark theme to the program in future?

**Comment by henrypp** [comment]
@Jtasiu dark theme issue here #248
