### ISSUE TITLE
[Feature Request] Option to choose between new and old notification ui

### ISSUE THREAD

**Issue by mohcow** [henrypp/simplewall#478]
First of all thanks for the great work! With 3.0.2 you added a new notification ui which i'm not that fond of. Is it possible to add an option to choose between old and new ui? Cheers

**Comment by perdolka** [comment]
+1

**Comment by henrypp** [comment]
What does not like you in new UI?

**Comment by perdolka** [comment]
Хотелось бы чтоб окошко появлялось в углу экрана.
Думаю, @mohcow тоже имел это ввиду.
Может, сделать хотя бы так, чтобы окошко запоминало позицию, куда я его переместил?
