### ISSUE TITLE
OneDrive included in "Microsoft spying and telemetry servers" list

### ISSUE THREAD

**Issue by natasha-ntsh** [henrypp/simplewall#479]
In result Simplewall constantly nags honest OneDrive users with notifications.

**Comment by henrypp** [comment]
So, OneDrive working and just nags?

![sshot-002](https://user-images.githubusercontent.com/3902025/60501780-67d20280-9cde-11e9-8a69-8ebbaeb59923.png)

**Comment by janusz-bb** [comment]
No, it's not working but every time it tries to connect I get the Simplewall nag. Putting OD on that list was a mistake anyway.

**Comment by henrypp** [comment]
SW does not show notifications for blocklist by default, what in dropped packets log?

**Comment by janusz-bb** [comment]
Sure it does.

"‎13/‎07/‎2019 ‏‎17:05:12","XPS15\XPS","C:\users\xps\appdata\local\microsoft\onedrive\onedrive.exe","52.114.32.7:443","https","TCP","simplewall\spy_52.114.32.7","#3441644","Outbound","Blocked"
"‎13/‎07/‎2019 ‏‎17:05:20","XPS15\XPS","C:\users\xps\appdata\local\microsoft\onedrive\onedrive.exe","52.114.32.7:443","https","TCP","simplewall\spy_52.114.32.7","#3441644","Outbound","Blocked"
"‎13/‎07/‎2019 ‏‎17:05:20","XPS15\XPS","C:\users\xps\appdata\local\microsoft\onedrive\onedrive.exe","52.114.32.7:443","https","TCP","simplewall\spy_52.114.32.7","#3441644","Outbound","Blocked"
"‎13/‎07/‎2019 ‏‎17:05:20","XPS15\XPS","C:\users\xps\appdata\local\microsoft\onedrive\onedrive.exe","52.114.32.7:443","https","TCP","simplewall\spy_52.114.32.7","#3441644","Outbound","Blocked"
"‎13/‎07/‎2019 ‏‎17:05:20","XPS15\XPS","C:\users\xps\appdata\local\microsoft\onedrive\onedrive.exe","52.114.32.7:443","https","TCP","simplewall\spy_52.114.32.7","#3441644","Outbound","Blocked"
"‎13/‎07/‎2019 ‏‎17:05:20","XPS15\XPS","C:\users\xps\appdata\local\microsoft\onedrive\onedrive.exe","52.114.32.7:443","https","TCP","simplewall\spy_52.114.32.7","#3441644","Outbound","Blocked"
"‎13/‎07/‎2019 ‏‎17:05:20","XPS15\XPS","C:\users\xps\appdata\local\microsoft\onedrive\onedrive.exe","52.114.32.7:443","https","TCP","simplewall\spy_52.114.32.7","#3441644","Outbound","Blocked"
"‎13/‎07/‎2019 ‏‎17:05:20","XPS15\XPS","C:\users\xps\appdata\local\microsoft\onedrive\onedrive.exe","52.114.32.7:443","https","TCP","simplewall\spy_52.114.32.7","#3441644","Outbound","Blocked"
"‎13/‎07/‎2019 ‏‎17:05:20","XPS15\XPS","C:\users\xps\appdata\local\microsoft\onedrive\onedrive.exe","52.114.32.7:443","https","TCP","simplewall\spy_52.114.32.7","#3441644","Outbound","Blocked"
