### ISSUE TITLE
Whitelist folder?

### ISSUE THREAD

**Issue by fredgolightly** [henrypp/simplewall#482]
Every time my Office 2016 suite updates the exe of the updater in C:\program files\common files\microsoft shared\clicktorun\updates\16.xxxxx1\ is updated to a new directory ie C:\program files\common files\microsoft shared\clicktorun\updates\16.xxxxx2\, which now is not white listed.

Is it possible to allow a folder through permanently, or in some way track the exe to keep it allowed through?

**Comment by henrypp** [comment]
#463
