### ISSUE TITLE
Simplewall consumes too much CPU resources

### ISSUE THREAD

**Issue by githubcom13** [henrypp/simplewall#486]
Simplewall consumes too much CPU resources on my Surface Pro i5 4go.

Is it possible to correct the problem via a setting?

![Sans titre](https://user-images.githubusercontent.com/2403925/60397296-6d322000-9b19-11e9-816b-2ddfbfcad731.png)

**Comment by henrypp** [comment]
what version?

**Comment by githubcom13** [comment]
Version 2.4.6, thanks

**Comment by henrypp** [comment]
I know about this, beta version 3.x was already fixed this. No new versions for 2.x branch will be.
