### ISSUE TITLE
windows update error

### ISSUE THREAD

**Issue by upxdouglas121** [henrypp/simplewall#492]
2019-06 Cumulative Update for Windows 10 Version 1903 for x64-based Systems (KB4501375) - Error 0x800f081f

this is with svchost.exe enabled

**Comment by TemperTrap29187** [comment]
Take a look [here](https://github.com/henrypp/simplewall/issues/481#issuecomment-508719965).

**Comment by upxdouglas121** [comment]
Thank you. I read somewhere that svchost is overkill for simply the update i.e. it leaks other info too to Microsoft..

**Comment by henrypp** [comment]
#481
