### ISSUE TITLE
Does it allows wildcard subdomain names in rules please?

### ISSUE THREAD

**Issue by raycheung** [henrypp/simplewall#494]
Pre 3.0.2 beta, it's possible to add an outbound allow rule for `*.mydomain.com:443`. Once I upgraded to 3.0.2 / 3.0.3, the rule showed with red and flagged as invalid.

Is the wildcard suppose to be supported please?

**Comment by henrypp** [comment]
No, wildcard will not be implemented, ever!
Here is available rules syntax https://github.com/henrypp/simplewall/wiki/Rules-editor

**Comment by raycheung** [comment]
Perfectly understood, thank you for the quick answer and the great app!

**Comment by asvc** [comment]
> No, wildcard will not be implemented, ever!

Out of curiosity, what's the rationale behind of this decision?

**Comment by skupjoe** [comment]
Opening new thread for thought/discussion on wildcard support in #1441
