### ISSUE TITLE
group

### ISSUE THREAD

**Issue by Iruberiam** [henrypp/simplewall#495]
Feature Request: UI Improvement. 

Some applications have several files that need to be permitted together, these are treated as seperate applications.  It would be great if we could move these to a custom tab or folder. To both improve the appearance and functionality of the Interface when lots of applications are present.

Simplewall is amazing.
Thank you.

**Comment by Iruberiam** [comment]
Feature Request: UI Improvement

Please can we have a Dark mode? :)

**Comment by henrypp** [comment]
#459
