### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by asvc** [henrypp/simplewall#499]
Windows 10 Pro, 10.0.18362 Build 18362
Simplewall v2.4.6
Might be related to https://github.com/henrypp/simplewall/issues/391

![image](https://user-images.githubusercontent.com/300146/61222422-d17bf300-a759-11e9-8058-2e94ac99e142.png)
No log in application folder, nothing specific in "events viewer". Application config:
```ini
[simplewall]
WindowPosX=1566
WindowPosY=588
WindowPosWidth=889
WindowPosHeight=593
IsDisableWindowsFirewallChecked=false
Mode=0
BackupTimestamp=1563196404
SettingsLastPage=108
IsLogEnabled=false
IsNotificationsEnabled=true
AutorunIsEnabled=true
IsSecureFilters=true
UseStealthMode=true
InstallBoottimeFilters=true
IsCerificatesEnabled=true
IsNetworkResolutionsEnabled=true
CheckUpdatesLast=1563115444
IconSize=0
ShowFilenames=true
AllowIPv6=false
ConfirmDelete=false
IsStartMinimized=true
SkipUacIsEnabled=true
IsWindowZoomed=false
Column1Width=0
Column2Width=0
Group1IsCollaped=false
Group2IsCollaped=false
Group3IsCollaped=false
IsEnableWindowsFirewallChecked=true
```

Reading some other issues, it seems that problem might be resolved in v3.
However, maintainers of SimpleWall at [Chocolatey](https://chocolatey.org/packages/simplewall ) are unlikely to package the latter until it's out of Beta.

**Comment by henrypp** [comment]
Yes, this bug was already resolved in v3 and i see that the latest v3.0.3 are almost stable and i think to release new version soon!
