### ISSUE TITLE
[REQ] Minor GUI improvements 

### ISSUE THREAD

**Issue by Clouds123** [henrypp/simplewall#500]
- If one or more rules are selected and they are either all enabled or all disabled, then the right-click context menu should only show either Disable or Enable, rather than showing both options (or one should be disabled and greyed out). When the selected items are a mixture of enabled and disabled, both menu items should be enabled/visible.
- If a rule is created from the tray notification that uses one of the default user/special rules, the rule is created and enabled but the checkbox is not checked. Also, it doesn't appear to be possible to just uncheck the rule to disable it (I know you have to disable the special user rule). It would be nice if you could disable an app without the need to disable the special rule (obviously, disabling the special rule would disable any apps that use it, assuming that's the only rule they have)
- Can you add toolbar buttons for "Edit rules" and "Create rule..."
- Can you add "Allow Once", "Block Once" and "Allow for Session", "Block for Session" (Session is until a reboot, so you could also name them "Allow/Block until reboot")
- On Apps tab listview, you have section titled "Apps with special rules (1/6)", but the tab where these rules are defined is called "User rules" - To avoid confusion, can you either rename the section title to "Apps with user rules (1/6)" or the tab to "Special rules"

**Comment by henrypp** [comment]
> If a rule is created from the tray notification that uses one of the default user/special rules, the rule is created and enabled but the checkbox is not checked. Also, it doesn't appear to be possible to just uncheck the rule to disable it (I know you have to disable the special user rule). It would be nice if you could disable an app without the need to disable the special rule (obviously, disabling the special rule would disable any apps that use it, assuming that's the only rule they have)

What version? 3.0.3 works well with that

**Comment by Clouds123** [comment]
Yes 3.0.3. However, it is same with 3.0.4.

> If a rule is created from the tray notification that uses one of the default user/special rules, the rule is created and enabled but the checkbox is not checked.

Shouldn't the checkbox be checked once the rule has been created via tray notification that uses one of the default user/special rules ?

**Comment by henrypp** [comment]
checkbox for the or what?


------ Исходное сообщение ------
От: Clouds123 <notifications@github.com>
Отправлено: August 2, 2019 4:16:19 PM UTC
Кому: henrypp/simplewall <simplewall@noreply.github.com>
Копия: Henry++ <support@henrypp.org>, Comment <comment@noreply.github.com>
Тема: Re: [henrypp/simplewall] [REQ] Minor GUI improvements  (#500)

Yes 3.0.3. However, it is same with 3.0.4.

> If a rule is created from the tray notification that uses one of the default user/special rules, the rule is created and enabled but the checkbox is not checked.

Shouldn't the checkbox be checked once the rule has been created via tray notification that uses one of the default user/special rules ?




-- 
www.henrypp.org | github.com/henrypp

**Comment by Clouds123** [comment]
I thought the checkbox on the left meant the rule was either  enabled or disabled, but when using a special/usel rule, the rule is created with the checkbox disabled, even thoug hthe rule seems tobe enabled. Expected behaviour: When the new rule is created using a user/special rule, the chebox shouldnbe checked/enabled by default. Enabling/Disabling the rule with the wcheckbox should meanthat it doesn't apply to that process.

**Comment by henrypp** [comment]
Now i see - it's just UI bug, rule is enabled and filters are working.

**Comment by ltGuillaume** [comment]
@Clouds123 In the main application list, when the checkbox is ticked, it means "allow all traffic". When it's not ticked, it means "block all traffic". So, if you have a user rule that allows specific traffic for the application, you should leave the checkbox __unticked__, otherwise, you would still allow all traffic, no matter what the user rules are.

If you use a user rule for the app to _block_ specific traffic, you can tick the checkbox to allow all other traffic.

@henrypp Hopefully, I explained this correctly?

**Comment by henrypp** [comment]
@ltGuillaume thank you for your explanation!

**Comment by Clouds123** [comment]
Thanks @ltGuillaume - that makes it clear.

@henrypp - To make the GUI more intuitive, can you change the listview group/section headers text to something like....
1. "ALLOW all traffic for these apps" instead of "Enabled apps"
2. "BLOCK all traffic for these apps" instead of "Disabled apps"

You could also maybe split the "Apps with user rules" group/section into two separate groups:

"ALLOW all traffic for these apps EXCEPT for specified user rules"
and
"BLOCK all traffic for these apps EXCEPT for specified user rules"

Also, possibly remove the option View > Enable group of user rules, as the above changes make it redundant.

**Comment by ltGuillaume** [comment]
"Allowed apps" and "Blocked apps" would suffice I think 😃
