### ISSUE TITLE
simplewall+adguardhome

### ISSUE THREAD

**Issue by hesss5** [henrypp/simplewall#501]
hi
the problem is no matter what rule i created this appear all the time in log
i created some other rule which appeared in log but seems them working since not loged
https://gist.github.com/hesss5/b73367eef728018dee76ecd417823ae8
and adguard home not working completely example wont log request just log blocked one
i have disable filter enable adguard home then enable filter
network tab show established and listen but not working fully
 
thanks

**Comment by hesss5** [comment]
added HTTP  rule generate some more log so created more rule
its work better now no need to disable filler of simplewall
just sometimes seems need restart AH
above log sometimes appears again 
so close issues

**Comment by hesss5** [comment]
the above log still appear when install  adguardhome as service
and cause adguardhome wont log unfiltered request
can anybody help on this?

i created manually rule for 0.0.0.0 too
but in network tab when try create rule for it it just add port number
![screenshot 2019-07-20 002](https://user-images.githubusercontent.com/23487445/61579413-ecfc4a80-ab19-11e9-8d92-3b38e1b2b335.png)

**Comment by hesss5** [comment]
its appear with new beta 3.0.5 problem solved
created some other rule and dont see anything related in log file
so far working
thank you

**Comment by hesss5** [comment]
oops not working yet
https://gist.github.com/hesss5/4565530ac41ebdce6e713948d30b07d3
shouldn't be work just by put it in  enabled app?
unticked outbound unbound for all connection,allowed loopback still happen
sorry

**Comment by henrypp** [comment]
`"FireWall ALE Classify","#471752"` is not simplewall rule
