### ISSUE TITLE
Missing and not translated Russian translation lines in the file simplewall.lng

### ISSUE THREAD

**Issue by REKTSTEADY** [henrypp/simplewall#508]
In the latest version of the language pack, there are not translated and/or missing Russian translation lines.
Here is a list of them:
008=Удалить приложения с ошибками
034=Лог сброшенных пакетов
037=Добавить процесс
038=Добавить приложение
039=Добавить сервис
056=Белый список (разрешить отмеченные)
057=Чёрный список (заблокировать отмеченные)
085=Область применения правила
100=[%s] "%s" для выбранных приложений
153=Предустановленные правила для системных приложений и протоколов.
154=Пользовательские правила. <a href="%s">Справка по редактору правил</a>.
155=Создать правило для "%s" адреса
156=Создать правило для "%d" порта
157=Отключить уведомления для этого приложения
158=Создать специальное правило для открытия доступа к адресу или порту к этому приложению.
163=Сменить режим работы на "%s"?
171=%d выделено
201=Ошибки

It would be great to fix in the new version of the language pack, otherwise I have to edit after each update. Thank you!

**Comment by henrypp** [comment]
Hello, this lines is for 2.x versions, in 3.x this does not required. If you need it, you can replace missing strings and i am approve it!

**Comment by REKTSTEADY** [comment]
Well, I added the missing and not translated lines in simplewall.lng https://github.com/henrypp/simplewall/commit/6952c2a8e56343feac197f9adfc7f745dfcf8cbd
