### ISSUE TITLE
Issues with Find (Ctrl+F)

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#511]
It's great to have the Find... feature back in v3!

In v3.0.5, there are two issues with it, though:
1. Filling in something and then pressing Enter does not start the search, but actually behaves like pressing Enter on the active list item. So, in _Apps_ it opens the folder to the application, and in the rules tabs it opens the rules editor. Pressing Enter _should_ be like a click on the "Find next" button.
2. It only matches the _beginning_ of the string: if I search for "fire", it will find "firefox.exe", but if I search for "fox", it will **not** find "firefox.exe".

**Comment by ltGuillaume** [comment]
Furthermore, it would be really nice if the search "wrapped around" the list, in other words "if at the bottom of the list, continue searching from the top when pressing Find Next"

**Comment by henrypp** [comment]
1. Find dialog does not support hotkeys
2. Done!
3. Done!

**Comment by ltGuillaume** [comment]
1. If that were true, then Alt-F wouldn't work either, but it does. Also, Space on buttons and Tab work. I don't think I've ever seen a Find dialog like this that doesn't support Enter to find the next item when the cursor is in the input field, to be honest.
2. Thanks! Confirmed working 😁
3. Thanks! Confirmed working 😁
