### ISSUE TITLE
Network tab completely empty for minutes when using IKEv2 VPN connection

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#515]
I just found out that after simplewall starts while I'm connected to a VPN, no connections are shown in the Network for at least a minute.

The refresh rate of the Network tab seems to be over a minute. I think it's fine that it doesn't refresh often (otherwise it would only drain resources), but is there a way to manually do a refresh for the Network tab?

**Comment by henrypp** [comment]
Try to disable "resolve nework addresses".
There is nothing unusual - resolving addresses is processed in a same thread (synchronous).
