### ISSUE TITLE
(Feature Request)-Block All Option

### ISSUE THREAD

**Issue by Ct4u2** [henrypp/simplewall#519]
Henry,

I took a look at the latest version 3.05 Portable & noticed
you have no **Change Mode to Block All Option** when you click on the 
SimpleWall Icon in the System Tray. For me this is  the only thing
that is missing before I jump ship to  using your Firewall.

All the Firewalls I have tried so far have had this option.

I find this very usefull when I am not using my computer I want
all Incoming & Outgoing Traffic Blocked, Otherwise I would have to
unplug the ethernet cable everytime.

For examples you can take a look at Tinywall & Windows Firewall Control.

Thank You.

**Comment by Clouds123** [comment]
+1

Was going to request exactly this feature myself to quickly block all traffic.

**Comment by asvc** [comment]
```powershell
Disable-NetAdapter -Name "wan"
```

Would do the trick. [Check the docs](https://docs.microsoft.com/en-us/powershell/module/netadapter/disable-netadapter).
