### ISSUE TITLE
Remove the Folder isn't detected by SImpleWall

### ISSUE THREAD

**Issue by CHEF-KOCH** [henrypp/simplewall#52]
**What happend?**
* Remove the SimpleWall folder
* You see the GUI is still running but it doesn't recnorize that it's deleted. 

**Expected behavior**
* SimpleWall should detect that you want the folder and prevent this to avoid manipulations and to avoid problems, especially on restarts.

**Comment by henrypp** [comment]
> You see the GUI is still running but it doesn't recnorize that it's deleted.

I don't see anything, especially your computer configuration.

**Comment by CHEF-KOCH** [comment]
Did you ever test it before closing it?

**Comment by henrypp** [comment]
Yes. It's impossible to remove folder of ANY running executable.

**Comment by CHEF-KOCH** [comment]
Dunno what you're not understand when I write simplewall doesn't detect folder deleting. Actually you can remove the folder while the executable is running in the  background which is not an expected behavior. 


Well I give up you're an ignorant person which never checks his own product, I cant recommend this project to anyone in his right mind. Besides 100 bugs, memory hooks and leaks it's the ignorance which posses me off.

**Comment by henrypp** [comment]
> Actually you can remove the folder while the executable is running in the background which is not an expected behavior.

Actually it impossible. This is a really strange to hear from person who worked for microsoft over 15 years, really!

**Comment by CHEF-KOCH** [comment]
It's called memory hook, maybe you install process explorer and see for yourself. 

It's not in I'd ticket just bad coding here and others can configure this as well cause it's related. 

Closing video tickets makes it not gonna fix neither has this something to do with my PC or windows configuration the reported slowdowns are a result of that - you not know how to code.

**Comment by henrypp** [comment]
> Besides 100 bugs, memory hooks and leaks it's the ignorance which posses me off.

Ye, ama bad boy ;)

> Closing video tickets makes it not gonna fix neither has this something to do with my PC or windows configuration the reported slowdowns are a result of that - you not know how to code.

You can remove folder of running executable and i have marked as bad coder, okay.
