### ISSUE TITLE
Support domains in notification window

### ISSUE THREAD

**Issue by savchenko** [henrypp/simplewall#520]
As an example, LittleSnitch notification:
![decide-immediately](https://user-images.githubusercontent.com/300146/63024372-3c018980-bee6-11e9-8a16-dfdef5a4707b.png)
It allows user to choose between the two vital options:

1. Allow access anywhere in the world
2. Restrict access to the selected domain

It would be a huge boost in UX experience if SimpleWall could allow the same level of decision-making straight from the notification window.

Given that ability to use domains in rules is already implemented, what would it take to introduce domain-level granularity to the rest of UI?

**Comment by StrikS** [comment]
Very useful if you want to give applications access only to the IP you expect. 
Especially handy when the likely domain the IP belongs to is listed next to it. This allows you not to search for IP information through third-party web sites.
As an example of this output:
https://github.com/evilsocket/opensnitch/issues/321

**Comment by StrikS** [comment]
I found a way to see the domain next to the ip. It turns out there is such a possibility:
![изображение](https://user-images.githubusercontent.com/15943769/124063644-bee54c00-da4c-11eb-83f9-2504d94b766a.png)

**Comment by henrypp** [comment]
done
