### ISSUE TITLE
Time synchronization does not work

### ISSUE THREAD

**Issue by sergejk74** [henrypp/simplewall#521]
Isn't there time in the "White list".

**Comment by henrypp** [comment]
System rules named by protocols and Time synchronization is have NTP name, thats what you need.

**Comment by asvc** [comment]
@sergejk74 , alternatively, you can allow `svchost.exe`to connect via UDP on p123 to the NTP server of your choice.

**Comment by ptkovsky** [comment]
Can you please elaborate on why is NTP blocked by default? Is there a potential security threat?
