### ISSUE TITLE
App rules self-delete on reboot

### ISSUE THREAD

**Issue by 7MXek** [henrypp/simplewall#522]
On the occasional reboot, simplewall will have deleted it's stored apps.yml and I will have to restore from backup. I haven't yet noticied any trigger besides rebooting and I'm not doing anything out of the ordinary to delete these myself. I'm running Windows 10 LTSC 2019 version 1809. Anyone else have this issue?

**Comment by henrypp** [comment]
Duplicate https://github.com/henrypp/simplewall/issues/391#issuecomment-491314105
