### ISSUE TITLE
"_r_reg_query..." not found

### ISSUE THREAD

**Issue by DaPa** [henrypp/simplewall#523]
They were introduced in the "updated project sdk" commit 5 days ago, but seem the routine has not been updated. Can you please check?

Trying to build current master fails with:
simplewall\src\helper.cpp(1836): error C3861: '_r_reg_querybinary': identifier not found
simplewall\src\helper.cpp(1868): error C3861: '_r_reg_querystring': identifier not found
simplewall\src\helper.cpp(1889): error C3861: '_r_reg_querystring': identifier not found
simplewall\src\helper.cpp(1892): error C3861: '_r_reg_querytimestamp': identifier not found
simplewall\src\helper.cpp(1979): error C3861: '_r_reg_querystring': identifier not found
simplewall\src\helper.cpp(1982): error C3861: '_r_reg_querytimestamp': identifier not found
simplewall\src\helper.cpp(1997): error C3861: '_r_reg_querystring': identifier not found
simplewall\src\helper.cpp(2001): error C3861: '_r_reg_querytimestamp': identifier not found
simplewall\src\notifications.cpp(505): error C3861: '_r_reg_querystring': identifier not found

**Comment by cengiz7** [comment]
I am having the same errors. Up!
