### ISSUE TITLE
Not clear on why default blocked System32 apps are blocked by default

### ISSUE THREAD

**Issue by FallenSpaces** [henrypp/simplewall#524]
I feel like this should be added in the docs. 

I could google each file, but that would be a pain, because knowing what the file is doesn't necessarily tell me why the dev has chosen to block the app by default.

**Comment by asvc** [comment]
Why do they need to be unblocked in the first place? Who are _they_?..

**Comment by henrypp** [comment]
Block everything, except required protocols/loopback addresses, is a paradigm of simplewall. Allow/block or set [custom rule](https://github.com/henrypp/simplewall/wiki/Rules-editor) decision is always on user.

NB:
![nb](https://user-images.githubusercontent.com/3902025/63755695-ef03b700-c8d8-11e9-9eca-1688e61e3ffb.png)
