### ISSUE TITLE
[Future request] Install for All Users

### ISSUE THREAD

**Issue by Rehorek** [henrypp/simplewall#525]
@henrypp Thank you for this great application. I'd like you ask you if you're going to add use for  Standard user or maybe there is a simple solution for me. I work on standard user and every time I logging in I need to launch SimpleWall and enter admin credentials. Is there a simpler method or new feature has to be implemented :-) ?

**Comment by bitpixl** [comment]
Hi, I also work with standard user rights (as everyone should!) and my solution is a simple batch script.
Replace '!!!' with your admin name (no spaces) and verify if the simplewall installation folder is correct ('ProgramW6432' = the buildin variable for 'c:\program files') on Windows 10, unless you installed windows on your 'D' drive/partition or something). The /savecred will store your admin password in the Windows Credential Manager (locally on your system) and will not ask you again for the password the second time you run this script or any other script also using the line %windir%\system32\runas.exe /user:%admin% /savecred "<path\<exe>" It will retrieve it from the credential manager.

`
@echo off
cls
set admin=!!!
set loc=%ProgramW6432%\simplewall
set exe=simplewall.exe

%windir%\system32\runas.exe /user:%admin% /savecred "%loc%\%exe%"

exit 0
`

Open your notepad/text editor and copy the code in a new document. Save the document for example as "simplewall.cmd" (make sure it doesn't save as "simplewall.cmd.txt". Then simply doubleclick on simplewall.cmd to start the firewall.
