### ISSUE TITLE
Rules remote local limit !?

### ISSUE THREAD

**Issue by Wizzergod** [henrypp/simplewall#528]
Hi, can you show how many rules in remote and local can do and can pls replace text to list edit rule remote and local
![Screenshot_1](https://user-images.githubusercontent.com/6242208/64439359-74098000-d0d2-11e9-99bb-0ba406b09f3e.png)

**Comment by henrypp** [comment]
every rule limit is is equal to 256 chars, do you calculate how rules is can be assigned for 1 rule by yourself?
