### ISSUE TITLE
simplewall cant find correct battlenet location (whitelist)

### ISSUE THREAD

**Issue by razzor1984** [henrypp/simplewall#529]
System:
Window 10 64bit
8 core CPU
32Gb Ram

Application:
Simplewall: 2.4.6 - 64bit

**What the application does:**

When i will start battlenet simplewall is asking if it should let it out. 
But the source location is wrong. Simplywall defines it via mouse over C:\battlenet ......
The real location is the Hard-drive F - F:\Battle.net\Battle.net Launcher.exe

https://ibb.co/QdhVxWX

**What the application should do:**

When i start battlenet, simplewall is asking if it should let it out. I will accept it, and it goes into my whitelist.

What did i do:
Uninstalled battlenet 3 to 4 times. Wiped caches with BleachBit - nothing worked

Best regards Razzor

**Comment by henrypp** [comment]
> But the source location is wrong. 

You do not have file on C:\battlenet ......, or what?

**Comment by razzor1984** [comment]
Yep nothing there, but simpleywall always says that the file is there and via mouse over it is saying it isn't.

**Comment by henrypp** [comment]
and old version 1.x has bug, it was cannot define right drive letter, but 2.x was fixed this behaviour.
now i am interested, what kind of type of your drive where files are located? i can suggest you to use v3.x of SW, but i did not, because i did not understand where is the problem here!

**Comment by razzor1984** [comment]
I upgraded to the RC version as mentioned. That fixed oddly my problem with battle net, but now its blocking my games. They are all located in new NVME SSD under F:

The log:
"‎07.‎09.‎2019 ‏‎20:20:47","DESKTOP-xxxxx","C:\overwatch\_retail_\overwatch.exe","xx.xxx.xx.xx","11xx (bnetgame)","tcp","simplewall\BlockConnectionsV4","#1643xxxx","Outbound","Blocked"
"‎07.‎09.‎2019 ‏‎20:22:36","DESKTOP-xxxxx","C:\overwatch\_retail_\overwatch.exe","xx.xxx.xx.xx","11xx (bnetgame)","tcp","simplewall\BlockConnectionsV4","#164xxxx","Outbound","Blocked"

The my initial problem:
When i start the application overwatch which is located under - F:\overwatch\_retail_\overwatch.exe
Simplywall asks me, to grant it access to the internet, but that doesn't work because the path to the exe is wrong --> Simplywall always logs C:\overwatch\_retail_\overwatch.exe as the source path

**Comment by henrypp** [comment]
Task manager is also says that process started as "F:\overwatch_retail_\overwatch.exe", or anything different as SW says, hmm?

**Comment by razzor1984** [comment]
Same path as i said - https://ibb.co/Y3DQbHq

**Comment by henrypp** [comment]
v3.x is resolve this problem, yes?

**Comment by razzor1984** [comment]
For battle net it fixed it, but the game over watch sadly not.
Simplywall still uses the wrong path to the game 
It still thinks its under C: - the corret path is https://ibb.co/Y3DQbHq  which Process Explorer also shows. Its like Simplaywall is getting a wrong path for this exe ......

**Comment by henrypp** [comment]
Check app list:
- remove unused apps in SW
- start required app
- try to find app in the list
- ...

use v3.x for all of this

**Comment by razzor1984** [comment]
I did remove unsed apps in simpleywall.
Started the required app - Overwatch
Found it in the list (was red because, Simplywall can't find the exe ) - still under the wrong path C:overwatch\overwatch launcher.exe
https://ibb.co/Kw4BzzZ

Is there a option to manually edit the patch for the this exe?
Why is Simplywall getting an old path? even when start the application, its getting the wrong patch to the exe.

**Comment by beerisgood** [comment]
I use battle.net too and never see this problem. Nor with new 3.x or with old 2.x

Did you try a clean simplewall ?

**Comment by razzor1984** [comment]
@beerisgood - I did a clean install of simplewall. After that i restored my settiungs via profile.xml import.
Nothing changed.
Do you use batte.net and the concerning games at the default location (C:) ?

**Comment by henrypp** [comment]
it's maybe device path resolver bug, and probably fixed on next release soon.

**Comment by Chaython** [comment]
Henry was correct in referencing this and closing my issue. Sorry about the duplicate issue.
His last message is likely the suitable fix, thanks.
Just recapping what happened to me, for the OP.
Every program in c:\ is being found on drive b:\ over time and being marked invalid immediately though it's on drive c:\
this started happening after plugging in a USB drive, windows derped and relabeled d:\ to e:\ [I since renamed my HDD to b:\ so the error would not happen again] though this started happening for every application on c 
Thanks for your hard work, @henrypp !
