### ISSUE TITLE
High CPU load from svchost (CDPUserSvc) with blocked "spy" IP

### ISSUE THREAD

**Issue by xnoreq** [henrypp/simplewall#531]
Hello,

I noticed that "svchost.exe -k UnistackSvcGroup -s CDPUserSvc" causes 100% CPU load on one core.

It seems to be stuck in a loop trying to connect to 52.157.234.37:https. This is a "spy" IP blocked by default by simplewall.

The service also reads/writes to a db at:
C:\Users\<user>\AppData\Local\ConnectedDevicesPlatform\<some hex key>\ActivitiesCache.db

Does anyone have further infos on this service and how to disable it?

**Comment by henrypp** [comment]
[It's another "good" service for шindows](https://superuser.com/questions/1115769/what-is-the-cdpusersvc-service).

**Comment by durillo** [comment]
Xnoreq , i fixed this Windows "issue".
You can follow the next guide. 
https://appuals.com/how-to-fix-unistack-service-group-unistacksvcgroup-high-cpu-or-memory-usage/

Regards
