### ISSUE TITLE
Requesting new feature..

### ISSUE THREAD

**Issue by rubysm** [henrypp/simplewall#532]
Hello henry can u add dns blocking to simplewall so we can block induvidual domain name without competely blocking the whole applcation and adding the option to see the request made by the application will be helpful..

**Comment by henrypp** [comment]
It's already done https://github.com/henrypp/simplewall/wiki/Rules-editor

**Comment by rubysm** [comment]
How to see the individual request made by the application like wireshark and how to block
them induvidually..

**Comment by henrypp** [comment]
All network requests is displayed in dropped packets log.

ps: SW is not Wireshark
