### ISSUE TITLE
Instructions for building?

### ISSUE THREAD

**Issue by Workings** [henrypp/simplewall#533]
Not sure if just being dim, but cannot find any instructions for building. Worked out need your routine project and pugixml cloned, but now missing _r_str_isempty. Bit concerned this open source project is not completely open source.

**Comment by henrypp** [comment]
> Worked out need your routine project and pugixml cloned, but now missing _r_str_isempty. Bit concerned this open source project is not completely open source.

You don't know what is commit history for?

**Comment by henrypp** [comment]
#523
