### ISSUE TITLE
Notifications broken after PC crash.. 

### ISSUE THREAD

**Issue by charliechan231** [henrypp/simplewall#534]
Hello, I recently had a PC crash which I believe was caused by high cpu usage from some video editing I was doing. I tried connecting a usb device during this cpu spike and my computer froze so I reset. After the restart however I got a message from simplewall that "an error occurred". The log shows "FwpmEngineSetOption()","0x00000005","FWPM_ENGINE_COLLECT_NET_EVENTS","2.4.6" and any network connections and even usb devices only prompt the same "an error occurred" message. I have to manually add apps and programs to the whitelist to allow connection.

I have tried reinstalling but the error persists even after a fresh install. Any programs that try to connect generate the error message instead of the program name and option to block/allow, so I don't even know which programs are trying to connect or their location. Do you think my PC crashing caused a problem for simplewall in the registry perhaps? since uninstalling/reinstalling didn't fix it.
My system is Windows 10 64bit, i7 3.40GHz 16gb ram. Windows version 1903.

**Comment by henrypp** [comment]
2.4.6 is unstable. Use v3
