### ISSUE TITLE
Apps constantly cloning and making the previous invalid

### ISSUE THREAD

**Issue by Chaython** [henrypp/simplewall#535]
Apps constantly cloning and making the previous invalid
![image](https://user-images.githubusercontent.com/6486343/65376417-c0b99300-dc5c-11e9-9fed-43ee0ea3c73b.png)
![image](https://user-images.githubusercontent.com/6486343/65376425-d29b3600-dc5c-11e9-8443-f4bff6146743.png)
![image](https://user-images.githubusercontent.com/6486343/65376441-0d04d300-dc5d-11e9-8dbc-5ed1af7a5a43.png)
I will check back in several hours and then there's like 20 invalid apps
These screenshots are seconds apart
This seems to have been happening for a couple weeks, since I plugged in a USB drive and windows derped swapping my D:\ to E:\ though these are all applications on C:\. I have tried deleting the simplewall and unpacking another portable to no avail.
3.0.5

**Comment by henrypp** [comment]
I think it's duplicate, here is the same problem #529
