### ISSUE TITLE
Simplewall forgets all my rules

### ISSUE THREAD

**Issue by DaveHuman** [henrypp/simplewall#536]
Twice now I've booted up Windows to discover that Simplewall's rules list is empty.

So then, of course, it pops up with dozens of confirmation boxes for me to allow or block apps.

I was hoping it was a one off, but it happened again this evening.

Anyone else seen this?

**Comment by henrypp** [comment]
Duplicate https://github.com/henrypp/simplewall/issues/391#issuecomment-491314105
