### ISSUE TITLE
View local and remote ip+port

### ISSUE THREAD

**Issue by agiz10** [henrypp/simplewall#537]
Windows 10, simplewall 3.0.5
In "Network alert" popup, can i somehow make source ip:port and destination ip:port visible? Right now i can see only remote ip+port. It would be much clearer what is connecting where.
Iirc this is visible in v2.4.6.
Thank you for awesome software.

**Comment by henrypp** [comment]
local port/ip view was returned in 3.0.6 (tba), but only for logs (not a notifications).
thats all!

**Comment by agiz10** [comment]
Thanks. 👍 
If it makes sense to you and is not too much work, it would be appreciated in notifications as well. It is often hard to see what is trying to connect where as you already did a rule that covers certain app just to find out later that you opened wrong thing.
