### ISSUE TITLE
simplewall not auto-starting

### ISSUE THREAD

**Issue by leuldereje** [henrypp/simplewall#539]
Every time my laptop reboots or shutdown, I have to manually open simplewall because it doesnot auto start with windows on boot. If I don't open simplewall then none of my app will work (connect to the internet) until I run simplewall. how can I fix this?

**Comment by helpfulBrother** [comment]
I had this issue, turned out to be some broken tasks in the windows task scheduler preventing other items loading at startup.

Not sure if this is your issue too. What OS are you using?

**Comment by henrypp** [comment]
> If I don't open simplewall then none of my app will work (connect to the internet) until I run simplewall.

It's not true - filters are working even SW is not running.

**Comment by henrypp** [comment]
dup #336
