### ISSUE TITLE
Notification window [UI]

### ISSUE THREAD

**Issue by pwn0r** [henrypp/simplewall#54]
New notification window is much better than in the previous version, much appreciated.

However there are a couple of UI logic problems still there. 

First, it is not very clear what exactly **Allow** and **Block** actually do. It appears that Block does nothing (keeps blocking as before or actually nothing?) and Allow will actually check the app in the main window (i.e. enables everything for that app). I reckon many users can make an easy mistake here -- for instance clicking on disable notifications and then allow instead of disable. 

There are a couple of allow options to create a new custom rule, which is very convenient, however there are no options to create a custom blocking rule. E.g. I might want to block that particular IP address but allow the app to access the rest of the internet. 

Suggestion:
I think the best way around it would be to create block or allow custom rule based on the button clicked i.e. "Allow" or "Block". Of course the options text would need to be reworded for that. 

I.e. **Create a custom rule for .... address** and then subject to the button clicked the allow or block rule is created. 

In the current scenario the UI logic is broken -- because currently you select e.g. Allow rule by IP and then click on **Block** and that does nothing, apparently.

**Comment by henrypp** [comment]
2..0.3b fixed this ui bug (check latest 2.0.4)
