### ISSUE TITLE
3.0.6 RC - same internal rules update prompted upon windows startup

### ISSUE THREAD

**Issue by callmenemo491** [henrypp/simplewall#543]
i installed:  simplewall-3.0.6

on startup, the program prompts me with an update:
- update available. download and install now?
internal rules 9/2/2019 5:36 PM

![image](https://user-images.githubusercontent.com/13878580/67013003-585fb380-f12d-11e9-9eb9-f4ab9e85a091.png)

i click "Yes", and this is shown:

![image](https://user-images.githubusercontent.com/13878580/67013030-64e40c00-f12d-11e9-9730-714c45e3f85e.png)

if i reboot PC, it will appear again on startup (Win10)

**Comment by narayagh** [comment]
Same thing happens to me on Win7.

**Comment by henrypp** [comment]
Hi, i know about this bug, it's fixed!

**Comment by haudi** [comment]
FYI: this is also the case for the language file update (published on 15.10.2019).
