### ISSUE TITLE
notification window issue in 3.0.6

### ISSUE THREAD

**Issue by Scordem** [henrypp/simplewall#544]
Windows10 x64 18362.418
simplewall 3.0.6

There is a problem that the text in the notification window is not displayed in 3.0.6.
3.0.5 is no problem.

**3.0.5**
![3 0 5](https://user-images.githubusercontent.com/56701141/67050084-aa76f800-f172-11e9-9d5d-9176f0b5d442.png)

**3.0.6**
![3 0 6](https://user-images.githubusercontent.com/56701141/67050155-d7c3a600-f172-11e9-9d59-d558fb47f7ae.png)

**Comment by Scordem** [comment]
No. I keep default DPI. (100% 96dpi)

**Comment by henrypp** [comment]
how about 3.0.7?

**Comment by Scordem** [comment]
Windows10 x64 18362.449

Many thanks for your reply.
I tested 3.0.7.
Same as before (3.0.6).

**3.0.7**
![3 0 7-1](https://user-images.githubusercontent.com/56701141/68061742-b99c9f00-fd49-11e9-8feb-d6e2a47c4cce.png)
![3 0 7-2](https://user-images.githubusercontent.com/56701141/68061750-c1f4da00-fd49-11e9-96ce-ec3c82d7ff92.png)

**Comment by tokariu** [comment]
I have the same issue on v3.0.7 on win7.

see:
![2019-11-02_21-01-32](https://user-images.githubusercontent.com/7195846/68076898-2ac86a80-fdbb-11e9-8ce2-3a874d6a4186.png)

**Comment by tokariu** [comment]
btw: using non-default system dpi. dpi levels of 115 and 125%
happens on win10 and win7
