### ISSUE TITLE
Bypass simplewall with a hidden rule that remains after uninstalling CIS

### ISSUE THREAD

**Issue by Nitimoon** [henrypp/simplewall#545]
Some times ago I used simplewall without any problems. I set up whitelist blocking. What I needed to allow was allowed. Everything else was successfully blocked.
But then I discovered that Psiphon successfully bypasses simplewall.

Psiphon creates a local proxies on a host (HTTP with CONNECT method? and SOCKS5) when connected to its network.
Psiphon creates another process in the folder (example):
**C:\Users\UserName\AppData\Local\Temp\psiphon-tunnel-core.exe**

**"psiphon-tunnel-core.exe"** goes on the Internet.
**"psiphon3.exe"** does not go to the Internet.

**"psiphon-tunnel-core.exe"** has been added to the blacklist!
But Firefox successfully goes to Internet through Psiphon (in this situation, Firefox goes to Internet through the local Psiphon proxy 127.0.0.1:PortNumber).
Adding Firefox to the blacklist obviously will not help, because there is a rule allowing loopback connections.
**"psiphon-tunnel-core.exe"** goes to the Internet, despite being in the blacklist!
Simplewall filtering has been enabled (obviously), Windows default firewall disabled.

Fortunately, simplewall has the ability to enable logging.
That's some things was in those logs:

From simplewall 2.4.6
`"‎22.‎10.‎2019 ‏‎2:05:03","HomePC\UserName","C:\users\username\appdata\local\temp\psiphon-tunnel-core.exe",213.5.71.217:53 (Remote),192.168.0.100:64447 (Local),UDP,"COMODO ConnectV4",#82691,OUT,ALLOW`

From simplewall 3.0.5
`"‎13.‎09.‎2019 ‏‎2:19:26","HomePC\UserName","C:\users\username\appdata\local\temp\psiphon-tunnel-core.exe","212.71.235.155","53 (domain)","udp","COMODO ConnectV4","#82691","Outbound","Allowed"`

From simplewall 3.0.6
`"‎22.‎10.‎2019 ‏‎2:43:32","HomePC\UserName","<empty>","192.168.0.100","58726","213.5.71.217","53 (domain)","udp","COMODO ConnectV4","#82691","Outbound","Allowed"`

It can be noted that in simplewall 3.0.6 log record, the process path is `"<empty>"`.

I was surprised that there is the "COMODO ConnectV4" rule that should not be here.
And simplewall does not display this rule.
There
https://github.com/henrypp/simplewall/wiki/FAQ
in that section
**"How can i view all installed filters"**
are such commands:
**netsh wfp show filters
netsh wfp show state**

I looked at these files "filters.xml" and "wfpstate.xml".
And found a lot of Comodo rules:
COMODO AssignmentV4
COMODO AssignmentV6
COMODO ListenV4
COMODO ListenV6
COMODO ConnectV4
COMODO ConnectV6
COMODO ResourceReleaseV4
COMODO ResourceReleaseV6
COMODO ClosureV4
COMODO ClosureV6

These rules, apparently, remained after the removal of Comodo Internet Security. I installed Avast at that time.
I began to study about the Windows Filtering Platform (WFP).
I began to look for how it is possible to remove these rules through cmd or at least Powershell.
I have not found such ways.
How can I change and/or delete these rules (filters)?
Changing and deleting these rules can only be done through the Windows API?
Why does simplewall not show these rules when these rules are in effect?
Why does simplewall not show these rules at all?

It can also be a good recipe for malware. You can create a hidden rule like this. And even deleting the executable file of the malware will not help.

Checked these simplewall versions:
2.4.6; 3.0.5; 3.0.6

Windows 8.1 64bit

**Comment by Nitimoon** [comment]
The process "psiphon-tunnel-core.exe" was able to block in this way:
1) Disable default "DNS" rule in "System rules";
2) Create (and enable) custom "DNS_v2" rule in "User rules" with the same settings from original "DNS" rule.
Unbelievable, but it works.

And then the question appears.
Default "DNS" rule allows connections for all applications?
The tooltip shows the paths "System" and "C:\Windows\system32\svchost.exe", but in "Rules editor" window we can see enabled "Enable for all apps" option. "Enable for selected apps" is grayed.
Was there some mistake?
Similar questions arise to other rules too.

**Comment by skycommand** [comment]
@Nitimoon Hello. Today, I ran into an issue similar to yours: Noticed programs connecting through the "COMODO ConnectV4" rule.

Looking for a way to delete these invisible filters (that you mentioned above,) I found [Windows-Kernel-Explorer](https://github.com/AxtMueller/Windows-Kernel-Explorer). It can delete WFP rules.

Please exercise utmost caution while using it. Be sure to back up at least your boot and system partitions in advance.

**Comment by Nitimoon** [comment]
@skycommand Hello. :) Thank you so much for finding this tool [Windows-Kernel-Explorer](https://github.com/AxtMueller/Windows-Kernel-Explorer)! I will try this app for a few days. Thank you for the warning about using this tool. I'll take that into consideration. Still, simplewall should be able to view and change all the WFP filters and rules. Otherwise, this will happen when some program will be able to add WFP rules that simplewall will not see.
