### ISSUE TITLE
Does simplewall block government connections?

### ISSUE THREAD

**Issue by Totom777** [henrypp/simplewall#548]
Hello,
I live in France and the download is illegal (protected by Hadopi).
I would like to know if simplewall automatically blocks the security connections of governments, French in particular.
If no, could you tell me how to proceed?
PS: I download a lot of torrent and P2P I do not want to get caught.
Sincerely, Tom.

**Comment by asvc** [comment]
> PS: I download a lot of torrent and P2P I do not want to get caught.
> Sincerely, Tom.

Perhaps slow down and have a deep thought on how your life choices coincide with your actions.

**Comment by beerisgood** [comment]
I don't think you know how stuff works. A firewall, no matter if hardware or software can you protect against what you search here.  

Also I don't think and hope that you got here any help for your illegal torrent
Just stop using that crap
