### ISSUE TITLE
Copy rules from Windows Firewall to SimpleWall

### ISSUE THREAD

**Issue by SoyRA** [henrypp/simplewall#551]
I'm testing SimpleWall on a VM and a small question arose: if it is able to put in SimpleWall the configuration that [MM Server Picker](https://gamebanana.com/tools/5684) is going to try to put in the Windows Firewall.
&nbsp;&nbsp;\* Two other options I tried are [CSGO Routing Tool](https://gamebanana.com/tools/6253) and [Steam Route Tool](https://gamebanana.com/tools/6667) (functional or not for CS: GO, they were the first thing that occurred to me to perform a test like this :P ).

And no, that didn't happen. It directly put everything in the Windows Firewall and that's it.
I know I can take the trouble to check and manually put it in SimpleWall (because I don't know if there's an automatic way) **but...**_would it be possible to implement something like that?_ That SimpleWall would be able to detect these requests and ask the user to accept them or not.

I hope I explained this right. :P

**Comment by henrypp** [comment]
>but...would it be possible to implement something like that?

never

**Comment by SoyRA** [comment]
> never

Ok. 😭
