### ISSUE TITLE
3.0.7 silently crashes 

### ISSUE THREAD

**Issue by asvc** [henrypp/simplewall#552]
Latest stable Win 10:
```powershell
[Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0
```

v.2.4.6 was working fine (albeit known bug that caused high CPU usage), while v3.0.7 seems to crash at random, without any sort of user-facing error minutes after launch.

Considering that it is labelled as "release" after several alpha/beta iterations, I was expecting it to be at least as stable as v2.X branch. Am I missing something?

**Comment by perdolka** [comment]
>  v3.0.7 seems to crash at random

+1

**Comment by Hitrate** [comment]
+1 WHERE CAN I DOWNLOAD THE PREVIOUS VERSION ?!

**Comment by perdolka** [comment]
@Hitrate https://github.com/henrypp/simplewall/releases/tag/v.3.0.6

**Comment by ViRb3** [comment]
Same here. Seems to crash every time I resume from hibernation

**Comment by ViRb3** [comment]
Possibly related: #557

**Comment by asvc** [comment]
Alright, I have tried v3.0.7 on a freshly installed W10 and it works just fine.

@henrypp , any chance the issue can be related to a set of old rules imported from v2.X.X branch?

**Comment by ViRb3** [comment]
I never used 2.x, started from around 3.0

**Comment by henrypp** [comment]
>any chance the issue can be related to a set of old rules imported from v2.X.X branch?

no

**Comment by henrypp** [comment]
Please check https://github.com/henrypp/simplewall/releases/tag/v.3.0.8

**Comment by Matthaiks** [comment]
When using AnyDesk (remote desktop tool), v3.0.8 crashes on a remote client computer (Windows 10 v1809 x32).
