### ISSUE TITLE
Wildcard-rule for changing application path

### ISSUE THREAD

**Issue by orangebutblue** [henrypp/simplewall#553]
There are several applications that constantly change their application path when they auto-update.

One example is the Windows Defender

C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.1909.6-0\\**msmpeng.exe**

C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.1910.4-0\\**msmpeng.exe**

This is pretty annoying, because everytime it updates, I'll get a new notification asking me to allow/block it.

How can I just setup a wildcard in a rule to allow/block all files in the "C:\ProgramData\Microsoft\Windows Defender\Platform\\*" Parent directory?

**Comment by henrypp** [comment]
dup #463
