### ISSUE TITLE
Windows Firewall off notification

### ISSUE THREAD

**Issue by privacyguy123** [henrypp/simplewall#554]
any way to stop this from happening? ive got nofications for security centre off but its still warning me when simplewall turns it off at startup

**Comment by henrypp** [comment]
Hi,

add this lineIs `DisableWindowsFirewallChecked=false` into `simplewall.ini` and restart SW.

**Comment by cloudgreen** [comment]
@ltGuillaume Does adding the line above in `simplewall.ini ` prevent the Windows 10 notification below?

![image](https://user-images.githubusercontent.com/42112877/69499942-673d4100-0ef7-11ea-8484-329be529a215.png)

**Comment by ltGuillaume** [comment]
No idea, I've never had this notification.

**Comment by cloudgreen** [comment]
That's Windows 10 complaining about Windows Firewall being turned off (since I got Simplewall).

I have been thinking about how to get rid of that... :( I think maybe one of the tips in [this Serverfault thread](url=https://serverfault.com/questions/880639/windows-10-disable-warning-notification-about-disabled-firewall-via-gpo) might do the trick...

**Comment by ltGuillaume** [comment]
Can't you just tell Windows to stop giving those messages in the Security & Maintenance dialog?

**Comment by ltGuillaume** [comment]
@cloudgreen Sorry, I was wrong: the thing is that you can _only_ tell Windows to stop whining about the Defender Firewall's being disabled if you have removed Windows Defender altogether. Otherwise the option is greyed out, so you can't uncheck it.

**Comment by cloudgreen** [comment]
> 
> 
> @cloudgreen Sorry, I was wrong: the thing is that you can _only_ tell Windows to stop whining about the Defender Firewall's being disabled if you have removed Windows Defender altogether. Otherwise the option is greyed out, so you can't uncheck it.

Thanks for following up, @ltGuillaume!

Yeah, there are a lot of different reports around the web about how to turn off the Windows Firewall warning, many include editing Group Policy settings, but many say it doesn't work. Your tip is probably the most likely one to be correct! But I would like to have the cake (Defender) and skip the warning... :)

**Comment by ltGuillaume** [comment]
Yeah, it's ridiculous. Way to go, MS....

**Comment by qupig** [comment]
> Hi,
> 
> add this lineIs `DisableWindowsFirewallChecked=false` into `simplewall.ini` and restart SW.

@henrypp 
I have added the settings to simplewall.ini as follows:
```
[simplewall]
DisableWindowsFirewallChecked=false
LogViewer=.\csvfileview.exe
BackupTimestamp=1583678120
CheckUpdatesLast=1583690026
……
```
But I still get notifications [Turn on Windows Firewall] like https://github.com/henrypp/simplewall/issues/554#issuecomment-557918940
> ![image](https://user-images.githubusercontent.com/42112877/69499942-673d4100-0ef7-11ea-8484-329be529a215.png)

This notification is generated every time the system is restarted. Is this setting lineIs not working? Or do I understand something wrong? Any suggestions to turn off notifications?

**Comment by qupig** [comment]
> Hi,
> 
> add this lineIs `DisableWindowsFirewallChecked=false` into `simplewall.ini` and restart SW.

@henrypp 
I notice that the latest version of `simplewall.ini` already has this line `IsDisableWindowsFirewallChecked = true` Is this the same as `DisableWindowsFirewallChecked` you mentioned?

If I understand correctly, this is the same as the `Turn off Windows Firewall` checkbox when `Enable Filtering`.

I checked `Turn off Windows Firewall`, but the notification warning pops up every time I restart the system and from time to time [Turn on Windows Firewall] like https://github.com/henrypp/simplewall/issues/554#issuecomment-557918940
> ![image](https://user-images.githubusercontent.com/42112877/69499942-673d4100-0ef7-11ea-8484-329be529a215.png)

I found that I cannot turn off this notification in the Windows Notification Center or Security Center. I tried to turn off notifications in the windows firewall settings, but it didn't work, Any suggestions to turn off this notifications?

It pops up often and is accompanied by sounds, very annoying, I can't disable the entire notification center because of this.

**Comment by cloudgreen** [comment]
I have not been able to figure out how to stop the "Windows Firewall turned off" notification, without turning of the entire Windows Defender. (You can remove the sound in System Sounds, though...)

**Comment by qupig** [comment]
@cloudgreen Do you mean to be able to delete sounds for specific app notifications, or delete all notification sounds? Obviously the latter is not the solution we need.

**Comment by cloudgreen** [comment]
> @cloudgreen Do you mean to be able to delete sounds for specific app notifications, or delete all notification sounds? Obviously the latter is not the solution we need.

I meant no system sounds at all, by selecting the "No sounds" sound scheme. (That's how I always roll it.) But my sound comment was merely a small "afterthought", the sound is the least of this problem... :)

I am also interested in getting rid of the Firewall notification message itself.

**Comment by mizzuri** [comment]
Try the following (not a proper solution but ...)

Local Group Policy Editor > Local Computer Policy > Computer Configuration > Administrative Templates > All Settings

Disable the following two policies:

![SharedScreenshot](https://user-images.githubusercontent.com/1288437/80565946-cad41900-8a17-11ea-9dbd-fd99e4b624ff.jpg)

**Comment by ltGuillaume** [comment]
@mizzuri Errr yeah that's not gonna work: it will also cause simplewall's rules to be disabled.

**Comment by mizzuri** [comment]
> @mizzuri Errr yeah that's not gonna work: it will also cause simplewall's rules to be disabled.

Not for me though.  Actually isn't simplewall using its own rules?

**Comment by ltGuillaume** [comment]
I tried to set these policies to disabled on Windows 10 19H2, then tried blocking Ungoogled-Chromium: it still opened all pages I tried. I even refreshed all the rules in simplewall (F5). It was only after resetting the two policies that Ungoogled-Chromium's access was blocked.

Could you please test this in a similar way on your system?

**Comment by mizzuri** [comment]
Tested in the following ways while having set those two policies to disabled:

Windows version:  1909 (Build 18363.815, x86_64)

1.  I downloaded a new, never before used, portable version of FileZilla (an FTP client).  Right after I opened filezilla.exe, the usual simplewall's popup came up asking for permission to allow to connect.  Possibly FileZilla is checking for available updates automatically.

2.  I unchecked the psping.exe, which is part of the Sysinternals Suite, from the "Enabled apps" section, and also deleted it from the "Disabled apps" section.  Once I started using psping, the usual simplewall's popup asked to connect.  I wasn't able to ping until I clicked the "Allow" button.

Notes:
- My simplewall.ini content:  https://pastebin.com/raw/7t9sunH6
- I've enabled everything under the Blocklist tab.
- There're some other rules that I've changed, but I don't think they will have any effect on the tests.

**Comment by ltGuillaume** [comment]
That's very odd then. I'll do some more testing.

**Comment by mizzuri** [comment]
I don't think setting those 2 policies totally disable the windows' internal firewall.
Because it seems the "Windows Defender Firewall" service is still running.  Not sure if they're related though.

**Comment by willemduncan** [comment]
Came here for the same thing, followed @mizzuri 's suggestion and can confirm: Simplewall still blocks connections, and I still get warning popups. Now just to see how long it takes Windows to switch back on the annoying warnings.

I guess a "real solution" would be to allow windows to detect Simplewall as a custom firewall provider? Seeing as they allow custom providers for antivirus/malware/etc I would guess they have a system for firewall too. Though I do not know what effort and/or downsides are involved in that, or if it's feasible at all.

**Comment by ltGuillaume** [comment]
I just tried again and there is some strange behavior around the setting:

- So, first time, it caused all traffic to be allowed, even though simplewall had its filters applied. A filter refresh from simplewall's UI didn't work either.
- This time, I got an error + red cross over the Defender tray icon (shield), and only after a reboot everything seemed to be working OK.

I'll keep tabs on whether the filters keep working, but so far this is indeed the best workaround for the notification issue.

**Comment by mizzuri** [comment]
I just tried it on another computer, and it also went fine.

**Comment by mizzuri** [comment]
An update or something might have triggered the built-in firewall to turn back on today.

My browser wasn't working in the morning, even though I have it allowed in the simplewall.  Everything else seemed fine.  So I checked the group policies again, and somehow the 2 Windows Defender Firewall settings were set to "Enable".

I'm not sure what might have caused it.

Something to be careful about.  Weird things could happen if both simplewall and Windows Defender Firewall are on at the same time, I guess.

**Comment by ltGuillaume** [comment]
> 
> 
> An update or something might have triggered the built-in firewall to turn back on today.
> 
> My browser wasn't working in the morning, even though I have it allowed in the simplewall. Everything else seemed fine. So I checked the group policies again, and somehow the 2 Windows Defender Firewall settings were set to "Enable".
> 
> I'm not sure what might have caused it.
> 
> Something to be careful about. Weird things could happen if both simplewall and Windows Defender Firewall are on at the same time, I guess.

Do you mean the policies turned back on and you saw a red cross warning over Defender's tray icon again, or did Defender Firewall _actually_ get re-enabled? The last thing would be strange, since simplewall now checks again if Defender Firewall is enabled and then disables it when you ticked the checkbox to do so.

I just mean that the firewall doesn't need to be enabled if those policies are back to default.

**Comment by mizzuri** [comment]
No red cross.  But the policies got re-enabled, so did the Defender Firewall.

Maybe this was a fluke.  I'll keep watch.

**Comment by caboo337** [comment]
I applied @mizzuri 's suggestion, it works, my Simplewall still blocks connections, no red cross, and no warning popups. (OS Version 1909)

**Comment by newbie337** [comment]
I applied @mizzuri 's suggestion, it works, my Simplewall still blocks connections, no red cross, and no warning popups. (OS Version 1909)

**Comment by Jaitsu** [comment]
Just as a note for those of us that don't have access to gpedit/Group Policy, the Registry equivalents for those Group Policy settings are as follows:

HKLM\SOFTWARE\Policies\Microsoft\WindowsFirewall\DomainProfile\EnableFirewall (DWORD) = 0
HKLM\SOFTWARE\Policies\Microsoft\WindowsFirewall\StandardProfile\EnableFirewall (DWORD) = 0

Perhaps simplewall could provide an option to set these values to silence the notifications.

**Comment by FischerandomONLY** [comment]
> No red cross. But the policies got re-enabled, so did the Defender Firewall.
> 
> Maybe this was a fluke. I'll keep watch.

Your method works perfectly mizzuri, thank you! this non-removable notification was starting to get bloody annoying.

**Comment by Johandrex** [comment]
I'm going insane, still getting the firewalls notification despite attempting to use the tips by everyone in this thread on my two computers, both running Windows OS build 19041.

I have attempted to disable the policies "Windows Defender Firewall: Protect all network connections" in (Local Group Policy Editor > Local Computer Policy > Computer Configuration > Administrative Templates > All Settings) as @mizzuri recommended.

I've also disabled the following registries down below as recommended by @Jaitsu

```
Computer\HKEY_USERS\{XXXXXXXXXXX}\SOFTWARE\Microsoft\Windows\CurrentVersion\Group Policy Objects\{XXXXXXXXXXX}Machine\SOFTWARE\Policies\Microsoft\WindowsFirewall\StandardProfile\EnableFirewall = 0
Computer\HKEY_USERS\{XXXXXXXXXXX}\SOFTWARE\Microsoft\Windows\CurrentVersion\Group Policy Objects\{XXXXXXXXXXX}Machine\SOFTWARE\Policies\Microsoft\WindowsFirewall\DomainProfile\EnableFirewall = 0
```

But I'm still getting the notification every single day, does the tips above still work for anyone else? Or is there any other methods for disabling the Windows defender notifications?

**Comment by mizzuri** [comment]
@Johandrex, the tip above still works for me. I'm on Windows Version 20H2 (19042).

**Comment by middleflesh** [comment]
Disabling Windows Security service stops the notification from appearing. Im on Windows 11, but it worked on Windows 10 as well. You need to disable it from registry. Take ownership of the key to change the value of 'start' to '4'.
`Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SecurityHealthService`

Do it at your own risk. This will break the Windows Security app!

**Comment by ZacharyElkins** [comment]
Yeah, none of the solutions above stop the notification for me.

Perhaps I'll be completely removing Windows Defender and replacing it with something else soon. I can't even use the notification system because I don't want a microaggression everytime I boot my PC (pun intended).

**Comment by FischerandomONLY** [comment]
> Yeah, none of the solutions above stop the notification for me.
> 
> Perhaps I'll be completely removing Windows Defender and replacing it with something else soon. I can't even use the notification system because I don't want a microaggression everytime I boot my PC (pun intended).

Hey man, i'm on W11 22H2 pro version and still using the gpedit fix mizzuri posted and for me it's working. you tried that?

**Comment by b0unty1** [comment]
Maybe too late, but this is what I use to disable annoying notifications about Windows Firewall when using simplewall.

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Defender Security Center\Notifications]
"DisableNotifications"=dword:00000001

Working on latest win10 LTSC

**Comment by mizzuri** [comment]
> Maybe too late, but this is what I use to disable annoying notifications about Windows Firewall when using simplewall.
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Defender Security Center\Notifications] "DisableNotifications"=dword:00000001
> 
> Working on latest win10 LTSC

But be careful, since it will also disable notifications and alerts about viruses, malware, etc.

**Comment by b0unty1** [comment]
> But be careful, since it will also disable notifications and alerts about viruses, malware, etc.

Yes, true, but i'm using third-party antivirus (ESET Nod32)
