### ISSUE TITLE
[3.0.7] Empty proccess name and path

### ISSUE THREAD

**Issue by Globulopolis** [henrypp/simplewall#555]
Hi!
Started using simplewall.
After update from 3.0.6 to 3.0.7 I see this in logs
![Clipboard01](https://user-images.githubusercontent.com/740757/68075099-83483980-fdb4-11e9-861d-27648d3b323c.jpg)
I know that these connections coming from/for utorrent. In settings utorrent is enabled in application list, and upnp and ssdp enabled in system rules.

![image](https://user-images.githubusercontent.com/740757/68075173-4cbeee80-fdb5-11e9-8f6b-215f99135438.png)

Is where a normal behaviour?

**Comment by henrypp** [comment]
It's not torrent, it's a port scanner filters
