### ISSUE TITLE
Right click options and Purge Invalid Apps Gone

### ISSUE THREAD

**Issue by ShaerAlvy** [henrypp/simplewall#556]
Hi there,
in New version, Add to whitelist apps by service or exe with 'right click option' is gone. Also 'Purge invalid apps' is also gone which is necessary i think.... Back to previous version for these 2 Issues (Or Changes).
Please consider to bring those options again... Thanks

**Comment by henrypp** [comment]
Hmm, why you need this right click option if all services are placed in "Services" tab and do not needed to be "added"

Same with purge invalid apps, it's useless - use purge unused apps, is the same.

**Comment by ShaerAlvy** [comment]
Hi there !
i need right click option for the 'Add Process'... its very easy to choose selected apps to whitelist whether only 'Services' is kinda messy for me....
And purge invalid apps is needed bcoz i can see which apps i blacklisted, But in new version if i click purge unused apps, al the blacklisted apps are gone...

Please see the picture
Thanks
![12](https://user-images.githubusercontent.com/24366205/68129990-c9340780-ff44-11e9-9019-0f0f7f598c3f.jpg)

**Comment by henrypp** [comment]
>  And purge invalid apps is needed bcoz i can see which apps i blacklisted, But in new version if i click purge unused apps, all the blacklisted apps are gone...

Disabled apps group have count badge.

>  i need right click option for the 'Add Process'... its very easy to choose selected apps to whitelist whether only 'Services' is kinda messy for me....

SW have completely removed process explorer features, sorry!
