### ISSUE TITLE
Constant connection request

### ISSUE THREAD

**Issue by privacyguy123** [henrypp/simplewall#558]
What on earth is this?

![image](https://user-images.githubusercontent.com/50337995/68149024-098b8980-ff35-11e9-9513-511a353db57b.png)

**Comment by henrypp** [comment]
It's, obviously, IGMP

**Comment by pwn0r** [comment]
Just a lifehack here: if you are on a secure LAN (best at home, not an public wifi of course) then in order to make you life much easier -- you just allow certain system apps to access _LAN ONLY_. 

I normally allow unpcampaignmanager.exe, spoolsv.exe, System etc for access the LAN but block them on the internet.

**Comment by privacyguy123** [comment]
It doesn't seem to matter if I create a custom rule to allow them, they ask for connection over and over and over

**Comment by henrypp** [comment]
> It doesn't seem to matter if I create a custom rule to allow them, they ask for connection over and over and over

So apply created user rule (if it right - it will work) for the app and disable notifications for this app and no more problems, hmm?

**Comment by privacyguy123** [comment]
When the popup appears I click "create rule" and it makes a correct one for me - yet the program keeps asking over and over and over for permission???

**Comment by henrypp** [comment]
Program keeps asking for what? You are completely allowed app OR created user rule for app?

**Comment by privacyguy123** [comment]
When this popup appears I click "Create Rule" and the same popup happens agan and again ...

**Comment by henrypp** [comment]
What rule do you create?

**Comment by privacyguy123** [comment]
The rule it creates automatically for me when I click "Rules - Create Rule" in the bottom left of the screenshot

**Comment by henrypp** [comment]
Create more wide rule:

protocol: igmp
direction: both
other fields: <leave blank>

and apply it

**Comment by privacyguy123** [comment]
Here is the rule and the firewall notification - simplewall is ignoring it

![image](https://user-images.githubusercontent.com/50337995/68530688-9900b600-0302-11ea-9f07-92e8f240c810.png)

**Comment by henrypp** [comment]
What local address? Can you open the packets log? I think, `192.168.1.254` is incorrect, because of System do recv/accept operations. Try clear remote rule and set local rule to `224.0.0.0/4`

**Comment by privacyguy123** [comment]
192.168.1.254 is my router address 😕

**Comment by henrypp** [comment]
it does not matter, igmp used multicast address

**Comment by privacyguy123** [comment]
I think this might be it

"‎09/‎11/‎2019 ‏‎15:47:34","NT AUTHORITY\SYSTEM","System","224.0.0.1 (all-systems.mcast.net)","<empty>","192.168.1.254","<empty>","igmp","simplewall\BlockRecvAcceptConnectionsV4","#394479","Outbound","Blocked"

**Comment by privacyguy123** [comment]
Not matter what I do to allow this, it is blocked

**Comment by henrypp** [comment]
Rule is incorrect, i think. What do you do?

**Comment by privacyguy123** [comment]
Rule states that igmp://192.168.1.254 should be allowed in any direction for System no?

I think I've turned it off, wtf does IGMP even do?
