### ISSUE TITLE
Work at service driver!

### ISSUE THREAD

**Issue by Wizzergod** [henrypp/simplewall#560]
Hi,
Can you do this programm work at the same **service or driver** its much more faster and he can _started at boot_?
Because **standart Windows Gui bugged** if i created so many much rules its lagged about **1 min** to enable and disable, _i know its a check process_ and he is not faster because limited be windows gui, but if you do this programm work at service driver its work as faster and no bugs and lags, can you do it pls if its possible? Thanks.

**Comment by henrypp** [comment]
You mean service/driver ideal adn does not contain bugs? WTF
