### ISSUE TITLE
Cannot disable internet for Microsoft Edge

### ISSUE THREAD

**Issue by ViRb3** [henrypp/simplewall#561]
Moved `Microsoft Edge` to `Disabled apps` under `Packages`, but Edge still has internet access. Is there anything I am missing?

**Comment by ViRb3** [comment]
Seems that internet is only blocked if __both__ `MicrosoftEdgeCP.exe` (Apps tab) and `Microsoft Edge` (Packages tab) are disabled. If just one of them is disabled, internet will still work. Is this intentional?

**Comment by henrypp** [comment]
> Seems that internet is only blocked if **both** `MicrosoftEdgeCP.exe` (Apps tab) and `Microsoft Edge` (Packages tab) are disabled. If just one of them is disabled, internet will still work. Is this intentional?

It's right, "Packages tab" are allowed by "PackageSID" - it means all registered executables of this package (including `MicrosoftEdgeCP.exe`) will have internet access, and "Apps tab" allow executables strict (just allowed <fullpath> will have ineternet accesss). Understand?

**Comment by ViRb3** [comment]
I get that, but if the `Packages` tab controls
> ... all registered executables of this package (including MicrosoftEdgeCP.exe)

shouldn't disabling the `Microsoft Edge` package also disable `MicrosoftEdgeCP.exe`? Or if I disable `MicrosoftEdgeCP.exe` but not the `Microsoft Edge` package, shouldn't internet still be blocked? I can't understand why both of the places have to be disabled to block internet as opposed to just one.

Thanks!

**Comment by henrypp** [comment]
Because Edge working in both levels UWP and Win32.
If UWP app does not get internet, then Win32 app get it.
