### ISSUE TITLE
signed int (32)  overflow

### ISSUE THREAD

**Issue by lulcat** [henrypp/simplewall#564]
Hi, just tried downloading an update. Not sure why but the percentage progress overflowed it seemed:

https://pasteboard.co/IGgOUOB.jpg

it didn't work therefore, so it did have an impact it seemed. how are these updates transferred? ssl or unencrypted? Not that tls does much vs. middle men but just was curious.

**Comment by henrypp** [comment]
image not found

**Comment by henrypp** [comment]
#568
