### ISSUE TITLE
The program download an "update" when there's no updates

### ISSUE THREAD

**Issue by Loughty** [henrypp/simplewall#565]
And keep on the 100%, never install that "update". Only happens when the computers turn on, not the rest of the day. If I abort it and next click on Check updates say that there's not updates.

**Comment by Wizzergod** [comment]
yes is bugged update, i have old 307 and check update found but 100% loading, no start install update, then i update manually download 308 and reinstall 307 to 308 then whe i start pc again says have update i click ok and again 100% loading, no start install update, i click cancel and check again for update he say no have update!

**Comment by henrypp** [comment]
Duplicate? #543
