### ISSUE TITLE
Allow custom rules with no local/remote address

### ISSUE THREAD

**Issue by privacyguy123** [henrypp/simplewall#567]
As it stands it's not possible to make a rule to place a blanket block rule over a certain protocol (save is greyed out with no addresses)

![image](https://user-images.githubusercontent.com/50337995/68700555-03248f80-057d-11ea-912d-56694235db2c.png)

**Comment by turkeyhandwoven** [comment]
I always add an empty space in either the remote or local rule, then it allows me to save and the rule works just fine.
Did you try that?

**Comment by privacyguy123** [comment]
Does empty space = everything? Or do we use *

**Comment by henrypp** [comment]
Use wildcard for this (it's a strict rule, *****)

**Comment by henrypp** [comment]
Anyway ICMP is already exists in-box as user rule
