### ISSUE TITLE
Updating internal rules (Nov. 10) - Download dialog gets stuck

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#568]
![image](https://user-images.githubusercontent.com/4777345/68703138-46d1c600-058a-11ea-9fa4-0f1d82accaea.png)

The download dialog got stuck like this. After restarting simplewall and checking for updates, there are none. `profile_internal.xml` seems to have been updated, though, so it may just be a GUI glitch.

**Comment by lulcat** [comment]
Hi again, well the img link worked for me over in the previous issue. Anyway, all good, ye, the 32 bit signed int overflows somewhere, and I don't have time right now to look into code. Out of curiosity, what connection are the updates negotiated on? tls 1.2<= or?

**Comment by ltGuillaume** [comment]
Oh, then it's probably good to know that I'm using the portable x64 (on Win10 1809LTSC).

**Comment by cloudgreen** [comment]
I just got the same stuck dialog (v3.0.9).

A few questions:

1. What are the language pack updates? Updates for the different GUI languages?
2. What setting controls the checking of language pack updates? Is it "Periodically check for updates"?
2. Could we have them automatically installed silently in the background?

Thanks!

**Comment by ltGuillaume** [comment]
> 
> 
> I just got the same stuck dialog (v3.0.9).
> 
> A few questions:
> 
>     1. What are the language pack updates? Updates for the different GUI languages?
Yes.
>     2. What setting controls the checking of language pack updates? Is it "Periodically check for updates"?
Yes.
>     3. Could we have them automatically installed silently in the background?
Would be ok _if_ we had a system notification that a language/blocklist was updated, yeah.

**Comment by cloudgreen** [comment]
@ltGuillaume Thanks for the replies, appreciated! 

Is the automatic "silent" update (with a system notification) feasible to do? Or does it have some obstacles?

**Comment by Silent-Hunter** [comment]
This has happened to me for all update dialogs, not just the internal rules one. The last update I had to uninstall the old version and then install the new one downloaded from the site.

**Comment by ltGuillaume** [comment]
I just had a successful update to v3.0.9, but then v3.0.9 itself failed to update the language pack with the problem described above.

**Comment by henrypp** [comment]
fixed
