### ISSUE TITLE
Simplewall 3.0.8

### ISSUE THREAD

**Issue by liskaaaaaaaaaa** [henrypp/simplewall#571]
https://www19.zippyshare.com/v/6ggC1tKJ/file.html

3.0.8 - it does not work

3.0.7 it works

please fix :((((

Windows 8 (not 8.1) 64bit

**Comment by henrypp** [comment]
fixed

**Comment by liskaaaaaaaaaa** [comment]
Simplewall 3.0.9 not fix ;/  3.0.9 also bug :(((

**Comment by henrypp** [comment]
what?

**Comment by liskaaaaaaaaaa** [comment]
@henrypp 
Simplewall 3.0.8 and Simplewall 3.0.9 is not works. Simplewall 3.0.7 is works 
Windows 8 (not 8.1) , 64bit

**Comment by henrypp** [comment]
What is not works?

**Comment by liskaaaaaaaaaa** [comment]
@henrypp
 Program does not open ;( please fix :( 
https://www19.zippyshare.com/v/6ggC1tKJ/file.html

Thia is some problem

**Comment by henrypp** [comment]
What problem? Everyone run this program as usual

**Comment by liskaaaaaaaaaa** [comment]
@henrypp 
https://www72.zippyshare.com/v/yZuJP82n/file.html

NEW WIDEO FOR YOU -.-  Program does not open, please fix

**Comment by henrypp** [comment]
what say process manager?

**Comment by liskaaaaaaaaaa** [comment]
@henrypp 
https://www98.zippyshare.com/v/RMbGeKQd/file.html
