### ISSUE TITLE
Update to 3.0.9 issue

### ISSUE THREAD

**Issue by fnordson** [henrypp/simplewall#574]
Hi,

first: thank you for this wonderful piece of software. It's an easy and not over bloated solution. I love it and even my not techsavy friends do understand it. Great job! 

Now to the issue: 
I get a notification to update my 3.0.8 version. 
Update downloads to 100% but nothing happens then.  
If I look for update again from the running software, the same thing happens but I get an error: "Update-Server Connection error"

At this point, I'd just download the newest version from the homepage but I would like to know if the rules that I've set will be preserved.  
Also: can I overwrite the current version or do I have to uninstall  3.0.8 first? 

Thank you.

**Comment by henrypp** [comment]
rules are preserved on update, no worry. uninstall is not required, just replace binaries
