### ISSUE TITLE
Back to before start Simplewall

### ISSUE THREAD

**Issue by Satellietje** [henrypp/simplewall#576]
I use Simplewall portable. If I put my USB disk in a PC, Simplewall will direct start up. I then have full control over which programs can and cannot go outside, including programs already installed on the PC's hard disk.
The only problem is that sometimes I forget to disable the filters when I turn off Simplewall and remove the stick from the PC.  
If I haven't given permission to a local program it can't go on the internet anymore, until I start Simplewall again and allow the a notification.

Can you build in an option that when I close Simplewall the filters will be reset as they were before I start using Simplewall.

**Comment by tomasts248** [comment]
Yes please!

**Comment by ltGuillaume** [comment]
> added temporary filtering mode whether is active until reboot

I couldn't find this anywhere. Where should I look?

**Comment by henrypp** [comment]
@ltGuillaume Install filters and then select mode

**Comment by ltGuillaume** [comment]
Thanks! Was looking for an option somewhere.
