### ISSUE TITLE
"system" still showing network connection after being blocked

### ISSUE THREAD

**Issue by charliechan231** [henrypp/simplewall#579]
Hello, I am using 3.0.9 64-bit version on windows 10. I moved svchost.exe and system(ntoskrnl.exe) into disabled apps to stop windows from updating. But from the disabled apps list the System app shows "Have network connections". 
Is this normal? How is the exe still getting network access while being disabled?

**Comment by henrypp** [comment]
How it get access? Some of System rules allow access for "System" & "svchost"

**Comment by charliechan231** [comment]
I have not changed any system rules or settings since updating from 2.0, on the previous version the 'system' had zero network data usage. Since updating to 3.0 the data usage for System shows almost 200mb and the icon in simplewall always has pink highlight indicating network access, even though it's in disabled list.

I have another question about the blocklist, when a rule is 'disabled' does this mean telemetry is blocked or do I have to 'enable' rules to block telemetry? 
I have them all the rules disabled at the moment.

**Comment by henrypp** [comment]
> I have not changed any system rules or settings since updating from 2.0, on the previous version the 'system' had zero network data usage. Since updating to 3.0 the data usage for System shows almost 200mb and the icon in simplewall always has pink highlight indicating network access, even though it's in disabled list.

Dont knnow anything about your configuuration. Still no telepaths.

> I have another question about the blocklist, when a rule is 'disabled' does this mean telemetry is blocked or do I have to 'enable' rules to block telemetry?
I have them all the rules disabled at the moment.

#512

**Comment by henrypp** [comment]
`System` shown connections because of loopback connections (192.168.0.0/16), it's normal. Don't worrry!
