### ISSUE TITLE
Create rule from notification: UDP direction wrong

### ISSUE THREAD

**Issue by geonanorch** [henrypp/simplewall#581]
Just installed simplewall, added several rules and generally all works well, thank you! 

I did come across something that puzzled me for a while:
  - I get a notification that a connection was blocked (will attempt to attach): address=`udp://192.168.1.4`, Port=`5353 (mdns)`, direction=`Outbound`, Filter=`BlockRecvAcceptConnectionsV4`)
  - I then click on "Rules" / "Create rule..." and then directly on "Save"
  - a few seconds later I get the very same blocked notification again, although the rule is active

![mdns](https://user-images.githubusercontent.com/19654936/69626434-f3ab4900-1048-11ea-99b6-26e321c4853c.png)

Finally noticed that the filter does not match the direction. I then altered the rule's direction to `Inbound`, and notifications stopped showing.

Also noticed that notification addresses are sometimes shown including port like `udp:xxx.xxx.xxx.xxx:NNNN`, sometimes the port is provided separately under `Port`. Is it the local port then ? (if yes I suggest to make the label explicit: `Local port`)

**Comment by Janaue** [comment]
i have the same situation
direction in popup warning = inbound
then choose ''create the rule'' and the direction ''outbound'' is selected...

**Comment by cloudgreen** [comment]
Smells like a bug, good find! We should probably ping @henrypp.

**Comment by henrypp** [comment]
fixed
