### ISSUE TITLE
Can't Upload Files: Neither on gmail or Web WhatsApp on W7 64-bit

### ISSUE THREAD

**Issue by tomasts248** [henrypp/simplewall#582]
Also if I choose to disable the Windows Firewall while reactivating the filters I'm not even able to browse properly nor access my gmail account. If I restart the computer the problems are gone till I start Simplewall. Oddly disabling the filters does not seem to fix the issues

**Comment by henrypp** [comment]
No one know, there is no telepaths. No one see your logs or some

**Comment by tomasts248** [comment]
I'm afraid I uninstalled it...

**Comment by henrypp** [comment]
Don't worry and not aftaid!
![sshot-002](https://user-images.githubusercontent.com/3902025/69911217-803b7a00-1442-11ea-9852-64b1700f2145.png)
