### ISSUE TITLE
Change the default file manager 

### ISSUE THREAD

**Issue by eugenesvk** [henrypp/simplewall#583]
I have a different **default file manager** app in Windows (e.g. when I double-click on 'My computer' on the desktop, I don't have **File explorer** opening, but this other app).
However, when I double-click an item in the **Apps** list, Simplewall always opens Windows' stock **File explorer**.
Is it possible to change this?:
a) either configure Simplewall to open a file manager from a custom path
b) or make Simplewall respect the default file manager setting
Thank you!

**Comment by henrypp** [comment]
SW uses system call [SHOpenFolderAndSelectItems](https://docs.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shopenfolderandselectitems), if custom File Manager registered as file manager in system it can be opened without any dirty hacks.

**Comment by eugenesvk** [comment]
Yes, it is registered and works in other apps (as well as on simple double-clicks on a desktop link/folder).
Is there a way to upate to the most recent version that uses the fixed SKD version with the SHOpenFolderAndSelectItems system call?

**Comment by henrypp** [comment]
>  Is there a way to upate to the most recent version that uses the fixed SKD version with the SHOpenFolderAndSelectItems system call?

Very soon.

**Comment by eugenesvk** [comment]
Thank you!
