### ISSUE TITLE
Simplewall win10 startup?

### ISSUE THREAD

**Issue by igitlin** [henrypp/simplewall#588]
I installed the program and included it in startup, I also have filtering enabled all the time. I would like to know if it is possible in this mode that some program, when starting up the system, will have time to go online before Simplewall starts? How can this be avoided?

**Comment by henrypp** [comment]
hmmm... SW displays warning message on exit and (at least) 3 same issues before this.

![850](https://user-images.githubusercontent.com/3902025/70728673-0ea9d880-1d2c-11ea-8904-420552958803.png)
