### ISSUE TITLE
Applications within symbolic links

### ISSUE THREAD

**Issue by 0x084E** [henrypp/simplewall#59]
If you have in application within a symbolic link it gets detected and can be configured but in whitelist mode it is always blocked.
For example if you have a second partition and mount it into c-drive with
```
mklink /J C:\external \\?\Volume{00000000-0000-0000-0000-000000000000}\
```
then the app gets detected with C:\external\app.exe but it is still blocked.

I don't know if there's anthing that can be done as the windows firewall has the same problem so it might be a filter driver issue.

Edit:
The problem only occurs if the second partition doesn't have a normal drive letter. If it has and a rule to this path exists (e.g.: D:\app.exe) the app is allowed even if it is started from C.\external\app.exe

Edit 2:
In the latest beta the blocking problem does not occur. But apps get auto-detected with a path \device\harddiskvolumeX\app.exe
If apps are added manually (e.g. from running processes) everythings works fine.

**Comment by henrypp** [comment]
2.0.6b fixed

**Comment by 0x084E** [comment]
Thanks for the fast response! But if an app is added to the list because of an conneciton attempt it still shows \device\harddiskvolumeX\app.exe which is then displayed as "not found".

**Comment by henrypp** [comment]
I'm tested it with latest beta, created link to `"D:\"` drive through:

`mklink /J C:\external \\?\Volume{00000000-0000-0000-0000-000000000000}\`

and all is working fine, i mean program detects as D:\app.exe, not C:\external, in packets log and main window.

what OS do you use? are your D: is physical drive?

**Comment by 0x084E** [comment]
I don't have a drive letter for this volume. I only have the junction C:\external so thats the only way to access it through a "normal" path.
With drive letter or if I add C:\external\app.exe manually it is working fine.

**Comment by henrypp** [comment]
I'm tested and found there is no way to found junction path for drive with no letter assigned, because dropped packets logging gets path in low-level style (\device\harddisk1\etecera). In 2.0.9b you can see file with nt path (\device\harddisk1\etecera) and this not marked as "invalid" anymore, it have all features like all other apps with normal (dos) paths, but without icon/description/signature information displaying.

There is only way in your case, sorry.

**Comment by 0x084E** [comment]
Not the only "problem" with this kind of setup. I'm very happy already if it is handled correctly 😃 
Thanks for your time!
