### ISSUE TITLE
Update progress stuck (Downloading update... -2147483648%)

### ISSUE THREAD

**Issue by rayheffer** [henrypp/simplewall#590]
The 'Update Available' dialog appears, but when I click to perform the update it displays 'Downloading update... -2147483648%' and doesn't download anything. I have to cancel. Tried uninstalling and reinstalling.

Edit: If I cancel and go to Help > Check for updates, then it says 'No updates available'

Windows 10: Build1809 (Enterprise)
SimpleWall 3.0.9

**Comment by Chaython** [comment]
I have the same issue aswell for the past couple months. I reported it in #580

**Comment by TheMCNerd2017** [comment]
This has also been happening to me for several months now.
Is there any fix other than reinstalling Windows? I have slow and unreliable DSL and can't download a 5GB ISO file.

**Comment by Chaython** [comment]
If you're just having the percentage issue, then disable auto updates as there's no update available, disable simple wall's fw access.
There's obviously no update available, there's probably just some hash error.
Manually check for updates via the git. Click watch "releases only" to get an email when there's updates.
If you're experiencing the other issues described in my ticket then a clean install of windows was necessary, I believe simplewall blocked fw access to something during the windows update install [as I had the enable at boot settings] which corrupted something in windows filtering. Maybe manually check windows filtering, as simplewall is just a nice gui for it....

**Comment by TheMCNerd2017** [comment]
Well it claimed there was updates for internal rules and something else, and clicking update resulted in it displaying the downloading update dialogue forever until I manually closed the program.
As for the corruption in Windows Filtering Platform, how can I check for that?

**Comment by Chaython** [comment]
I referenced 580 which included ""0x00000005","FWPM_ENGINE_COLLECT_NET_EVENTS"" error. I was asking if you also had that issue.
Regardless, you can copy the internal rules from the git
https://github.com/henrypp/simplewall/blob/master/bin/profile_internal.xml
https://github.com/henrypp/simplewall/blob/master/bin/blocklist.xml
Replace / copy into the files inside the simplewall folder
There could be many reasons for updates not working, like insufficient write permissions, mismatched hashes, some service being blocked...
As an open source project, I recommend compiling yourself and disabling auto updates, for the best security and to be most up to date. However you may only want to compile from releases and build a powershell script etc to manually auto update at windows startup etc.

**Comment by TheMCNerd2017** [comment]
Yeah, I don't think I'm getting that error. I also compared the internal rules and blocklist with the ones on my PC and they're the same.
Also, the program never automatically updated for me, as the most it would do is ask if I would like to update it.

**Comment by Chaython** [comment]
Yes, it doesn't auto update fully, it prompts you. Just disable "periodically check for updates" and uncheck simplewall in the apps panel. Subscribe to releases and manually update via the git when you deem necessary.
For me the list is the same, build and revision number is the same, but the file in the git was updated recently. The onlything that seemed to change is the root timestamp.
Which all these issues seemed to be related to the timestamping. "0x00000005","FWPM_ENGINE_COLLECT_NET_EVENTS" seemed to be happening when my windows clock was out of sync.
Anyways if the file doesn't have the same hash it will keep telling you to update [probably is how it's checked though I am not sure].
There is many tools to check file hash. https://www.virustotal.com/gui/home/upload for example gives the hash for the newest version of profile_internal.xml 4b8d570ca3b92e40d7dff9089dcaaba3fd3556a6ec71d93a2c6d81a9bb4cc104
Drop your profile_inernal.xml into virustotal to check if the hash is the same?

**Comment by henrypp** [comment]
original topic #568
