### ISSUE TITLE
Features Suggestions

### ISSUE THREAD

**Issue by Mike-Reddick** [henrypp/simplewall#592]
1 - Make font of notifications popup and other fonts follow the font size setting

2 - Add an easy way or an default rule to easy restrict apps to LAN ONLY, blocking just internet traffic

3 - Better documentation of features and settings

4 - setting to auto purge invalid and unused app on startup

5 - add network speed monitor on taskbar the same features of the NetSpeedMonitor by Florian Gilles

**Comment by khabib227** [comment]
@henrypp this was really good suggestions!

**Comment by parasiteoflife** [comment]
+1 for the number 2, it would be easier for non techie ppl so they would only have to click a "LAN Only" button or something.
