### ISSUE TITLE
Simplewall doesn't block outbound for potable app

### ISSUE THREAD

**Issue by Globulopolis** [henrypp/simplewall#593]
I have a portable app with executable. I add it to app list and set rule to block remote 0.0.0.0/0 outbound, protocol tcp, action block.
When I run portable app SW should block access but in logs nothing displayed. Even when splash screen for actions doesn't show up.

**Comment by henrypp** [comment]
> Simplewall doesn't block
> When I run portable app SW should block access but in logs nothing displayed.

Log contain only dropped connections, are you sure <app name> does?

**Comment by Globulopolis** [comment]
Yes, i's sure. After digging I see that the app is running in virtual container and physical path for app differ from actual path.
App executable located at the `d:/app/app.exe` but in ProcessExplorer I see that the app running from `c:/portapp/app/app.exe`.

I don't know how Simplewall should handle this behaviour, but in Comodo Firewall I just add an app at the physical location and the firewall can handle app connections.

**Comment by henrypp** [comment]
What app? What os?

Whatever. Physical location & symlink (etc) it does not matter, SW will write dropped packets into the log.

**Comment by Globulopolis** [comment]
Cannot provide a link to app because it's warez.
OS Win 7 Ultimate with latest updates.

Don't know why this happens. I will test again.

**Comment by henrypp** [comment]
> I add it to app list and set rule to block remote 0.0.0.0/0 outbound, protocol tcp, action block...

This is useless, because _all_ apps not in _allowed apps_ list are blocked by default.

Maybe debug log in SW profile directory contaiins any 0x05 errors, which means - SW cannot subscribe to WFP packets logging?
