### ISSUE TITLE
Windows sandbox

### ISSUE THREAD

**Issue by MDSilviu** [henrypp/simplewall#594]
I'm trying to use windows sandbox and allow it to connect to the internet but i can't figure it out how to do that. There is no notification pop-up to add when i run the sandbox, i tried to add the executable into allowed app list but still without any success. If i disable the firewall it works fine.
Any chance i could get some details on how can i make it work?

**Comment by henrypp** [comment]
All information about dropped packets contained in log. I think it worked over svchost.exe

**Comment by QingKongBaiYu** [comment]
allow both inbound and outbound of remote port 68 for svchost.exe

**Comment by CheariX** [comment]
Enable Services -> SharedAccess
