### ISSUE TITLE
Simplewall has blocked my windows store and all apps

### ISSUE THREAD

**Issue by path501** [henrypp/simplewall#598]
After installing simplewall, I find that I am no longer able to access my Microsoft store or any of the apps like windows update they have been permanently blocked by this program.  I uninstalled simplewall and these are still blocked.  Help me, I don't know how to unblock these.

**Comment by henrypp** [comment]
>  I uninstalled simplewall and these are still blocked. Help me, I don't know how to unblock these.

<s>Reinstall Windows is simpliest way, ever!</s> 

SW is not correctly uninstalled ([here is the answer](https://github.com/henrypp/simplewall/issues/584#issuecomment-577990012) and do not install again, please)

> I don't know how to unblock these.

SW is working in manual-only mode: all changes you made, you can unmade by yourself!


2) or you do not know how Щindows works. (there is no answer)

**Comment by path501** [comment]
I see you removed your smart a** comment that you left.  I know how windows works!
How about you let me in on what filters you are talking about in your answer!  I asked for your help not your trolling!

**Comment by perdolka** [comment]
@path501

![зображення](https://user-images.githubusercontent.com/24720263/73724153-64e73680-4733-11ea-8669-d217e0d3f530.png)

**Comment by path501** [comment]
I've tried everything I can (with the exception of reinstalling windows).  A screenshot of your simplewall does nothing for me especially after I have uninstalled the program.  Thank you anyways though.   The app developer has no clue as to how to do fix it either.

**Comment by cloudgreen** [comment]
@path501 I'm sorry you got unhelpful and sarcastic responses. :(

Have you tried resetting the Windows Firewall with "netsh advfirewall reset" as described below?

https://winaero.com/blog/how-to-reset-windows-firewall-in-windows-10/

I have Windows Update and the Store working with Simplewall, so it should be possible for you as well. If nothing else works, maybe you could reinstall Simplewall v3.1 and see if you can enable Windows Update in the settings (there are good threads here about that). Once it works, you could probably uninstall Simplewall again...

Good luck!

**Comment by path501** [comment]
> 
> 
> @path501 I'm sorry you got an unhelpful and sarcastic response. :(
> 
> Have you tried resetting the Windows Firewall with "netsh advfirewall reset" as described below?
> 
> https://winaero.com/blog/how-to-reset-windows-firewall-in-windows-10/
> 
> I have Windows Update and the Store working with Simplewall, so it should be possible for you as well (if you're still interested in having Simplewall installed). If nothing else works, maybe you could install Simplewall v3.1 and see if you can enable Windows Update in the settings (there are good threads here about that). Once it works, you could probably uninstall Simplewall again...
> 
> Good luck!

Thank you cloudgreen!  I do appreciate your insight.  I first tried reinstalling simplewall and then went into the manual rules settings and I was able to re-enable everything!  Now my PC can receive updates again!  I am so thank for your suggestion because I wasn't going to do that for fear of having everything blocked.  I can't thank you enough!  I'm going out on a limb here.... This app is great as long as you know how to use it, but if you don't have a clue, stay away from it!

To Henryplusplus ass.  The simple answer was to install it again!  GFY!
To cloudgreen, thank you again!

**Comment by path501** [comment]
Problem solved, follow cloudgreens instructions on re-installing simplewall and then go to manual rules settings.  Put a check in the "disable rule" box and manually put a check in every box.  There are a lot of them!

**Comment by cloudgreen** [comment]
I'm really glad it helped! :D And let's try to have great manners even when others don't. ;)
