### ISSUE TITLE
Error with windows firewall management

### ISSUE THREAD

**Issue by hed0nist** [henrypp/simplewall#60]
First thanks for this very nice piece of software.

I have an error since the first version 2.0 i tried ( maybe the 2.0.4b ) related to the control of windows firewall service within your program.

Here is the log ( same message in prior versions ) : 
[‎24/‎09/‎2017 ‏‎08:43:35] OpenService() failed with error code 0x00000005 (mpssvc) [2.0.8]
[‎24/‎09/‎2017 ‏‎08:43:36] OpenService() failed with error code 0x00000005 (mpsdrv) [2.0.8]
[‎24/‎09/‎2017 ‏‎08:46:08] OpenService() failed with error code 0x00000005 (mpssvc) [2.0.8]
[‎24/‎09/‎2017 ‏‎08:46:08] OpenService() failed with error code 0x00000005 (mpsdrv) [2.0.8]

I am using windows 10 family x64 "insider" french version.
I am under an admin account, I tried running simplewall.exe as admin, same results. 

Besides after stopping windows built-in firewall, windows doesnt recognize simplewall as a valid protection.

Just wanted to let you know, and again, thanks for this.
Regards ,

**Comment by henrypp** [comment]
> I have an error since the first version 2.0 i tried ( maybe the 2.0.4b ) related to the control of windows firewall service within your program.

`0x00000005` means `Access Denied`, maybe any protection software, you have, blockling access to services?

> Besides after stopping windows built-in firewall, windows doesnt recognize simplewall as a valid protection.

Yes, it is.

**Comment by henrypp** [comment]
2.0.18 fixed
