### ISSUE TITLE
Add a log on startup task to run simplewall as admin

### ISSUE THREAD

**Issue by aha999** [henrypp/simplewall#601]
Everytime a pc gets logged in, Simplewall asks for admin permissions confirmation.

Add a task into the task scheduler to run Simplewall on log-on with highest privilegies (so no confirmations are needed e.g. upon pc restart).

I created a startup task, but it would be nice if it was included by default (or in a checkbox) when Simplewall gets installed.

**Comment by tokariu** [comment]
see: https://github.com/henrypp/simplewall/issues/604#issuecomment-582331985
