### ISSUE TITLE
Question about Disabling Windows Defender...

### ISSUE THREAD

**Issue by leeuniverse** [henrypp/simplewall#602]
So, I saw in your FAQ's that you want us to use a .BAT file to disable WF.
However, going to Defender Settings it shows as still "On".

Is that what you mean by "partially" we are disabling WF?
Does the BAT file disable only "part" of Windows Firewall, and it remains on otherwise?
Is that why you have us to the BAT file rather than just going to Settings and disabling Windows Firewall?

The reason I ask about this is apparently I can't sign into OneDrive unless I actually disable Windows Defender through the settings.  I see nothing that I can tell should be stopping it in your program?  What's even weirder is I look through Defenders Incoming and Outgoing Lists and NOTHING is blocked?  So, don't know if there's some other setting hiding somewhere in Defender or what?

Thanks, much for your program, it's the only one that's working without much problems for a small compact firewall.

**Comment by leeuniverse** [comment]
Okay, ignore the "OneDrive" comments, found out it was 360 Total Security who added necessary OneDrive startup functions to their block on startup list so it was removing the startup task, which is dumb when if anything it should be disabling it.

But, still have a quesiton about Windows Defender, if we should be leaving it ON and just using your BAT file to be turning off whatever function it is, and the program still stays on.
Thanks

**Comment by ltGuillaume** [comment]
Try this one instead.
[disableWinFirewall.zip](https://github.com/henrypp/simplewall/files/4176204/disableWinFirewall.zip)
