### ISSUE TITLE
Allow simplewall to skip UAC 

### ISSUE THREAD

**Issue by crazyyzarc** [henrypp/simplewall#604]
Hello.

When simplewall started automaticly, it trigger the UAC. Great job.
But how I can do not trigger the UAC on startup, while I do not deactive it. Can I define exceptions for the UAC prompts? I will not click on "yes, you can have admin rights" every day, every logon.

My current setting:
```
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run]
"simplewall"="\"C:\\Program Files\\simplewall\\simplewall.exe\" /minimized"
```

Anyone some ideas? Thanks

**Comment by tokariu** [comment]
Tell me, have you *even* read the settings menu?

![simplewall_2020-02-05_10-51-21](https://user-images.githubusercontent.com/7195846/73831841-494d6000-4807-11ea-8565-135f22692ae4.png)

**Comment by crazyyzarc** [comment]
**Thanks a lot**. I've forgotten this check mark.

**Comment by AshishHarkare** [comment]
Hi Team,
In portal version When we enable/tick the "Skip "User Account Control" prompt warning' and copy the folder to another machine or folder this option gets disabled/unticked. 
Is there any way to retain the enable/tick option even if we copy the folder to another machine or folder.
Thanks.

**Comment by henrypp** [comment]
@AH1223

>  Is there any way to retain the enable/tick option even if we copy the folder to another machine or folder.

No way.
