### ISSUE TITLE
v.3.1 64bit start with PrxerDrv.dll error

### ISSUE THREAD

**Issue by rampageX** [henrypp/simplewall#605]
WIndows10 x64 18363.592
v.3.0.9 worked fine.

![311_64bit_error](https://user-images.githubusercontent.com/994081/74082631-cfcba100-4a96-11ea-9d66-fbfbc49abfdb.jpg)

**Comment by Scordem** [comment]
WIndows10 x64 18363.628
Simplewall 3.1 x64

Same issue.

![1](https://user-images.githubusercontent.com/56701141/74083912-8b4b0000-4aac-11ea-9143-351ee4e75f85.png)

3.0.9 is no problem.

**Comment by valefrox** [comment]
Same problem starting RivaTuner Statistics Server.

**Comment by mochigithub** [comment]
Same issue with Volumouse and Listary.

This is a CRITICAL issue and should be updated ASAP. Had to revert to 3.09

**Comment by Lumbago1337** [comment]
Same here with Displayfusion: https://i.imgur.com/RCe4Evn.jpg
As a workaround I was able to "Disable Application Hooks" in the compatibility tab of the program. Maybe this info helps.

**Comment by mochigithub** [comment]
> Same here with Displayfusion: https://i.imgur.com/RCe4Evn.jpg
> As a workaround I was able to "Disable Application Hooks" in the compatibility tab of the program. Maybe this info helps.

Where is this this? I'm on Windows 10 Enterprise and I Don't see any disable application hooks in the right click compatibility tab

**Comment by valefrox** [comment]
It's a program option, not a system one.

**Comment by mochigithub** [comment]
I looked all over the program. Can you tell me where specifically it is? ☹

**Comment by valefrox** [comment]
> 
> I looked all over the program. Can you tell me where specifically it is?

Look here: http://www.pumbaa.ch/blog/tutoriaux/img/Eclipse-DisplayFusion.jpg

**Comment by cghub-io** [comment]
This release is not usable. Too many dll conflicts across a range of programs . Just to mention a few here I have the same issue. 
Thanks for looking into it. 
![Screenshot_1](https://user-images.githubusercontent.com/6765385/74114507-9746d700-4bfe-11ea-9520-a7393a0997fe.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/6765385/74114509-98780400-4bfe-11ea-9ffe-00140df803b3.jpg)

**Comment by ltGuillaume** [comment]
Why on earth would it have to be doing anything with these DLLs in the first place? Please @henrypp do explain.

**Comment by cloudgreen** [comment]
Hm, this is worrying.

Has anyone else but HenryPP knowledge about the Simplewall source code? Has it been reviewed by someone else here? Are we getting what we think we are getting with Simplewall?

**Comment by ltGuillaume** [comment]
What I suspect is that simplewall now puts some kind of hooks on these DLLs, which is definitely NOT what I would expect from a firewall application. What is going on here @henrypp ?

**Comment by ltGuillaume** [comment]
I just had the same thing with a DLL of software that never even tries to make a connection.

**Comment by henrypp** [comment]
Here is the answer https://github.com/henrypp/simplewall/issues/611#issuecomment-586869750
