### ISSUE TITLE
WSL apps do not display names in the Network tab and do not follow Show In List

### ISSUE THREAD

**Issue by cowsay1** [henrypp/simplewall#606]
I am running Nginx and some other daemons under WSL.

I managed to create rules for them, but when I want to check the connection status on the “Network” tab, there are no names, and the “Show in list” button also does not work.

![wsl](https://user-images.githubusercontent.com/60675651/74087932-c85dc500-4aa1-11ea-9c1a-2ba48fb459f5.png)

**Comment by henrypp** [comment]
Hello, let me know this bug is fixed in 3.1.2 or not?
