### ISSUE TITLE
[toolbar menu] View>Icons>Hide icons - doesn't really hide icons

### ISSUE THREAD

**Issue by wizetek** [henrypp/simplewall#607]
'Hide icons' doesn't actually hide icons. When this option is enabled, it shows a generic icon for all applications instead of their own.

Either rename this menu option to something more accurate, e.g. 'No custom icons' or don't display the generic icons at all and only show apps names alone. For the latter solution, rename the option to 'None' and move it to the top above 'Small'.

Tested in Windows 10 x64

**Comment by henrypp** [comment]
Yes. "Hide icons" option is for do not load binaries icons, this for speed reason.

I do nothing for this "improvement", [but you can](https://github.com/henrypp/simplewall/blob/763e199a2f512904494015310affa07a87ee6756/src/resource.rc#L492), if you need this.

PS: [same](https://github.com/henrypp/simplewall/blob/763e199a2f512904494015310affa07a87ee6756/src/resource.rc#L703) for #608
