### ISSUE TITLE
Why are all menus and tooltips dark?

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#609]
W10 19H2, simplewall v3.1. Somewhere between W10 1809 and 1909, a distinction between dark/light of Windows and dark/light for apps has been made. See Personalization -> Colors.

simplewall's background colors for menus and tooltips should adhere to Windows' option called "Choose your default app mode: light/dark", but instead it now adheres to "Choose your default Windows mode: light/dark".

As a result, all apps are light with the Windows default settings (Windows mode = dark, app mode = light), except for simplewall.

**Comment by reddyshyam** [comment]
Yes, this is not correct. User should have this option. I prefer light mode.

**Comment by ltGuillaume** [comment]
As said, it probably just looks at the wrong Windows setting. Simplewall doesn't need an option for it, you're setting the option within Windows.

**Comment by reddyshyam** [comment]
Hi,

Thanks for getting back. If it is looking at wrong windows settings starting 3.1 then it needs to look at correct windows setting like 3.0.9. Isn't it? Why should user do anything to fix something introduced in 3.1? Just saying. 🙂

Regards
Shyam

________________________________

**Comment by cloudgreen** [comment]
@reddyshyam @ltGuillaume 
I have the same issue here - SW v3.1 is dark, with my (default) Windows 10 1909 setting being:

![image](https://user-images.githubusercontent.com/42112877/74594996-c3b68500-503c-11ea-9d02-17de9a0cc60a.png)

...so Windows itself should be dark, but the apps light, right?

**Comment by ltGuillaume** [comment]
Correct.

**Comment by henrypp** [comment]
Affirmative. There is a bug of undocumented api on Windows 1903+. My mistake!

**Comment by xnoreq** [comment]
I have both set to dark. Simplewall (the menu bar, apps, services... settings windows) is white but the context menus are dark.
