### ISSUE TITLE
[Enhancement suggestion] Block mining scripts

### ISSUE THREAD

**Issue by duttyend** [henrypp/simplewall#61]
Dear Henry,

First of all, thank you so much for this wonderful (and so much needed !) app ! I'm already using 2.0.13 and it's awesome...

I thought that you might be interested in adding an "anti-mining" blocklist filter, for example by using a list such as this one : https://raw.githubusercontent.com/greatis/Anti-WebMiner/master/hosts

Thank you so much again and have a great day !

**Comment by henrypp** [comment]
To block hosts better use "[hostsmgr](https://github.com/henrypp/hostsmgr)". It's faster

**Comment by duttyend** [comment]
OK, thank you !

**Comment by beerisgood** [comment]
Or better: use PiHole
That doesnt slow down your PC

**Comment by duttyend** [comment]
Yes, thanks, I was very interested in Pi Hole but it doesn't run natively on Windows unfortunately...
For the moment, simplewall fits my needs perfectly !
