### ISSUE TITLE
simplewall.exe - Bad image

### ISSUE THREAD

**Issue by cghub-io** [henrypp/simplewall#611]
Thanks for the latest update. 

Before v3.1 everything was fine, but now since the update to 3.1 I am getting randomly the dialog box across many different applications. So far the dialog box comes when I start my computer freshly and have following programs running in the background: 
- OldNewExplorer v1.1.9
- Oracle VM VirtualBox v6.1.0 r135406
- teamviewer
![Screenshot_2](https://user-images.githubusercontent.com/6765385/74114400-fb1cd000-4bfd-11ea-91ff-ee9eace2a913.jpg)

I am worried now that simpleWall will start generating these popus on other 'dll' files of other programs. 

> simplewall.exe - Bad Image
> C:\Windows\sysetm32\VBoxMRXNP.dll is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system admin of the software vendor for support. Error status 0x0000428
![Screenshot_1](https://user-images.githubusercontent.com/6765385/74113173-a7f34f00-4bf6-11ea-8cfc-51be89393e64.jpg)

**Comment by valefrox** [comment]
Already signalled: https://github.com/henrypp/simplewall/issues/605

**Comment by cghub-io** [comment]
oh. i see. I thought i was going crazy :) cheers

**Comment by JoeBarouneD** [comment]
I have the same with Oldnewexplorer.dll

**Comment by mssign** [comment]
Те же, только в профиль. Библиотека JKL вылетает от https://github.com/BladeMight/Mahou/releases

**Comment by RawSlugs** [comment]
same with bonjour\mdnsNSP.dll

**Comment by Serebriakov** [comment]
Same error with Bandicam:
![photo_2020-02-10_08-37-13](https://user-images.githubusercontent.com/6421516/74366536-40e5be00-4de1-11ea-8a6e-ec18a79d1ac1.jpg)

**Comment by henrypp** [comment]
Yes. This is Windows 10 feature named Mitigation. Here is the **solution**:

Open PowerShell (as admin) and enter this code:
~~~ps1
set-ProcessMitigation -Name freeshooter.exe -Enable BottomUp,HighEntropy,StrictHandle,DisableExtensionPoints,MicrosoftSignedOnly,BlockRemoteImageLoads,BlockLowLabelImageLoads
~~~

**Comment by ltGuillaume** [comment]
Can you please tell us why simplewall would even load these modules when they don't even have to have any network access?

I saw this message relating to a DLL from PISMO File Mount, a suite that never makes any network connection.

**Comment by JoeBarouneD** [comment]
I wonder why it only began with the lastest release and not before.

Mitigation is not a new feature, so you have changed something related to it in the lastest version of SW.

**Comment by rudolphos** [comment]
powershell command didn't had any effect.

> ---------------------------
> simplewall.exe - Bad Image
> ---------------------------
> C:\PROGRA~1\MacType\MacType64.dll is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0xc0000428.

**Comment by ltGuillaume** [comment]
@henrypp Could you explain why you're loading all these modules into sw address space?

**Comment by Iruberiam** [comment]
Since the recent update, Simplewall started showing "Bad image" to many already installed applications. Now I can't get the application window to show even after uninstallling and reinstalling. It's apparently installed but I can't configure it,  Process Hacker shows it running as a suspended task.

**Comment by badwhing** [comment]
badwhing, badwhing, bahhdwhinngggg!! This is the sound i keep hearing now. Along with the badimage. Ever since updating to 3.1 i keep getting that annoying sound and bad image popup!!!
I then went back to the 3.09 version and it was working normally again, however i got another popup message saying to update to a new version and i was dumb enough to do it again and started getting the annoying issues again. However this time i tried using the powershell tip and it fucked things up even more! Now when i go back to the 3.09 version i am getting the badwhing, badwhing, bahhdwhinngggg sounds and badimage popups all! This sucks too this product was actually really good and a great way to kill it is by not even providing any feedback!

**Comment by cghub-io** [comment]
Yea. Such a great program but the developer seems quiet about the bug. 
Hmmm. Henry, You might loose potential users if you don’t make any comments on such serious bugs.

**Comment by JoeBarouneD** [comment]
I switched to Netstalker, as the dev is not answering anymore ...

**Comment by Iruberiam** [comment]
Downgraded to 3.09, the popup still appears though, so I temporarily uninstalled the offending program to prevent the bad image message. Simplewall seemed to fill a necessary hole in Windows security but now the cons are starting to outweigh the pros. 3.1 appears to be a disaster and the lack of dev feedback is encouraging me to find alternatives.

**Comment by henrypp** [comment]
> Edit : Your PowerShell script doesn't prevent the "Bad image" popup.

Restart SW. And PS script fixed, SW crashed because of StrictHandleCheck.

~~~ps1
set-ProcessMitigation -Name simplewall.exe -Enable BottomUp,HighEntropy,DisableExtensionPoints,MicrosoftSignedOnly,BlockRemoteImageLoads,BlockLowLabelImageLoads
~~~

**Comment by henrypp** [comment]
> Could you explain why you're loading all these modules into sw address space? Are you using any hooks? What changed between 3.1 en 3.0.9?

SW does not load anything not listed in his export, all this BadImages  because of 3rd party apps who force injecting his DLL's into SW address space. It's not good!

**Comment by Iruberiam** [comment]
Thanks for the response however the PS script does not solve the issue.
This is with SW 3.09

![image](https://user-images.githubusercontent.com/25612005/75266941-03befa00-57eb-11ea-8439-6661327e234f.png)

**Comment by henrypp** [comment]
> Thanks for the response however the PS script does not solve the issue.
> This is with SW 3.09

For 3.0.9 reset Mitigation policy:
~~~ps1
set-ProcessMitigation -Name simplewall.exe -Disable MicrosoftSignedOnly
~~~

**Comment by Iruberiam** [comment]
Thank you.
Yes, that works for 3.09. The previous recommended script does not work for 3.1 here.

**Comment by JoeBarouneD** [comment]
Couldn't you just revert the memory protection changes, instead of giving powershell commands that doesn't work (as for 3.1) ?

**Comment by ltGuillaume** [comment]
> SW does not load anything not listed in his export

Could you please explain what you mean by this? 😃 I'd like to learn what's going on here. What _is_ listed in which "export"?

> all this BadImages because of 3rd party apps who force injecting his DLL's into SW address space and SW resist

So, [PISMO File Mount](http://pismotec.com/pfm/ap/), MacType, Bandicam, Oldnewexplorer, VirtualBox etc. all try to inject their DLL into simplewall's address space? It seems like at least some of these have to do with Explorer shell extensions, right? Why would they want to inject into simplewall address space?

**Comment by henrypp** [comment]
> Could you please explain what you mean by this? 😃 I'd like to learn what's going on here. What _is_ listed in which "export"?

[Here is simple answer.](https://lmgtfy.com/?q=pe+file+import+address+table)
ps: not "export", but "import", although it doesn’t matter.

> It seems like at least some of these have to do with Explorer shell extensions, right? Why would they want to inject into simplewall address space?

This question is not under my knowledge. Ask them, "why".

[![sshot-001](https://user-images.githubusercontent.com/3902025/75363383-40225100-58e4-11ea-8a5d-92e14da8ac4c.png)](https://github.com/snowie2000/mactype#known-issues)

**Comment by Lexua1967** [comment]
I have the same with **ELshellkhook64.dll** (EveryLang v5)
![simplewall](https://user-images.githubusercontent.com/61548962/75450391-634a1080-5977-11ea-95be-006504a25315.png)

**Comment by Iruberiam** [comment]
Thanks for the update to 3.1.1, sadly the issue with 'bad image' is still present. I've also tried the 1st PS script and restarted simplewall.

**Comment by henrypp** [comment]
@Iruberiam run this:

~~~ps1
set-ProcessMitigation -Name simplewall.exe -Disable MicrosoftSignedOnly
~~~

**Comment by Iruberiam** [comment]
That did it, thank you.
