### ISSUE TITLE
Corrupt log encoding

### ISSUE THREAD

**Issue by kmm2** [henrypp/simplewall#613]
On Windows 7 the log is corrupt, it looks like Unicode but no app can open it properly. Check the sample [simplewall.log](https://github.com/henrypp/simplewall/files/4189327/simplewall.log)

Tested on simplewall-2.4.6 and simplewall-3.1.

OK on Windows 10.

**Comment by henrypp** [comment]
Not confirmed. Are you sure log file doesn't touched by thirdparty?

**Comment by kmm2** [comment]
Default installation of simplewall, no third parties.
Windows 7 set to US/Eng location/encoding.

**Comment by kmm2** [comment]
More observations:

- if I overwrite the first two 0x00 bytes of the log ("utf-16 le byte order mask") with "{0xFF, 0xFE}", it displays properly.

- according to your source code, there should be a "csv header" just after the "utf-16 le byte order mask" but I do not see it Win7 nor Win10.

**Comment by henrypp** [comment]
When you remove log file manual and start SW, byte order mask & csv header added correctly?

**Comment by kmm2** [comment]
Yes, it works this way, mask/csv OK, thanks!
Will there be a permanent fix for it in a future SW version?

**Comment by henrypp** [comment]
I need to know who/what action corrupt the log, then fix out

**Comment by kmm2** [comment]
If you want me to test, modify or run something, please let me know.

Thanks for the best Windows firewall!

**Comment by henrypp** [comment]
If it happpens again just let me know what steps you do.
