### ISSUE TITLE
Struggle with IP ranges in ipv6

### ISSUE THREAD

**Issue by Janaue** [henrypp/simplewall#614]
Hello

I do not understand how to create a custom rule with IP range for ipv6. THis is on w10 in order to allow my devices to be seen in the ''network'' folder of w10. for instance simplewall says windows want to connect like this, when I click ''discover devices'',
[fe80::2057:xxxxx:xxxxxx:xxxxx]:59006, inbound, UDP, svhost.exe
[fe80::6157:yyyyyyyyy:yyyyyyyyy:yyyyyy]:53126, inbound, UDP, svhost.exe
lots of connections with dashost.exe and system too.
Since i have lots of devices on my routeur and running w10 and seen on my ''network'' folder , I want to generalize the rule to allow all my devices with IPv6 on my local LAN to be seen from my current device where i configure simplewall. How do I do this ?

**Comment by henrypp** [comment]
ipv6 is assigned for link-local addresses `fe80::/10` mask.

**Comment by Janaue** [comment]
can you add this example at https://github.com/henrypp/simplewall/wiki/Rules-editor like you did with 192.168.0.0/16 and so on

**Comment by Janaue** [comment]
can i use the CIDR notation with ports too
eg = 192.168.0.0/16:443 or [fe80::/10]:8080 ?

**Comment by henrypp** [comment]
> can you add this example

ok

> can i use the CIDR notation with ports too

No, it wont work, And correct example is without brackets `fe80::/10`.
