### ISSUE TITLE
Not sure if it's an issue or just mee being a noob :D But for Simplewalll. . .

### ISSUE THREAD

**Issue by MagEnhance** [henrypp/simplewall#615]
Hi im having the issue that in bf4 i have connection but  im getting kicked for not having my ping being visable, if i disable the filter ping appear right back but i dont want to do this for more then a few seconds or else all hell breaks loos on my non updated widows 10 version 1511 pc and im loving this app it dose a great job at blocking. . .   Any help is much appreciated

**Comment by cloudgreen** [comment]
Hi @MagEnhance! Check the ICMPv4 rule under "User rules" tab. I actually searched this forum for "ping" myself to find [this post that described it](url=https://github.com/henrypp/simplewall/issues/589). :D

**Comment by MagEnhance** [comment]
Okay will try that and thanks for the swift reply 😀 is this the owner ?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by MagEnhance** [comment]
I only need to tick that box ? shouldent i seletc only for specific apps too ? cant just allow for all apps right ?

Sent from [ProtonMail](https://protonmail.com), Swiss-based encrypted email.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by cloudgreen** [comment]
Yes, as far as I know ICMP can only be enabled for the whole "host" (computer) and not for specific application.

I'm now the owner, just a Simplewall user. :)

**Comment by MagEnhance** [comment]
Okay well it works great after fresh install and Simplewall my game has never run so smooth wauw 😁 besides Simple wall what else do you run for protection ?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by cloudgreen** [comment]
I'm happy to hear it works well! :D

My computer is behind a NAT router and I installed Simplewall for getting better control over "phone home" applications, which it does nicely. :) Other than that, I'm just using Windows 10's built-in antivirus. How about you?

**Comment by MagEnhance** [comment]
Same about nat on router and for now windows built in, but at times i use bitdefender. . .do yo game bf4 alot ?

Sent from ProtonMail mobile

-------- Original Message --------
