### ISSUE TITLE
Update dialog still isn't fixed

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#616]
I've had the update dialog still getting stuck at 100% indefinitely with v3.1
![image](https://user-images.githubusercontent.com/4777345/74535259-bebade00-4f35-11ea-9fba-9eeaebdb831e.png)

**Comment by asvc** [comment]
Slightly different issue here:
![2020-02-15 10_31_26-simplewall  WIN_asv](https://user-images.githubusercontent.com/300146/74577344-8cb18680-4fde-11ea-99d7-37f581cc8fae.png)
