### ISSUE TITLE
Installed latest 3.1 version and same issues as before

### ISSUE THREAD

**Issue by tomasts248** [henrypp/simplewall#617]
So I decided to give it a try in case the errors I had in the past were solved https://github.com/henrypp/simplewall/issues/582 But again I can't upload images to wordpress, nor upload images or other stuff to gmail, and borwsing is slow, getting errros such  as "corrupted content". Tell how can we debug this please.

**Comment by cloudgreen** [comment]
Hm, you are saying that general web browsing is slow with Simplewall installed?

**Comment by tomasts248** [comment]
> 
> 
> Hm, you are saying that general web browsing is slow with Simplewall installed?
Well that also happens though, the bigest problem is that I can't upload files.

**Comment by cloudgreen** [comment]
As long as you have enabled the "HTTP" rule for your browser of choice, say Firefox, I have a hard time understanding how Simplewall could prevent you from uploading via your browser. Does it work without Simplewall?

![image](https://user-images.githubusercontent.com/42112877/74592022-7d9df900-501d-11ea-82ea-6a200652424c.png)

**Comment by tomasts248** [comment]
> "As long as you have enabled the "HTTP""

It is enabled. 

> Does it work without Simplewall?

It used to that's why I uninstalled it, but now even if I uninstall it the problem persists. Could it be related to the Windows Firewall?

**Comment by cloudgreen** [comment]
The thing to understand is that Simplewall is a management interface for the Windows Firewall. Or to be correct, a management interface for the underlying firewall platform called Windows Filtering Platform ("WFP").  Via Windows Firewall, you manage the Windows Filtering Platform as well.

When you uninstall Simplewall, I believe any changes you have done will still be in effect in the underlying WFP. You could try and reset all Windows Firewall rules to their defaults. Start "WindowS Defender Firewall" and click the "Restore Default Policy" button to the right. Or you can use the command prompt, see below.

https://www.ghacks.net/2007/12/19/reset-the-windows-firewall/

There was another issue (#598 ) about this a couple of days ago, where the poster had problems with problems persisting after uninstall. He solved it by re-installing Simplewall, configuring rules and then uninstalling again.

Good luck!

**Comment by tomasts248** [comment]
Thank you so much!! I understand now!!
 I think I figured out. There was another firewall installed (Evori Free Firewall) I had forgotten about.. Uninstalled it and things work fine now. Well I also reset the windows 7 firewall as well as running: "netsh int ip reset" and "ipconfig /renew" in the console, but I suppose it should be enough uninstalling the other firewall. Thanks again and have a nice week!! =)

**Comment by cloudgreen** [comment]
@tomasts248 You're welcome, I'm glad you solved it! :) Firewalls can be messy indeed...

You can probably mark this issue as closed/resolved now? Take care! :)

**Comment by tomasts248** [comment]
>  You're welcome, I'm glad you solved it! :)

=)

> You can probably mark this issue as closed/resolved now? Take care! :)

Definitely yes! thanks for everything! you too! :)
