### ISSUE TITLE
Rule for random IP (Luminati)

### ISSUE THREAD

**Issue by duzers** [henrypp/simplewall#618]
![2020-02-16_18-55-35](https://user-images.githubusercontent.com/1188931/74687925-1ecfaf80-51d6-11ea-8681-9aff5d211dfc.jpg)
I use proxy which returns **random IP** (zproxy.lum-superproxy.io:22225). What rule to add to allow connection for selected program?

**Comment by ltGuillaume** [comment]
Do you have Rules -> Resolve network addresses enabled?

**Comment by duzers** [comment]
> Do you have Rules -> Resolve network addresses enabled?

Yes, I do. Do I have to disable it?

**Comment by ltGuillaume** [comment]
No, that would be necessary to make it work. Have you tried without adding the port at the end?

**Comment by duzers** [comment]
I tried without port, also. Yes, IP is different every single time of connection.
Well.....Thanks for your trie to help.

**Comment by duzers** [comment]
I added only port.

**Comment by ltGuillaume** [comment]
Oh yeah, that's a good way, too 😊
