### ISSUE TITLE
Uses non-default language after installation

### ISSUE THREAD

**Issue by AnnanFay** [henrypp/simplewall#621]
I just installed simplewall and it's displaying everything in Japanese. I have the Japanese language pack installed but it's not the default language. My Japanese isn't nearly good enough to figure out how to change the language.

Here's a screenshot showing the application as it appeared after running for the first time and my language settings. I am using Windows 10 Pro with latest updates.

![image](https://user-images.githubusercontent.com/766048/75168680-34d1f880-571f-11ea-8955-16fc58fd8425.png)

**Comment by AnnanFay** [comment]
I got around the issue for myself by deleting Japanese from `simplewall.lng`.

**Comment by henrypp** [comment]
Maybe this is bug.

![sshot-001_proc](https://user-images.githubusercontent.com/3902025/75339130-1c4a1580-58ba-11ea-8d25-5108c353b8fc.jpg)
You can change language in menu. Language submenu always displays in international locale or in settings (press F2) on 1st page.
