### ISSUE TITLE
Yo man FU

### ISSUE THREAD

**Issue by zizzu0** [henrypp/simplewall#622]
Nice program man, at first it won't autostart with windows, so ofc i uninstalled it, but guess what?

That didn't remove the changes it did. Only those programs allowed before uninstalling were able to connect to the internet.

I gone crazy uninstalling everything else while the suspect that your program was the cause was growing in my mind and at the end i reinstalled it and YES. Your program was the cause.

Which kind of windows shitty technology are you using behind this abort?

So where are those changes left? Have i to read Windows source code which noone knows becouse this is a dead operating system to understand how to remove the changes your program does?

Nice JOKE MAN.

**Comment by Iruberiam** [comment]
You could try and see if resetting the Windows Firewall will restore your connections. https://www.ghacks.net/2007/12/19/reset-the-windows-firewall/

**Comment by henrypp** [comment]
You can't read and i am joker?

![sshot-002](https://user-images.githubusercontent.com/3902025/75338699-5c5cc880-58b9-11ea-943e-da37538849f1.png)
