### ISSUE TITLE
Updating progress freezes at 100%

### ISSUE THREAD

**Issue by aha999** [henrypp/simplewall#624]
When it says that the update is available, i press Yes to download. Then it opens a small window with download progress and when it comes to 100% it just stops and does nothing and it stays like that.

![NqAMCPuOwC](https://user-images.githubusercontent.com/50620416/75548406-791a0d00-5a2d-11ea-94e1-4edaf7b04816.png)

**Comment by hhrhhr** [comment]
Confirm this.
Also, after clicking "cancel" and try to manually check for updates, then:
![s1](https://user-images.githubusercontent.com/966048/75558868-834f0200-5a53-11ea-95bc-0546c080a7fa.png)
![s2](https://user-images.githubusercontent.com/966048/75558877-8649f280-5a53-11ea-84e7-95b660b83766.png)

**Comment by henrypp** [comment]
version 3.1.1 already fixed this

> fixed update window does not close (issue #616)
