### ISSUE TITLE
Detected as RDN/Generic.dx

### ISSUE THREAD

**Issue by crazyyzarc** [henrypp/simplewall#625]
Why is the new simplewall version declared a trojan?

Detected as: RDN/Generic.dx
Thread process name: C:\Windows\System32\RuntimeBroker.exe
File name: C:\Users\User\Downloads\simplewall-3.1.1-setup.exe
AV: McAfee VirusScan Enterprise

https://www.virustotal.com/gui/file/9473863df5d14058699bacc2d8956c83b146238b6824e65a25e8185679415ad5/detection

**Comment by cloudgreen** [comment]
@henrypp Do you have any more "comforting" information to give your users? :)

**Comment by henrypp** [comment]
> Why is the new simplewall version declared a trojan?

where from the hell i know, ask them "why"

**Comment by cloudgreen** [comment]
Friendly. :)

**Comment by henrypp** [comment]
> Friendly. :)

Cure, [i love false-positive threads](https://github.com/henrypp/freeshooter/issues/29#issuecomment-556034764)

**Comment by cloudgreen** [comment]
> 
> 
> > Friendly. :)
> 
> @cloudgreen cure, [i love false-positive threads](https://github.com/henrypp/freeshooter/issues/29#issuecomment-556034764). ;)

That was an interesting thread, good that you linked it!

@henrypp Keep up the great work, you rock! :D
