### ISSUE TITLE
Shares for network drives effectively

### ISSUE THREAD

**Issue by soboknilch** [henrypp/simplewall#629]
Programs that are based on network releases are recognized, but the rules are effective.
The problem is the double "\\" this is only recognized as '\' or a '\' is done.

**Comment by henrypp** [comment]
What problem do you describe?

**Comment by soboknilch** [comment]
The problem comes with network drives.

Example:
\\server\path\putty.exe

Simplewall interpretation:
\server\path\putty.exe

A **\** is missing from the rules, so it always says "file not found"
Because the path is not correct in the SimpleWall rule

**Comment by henrypp** [comment]
Looks like a bug. Checking.

**Comment by henrypp** [comment]
Can you add  "\\server\path\putty.exe" into SW apps list manually?

**Comment by soboknilch** [comment]
If I write it into the "profile.xml" by hand or adjust the existing entry - it is displayed correctly in the Simplewall Gui but the entry does not work.

As soon as I start "putty" via the network drive, Simplewall comes back and wants to write a new rule. He doesn't recognize that there is already one.

**Comment by henrypp** [comment]
this bug is fixed https://github.com/henrypp/routine/commit/09a07613f83ab7c984bd2f52b11133bf7df45bb3, wait for release
