### ISSUE TITLE
IDM integration module

### ISSUE THREAD

**Issue by Freddynic159** [henrypp/simplewall#63]
In version 2 (until the most recent) there is a problem with the program Internet Download Manager (IDM) because it's Integration Module doesn't work after installing the filters and only appears this message.

![37462343152_d0e5144229_o](https://user-images.githubusercontent.com/7980100/31180171-27eafa12-a8db-11e7-8cd2-9fb913f09595.jpg)

In version 1 (until version 1.6.5) this problem didn't exist.

I hope there's some way to fix it.

**Comment by henrypp** [comment]
Executable paths allowed? Stealth-mode enabled?

**Comment by Freddynic159** [comment]
Yes, executable paths is allowed, I have also tried stealth mode on and off, but the problem persists.

**Comment by henrypp** [comment]
What on log?

**Comment by Freddynic159** [comment]
[‎04/‎10/‎2017 ‏‎09:55:29 a.m.] <empty> (<empty>) [UDP:10.129.49.181:52765 (from 8.8.4.4:53)] simplewall\BlockTcpRstOnCloseV4 [In]
[‎04/‎10/‎2017 ‏‎09:55:29 a.m.] <empty> (<empty>) [ICMP:8.8.4.4] simplewall\BlockIcmpErrorV4 [Out]
[‎04/‎10/‎2017 ‏‎09:55:29 a.m.] <empty> (<empty>) [UDP:10.129.49.181:59446 (from 8.8.4.4:53)] simplewall\BlockTcpRstOnCloseV4 [In]
[‎04/‎10/‎2017 ‏‎09:55:29 a.m.] <empty> (<empty>) [UDP:10.129.49.181:59879 (from 8.8.8.8:53)] simplewall\BlockTcpRstOnCloseV4 [In]
[‎04/‎10/‎2017 ‏‎09:55:29 a.m.] <empty> (<empty>) [UDP:10.129.49.181:59259 (from 8.8.8.8:53)] simplewall\BlockTcpRstOnCloseV4 [In]
[‎04/‎10/‎2017 ‏‎09:55:29 a.m.] <empty> (<empty>) [UDP:10.129.49.181:61095 (from 8.8.8.8:53)] simplewall\BlockTcpRstOnCloseV4 [In]
[‎04/‎10/‎2017 ‏‎09:55:29 a.m.] <empty> (<empty>) [ICMP:8.8.8.8] simplewall\BlockIcmpErrorV4 [Out]
[‎04/‎10/‎2017 ‏‎09:55:29 a.m.] <empty> (<empty>) [UDP:10.129.49.181:59879 (from 8.8.4.4:53)] simplewall\BlockTcpRstOnCloseV4 [In]
[‎04/‎10/‎2017 ‏‎09:55:29 a.m.] <empty> (<empty>) [UDP:10.129.49.181:59259 (from 8.8.4.4:53)] simplewall\BlockTcpRstOnCloseV4 [In]
[‎04/‎10/‎2017 ‏‎09:55:29 a.m.] <empty> (<empty>) [UDP:10.129.49.181:61095 (from 8.8.4.4:53)] simplewall\BlockTcpRstOnCloseV4 [In]
[‎04/‎10/‎2017 ‏‎09:55:29 a.m.] <empty> (<empty>) [UDP:10.129.49.181:64229 (from 8.8.8.8:53)] simplewall\BlockTcpRstOnCloseV4 [In]
[‎04/‎10/‎2017 ‏‎09:55:30 a.m.] <empty> (<empty>) [TCP:10.129.49.181:1461 (from 192.30.253.125:443)] simplewall\BlockTcpRstOnCloseV4 [In]
[‎04/‎10/‎2017 ‏‎09:55:30 a.m.] <empty> (<empty>) [TCP:10.129.49.181:1461 (from 192.30.253.125:443)] simplewall\BlockTcpRstOnCloseV4 [In]
[‎04/‎10/‎2017 ‏‎09:55:40 a.m.] C:\windows\syswow64\svchost.exe (NT AUTHORITY\SYSTEM) [UDP:107.182.238.152:6057 (from 10.129.49.181:60269)] simplewall\Block all outbound connections [Out]

**Comment by henrypp** [comment]
There is only entries from stealth mode (BlockIcmpErrorV4/BlockTcpRstOnCloseV4) and one from service (svchost.exe), not too much. Are you trying, what says IDM when uninstall simplewall filters?

**Comment by Freddynic159** [comment]
The IDM integration module works perfectly after uninstalling the filters.

**Comment by henrypp** [comment]
If IDM is blocked it will be listed in dropped packets log file. Can you find any?

**Comment by Freddynic159** [comment]
I have searched but there is nothing related to IDM.

**Comment by Freddynic159** [comment]
I've found a way to fix it.

It seems that it is necessary to allow explorer. exe for the IDM integration module to work properly.

Anyway, it's a bit strange because in version 1 (until version 1.6.5) this wasn't necessary.

**Comment by henrypp** [comment]
Maybe IDM changed shell extension plugin, maybe 2.x have lot of bug fixes!

**Comment by Freddynic159** [comment]
Well, I think this issue can be considered closed ;)
