### ISSUE TITLE
[Proposal] Need more simple: remove any built-in thing

### ISSUE THREAD

**Issue by ahdung** [henrypp/simplewall#630]
I don't want these:

![image](https://user-images.githubusercontent.com/12094247/76068257-cbc66c80-5fcb-11ea-8e27-a1a1bcd90050.png)

![image](https://user-images.githubusercontent.com/12094247/76068298-de40a600-5fcb-11ea-8779-80a4de7fec62.png)

![image](https://user-images.githubusercontent.com/12094247/76068537-45f6f100-5fcc-11ea-905c-d20f6557e653.png)

![image](https://user-images.githubusercontent.com/12094247/76068577-5909c100-5fcc-11ea-850d-b1070f93b560.png)

Please consider release/create a more lightweight edition/branch, Thanks.

**Comment by henrypp** [comment]
Install "profile_internal.xml" into profile directory and restart SW.

[profile_internal.zip](https://github.com/henrypp/simplewall/files/4297655/profile_internal.zip)

NB: This is a dirty hack, and did not tested correctly.

**Comment by ahdung** [comment]
It seems worked, thank you.

**Comment by ahdung** [comment]
@henrypp Your link should be [.zip](https://github.com/henrypp/simplewall/files/4297655/profile_internal.zip) not .xml.

**Comment by henrypp** [comment]
Added option for this request. Read commit notes.
