### ISSUE TITLE
HTTP Rule

### ISSUE THREAD

**Issue by Git-SpaceJanitor** [henrypp/simplewall#631]
Your default user rule for HTTP contains ports 80, 443, 8000, 8008, 8080, 8443-8444. Whats the logic behind this / maybe I have an infected version?

![Rules](https://user-images.githubusercontent.com/51430625/76371572-ac4f7c80-6308-11ea-881e-62b1db6603d0.png)

**Comment by henrypp** [comment]
There is no standard about that, but port `8443` is sometimes known as the **http-alt**.

https://www.speedguide.net/port.php?port=8443

https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=http-alt

Source: https://stackoverflow.com/a/32478278
