### ISSUE TITLE
Improve network alert

### ISSUE THREAD

**Issue by xnoreq** [henrypp/simplewall#637]
Currently, this information is provided:
![grafik](https://user-images.githubusercontent.com/4028859/77184693-6fd20c80-6ad0-11ea-9dcd-078ede87b63e.png)

In case of inbound this just gives us the source address (and source port I _assume_) and in case of outbound it just gives the destination address and port.

1. Could you please add destination ("local") information for inbound and source ("local") information for outbound?

Each network alert steals the focus which can be very annoying and interrupting.

2. Could you please add an option to still show the network alerts but NOT requesting focus?

And alternative would be not showing the network alerts window but sending a Windows notification instead. Clicking the notification would then open the network alerts window with all the missed alerts.

edit: 
Creating a rule based on an inbound network alert only does not fill in the local address.

3. Please fill both remote and local addresses (if available) when creating a new rule.

**Comment by SeriousHoax** [comment]
I also think color wise there should be some difference between outbound and inbound connection notification.

**Comment by henrypp** [comment]
> In case of inbound this just gives us the source address (and source port I _assume_) and in case of outbound it just gives the destination address and port.

Network alerts displays only remote address information, because local address are used local network ip's or empty (0.0.0.0)

> Could you please add an option to still show the network alerts but NOT requesting focus?

This is UI bug and fixed now.

**Comment by xnoreq** [comment]
> Network alerts displays only remote address information, because local address are used local network ip's or empty (0.0.0.0)

The information is actually very important and it's not just the IP address but also the port.

What does "Remote: x.x.x.x, Port: 56832, Inbound" tell you? Nothing.

This could have been an inbound connection to some svchost service, a http server, a ssh server ... 
Right now, to find out what the destination was, I have to enable the log, then search for the remote port and then in the log line it also gives me the local address & port.

Please add this.

Also, instead of having two fields for the address and port you could just do: "<IP>:<Port>" in a single line.

Lastly, the local IP address is also very important. Use cases are multiple interfaces with different IPs, broadcasts, multicasts, etc.

**Comment by merentitis** [comment]
Displaying Destination IP:Port for inbound connections would be very useful.
Right now, I see for example an inbound source port 3115 trying to connect to svchost.exe and have no clue what protocol it is trying to use (RDP?, mDNS?, RPC?,...)
