### ISSUE TITLE
[UI] Grid improvement [enhancement]

### ISSUE THREAD

**Issue by pwn0r** [henrypp/simplewall#64]
Hi again :)

Been testing all beta versions and now 2.14 is really looking awesome, a lot of UI has been improved and it more or less makes sense now :)))

Still, for the main windows grid list, it is methodologically incorrect to split apps only in two groups, i.e. Blocked and Allowed. It should be three groups minimum: Blocked completely, Allowed and Filtered apps.
The Filtered group is for the apps which have custom filters on, it should be in the middle then. 

I noticed you use colours to classify different apps like System, Signed, Having Filters, Disabled notifications etc. Whilst per se it is a good thing, having too many such colours makes UI too busy and not straightforward to use.  Suggesting to rework the colour system and reduce the number of colours, but that's not very important atm, I guess.

**Comment by henrypp** [comment]
> It should be three groups minimum
Ok, i will keep in mind!

> having too many such colours makes UI too busy
Colors is not cause of UI busy. Colors make UI better because of displaying information in colors+tooltip scheme and list displaying not like blank list.
