### ISSUE TITLE
UNC path added from notification window missing second backslash

### ISSUE THREAD

**Issue by ghysler** [henrypp/simplewall#641]
Whenever I allow or deny a program located on the network from the notification window, the added rule is missing the second backslash, which renders the added rule invalid. 

ie.: \192.168.1.1\filename  instead of  \\\192.168.1.1\filename

I believe this issue first appeared in version 3.0, but could be before that. Could you look into this?

When adding files to the list manually, the mounted drive letter is used instead of the UNC path, and this works as expected.

**Comment by henrypp** [comment]
hello, this bug are already fixed (#629), just wait for release.

**Comment by ghysler** [comment]
Ah, completely overlooked that issue, sorry. Thanks for the quick response!
