### ISSUE TITLE
will it run on a normal user account?

### ISSUE THREAD

**Issue by edpanes** [henrypp/simplewall#642]
I tried the following:

1. download and install it from a normal user account.
2. installed it via 'run as administrator'
3. everything worked well and as expected. changed the settings to auto start.
4. i rebooted my machine and logged back in as the normal user
5. simplewall icon did not appear (in the task bar icons) and couldn't find the item on my start menu (understandable because i installed it using admin)
6. switched to the admin and found the program there. 

q1) so should i be using an admin user in order to fully utilize the app? because it might be running in the background but no pop ups are being displayed.
q2) should i tell it to start as an admin user everytime i login as a normal user to solve this problem?

**Comment by Mateusresende** [comment]
I have the same problem.
I'm using windows enterprise. I may have disabled the start functions and don't remember. It does not start. How can I explore all options to check why it doesn't start automatically?

And he doesn't even show up on tasks.
I thought it was starting minimized. Nor was that.

I always have to start it manually.

**Comment by edpanes** [comment]
you can login as the administrator account and you will see be able to open the app and make the changes.

**Comment by Mateusresende** [comment]
My account is an administrator!

**Comment by Mateusresende** [comment]
New version fixed! congratulations!

**Comment by edpanes** [comment]
which version are you now on?
