### ISSUE TITLE
VirusTotal / WinDefender false-positive

### ISSUE THREAD

**Issue by asvc** [henrypp/simplewall#644]
Seems like v3.1.2 gets flagged. Pushed the binary to Microsoft for white-listing: https://www.microsoft.com/en-us/wdsi/submission/c44e59f6-bcdb-4164-9e7a-51d85bd4399a

**Comment by henrypp** [comment]
Thank you for your help!
Seems like it may decrease false-positive detections count.

**Comment by henrypp** [comment]
There is no more FP. Thank you all!

x86 - https://www.virustotal.com/gui/file/19f6d898ccdded140e9caf359494e46f8145681f977bd4cfb48cf0a8804f2837/detection
x64 - https://www.virustotal.com/gui/file/001aca930254743b8f1197dc336bb7d47ca27985629af15602c27ff2ed3a5449/detection
