### ISSUE TITLE
/uninstall not removing filters installed by /install argument

### ISSUE THREAD

**Issue by rover886** [henrypp/simplewall#645]
How to generate this issue:

1. Open command prompt
2. Navigate to simplewall installation folder
3. Hit command `simplewall.exe /install /silent`, this will install the filters.
4. Now, hit command to uninstall filters as `simplewall.exe /uninstall`. This will prompt message as "This will restore network access for all apps that are currently blocked. Continue?" Click on button "Disable filters"

After this command prompt returns but it seems that filters are not uninstalled or disabled. I can see a debug log is generated, that file is attached.

Also, is there any /silent argument to /uninstall argument (same as like for /install), to skip the prompt while disabling filters? I tried `simplewall.exe /uninstall /silent` but still gives message prompt ""This will restore network access for all apps that are currently blocked. Continue?""

I am using :

Windows 7 64 Bit
simplewall 3.1.2

[simplewall_debug.log](https://github.com/henrypp/simplewall/files/4391904/simplewall_debug.log)

**Comment by henrypp** [comment]
> Open command prompt

There error at first step, administrator rights is required and start command prompt from admin.

> Also, is there any /silent argument to /uninstall argument (same as like for /install), to skip the prompt while disabling filters? I tried `simplewall.exe /uninstall /silent` but still gives message prompt ""This will restore network access for all apps that are currently blocked. Continue?""

Silent uninstall is a breach which allow anyone to delete filters silently.

**Comment by rover886** [comment]
> There error at first step, administrator rights is required and start command prompt from admin.

I confirmed that command prompt is running with administrator rights.

**Comment by rover886** [comment]
@henrypp I run same command on 4 machines on command prompt which is run as administrator. /install works but /uninstall doesn't.

Please check this video which shows though the command prompt is opened as "Administrator" error is coming while /uninstall. https://drive.google.com/open?id=1-EMGC0py6xpz603bjNgFA3uRPW6jbeYy

**Comment by henrypp** [comment]
Ok, this is bug.

**Comment by rover886** [comment]
> Silent uninstall is a breach which allow anyone to delete filters silently.

Thanks @henrypp  for fixing bug. About silent uninstall, I think applying filters silently is not enough. If a person applying filters silently then of course he wants (or he may wants) to remove it silently. 

**Take my use case:** I am developing a software for students for online examination, so I don't want while giving exam anyone could able to browse internet (other than exam website). I will embed simplewall in my application (of course with LICENSE note), and install filters silently when student starts the exam and uninstall it when exam gets finished. In this scenario if "Disable Filter" popup message gets displayed then it's out of the context of exam software (or any implementing/embedding software). 

Like above, if anyone wants to use simplewall as a command line solution with silent install and uninstall feature (like topping over the ice-cream) in his application, then he have to take care that no one (other than application) should able to uninstall filters.

I just opened my mind about this, I will create pull request for this after making small (if condition) change. Wether to merge it or not is in your hand :pray: :slightly_smiling_face:

**Comment by henrypp** [comment]
done. it can be set in next version.
