### ISSUE TITLE
LogViewer attribute does not accept manually changed value in config.ini

### ISSUE THREAD

**Issue by MPeti1** [henrypp/simplewall#646]
I've noticed yesterday that I could set up something better than the normal notepad to be used for viewing the logs. I wanted to try that out, so following your [instructions](https://github.com/henrypp/simplewall/wiki/FAQ#how-can-i-use-3-rd-party-software-to-view-log) I downloaded CSVFileView from NirSoft, copied the .exe file besides the config file and added the LogViewer attribute to the settings.ini file.

Ok, first I didn't copy it there, because I wanted to store the exe at a place where I already store NirSoft utilities, but included it's full path in the settings file. But after it didn't work, I've copied it to the same folder in which the settings file is, and tried to use the relative path `.\csvfileview.exe`, and it still didn't work.
In the end I've found that there is also a convenient way to change the log viewer in the settings window, and this way it was working even with the path that included spaces.

I've checked the settings file after changing the log viewer in the settings window, and I don't see the difference between the path here and the path that I previously inserted, except that it shortened the beginning of the path to `%USERPROFILE%\`.
It seems that currently that setting value only works as a read-only one, if you want to change it by hand

**Comment by henrypp** [comment]
Path relative not from settings.ini, but current directory of simplewall (%CD%) and before changing options in settings.ini you need to shutdown simplewall.

**Comment by MPeti1** [comment]
> Path relative not from settings.ini, but current directory of simplewall
What is the current working dir of Simplewall? I think this should be included in the wiki

> and before changing options in settings.ini you need to shutdown simplewall
What counts as a shutdown? Is it choosing "Exit' in the "File" menu? If it is, I did that every time after modifying and saving the file
