### ISSUE TITLE
[UI] [cosmetic] tooltip 

### ISSUE THREAD

**Issue by pwn0r** [henrypp/simplewall#65]
Tooltip (on a grid in the main window) appears slightly wrong:
The first line is the path to the app in question and then it says "Path:" in the second line. 
Then it follows with a name and signature (if any). So "Path" either should be first or maybe even better to get rid of that line completely.

**Comment by henrypp** [comment]
Path may have different length and complete not fit in control, thats why i decided add tooltips: _hover "Path" control and you will see full path_.

**Comment by pwn0r** [comment]
I'm not sure you referring to the same issue

![tooltip](https://user-images.githubusercontent.com/19326623/31498732-b714e0ec-af5a-11e7-9a83-3c083f907aa1.png)

as you can see, there is an actual path and then there is "Path:" which actually is followed by application information.

**Comment by henrypp** [comment]
![sshot-1](https://user-images.githubusercontent.com/3902025/31504286-cc62f9dc-af93-11e7-9009-5ce35afe1a00.png)
![sshot-2](https://user-images.githubusercontent.com/3902025/31504288-ccf18f44-af93-11e7-9f10-c7b4d3e6b4cb.png)
