### ISSUE TITLE
Since 3.1.1 notifications seems broken

### ISSUE THREAD

**Issue by AlphaJack** [henrypp/simplewall#654]
I've had this problem for months, in the hope that an update would fix it.  
After reading [this](https://github.com/henrypp/simplewall/issues/496#issuecomment-572200851) I decided to reinstall all the versions of the program starting from the 3.0 to understand which one caused this error, and it appears to be the 3.1.1, released only a month ago (weird thing since the problem seems older).  
The settings are the same as the previous versions, however I don't get notified (and simplewall.log isn't updated) with new blocked apps, and I have to manually add them.   
The latest working version is 3.1, and I can use it with my 3.1.2 profile.xml file.  
My system is Win7 SP1 64bit

**Comment by temaxdoo** [comment]
Same problem here, system is also Win7 SP1 64 bit: no notifications, no log. Last working version is 3.1. 
On my other PC with Win 10 version 3.1.2 works perfect. Donation is on the way...

**Comment by henrypp** [comment]
@AlphaJack @temaxdoo

Guys, anyone checks in 3.2.2?

**Comment by AlphaJack** [comment]
@henrypp Seems to work, thank you
