### ISSUE TITLE
Dark theme [feature request]

### ISSUE THREAD

**Issue by aha999** [henrypp/simplewall#658]
It would be really nice, if we could have an optional dark theme.

**Comment by anephew** [comment]
+1

thanks

**Comment by goldaryn** [comment]
![Untitled](https://user-images.githubusercontent.com/4416039/81344024-e8efe800-90ad-11ea-9e12-9cb54fee251b.png)

I recently installed Cake OS windows theme and it's not perfect, but it's pretty good.

**Comment by shiftyshady** [comment]
SimpleWall is a win32 app and therefore uses OS default colors.
you can change those colors by editing HKEY_CURRENT_USER\Control Panel\Colors
This feature request should be closed.

**Comment by henrypp** [comment]
SW is uses Windows API to use native theme support, but problem is in Microsoft is not being open documentation for this and no one know when M$ add native support for dark theme for win32 applications.

And now you can use thirdparty dark themes for this.

**Comment by henrypp** [comment]
@fusionneur 

>....but problem is in Microsoft is not being open documentation for this and no one know when M$ add native support for dark theme for win32 applications
