### ISSUE TITLE
[Question] - Undo all changes made by Simplewall

### ISSUE THREAD

**Issue by smarquespt** [henrypp/simplewall#66]
Yesterday I've tried SimpleWall (portable) just to see how it works. I´ve set rules and suddenly al of my apps are unable to access Internet. I've removed the portable folder and restored Windows Firewall default settings, but no luck either. I've also tried to restore system to before but that also didn't work.

So my question is: how can I undo all settings made by simplewall in order to gain Internet access again?

Thanks

**Comment by henrypp** [comment]
Press "Uninstall filters" button, is so obviously.

**Comment by smarquespt** [comment]
@henrypp 

So I did, but that didn't worked. Maybe you can say "Then that's nothing to do with simplewall" and you may be correct but the access to Internet was blocked after my attempt to work with it.

**Comment by smarquespt** [comment]
@henrypp 

Can you advise if this will work?
1 - Install simplewall
2 - Select mode
3 - Apply filters
4 - Remove filters

**Comment by henrypp** [comment]
If filters are installed UI shows "Uninstall filters" button, do not need goto 1 step first. If you are uninstalled filters, button text  changing to "Install filters". Thats all.

If you lose internet access and simplewall filters are not installed - there is not because of simplewall reason.
