### ISSUE TITLE
PowerShell Support [Request]

### ISSUE THREAD

**Issue by TLCPlusPlus** [henrypp/simplewall#660]
`cd <installation folder>; .\simplewall.exe`

That opens the normal GUI if run from PowerShell, would it be possible to add interactions via PowerShell for power users that prefer the text based enviroment? 

If needed, I use the pre-release 1 varient of PowerShell v7 (Latest as of typing on [github](https://github.com/powershell/powershell)).  
Normal win10 users have v3 if they don't grab from github.

**Comment by Tyrix** [comment]
> Normal win10 users have v3 if they don't grab from github.

Default Windows 10 has at least v5 (5.1) 😉
