### ISSUE TITLE
How to load/import txt file with milions ip ranges for blocking?

### ISSUE THREAD

**Issue by AngelTs** [henrypp/simplewall#661]
How this question is not on the first place in your FAQ?!?!?!

**Comment by Mateusresende** [comment]
Can we do it manually by the rules?
If so, how would it be?
And what would be a disadvantage? advantage?

**Comment by AngelTs** [comment]
Doors will always have, the better way is to shut the source.
I am using Peerblock which work perfect, no significant impact of the performance, and blocks currently 800M IPs from the most dark and corrupted countries and territories like Russia, China, Balkans, Asia, South America (most are narco countries).

**Comment by ace2k** [comment]
The WFP is not a caching DNS resolver, even if you somehow manage to import your "800M IPs"  into simplewall, expect all sorts of integrity issues, from memory leaks over random packet drops to entire loss of connectivity. Microsoft specifically discourages from using the WFP as a glorified IP filter.

For that particular purpose there is other software like Pi-Hole, AdGuardHome or eBlocker.

**Comment by asvc** [comment]
...if I might add to the above: it might be lucrative to dump bazillion of record in Windows' `../hosts` file. Do not do it.
