### ISSUE TITLE
Enable GitHub "Sponsor" feature

### ISSUE THREAD

**Issue by savchenko** [henrypp/simplewall#664]
As Microsoft [matches up to $5000 USD total per sponsored developer in their first year](https://help.github.com/en/github/supporting-the-open-source-community-with-github-sponsors/about-github-sponsors)... I thought, why not?

This way, @henrypp receives somewhat boosted revenue stream (if I may label voluntary donations as such) and users will be able to send tokens of support using convenient interface.

**Comment by henrypp** [comment]
Dont know how to use this, but `funding.yml` is not working.

**Comment by asvc** [comment]
Hmm.. I would think about two things:

1. You might have not [turned it on in settings](https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository#displaying-a-sponsor-button-in-your-repository)
2. Try changing custom selector to `custom: ["https://www.paypal.me/henrypp"]`

**Comment by asvc** [comment]
And here is an explanation:

![image](https://user-images.githubusercontent.com/300146/79345901-dda71200-7f70-11ea-8c45-131485475abf.png)

**Comment by henrypp** [comment]
Lol. I think it works more simple, but it needs register your account as sponsor in sponsorship registry.

**Comment by asvc** [comment]
> it needs register your account as sponsor in sponsorship registry.

Well... Update this issue once your registration is approved?
