### ISSUE TITLE
Signature <empty> in notifications

### ISSUE THREAD

**Issue by koro-xx** [henrypp/simplewall#666]
I'm having the issue that all notifications of attempted connections from apps show the app signature as "<empty>" (see for example the attached notification that I got when I launched Microsoft Edge). Is this a bug?
![Simplewall](https://user-images.githubusercontent.com/460962/79384866-0661e400-7f3e-11ea-9a4f-8fde85644c68.jpg)

**Comment by henrypp** [comment]
Signature information is available when SW has "Check for apps digital signatures" option enabled.
