### ISSUE TITLE
Windows 10 Fall Creators Update - firewall service renamed

### ISSUE THREAD

**Issue by duttyend** [henrypp/simplewall#67]
Dear Henry,

They have changed the name of _Windows Firewall_ to _Windows Defender Firewall_.
Installing filters and disabling Windows Firewall from simplewall doesn't work anymore.

Thanks a lot, as always 👍 !

**Comment by henrypp** [comment]
2.0.18 fixed

**Comment by duttyend** [comment]
Working great, thank you very much !!!
