### ISSUE TITLE
your 3.1.2  source code can't be compiled?

### ISSUE THREAD

**Issue by wuji007a** [henrypp/simplewall#670]
i am using visual stdio 2019 to complile your code
the source code version is 3.1.2

these files seem to be missing  

#include "routine.hpp"
#include "rapp.hpp"
#include "..\..\pugixml\src\pugixml.hpp"

why?

**Comment by Tyrix** [comment]
You need to get the submodules "routine" and "builder":

https://github.com/henrypp/routine.git
https://github.com/henrypp/builder.git

**Comment by Tim1Wu** [comment]
@Tyrix Thanks very much  You solved my problem.

**Comment by jjxtra** [comment]
I'm trying to build a dll out of this. I have added the source files from the sub-modules but I still get hundreds of errors like `_r_obj_allocateex not found`. Where is the source code for these missing methods? Even a google or github global search does not yield this method...

**Comment by jjxtra** [comment]
Pulled sub-modules, still does not build
