### ISSUE TITLE
Allow all, except blocked

### ISSUE THREAD

**Issue by kayanco1** [henrypp/simplewall#674]
Hi,

This is the best firewall.

But I am not seeing how to set this:
Allow all programs, unless in Disabled list (blacklisted).

Meaning, I want to allow all programs and only block some I select. So any new program should have access, unless I manually block it. 

Please help. Thanks.

**Comment by ltGuillaume** [comment]
Blacklist mode has been removed since a couple of versions.

Two alternatives you could consider:
- [Firewall App Blocker (Fab)](https://www.sordum.org/8125/firewall-app-blocker-fab-v1-7/)
- [TinyWall](https://tinywall.pados.hu)

**Comment by kayanco1** [comment]
> 
> 
> Blacklist mode has been removed since a couple of versions.
> 
> Two alternatives you could consider:
> 
>     * [Firewall App Blocker (Fab)](https://www.sordum.org/8125/firewall-app-blocker-fab-v1-7/)
> 
>     * [TinyWall](https://tinywall.pados.hu)

Hi,

Can you say why blacklist mode was removed please? 
Any plan of adding it back?

Thank you!

**Comment by ltGuillaume** [comment]
Well, I'm not the one in charge here :p

**Comment by henrypp** [comment]
You can configure Blacklist mode in that way:

- Open settings -> Rules
- Uncheck 2 options: "Block outbound for all" and "Block inbound for all"
- Create user rule (green cross on toolbar) with block action, any direction, "Block connection" name and empty remote and local rule (if you cannot leave it empty, enter * for one of them, it mean empty rule)
- You can assign this rule for apps whatever you want.
- Done!
