### ISSUE TITLE
Problems after I unistalled and removed the filters

### ISSUE THREAD

**Issue by tomasts248** [henrypp/simplewall#675]
So every time my connection is lost or my modem is restarted I have to restart my computer as well  in order to fix not having any upload speed at all. Never had these issues before installing Simplewall, wish I never tried it, sorry to say it but uninstalling it should actually at least reset the computer state as before it was and not this real mess. And for starters why uninstalling doesn't also the remove/disable the filters??

**Comment by ltGuillaume** [comment]
I agree completely: uninstalling simplewall _should_ mean that simplewall's WFP sublayer and its rules would first be completely removed.

Did manually clicking Disable Filters and _then_ uninstalling at least fix your issues?

**Comment by tomasts248** [comment]
`Did manually clicking Disable Filters and then uninstalling at least fix your issues?`
After that it works fine till the connection is reset, then the connection gets messed up (no upload speed/slow browsing). Said that I tried several portable installations such as different versions, before realizing that extra step was needed. So maybe there's a chance one of those installations are still affecting the windows firewall, I'm not sire since I deleted those installation folders.

**Comment by ltGuillaume** [comment]
@henrypp Any way to properly remove sublayer(s) & filters for @tomasts248 ?

**Comment by henrypp** [comment]
dupl #645

**Comment by tomasts248** [comment]
I read the referenced duplicated topic, but what should I do to fix my current issues?

**Comment by henrypp** [comment]
@tomasts248 there is no suggestions, this is a bug and it [was closed in past](https://github.com/henrypp/simplewall/commit/487776de38b1cfba1bffe154231f91f6ca23aefa). now you can use remove filters through UI and wait for command line bugfix release. thats all
