### ISSUE TITLE
 uninstall with command, this rule is still in effect, there is no way to remove it

### ISSUE THREAD

**Issue by wuji007a** [henrypp/simplewall#682]
3.1.2 release

1. I use gui and added a rule to my app
2. I use / install and this rule takes effect
3. I use / uninstall, this rule is still in effect, there is no way to remove it

i found some problems in log files, deletebykey failed ,return 0x00000005
"?2020/?5/?12 ??11:20:45","FwpmFilterDeleteByKey failed()","0x00000005","{2FE14722-D9AC-4199-8D48-7C8579AA3F0B}","3.1.2 Pre-release"
"?2020/?5/?12 ??11:20:45","FwpmFilterDeleteByKey failed()","0x00000005","{D0BEBF67-F14A-45EC-85BE-F13913C98D19}","3.1.2 Pre-release"
"?2020/?5/?12 ??11:20:45","FwpmFilterDeleteByKey failed()","0x00000005","{F495E4ED-3905-48B5-8BF8-5E9618F2F1A8}","3.1.2 Pre-release"

**Comment by henrypp** [comment]
dupl #645
