### ISSUE TITLE
visible Search field option

### ISSUE THREAD

**Issue by aha999** [henrypp/simplewall#685]
One feature that would be nice to be implemented imo would be a search field option, so searches could be made quick and easy. it could be turned off in the view settings. also, when searching, it would be nice if all other results would be hidden that are not included in the search. example of where it could be placed:

![slika](https://user-images.githubusercontent.com/50620416/82203333-77ad0200-9903-11ea-8521-c98fff6977f4.png)

**Comment by henrypp** [comment]
here is discussion topic #663
