### ISSUE TITLE
simplewall 3.0.9 64bit is the last working version on window 7 x64 enterprise sp1

### ISSUE THREAD

**Issue by rg78r** [henrypp/simplewall#687]
As the title.
If you upgrade from 3.0.9 to the next you don't notice the problem, everything works until you have to install a new application that is not in the list.
When this happens the application is not seen and no notification icon to accept or block appears on the video.
So simply the application cannot work on the internet if simplewall is activated.

The versions that don't work are 3.1.1 and the latest version 3.1.2
3.0.9 works well.
If you uninstall the application and reinstall it you will immediately notice why nothing works, no notification icon and no internet.
(I also tried on a fresh installation of windows 7 and the problem remains).
Windows 7 enterprise x64 sp1
Regards

**Comment by henrypp** [comment]
yeah this is a bug, there is a topic for discussion #654
