### ISSUE TITLE
Filters with a hard permit on a higher weight sublayer can override a block by simplewall

### ISSUE THREAD

**Issue by elesiuta** [henrypp/simplewall#689]
Using this code (based on what @taviso wrote in issue https://github.com/henrypp/simplewall/issues/680) I was able to confirm that a filter on a sublayer with a weight of 0xFFFF or 0xFFFE and using a hard permit (setting the FWPM_FILTER_FLAG_CLEAR_ACTION_RIGHT flag on the filter) can override a block by simplewall. 

```c++
#include <stdio.h>
#include <windows.h>
#include <fwpmu.h>
#include <rpc.h>

#pragma comment(lib, "FWPUCLNT")
#pragma comment(lib, "Rpcrt4.lib")

int main(int argc, char** argv)
{
	HANDLE engineHandle;
	FWPM_SUBLAYER0 fwpFilterSubLayer1;
	FWPM_SUBLAYER0 fwpFilterSubLayer2;
	GUID SubLayerGuid1;
	GUID SubLayerGuid2;
	FWPM_FILTER0 fwpFilter1;
	FWPM_FILTER0 fwpFilter2;
	UINT64 FilterId1;
	UINT64 FilterId2;
	FWPM_SESSION0 fwpSession = {
		.flags = FWPM_SESSION_FLAG_DYNAMIC
	};

	if (UuidCreate(&SubLayerGuid1) != RPC_S_OK)
	{
		printf("UuidCreate failed.\n");
		return 1;
	}
	if (UuidCreate(&SubLayerGuid2) != RPC_S_OK)
	{
		printf("UuidCreate failed.\n");
		return 1;
	}

	ZeroMemory(&fwpFilterSubLayer1, sizeof(FWPM_SUBLAYER0));
	ZeroMemory(&fwpFilterSubLayer2, sizeof(FWPM_SUBLAYER0));
	ZeroMemory(&fwpFilter1, sizeof(FWPM_FILTER0));
	ZeroMemory(&fwpFilter2, sizeof(FWPM_FILTER0));

	if (FwpmEngineOpen0(NULL,
		RPC_C_AUTHN_DEFAULT,
		NULL,
		&fwpSession,
		&engineHandle) != ERROR_SUCCESS) {
		fprintf(stderr, "FwpmEngineOpen0 failed, %#X\n", GetLastError());
		return 1;
	}

	fwpFilterSubLayer1.displayData.name = L"TestFilterSublayer1";
	fwpFilterSubLayer1.displayData.description = L"Test filter sublayer1";
	fwpFilterSubLayer1.weight = 0xFFFD;
	fwpFilterSubLayer1.subLayerKey = SubLayerGuid1;

	fwpFilterSubLayer2.displayData.name = L"TestFilterSublayer2";
	fwpFilterSubLayer2.displayData.description = L"Test filter sublayer2";
	fwpFilterSubLayer2.weight = 0xFFFF;
	fwpFilterSubLayer2.subLayerKey = SubLayerGuid2;

	printf("Adding filter sublayer.\n");
	if (FwpmSubLayerAdd0(engineHandle, &fwpFilterSubLayer1, NULL) != ERROR_SUCCESS) {
		fprintf(stderr, "FwpmSubLayerAdd0 failed, %#x\n", GetLastError());
		return 1;
	}
	if (FwpmSubLayerAdd0(engineHandle, &fwpFilterSubLayer2, NULL) != ERROR_SUCCESS) {
		fprintf(stderr, "FwpmSubLayerAdd0 failed, %#x\n", GetLastError());
		return 1;
	}

	// Block all outbound traffic
	fwpFilter1.layerKey = FWPM_LAYER_ALE_AUTH_CONNECT_V4;
	fwpFilter1.subLayerKey = fwpFilterSubLayer1.subLayerKey;
	//fwpFilter1.flags = FWPM_FILTER_FLAG_CLEAR_ACTION_RIGHT;
	fwpFilter1.action.type = FWP_ACTION_BLOCK;
	fwpFilter1.displayData.name = L"Testing FwpmEngineSetSecurityInfo1";
	
	// Permit all outbound traffic
	fwpFilter2.layerKey = FWPM_LAYER_ALE_AUTH_CONNECT_V4;
	fwpFilter2.subLayerKey = fwpFilterSubLayer2.subLayerKey;
	fwpFilter2.flags = FWPM_FILTER_FLAG_CLEAR_ACTION_RIGHT;
	fwpFilter2.action.type = FWP_ACTION_PERMIT;
	fwpFilter2.displayData.name = L"Testing FwpmEngineSetSecurityInfo2";

	if (FwpmFilterAdd0(engineHandle, &fwpFilter1, NULL, &FilterId1) != ERROR_SUCCESS) {
		fprintf(stderr, "FwpmFilterAdd0 failed, %#x\n", GetLastError());
		return 1;
	}
	if (FwpmFilterAdd0(engineHandle, &fwpFilter2, NULL, &FilterId2) != ERROR_SUCCESS) {
		fprintf(stderr, "FwpmFilterAdd0 failed, %#x\n", GetLastError());
		return 1;
	}

	fprintf(stderr, "Success: Press any key To remove filters...\n");

	_getch();

	FwpmFilterDeleteById0(engineHandle, FilterId1);
	FwpmSubLayerDeleteByKey0(engineHandle, &fwpFilterSubLayer1.subLayerKey);
	FwpmFilterDeleteById0(engineHandle, FilterId2);
	FwpmSubLayerDeleteByKey0(engineHandle, &fwpFilterSubLayer2.subLayerKey);
	FwpmEngineClose0(engineHandle);
	return 0;
}
```
I also tested what was needed to override a hard permit.

Based on these docs (https://docs.microsoft.com/en-us/windows/win32/fwp/filter-arbitration) it sounds like the filter doing the blocking also needs the FWPM_FILTER_FLAG_CLEAR_ACTION_RIGHT flag (to reset FWPS_RIGHT_ACTION_WRITE) to become a hard block, which is what they call a callout veto.

However, in my tests, only setting the weight of the sublayer doing the blocking (fwpFilterSubLayer1) to 0xFFFE or 0xFFFF was required. The FWPM_FILTER_FLAG_CLEAR_ACTION_RIGHT flag doesn't seem to do anything on the blocking filter (fwpFilter1), but it doesn't seem to hurt either and may be safer to set it, along with a weight of 0xFFFF, could someone confirm this?

**Comment by elesiuta** [comment]
Based on my tests, it seems the order of priority between the 2 filters here in this code (ignoring simplewall for a moment) was

1. Block with weight 0xFFFE or 0xFFFF
2. Permit with weight 0xFFFE or 0xFFFF and FWPM_FILTER_FLAG_CLEAR_ACTION_RIGHT
3. Block with any weight <= 0xFFFD
4. Permit with any weight

**Comment by taviso** [comment]
FWIW, I agree with you, that configuration makes much more sense.

**Comment by ltGuillaume** [comment]
Dang it, this was what I suspected quite some time ago (and discussed in https://github.com/henrypp/simplewall/issues/254 and https://github.com/henrypp/simplewall/issues/559), but I didn't really get feedback, nor did & do I have the expertise to be absolutely sure about it (I found the MS documentation rathering lacking, too, for that matter).

Thanks for diving into this, I hope these proposed changes will be adopted by @henrypp

**Comment by cloudgreen** [comment]
This is an open source project, so @henrypp is not our only hope, right?

**Comment by Kein** [comment]
We always can start a new one considering the recent needs :P

**Comment by ltGuillaume** [comment]
Could someone explain to me what the word "clear" in the MS documentation actually means?

> Along with the action type, a filter also exposes the flag FWPM_FILTER_FLAG_CLEAR_ACTION_RIGHT. If this flag is cleared, then the action type is hard and cannot be overridden except when a hard permit is overridden by a Veto as explained later on, else it is soft which can be overridden by high priority action.

"If this flag is _cleared_"

Does that mean it should be added, like @henrypp just did in https://github.com/henrypp/simplewall/commit/2b7a4a849f76f819b6ac45d468fbfe79b40b668a, or does its _absence_ mean that the action type is hard?

**Comment by elesiuta** [comment]
> Could someone explain to me what the word "clear" in the MS documentation actually means?
> 
> > Along with the action type, a filter also exposes the flag FWPM_FILTER_FLAG_CLEAR_ACTION_RIGHT. If this flag is cleared, then the action type is hard and cannot be overridden except when a hard permit is overridden by a Veto as explained later on, else it is soft which can be overridden by high priority action.
> 
> "If this flag is _cleared_"
> 
> Does that mean it should be added, like @henrypp just did in [2b7a4a8](https://github.com/henrypp/simplewall/commit/2b7a4a849f76f819b6ac45d468fbfe79b40b668a), or does its _absence_ mean that the action type is hard?

The wording in the documentation isn't great, and that paragraph on its own is kind of misleading. Based on the next paragraph
> A Veto is a "Block" action returned by the filter when the FWPS_RIGHT_ACTION_WRITE flag was reset prior to calling the filter. A Veto will block traffic that was permitted with a hard permit.  

My understanding is that creating a Veto, which is what we want, depends on resetting/clearing the FWPS_RIGHT_ACTION_WRITE flag, which is done by setting FWPM_FILTER_FLAG_CLEAR_ACTION_RIGHT in the filter.  

So it looks to me like the change in the commit is correct.

**Comment by ltGuillaume** [comment]
Yeah but it reads like a Veto doesn't allow any Allow rules to work anymore?

**Comment by ltGuillaume** [comment]
Apparently this has been fixed in 3.6 🙂 but I can't find the corresponding commit.

@elesiuta Could you retry with v3.6 and see if it's fixed?

**Comment by henrypp** [comment]
@ltGuillaume

you can test it yourself. May be required simplewall filters uninstall and then install first if it does not worked.

[hard_permit_test.zip](https://github.com/henrypp/simplewall/files/7505901/hard_permit_test.zip)

**Comment by ltGuillaume** [comment]
Damn, I just did and all my systems still had the old filters installed, so hard_permit_test opened up everything... until I manually disabled and enabled the filters again.

This probably means everyone who missed your line

> May be required simplewall filters uninstall and then install first

and just updated is still vulnerable...

**Comment by henrypp** [comment]
@ltGuillaume are you on win7/win8?

**Comment by ltGuillaume** [comment]
No, I'm on Windows 10 x64
