### ISSUE TITLE
Custom Rules behavior

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#69]
In whitelist mode, creating rules is very confusing.
1. Why are custom rules after creation via a notification not enabled by default?
2. Are custom rules created via a notificaiton linked specifically to the executable or not? Although the answer is yes (the tooltip denotes the path to the executable), the Rules Editor itself does not mention the executable anywhere.

By now I've figured out that I should create a custom rule (without enabling it), then right-click on the app and choose to allow it for that app. It's extra confusing if you're trying to create a custom rule from the context menu of an app and finding out that the created custom rule is not linked to that app.

A. I think mentioning the app path inside the Rules Editor would be necessary for clarity
B. I think creating a rule from the context menu should include the application one has right-clicked on

**Comment by henrypp** [comment]
>By now I've figured out that I should create a custom rule (without enabling it), then right-click on the app and choose to allow it for that app. It's extra confusing if you're trying to create a custom rule from the context menu of an app and finding out that the created custom rule is not linked to that app.

Yes, rules from notifications applied specially for the app.
And, yes this is confused, but Rules editor will be reworked as soon as possible!

**Comment by ltGuillaume** [comment]
Thank you! Don't forget to fix - when reworked - the IP ranges format `xxx.xxx.xxx.xxx-xxx.xxx.xxx.xxx` which is not working right now!

**Comment by henrypp** [comment]
No, ranges will stand still, `113.30.0.0/16` and normal ranges `192.168.0.1-192.168.0.100`, not another style.

**Comment by ltGuillaume** [comment]
I didn't mean that you should change anything, I meant that
xxx.xxx.xxx.xxx-xxx.xxx.xxx.xxx is broken: it doesn't work at all.

**Comment by henrypp** [comment]
Ok, i found problem, wait for fix.

**Comment by henrypp** [comment]
fixed
