### ISSUE TITLE
No buttons when set scale 175%

### ISSUE THREAD

**Issue by kreon1** [henrypp/simplewall#693]
Hello
Thanks  for best lightweight firewall on the market.
Issue- when I set in windows10x64 res 1920x1080  scale and layout to 175% when popup window and ask allow or block, no text, no buttons, only a clean window with no options.when I set it to 150%, everything is ok.
Any chance to fix this please?

**Comment by henrypp** [comment]
This is fixed in 3.2

**Comment by kreon1** [comment]
Awesome. Thank you Sir :)
