### ISSUE TITLE
How to build the simplewall?

### ISSUE THREAD

**Issue by jayprakashkumar1** [henrypp/simplewall#694]
![Screenshot (142)](https://user-images.githubusercontent.com/26687042/84137859-ebf24580-aa6a-11ea-8211-a17d341cbc52.png)

**Comment by jjxtra** [comment]
Lots of errors here also, trying to make a dll out of it. There are a couple of sub modules that are needed, but I still have errors. Build instructions are missing from repo docs as far as I can tell.
