### ISSUE TITLE
How do I unblock this?

### ISSUE THREAD

**Issue by helpfulBrother** [henrypp/simplewall#695]
"‎9/‎06/‎2020 ‏‎7:07:44 PM","NT AUTHORITY\SYSTEM","C:\windows\system32\svchost.exe","2001:0:2851:b9f0:109d:219d:6f76:ab0b","500 (isakmp)","2001:0:2851:b9f0:30bf:4ac:95b8:cc97","500 (isakmp)","udp6","Microsoft Corporation\ET Default Block All","#2091251","Inbound","Blocked"

svchost.exe is on the enable list. I can't actually find where this is blocked?

How do I add an exception for port 500 udp6 for this process?

**Comment by Chaython** [comment]
Go to the service tab, and allow the service.
You can add a rule, and set for a specific app, and select the port...

**Comment by helpfulBrother** [comment]
Thanks, I can't find svchost.exe in the services tab?

**Comment by Chaython** [comment]
Svchost is an app hosts all services.
You're looking for a specific service in the services tab.

**Comment by helpfulBrother** [comment]
Thanks, I couldn't decipher what service it is based on the above log entry.

Any pointers on how I would go about determining that?

Thanks again

**Comment by Chaython** [comment]
I do not know. What is wrong that you want to allow this service?

**Comment by helpfulBrother** [comment]
Unable to connect to friends in xbox (windows) games

Switching back to Windows firewall solves the issue, but I'd rather address it using simple wall.

**Comment by Chaython** [comment]
All those services are titled "gaming" and "xbl" you must also enable the individual packages/apps and enable the settings in the blocklist.

**Comment by helpfulBrother** [comment]
Thanks, this looks like an isakmp call?

I guess once the right packages / apps / services are enabled isakmp and other calls will work as expected?

**Comment by henrypp** [comment]
`"Microsoft Corporation\ET Default Block All"`

This filter is not from SW, this is Windows Defender filter.

**Comment by helpfulBrother** [comment]
Thanks, is it possible to see this rule within SW or do I need to elsewhere to locate and disable?

**Comment by henrypp** [comment]
Use WF.msc, SW is not mean with this.

**Comment by helpfulBrother** [comment]
Thank you!

**Comment by Chaython** [comment]
So what did you do?

**Comment by helpfulBrother** [comment]
> So what did you do?

Just turned off SW and used Microsoft FW when I needed to. Not the best solution.

**Comment by henrypp** [comment]
Yes, SW is actually not the best solution for solve [your](https://github.com/henrypp/simplewall/issues/695#issuecomment-656511258) "problem".

**Comment by helpfulBrother** [comment]
Well I like SW this seems to be only app I have issues with, all other apps behave as expected. So it's only a minor inconvenience. Thanks 👍

**Comment by henrypp** [comment]
I really reread OP topic twice and did not found how [WFP filter created by another application](https://github.com/henrypp/simplewall/issues/695#issuecomment-656511258) doing with simplewall.

**Comment by helpfulBrother** [comment]
@henrypp this was closed almost a year ago, as you can see in the thread it started as a question, moved to discovery and then to a solution accepting that the rule was created by WF.

I replied today because @Chaython asked me 9 hours ago what I did.

There is no need to be defensive about SW, anyone reading this issue can see the cause and remediation.

**Comment by henrypp** [comment]
Misunderstand, sorry!

**Comment by helpfulBrother** [comment]
All good, love your work and donated. Thank you ❤
