### ISSUE TITLE
How to turn simplewall into learning mode?

### ISSUE THREAD

**Issue by silvioplus** [henrypp/simplewall#696]
As title say, I'd like to be asked for permission on every new connection with a window popup. Simplewall used to work like that, but not anymore. Maybe there's some trick that could help me. Thanks. I'm on 3.1.2 64bit windows 7.

**Comment by silvioplus** [comment]
Hi. All notifications are enabled. Meanwhile I have to disable filters when a new connection is blocked. Maybe I can downgrade to a previows release where pop-ups works well...but I don't know which release shoud I try. Thanks for answering.

**Comment by silvioplus** [comment]
I noticed that the latest version with pop-up working for me is the v3.1 (8-feb). Is it safe to use it? I really need the pop-up method.

**Comment by henrypp** [comment]
here is topic #654

**Comment by rudolphos** [comment]
With these settings, there are still no notifications showing up in 3.2.4 verison.
![image](https://user-images.githubusercontent.com/4366810/104849265-73e9d900-58f1-11eb-9176-fb055550b923.png)
