### ISSUE TITLE
UI suggestion: better groups/filters of all the lines

### ISSUE THREAD

**Issue by eugenesvk** [henrypp/simplewall#698]
Currently the main UI differentiator is colors highlighting, which are good, but suffer from these two issues:
1. there are too many of them so it's a bit of a challenge to read what group a specific line belongs to

**Suggestion**: this could be improved if there were an always visible legend with abbreviations in the toolbar (there is plenty of free space for that), e.g.:
 `time user sys sign winserv inval disnot hascon`
with each word highlighted with the corresponding colors and showing the full names on mouseover

2. They can't be used for **visual groups/filters**
For example, in the **Network** tab I would like to be able to
a) group **Windows service** and **System app** together so that they are not mixed with user apps
b) filter them out (hide) completely for even better visibility of user apps

**Suggestion**: 
- wither would you please add optional column that has all the color highlightings as text values that would allow sorting by content (that's the default of any column, just there is currently none that has highlighting text in them) and excluding certain categories (this is a new feature not available for other columns)
- or maybe it could be similar to the Task Manager with boolean columns for each or some of the color highlighting categories (e.g. **WinService** **Yes/No** and **SystemApp** **Yes/No**), though even for them filtering **Yes** out would be a bonus

**Comment by aminya** [comment]
This will be a nice feature. For example, a single antivirus like Avast has many executables. Grouping these all together will simplify the list.
