### ISSUE TITLE
WSL2: allow connections via a custom rule

### ISSUE THREAD

**Issue by eugenesvk** [henrypp/simplewall#699]
Microsoft has enabled in its recent 2004 update [WSL2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-index) and I can't seem to understand how to allow its traffic, I don't see any prompts and the only way to allow traffic is to disable simplewall or both of these rules:
`Block inbound connections for all`
`Prevent port scanning`

Is there a way to keep those rules enabled, but create an exception for WSL2?
Thank you!

**Comment by nedimAT** [comment]
I have the same Problem. With WSL1 i got a Popup for the Tool that wanted to connect (e.g. ping). If i can help further with extended logs or something similiar, i would be glad to help.
I installed WSL2 yesterday and only used PengWin so far.

**Comment by bullshit** [comment]
+1

**Comment by GetzMikalsen** [comment]
Working here OOTB only got user rule HTTP* enabled, Windows 10 Enterprise, Version 2004

**Comment by nedimAT** [comment]
works for me :), thank you 
![image](https://user-images.githubusercontent.com/12996034/86337597-9700b400-bc51-11ea-8f36-e8358eb7bcb2.png)

**Comment by eugenesvk** [comment]
Thanks, @GetzMikalsen, this does indeed help, though do you know if there is a more narrow range to open for this shared host process?

**Comment by GetzMikalsen** [comment]
> Thanks, @GetzMikalsen, this does indeed help, though do you know if there is a more narrow range to open for this shared host process?

Not as I'm aware of without modifying the network system in windows/WSL. 
Normally dynamic ports range between 49152 and 61000 but the Linux kernel being used uses ports from 32768.
We could file a report to the WSL2 repo to limit the ports used for inbound UDP traffic. This is one of the caveats of running Linux in a virtual machine rather than using the window networking stack as in WSL1
You can read more here
https://serverfault.com/questions/222606/how-can-i-reject-all-incoming-udp-packets-except-for-dns-lookups
and here
https://en.wikipedia.org/wiki/Ephemeral_port

**Comment by GetzMikalsen** [comment]
Can confirm that `# echo 32768 32768 > /proc/sys/net/ipv4/ip_local_port_range` works to set the port used to 32768, Im not advising you to do this but it does enable you to limit the port range

**Comment by henrypp** [comment]
new WSL2 networking works from Windows service, because allowing svchost and "apg get" is working, but this is no solution.
there is question is which Windows service WSL2 used? if anyone know, please write about it.

**Comment by rudolphos** [comment]
Similar problem with WSL2

When simplewall is enabled:
![image](https://user-images.githubusercontent.com/4366810/97086020-91c4dc00-1629-11eb-8f81-a1c967f6111b.png)


When simplewall is disabled:
![image](https://user-images.githubusercontent.com/4366810/97086040-a43f1580-1629-11eb-9efe-ecb2b45d8e93.png)

I have added multiple executables to exclusions in simplewall:

- ubuntu.exe
- wsl.exe
- bash.exe
- vmcompute.exe
- vmwp.exe
- wslhost.exe

with no effect..

**Comment by rojnwa** [comment]
I can confirm that adding an exception for **SharedAccess** via the services tab will make WSL2 work flawlessly.

No idea if that's at least a little bit better than allowing svchost completely but I'd assume so. I guess you can mark this as solved.

**Comment by escanoru** [comment]
> I can confirm that adding an exception for **SharedAccess** via the services tab will make WSL2 work flawlessly.
> 
> No idea if that's at least a little bit better than allowing svchost completely but I'd assume so. I guess you can mark this as solved.

This worked for me as well, thanks :)

**Comment by braminsign** [comment]
This wont work for me. 
![image](https://user-images.githubusercontent.com/78485280/159636360-b31218d7-55d7-4198-8e7a-b9c6dbfc3c20.png)
![image](https://user-images.githubusercontent.com/78485280/159636413-67d0d9f0-416b-4a03-a260-6f19b1f9bda5.png)

When i`ll disable the filter everthings works. But i cannot allow this emtpy application :)

**Comment by eugenesvk** [comment]
> I can confirm that adding an exception for **SharedAccess** via the services tab will make WSL2 work flawlessly.
> 
> No idea if that's at least a little bit better than allowing svchost completely but I'd assume so. I guess you can mark this as solved.

This also enables network access for "Windows Sandbox", which is undesirable, so this is still not great, properly you should be able to scope by a spepcific service
