### ISSUE TITLE
Custom rules with IP ranges do not work

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#70]
The only problem seems to be that IP ranges do not work when the notation `0.0.0.0-110.44.255.255` is used. So this should be checked. IP ranges in the CIDR notation _do_ work.

Old comment:
> Apparently, allowing an app will overrule any custom (blocking) rules for that app? Custom rules should have higher priority, but the IP ranges I've set for an allowed app are NOT blocked. How should I allow an application to create outbound connections to anywhere, with the exception of a set of IP ranges?
> 
> I tried the other way around, by blocking the app and then creating a custom rule to allow everything outside of these IP ranges (and disabling notifications for the executable). No go.
> 
> On a side note: if it _would_ have worked, can I specify multiple ranges in a single rule like this
> `0.0.0.0-110.44.255.255; 110.48.0.0-113.28.255.255`? It _seems_ to be accepted by the Rules Editor, but as said there is no effect at all. Even a single range like `113.30.0.0-203.216.255.255` in a custom allow rule doesn't stop SimpleWall from blocking everything for that app.

**Comment by ltGuillaume** [comment]
I've figured out that IP ranges do not work, whereas CIDR notations like `113.30.0.0/16` _do_ work.

**Comment by henrypp** [comment]
fixed
