### ISSUE TITLE
Microsft Edge suddenly not being blocked anymore

### ISSUE THREAD

**Issue by UNDEFINED-BEHAVIOR** [henrypp/simplewall#700]
I have
"microsoftedgecp.exe", "microsoftedgesh.exe"
and "Microsoft Edge" package disabled yet edge were still able to access the internet. (actually, all packages disabled)

The actual executable of edge were at %WinDir%SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\MicrosoftEdge.exe
But won't show up on the app list.

Any idea what's going on?

**Comment by asvc** [comment]
Not really. Have you tried `tcpview` & `wireshark` to verify what actually connects where?

**Comment by henrypp** [comment]
Any proof?

**Comment by Hunanbean** [comment]
Listen. This is Not blocking Edge. plain and simple. I am forced to change firewalls due to this.

**Comment by Hunanbean** [comment]
And i do not mean it is letting a cached page through, I mean i can login to peacock and watch tv.

**Comment by savchenko** [comment]
> I mean i can login to peacock and watch tv.

Poor peacock, please log out and stop abusing the bird. To answer your question - ensure that AppX package _and_ *.exe are both blocked. Which version of Simplewall do you use?

**Comment by savchenko** [comment]
> A Full reverse Correction to my last statement. The propertie for UWP are under a different tab.

That was quick, I've managed to reply to your original message :) Glad it works now.

**Comment by Hunanbean** [comment]
:) sorry about the confusion. After updating to the latest version (i was
one version behind) it has decided to place edge on the main tab instead of
the UWP tab, which i had entirely forgotten about. After fighting windows
update failures for the past two days, my frustration carried over to my
simplewall comment. it shouldn't have. Thank you for making simplewall, and
for the additional insight into its workings. it is exactly what i needed.

Be well!

**Comment by ltGuillaume** [comment]
Isn't that just the difference after updating from Edge (Classic), which was (partly?) an UWP app and the new Edge Chromium, which isn't UWP?

**Comment by Hunanbean** [comment]
I do believe you are exactly right.

**Comment by savchenko** [comment]
> Thank you for making simplewall, and for the additional insight into its workings. it is exactly what i needed.

This goes straight to @henrypp who is the author of SimpleWall :)

**Comment by Kein** [comment]
> Not really. Have you tried `tcpview` & `wireshark` to verify what actually connects where? 

Use LiveTCPUPDWatch by Nirsoft instead if you wanna trace BFE level events.

And I dont understand what the point of using simplewall if you dont set default blocking policy and use whitelist.
