### ISSUE TITLE
The "File, Edit, View..." menus are a meter long

### ISSUE THREAD

**Issue by BloodRaven0** [henrypp/simplewall#701]
![sshot-2020-06-16-11-09-43](https://user-images.githubusercontent.com/42444745/84749132-3d965500-afc2-11ea-8896-f55eee4ef088.png)
![sshot-2020-06-16-11-09-54](https://user-images.githubusercontent.com/42444745/84749135-3ec78200-afc2-11ea-92d4-24159beae8fa.png)
I'm using Windows 10 Pro x64 with a custom theme installed (could be the main reason for the bug) - with SecureUX theme patcher, the theme is called Arc (you can find it on deviantart)
The menus seem to have a fixed width, as you can see from the screenshots. This doesn't happen in any other application with this theme. Also they seem unaffected by the theme, being completely white.
If you're unable to fix this, atleast give us the option to autohide the menu bar and open it only when needed with the Alt key. This could also help to declutter the interface and make it more sleek and modern.

**Comment by BloodRaven0** [comment]
![sshot-2020-06-16-11-20-07](https://user-images.githubusercontent.com/42444745/84750000-6408c000-afc3-11ea-85b9-e63b0035b6ee.png)
It somehow randomly partially fixed itself, although it's still an eyesore, the text blends into the separators and it's still unthemed. I still propose letting us autohide the menu bar.

**Comment by henrypp** [comment]
what windows version?

**Comment by BloodRaven0** [comment]
Windows 10 Pro v1903.
I have a v2004 machine I can try it on with the same theme if you want to.

**Comment by henrypp** [comment]
I confirm, this is a bug. Fix i comming. Thanks for the report.

**Comment by henrypp** [comment]
done
