### ISSUE TITLE
[Low Priority] New binary release soon?

### ISSUE THREAD

**Issue by gettysburg** [henrypp/simplewall#704]
More than 210 commits already since 3.1.2, some being important bug fixes.

I politely request the release of simplewall 3.1.3, and I also want to thank you for your continued work, your software blows even paid programs out of the water, and that's why I will continue to donate.

Simplewall forever ❤️

**Comment by henrypp** [comment]
Hello,

I am working on 3.2.x a branch and now it is unstable, i hope release _at least_ beta - soon.

**Comment by gettysburg** [comment]
Thank you for the update dear Henry.
