### ISSUE TITLE
Microsoft Store broken

### ISSUE THREAD

**Issue by privacyguy123** [henrypp/simplewall#705]
I guess they added some more new servers not covered in "Allow Microsoft Update/App Servers" option

**Comment by privacyguy123** [comment]
More IPs to come:

151.139.128.14

**Comment by privacyguy123** [comment]
Both allowed yes - new Windows build 2004 is asking for more connections that aren't covered in the current lists.

**Comment by Chaython** [comment]
Anyways the anti microsoft stuff is https://github.com/crazy-max/WindowsSpyBlocker
As credited.
None of these are in the lists, when they update, henry would probably merge, they're also updating much more frequently with more commiters...

**Comment by privacyguy123** [comment]
Going to upload new IPs as an image from now on.

I've opened a ticket over there too, it seems their lists are 2 months out of date which explains it.

**Comment by Chaython** [comment]
I think in proper formatting a port shouldn't be specified(?)
They update very frequently and ms store works for me.
Again I'm sure if you're right thne they will uodate then henry will merge.
What do you even use ms store for uwp is cancer
________________________________

**Comment by SimonEast** [comment]
I also cannot get the Microsoft Store to work. I'm getting the error message "You'll need the internet for this".

I've tried:

* Blocklist menu > Microsoft update > Allow
* Blocklist menu > Microsoft applications > Allow
* Apps tab > windowspackagemanagerserver.exe > Allow
* Services tab > InstallService > Allow
* UWP Apps tab > App Installer > Allow
* UWP Apps tab > Microsoft content > Allow
* UWP Apps tab > Microsoft Store > Allow

What am I missing? 

When reviewing the packet log, the main relevant item seems to be `svchost.exe` which indicates one of the Windows services, but I'm not sure which one I'm missing, and simplewall is not good at identifying which services are attempting connections.

I really don't want to have to whitelist every single IP address for the Windows Store - that seems like a poor approach.

Any other suggestions?

**Comment by Chaython** [comment]
> I also cannot get the Microsoft Store to work. I'm getting the error message "You'll need the internet for this".
> 
> I've tried:
> 
>     * Blocklist menu > Microsoft update > Allow
> 
>     * Blocklist menu > Microsoft applications > Allow
> 
>     * Apps tab > windowspackagemanagerserver.exe > Allow
> 
>     * Services tab > InstallService > Allow
> 
>     * UWP Apps tab > App Installer > Allow
> 
>     * UWP Apps tab > Microsoft content > Allow
> 
>     * UWP Apps tab > Microsoft Store > Allow
> 
> 
> What am I missing?
> 
> When reviewing the packet log, the main relevant item seems to be `svchost.exe` which indicates one of the Windows services, but I'm not sure which one I'm missing, and simplewall is not good at identifying which services are attempting connections.
> 
> I really don't want to have to whitelist every single IP address for the Windows Store - that seems like a poor approach.
> 
> Any other suggestions?

For most microsoft crap svchost needed perm

**Comment by henrypp** [comment]
@Chaython u complete dont have eyes?

https://github.com/henrypp/simplewall#q-how-to-fix-windows-update-internet-access

**Comment by henrypp** [comment]
@Chaython store works over WU, only once i encountered store not working when WU service is enabled, dont know because of what? i fix this reinstalling OS, everything alright now!

**Comment by SimonEast** [comment]
@henrypp I have both `wuauserv` and "Microsoft Update" enabled in simplewall, like this:

<img width="914" height="258" alt="Image" src="https://github.com/user-attachments/assets/f973db19-e235-4f6c-9dff-c3007d774ab9" />

But Microsoft Store still shows an error message like this:

<img width="330" height="236" alt="Image" src="https://github.com/user-attachments/assets/270d9bbf-5002-45cb-bcad-c8d897a769a4" />

I suspect another service is needed also, but I don't know which.

Are you sure it works OK for you when only `wuauserv` is enabled?

I prefer _not_ to enable `svchost` as it will give internet access to dozens of things.
