### ISSUE TITLE
Google translate is disabled

### ISSUE THREAD

**Issue by Shryce** [henrypp/simplewall#706]
Hi,
I just installed Simplewall today and so far I'm liking it.
However.... on my Chrome browser Simplewall appears to have disabled the Google Translate option which is available by right clicking in a screen. Since I work with foreign languages a lot this is rather inconvenient.

I have no idea how to resolve it... turning off Simplewall doesn't allow it to work either/restarting browser doesn't help.
Can't seem to figure out what is blocking this Google Translate service from operating since I've installed Simplewall....
Google Translate is still in the extentions menu and it is turned on.

Any ideas what to do ?

**Comment by henrypp** [comment]
> However.... on my Chrome browser Simplewall appears to have disabled the Google Translate

SW does not change 3-rd party applications configuration.

> I have no idea how to resolve it... turning off Simplewall doesn't allow it to work either/restarting browser doesn't help.

I have no idea too.

**Comment by Shryce** [comment]
Sorry please disregard.
