### ISSUE TITLE
Windwos firewall updates are being blocked

### ISSUE THREAD

**Issue by dducted** [henrypp/simplewall#708]
Hi,

I am having issues getting windows updates. 

I did set:
`Blocklist > Microsoft update severs > Allow` 

Hope someone can tell me what other settings needs to be changed so that I dont have to disable SF to receive updates.

Thanks!

**Comment by henrypp** [comment]
[Here](#677) is solution for win10+

**Comment by ltGuillaume** [comment]
> 
> 
> [Here](#677) is solution for win10+

Wrong link. See https://github.com/henrypp/simplewall/issues/677 instead.
