### ISSUE TITLE
no internet / sometimes  simplewall automatically denies internet 

### ISSUE THREAD

**Issue by superman4** [henrypp/simplewall#709]
no internet / sometimes  simplewall automatically denies internet 
this started happening from the recent simplewall updates 

![Screenshot (23)](https://user-images.githubusercontent.com/12621759/86329913-5197b300-bc60-11ea-875f-0d31a1d34be7.png)
please help
![Screenshot (25)](https://user-images.githubusercontent.com/12621759/86330010-768c2600-bc60-11ea-96c2-0e524c2f8f25.png)

do i need to enable anything in service 
i dont want to enable windows update or any log uploading services

please help

**Comment by bbx-git** [comment]
I have the same problem, after restarting Windows i have no internet, i have to disable all filters, connect to WiFi and then re-enable them.

**Comment by Skrem339** [comment]
Can you send screenshots of your other tabs in simplewall? (Like System Rules, User Rules etc.)

**Comment by henrypp** [comment]
When you are connected to a new network, Windows checks for internet connectivity using Active Probing. This feature is named as NCSI (Network Connectivity Status Indicator).

- You can allow **NlaSvc** in services tab.
- You can disable NCSI entirely throught system registry.

create **"Disable NCSI.reg"** and import it into registry.
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\NetworkConnectivityStatusIndicator]
"NoActiveProbe"=dword:00000001
"DisablePassivePolling"=dword:00000001
```

**Comment by tribals** [comment]
> When you are connected to a new network, Windows checks for internet connectivity using Active Probing. This feature is named as NCSI (Network Connectivity Status Indicator).
> 
> * You can allow **NlaSvc** in services tab.
> * You can disable NCSI entirely throught system registry.
> 
> create **"Disable NCSI.reg"** and import it into registry.
> 
> ```
> [HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\NetworkConnectivityStatusIndicator]
> "NoActiveProbe"=dword:00000001
> "DisablePassivePolling"=dword:00000001
> ```

Unfortunately this does not work for Windows 11 21H2 build 22000.1936.

**Comment by henrypp** [comment]
@tribals it started not working on win11 23h2, use this instead:

```
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\NetworkConnectivityStatusIndicator]
@=""
"EnableActiveProbing"=dword:00000001
;"NoActiveProbe"=dword:00000001 ; remove this
;"DisablePassivePolling"=dword:00000001 ; and this
```

**Comment by tribals** [comment]
> and ofc enable ncsi in system rules

What does it ever mean?

![image](https://github.com/henrypp/simplewall/assets/3613180/d875e698-1190-4bb3-bdc2-b4b864603871)
![image](https://github.com/henrypp/simplewall/assets/3613180/1902b5c6-98aa-467c-89ca-f651fa10f95b)

**Comment by henrypp** [comment]
@tribals u cant navigate to "System rules" tab?

**Comment by tribals** [comment]
Sorry, I've missed the elephant. I removed comment in order to not mislead other people.

Thanks, it worked.

But it worked by enabling this "service" (from MS), IIUC?

(This is not problem for me. Conversely, it breaks so many things that I think it is better to leave this enabled. For example, it breaks installation of WSL distro - what a stupid OS that thinks there is no Internet, when there is.)
