### ISSUE TITLE
How to allow ping and nslookup?

### ISSUE THREAD

**Issue by Wakagithub** [henrypp/simplewall#710]
I would like to use *ping* and *nslookup* for some tests. I included both of them in the *Enabled apps* section, but they're still blocked as seen in the log.

Thanks in advance.

**Comment by Skrem339** [comment]
Just enable ICMPv4 and ICMPv6 under User Rules

**Comment by Wakagithub** [comment]
> Just enable ICMPv4 and ICMPv6 under User Rules

Ok thanks, that did it. I was previously trying to follow instructions from other related forums on how to get the IP numbers of particular domains. I will just disable those two again whenever I'm done.👍☺
