### ISSUE TITLE
I can't find the definition of "PR_STRING" 

### ISSUE THREAD

**Issue by zhuleejun** [henrypp/simplewall#716]
hi
when I clone the project and build it, it make mistake like this

![image](https://user-images.githubusercontent.com/8939885/87652023-437c8300-c786-11ea-8b68-8fcca3e9f95e.png)
![image](https://user-images.githubusercontent.com/8939885/87652034-47100a00-c786-11ea-8b33-c81f3e1bff95.png)

**Comment by frustreated** [comment]
the build issue is not properly solved always
just to sleep is OK

**Comment by zhuleejun** [comment]
> the build issue is not properly solved always
> just to sleep is OK

I guess some modification have not upload in project routine

**Comment by frustreated** [comment]
these two days have been gone ,and many updates updated ,but PR_STRING is not updated.
is there some other questions or wories?

**Comment by frustreated** [comment]
> > the build issue is not properly solved always
> > just to sleep is OK
> 
> I guess some modification have not upload in project routine

i guess this tooo

**Comment by frustreated** [comment]
> hi
> when I clone the project and build it, it make mistake like this
> 
> ![image](https://user-images.githubusercontent.com/8939885/87652023-437c8300-c786-11ea-8b68-8fcca3e9f95e.png)
> ![image](https://user-images.githubusercontent.com/8939885/87652034-47100a00-c786-11ea-8b33-c81f3e1bff95.png)

一般提问编译问题，印象里这位老哥一般都不会回答，会给个重复issue的标签，然后，关闭。
比较旧一点的版本，都可以正常编译，最近的版本，作者标记为私有lib的，东西，不更新了。其实最近更新了，但是和现在的simplewall不配套了。
很早，就需要最新的那个lib，然而前几天更新过后，仍旧不配套。
你懂的，恰好编译不通过。

**Comment by zhuleejun** [comment]
> > hi
> > when I clone the project and build it, it make mistake like this
> > ![image](https://user-images.githubusercontent.com/8939885/87652023-437c8300-c786-11ea-8b68-8fcca3e9f95e.png)
> > ![image](https://user-images.githubusercontent.com/8939885/87652034-47100a00-c786-11ea-8b33-c81f3e1bff95.png)
> 
> 一般提问编译问题，印象里这位老哥一般都不会回答，会给个重复issue的标签，然后，关闭。
> 比较旧一点的版本，都可以正常编译，最近的版本，作者标记为私有lib的，东西，不更新了。其实最近更新了，但是和现在的simplewall不配套了。
> 很早，就需要最新的那个lib，然而前几天更新过后，仍旧不配套。
> 你懂的，恰好编译不通过。

哈哈，老哥说的很对，没办法只能拿旧版本来编译
