### ISSUE TITLE
Missing translation strings in 3.2 pre-release

### ISSUE THREAD

**Issue by Matthaiks** [henrypp/simplewall#719]
It looks that these strings cannot be translated:

**(default)** in Block (default) and Disable (default)

**(session only)** in Enable packets logging interface (session only)

**(Local)** in Port (Local) and Address (Local)

**(Remote)** in Port (Remote) and Address (Remote)

**Comment by henrypp** [comment]
Yes, this is hardcoded strings, it does not need to be translated.

**Comment by ltGuillaume** [comment]
Why? That makes no sense?
