### ISSUE TITLE
Notifications stop spontaneously, nothing logged

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#72]
1. I had to clear the log, then disable/enable logging to file again, in order to see 1) notifications within the program again and 2) have Simplewall log to a file again. The size of the log file by then was 272,522 bytes. Is there a maximum of 256KB for the log file or something?
2. Clear log file when log to file is NOT enabled does not work: the log file is only cleared when logging to file is enabled. If this is by design, then the clear log file option should be greyed out when logging to file is not enabled.

**Comment by henrypp** [comment]
1. Maximum log size is 1024KB (1mb.) and this is optional config.
2. When log to file disabled "Clear log" is working too, and it remove file, instead of truncate when log to file enabled. No grayed out will be.

**Comment by ltGuillaume** [comment]
1. Thanks for the info. I think I was tired and mistook the clearing the option to clear the error log for the one to clear the dropped packets log. My bad!
2. Would increasing the log file to something like 2-5MB really impact the performance? (I have a not-so-fast, like really really slow, laptop over here).
3. It would be really great to have an option to not show notifications for the IPs of WindowsSpyBlocker's blocklist: I know these will be blocked, I checked the option myself. I'm kinda annoyed by the notifications all the time, and they come from a set of applications, including the browser when I open up Outlook.com, for example, for which I _do_ want notifications for other blocked items (such as custom rules).

**Comment by ltGuillaume** [comment]
In 2.1b I have had no notifications for "new"/unlisted (just regular) applications in almost all cases. They were just blocked and I had to add the processes manually.

W10 x64 b1703
Whitelist mode.

**Comment by henrypp** [comment]
Are you checking RC version? Fixed?

**Comment by ltGuillaume** [comment]
Well, now I experience often that the notification doesn't pop up at all, or 10-20s after the program in question already gave up connecting. It makes me forget about the firewall sometimes.

**Comment by ltGuillaume** [comment]
Still have this in 2.1.4. I do see the blocked connections in the log file, though, but there never is a notification. Some of the connections were blocked via the WindowsSpyBlocker blocklist, but I currently don't have "Exclude block list rules" enabled.

**Comment by ltGuillaume** [comment]
In v2.2 I rarely get ANY popup anymore, even though connections are blocked. They won't show up in the log anymore, either. For example, I disable the system rule "ICMP" to block pinging, open up a console and ping some website. The result is "general failure", but no notification pops up, and no entries are to be found in the log.
