### ISSUE TITLE
Packet log not opened via Ctrl+I or button

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#720]
With the new packet logging interface disabled, the hotkey Ctrl+I and the button to view the log do not open the file anymore.

**Comment by henrypp** [comment]
File exists?

**Comment by ltGuillaume** [comment]
Yes, it does.

**Comment by henrypp** [comment]
Let me see option "`LogPath`" and "`LogViewer`" in ini file.

**Comment by ltGuillaume** [comment]
I found the issue to be the relative path I set for `LogViewer`, totally forgot that, because it used to work without any issues.

I had set `LogViewer` to `.\csvfileview.exe`. Now I set it to just `csvfileview.exe` it seems to be working again (the executable is inside Simplewall's folder).
