### ISSUE TITLE
Need instructions on how to build

### ISSUE THREAD

**Issue by jjxtra** [henrypp/simplewall#721]
Can we please either have:

1] A batch file that initializes all the sub-modules properly and makes it so the .sln file will build in vs 2019 or
2] Instructions in the FAQ or wiki that spell out the exact steps needed for a build including how to pull sub-modules, add any other dependencies like pugxml, etc. 

I've gone through all the closed issues where people are having trouble building, I've tried pulling submodules down, downloading them manually and everything in between and there are always hundreds of errors.

I realize you do this project for free, would be happy to donate for at least basic build instructions on vs 2019...

**Comment by jjxtra** [comment]
I got everything working in C# with PInvoke, so this request is no longer necessary as I have alternative means to accomplish what I want.

**Comment by henrypp** [comment]
OK!
