### ISSUE TITLE
Some issues on beta v.3.2 and v.3.1.2

### ISSUE THREAD

**Issue by crazyyzarc** [henrypp/simplewall#724]
**short and snappy:**

**v.3.2:**
- UAC skip doesn't work correctly. It still asks for a UAC prompt warning. The schedule task doesn't work I think

**v.3.1.2:**
- During the installation the administrative privileges were not queried, so an error occurs
- The administrator who confirms the UAC request also automatically saves the .log file in his user directory. Instead of being stored in the non-administrator's user directory when the non-administrator runs the program

for example:
1. user1 runs the program
2. user1 gets the uac prompt warning and user1 uses the admin1 credentials
3. the log/config will be saved in admin1 dir, instead user1 dir

**Comment by Tom4tot** [comment]
I can confirm I'm facing the same issue with 3.2. Trying to untick/tick back didn't make the trick. I'm using simplewall as a portable program.

**Comment by henrypp** [comment]
> UAC skip doesn't work correctly. It still asks for a UAC prompt warning. The schedule task doesn't work I think

@Tom4tot @crazyyzarc

Open `taskschd.msc` and then open `simplewallSkipUAC` task and let me see his actions configuration - what full path to the executable?

**Comment by crazyyzarc** [comment]
> 
> 
> > UAC skip doesn't work correctly. It still asks for a UAC prompt warning. The schedule task doesn't work I think
> 
> @Tom4tot @crazyyzarc
> 
> Open `taskschd.msc` and then open `simplewallSkipUAC` task and let me see his actions configuration - what full path to the executable?

It's like in version 3.1.2.... but it differs on:
<a href="https://ibb.co/jRky6xP"><img src="https://i.ibb.co/xHq1Cct/2020-07-28-11-59-05-Eigenschaften-von-simplewall-Skip-UAC-Lokaler-Computer.png" alt="2020-07-28-11-59-05-Eigenschaften-von-simplewall-Skip-UAC-Lokaler-Computer" border="0"></a>

and was not executed
<a href="https://ibb.co/Jn3K8wF"><img src="https://i.ibb.co/CBPz43s/2020-07-28-12-01-36-Window.png" alt="2020-07-28-12-01-36-Window" border="0"></a>

**Comment by henrypp** [comment]
@crazyyzarc show Actions (Aktionen) tab and click twice on item

**Comment by crazyyzarc** [comment]
> 
> 
> @crazyyzarc show Actions (Aktionen) tab and click twice on item

As I said before: there is an obvious difference only in "Einstellungen" / Settings
<a href="https://imgbb.com/"><img src="https://i.ibb.co/BVq5ZjN/2020-07-28-12-58-27-Window.png" alt="2020-07-28-12-58-27-Window" border="0"></a>

**Comment by henrypp** [comment]
I confirm this is a bug.

Workaround is available:
- because new versions of routine library used new task scheduler engine (unified), i recommend do not use older versions of SW at your machine
- if you are used older version of SW before, then open SW and disable SkipUAC option and then restart OS and after that do not start old versions of SW.
- in next SW release i fix this issue.
