### ISSUE TITLE
[Feature Request] Rules for specific wifi networks

### ISSUE THREAD

**Issue by xdnicoco** [henrypp/simplewall#727]
I've found myself lately wanting to enable certain applications (mainly data-heavy synchronization apps) only when I'm connected to my home wifi network, and disable some of them when I'm connected to a public/work network.
I think it would be great if I could add rules based on the specific SSIDs to enable or disable those apps.

**Comment by asvc** [comment]
OK, what if user isn't using wireless connection? Filter by the host ip? Interface? What if the machine in question is using LTE modem or Bluetooth tethering?..
