### ISSUE TITLE
Profile broken since 3.2.2?

### ISSUE THREAD

**Issue by Manaplayer** [henrypp/simplewall#732]
I updated from version 3.1.2 to version 3.2.2. Since then, every time I completely restart Windows, I get a new request from FireFox and Thunderbird (portable) whether I should activate them or not, although I had already done so last time. I have already tried to create the complete profile again, but the same thing happens. The strange thing is that it only happens after a system restart. If I only restart Simplewall, everything seems to be correct for the time being, the programs are also permanently entered in the list, even after the system has been restarted. Nevertheless, the request comes back after the restart. With version 3.1.2, which I switched to again, everything works correctly again.

**Comment by asvc** [comment]
Can't reproduce, but sounds like a https://github.com/henrypp/simplewall/issues/739

**Comment by Manaplayer** [comment]
Maybe this video will show what i mean:

[video.zip](https://github.com/henrypp/simplewall/files/5136960/video.zip)

On version 3.1.2 this issue don't happen

**Comment by henrypp** [comment]
Let me see full-path to FireFox and Thunderbird (portable)? And how his appear in apps list in SW?

**Comment by Manaplayer** [comment]
It runs on a ramdisk, but it is always the same path, even after a complet restart of system.
[video2.zip](https://github.com/henrypp/simplewall/files/5140512/video2.zip)

**Comment by henrypp** [comment]
check 3.2.4

**Comment by Manaplayer** [comment]
Super! It runs correctly again now :)
