### ISSUE TITLE
Filters disabled through "HTTP" user rule (3.2.2)

### ISSUE THREAD

**Issue by thibault204** [henrypp/simplewall#733]
I updated to version 3.2.2 yesterday and I noticed that with HTTP user rule enabled, the "apps **without** internet access all have connections. I disabled HTTP rule and now filters are working properly again. Is this correct? In the previous version only "apps with internet access" were allowed connection.

**Comment by henrypp** [comment]
> I noticed that with HTTP user rule enabled, the "apps **without** internet access all have connections

![image](https://user-images.githubusercontent.com/3902025/89104380-92721b80-d408-11ea-8c05-78de5358e830.jpg)

YES!

**Comment by thibault204** [comment]
Yes, :)
I see now. it is working correctly, my issue is solved Thank you.
