### ISSUE TITLE
Feature Request: Ignore a drive

### ISSUE THREAD

**Issue by Chaython** [henrypp/simplewall#734]
Feature Request: Ignore a drive
Simplewall takes a very long time to load, how about an option to ignore certain devices? Or delay checking devices so GUI launches immediately.
I have 13tb of storage, when a drive is asleep simplewall waits for it to wake up, which can take 1m.
Just a small annoyance. 
I don't really understand why it waits for the drive at launch, rather than when purging unused? As it doesn't find new apps, unless they're launched.

**Comment by henrypp** [comment]
Try disable signature checking, nothing another checks was used on startup.
