### ISSUE TITLE
Can't manually or automatically install or update to 3.2.2

### ISSUE THREAD

**Issue by ptkovsky** [henrypp/simplewall#737]
Getting the following error when trying to install 3.2.2 on Windows 7 32 bit:
![1](https://user-images.githubusercontent.com/10148835/89155520-a6855c80-d571-11ea-82a3-7bf0f978be5f.png)
Reverted to 3.2 for now.

**Comment by henrypp** [comment]
Install [KB2533623](https://support.microsoft.com/KB/2533623)

**Comment by ptkovsky** [comment]
Nice, it worked now. Do you recommend installing any other essential security patches? Link something interesting to read about it? Thanks!

**Comment by henrypp** [comment]
> Do you recommend installing any other essential security patches?

Yes! All of them!

> Link something interesting to read about it? Thanks!

You can install custom update package with cut out telemetry.

https://blog.simplix.info/update7/
