### ISSUE TITLE
Tab on launch

### ISSUE THREAD

**Issue by Sibelius58** [henrypp/simplewall#738]
Starting with version 3.2.2, simplewall always shows the tab "Blocklist" instead of "Apps" at startup. Is it possible to make the tab displayed by default become "Apps" again?
Thank you

**Comment by henrypp** [comment]
Not true. SW displays last displayed tab on startup.

**Comment by bellgamin** [comment]
On startup, SW always shows last displayed tab for my computer, & also for my daughter's.
