### ISSUE TITLE
Allow outbound rule not working with 3.2.2, constantly asks for confirmation

### ISSUE THREAD

**Issue by xnoreq** [henrypp/simplewall#739]
Hello,

I have the following rule:
![grafik](https://user-images.githubusercontent.com/4028859/89459035-53c1c580-d768-11ea-8c78-f277bf33c100.png)
with *no further restrictions* on remote or local (both are empty).

I have *this rule applied to an exe.*

Yet, I keep getting network alert popups about this exe wanting to do an Outbond connection `"80 (http)","tcp","simplewall\BlockConnectionsV4","#548100","Outbound","Blocked"`.

**Comment by xnoreq** [comment]
One more hint: in the network alert popup when I hover over the exe link I see:
```
<path to exe>
Rule:
   Any [outbound]
Notes:
   System app
   Invalid (file not found or filter problem)
```

Could the problem be that this exe is created *temporarily* to run an update and then deleted again?

**Comment by kreon1** [comment]
I can conmfirm, every day firewall ask me for firefox and telegram permission.

**Comment by xnoreq** [comment]
Also, in the network alert popup, the application name/link moves to the right (outside the window to the point of becoming invisible) with repeat notifications.

**Comment by asvc** [comment]
Don't have such problem... Perhaps try limiting by protocol and remove square brackets from the rule name?

**Comment by henrypp** [comment]
check 3.2.4
