### ISSUE TITLE
A rule for blocking all [solved]

### ISSUE THREAD

**Issue by vgiv** [henrypp/simplewall#744]
Hi!. 

I create a rule that is to block all connections (any port, protocol, addresses):
![Image1](https://user-images.githubusercontent.com/23143025/89649484-8a632180-d8c9-11ea-985c-199456d09004.png)
![Image1a](https://user-images.githubusercontent.com/23143025/89651209-41609c80-d8cc-11ea-9d6f-7af3e2d96608.png)

Then I start IE (or any other program that use internet connections), and see that my rule does not block anything:
![Image2](https://user-images.githubusercontent.com/23143025/89649852-1aa16680-d8ca-11ea-81ea-d0ba797337e9.png)

Why? What I do wrong?

Simplewall: v.3.2.2 64bit (Unicode)
OS: Windows 7 64bit Ultimate.

**Comment by crazyyzarc** [comment]
You've to define a remote rule like these:
1.0.0.0-224.255.255.255

**Comment by vgiv** [comment]
No, it doesn't work. Besides, any time I edit the rule I get a message: "Something went wrong' Open debug log file..." In the file I see line
`"‎8/‎8/‎2020 ‏‎12:32:31 AM","FwpmFilterAdd()","0x80320005","Block all","3.2.2 Release"`

**Comment by bellgamin** [comment]
Um... Isn't the "block all outgoing" rule covered by SW's settings, as shown below?
![ScreenHunter_01 Aug  07 12 42](https://user-images.githubusercontent.com/66855058/89693973-e323c180-d8ab-11ea-9a4a-6ed37fdca92c.gif)

**Comment by vgiv** [comment]
bellgamin, yes, the boxes are checked just as shown on the screenshot. So I don't understand anything. With these setting all connections must be blocked without any rule, right?

**Comment by vgiv** [comment]
Oups, I'm stupid! The filters ware disabled by default. I must press button "Enable filters".
