### ISSUE TITLE
New WindowsSpyBlocker block rules aren't implemented yet

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#745]
https://github.com/crazy-max/WindowsSpyBlocker/tree/master/data/simplewall lists have been updated 5 days ago, but simplewall itself hasn't been updated yet.

Is there a way this can be done quicker, e.g. by checking for updates of https://github.com/crazy-max/WindowsSpyBlocker/raw/master/data/simplewall/extra/blocklist.xml etc. directly?

Are you watching releases of https://github.com/crazy-max/WindowsSpyBlocker via GitHub notifications?

**Comment by Shen897** [comment]
I think a better way is to add the option to update the WindowsSpyBlocker list directly from the app. 
We can update the app from `help` ->`check for updates` but since WindowsSpyBlocker lists updated regularly and simplewall can't  keep up with it it's better to implement an option to pull them directly from https://github.com/crazy-max/WindowsSpyBlocker/tree/master/data/simplewall 
`help` ->`check for WindowsSpyBlocker updates`

**Comment by ltGuillaume** [comment]
@Shen897 That's basically what I meant with the second paragraph, yeah.

**Comment by ltGuillaume** [comment]
This is strange: I had to manually check for updates in order to see that there was indeed an update of the internal rules (dated August 3rd!).

I have rebooted my system at least 15 times since August 3rd, so it should have picked up there was an update (auto-check for updates is enabled).

**Comment by ltGuillaume** [comment]
@henrypp Again, I got an update notification for the September 8 internal rules update only today. On three different machines that are rebooted at least once a day. Any idea how this is possible?

**Comment by henrypp** [comment]
@ltGuillaume [update checking period constant is incorrect](https://github.com/henrypp/routine/blob/master/rconfig.hpp#L99) - it checks 48 days instead 48 hours, i fix this asap...

**Comment by ltGuillaume** [comment]
Aahaa that makes sense! Thanks for looking into this! 👍

**Comment by Shen897** [comment]
Is there a notification for updates? I got non. In fact this post is what made me check for update and the update checker told me about the September 8 internal rules update.

**Comment by ltGuillaume** [comment]
@henrypp just explained that he made a mistake in the code that causes the automatic updates routine to check every 48 days, instead of every 2 days. That's why you and I missed the September 8 rules update.
