### ISSUE TITLE
Show a full path instead of only process name in the popup alert

### ISSUE THREAD

**Issue by Shen897** [henrypp/simplewall#746]
![N2GI8kx](https://user-images.githubusercontent.com/66660101/89693010-ec497880-d915-11ea-8043-e9b63eebf4e7.png)

It's really useful to show a full path instead of only process name in the popup alert so you can know the origin of that process.

**Comment by bellgamin** [comment]
I agree. For many files (such as update.exe) the path or calling app is not easily recognized.

**Comment by henrypp** [comment]
@Shen897 @bellgamin 

You can put cursor over filename to view full path. It's not so hard.
