### ISSUE TITLE
Microsoft Teams (desktop client)

### ISSUE THREAD

**Issue by Ra0EL** [henrypp/simplewall#747]
Hi,

Looking for help on fixing a little annoyance with Microsoft Teams desktop client on my W10 machine.

**Problem** :
- All users have _white_ status (instead of green/yellow/red)  ;  
  though it does not prevent from e.g. chatting with them.  
  And everything else is working fine.
- On top of window, there is this message "We ran into a problem. Reconnecting…"

**What I tried but does not fix the issue** :
- temporarily re-enabled all blocked apps and all blocked services

**Only way to fix this issue** :
- Disable Simplewall (all filters) and re-enable Windows Firewall rules.

**Question** :
- Any idea how to investigate / fix that ?  
  At this step, I figure the problem is not with any blocked apps or services, but likely specific port to open…  
  (and yes, I don't know that much about firewall in Windows 🤦 )

Best regards.

**Comment by PunnyBoi** [comment]
Hi,

So, I was facing the same problem with MS Teams desktop client. I didn't try your solution of disabling all filters. I was digging the internet for the solution and found one on [this](https://techcommunity.microsoft.com/t5/microsoft-teams/ms-teams-connection-problem/m-p/1396483). I am copying the solution here too (credits: [SAHAM](https://techcommunity.microsoft.com/t5/user/viewprofilepage/user-id/670296)). Let me tell you one thing, this solution makes no sense at all but it worked for me. I hope it works for you as well.

1. Right click on the MS Team app -> properties -> "compatibility" tab -> "compatibility mode" section -> Tick the "Run this program in compatibility mode for" -> windows 7 -> Apply -> Ok

2. Right click on the MS Team app -> Run as administrator -> close it (without sign in)

3. Right click on the MS Team app -> properties -> "compatibility" tab -> "compatibility mode" section -> Remove tick the "Run this program in compatibility mode for" -> Apply -> Ok

4. Open the MS Team app and sign in.

Do tell me if it works for you or not.

**Comment by Ra0EL** [comment]
And sorry for the very belated answer.

So, I am totally amazed but… it worked ! 🙆‍♂️ 
Problenm solved. Not related to Simplewall at all....

Many thanks @PunnyBoi  !

**Comment by happyboy1992** [comment]
This method does not work on my side. :(
