### ISSUE TITLE
logical option for ruleset

### ISSUE THREAD

**Issue by crazyyzarc** [henrypp/simplewall#748]
Is it already possible to allow/block logical combinations of IP address ranges explicitly
If not, it would be my idea: I want to completely ban communication for mstsc.exe except in my private IP address range. At the moment this is only possible if I have not "forbidden" the allowed IP address range

For example:
mstsc @ block all
except:
192.168.0.0/24

**Comment by henrypp** [comment]
just create user rule 192.168.0.0/24 and set it to mstsc
