### ISSUE TITLE
[Feature Request] Allow to paste a list of domains instead of one-by-one entery in Rules editor

### ISSUE THREAD

**Issue by ghost** [henrypp/simplewall#749]
It's counterproductive and not a user-friendly to create a rule to block list of domains by manually add them one-by-one. 
![Untitled](https://user-images.githubusercontent.com/66660101/89779171-7876be00-db17-11ea-976d-200c27d69af2.png)

If there is a way to just copy the list and add/paste it to the rule editor it would be really useful. There are a lot of software that ping home for information and telemetry stuff and it's not Microsoft software only, that means the regular Joe has to manually add huge lists one-by-one and that painful.

**Comment by pwn0r** [comment]
Yes. 

And same as my pretty dated request --- allow to link rules to a file. That would be even better. 
Would be really cool, as sometimes I need to B& various bot networks who attempt to break in and that could be 500 IP address *blocks*. Not even seperate IP addresses.

**Comment by asvc** [comment]
> a way to just copy the list and add/paste it to the rule editor it would be really useful

+1

**Comment by AndShy** [comment]
Also will be good to use regular expressions as domain name. How is it done in Comodo IS.

**Comment by Ithiloneth** [comment]
+1 This would be a most welcome feature!

I read on the wiki for the old interface that lists could be added using semi-colon; no luck so far for me...

Tried:
> IP;IP;IP;
> IP;IP;IP
> 
> IP; IP; IP;
> IP; IP; IP

**Comment by henrypp** [comment]
`ip;ip` works in latest versions
