### ISSUE TITLE
Not loading on system startup

### ISSUE THREAD

**Issue by cinke** [henrypp/simplewall#75]
Simple wall does not start with system, when corresponding option is ticked in Setting - General.
(And program string is at HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run)

However, if I copy the program string to 
HKLM\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Run
then Simplewall loads all right.

Not happening on my work PC.
Both machines run Windows 10 Pro 64bit (Volume license at my workplace).

Strange.
Not even sure if it is an issue, or it's just my home pc is acting weird.

**Comment by henrypp** [comment]
Are you really use 64-bit executable under 64-bit OS?

**Comment by cinke** [comment]
My windows is 64bit.

Originally I downloaded the zip file, then extracted the 64 bit folder to "program files".
Recently I used the installer.
I checked the file size in "program files" folder (599 040 byte), it matches the size of the 64bit installer.
Process hacker also identifies it as a 64bit process.

**Comment by GHosTiKuS** [comment]
I can confirm on Windows 7 x64
In my case there is no any simplewall string in HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run nor in HKLM\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Run created when option is ticked.
Maybe its somehow connected with "portable mode" (simplewall.ini in application folder)?

**Comment by henrypp** [comment]
Check from non-UAC  folder. `"program files"` is not desegned to contain portable applications.

**Comment by GHosTiKuS** [comment]
Uhm... i understand now how its works... simplewall creating autorun string for user that it runs under (sorry for my english), and as my main account have no admin rights, i run simplewall under other user and for that user autorun created (but i dont logging in locally under that user... is there possibility to add "Load on system startup (for all users)" option?)...
ps: i have disabled standard admin account
offtopic: how i can report (maybe i can collect some more data) bug, that when i wake my computer from sleep mode simplewall is behaves strangely (black icon context menu, main window blinking ets)?

**Comment by githubcom13** [comment]
I have the same problem with version 2.2.12 64bits, the previous version does not have this problem.
There was a bug when upgrading from version 2.2.10 to version 2.2.12, 2 versions coexist in the list of installed programs. I uninstalled the old version.

**Comment by henrypp** [comment]
2.3.2 fixed

**Comment by cinke** [comment]
What caused this issue, if I may ask?

Henry++ <notifications@github.com> ezt írta (időpont: 2018. jún. 27., Sze
10:52):

**Comment by henrypp** [comment]
@cinke simplewall runs as admin account and create autorun entry in HKCU registry root, it will create entry for admin account, not for currently logged-in user.

**Comment by cinke** [comment]
I see, thanks.
Simplewall is just great, thanks for your work.

Henry++ <notifications@github.com> ezt írta (időpont: 2018. jún. 29., Pén
7:39):

**Comment by accnetdev** [comment]
Hi all,

Just install 3.7.8 after several years of TinyWall (last was 3.3.1).

Simplewall does not start on my standard user I a using every day.
I red this topic, but as far as I understand, the are no solution suggested to launch (and and be able to manage, with elevation if necessary) Simplewall from my standard user everyday used profile.

Please could you explain?

**Comment by queueeeee** [comment]
@accnetdev have you found your solution? same started happening for me

**Comment by henrypp** [comment]
@accnetdev & @queueeeee [there is a fix](https://github.com/henrypp/simplewall/issues/1851#issuecomment-2295982173)
