### ISSUE TITLE
[Feature request] Allow/Block Folder

### ISSUE THREAD

**Issue by Jaitsu** [henrypp/simplewall#751]
I'd love it if I could block or allow programs based on the folder they're located in. For instance, I have a utility for my laptop that updates *very* frequently, and every time it does, it contacts the internet from a new subfolder with a random 8-digit hash for a name, meaning I get repetitive prompts every day, sometimes multiple times a day. If I could allow the parent folder, I wouldn't have that problem. Even "allow signer" would be good, as they're all signed by the same signer.

**Comment by asvc** [comment]
Good idea re. "Filter by signed cert", less confident about the "parent folder". What if malicious payload is dropped into such folder by malware?
