### ISSUE TITLE
[Feature Request] Check allowed apps for changes

### ISSUE THREAD

**Issue by nji9nji9** [henrypp/simplewall#752]
Actually I can't imagine that this hasn't been asked for:

Recently I changed an app that had SimpleWall's permission
to access the internet and ...
everything worked as before!

I think this should not happen ... a security issue to my opinion.

If SimpleWall grants internet access to an app,
it must take care that this is linked to exactly that binary file.
Otherwise if there is only one app which is permitted internet access,
every file has internet access (by just moving, renaming).

Remains the question how and when to check the equality.
How: CRC?
When:
Either synchronous: By time schedule, every time SimpleWall is started, ...
or asynchronous: FileSystemWatch on all allowed apps if changed.

**Comment by asvc** [comment]
@henrypp 
This sounds sane actually. Does SimpleWall and/or WFP layer check anything apart from the file path?

**Comment by henrypp** [comment]
Crc is a deprecated shit and this is a duplicate #394.
