### ISSUE TITLE
[feature suggestion] Rate Limit

### ISSUE THREAD

**Issue by pwn0r** [henrypp/simplewall#754]
Add an option to a rule to limit connections rate. 

I'm not talking about bandwidth, only connection initialization rate.  I dont know about outbound, probably not necessary. But for inbound it is useful. Linux (e.g. Ubuntu) has some options for that. 

There need to be three user defined parameters: time window, connection rate, ban time limit. E.g. example of my settings on one Linux VM -- 10min time window, 5 attempts, 1hr time ban.

**Comment by asvc** [comment]
This reads like an out of scope for what Simplewall is. You might consider `sshguard`, `fail2ban` and similar tools.

**Comment by cocoon** [comment]
Yes there are many different ones, just some links:

One with full Windowes Filtering Platform:
https://github.com/vokac/F2B

or simple one that creates FW-Rules only:
https://github.com/glasnt/wail2ban
