### ISSUE TITLE
Time Stamps for packet logs and sorting in the gui

### ISSUE THREAD

**Issue by BullShark** [henrypp/simplewall#757]
In the "Packet log" tab of the gui, there should be time stamps and the ability to sort by categories "Name, Address (Local), Port (Local), Address (Remote), Port (Remote), Protocol, Filter, and Direction. I'm not sure if the newest in the logs is the top or bottom. There are currently no time stamps.

Thanks,

**Comment by asvc** [comment]
Timestamps are handy, but would increase the log size. Decision is up to @henrypp .
Filtering would be ace though.

**Comment by BullShark** [comment]
The log already includes timestamps.

**Comment by pdrive** [comment]
timestamps would be lovely. having to mouse over an entry is annoying.
also, either auto scroll and or the ability to sort by time.
