### ISSUE TITLE
No idea what time it is

### ISSUE THREAD

**Issue by BullShark** [henrypp/simplewall#759]
I changed my ntp server to something that's not a microsoft server from the windows 10 control panel, but it's still being automatically blocked by the firewall. How do I allow only pool.ntp.org? Also my firewall log doesn't give hostnames, so it can be extremely difficult and time consuming to copy and paste ips to the command prompt to run the whois command on them and figure out what they belong to. This seems like something the firewall could do automatically? But for now, what about the time?

simplewall is blocking WSL, Windows Subsystem for Linux. I can't figure out how to unblock it. All internet access is denied from it, not just the microsoft telemetry servers. I cannot ping any domain or ip from it. So I thought if I tried to ping a host, and it was denied, it should create a new log in the firewall. Then I can use that log entry to unblock it. But I could not find any new log created from my ping. And it's difficult enough to figure out if the newest logs are on the top or on the bottom because the time stamps are not shown and sorting is disabled. Let me know how to solve this. Thanks in advance.

**Comment by asvc** [comment]
> How do I allow only pool.ntp.org? 
 Allow via IP address instead of a domain name

> simplewall is blocking WSL, Windows Subsystem for Linux
No issues with WSL1. Are you using 2nd version by any chance?

**Comment by henrypp** [comment]
Allow NTP in system rules.

Try sync system time, and check SW log to see what is blocked.

**Comment by deepaktrama** [comment]
Just to help others who are trying to do this, this is what worked for me on simplewall 3.8.3
In the simplewall windows app, go to the system rules tab and ensure ntp is checked. there are a lot of rules there so you can also search there for ntp if you cannot see it.
see attached screenshot.
Thanks henry for creating such a fantastic app and keeping it free.
![simplewall](https://github.com/user-attachments/assets/c37c335f-a09a-446f-ba4d-49d3962eb00c)
