### ISSUE TITLE
CEIP task deleted by SimpleWall setup

### ISSUE THREAD

**Issue by asvc** [henrypp/simplewall#761]
See https://www.virustotal.com/gui/file/796d3acd305d9e133e9fe079a98ee2ea5b6133e4cc97ddd92f57c93c89d48e9f/behavior/VirusTotal%20Sysmon

> Processes terminated
> 2804 - C:\Windows\system32\schtasks.exe /delete /f /TN "Microsoft\Windows\Customer Experience Improvement Program\Uploader"

It is not like I support CEIP, just curious why is this necessary.

**Comment by henrypp** [comment]
> When executing the file being studied, the following processes were terminated.

Lol. Nsis [only create](https://github.com/henrypp/builder/blob/master/installer.nsi#L188) `schtasks` process, not terminate.
