### ISSUE TITLE
Switch PayPal to "Friends & Family"

### ISSUE THREAD

**Issue by savchenko** [henrypp/simplewall#762]
Otherwise I am not sure to whom is the donation, @henrypp or PayPal Holdings...
![image](https://user-images.githubusercontent.com/300146/91239856-01a10e00-e730-11ea-9c5e-51bfc3821608.png)

**Comment by bellgamin** [comment]
I clicked the heart button & a pop-up appeared with [code]https://www.paypal.me/henrypp[/code}. paypal.me IS Friends & Family. What's your problem?

**Comment by asvc** [comment]
@bellgamin , check the fee on the screenshot. It doesn't quite make sense.

**Comment by bellgamin** [comment]
I donate from time to time. I see NO such display as that in your screenshot. I see the 2 items shown below, then the process takes me to my PayPal account where I complete the transaction.

![ScreenHunter_01 Aug  25 14 53](https://user-images.githubusercontent.com/66855058/91242412-130ff900-e6e3-11ea-931c-e8b4ea9a39dc.gif)
![ScreenHunter_02 Aug  25 14 53](https://user-images.githubusercontent.com/66855058/91242437-20c57e80-e6e3-11ea-873e-7d2be7e5346e.gif)

**Comment by asvc** [comment]
Weird. Anyway, sent some BTC instead of $.

**Comment by asvc** [comment]
Also, https://github.com/henrypp/simplewall/issues/664

**Comment by henrypp** [comment]
i try to switch-off bussiness account on paypal because it does not make sense in near time.

but i am open yandex money, you can donate money in this way now.

https://money.yandex.ru/to/4100115776040583

**Comment by asvc** [comment]
Tried Yandex Money, without much of success:
![image](https://user-images.githubusercontent.com/300146/91416215-9a25b400-e83e-11ea-86ad-9e65b1bdbb6a.png)

@henrypp , you might consider accepting "cash in an envelope" &mdash; would be easier than all of this :)

**Comment by henrypp** [comment]
@asvc 

Khe-khe, yandex money required identity so i can add this information at least tommorow.

**Comment by henrypp** [comment]
@asvc 

Done! Check it!

**Comment by asvc** [comment]
Homing pigeons are more reliable than Yandex Money!
![image](https://user-images.githubusercontent.com/300146/91558525-09c29e80-e926-11ea-8d56-8cc23aacd90e.png)

**Comment by henrypp** [comment]
@asvc 

Lol, no, yandex money is normal. Try another browser)

**Comment by asvc** [comment]
Man, it was the "naked" Microsoft Edge. Can't go further than that.

**Comment by henrypp** [comment]
> Perhaps Yandex doesn't like Australian cards?

Yes, maybe.

And maybe because of this PayPal gives big fee for Australian cards.
