### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by userneu** [henrypp/simplewall#764]
Hi.
When the program starts an error appears. Screenshot attached. 
Win10 LTSC, simplewall 3.2.3
![235346547](https://user-images.githubusercontent.com/4303295/91467302-13ea8b80-e899-11ea-9097-a4530e9f05f5.JPG)

**Comment by henrypp** [comment]
- check assertion failure on clean profile (when profile.xml is empty)
- check assertion failure on clean configuration (when simplewall.ini is empty)
- send profile.xml or/and profile.xml and simplewall.ini if it trigger assert
- when you press "Skip" button assertion failure is gone until you start SW again?

**Comment by userneu** [comment]
Empty profile.xml doesnt solve the problem. Same with empty simplewall.ini. After cleaning both files the error does not resolve.

> when you press "Skip" button assertion failure is gone until you start SW again?
I press skip, error is gone and simplewall starts. Until next program start.

**Comment by henrypp** [comment]
Hi,

try run this debug build (just replace existing
executable). on startup you get message with more information about "Assertion failed",
press Prt scrn and let me see!


[simplewall-3.2.3-debug.zip](https://github.com/henrypp/simplewall/files/5175446/simplewall-3.2.3-debug.zip)

**Comment by userneu** [comment]
Hi,
![аврапопрло](https://user-images.githubusercontent.com/4303295/92306173-a1169a00-ef95-11ea-8842-8969523e0f43.JPG)

**Comment by henrypp** [comment]
check 3.2.4

**Comment by userneu** [comment]
Works fine, thanks.
