### ISSUE TITLE
Add filtering to the application list

### ISSUE THREAD

**Issue by savchenko** [henrypp/simplewall#766]
How about an ability to search/filter the lists? Apps, Services, UWP...
Single text-input that filters in real time would be perfect.

Currently, pressing <kbd>CTRL+F</kbd> opens a "Find" window that does nothing.

**Comment by NikolayEKolev** [comment]
@henrypp Is there a plan to add a dynamic search box soon?

**Comment by henrypp** [comment]
@NikolayEKolev yes

**Comment by henrypp** [comment]
dupl #663
