### ISSUE TITLE
Simplewall 3.2.4_VirusTotal Scanned Result

### ISSUE THREAD

**Issue by newbie337** [henrypp/simplewall#769]
Hi, The scanned result from Viurstoal.com shows the newest simplewall-3.2.4-setup contains three malicious file in it. Also, I am using the 3.2.2 version now, I noticed the simplewall is blocked in WD's protection history Could you provide solutions? I love your app, Thank you.
![VirusTotal](https://user-images.githubusercontent.com/65002791/92367445-fb942f80-f128-11ea-853d-5c6bce2b84c6.jpg)
![Windows Defender](https://user-images.githubusercontent.com/65002791/92367449-fc2cc600-f128-11ea-88db-affeba236e91.jpg)

**Comment by bellgamin** [comment]
Hmm.. of over 100 AVs on VirusTotal, 3 pegged it as possible malware. One of these (APEX) is an AI/Behavior Blocker. None of those 3 is a top tier AV. Conversely, over 90 AVs found SimpleWall to be clean including all of the top tier AVs such as Kaspersky, Eset, Avast, McAfee, & Avira.

The Windows Security alert is based on "risky action (behavior, NOT signature) and is graded "low" risk.

My computer's security apps (VoodooShield, WiseVector, Hitman Pro, & Kaspersky) all find Simplewall  3.2.3 to be totally clean of malware.

The alerts by VirusTotal & Windows Security warrant looking into by SimpleWall's developer. However,  I am quite satisfied that these are all False Positives by a tiny minority of AV's.

**Comment by newbie337** [comment]
Thank you for your reply. I asked because i am not a computer expert. You gave me more confidence for using the simplewall

**Comment by bellgamin** [comment]
I'm happy to help. I'm sure SimpleWall's developer will add his comment. He is very skilled and diligent.

**Comment by henrypp** [comment]
I even dont know names of this AV, lol

About WD risky action:
it's normal - SW access certificates storage to check apps signatures.
