### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by OzgunKB** [henrypp/simplewall#770]
> Önem Derecesi	Kod	Açıklama	Proje	Dosya	Çizgi	Gizleme Durumu
Hata	C1083	kaynak dosyası açılamıyor: '..\routine\rapp.cpp': No such file or directory	simplewall	C:\Users\1700x\Desktop\simplewall-masterorj\c1xx	1	
Hata	C1083	kaynak dosyası açılamıyor: '..\routine\routine.cpp': No such file or directory	simplewall	C:\Users\1700x\Desktop\simplewall-masterorj\c1xx	1	
Hata	C1083	içerme dosyası açılamıyor: 'routine.hpp': No such file or directory (kaynak dosyası derleniyor src\log.cpp)	simplewall	c:\users\1700x\desktop\simplewall-masterorj\src\global.hpp	6	
Hata	C1083	içerme dosyası açılamıyor: 'routine.hpp': No such file or directory (kaynak dosyası derleniyor src\controls.cpp)	simplewall	c:\users\1700x\desktop\simplewall-masterorj\src\global.hpp	6	
Hata	C1083	içerme dosyası açılamıyor: 'routine.hpp': No such file or directory (kaynak dosyası derleniyor src\editor.cpp)	simplewall	c:\users\1700x\desktop\simplewall-masterorj\src\global.hpp	6	
Hata	C1083	içerme dosyası açılamıyor: 'routine.hpp': No such file or directory (kaynak dosyası derleniyor src\helper.cpp)	simplewall	c:\users\1700x\desktop\simplewall-masterorj\src\global.hpp	6	
Hata	C1083	içerme dosyası açılamıyor: 'routine.hpp': No such file or directory (kaynak dosyası derleniyor src\security.cpp)	simplewall	c:\users\1700x\desktop\simplewall-masterorj\src\global.hpp	6	
Hata	C1083	içerme dosyası açılamıyor: 'routine.hpp': No such file or directory (kaynak dosyası derleniyor src\timer.cpp)	simplewall	c:\users\1700x\desktop\simplewall-masterorj\src\global.hpp	6	
Hata	C1083	içerme dosyası açılamıyor: 'routine.hpp': No such file or directory (kaynak dosyası derleniyor src\wfp.cpp)	simplewall	c:\users\1700x\desktop\simplewall-masterorj\src\global.hpp	6	
Hata	C1083	içerme dosyası açılamıyor: 'routine.hpp': No such file or directory (kaynak dosyası derleniyor src\main.cpp)	simplewall	c:\users\1700x\desktop\simplewall-masterorj\src\global.hpp	6	
Hata	C1083	içerme dosyası açılamıyor: 'routine.hpp': No such file or directory (kaynak dosyası derleniyor src\profile.cpp)	simplewall	c:\users\1700x\desktop\simplewall-masterorj\src\global.hpp	6	
Hata	C1083	içerme dosyası açılamıyor: 'routine.hpp': No such file or directory (kaynak dosyası derleniyor src\notifications.cpp)	simplewall	c:\users\1700x\desktop\simplewall-masterorj\src\global.hpp	6

**Comment by henrypp** [comment]
https://github.com/henrypp/simplewall/issues?q=is%3Aissue+is%3Aclosed+routine
