### ISSUE TITLE
最新更新

### ISSUE THREAD

**Issue by liao6964799** [henrypp/simplewall#773]
刚刚更新时提示更新不了，不是更新版本，好像是更新规则？而且需要翻墙才可以更新。。。请问这个更新是什么，对翻墙有影响吗？

**Comment by kekukui** [comment]
**必须允许防火墙程序访问网络。**
![image](https://user-images.githubusercontent.com/20834957/94252109-7adb7e80-fef1-11ea-9f90-70485441b010.png)
