### ISSUE TITLE
Win7-64 Notifications Missing

### ISSUE THREAD

**Issue by jsnx11** [henrypp/simplewall#774]
Notifications for new and existing apps do not appear; no prompt given to user for approve/deny/etc.

Noticed this issue starting after v3.0.6 RC

Tried most of the new releases, but all have same issue. 
Reverting back to v3.0.6 RC or sooner makes notifications show again.

There are a few old tickets related, but now ~1year old

Thanks

**Comment by henrypp** [comment]
Whats in log?

Possible duplicate #654

**Comment by Wakagithub** [comment]
Hello. Somewhat the same for me. Windows 7 64-bit. After logging off then on at least twice or more than twice, the Packets log tab is always blank, same for the external Show log.

The previous version which doesn't have the Packets log tab yet, I could log off and on many times without the issue. I use SnakeTail for the external Show log.

My remedy is to restart/reboot Windows. Then I could log off and on again which would result to the issue again.

**Comment by jsnx11** [comment]
Just tried a bunch of versions -- it looks like the last working notifications are v.3.1
v3.1.1+ the notifications do not show.
 
No recent errors in simplewall_debug or simplewall_error.
Nothing appears in the packet logs.

**Comment by waterj** [comment]
Hi guys！It turns out that LoadLibraryEx("fwpuclnt.dll") failed on win7, and microsoft docs says KB2533623  should be installed.  So do it and be happy!

**Comment by henrypp** [comment]
> It turns out that LoadLibraryEx (L"fwpuclnt.dll", nullptr, LOAD_LIBRARY_SEARCH_USER_DIRS | LOAD_LIBRARY_SEARCH_SYSTEM32) failed on win7, and microsoft docs says KB2533623 should be installed when use flags of LOAD_LIBRARY_SEARCH_USER_DIRS or LOAD_LIBRARY_SEARCH_SYSTEM32.

Yes, may be notifications broken because of that.

> Or just load the library with flag LOAD_LIBRARY_AS_DATAFILE.

No, you can't use loaded library as executable if you set this flag.

**Comment by waterj** [comment]
> > Or just load the library with flag .
> 
> No, you can't use loaded library as executable if you set this flag.

You are right according to ms api docs, but it's wierd that LOAD_LIBRARY_AS_DATAFILE actually works on win7

**Comment by Vechio** [comment]
> 
> 
> Hi guys！It turns out that LoadLibraryEx (L"fwpuclnt.dll", nullptr, LOAD_LIBRARY_SEARCH_USER_DIRS | LOAD_LIBRARY_SEARCH_SYSTEM32) failed on win7, and microsoft docs says KB2533623 should be installed when use flags of LOAD_LIBRARY_SEARCH_USER_DIRS or LOAD_LIBRARY_SEARCH_SYSTEM32. Or just load the library with flag LOAD_LIBRARY_AS_DATAFILE.

I can confirm that the notifications are working in Windows 7 after installation Windows6.1-KB2533623-x86.msu
