### ISSUE TITLE
Regular crashes since 3.2.4 and UAC skip bug

### ISSUE THREAD

**Issue by ptkovsky** [henrypp/simplewall#775]
It started crashing regularly for me since 3.2.4. Noticed it also sometimes starts taking 100% of one logical CPU time and I get the same message when trying to exit:

![crash](https://user-images.githubusercontent.com/10148835/93079506-ea04d780-f694-11ea-89e0-05b4d21777b9.png)

Also skip UAC screen option is still broken for me in 3.2.4:

![uac settings bug](https://user-images.githubusercontent.com/10148835/93081215-95169080-f697-11ea-8776-4ce8517126f9.png)

Windows 7 32 bit. Don't have much free RAM on this machine but other software doesn't crash and it only started crashing since 3.2.4.

**Comment by henrypp** [comment]
> It started crashing regularly for me since 3.2.4. Noticed it also sometimes starts taking 100% of one logical CPU time and I get the

Ok, i look

> Also skip UAC screen option is still broken for me in 3.2.4:

`SkipUacIsEnabled` is no more used.

**Comment by ptkovsky** [comment]
Hi, thanks for replying.

I still think that the issue might be related to memory, here is a new evidence of that: 
![sw mem err](https://user-images.githubusercontent.com/10148835/94364999-22b1a180-00d6-11eb-892c-271f442d0596.png)

**Comment by henrypp** [comment]
Can this happen if you disable Logging into UI option?

**Comment by ptkovsky** [comment]
Sorry, do you mean this option? Please elaborate. If so, looks like it was already disabled:
![sw log](https://user-images.githubusercontent.com/10148835/94365456-d1a3ac80-00d9-11eb-8c52-b79471d479c8.png)
