### ISSUE TITLE
feauture request - disable update check

### ISSUE THREAD

**Issue by brightersun99** [henrypp/simplewall#777]
Could we get a feature that disables update checking? some of us don't like to update things and clicking out of it is really annoying, especially when we use a few of your applications and they all do it. 
I did just download it from the site 5 minutes ago so it shouldn't be doing that anyways.

**Comment by frustreated** [comment]
估计得自己编译一下，去掉就行了。

**Comment by Alcazer** [comment]
In "**Settings**" disable "**Periodically check for updates (recommended)**"
