### ISSUE TITLE
Whats wrong here. (Sorry for maybe stupid question, new at blocking windows from spying me. :D ) 

### ISSUE THREAD

**Issue by alext6565** [henrypp/simplewall#778]
In Simplewall, "System" and "svhost.exe" are in the list of blocked applications.
If you open TCP View, you can see that svhost.exe and system are sending and receiving data to remote address asterisk symbol. If I deactivate "Show unconnected Endpoints" in the TCP View, it no longer appears there. What does that mean the asterisk symbol ? And where do the two files send and where do they receive data from, or what kind of data are they if they supposedly have no connection to the Internet?
Btw:  I only blackened the Screenshots because of my desktop name. Nothing interesting there. :D

![simplewallscreen](https://user-images.githubusercontent.com/71760793/93996882-14404e80-fd93-11ea-9253-3ebdd5ad1b09.PNG)
![2](https://user-images.githubusercontent.com/71760793/93996895-186c6c00-fd93-11ea-97f1-356ebc4664c6.PNG)
![3](https://user-images.githubusercontent.com/71760793/93998173-7e0d2800-fd94-11ea-8fa1-a36844b81cb1.PNG)

**Comment by Alcazer** [comment]
In "**System rules**" tab you can disable what you want.

**Comment by alext6565** [comment]
Ok, deactivated Netbios Rules and now no more trafic there. Thx.
