### ISSUE TITLE
Application both Blocked and Allowed

### ISSUE THREAD

**Issue by Xierion** [henrypp/simplewall#779]
I am seeing a number of processes in the packet log that show both Blocked and Allowed. What would be causing this, and are the connections Blocked or Allowed?
![Simplewall Blocked or Allowed](https://user-images.githubusercontent.com/23009638/94024778-f4427680-fdf6-11ea-8973-f2cd49e87005.PNG)

**Comment by henrypp** [comment]
look at your blocklist settings, there is the answer.
