### ISSUE TITLE
Не блокирует сервисы и не уведомляет.

### ISSUE THREAD

**Issue by grinchrussia** [henrypp/simplewall#781]
1).Если создать свое правило для приложения только для протокола TCP и неуказать port назначения или IP и port(8.8.8.8:443), то приложения сможет выходить и по UDP и TCP. Несмотря на то что указано только TCP.
2).Приложение svchost.exe, если разрешено то все сервисы от него зависящие выходят в интернет без уведомления и правила(например BITS,CryptSVc,WpnService) 
3). SearchUI.exe тоже выходит  в сеть без спроса.
[https://yadi.sk/i/jbYNZL5w5DuPRw](url)

**Comment by henrypp** [comment]
1) неправда
2) вот тут всё верно
3) searchui выходит в сеть согласно правилу (extra_13.107.21.200), котрое ты сам включил, по умолчанию оно отключено
