### ISSUE TITLE
Colours @ UI

### ISSUE THREAD

**Issue by snfmX** [henrypp/simplewall#783]
Hello,
just updated on 3.2.4 and saw some problems with UI:

1. Apps with user rules dont colored

![1](https://user-images.githubusercontent.com/71968427/94364136-ff442200-00e8-11eb-91dd-f7fce7710c1a.jpg)

2. Services with user rules dont colored by user rules colour

![2](https://user-images.githubusercontent.com/71968427/94364151-197e0000-00e9-11eb-84a9-45615587c8f8.jpg)

3. User rules dont grouping by "for all" and "for apps"

![3](https://user-images.githubusercontent.com/71968427/94364174-492d0800-00e9-11eb-9c07-c40e5ce59714.jpg)

**Comment by henrypp** [comment]
1. There is no need to highlight items already contained in "Apps with user rules", this color highlight only apps in Rules editor, Network tab.
2. see n.1
3. Yes, user rules grouping by enabled and disabled only. Rules with applied apps is highlighted.

**Comment by snfmX** [comment]
But if they colored like @ 3.1.1 visually its more comfortable,
and can say same about grouping - more comfortable if u can seperate "apps only" from "for all".

Do u have any plans back it like an option?

Thanks for fast reply.

**Comment by henrypp** [comment]
> Do u have any plans back it like an option?

No
