### ISSUE TITLE
Connections without rules that should be blocked getting through

### ISSUE THREAD

**Issue by hushkamala** [henrypp/simplewall#784]
I am on windows 10 2004, and was integrating hotfixes in NTLite on a windows 7 instalation ISO when i saw WpnService and CryptSvc services making http connections. (WpnService Outbound TCP 443 - CryptSvc on port 80 dont remember the details).

Both are under svchost and i have svchost with disabled notifications and the only allowed rules i have set is for my local lan ip's.

So since this were http connections to microsoft servers they should be blocked without notifications and appear in the simplewall packests log that i have enabled.

I right clicked in the connections tab and closed the connection for WpnService long after i was done with the integration of the hotfixes, it closed the connection and reopened another, which again should be blocked.

I dont see user rules or system rules that would let this connections through. Is it normal behavior or not?

EDIT: Creating a user block rule for WpnService and closing the connection manually does block the connection from reopening.

Screenshot of this happening without NTLite running and after i closed the connection manually:
![2020-09-28](https://user-images.githubusercontent.com/72048073/94489855-2aa83900-01dd-11eb-980e-b854fc27d1de.jpg)

**Comment by henrypp** [comment]
![sshot-001](https://user-images.githubusercontent.com/3902025/94519584-5564b280-021a-11eb-8c37-e15ef07941a4.png)
it is WU rule, you enabled it yourself

**Comment by hushkamala** [comment]
Oh ok... i was using the recommended setting for wu. Looks like the recommended setting for me is block and not disable. I thought disabled would block connections since most of them come from svchost and no allow rules and no notifications were set for svchost.

Sorry for wasting your time, and thank you.
