### ISSUE TITLE
USB tethering (rndis) general failure

### ISSUE THREAD

**Issue by char101** [henrypp/simplewall#789]
Hi,

Issue: on first boot, when enabling usb tethering to android phone, the network connection does not work. Pinging the gateway results in general failure. Socket connection results in access denied error.

Platform:
Windows 10
simplewall 3.2.4

Steps:
1. boot windows 10
2. simplewall automatically runs on boot
3. enable usb tethering on android phone
4. connection problem with above error
```
> ping  192.168.42.129

Pinging 192.168.42.129 with 32 bytes of data:
General failure.
General failure.
General failure.

Ping statistics for 192.168.42.129:
    Packets: Sent = 3, Received = 0, Lost = 3 (100% loss),
```
5. disable then enable simplewall rules
6. connection now works
```
> ping  192.168.42.129

Pinging 192.168.42.129 with 32 bytes of data:
Reply from 192.168.42.129: bytes=32 time=3ms TTL=64
Reply from 192.168.42.129: bytes=32 time=1ms TTL=64
Reply from 192.168.42.129: bytes=32 time=1ms TTL=64
Reply from 192.168.42.129: bytes=32 time=3ms TTL=64

Ping statistics for 192.168.42.129:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 1ms, Maximum = 3ms, Average = 2ms
```

It only happens on first boot. There is no problem when the tethering is disabled and then enabled again or when booting after the OS is put into sleep mode.

**Comment by henrypp** [comment]
Allowing ICMP rule is fix this problem.

**Comment by char101** [comment]
ICMPv4 is already enabled in user rules.

**Comment by char101** [comment]
Please note that the problem is not that the new rndis interface cannot be pinged but no connection can be made to it at all.

**Comment by henrypp** [comment]
>Socket connection results in access denied error.

Take a look at the log.
