### ISSUE TITLE
Log connections for allowed app

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#79]
Would be great to allow users to write a log of the connections of a single process/app that is allowed to access the internet, for later analysis.

So, adding an item `log app connections to file` to the context menu, and writing a log file in the user folder (next to simplewall.log), for example.

From this log, the user could analyze the connections made and then create custom blocking rules if necessary.

**Comment by henrypp** [comment]
It's impossible.

**Comment by henrypp** [comment]
It's works (for Win8 and above only, of course).
![sshot-001](https://user-images.githubusercontent.com/3902025/57518129-32daac80-733a-11e9-9c6e-d8db42d3ab05.png)
