### ISSUE TITLE
How to block only specified apps?

### ISSUE THREAD

**Issue by AndShy** [henrypp/simplewall#790]
Hello. There is a way to allow all apps by default and only block specified apps by specified rules ?
I need it only because I'm looking for a better way (not trough hosts file) to block AD domains for specific apps (such as acestream).

**Comment by alext6565** [comment]
Just uncheck and create new rules for apps who you want to block. 
![Uploading 1.png…]()

**Comment by AndShy** [comment]
simplewall still wants me to specify rule for each app
![20201002_17-24-31](https://user-images.githubusercontent.com/15649615/94934282-d39bb000-04cb-11eb-8c3f-451f1521f117.jpg)
![20201002_17-25-41](https://user-images.githubusercontent.com/15649615/94934453-0c3b8980-04cc-11eb-8fc3-8154d4b2c84c.jpg)

**Comment by alext6565** [comment]
are you sure that rules are still deactivated after you enable filter again?

**Comment by AndShy** [comment]
yes 
![20201002_18-47-20](https://user-images.githubusercontent.com/15649615/94943127-87ef0380-04d7-11eb-9471-3c4ff933e3a1.jpg)

**Comment by alext6565** [comment]
why you unchecked Allow loopback and Allo ipv6... only uncheck the block out and inbound rules.

**Comment by AndShy** [comment]
ok. in fact not for all apps need to set permissions. but for many of them
all another works without requesting
![image](https://user-images.githubusercontent.com/15649615/94945693-5a0bbe00-04db-11eb-9071-0159b3ae26fe.png)

**Comment by AndShy** [comment]
> why you unchecked Allow loopback and Allo ipv6... only uncheck the block out and inbound rules.

thank you. with that options only utorrent requesting permissions.
