### ISSUE TITLE
Logging broken in 3.2.4

### ISSUE THREAD

**Issue by robertschulze** [henrypp/simplewall#791]
Since I upgraded from 3.2.2 to 3.2.4 I see no more log entries for blocked connections and the pop-up asking whether to Allow/Deny is not coming up anymore. Also the Applying Rules phase at program start takes much longer (2-3x). Reverting to 3.2.2 solves the issue. Going forward to 3.2.3: continues to work. Going forward to 3.2.4 again leads to the observed issue. Then going back to 3.2.3 does not solve the issue - I have to go back to 3.2.2 to solve it. Then going forward to 3.2.3 is ok again. I am puzzled.

Can you please have a look?
Let me know if I can provide any further necessary input.

SYSTEM: Windows 7

**Comment by robertschulze** [comment]
Is there anything I can provide in order to address this issue? Thanks!

**Comment by rudolphos** [comment]
I am having the same problem. I tried another app called FreeFirewall and it's the same (no notifications), so it's a Windows problem. I'm on Win10.

**Comment by henrypp** [comment]
here discuss #841
