### ISSUE TITLE
Simplewall sometimes would not ask for confirmation for accessing internet

### ISSUE THREAD

**Issue by breadnone** [henrypp/simplewall#792]
Simplewall sometimes would not ask for confirmation for accessing internet. It would blocked the connection entirely(this should be expected), but it would ask for confirmation to be allowed for the second time.

This happens consistently with "visual studio installer" whenever I tried to update. It would not be a problem if the update fails instantly but the problem is, it would stuck for hours before it shows connection error (probably on vs installer's part but who knows)

Thought I'd drop it here in case it's really a bug. Thanks!

**Comment by henrypp** [comment]
#774
