### ISSUE TITLE
Blank Popups

### ISSUE THREAD

**Issue by Connoe** [henrypp/simplewall#794]
![blankpopup](https://user-images.githubusercontent.com/47482591/95419040-c08f4280-0906-11eb-964a-0aa5283d72e3.PNG)
Every time I get a pop up from simplewall it is just blank. It has been like this for a while now and I have no idea how to fix it

**Comment by deadcombo** [comment]
I have the exact same issue, rolling back to 3.2.3 fixed it.

**Comment by connyw** [comment]
I have the same issue after updating the graphics driver

**Comment by deadcombo** [comment]
I reinstalled simplewall from chocolatey 3 days ago and the issue went away again. So far so good.

Maybe it's dependencies/file permissions? I didn't have a look at the install script...
