### ISSUE TITLE
Allow apps in certain folders

### ISSUE THREAD

**Issue by rhacker** [henrypp/simplewall#798]
I have a use case when I do go development, whenever I run `go run .`, new binary file is generated and make request to network. Is there anyway that I can allow all of these generated binary files at once ( file pattern or something like that .. )? 

Thanks for create such simple and effective firewall for windows.

**Comment by Tom4tot** [comment]
https://github.com/henrypp/simplewall/issues/379
https://github.com/henrypp/simplewall/issues/307
https://github.com/henrypp/simplewall/issues/456
https://github.com/henrypp/simplewall/issues/136#issuecomment-389056619

**Comment by rhacker** [comment]
@Tom4tot Thanks for pointing out.
