### ISSUE TITLE
About app rules. Negate indicator for subnet destination.

### ISSUE THREAD

**Issue by vainiya** [henrypp/simplewall#802]
Hello. About app rules.

Can negate IP range? Block all destination (all IPs except this subnet 192.168.10.0/24) ??

Like iptables syntax-> Block all traffic to destination !192.168.10.0/24

with this symbol, for example -> !

Sorry my bad english.

Regards.

**Comment by crazyyzarc** [comment]
I also asked him to add such a function
https://github.com/henrypp/simplewall/issues/748#event-3689582511

**Comment by crazyyzarc** [comment]
> 
> 
> Hello. About app rules.
> 
> Can negate IP range? Block all destination (all IPs except this subnet 192.168.10.0/24) ??
> 
> Like iptables syntax-> Block all traffic to destination !192.168.10.0/24
> 
> with this symbol, for example -> !
> 
> Sorry my bad english.
> 
> Regards.

I also asked him to add such a function
https://github.com/henrypp/simplewall/issues/748
