### ISSUE TITLE
How to accept all but some apps ?

### ISSUE THREAD

**Issue by JoeBarouneD** [henrypp/simplewall#803]
Hello, i would just want to block some apps and let the rest opened, and accept the upcoming connections automatically.
My goal is to let filters activated alltime without opening SW at all but for adding some blocked apps.
I don't manage to do this.
If i disable the Block in/out connections in Rules, it applies to blocked apps too, i just want to block these apps and let the rest opened.

Thanks.

**Comment by TontyTon** [comment]
Turn off 'Block Outbound connections for all' and 'Block Inbound connections for all' in Settings>Rules. And then create a User Rule to block everything and add the apps you need to block to it.
I don't know when it was changed, but earlier it was quite easy to do. There was option to choose a mode from 'Block Selected' and 'Allow Selected'. I think henrypp while updating didn't consider this or intentionally removed the option.

@henrypp can you see to this, this is critcal.

**Comment by francwalter** [comment]
And what do I do, if an app is not in the list of blockable apps? Does this mean, it has no network connection at all?
I wonder if an app is not listed if the app does only on start some network connection but then not anymore.
Does it help if I add this app manually?
I have an app (ClipMate7) which only uses local network but I don't want this. Can I prevent this app from any network connection?

**Comment by JoeBarouneD** [comment]
@TontyTon Thanks, that worked, you're right, there should be an option to allow/deny

@francwalter That was my case, add it in the Apps tab, and retry adding it in User Rules

**Comment by TontyTon** [comment]
@francwalter If 'Block Outbound connections for all' and 'Block Inbound connections for all' are OFF then only the apps blocked by user rule are blocked, other apps listed or unlisted have internet connetion. You have to add the app manually and then add it to the created rule.

Oh, I miss the old SW, it had much better UI and usability.

**Comment by JoeBarouneD** [comment]
> 
> 
> @francwalter If 'Block Outbound connections for all' and 'Block Inbound connections for all' are OFF then only the apps blocked by user rule are blocked, other apps listed or unlisted have internet connetion. You have to add the app manually and then add it to the created rule.
> 
> Oh, I miss the old SW, it had much better UI and usability.

That's what i answered before, and yes the old system was more "block what wou want, let the rest working", that was more user friendly.

**Comment by henrypp** [comment]
https://github.com/henrypp/simplewall#q-where-is-blacklist-mode

**Comment by TontyTon** [comment]
@henrypp But with this we won't get notifications right? Or in blacklist mode also notifications were not shown?

**Comment by henrypp** [comment]
@TontyTon no, you get notification.
