### ISSUE TITLE
6 months old app after full format

### ISSUE THREAD

**Issue by Exekkuter** [henrypp/simplewall#805]
Hey,

so i installed fresh win10 and my simplewall found this app:

![image](https://user-images.githubusercontent.com/73531337/97295432-8eab3500-184f-11eb-8826-2936dde332ac.png)

Is it possible that on erased hard drive I have a file that is 6 months old? Is that a formating bug? or virus of some sort? I did full scan with avast premium but it found nothing.

It says it's Pico App ( not sure what does it mean exactly, Google doesnt answer that question ;P ). 

I tried to open file directory to delete it but nothing happens.

Is there any way I can get rid of that?

**Comment by TontyTon** [comment]
What is the location of app?
Did you wipe all drives on your device?
Pico apps are 'subsystem for unix-based applications' https://github.com/henrypp/simplewall/issues/282

**Comment by Exekkuter** [comment]
> What is the location of app?
> Did you wipe all drives on your device?
> Pico apps are 'subsystem for unix-based applications' #282

When i try to open location nothing happens.
Yes, I made full wipe and made entire new partitions.

When i open services window there are more services running with addition date pre-format:
![image](https://user-images.githubusercontent.com/73531337/97512584-29a82a00-198a-11eb-8134-11bdf02b7253.png)


When i open them the location is usually program files/system32/filerepository
How is it possible?

**Comment by TontyTon** [comment]
Ohhh, then it is not an issue, windows just didn't set the date it was written to your system, and instead set it to when it was updated/created in iso.
They are Windows Files, here WMPNetworkSvc is Windows Media Player Network Sharing Service.
