### ISSUE TITLE
Just a question: Is this still secure on Windows 7?

### ISSUE THREAD

**Issue by Hoppimike** [henrypp/simplewall#806]
I can't work this one out, heh :)

I still use 7 and whilst I don't really want to get into the ins and outs of that here, I am using simplewall and was wondering if it's secure, seeing as it's using WFP and that isn't receiving updates. Does that matter?

Thanks :)

**Comment by bellgamin** [comment]
I use both Win7 and Simplewall. Actually, Simplewall works best with WFP disabled. That small aspect of WFP used by Simplewall doesn't require updates. Simplewall works just fine on Win7.

**Comment by Hoppimike** [comment]
> I use both Win7 and Simplewall. Actually, Simplewall works best with WFP disabled. That small aspect of WFP used by Simplewall doesn't require updates. Simplewall works just fine on Win7.

Oh interesting. Why does it work better with WFP disabled? The Windows firewall itself is disabled on my PC. Does that disable WFP too? My knowledge on this isn't great :)

**Comment by Kein** [comment]
Because simplewall introduces its own sublayer. And besides just that there are CRAPLOAD of default system layers already. It is better to reason about your rules if you have them in one place, rather then using two walls and trying to figure out why thing X went into the interwebs when it is clearly blocked

**Comment by henrypp** [comment]
> Just a question: Is this still secure on Windows 7?

Just a answer.

> On January 14, 2020, Windows 7 support ended with Microsoft no longer providing security updates or fixes after that date, except for subscribers of the Windows 7 Extended Security Updates.

Just as example take a look at [this issue](https://github.com/henrypp/simplewall/issues/774) - some people do not install even SP1 on his Win7 installations, what kind of security can we talk about?
