### ISSUE TITLE
Need ability to Allow or Block in response to an SW alert when mouse is FROZEN

### ISSUE THREAD

**Issue by bellgamin** [henrypp/simplewall#807]
My mouse froze on me today. I needed a "certain rescue app" to connect out in order to get a remote fix to the mouse problem. However, I had never used that rescue app before so SW popped up an Alert and blocked that rescue app from connecting out. Since my mouse was frozen, I could not click on the "Allow" button on SW's Alert pop-up.

REQUESTED FIX: Please change SW so that hitting Alt-A on an Alert pop-up will click "Allow" and hitting Alt-B will click "Block". (Doing so will provide a fail-safe for freeze up of other input devices.)

P.S. I found another way to fix my frozen mouse. Also, I have added that "certain rescue app" to SW's Allow list.

**Comment by henrypp** [comment]
You can press "Tab" to navigate  notification alert window and press "enter" or "space" to commit requuired action.
