### ISSUE TITLE
Popups Emtpy after Screensaver

### ISSUE THREAD

**Issue by Bingohecht** [henrypp/simplewall#810]
If my monitor goes into sleep mode or the resolution changes the following popups of simplewall are just blanc space.
Can be fixed by restarting simplewall.

![Screenshot 2020-11-12 224752](https://user-images.githubusercontent.com/58223833/99000318-5be48a80-2539-11eb-91bd-7a78dbb41016.jpg)

**Comment by henrypp** [comment]
dupl #794
