### ISSUE TITLE
Non-NTFS partitions

### ISSUE THREAD

**Issue by Chaython** [henrypp/simplewall#817]
I use BTRFS for some of my drives.
BTRFS is a FOSS fileystem, and there's a FOSS driver on GItHub for Windows https://github.com/maharmstone/btrfs/
Simplewall is not detecting some applications. It does not detect icons and it cannot open the containing folder.
https://github.com/maharmstone/btrfs/issues/324
Hope you can fix it.

**Comment by Chaython** [comment]
The issue still exists in the newest version.
![image](https://user-images.githubusercontent.com/6486343/114922833-63aaa280-9de9-11eb-8608-4b51175beafa.png)
This same thing happens for windows store games. Where they show up as hard disk volume, have no icon and can't open containing folder. 
![image](https://user-images.githubusercontent.com/6486343/114923088-a2405d00-9de9-11eb-9b91-1d909c65a005.png)

**Comment by henrypp** [comment]
@Chaython the files in your list is old, just cleanup it, simplewall resolve only new apps in list.

**Comment by henrypp** [comment]
Anyway, in 3.3.1 added workaround for this.
