### ISSUE TITLE
Packet Log sorting, DoT and DoH resolution, QUIC detection

### ISSUE THREAD

**Issue by EntropySmoke** [henrypp/simplewall#819]
First of all - HUGE THANKS to the developer! I can't think of a better way to organize Windows Filter Platform rules than with SimpleWall.
 
SimpleWall is awesome, but it could use more features, such as:
- Packet Log sorting
- DNS-over-HTTPS and DNS-over-TLS address resolution
- Provision of Remote Hostname 
- ICMP/Ping, TraceRT, and WHO.IS integration
- Detection of newer protocols such as QUIC (currently detected as <empty> UDP over port 443)

Process Hacker (3.X nightly builds) is a Task Manager replacement and does not provide any firewall capabilities, but Process Hacker Firewall section (log-only) should serve as an example of what SimpleWall Packet Log should be like.

**Comment by bonbonboi** [comment]
> * Detection of newer protocols such as QUIC (currently detected as  UDP over port 443)

Simplewall doesn't list UDP over port 443 in Connections Tab.
