### ISSUE TITLE
Allow IP range for specific ports

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#82]
While the Windows Firewall custom rules do allow to set specific ports for IP ranges, it seems that there's no way to do this with simplewall.

Proposed syntax: `192.168.1.0/24:1234` and `192.168.1.0-192.168.1.255:1234`
or even `192.168.1.0/24:1234-1237` and `192.168.1.0-192.168.1.255:445-1237`

Unless I'm missing how to do this already...

**Comment by GHosTiKuS** [comment]
Check out https://github.com/henrypp/simplewall/wiki/Rules-editor, i think there described what you asking about.

**Comment by ltGuillaume** [comment]
I've seen that, but it doesn't cover what I described!

**Comment by GHosTiKuS** [comment]
oh i see, and for me syntax 192.168.1.0-192.168.1.255:1234 is perceived by simplewall normally but i cant test is it works out

**Comment by henrypp** [comment]
> 192.168.1.0/24:1234
> 192.168.1.0/24:1234-1237
> 192.168.1.0-192.168.1.255:445-1237

~OH SHEEEIT... NOOO.. NOOOO. Omagad.

> 192.168.1.0-192.168.1.255:1234

Ok, it's properly done, in near 2.0.20.

**Comment by ltGuillaume** [comment]
Ok, so single ports only?

**Comment by henrypp** [comment]
Yes
