### ISSUE TITLE
ERROR in CRC check for v.20.019 (Win10 x64)

### ISSUE THREAD

**Issue by Tubix** [henrypp/simplewall#83]
Hello Henry,
When i try to unzip the simplewall-2.0.19-bin.zip I have a "File fails CRC check" error on "..\simplewall-2.0.19-bin\64\simplewall.exe". Then, after extracting, there is no "simplewall.exe" in subdirectory \64 (but wel in subdirectory \32).
The computer runs under Win10 x64.
Best regards

**Comment by henrypp** [comment]
"`simplewall-2.0.19-bin`" are extracted normally, even with Windows Explorer.
