### ISSUE TITLE
Loading all icons of each application at startup freezes the simple wall interface

### ISSUE THREAD

**Issue by MASTREX** [henrypp/simplewall#830]

**Comment by MASTREX** [comment]
I think I found the reason.
Windows defender (or may be with other antivirus too).

When SimpleWall starts it reads all executable in its database for data, signature etc. Due to this defender is triggered to scan the process and those file which slows the process.
And when I excluded 'simplewall.exe' in defender simplewall started much faster.

Bonus: It become very responsive also.

**Comment by henrypp** [comment]
fixed

**Comment by MASTREX** [comment]
When you are free then do tell me about the real problem causing this and how you fixed it, @henrypp

**Comment by henrypp** [comment]
Moved all file\network resolution operations into worker threads.

**Comment by MASTREX** [comment]
Ok thanks
