### ISSUE TITLE
Feature request: Creating rule by executable name

### ISSUE THREAD

**Issue by tormit** [henrypp/simplewall#832]
Currently the problem is that Visual Studio Updater creates it's executable in random temp directory every time and it constantly bothers me by asking network access.
Ex. `C:\Users\***\AppData\Local\Temp\kzpxwuj5.ifz\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\BackgroundDownload.exe`

It would be good if I could add rule by executable name.

**Comment by henrypp** [comment]
You can workaround these by allow VSIX update servers in rules.

[There is the answer](https://github.com/henrypp/simplewall/issues/136#issuecomment-389056619) why it cannot be realised.
