### ISSUE TITLE
system rules not working properly?

### ISSUE THREAD

**Issue by jdw1023** [henrypp/simplewall#833]
Hi, I am using simplewall 3.2.4 on windows 10 (build 19042). I recently noticed that certain port are allowed even though there's no rule for it. I think this might be caused by the system rules. For example, the NetBIOS [outbound] is suppose to allow port 137-139 for process svchost.exe and ntoskrnl.exe but it looks like it is allowing all apps?
![image](https://user-images.githubusercontent.com/43763092/103409720-0d656c80-4b36-11eb-8667-46489bd158a9.png)

![image](https://user-images.githubusercontent.com/43763092/103409698-fa529c80-4b35-11eb-9c53-a038c2ced695.png)

**Comment by Chaython** [comment]
Do you have loopbacks enabled?
Are you sure that application you're using doesn't use SVChost?

**Comment by jdw1023** [comment]
> 
> 
> Do you have loopbacks enabled?
loopbacks are disabled. 
> Are you sure that application you're using doesn't use SVChost?
not sure if Internet Explorer uses SVChost. but it's able to connect even when the svchost.exe rule is disabled.

**Comment by Chaython** [comment]
You can only do it via internet explorer?
I tried with MSEdge to use allowed port with edge blocked and it didn't work.
Is the page being cached? Maybe IE has a way around... This uses Windows Filtering after all, so MSFT may have backdoor :x

**Comment by jdw1023** [comment]
> 
> 
> You can only do it via internet explorer?

I can do also do it via `ncat` (Netcat). 

The ERR_UNSAFE_PORT is cause by chromium's built-in security mechanism. The port is not accessible even without using simplewall.

**Comment by Chaython** [comment]
What is netbios used for?
If you look at the rule, it gives system and svchost access to the port.
Any application that uses svchost [basically all of them] could then use that port...

**Comment by Chaython** [comment]
So instead of having open ports, you should allow the individual service/app, to access everything.

**Comment by jdw1023** [comment]
I don't think it uses svchost to access the port. If I disable the system rule and create a user rule with the exact same parameters then the application can not access the port. If the application uses svchost, creating a user rule with svchost/system and port 137 should cause app to have access to the port. However it's blocked by simplewall when it is a user rule instead of system rule. This led me to think if there's some issue with system rule.

**Comment by Chaython** [comment]
Ya, your right only the system rule does it.

**Comment by henrypp** [comment]
Are you really <s>open 137 port</s> allow in/out netbios rule and wants 137 port to be closed?
