### ISSUE TITLE
Blank notification when switching to different resolutions

### ISSUE THREAD

**Issue by luciochagas** [henrypp/simplewall#835]
Hello!

First and foremost, I want to give my kudos to this amazing application, which has become a staple of my setup.

I noticed that when switching to different resolutions (4K to 720p auto-transitioned from Steam games, didn't check for other graphical changes, but suspect might also affect) and back, the notifications become blank from that point on. By blank I mean that the notification appears, but no discernible writing in it. Checking the filter list still allows to check what service wants to have inbound or outbound, but the notifications themselves become unusable until a fresh restart.

**Comment by henrypp** [comment]
dupl #794
