### ISSUE TITLE
how to add bulk IP to block

### ISSUE THREAD

**Issue by Kali273** [henrypp/simplewall#838]
hi, its only question maybe. How i can add multiple IPs and domains to block into this firewall? In the blocklist is no option for add IPs.. On reddit is some recommended lists but i dont know how to instal them..

**Comment by akeilox** [comment]
I too am interested with this. I wish to block certain Countries with country IP lists or batch IP lists.

How do we go about doing this?

**Comment by Chaython** [comment]
I believe you can add them each with a semi colon ; you can copy paste into your profile.xml if you don't want to use the GUI

Example `<item name="chrome.exe" rule="104.27.148.212;54.215.176.103;74.125.20.188:5228;8.252.193.252:443;8.240.38.124:443;172.217.3.170:443;172.217.3.163:443;8.252.193.252:443;8.252.193.252:443;8.252.193.252:443;8.252.193.252:443;8.252.193.252;8.240.38.124;13.224.2.117" dir="2"  is_block="1" is_enabled="1"/>
`
