### ISSUE TITLE
"Ignore" button in notification

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#84]
In the notification dialog, there's the option to permanently allow the app, or permanently block it (or create a more specific rule with it). There's no option, however, to clear the notification, i.e. ignore the notification (without creating a rule) and it not turning up again when hovering over the tray icon. Could you add a button "Ignore"?

**Comment by henrypp** [comment]
"Block" button does "Ignore" functional, but okay i will do cosmetic fixes.

**Comment by ltGuillaume** [comment]
As far as I saw, it "Block" also introduced a new rule for that app. That's not the same as ignoring.

**Comment by henrypp** [comment]
If notification displayed then application ALREADY blocked thats why another special rule does not needed.

**Comment by ltGuillaume** [comment]
Not when you're in whitelist mode.

**Comment by henrypp** [comment]
So, allow rule in notifications worked as well.

**Comment by ltGuillaume** [comment]
Ok, I'm going to try to explain this once more:
In whitelist mode, an application can have three states:
1. It's among the allowed applications
2. It's among the explicitly block applications
3. It's not in either of the above lists, but will be blocked due to the whitelist mode

Now, if a notification pops up for an application that's currently described by (3), "Ignore" (previously "Block"), doe not ignore the application at all. What it actually does is explicitly block the application (and thus puts in the list).

**Comment by ltGuillaume** [comment]
Do you get what I mean?

**Comment by henrypp** [comment]
No! :)

**Comment by ltGuillaume** [comment]
"Ignore" means "close notification and don't do anything". 

"Block" means "close notification and add app to blocked list". 

Currently, the "Ignore" button does the "Block" action, while there is no way to "ignore". You could also use the X in the upper right corner to "ignore" (currently that just closes the notification, but it doesn't drop that notification from the "notifications stack" (the "1/3" stuff).
