### ISSUE TITLE
Double-click, 'open containing folder' or Enter doesn't open Explorer

### ISSUE THREAD

**Issue by halejok** [henrypp/simplewall#840]
Hi,
double-click, 'Open containing folder' or Enter doesn't open Explorer.
(simplewall 3.2.4, Windows 8.1 64-bit).
Regards, hjok

**Comment by henrypp** [comment]
What file do you open? I am not telepath.

**Comment by halejok** [comment]
I meant an item in the Apps list:
![app-list](https://user-images.githubusercontent.com/50183502/104824794-6d0d8880-5855-11eb-8d2d-3cdc488778f8.png)

**Comment by henrypp** [comment]
What _file_ do you open? Still not a telepath.
