### ISSUE TITLE
Simplywall blocks Microsoft.AAD.BrokerPlugin.exe - despite its allowed

### ISSUE THREAD

**Issue by razzor1984** [henrypp/simplewall#842]
Hello,

OS information:
Windows 10 - 20H2
Ryzen:3600
1TB SSD

i have problems with simlywall blocking Microsoft.AAD.BrokerPlugin.exe despite its allowed:
![2021-01-21 17_38_38-Window](https://user-images.githubusercontent.com/3404263/105382714-48743080-5c08-11eb-8f8b-5983bd59cb0f.png)

Microsoft.AAD.BrokerPlugin.exe is a sub program wich is need that MS Teams can actually work.
But Simplywall still blocks it:
[logs.txt](https://github.com/henrypp/simplewall/files/5850801/logs.txt)
The only solution is, to allow the ips under custom rules:(it has now effekt to ad the ips to the programm - Microsoft.AAD.BrokerPlugin.exe )
![2021-01-21 17_47_56-Window](https://user-images.githubusercontent.com/3404263/105382957-8a9d7200-5c08-11eb-9e6d-b355dac8534d.png)
If i generally allow the shown ips,  this breaks the firewall.Suddenly every programm can access the internet, but is shown blocked in logs.

Filterlists: MS/ alle are allowed - telemetry blocked by Pihole

Do you need more information?

best regards Razzor

**Comment by henrypp** [comment]
`Microsoft.AAD.BrokerPlugin.exe` is a UWP app.

**Comment by Chaython** [comment]
Did the above work?
Otherwise you may need to allow SVChost

**Comment by razzor1984** [comment]
Hello :) 
sadly not I had not enough time to debug it, Teams are in a "home office" oriented world a must have now....
I changed to OS to Linux (Debian) and there I filter request via iptables/build on Firewall + stuff I cannot block via a PI hole. Windows is sometimes a pain in the....

**Comment by henrypp** [comment]
Ага, держи в курсе.
