### ISSUE TITLE
fiddler disabling/bypassing simplewall

### ISSUE THREAD

**Issue by gl4d** [henrypp/simplewall#847]
^title says it all; Started using fiddler (wireshark like) and it seems that when i'm monitoring traffic, simple wall is simply not applying/using filters anymore, is there any fix to this?

regards,

**Comment by jpieczonka** [comment]
I cannot reproduce this.  SimpleWall continues to block traffic from an app (0patchconsole.exe) while fiddler is live.  Which app are you trying to block?

**Comment by Vishrut-Arora** [comment]
It will depend if you are trying to use web apps or native apps.

**Comment by gl4d** [comment]
seems that simplewall just allows traffic without asking for permission when fiddler is on but only for new apps, no big deal since previous filters aren't affected.
/closed
