### ISSUE TITLE
Exclude folder from Simplewall?

### ISSUE THREAD

**Issue by XImpalerX** [henrypp/simplewall#848]
I use an updater program that downloads installer to a TEMP folder, and Simplewall blocks the download every time there is an update. Is there a way to exclude a folder from Simplewalls filters?

**Comment by captainhook** [comment]
@henrypp has covered this in #463
It's a pain so for now I'm just temporarily disabling simplewalll to update/run software that does this.

**Comment by XImpalerX** [comment]
ok thanks!

**Comment by skupjoe** [comment]
I am seeing temp folders used for automatic background updates and such much more commonly these days, and so I've raised this concern in #1441
