### ISSUE TITLE
May I ask you a question. For a process, I want to use fwpm_ LAYER_ ALE_ CONNECT_ The direct layer forwards TCP / UDP to other services through sokect5. Can I demonstrate it

### ISSUE THREAD

**Issue by 86speed** [henrypp/simplewall#849]
May I ask you a question. For a process, I want to use fwpm_ LAYER_ ALE_ CONNECT_ The direct layer forwards TCP / UDP to other services through sokect5. Can I demonstrate it

**Comment by TechnikEmpire** [comment]
I develop wfp drivers and AFAIK you can't do this in user mode. In those connect layers you need to grab the connection data and rewrite it inside a callout and callout is kernel mode only.
