### ISSUE TITLE
Late startup seems to make simplewall ineffective 

### ISSUE THREAD

**Issue by aminya** [henrypp/simplewall#850]
Sometimes simplewall starts quite late when the computer is turned on. This seems to make it ineffective for some time until it starts. Is there a way to start the service sooner?

**Comment by henrypp** [comment]
Any proof?

**Comment by aminya** [comment]
Sometimes, it takes some time until the icon appears in my taskbar.

**Comment by henrypp** [comment]
https://github.com/henrypp/simplewall#q-are-internet-connections-blocked-when-simplewall-is-not-running
