### ISSUE TITLE
Sometimes annoying message that Windows Firewall is switched off

### ISSUE THREAD

**Issue by Knutselsmurf1** [henrypp/simplewall#851]
I installed the latest Windows 10 Enterprise, then I installed Simplewall 3.2.4. I blocked almost everything except a few ports and a few applications.

After installation I enabled Simplewall and then Windows Firewall is automatically switched off.

I disabled all notifications in Windows Settings --> System --> Notifications & actions.

However sometimes (like a few minutes after startup) in bottom left corner an annoying Windows popup appears for a few seconds with the message that Windows Firewall is switched off. This message also appear in Windows notification panel. In my system I do not want popups na matter what. How can I suppress this message?

I am user of Simplewall for several years, but this issue did not occur in the past. Not sure about the cause, the latest Windows patches and/or the latest Simplewall or a combination?

**Comment by mizzuri** [comment]
Try the solution [here](https://github.com/henrypp/simplewall/issues/554#issuecomment-621012406).  I'm not sure if it's the same issue as yours.
