### ISSUE TITLE
Wildcard for allowed application names.

### ISSUE THREAD

**Issue by acos21** [henrypp/simplewall#853]
I have several applications running that require a frequent update.

The files that contain the update all have a somewhat different filename (dropbox is one of them).

This results in me having to authenticate new files multiple times a day on different machines.

![2021-02-06 00_09_14-simplewall](https://user-images.githubusercontent.com/47493261/107094409-a0698480-680f-11eb-808e-7ec5c6a2281c.png)

Any way i can allow "dropboxclient*" files to always be Allowed?

**Comment by captainhook** [comment]
@henrypp has covered this in #463
It's a pain so for now I'm just temporarily disabling simplewalll to update/run software that does this.

**Comment by Chaython** [comment]
He's stubborn about implementing new things, but it's good to not make it a bloated mess.

You could fork and implement yourself, or create a batch file or something to write new rules to your profile xml, or to launch an app with loopback etc.

**Comment by skupjoe** [comment]
Is anybody aware of a fork or PR that implements this feature?
