### ISSUE TITLE
Which services does simplewall depends on?

### ISSUE THREAD

**Issue by basti0704** [henrypp/simplewall#855]
Hello!
I'm disabling some windows services for lower ram consumption and everything is working quite well.
Before simplewall worked great, but after my tweaks when I click "Enable Filters" nothing happens.
I also tested it with those services enabled but it did not change anything:
Windows Defender Firewall (mpssvc) and Base Filtering Engine (BFE)

The log always says:
"Critical","2021.02.13 02:09:01","FwpmEngineOpen()","0x000006D9","(null)","3.2.4 Release","10.0 build 19042"

New Installation doesn't change anything either. Do you know which services I also need to enable so simplewall is correctly working?

Thanks for answers!

**Comment by jpieczonka** [comment]
To name a few...
BFE				Base Filtering Engine
mpsdrv			Windows Defender Firewall Authorized Driver
RpcSs			Remote Procedure Call (RPC)
DcomLaunch		DCOM Server Process Launcher
RpcEptMapper	RPC Endpoint Mapper
mpssvc			Windows Defender Firewall
PolicyAgent 	        Internet Protocol security (IPsec)
Tcpip			TCP/IP Protocol Driver

**Comment by pwn0r** [comment]
> To name a few...

> mpsdrv Windows Defender Firewall Authorized Driver
> mpssvc Windows Defender Firewall


are you sure on those two? On older versions of windows you can completely disable native firewall service and everything works. Just on w10 too much is depends on that firewall service so completely disabling it (starting from 1809 or so) is not really advisable.

**Comment by jpieczonka** [comment]
> > To name a few...
> 
> > mpsdrv Windows Defender Firewall Authorized Driver
> > mpssvc Windows Defender Firewall
> 
> are you sure on those two? On older versions of windows you can completely disable native firewall service and everything works. Just on w10 too much is depends on that firewall service so completely disabling it (starting from 1809 or so) is not really advisable.

Yes it’s ok to do so. I’ve had it disabled for years with no adverse effects.
