### ISSUE TITLE
Windows and Firewalls

### ISSUE THREAD

**Issue by Skeletonsnax** [henrypp/simplewall#856]
Few questions bugging me that I can't find the info I'm wanting.

1) If Simplewall is used to configure Windows Filtering Platform, will it still filter if Windows Firewall is disabled?
2) Does it log traffic like Wireshark?
3) Is there other free open source firewalls for Windows 7 and higher or MacOS?

**Comment by jpieczonka** [comment]
1. Yes, SimpleWall filters with Windows Firewall Disabled.  When selecting "Enable Filters" inside of SimpleWall this in turn disables Windows Firewall.
2. No, it does not log traffic like Wireshark.  SimpleWall does not show encapsulation data between layers.  SimpleWall does offer a logging option that gives the ability to see "Allowed" and "Blocked" traffic that passes though WFP.
![image](https://user-images.githubusercontent.com/61094995/108082570-3c7d6200-7040-11eb-8600-bbb164ec39e3.png)

3. I'm not fimiliar with any other available open source options.

**Comment by tnodir** [comment]
> 3. Is there other free open source firewalls for Windows 7 and higher or MacOS?

Check my https://github.com/tnodir/fort

**Comment by jpieczonka** [comment]
> Check my https://github.com/tnodir/fort

Pinned to my tasks list, thanks!
