### ISSUE TITLE
How to connect to Xbox Live without windows firewall?

### ISSUE THREAD

**Issue by miIktoast** [henrypp/simplewall#857]
It seems that I need windows firewall enabled to be able to be able to use xbox live servers,

>[Windows Firewall is required to establish a Teredo IPsec connection. Even if you use additional security software and firewalls, most of these will use Windows Firewall as a base. If for some reason your Windows Firewall has been disabled, you’ll have to enable it in order to use Xbox Live party chat and do multiplayer gaming.](https://support.xbox.com/en-IN/help/hardware-network/connect-network/server-connectivity-xbox-app-displays-blocked) 

 obviously I dont want to use windows firewall along side simplewall. Since I know no other way to check, Ive tried brute force by allowing everything through SW to see if I could establish a connection, nothing worked until I enabled windows firewall. 
 
 Is there a solution to this or do I just have to live with enabling windows firewall any time I want to use xbox live?

**Comment by Chaython** [comment]
You must whitelist the games, you must enable msft stuff in the settings, you may need to allow svchost.

**Comment by cristianxhg** [comment]
> 
> 
> You must whitelist the games, you must enable msft stuff in the settings, you may need to allow svchost.
> ![image](https://user-images.githubusercontent.com/6486343/111059754-3e76ed00-8455-11eb-816d-7768efa06ddc.png)
> Games from MSFT store create a new harddiskvolume on each run. So you need to whitelist the game each time.
> ![image](https://user-images.githubusercontent.com/6486343/111059779-61a19c80-8455-11eb-8d39-d2ee457ebea0.png)
> ![image](https://user-images.githubusercontent.com/6486343/111059796-7f6f0180-8455-11eb-9c83-cc8213e36c34.png)

I'm encountering the same problem, I tried all of the above and it still doesnt work.
![Capture](https://user-images.githubusercontent.com/77160528/111826557-7e285380-88f1-11eb-9915-e768f22b0520.PNG)

**Comment by Chaython** [comment]
Send me your profile XML

**Comment by cristianxhg** [comment]
Currently not using simplewall, so it would be a clean profile, could you send me one where Xbox Live works instead?

**Comment by Chaython** [comment]
> 
> 
> Currently not using simplewall, so it would be a clean profile, could you send me one where Xbox Live works instead?
There's a ton of stuff in my profile.
[Ini xml.zip](https://github.com/henrypp/simplewall/files/6178394/Ini.xml.zip)

The settings app may still state there's no toredo access, but every game plays fine, achievements are still working... Voice chat and messaging works...
But yes, if I disable simplewall, and don't enable windows firewall, then xbox live services gets no access.

**Comment by Chaython** [comment]
> 
> 
> Currently not using simplewall, so it would be a clean profile, could you send me one where Xbox Live works instead?
There's a ton of stuff in my profile.

![image](https://user-images.githubusercontent.com/6486343/111920649-b9439780-8a55-11eb-938f-5d2bf21faca0.png)

The settings app may still state there's no toredo access, but every game plays fine, achievements are still working... Voice chat and messaging works...
But yes, if I disable simplewall, and don't enable windows firewall, then xbox live services gets no access.

**Comment by gl4d** [comment]
> was your issue fixed? Here are my current settings and xbox live works fine, it's not recommended to whitelist svchost.exe, but using only a port rule I don't see any other non-set connections. [Simplewall.zip](https://github.com/henrypp/simplewall/files/6445300/Simplewall.zip)

Hello, could you please re-upload your zip archive? seems like this one is corrupted.
I'm getting the same problem as @miIktoast and i'd like to try your settings.
