### ISSUE TITLE
Why is it preventing me from using IPv6?

### ISSUE THREAD

**Issue by GirkovArpa** [henrypp/simplewall#860]
I don't even know where to start looking.  I've blocked lots of apps and today I setup IPv6 on my router and computer for the first time but it only works when all filters are disabled.  I've never went out of my way to block IPv6 so I don't understand why it would be doing this.

**Comment by jpieczonka** [comment]
Have you tried to create a rule in SimpleWall that allows IPv6 in/outbound?

**Comment by GirkovArpa** [comment]
Like this?

![screenshot](https://i.imgur.com/JqHh8Ij.png)

I still fail the IPv6 test at https://test-ipv6.com/

**Comment by Chaython** [comment]
Settings:Rules:Allow IP6 Redirections
Make sure you even have IPV6 without simplewall enabled.

**Comment by GirkovArpa** [comment]
![screenshot](https://i.imgur.com/S3X3Ib1.png)

I still fail the test at https://ipv6-test.com.  Right-clicking on the tray icon and clicking `Disable filters` makes the site say I pass.

**Comment by Chaython** [comment]
I'm sorry, my ISP still doesn't provide IPV6 very few services use it, IDK any that require it. So why does it matter?
Allow IPV6 redirects... Anyways some other things could be userrules: ICMPv6* ...

**Comment by GirkovArpa** [comment]
Enabling / disabling the rule `ICMPv6*` did not seem to work.  I need to debug a server to confirm it supports IPv6 but can't do that while simplewall is disabled, and that's pretty risky because Windows tries to force all sorts of stuff (like updates) when I do that.

**Comment by Chaython** [comment]
You can disable services, such as Wuauserv
Could also boot safemode with networking, or another limited service mode.
Control Panel = Networking, right click your device's ethernet etc, and you can set your IPV6. IPV6 has been widely supported for over a decade, as it launched 25 years ago. The only issue is, lots of ISPs still don't provide IPV6. But I havent had a device in a decade that didn't have hardware/firmware support.
________________________________

**Comment by henrypp** [comment]
Only dropped packets log answer to you.

Also, enable 6to4 redirection and icmpv6

**Comment by GirkovArpa** [comment]
It started working after I checked the box by Brave:

![screenshot](https://i.imgur.com/Vrx9w8Y.png)
