### ISSUE TITLE
Windows 10 Mail - Unable to Whitelist

### ISSUE THREAD

**Issue by Ithiloneth** [henrypp/simplewall#865]
I am unable to send/receive emails in Windows 10 Mail.

Usually that would be resolved by Simplewall notifying me that a program wants to connect but I do not get such a notice.

Microsoft, in their eternal wisdom, have blocked access to the folder containing the executable file for "Mail" as seen in Task manager when the program is running. This has prevented me from adding the app to whitelist manually.

Packets log can be arranged, not attached due to privacy concerns (I am not sure what to exclude).

**Comment by Ithiloneth** [comment]
I have moved on to another email client, there is no need to keep the ticket open on my behalf.
Will still keep this ticket under my watch though so I can give more information if requested.

**Comment by Chaython** [comment]
It should show up under UWP apps, you need to allow MSFT stuff in the settings page, you need to allow svchost.exe, and some UWP apps also create a new harddiskvolume every time it is ran so needs whitelisted per instance.

**Comment by Ithiloneth** [comment]
Thank you Chaython - I have learned something new!
Following your instructions I was able to let Windows 10 mail through the firewall by allowing Mail and Calendar in UWP apps.

Issue closed!

**Comment by Chaython** [comment]
Ya, some apps in the list, of UWP apps, are miscategorized, and are x86, in which case, you need to enable it in app list. Anything that's actually UWP [Legacy apps, designed to work on windows phone etc] are in the UWP list and filtering works correctly.
Just know that, MSFT is changing the mail app to be a PWA of outlook.com. So soon it won't be UWP, rather it would have a new "app" or, would use MSEdge Chromium's App.
