### ISSUE TITLE
Rule window box ONLY HOLDS 17 RULES. DOESN'T TELL YOU YOUR UNPROTECTED

### ISSUE THREAD

**Issue by firepacket** [henrypp/simplewall#867]
I spent hours adding tons of rules, there is NO FEEDBACK that rules are NOT BEING ADDED
**There is no indication of the 17 rule limit.**

My server was compromised because I thought the rule dialog held all rules I added, but it didn't. Now I have to format and reinstall because I used this crap software.

Shame on you.

And why do we need to click ADD for each new rule? Was there something wrong with leaving it a delimited string?

I am furious at this incompetnce.

**Comment by henrypp** [comment]
> My server was compromised because I thought the rule dialog held all rules I added, but it didn't. 

What compromised? Everything is blocked by default.

> Now I have to format and reinstall because I used this crap software.

Unbelievable, you delude oneself, and that's why you blame this tool.

**Comment by 0x4E69676874466F78** [comment]
@firepacket, pls use $$$proprietary$$$ firewall and go away.
You're stupid.

**Comment by firepacket** [comment]
> > My server was compromised because I thought the rule dialog held all rules I added, but it didn't.
> 
> What compromised? Everything is blocked by default.
> 
> > Now I have to format and reinstall because I used this crap software.
> 
> Unbelievable, you delude oneself, and that's why you blame this tool.

I'm sorry oh high and mighty developer of this mediocre tool,
do you DENY that your rule dialog does NOT ALERT PEOPLE when they are adding rules over 17 that those rules are NOT BEING ADDED?

Do you DENY deluding your users with poor interface design that their blocklists are complete when they are not?

Is there ANY MENTION of a 17 rule limit per custom rule that you changed from being single textbox?  What was the purpose of that change? Simply to make it harder to block more complex designs?  


> @firepacket, pls use $$$proprietary$$$ firewall and go away.
> You're stupid.

If you can handle the issue section maybe you should go somewhere else.

**Comment by 0x4E69676874466F78** [comment]
@firepacket you do not want stop being hysterical and show respect to the author of free and opensource software?

**Comment by gettysburg** [comment]
@firepacket

https://www.youtube.com/watch?v=48rz8udZBmQ

**Comment by gettysburg** [comment]
@firepacket

https://www.youtube.com/watch?v=48rz8udZBmQ

@henrypp

Close this already / ban the user, this is a prime example of the Dunning–Kruger effect.

**Comment by firepacket** [comment]
> @firepacket you do not want stop being hysterical and show respect to the author of free and opensource software?

No.
You do not want to address a legitimate security issue that his software is responsible for?

**Comment by firepacket** [comment]
> https://www.youtube.com/watch?v=48rz8udZBmQ

I am rubber, you are glue. Anything you say bounces off of me and sticks to you.



> Close this already / ban the user, this is a prime example of the Dunning–Kruger effect.

You want to ignore the LEGITIMATE SECURITY ISSUE I raised in the issues tab? How many people will be hurt if the author listens to fools like you and ignores the issue I raised?

### THE RULES TAB ONLY HOLDS 17 RULES, EVEN THOUGH THE GUI ALLOWS YOU TO ADD MORE, THEY ARE SILENTLY ERASED.

FIX IT OR ADDRESS IT AN GET OFF YOUR PEDESTAL.

**Comment by gettysburg** [comment]
> THE RULES TAB ONLY HOLDS 17 RULES, EVEN THOUGH THE GUI ALLOWS YOU TO ADD MORE, THEY ARE SILENTLY ERASED.

I added over 30 individual custom rules whitelisting only specific subnets and ports / port-ranges for each application and they all work fine, most of my applications would stop working if there was a 17 rule limit which is stupid in itself, why 17, why not 18 or 16?

![simplewall_UserRules](https://user-images.githubusercontent.com/2256003/112415152-39e6ea00-8d1b-11eb-8df2-077bba57a12f.PNG)

To top it off, I also enabled every single built-in block-list, which in total are 893 rules.

![simplewall_BlockList](https://user-images.githubusercontent.com/2256003/112415245-6bf84c00-8d1b-11eb-84fd-7e18812025af.PNG)

If you were smart enough to read the code, you would also see that there is no limitation of 17 rules - not in simplewall's code, and not in the usermode and kernelmode counterparts of WFP's code - most of the times not the computer is the problem, but the user sitting in front of it. **In general, code also doesn't lie.**

You should be furious over your own incompetence, the childish replies only further prove my point that you are either a newbie system administrator or a bad troll - either way, you will achieve nothing spamming the bug tracker - unfortunately the bug-tracker only applies to bugs within the code of the application, not user incompetence.

P.S.: Ever thought about maybe building your rules using the provided examples? Bad syntax could be a problem here, but that too would trigger a syntax error and not let you apply the rule anyway.

🤡

**Comment by henrypp** [comment]
fixed
