### ISSUE TITLE
Windows + Share internet connection no connection to new machine

### ISSUE THREAD

**Issue by zgzg2020** [henrypp/simplewall#871]
Hi,
My setup is as follows:
ComputerA has two ethernet plugs 1 and 2.
ComputerA.plug1 is connect to the internet.
ComputerA.plug2 is connect to the computerB.
ComputerA.plug1.Properties.Sharing.InternetConnectionSharing(check)->HomeNetworkingConnection(ComputerA.plug2)

When simplewall filters are disabled:
ComputerB can connect to the internet.

When simplewall filters are enabled:
ComputerB can NOT connect to the internet.

I am new with ports/firewall rules...etc. But, I tried adding every rule I could, yet could not make it work.

Please help!

**Comment by zgzg2020** [comment]
This shows up in the "Packet Log", I try to add it as a rule, yet doesn't work, even without a port.
svchost.exe, 192.168.137.1, 53 (domain), 192.168.137.154, 58805, udp, BlockRecvAcceptConnectionsV4, Inbound, Blocked

**Comment by zgzg2020** [comment]
Anybody has any ideas???

**Comment by Chaython** [comment]
There's probably additional services that require whitelisting.
What if you just whitelist svchost in the apps pane.

**Comment by tokariu** [comment]
this might be related to isse: https://github.com/henrypp/simplewall/issues/425

**Comment by 0Dragonmoon** [comment]
have you enabled "SharedAccess" in the services tab? that allows internet connection to virtual network adapters

**Comment by zgzg2020** [comment]
Yes, it is enabled.

**Comment by henrypp** [comment]
dupl #425
