### ISSUE TITLE
Some comments and some help

### ISSUE THREAD

**Issue by phaolo2** [henrypp/simplewall#873]
Hello, I need some help configuring Simplewall (I don't know where to ask if not here..)
I'm also going to add some comments about the program, hoping for some improvements.

I like the notification dialogs, but I thought that clicking the "Allow" button only granted each programs a permission for the current type of request. Instead, it seems it allows every connection, unless I select "create rule" from the menu!? Shouldn't this be the main feature, instead of the full allow?

Also, the automatic creation by default creates user rules with IP+port in the name, omitting the more useful part which is the program program+IP+port, I think. 
Btw, in my opinion Simplewall shouldn't move System Rules (e.g. HTTP) to User Rules just because I assigned some programs to them.

In the App tab, the "tick" before each App is confusing. IMO it should be in its own column, called "full access" (if I'm not mistaken about its function). It would also be nice to have other columns to quickly check more info. For example the rules utilized or the ports allowed (even in a single string).

About my request for help, it's in the User Rules, because I don't understand the difference between Local\Remote. I thought it meant mypc\otherpc ports respectively, but it doesn't seem to work that way? Outbound seems to use only the Remote section and Inbound just the Local one. 
Except for p2p programs, which I'm not sure how to set. I had to give full allow, because I see connections on many different ports.

P.s: also, what does this mean in the logs?
_"Sets up flow outbound filter for all IPv4 traffic, so we can filter the blocked ip-addresses out."_

P.p.s: shouldn't these be blocked in the default system rules, then?
www.sans.org/reading-room/whitepapers/firewalls/egress-filtering-faq-1059

**Comment by phaolo2** [comment]
Ok, I think I understood a bit the Local\Remote difference, after importing Simplewall's log into Excel and then noticing the headers. At first I didn't get why you only needed remote ports for some protocols.. for example I thought that HTTP communicated 80<->80, but then I saw instead that the local ports seem random like >5000.

**Comment by phaolo2** [comment]
Something is still strange.
For example, in the log I see this repeated connection: 
myip:137 -> 192.168.1.254:137
If I allow local ports 137-139 and remote 192.168.1.254:137, I still get a notification to add the same filter but without the local ports..

**Comment by phaolo2** [comment]
Mm.. I think the rules have some bug if you fill both local and remote ports.

**Comment by Chaython** [comment]
Ya normally local rule is empty
But why do you need such specific rules?
If you leave a port open to an ip, you might as well leave "full access" to an ip, as you can use 1 open port to do whatever you want...

**Comment by phaolo2** [comment]
I'm _trying_ to block anything I'm not aware of.
So if a virus tries some new port, I'll notice it.
If a program commonly uses specific local or remote ports, I don't want it to use anything else.

**Comment by Chaython** [comment]
I haven't seen that message before

Simplewall in default state should be in whitelist mode [everything is blacklisted and you choose what to allow]
Some ports are open though, you can disable them by going into "system rules" and "user rules". and deselecting everything.
However, DNS rule is always necessary for internet access.

To stop "virus" from scanning ports there's an option to prevent port scanning. [I'm not sure how it's implemented, but in other firewalls, what it would do is see an ip is port scanning and then it would block the IP]
This is also on by default...

if a virus is on your system, it can use other things to access the internet, this is usually done via  a loopback, so deselect loopbacks, but this can also break some apps.
