### ISSUE TITLE
x64 version closes itself upon startup on win 10 after windows update

### ISSUE THREAD

**Issue by kanzaki1201** [henrypp/simplewall#875]
I am on a 64 bit machine and was using the installed version. 
After a windows update (20H2), simplewall will crash/close itself right after it starts.
Sometimes you can see simplewall's window, but it will be closed very shortly.

This happens on both installed version and portable x64 version.

However, the portable 32bit version will work (it will prompt you to use 64bit version though).

I wonder if it is the windows update screwing up things?

**Comment by Chaython** [comment]
I have no issue, the latest beta versions are not stable, but no issue with the stable versions.
I run a clean windows install every several  months as windows often breaks with updates.
