### ISSUE TITLE
Svchost service identification?

### ISSUE THREAD

**Issue by Radagast** [henrypp/simplewall#88]
I've just started looking at Simplewall and wanted to know if it would be possible to differentiate between individual Svchost services for rules. For example, I might like to allow CryptSvc to make Internet connections but not DeviceAssociationService.

Thanks

One other question, any chance of adding the PID to the notification dialogue?

**Comment by ltGuillaume** [comment]
+1

**Comment by henrypp** [comment]
WFP isn't provide interface to allow apps by service name, only by it's paths and same for the question two, WFP dropped events callback does not provide any information about process (only paths).

**Comment by pwn0r** [comment]
extensive search for that topic shows that a probable way to implement this is by using Service SID. 

from cmd eg. sc showsid spooler. 

This way you would be filtering by user/service ID, not by application path.

Funny thing is that Windows Firewall itself allows (in custom rules) service filtering, but they are very unclear how it is exactly achieved on a lower level. (iirc Windows firewall uses userland WFP in a similar way as your own application).

**Comment by kekukui** [comment]
> **Windows Firewall itself allows (in custom rules) service filtering, but they are very unclear how it is exactly achieved**

While it does not provide filtering, **Process Hacker** will identify the service name & firewall status

![image](https://user-images.githubusercontent.com/20834957/83319442-771e4080-a20c-11ea-8dd5-2651719123da.png)

https://github.com/processhacker/processhacker
