### ISSUE TITLE
[featurerequest] [QOL] [UI]  UI features & improvements

### ISSUE THREAD

**Issue by pwn0r** [henrypp/simplewall#880]
some ideas: 

1. Statistics either per session or since last restart.
Connections allowed, connections blocked, per application, and total. A new stats column in the APPS tab. Stats should reset either on filters disable or computer restart, obviously. 

2. Show uptime since last filter enable (either by user or during OS boot) in the status bar days/hours/mins would be enough.

3. Enable a switch to force UI to minimize to taskbar as well, not just to tray. Basically same like MS Outlook app. In other words, when minimizing do not remove the icon from the taskbar. 

4. A new category of apps -- apps with timed access. Currently timed access apps are in the category *apps with internet access*. Well, first of all strictly speaking it should be named as *apps with network access* as it can be local network interfaces as well. 
And for timed apps it would be great to have some remaining time in the UI itself.  Perhaps after apps name? Like *10min remaining*

5. I know ctrl+F works but still would be nice to have a permanent search window in the top toolbar.

**Comment by eric15342335-test** [comment]
I would like to say also "Enable packet logging interface (session only)" with a long time (typically may hours) could potentially lag my computer, is it a issue?
