### ISSUE TITLE
 will simplewall scan the hard disk when pc starts ？

### ISSUE THREAD

**Issue by linranc** [henrypp/simplewall#881]
simplewall启动时会扫描硬盘吗？

**Comment by henrypp** [comment]
what for simplewall needs scan hard disk?

**Comment by linranc** [comment]
this 
![Uploading 2021-04-13_210106.jpg…]()

**Comment by linranc** [comment]
this
![2021-04-13_210106](https://user-images.githubusercontent.com/81269036/114911514-ac964180-9e51-11eb-8131-291fd00b6f84.jpg)

**Comment by henrypp** [comment]
did not understand, where is the question
