### ISSUE TITLE
simplewall not recognized PSIsniff

### ISSUE THREAD

**Issue by nico92GitHub** [henrypp/simplewall#882]
Hello

I am new user of your excellent simplewall I discovered little by little.
I am a "warned" user but not expert, under Windows 10 Pro X64.
Well, I launched the PSIsniff program (https://homepage.univie.ac.at/devag8/) and unless I am mistaken, this one is not seen by simplewall. Not in [Applications], nor in [Connections].

Do you have any idea of this situation with this snifeur (PSIsniff) which is perhaps a little special?

Waiting for your return,
best regards,
![ScreenShot_001](https://user-images.githubusercontent.com/22394276/113405575-5a154980-93aa-11eb-863c-2053a6924141.jpg)

Nico

**Comment by nico92GitHub** [comment]
Hello,
Something is wrong?
regards,
Nico wait for you...

**Comment by henrypp** [comment]
What you wait and how network visualizer application PSIsniff is related to simplewall?

**Comment by nico92GitHub** [comment]
Hello,
I was waiting to see Psisniff in the [Connections] tab of SimpleWall. As Psisniff scan the network permanently, I was surprised not to see it referenced in the Simplewall interface.

**Comment by henrypp** [comment]
Psisniff have connect to anything?

**Comment by nico92GitHub** [comment]
Heu...  thought it, but honestly I do not know ...
Remember: "I am a "warned" user but not expert", As for the network, I have everything to learn ;(
Thank you for your questions / answers

**Comment by henrypp** [comment]
Psisniff does not have description, any readme either, so i understand, there is easy to get confused.

Psisniff only draw bitmaps of current connections (visualizer), so he can simply described as version of simplewall connection tab with YOBA (visualizer) features.

**Comment by nico92GitHub** [comment]
OK, Thank you.
This gives me a more concrete idea of PSISniff and simplewall.
