### ISSUE TITLE
Add an easy way for LAN ONLY, blocking just internet traffic

### ISSUE THREAD

**Issue by yuyaryshev** [henrypp/simplewall#883]
Add an easy way for LAN ONLY, blocking just internet traffic

// Extracted the major feature from  #592

**Comment by Chaython** [comment]
By default, simplewall blocks everything except itself and "system rules"
Just keep a profile with everything blacklisted. To be "imported" on demand.

**Comment by henrypp** [comment]
you can create rule

**Comment by khabib227** [comment]
henrypp you can't add this feature, requested several times, you say you can create a rule, but you also can't say how to create it, can't make a better documentation, you just know how to do one thing, click on "closed this as completed", this very easy right? :D  CLOSE the project "as uncompleted", is better!
