### ISSUE TITLE
Context Menu Win 10

### ISSUE THREAD

**Issue by vasilyvaganov** [henrypp/simplewall#887]
Add the ability to block .exe files via the context menu

**Comment by Chaython** [comment]
I assume you mean in a file explorer...
But the beauty of simplewall is it's portable.
Also this makes no sense, as you should have simplewall running in whitelist mode [block everything by default] for the best security. Having a whitelist option in context menu, would make a little more sense, but it's best to just click the yellow triangle, to see notifications when an app wants access. 
The triangle is highlighted in the screenshot. 
![image](https://user-images.githubusercontent.com/6486343/116505621-96887800-a878-11eb-8c8b-c178d74f6eda.png)

**Comment by henrypp** [comment]
#703 dup
