### ISSUE TITLE
kernal mode drivers support?

### ISSUE THREAD

**Issue by 0Dragonmoon** [henrypp/simplewall#889]
In addition to processes and windows services there are also windows kernal drivers, is there a way to apply the firewall to these drivers?
thanks

**Comment by Chaython** [comment]
Any example? To my knowledge all show up as either a service or an app in simplewall.

**Comment by 0Dragonmoon** [comment]
simplewall lists the .dll proccesses but not the .sys drivers. an exmaple could be mssmbios.

**Comment by henrypp** [comment]
mssmbios connects?
