### ISSUE TITLE
Win10- v3.3.1- Crash

### ISSUE THREAD

**Issue by anvikVRN** [henrypp/simplewall#890]
When scrolling the list of programs in the Applications tab, the program crashes

**Comment by privacyguy123** [comment]
Got this same bug - functionality still remains but the GUI needs relaunched.

**Comment by reddyshyam** [comment]
Back to stable version. Too unstable to use it.

**Comment by Chaython** [comment]
Since MS store apps, were "fixed" to use UWP tab rather than app tab, if you have a windows store app in the app list delete it from your profile. There's still some crashing, but in my log, when I was constantly crashing it was from moussing over a Microsoft store app

**Comment by henrypp** [comment]
this fixed in 3.3.2

**Comment by anvikVRN** [comment]
Not fixed . 3.3.2 Crash

**Comment by reddyshyam** [comment]
> Not fixed . 3.3.2 Crash

Works for me.  I did the usual things I do normally and there is no crash so far.

**Comment by Chaython** [comment]
I still have crashing with the newest revision.
Again if you remove any "windowsapps" from the xml, it greatly reduces crashing.
