### ISSUE TITLE
Home Network Sharing and NAS Server issue..

### ISSUE THREAD

**Issue by Scorpio76** [henrypp/simplewall#891]
Hi,

I have recently setup my NAS and Home Network sharing between 2 laptops.
Whenever Simplewall is enabled I am not able to access the NAS or Home Hetwork.
If I enable SMB inbound & outbound then everything is visible but is this safe?

Thanks for your help...

**Comment by 0Dragonmoon** [comment]
might want to check https://github.com/henrypp/simplewall/issues/871 for solution

**Comment by Chaython** [comment]
As you said smb works...
It's safe as a user rule, but system rules, were opening the port to anything, not just what it was supposed to.
