### ISSUE TITLE
The app is still blocked while it is in Apps with internet access.

### ISSUE THREAD

**Issue by xianggithubli** [henrypp/simplewall#894]
After portable simplewall initiating startup ,  a app stated, and the simplewall  allow button was clicked, this app is in Apps with internet access list,  then close the app and restart it ,this app was still blocked by the simplewall,  how to resolve this issue?

**Comment by 0Dragonmoon** [comment]
what is the app and do other apps have same problem.

**Comment by xianggithubli** [comment]
> what is the app and do other apps have same problem.

The app is Pobo.exe(stock software), No problem for other apps.

**Comment by henrypp** [comment]
> After portable simplewall initiating startup , a app stated, and the simplewall allow button was clicked, this app is in Apps with internet access list, then close the app and restart it ,this app was still blocked by the simplewall, how to resolve this issue?

There is still no telepaths.
