### ISSUE TITLE
Annoying Windows Firewall notifications

### ISSUE THREAD

**Issue by ThiagoRangel7** [henrypp/simplewall#895]
I deactivated Windows Firewall using the script "disable_wf.bat" in the [FAQ](https://github.com/henrypp/simplewall/wiki/FAQ). It was only able to successfully run the line `netsh advfirewall set allprofiles state off`; the other lines returned "access denied" error, even though the command prompt was elevated.

Everything is working as expected, but Windows Defender keeps sending some notifications from time to time about the firewall being deactivated. It seems that Windows doesn't recognize Simplewall as a firewall that could replace Windows Firewall.

The options to deactivate (permanently ignore) these notifications are greyed out. Is there any other way to permanently deactivate these notifications?

Thanks

**Comment by 0Dragonmoon** [comment]
you can force delete the mpssvc.dll and mpsdrv.sys from the system32 folder to delete windows defender. might want to make a backup first though

**Comment by ThiagoRangel7** [comment]
> 
> 
> you can force delete the mpssvc.dll and mpsdrv.sys from the system32 folder to delete windows defender. might want to make a backup first though

Would that stop the Windows notifications? That's all I want, preferably not deleting system files

**Comment by eric15342335-test** [comment]
"Turn off all notifications from Windows Security?"

**Comment by ThiagoRangel7** [comment]
> 
> 
> "Turn off all notifications from Windows Security?"

It's greyed out, I can't click it. Do you know any way to bypass it?

**Comment by oklokl** [comment]
It's normal.
ms Windows 10 program policy change.
Force Windows Defender.
Unable to deactivate.
You'll need to register with a signed normal vaccine program.

So I'm using it at the same time.
It's clear.

**Comment by cloudgreen** [comment]
One of the longest threads here is about Windows Firewall notifications, see [Windows Firewall off notification #554](https://github.com/henrypp/simplewall/issues/554).

There were so many suggestions and versions that I haven't kept up, so I'm not sure if there is a final, workable solution.

**Comment by henrypp** [comment]
IT'S TIME TO MEET GROUP POLICY.

**Comment by cloudgreen** [comment]
> 
> 
> IT'S TIME TO MEET GROUP POLICY.

Eloquently put! ;)
