### ISSUE TITLE
Not Find routine.c rapp.c

### ISSUE THREAD

**Issue by w3h** [henrypp/simplewall#899]
l download project https://github.com/henrypp/routine. complie simplewall project,  but it  not exist routine.c rapp.c.  where can l download files, thks

**Comment by avboy1337** [comment]
已经不能完整编译了。作者把其中的一部分代码不公开了。我这儿留着一份代码可以完整编译

**Comment by w3h** [comment]
> 已经不能完整编译了。作者把其中的一部分代码不公开了。我这儿留着一份代码可以完整编

可否共享一份，感谢 ！！！！    邮箱：2969192546@qq.com

**Comment by henrypp** [comment]
https://github.com/henrypp/simplewall/issues/868#issuecomment-797524481

**Comment by henrypp** [comment]
@w3h 
https://github.com/henrypp/routine/releases
