### ISSUE TITLE
Any chance i dont have to give admin access on every boot with windows10?

### ISSUE THREAD

**Issue by Ud4ba** [henrypp/simplewall#901]
Any chance i can skip at every boot i have to give admin access to simplewall .
any way to whitelist it?

**Comment by oklokl** [comment]
schtasks /create /tn simplewall /tr "'%PROGRAMFILES%\simplewall\simplewall.exe' /minimized" /sc ONLOGON /rl HIGHEST
(Administrator permissions cmd)
??
Are you looking for this?
I am registering and using the reservation work.

**Comment by henrypp** [comment]
using skipuac?
