### ISSUE TITLE
FreeFirewallSvc error 7000

### ISSUE THREAD

**Issue by oklokl** [henrypp/simplewall#902]
simplewall-3.2.4-setup.exe

schtasks /create /tn simplewall /tr "'%PROGRAMFILES%\simplewall\simplewall.exe' /minimized" /sc ONLOGON /rl HIGHEST

my windows10 home Insider 64bit start.. Microsoft Windows [Version 10.0.19043.928]
The program runs in the window (normal operation).
However, an error event like below occurs.
Thank you.
:)

![1](https://user-images.githubusercontent.com/1571600/115983227-ef3ae500-a5da-11eb-97f8-7d5192793e49.png)
`로그 이름:         System
원본:            Service Control Manager
날짜:            2021-04-25 오전 3:05:44
이벤트 ID:        7000
작업 범주:         없음
수준:            오류
키워드:           클래식
사용자:           해당 없음
컴퓨터:           DESKTOP-DVVTRA0
설명:
다음 오류로 인해 FreeFirewallSvc 서비스를 시작하지 못했습니다. 
지정된 파일을 찾을 수 없습니다.
이벤트 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Service Control Manager" Guid="{555908d1-a6d7-4695-8e1e-26931d2012f4}" EventSourceName="Service Control Manager" />
    <EventID Qualifiers="49152">7000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8080000000000000</Keywords>
    <TimeCreated SystemTime="2021-04-24T18:05:44.5565798Z" />
    <EventRecordID>1867</EventRecordID>
    <Correlation />
    <Execution ProcessID="908" ThreadID="1620" />
    <Channel>System</Channel>
    <Computer>DESKTOP-DVVTRA0</Computer>
    <Security />
  </System>
  <EventData>
    <Data Name="param1">FreeFirewallSvc</Data>
    <Data Name="param2">%%2</Data>
    <Binary>46007200650065004600690072006500770061006C006C005300760063000000</Binary>
  </EventData>
</Event>`

**Comment by henrypp** [comment]
it does not relevant with simplewall
