### ISSUE TITLE
Filter Deletion Dialog Box

### ISSUE THREAD

**Issue by hl2guide** [henrypp/simplewall#903]
Please consider improving the Filter Deletion dialog box.

e.g.:

![example](https://user-images.githubusercontent.com/17044982/116351644-57860280-a837-11eb-97b5-79a6cd20daa1.png)

Please make it less generic and more informative with process name(s) for 5 or less items and '...' used as a suffix if more are selected.

**Comment by Chaython** [comment]
It's pretty self evident by the items you highlighted... Is it not?
