### ISSUE TITLE
sequence number

### ISSUE THREAD

**Issue by DMBrosig** [henrypp/simplewall#904]
I have build a user defined rule "10G - all block" for all incomming connections on the local interface 10.20.x.x, no application is selected.
I have build a second rule "10G - allow ping" for all incomming pings on the local interface 10.20.x.x, but because there is no sequence number, the ping will also blocked.

Only one of the interfaces should be affected.

What is the solution? How can I sequence the rules?

**Comment by henrypp** [comment]
Remove block all, and use only allow ping. Block all rule is useless, because SW is _**already**_ block all.

**Comment by DMBrosig** [comment]
This setting is turned off because there are 4 other interfaces that should not be restricted.
