### ISSUE TITLE
Excessive CPU Load

### ISSUE THREAD

**Issue by Ithiloneth** [henrypp/simplewall#913]
I sometimes find Simplewall starts using significant, but not outrageous amounts of CPU cycles.
About 10 - 15% or so.

It is not clear to me what is prompting it, what is clear is that once it starts it generally does not stop until I restart the application.

I know that's not a lot to go on, but it is what I have at this moment in time.

**Comment by Chaython** [comment]
Are you using the new beta? Do you have any simplewall log in your folder? Also try disabling packetlog.
I did have this issue also, but it's not present now. With the newest beta.

**Comment by Ithiloneth** [comment]
Disabling packet logging appears to have resolved the problem for me.
Hopefully I can enable it again once the next update rolls around.

Thank you Chaython!
