### ISSUE TITLE
Onedrive doesn't work after installing simplewall

### ISSUE THREAD

**Issue by xTom47** [henrypp/simplewall#919]
OneDrive is unable to sign in or connect after installing simplewall even tho I allowed the connection in simplewall. Please help!

**Comment by Chaython** [comment]
Allow microsoft in the sw settings
Allow onedrive exe
If you're using the UWP version allow onedrive in the uwp tab also
If that doesn't work
Allow OneSyncSvc in services tab
If that doesn't work
Allow wlidsvc in services tab
If that doesn't work
Allow BITS in services tab
lmk how it goes.

**Comment by xTom47** [comment]
I did what you said but It's still stuck on signing in.

**Comment by Chaython** [comment]
You can contact me in discord and screenshare settings, I use the Microsoft 365 version of onedrive without issue 
Chaython#7763

**Comment by Chaython** [comment]
He contacted me in discord, manually reinstalling onedrive was the fix.
