### ISSUE TITLE
In Packet Log show what service, In connections show what is waiting

### ISSUE THREAD

**Issue by Chaython** [henrypp/simplewall#920]
In Packet Log show what service, In connections show what is waiting
Currently logging is nearly useless[?], as it just says waiting connection, but not what is attempting connections, as for svchost it shows svchost but doesn't specify the service.
Hope you're able to enable better descriptions of what's waiting and what service wants connection.

**Comment by henrypp** [comment]
Waiting connections does not contain this information.
