### ISSUE TITLE
Cannot access certain webpages and some apps ( eg. anydesk ) cannot connect to internet

### ISSUE THREAD

**Issue by Adbrei12** [henrypp/simplewall#922]
I installed simplewall about a week ago because I had some trouble with some apps which were bugging me and I wanted to block them. I stumbled upon simplewall by chance and probably should've read a bit about it before since I have no experience with computers other than using them. Blocked everything I was interested in and then allowed everything else that popped up. I thought it was intuitive enough. At some point however ( this happened over a week or so ) I was no longer able to access certain websites, couldn't connect remotely via anydesk to my pc and so on. It seems pretty random to me which apps or websites have internet access and which don't. Initially I disabled simplewall's filters, which did nothing so I just went on and uninstalled it from control panel and during install it anounced me that settings made with simplewall would be disabled. Also didn't work. After a few hours of browsing the internet for a sollution I gave up and cleanly reinstalled my windows, formatting the drive which contains it. To my disappointment that didn't work either. I am now questioning wether the problem really was because of simplewall or if it is anything else. Tried disabling all firewall, flushing and registering dns and pretty much all easily available pieces of advice I could find by googling. Any other ideas what might be the cause?

**Comment by Chaython** [comment]
Why do you use anydesk, over other remote desktop solutions?
Anyways if you did a clean windows reinstall it obviously wasn't simplewall...
Does your modem have a firewall, have you tried resetting your modem? Your ISP may had pushed an update.
Are you in a country where the government manages and restricts internet access?
Manually set a dns such as 1.1.1.1

**Comment by henrypp** [comment]
All information contained in dropped packets log
