### ISSUE TITLE
It's possible to allow powershell?

### ISSUE THREAD

**Issue by kikishrink** [henrypp/simplewall#924]
I'm new in programming, I don't begin from C/C++, I don't know WinAPI and MS Stack... But, I have a question to big brains: it's possible to allow powershell with enabled filters and do not allow svchost? I need functionality such Invoke-WebRequest... it will be very bad if this functionality doesn't work due to svchost. Allowing powershell executable doesn't affect anything. Use docker image for powershell? - No :) Use curl? - Yes... but, I hope there is a solution with a built-in software.

Just in case: maybe taskhost, I don't know, but I would like to allow powershell only.

**Comment by Chaython** [comment]
https://docs.microsoft.com/en-us/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements
You can give svchost outgoing permission to those ports.
I'm not sure what services powershell is dependent on.

**Comment by Chaython** [comment]
For Invoke-WebRequest I can see powershell.exe itself requests network access.

**Comment by kikishrink** [comment]
> For Invoke-WebRequest I can see powershell.exe itself requests network access.
> For some reason using the ping command though, does not prompt ping.exe for network access.
> Many functions of powershell are dependent on windows services. So depending on your workflow it would be advisable to allow svchost access to the ports mentioned earlier, and manually disabling unwanted services from running.

You're right. Indeed, it is closely related to Windows services. If giving svchost access to the http protocol is like giving it full access. For 'iwr' powershell requests access but nothing happens after allowing it... Looks like cmdlet uses different programs/services to check conditions inside and one of them requests access and simplewall catches it, but core 'iwr' functionality doesn't work. So, it's not simplewall problem, it's MSFT problem. I will use both, curl for me and iwr equivalent for people who use my scripts. Simple way is create iwr wrapper in scripts, with both ways.

**Comment by kikishrink** [comment]
The problem does not concern the functionality of the simplewall, it depends on the core components of the operating system.

**Comment by henrypp** [comment]
All information contained in dropped packets log

**Comment by kikishrink** [comment]
> All information contained in dropped packets log

Thanks, I just saw what horror is happening in the system and how many components are trying to connect after Invoke-WebRequest)
