### ISSUE TITLE
3D Paint, snipping tool, Store and many more MS apps crash after simplewall installed, wgat needs to be enabled for basic MS app functionality?

### ISSUE THREAD

**Issue by dareksartre** [henrypp/simplewall#929]
3D Paint, snipping tool, Store and many more MS apps crash after simplewall installed, wgat needs to be enabled for basic MS app functionality?

default: spy and telemetry blocked, MS update servers enabled, MS application servers enabled.

Only 3rd party programs enabled. 

What services, system apps and UWP apps need access to internet for stuff to work?

**Comment by Chaython** [comment]
I've never had crashing, but most apps prompt for login. Everyone complains about UWP apps... 
You basically have to allow svchost, but many things can use svchost maliciously... 
You can set outbound only, so things can't ping you, only your system can ping them, to slightly improve security... Each app that you use that wants network you should also allow...
