### ISSUE TITLE
Exception raised crashes in 3.3.3

### ISSUE THREAD

**Issue by ptkovsky** [henrypp/simplewall#930]
Hey and thank you for updating the software.
With the current version once in a few days I have a crash like this:
![simplewall exception raised](https://user-images.githubusercontent.com/10148835/118354044-d25a5780-b571-11eb-9fe8-f39a16d22902.png)
Packet logging is disabled.
The issue feels similar to the one I experienced earlier here: https://github.com/henrypp/simplewall/issues/775

**Comment by ptkovsky** [comment]
As I already mentioned earlier in the previous issue, here is the moment when simplewall acts as a CPU hog (crash incoming?).
The machine uses 4 threads, so it is 100% of 1 logical core which is equal to 24-25% (The CPU temperature is in red, gets really hot): 
![simplewall cpu + temp](https://user-images.githubusercontent.com/10148835/119173418-eb7e6f00-ba6f-11eb-9be9-1338cba0efba.png)

So there are two issues which can be related:
1. Crashes when there is not much RAM left and a lot of swapping happening and a lot of disk I/O going on (browser, torrent, etc.) (not really sure what exactly triggers it though). No CPU usage;
2. CPU usage issue.

**Comment by Dark-Noir** [comment]
Same issue here, had it directly after update to 3.3.3 and today at the autostart.

**Comment by Dark-Noir** [comment]
Today i got this one after boot:
![grafik](https://user-images.githubusercontent.com/8070059/120333145-b08dfe00-c2ef-11eb-952b-97b7801868b0.png)

**Comment by Dark-Noir** [comment]
Issue still there with 3.3.4 😢

**Comment by henrypp** [comment]
Important!

Send crashdump when exception raised next time. Crashdump was introduced in 3.3.5 and contatined in sw profile directory.

note: @ptkovsky and @Dark-Noir you have different exception codes, i need crashdump from both of you.

**Comment by Dark-Noir** [comment]
> 
> 
> Important!
> 
> Send crashdump when exception raised next time. Crashdump was introduced in 3.3.5 and contatined in sw profile directory.
> 
> note: @ptkovsky and @Dark-Noir you have different exception codes, i need crashdump from both of you.

I will report when i get a crash again ;)

**Comment by henrypp** [comment]
@Dark-Noir i forgot, your exception is fixed in 3.3.5, be happy!

**Comment by henrypp** [comment]
FIXED
