### ISSUE TITLE
All traffic through tor

### ISSUE THREAD

**Issue by opiums9** [henrypp/simplewall#932]
Greetings! I am trying to send all traffic through tor, for this I created a virtual tap adapter from openvpn and directed all traffic through the tun2socks proxy. I would like to create a few simple rules using a simplewall: deny all connections on the main adapter (physical) except tor and allow everything on the virtual one, in addition, I need to deny all UDP except DNS (port 53), because tor cannot UDP. How can I do this, maybe there are ready-made examples?

**Comment by opiums9** [comment]
```
	<rules_custom>
		<item name="Разрешить все для localhost и local" rule_local="127.0.0.0/8;192.168.0.0/16;100.64.0.0/10" dir="2" is_enabled="true" />
		<item name="Разрешить все для службы tor" dir="2" apps="tor|C:\programdata\tor\tor\tor.exe" is_enabled="true" />
		<item name="Запретить все для remote" dir="2" is_block="true" />
	</rules_custom>
```
I added these rules, but it does not work, and all traffic is blocked by the last rule, can you somehow create an exception for the last rule?
Or are there any priorities for the rules?

**Comment by Chaython** [comment]
Like half of tor relays are honey pots so what's the point in using tor now?
