### ISSUE TITLE
Incoming RDP connection rules

### ISSUE THREAD

**Issue by agiz10** [henrypp/simplewall#935]
Hello,
I am trying to create user rule for incoming RDP connection (Win10 20H2) with defined local and remote addresses.
I disabled system rules (RDP [inbound] specifically).

I am trying to connect from 192.168.5.50 to 192.168.5.43 (editing simplewall configuration on this computer, this is the computer i am trying to RDP into)
This works:
RDP IN, tcp, Inbound, Rule (Remote): 192.168.5.50, Rule (Local): 3389, Apps: svchost.exe
It stops working the moment i set local ip:
RDP IN, tcp, Inbound, Rule (Remote): 192.168.5.50, Rule (Local): 192.168.5.43:3389, Apps: svchost.exe

Additionally when i change it, I see in "Packets log":
svchost.exe, 192.168.5.43, 3389 (ms-wbt-server), 192.168.5.50, 62339, tcp, Internal\BlockRecvAccept, Outbound, Blocked, 896
And in log file as:
"‎24/‎05/‎2021 ‏‎11:31","NT AUTHORITY\NETWORK SERVICE","C:\Windows\system32\svchost.exe","192.168.5.43","3389 (ms-wbt-server)","192.168.5.50","62339","tcp","simplewall\Internal\BlockRecvAccept","#163838","Outbound","Blocked"
Why is it logged as "Outbound"? I am just curious why it is logged as such and not as Inbound as this is incoming connection?

Why does incoming RDP stop working when i lock local rule to IP:port? What am i missing?

**Comment by henrypp** [comment]
> I am trying to connect from 192.168.5.50 to 192.168.5.43 (editing simplewall configuration on this computer, this is the computer i am trying to RDP into)

Packets log displays correct local ip when it is blocked.

> Additionally when i change it, I see in "Packets log":

Direction in packets log was fixed now.
