### ISSUE TITLE
Does it even do anything?

### ISSUE THREAD

**Issue by samokosik** [henrypp/simplewall#936]
Hello,
I installed the simplewall and left windows firewall started. Even though I set it up and the service runs in the background, it does not anything. While the competition - Windows Firewall Control from malwarebytes detects firefox trying to connect to the internet, this does not and it just allows it to go through even though I did not allow it...

Is there any setup required? I am asking because your wiki regarding to the installation and setup is empty.

Thank you

**Comment by phaolo2** [comment]
For me it's working.
Are you sure you enabled notifications and blocked Firefox correctly?
Maybe post your rule config for it?

**Comment by samokosik** [comment]
> 
> 
> For me it's working.
> Are you sure you enabled notifications and blocked Firefox correctly?
> Maybe post your rule config for it?
Yes, it was, however by the time, an update looks like it got fixed, so I was probably on an older version... who knows

**Comment by henrypp** [comment]
> I am asking because your wiki regarding to the installation and setup is empty.

Wiki useless, because all information about installation contains on MAIN page.
https://github.com/henrypp/simplewall#installation

>  Yes, it was, however by the time, an update looks like it got fixed, so I was probably on an older version... who knows

Who knows, who knows... even telepaths does not knows.
