### ISSUE TITLE
Windows App & Feature Settings Page shows wrong Version

### ISSUE THREAD

**Issue by Michiocre** [henrypp/simplewall#938]
![image](https://user-images.githubusercontent.com/7807995/120085944-bfe92d80-c0dc-11eb-823a-72b6cd9b8654.png)

I made sure I have the newest version installed.

![image](https://user-images.githubusercontent.com/7807995/120085952-d1323a00-c0dc-11eb-8ccb-26343db5acbf.png)

I noticed this because of the new Windows Package Manager.
WinGet will always try to update the application even tho it is on the latest version.

**Comment by henrypp** [comment]
If you install simplewall through installer, all okay?

Installer automatically update version information in application list.

And as i see, [repo used official installer](https://github.com/microsoft/winget-pkgs/blob/master/manifests/h/Henry%2B%2B/simplewall/3.3.3/Henry%2B%2B.simplewall.installer.yaml), you can try update through WinGet first and let me know about results.

**Comment by Michiocre** [comment]
I tried again and this time everything worked correctly.
I assume there was something wrong with my installation.
