### ISSUE TITLE
simplewall reaching out to 93.184.220.29?

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#94]
I'm getting a popup with simplewall blocking itself, while trying to access the IP 93.184.220.29.
![simplewall](https://user-images.githubusercontent.com/4777345/32922632-6c864c42-cb33-11e7-9fe2-7dae24dc7910.png)

What's that supposed to mean?

**Comment by henrypp** [comment]
It's a bug where Windows going to DNS resolution for hosts addresses. New beta fixed (maybe).

**Comment by henrypp** [comment]
Sorry, it's not DNS resolution, this is certificate OCSP query doing by Windows.

**Comment by ltGuillaume** [comment]
Haven't seen it since v2.1.1b, but if so, I'm guessing I should allow it?

**Comment by henrypp** [comment]
Yes, i fixed this, anyway, so you can wait for next build.

**Comment by ltGuillaume** [comment]
Cool! Thanks :)

**Comment by henrypp** [comment]
Check 2.1.2!

**Comment by henrypp** [comment]
fixed
