### ISSUE TITLE
3.3.4 v installer doesnot have simplewall icon

### ISSUE THREAD

**Issue by reddyshyam** [henrypp/simplewall#944]
3.3.4 v installer doesnot have simplewall icon

Tested 64bit version

![image](https://user-images.githubusercontent.com/12392746/120747377-88d0ad00-c51e-11eb-9a8c-27ed17111412.png)

**Comment by henrypp** [comment]
Ye, i know, is there a problem?

**Comment by reddyshyam** [comment]
Earlier, it should be fire symbol. Should the setup files show the icon?

**Comment by henrypp** [comment]
> Not an issue functionality wise but the setup having the icon makes it better

Setup should have normal, authentic installer icon, like now.

**Comment by reddyshyam** [comment]
> > Not an issue functionality wise but the setup having the icon makes it better
> 
> Setup should have normal, authentic installer icon, like now.

But 3.3.4 is showing a generic setup icon which I think is the default packaging icon and people will not know it is simpleWall or something else unles the installer icon is changed.
