### ISSUE TITLE
Question. disabled apps can connect via lan

### ISSUE THREAD

**Issue by stasonchickk** [henrypp/simplewall#947]
Hello! I'm using Advanced port scanner  which is in disabled apps to scan my local network. Is it normal behavior that disabled app can make outbound connections inside my local network?

**Comment by Chaython** [comment]
It may use a loopback or svchost? what settings do you have?
I don't want to install it and try myself...

**Comment by avboy1337** [comment]
用的其他的进程走的流量。Chrome安装包比如。
Chromesetup,exe可以下载安装，但是走的是update的进程的流量
