### ISSUE TITLE
High CPU usage for packet logger

### ISSUE THREAD

**Issue by pwn0r** [henrypp/simplewall#949]
Related to #941 

Basically on older computers, like here on one skylake i3 dualcore, if you have GUI open on a packet logging tab, CPU usage goes to about 25% for simplewall.  Until you navigate to that tab there is no so much CPU usage. After than you can even minimize the app but still CPU usage persists. 

Superficial check reveals nothing unusual -- thread count, handles, disk reads/writes remain very low. So most likely GUI bug imo. 

so even it is related to #941 but I believe it nothing to do with packet logging per se, it works as normal if you just start an application and not open logger tab.

**Comment by Chaython** [comment]
It seems to use 25% on any cpu including my 10900f, so it's a bug, personally log with process hacker, but be warned games like destiny 2 will ban you if process hacker is open.

**Comment by henrypp** [comment]
fixed
