### ISSUE TITLE
Hostname in filter not working

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#95]
I'm getting a syntax error popup if I want to set a custom rule for a hostname like fi.windscribe.com. Using 2.1.1.

**Comment by henrypp** [comment]
It because `fi.windscribe.com` does not have any dns record.

**Comment by ltGuillaume** [comment]
Shoot, I just found out, yeah. Sorry to have bothered you.

**Comment by henrypp** [comment]
It's ok!
