### ISSUE TITLE
top toolbar glitch on hidpi displays

### ISSUE THREAD

**Issue by pwn0r** [henrypp/simplewall#950]
Been a few versions with this bug so time to finally report it -- really inconvenient if you use scaling on display.

basically if scaling e.g. 150% or 200% is enabled, just try to maximize simplewall window. Then the top toolbar becomes too large (wrong scale) and basically blank. 

The bar is the one which contains "disable filters", "refresh", "settings" etc. just in case :D

**Comment by pwn0r** [comment]
P.S. once the toolbar becomes blank even resizing the window will not bring back.

**Comment by henrypp** [comment]
You have more than one monitor?

**Comment by pwn0r** [comment]
> You have more than one monitor?

this bug seems to be in any case, multimonitor setup (like at home i got one 200% one 100% for 4k and 1080p respectively which makes GUI same size between them, in theory) or you can just change temporarily scaling for a single monitor (i.e. enable 150% for a 1080p which is normally not needed, just for test)

**Comment by henrypp** [comment]
fixed https://github.com/henrypp/routine/commit/9a60175339a76309010589d3d0277638bf915309
