### ISSUE TITLE
How to get simplewall firewall to startup by itself when first booting up Windows 10 Pro on a non admin account? (limited account)

### ISSUE THREAD

**Issue by ng4ever** [henrypp/simplewall#951]
Any help appreciated thanks. 

Yes I know my admin password but I want it to startup every time on boot up without having to put that in after it opens. Thanks.

**Comment by meirroth** [comment]
+1 on this,
Having to open it every time I boot up and click Yes when this pops up: "Do you want to allow the following program…" is not ideal.

**Comment by oklokl** [comment]
schtasks /create /tn simplewall /tr "'%PROGRAMFILES%\simplewall\simplewall.exe' /minimized" /sc ONLOGON /rl HIGHEST

I'm using it well like this.
:)
I also want the policy to be changed.

**Comment by meirroth** [comment]
Thank you @oklokl! 
Your solution worked perfectly for me!
Cheers
