### ISSUE TITLE
Allow (pre-defined) actions for pattern/folder/wildcard

### ISSUE THREAD

**Issue by zoritle** [henrypp/simplewall#957]
https://github.com/henrypp/simplewall/issues/307#issuecomment-458467312

I know WFP only support full path to executable, but this can implemented in a limited way: any time you get notified when an application want to connect to internet, you can first check whether the path of executable matched a predefined pattern,if so just apply corresponding rules (allow/block) ,otherwise show the popup window to the user like before. UI might need some tweaks to distinguish these rules.

Though this way won't take effect for the first request of first time executed application, it should not be a big deal since many application have some kind of retrying mechanism, or user can just retry the command. Just inform to the user when they setup the rules.

Thanks for your great work!

**Comment by Chaython** [comment]
Ya everyone has been demanding folder/wildcard for a long time, and henry says no!
