### ISSUE TITLE
Color Highlighting for Western Countries

### ISSUE THREAD

**Issue by hl2guide** [henrypp/simplewall#958]
The below highlighting makes more sense for people from Western countries:

![example](https://user-images.githubusercontent.com/17044982/122596877-dec05b80-d0ad-11eb-973a-997f4f1f5907.png)

Please consider it as a default based on language.

e.g.: Australia, England, America, Germany, France etc.

**Comment by phaolo2** [comment]
Ah, you swapped the colors for "Signed" and "Have network connections".
Why the first ones should be pink?

**Comment by hl2guide** [comment]
I consider "active" as green, does "signed" mean digitally signed?

This is just an example.

**Comment by Chaython** [comment]
> 
> 
> I consider "active" as green, does "signed" mean digitally signed?
> 
> This is just an example.

Yes, under rules: advanced you have to enable checking for signatures. But this can cause hard drives to spin up when scrolling the app list.
Digitally signed = more trustworthy, hence the green?
