### ISSUE TITLE
"Allow for 15 minutes / Allow until restart"

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#96]
Would you consider adding a split button for "Allow" in the notifications that allows a temporary allow for programs that won't be used afterwards, such as installers? This way, the split button context menu could include "Allow for 15 minutes", "Allow for 1 hour", "Allow until restart", for example. It allows the user to prevent clutter and less manual work of deleting them from the list later on. ("Purge invalid apps" is a manual task AND doesn't always help, because some (e.g. portable) programs create temporary files upon run that will be gone when closed. They'll turn up as "invalid", but should remain in the list for next time the application is run).

![splitbutton](https://user-images.githubusercontent.com/4777345/32992413-b594d660-cd4a-11e7-8c17-4a3cfa13c045.png)

**Comment by henrypp** [comment]
It's _temporary_ unavailable.

**Comment by ltGuillaume** [comment]
Haha cool, looking forward to its availability :P

**Comment by pwn0r** [comment]
LOL only my lazyness prevented me from opening the same issue :) It is one of the most important tinywall features I use on my other computer -- excellent for installations as almost every install now downloads some files.

**Comment by GitCurious** [comment]
A good suggestion - I also use this feature.

**Comment by henrypp** [comment]
What predefined timer values do you need, people?

**Comment by ltGuillaume** [comment]
I'd say 15min, 1h, until restart, as suggested. Maybe 2h could work for some.
