### ISSUE TITLE
GOG Galaxy 2.0 Impossible to Install

### ISSUE THREAD

**Issue by hl2guide** [henrypp/simplewall#960]
When using Simplewall it is impossible to install GOG Galaxy 2.0.

This seems to be since the GOG installer has no "retry" option and uses a temp file for the EXE that is unique each attempt.

**Comment by Chaython** [comment]
Ya it was annoying, only option is to temporarily disable simplewall, as simplewall will not use wildcards.
Lots of installers have this issue.
Anyways galaxy 2.0 is more unnecessary launcher bloat why do you want it.

**Comment by phaolo2** [comment]
> Ya it was annoying, only option is to temporarily disable simplewall, as simplewall will not use wildcards.
Not a great solution for a firewall, but better than nothing.
Did you mean right-click->Disable filters, right?

> Lots of installers have this issue.
Also, all the temp files don't get cleaned from the App list..

> Anyways galaxy 2.0 is more unnecessary launcher bloat why do you want it.
Eh, it's ok. It's useful for achievements at least.
