### ISSUE TITLE
Filters not enabeled on startup

### ISSUE THREAD

**Issue by fnordson** [henrypp/simplewall#962]
![grafik](https://user-images.githubusercontent.com/5624605/123510339-2d0bc680-d67b-11eb-84f0-65f6893c498f.png)

When I boot up Windows I'm in this state.  
Filters are not enabled.  
If I click on "enable filter" the popup asks me if I want to **disable** filters.  
Only if I hit "yes" the program gets that they are in fact disabled and allows me to enable them again. 

I re-installed the program already. No help. 

SW Version: 3.3.4 Release 64Bit
Win 10 Version: 20H2

**Comment by Chaython** [comment]
When you reinstalled did you delete your profile?
Try starting a new profile.

**Comment by henrypp** [comment]
I think this is UI bug.

Try check by some app which cannot allowed internet access, it will append into log if it is true.

**Comment by fnordson** [comment]
> 
> 
> I think this is UI bug.
> 
> Try...
> 
>     * ...check by some app which cannot allowed internet access, it will append into log if it is true.
> 
>     * ... press "Refresh" button.

"Refresh" does indeed fix it.

**Comment by henrypp** [comment]
fixed
