### ISSUE TITLE
My network randomly becomes unidentified 

### ISSUE THREAD

**Issue by phaolo2** [henrypp/simplewall#965]
Since I started using Simplewall, my network seems to randomly become "unidentified" and I have to restart my pc to make it work again.
Does anyone have a suggestion about what could cause this issue?
Also, I have the problem reported [here](https://github.com/henrypp/simplewall/issues/954)

(please don't close this thread, I need help!)

**Comment by henrypp** [comment]
To know what is "unidentified" mean i need get help from astral?

Same for #954

**Comment by phaolo2** [comment]
Can't you let other people reply, instead of closing everything? -_-
