### ISSUE TITLE
Windows' built in antivirus treats v. 3.3.5. as a virus

### ISSUE THREAD

**Issue by danieltuzes** [henrypp/simplewall#966]
Windows' built-in antivirus successfully prevents me from updating simplewall.
![Untitled](https://user-images.githubusercontent.com/6088393/124961059-ea4fd400-e014-11eb-9e02-52cf2a6964d2.png)

Do I need to manually whitelist this item? Or can this be solved on the dev side?

**Comment by henrypp** [comment]
> Do I need to manually whitelist this item?

Yes, simplewall downloads update and _trying_ to run it. It seems false-detection.

> Or can this be solved on the dev side?

Yes, maybe i will cut this feature in the next minor release.
