### ISSUE TITLE
Microsoft Defender flagged recent Simplewall update as a Trojan - is this a false positive?

### ISSUE THREAD

**Issue by motreo** [henrypp/simplewall#967]
When I restarted my computer Simplewall launched automatically (which I've set it to do). As soon as Simplewall finished launching, I received a notification (in Simplewall, not an external notification) telling me an update was available and asking me if I wanted to download it. I said yes, and as soon as I clicked install, Windows Defender notified me that a severe trojan threat was detected. The details for this are:

Detected: Trojan:Win32/Emali.A!cl
Affected items: C:\Users\name\AppData\Local\Temp\simplewall-simplewall-3.3.5.exe

The threat was supposedly quarantined and removed immediately. Full system scan in Windows Defender and a full scan in Malwarebytes both come back clean. Has this happened to anyone else? Is it a false positive?

**Comment by henrypp** [comment]
#966
