### ISSUE TITLE
Recent update (3.3.5) flagged by Windows Defender as a trojan - despite clean full system/offline scans by Windows Defender and Malwarebytes, I decided to dig through Windows Defender event logs and run Microsoft Safety Scanner. Numerous infected files have been flagged

### ISSUE THREAD

**Issue by motreo** [henrypp/simplewall#968]
I feel compelled to make a post about this in case other users have been affected by the same issue. I know other users have been receiving the same trojan warning from Windows Defender and some have been told the detection is likely a false flag. I have reason to believe this might not be the case. 

Windows Defender flagged a recent Simplewall update - simplewall-3.3.5.exe - as a trojan. Specifically Trojan:Win32/Emali.A!cl

When I attempted to update, the threat was quarantined by Windows Defender. I ran a full system scan, a custom scan of my temp folder, and a full offline scan with Windows defender, as well as a full system scan checking for rootkits with Malwarebytes. All came back clean. 

I still had a feeling something wasn't right, so I went digging in the Windows Defender event logs. There I saw a large number of events indicating that Windows Defender has been altered (event ID 5007) - more than what's been typical during previous Windows updates, which indicates potential tampering with Windows Defender by malware. I decided to run Microsoft Safety Scanner and sure enough, twenty five files have been flagged as infected (still waiting on the final report). Next I plan to run Microsoft's Malicious Software Removal Tool. 

My machine is hardened with various group policy changes to reduce the risk of malware and I have controlled folder access enabled as well. I'm 99% certain these infected files are a result of the recent Simplewall update. I haven't gotten to the bottom of the issue yet, but encourage anyone who received the same warning from Windows Defender to run Microsoft Safety Scanner.

**Update**

When the scan completed I received a popup saying no threats were detected. Before the scan completed about thirty files had been flagged as infected.

**Comment by henrypp** [comment]
#966
