### ISSUE TITLE
How do I run a Silent Installation?

### ISSUE THREAD

**Issue by Mannshoch** [henrypp/simplewall#972]
I wish to Install Simplewall silent. Is there any Argument to run the setup in that mode?

**Comment by henrypp** [comment]
https://github.com/henrypp/simplewall#command-line

**Comment by Mannshoch** [comment]
I meant the silent installation of the Setup.exe
Sorry for the inaccuracy

**Comment by henrypp** [comment]
https://lmgtfy.app/?q=how+to+silent+install+nsis%3F
