### ISSUE TITLE
how do i block rdp port 3389

### ISSUE THREAD

**Issue by selipat** [henrypp/simplewall#974]
I want to block several ports (3389, 443, 3306) for all ip addresses except those that I specify, how do I do this?
and I also remember that someone did it through a file profile_internal.xml can you tell me how to do this?

**Comment by selipat** [comment]
![image](https://user-images.githubusercontent.com/87475644/125783930-a8b10174-6024-446d-acef-c7a2e9da47a0.png)

**Comment by selipat** [comment]
I blocked port 3389, but the problem is that I cannot connect under my ip, tell me what I did wrong

**Comment by henrypp** [comment]
#935
