### ISSUE TITLE
What rules under System Rules should be enabled to use IPv6?

### ISSUE THREAD

**Issue by TontyTon** [henrypp/simplewall#975]
I was not using IPv6 for long time, but now I need to use it.
IPv6 work without SW, but it don't work with SW.
I want to know which rules under System Rules should be enabled to use IPv6.

I have enabled DHCP and IGMP, which others are required to use IPv6?

Thanks.

**Comment by Chaython** [comment]
What're you using IPV6 for?
It should work without configuration, you must allow the app/service that you want to connect....

**Comment by TontyTon** [comment]
@Chaython AFAIK, there are some connections between router and PC that needs to enabled to use IPv6.
For IPv4, DHCP is enough, but for IPv6 there are other things that needs to be enabled, but I don't know which ones.

**Comment by Chaython** [comment]
I want to say IPV6 was dependent on LLMNR. I am not sure though. LLMNR has man in the middle vulnerabilities though...
