### ISSUE TITLE
Exception at startup

### ISSUE THREAD

**Issue by LStandman** [henrypp/simplewall#976]
Hi,
I recently updated simplewall to 3.4. When I start up, I get an exception with the following message (verbatim):

> The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s. (0xC0000005)

Rolling back to 3.3.5 solves the problem for me.

Thanks,
LS

**Comment by henrypp** [comment]
can you drop crash dump (in profile directory) to my email and provide OS version

**Comment by LStandman** [comment]
Hi,
I forwarded the crash dump to your support [at] address.

RE: the supplementary info you requested:
> Edition	Windows 10 Pro N
> Version	20H2
> Installed on	‎07/‎03/‎2021
> OS build	19042.1165
> Experience	Windows Feature Experience Pack 120.2212.3530.0

Hope this helps,
LS

**Comment by henrypp** [comment]
32/64?

**Comment by LStandman** [comment]
> System type	64-bit operating system, x64-based processor

**Comment by noxepy** [comment]
Hi. I have same problem with version 3.4. Previous version work fine. My system Win10 LTSC 1809 x64.

**Comment by popdisk** [comment]
Same problem with version 3.4 at system startup, reinstall is useless.  Try downgrading to version 3.3.5, it works well again.

**Comment by EntropySmoke** [comment]
I have the same issue here (Windows 10 19041.1151). Can SimpleWall filter DLL files just by adding those DLL files to whichever rule? Log only shows EXE files.

**Comment by henrypp** [comment]
fixes

**Comment by henrypp** [comment]
@EntropySmoke 
> I have the same issue here

This is not the same issue and also this is not a issue.
