### ISSUE TITLE
Windows Defender picking up something

### ISSUE THREAD

**Issue by unusualgarment** [henrypp/simplewall#977]
Not sure if it's a false positive but when I check for updates and choose to install now, Windows Defender pops up telling me to remove it.

Trojan:Win32/Sabsik.FL.A!ml
Alert level: Severe
Status: Active
Date: Todays Date/Time
Category: Trojan
Details: This program is dangerous and executes commands from an attacker.

Affected items:
file: C:\Users\XXXXXX\AppData\Local\Temp\simplewall-simplewall-3.4.exe

I am on 3.3.4 currently.

**Comment by theDarkFrenchy** [comment]
I can report the exact same problem...  is it a problem of an Unsigned exe ??

**Comment by henrypp** [comment]
https://github.com/henrypp/simplewall/issues/966#issuecomment-876642799
