### ISSUE TITLE
Sorting Apps That Have Network Connections

### ISSUE THREAD

**Issue by vuslatx** [henrypp/simplewall#978]
I want to sort apps that have network connections. In the present case, i can only sort by name or added. Is there a setting I missed? If not, wouldn't it be better if it was? I think, it would be useful.

**Comment by cowsay1** [comment]
I have a suggestion here, it may be possible to make to show only one line for each process from the list, and when you click on [+] expand all connections of this process.

**Comment by Chaython** [comment]
> 
> 
> I have a suggestion here, it may be possible to make to show only one line for each process from the list, and when you click on [+] expand all connections of this process.

I asked for grouping before, for apps list, [like adobe has 50 apps lol] and Henry rejected it.




> I want to sort apps that have network connections. In the present case, i can only sort by name or added. Is there a setting I missed? If not, wouldn't it be better if it was? I think, it would be useful.
This seems to be a bug, previous versions I recall sorting by state.
