### ISSUE TITLE
No updates available in 3.4.0

### ISSUE THREAD

**Issue by Alcazer** [henrypp/simplewall#979]
Hi @henrypp.

Thanks for updating to version 3.4.1.

If you try to check for updates in 3.4.0, you get "No updates available".

Please update server version.

https://www.henrypp.org/product/simplewall
https://www.henrypp.org/update.php?product=simplewall
https://www.henrypp.org/update.php?product=simplewall&api=3
https://www.henrypp.org/update.php?product=simplewall&is_beta=1
https://www.henrypp.org/update.php?product=simplewall&is_beta=1&api=3

**Comment by henrypp** [comment]
Yes, i forgot. Fixed.

**Comment by Alcazer** [comment]
same in version 3.5
