### ISSUE TITLE
svchost???

### ISSUE THREAD

**Issue by privacyguy123** [henrypp/simplewall#980]
Can't get my head around this one as DNS (port 53) is allowed globally.

![image](https://user-images.githubusercontent.com/50337995/129571730-ed7d642c-425e-4dfc-bb9b-dd1d2fe39704.png)

**Comment by privacyguy123** [comment]
Also this is a new bug

![image](https://user-images.githubusercontent.com/50337995/129573007-2bc4cfd3-ab1b-49a0-ba7c-10f118ebc615.png)

**Comment by Chaython** [comment]
Block svchost, unless you're dependent on it. [Certain xbox services].
SVChost is used for DNS queries, but if the port is open, all queries will work regardless.

**Comment by privacyguy123** [comment]
> 
> 
> Block svchost, unless you're dependent on it. [Certain xbox services].
> SVChost is used for DNS queries, but if the port is open, all queries will work regardless.

Thats what I'm saying - port 53 is allowed globally so I can't understand this request.

**Comment by Chaython** [comment]
Each app on first run asks for permission, regardless of if they use the port or not.
It's only on first action, if denied, it never shows up again.
Could be split tunneling, or it's requesting DNS records from your modem.

**Comment by privacyguy123** [comment]
Is this a bug or working as intended then? Is Split Tunnelling working with svchost blocked?

**Comment by Chaython** [comment]
If you block it, then it's moved to Apps without internet access. As intended.
IDK what's necessary for split tunneling. I recommend against split tunneling. https://github.com/henrypp/simplewall/issues/986#issuecomment-900921943

**Comment by cowsay1** [comment]
I disabled global system DNS rule and created a DNS client rule for svchost with only known DNS server IPs that I am using, eg

1.1.1.1:53
1.0.0.1:53
10.2.0.1:53

it simply protects from any unlisted app to make connections using dns tunnels https://www.hhs.gov/sites/default/files/acd-dns-tunneling.pdf

**Comment by henrypp** [comment]
> Can't get my head around this one as DNS (port 53) is allowed globally.

simplewall has 2 rules named dns (1 system and 1 user) for connect (outbound) to dns server, but svchosts is trying to make recv/accept operation which means this is inbound.

I think notification is displays a little bit incorrect direction ;)

**Comment by RikisX** [comment]
#945
