### ISSUE TITLE
kernel32.dll error on Win7

### ISSUE THREAD

**Issue by eccebae** [henrypp/simplewall#981]
It doesn't start.

See the attchments.
![KakaoTalk_20210816_163027299](https://user-images.githubusercontent.com/89035597/129602199-f76233b6-de4b-4afb-b841-5810c33f7b4c.png)
![KakaoTalk_20210816_163022478](https://user-images.githubusercontent.com/89035597/129602211-862e31ad-e024-4bee-b9a7-036b4841c70f.png)

**Comment by henrypp** [comment]
Update Windows maybe?

**Comment by henrypp** [comment]
https://support.microsoft.com/kb/2533623
