### ISSUE TITLE
Missing tray icon on minimized

### ISSUE THREAD

**Issue by raycheung** [henrypp/simplewall#985]
I experience missing tray icon problem since 3.4.0 (and see the same with 3.4.1) on my Windows 10. I've tried to "Reset" in the config but still the same. Is there anything I should look into fixing it please?

**Comment by henrypp** [comment]
Ok, i take a look

**Comment by Chaython** [comment]
> 
> 
> I experience missing tray icon problem since 3.4.0 (and see the same with 3.4.1) on my Windows 10. I've tried to "Reset" in the config but still the same. Is there anything I should look into fixing it please?

Is it displayed in your taskbar settings?
Is it installed or portable?
Is the app actually running, check task manager?
The 2 newest releases crash with my profile. Also filtering in the connections tab by state no longer works. The corner overflow icon is only missing when the app had crashed.

**Comment by howyay** [comment]
I was able to produce with the scoop package simplewall, with the exact same symptoms as described

**Comment by raycheung** [comment]
> 
> 
> > I experience missing tray icon problem since 3.4.0 (and see the same with 3.4.1) on my Windows 10. I've tried to "Reset" in the config but still the same. Is there anything I should look into fixing it please?
> 
> Is it displayed in your taskbar settings?
> Is it installed or portable?
> Is the app actually running, check task manager?
> The 2 newest releases crash with my profile. Also filtering in the connections tab by state no longer works. The corner overflow icon is only missing when the app had crashed.

Not in taskbar settings, if so it'd rather be a Windows issue.
Installed via scoop just like @howyay , not certain if that makes a different. Tried with scoop installed 3.4 then in-app upgrade to 3.4.1, as well as a clean install of 3.4.1 via scoop; both behaved the same.
And surely, the simplewall.exe appears in task manager. It's minimized to oblivion, not quit.

**Comment by henrypp** [comment]
@raycheung 

Can you start simplewall from another location? Tray icon displays?

Just change directory, like %ProgramFiles%\simplewall and start exe.

**Comment by raycheung** [comment]
> 
> 
> @raycheung
> 
> Can you start simplewall from another location? Tray icon displays?
> 
> Just change directory, like %ProgramFiles%\simplewall and start exe.

Genius! Placing simplewall.exe at `%ProgramFiles%\simplewall` works perfectly.

**Comment by henrypp** [comment]
@raycheung 

>Genius! Placing simplewall.exe at %ProgramFiles%\simplewall works perfectly.

And where it is before?

**Comment by raycheung** [comment]
> 
> 
> @raycheung
> 
> > Genius! Placing simplewall.exe at %ProgramFiles%\simplewall works perfectly.
> 
> And where it is before?

@henrypp Thank you so much for the hint. Not an issue of simplewall per se.
I found that as long as the simplewall.exe being in a symlinked folder, the tray icon doesn't show.
However even if the simplewall.exe is in the absurd %USERPROFILE%\scoop\apps\simplewall\3.4.1, it works fine.

That is, starting through %USERPROFILE%\scoop\apps\simplewall\current which is a link to %USERPROFILE%\scoop\apps\simplewall\3.4.1, it doesn't work.

I think we can close this ticket if there is no intention to resolve this compatibility with scoop installation.

**Comment by Xelbayria** [comment]
> @henrypp Thank you so much for the hint. Not an issue of simplewall per se.
I found that as long as the simplewall.exe being in a symlinked folder, the tray icon doesn't show.
However even if the simplewall.exe is in the absurd %USERPROFILE%\scoop\apps\simplewall\3.4.1, it works fine.
>That is, starting through %USERPROFILE%\scoop\apps\simplewall\current which is a link to %USERPROFILE%\scoop\apps\simplewall\3.4.1, it doesn't work.
>I think we can close this ticket if there is no intention to resolve this compatibility with scoop installation.

I'm curious. Did you find another way to make it work?

**Comment by raycheung** [comment]
> > @henrypp Thank you so much for the hint. Not an issue of simplewall per se.
> > I found that as long as the simplewall.exe being in a symlinked folder, the tray icon doesn't show.
> > However even if the simplewall.exe is in the absurd %USERPROFILE%\scoop\apps\simplewall\3.4.1, it works fine.
> > That is, starting through %USERPROFILE%\scoop\apps\simplewall\current which is a link to %USERPROFILE%\scoop\apps\simplewall\3.4.1, it doesn't work.
> > I think we can close this ticket if there is no intention to resolve this compatibility with scoop installation.
> 
> I'm curious. Did you find another way to make it work?

I don't experience this issue any more installing simplewall 3.6.6 through scoop. It has been awesome.

**Comment by Xelbayria** [comment]
> I don't experience this issue any more installing simplewall 3.6.6 through scoop. It has been awesome.

I see. I actually have experienced the same issue mentioned above. I am just wondering if there is a solution to fix that.

**Comment by Xelbayria** [comment]
I cannot find a solution to fix my issue where I couldn't see the minimized tray icon. I installed the `Simplewall v3.6.6` via Scoop. I want to know is there a solution for this?

**Comment by brian6932** [comment]
This is still an issue

**Comment by Xelbayria** [comment]
> This is still an issue

Are u using the latest version of Simplewall, if not, then update to the latest version.  I no longer have this issue anymore due to latest version.

**Comment by brian6932** [comment]
I am on latest, sometimes there is no tray icon

**Comment by Xelbayria** [comment]
> I am on latest, sometimes there is no tray icon

strange. What about your OS? are you also using the latest Windows 10 or different OS?

**Comment by brian6932** [comment]
> strange. What about your OS? are you also using the latest Windows 10 or different OS?

Happens on both Windows 10 and 11, start minimzed disabled

**Comment by Xelbayria** [comment]
I thought so. quoting ur 

> I couldn't see the minimized tray icon. 

and 

 > Happens on both Windows 10 and 11, start minimzed disabled

------------------------------------------------->☝️☝️☝️☝️☝️ 
this one is why you can't see minimized tray icon... So you need to enable start minimized so you can see it in the tray icon. if it's disabled, then it will be hidden while the simplewall is running. If you check task manager, then you should able to find "simplewall.exe" running. Let me know if enabling it solve your problem.
