### ISSUE TITLE
v3.4.x misses many blocked connections

### ISSUE THREAD

**Issue by ltGuillaume** [henrypp/simplewall#989]
Since v3.4.x simplewall started missing many blocked connections again: no popup was shown, no blocked connection entry was saved in the log. Seems to happen all the time.

I restarted 3.4.1 many times to try to get the popup, or at least the log entry, but got nothing.
With the exact same profile, downgrading to v3.3.5 resolved the issue immediately.

Win10 x64
simplewall 3.4.1

**Comment by ViRb3** [comment]
I am having the same issue. I don't get any blocked connection prompts, so all programs are silently denied. Sometimes the prompt shows up after a few minutes, even if the program is no longer running. Downgrading to v3.3.5 immediately solved this issue. The program I last tested was a Go compiled binary from JetBrains GoLand which is located in: `C:\Users\USER\AppData\Local\Temp\___default.exe`

**Comment by henrypp** [comment]
> Since v3.4.x simplewall started missing many blocked connections again: no popup was shown, no blocked connection entry was saved in the log. Seems to happen all the time.

Debug log?

**Comment by ltGuillaume** [comment]
This seems to be fixed with v3.4.2, I'll close it for now and reopen if I find there are still problems.

The instant popup is soooo much nicer, too, thank you for this!

**Comment by ViRb3** [comment]
I can also confirm that the issue is fixed in v3.4.2, and the new popup is MUCH faster than ever before, it's literally instant. Thank you!
