### ISSUE TITLE
simplewall not asking anymore to disable Windows Firewall?

### ISSUE THREAD

**Issue by eggplanting** [henrypp/simplewall#993]
I'm using simplewall since years and every time I enabled filters, simplewall asked me to disable Windows Firewall.
With the latest release 3.4.1 this isn't the case anymore.

Any reason for that, is disabling Windows Firewall not needed anymore?

Best regards

**Comment by henrypp** [comment]
https://github.com/henrypp/simplewall#q-is-it-safe-to-use-simplewall-with-windows-firewall
