### ISSUE TITLE
Rules that do not seem to be used

### ISSUE THREAD

**Issue by swirti** [henrypp/simplewall#994]
rules that are overwritten by an internal rule
For some applications like msedge.exe or svchost.exe, I created a rule allowing outgoing UDP port 5353 connection.
However, every 10 seconds I get a popup asking me to allow UDP port 5353 connection. The filter seems to be InternalBlockRecvAccept. How can I fix this problem ? It is the same for other rules like IGMP outbound for local machines.
If I create a rule allowing a certain connection for an application but there is an internal rule prohibiting that same connection, how do I allow that connection only without allowing everything for the application concerned?

**Comment by popdisk** [comment]
It seems a bug. Something with priority override the custom rule, which makes what you created take no effect.

**Comment by henrypp** [comment]
> I created a rule allowing outgoing UDP port 5353 connection.
>However, every 10 seconds I get a popup asking me to allow UDP port 5353 connection.

Maybe problem in rule?

**Comment by popdisk** [comment]
#945 has been fixed. I found it maybe just display the wrong direction which also caused the wrong direction in custom rule generation.
