### ISSUE TITLE
3.4.1 - Random crash while browsing the web

### ISSUE THREAD

**Issue by Dark-Noir** [henrypp/simplewall#995]
Hey,
i updated to 3.4.1 yesterday, today i got a crash while browsing the web.

> Einem Dienst oder einer Funktion wurde ein ungültiger Parameter übergeben. (0xC000000D)

Windows event report:
> Name der fehlerhaften Anwendung: simplewall.exe, Version: 3.4.1.0, Zeitstempel: 0x57f92f12
> Name des fehlerhaften Moduls: ntdll.dll, Version: 10.0.19041.1110, Zeitstempel: 0xe7a22463
> Ausnahmecode: 0xc000000d
> Fehleroffset: 0x0000000000112234
> ID des fehlerhaften Prozesses: 0x4b68
> Startzeit der fehlerhaften Anwendung: 0x01d79851c91a9bec
> Pfad der fehlerhaften Anwendung: C:\Program Files\simplewall\simplewall.exe
> Pfad des fehlerhaften Moduls: C:\Windows\SYSTEM32\ntdll.dll
> Berichtskennung: c9f47623-3f0b-422b-adc9-c9d16fb2e427
> Vollständiger Name des fehlerhaften Pakets: 
> Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

**Comment by henrypp** [comment]
Can you send crash dump to my email?

**Comment by Dark-Noir** [comment]
> 
> 
> Can you send crash dump to my email?

No problem, i sent it.

**Comment by henrypp** [comment]
> No problem, i sent it.

3.4.2 was released, but i did not investigate this issue. If you face it again, please send crash dump to my email again.

**Comment by sieveLau** [comment]
Have the same issue, and manually starting it gives no difference.
Tried 3.4 and 3.4.2, both crashed. 3.3.5 is good.

**Comment by henrypp** [comment]
@Dark-Noir no more 0xC0000005?

**Comment by fnordson** [comment]
![grafik](https://user-images.githubusercontent.com/5624605/131249007-a149c591-7bbc-4f28-9f1d-4e4421aba0ca.png)

Getting this with 3.4.2. on startup.

**Comment by henrypp** [comment]
@fnordson send crash dump to my email

**Comment by Dark-Noir** [comment]
> @Dark-Noir no more 0xC0000005?

Didn't saw any since I changed the executable 👍

**Comment by fnordson** [comment]
> 
> 
> @fnordson send crash dump to my email

Would love to but what is it?  
Couldn't find it on your page.

**Comment by henrypp** [comment]
Issue was fixed.

@fnordson if you face it again, send it to my email support [at] henrypp [dot] org
