### ISSUE TITLE
Portable version downloads and installs the setup version

### ISSUE THREAD

**Issue by super-lurker** [henrypp/simplewall#996]
Portable version downloads and installs the setup verion on the lastest update. wat

**Comment by henrypp** [comment]
wat

**Comment by super-lurker** [comment]
wat 
![sshot-2021-08-24-22-39-17](https://user-images.githubusercontent.com/13076066/130636994-8e7a7b36-caf8-414c-8575-15f462b91c61.png)
![sshot-2021-08-24-22-39-33](https://user-images.githubusercontent.com/13076066/130636998-53dee1d5-c98b-43d6-a927-4c69ef5e1f94.png)

**Comment by reddyshyam** [comment]
Even installed version goes through setup. I don't remember doing this before.

**Comment by henrypp** [comment]
Correct, that is how auto-update works.
