### ISSUE TITLE
Auto-update Fails

### ISSUE THREAD

**Issue by whitetuna1** [henrypp/simplewall#997]
Upon receiving notification of a new version being available, the Install Now option doesn't work. The dialog remains.
The install exe file isn't downloaded to the designated temp folder within the Users folder, and an error reports the file can't be found.

Checking for updates manually and initiating works as expected.
This is occurring with the installed version on Windows 10, both Home and Pro. (portable version not tested)

Thanks.

**Comment by whitetuna1** [comment]
Message attached.
![message](https://user-images.githubusercontent.com/225023/130706614-8e3818f4-ed45-4cf9-b827-ae1aaceaae47.gif)

**Comment by whitetuna1** [comment]
![message](https://user-images.githubusercontent.com/225023/130706866-635dea41-1712-4fa8-9e22-5cc98a716e4f.gif)

**Comment by henrypp** [comment]
dup #1016
