### ISSUE TITLE
Missing: Disable Windows Firewall Checkbox

### ISSUE THREAD

**Issue by musicguru** [henrypp/simplewall#998]
Hello!

Since i updatet simplewall i´m missing the checkbox to disable (or enable) windows firewall.
I googled this random picture to show the checkbox: [Checkbox-img](https://technicalustad.com/wp-content/uploads/2020/10/What-is-The-Difference-Between-Firewall-and-Antivirus-5.jpg) 

With v.3.3.5 the checkbox is available....v4.x it seems to be gone.
I tried that on 2 workstations. Windows 10 x64.

Thanks!
Regards

**Comment by henrypp** [comment]
#993

**Comment by musicguru** [comment]
https://github.com/henrypp/simplewall/wiki/FAQ
vs.
https://github.com/henrypp/simplewall#q-is-it-safe-to-use-simplewall-with-windows-firewall
???

**Comment by musicguru** [comment]
*push*
1 https://github.com/henrypp/simplewall/wiki/FAQ 
"...but Windows Firewall filters have high priority and processed first, thats why you need disable Windows Firewall."

2 https://github.com/henrypp/simplewall#q-is-it-safe-to-use-simplewall-with-windows-firewall
"Yes. You do not need to disable Windows Firewall. This two firewall works independently."

So the checkbox does not come back?
How should we understand that? What has changed since v.3.3.5?
