### ISSUE TITLE
Questions about the project's future and repository archival

### ISSUE THREAD

**Issue by ghost** [henrypp/simplewall#999]
Hello, I noticed that for 2 or 3 weeks, this repo was archived with no word from anyone in charge.

---

Is there any reason for this?

Is that going to be common practice going forward when no progress is made for some time?

When you finally decide to put this project behind you, should the users expect any kind of notice?

If so, do you anticipate a notice will be given in advance, or to apply immediately?

Are you currently losing interest in this project?

---

When the repository was archived, users were not able to communicate about the future of simplewall, and discussions took place in a disorganized way across Reddit and other channels. If you are losing interest, leaving the repo open for a few weeks would allow for an organized and peaceful migration.

Thank you for your work!

**Comment by Chaython** [comment]
There's little third party contribution, and most issues created are not considered issues to him. So many duplicate issues etc.
I assume he wanted a break from the spam.
I also think this is only open source to find users, as it was the only FOSS firewall GUI app for windows[?].
